import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {AccountOpeningReview,AccountOpeningWorkspace} from '@/components/financial/AccountOpeningReview';
import {AccountOpeningRejectedError} from '@/lib/financial/accountOpeningClient';
const mock=vi.hoisted(()=>({read:vi.fn(),evidence:vi.fn(),record:vi.fn(),reverse:vi.fn(),account:vi.fn()}));
vi.mock('@/lib/financial/accountOpeningClient',()=>({readAccountOpening:mock.read,recordAccountOpening:mock.record,reverseAccountOpening:mock.reverse,AccountOpeningRejectedError:class extends Error{}}));
vi.mock('@/lib/financial/cashOpeningClient',()=>({readOpeningAccount:mock.account,recordCashOpening:vi.fn()}));
vi.mock('@/lib/financial/periodEvidenceClient',()=>({readPeriodEvidence:mock.evidence}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),opening=crypto.randomUUID(),key=`finance-account-opening:${tenant}:${actor}:${account}`;
const context={version:1,tenant_id:tenant,account_id:account,from:'2026-01-02',to:'2026-01-31',opening:null,book:null,history:[],can_close:false};
const evidence={revision:'revision-one',opening_balance_cents:'-1200',arithmetic_status:'equal',anchors:[{verification_id:crypto.randomUUID(),file_name:'extrato.ofx',day:'2026-01-01',cents:'-1200',offset_minutes:-180}]};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.account.mockResolvedValue({id:account,tenant_id:tenant,name:'Banco QA',account_type:'checking',active:true});mock.read.mockResolvedValue(context);mock.evidence.mockResolvedValue(evidence);mock.record.mockResolvedValue({});mock.reverse.mockResolvedValue({});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(from='2026-01-02',cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><AccountOpeningWorkspace tenant={tenant} actor={actor} account={account} from={from} to="2026-01-31"/></QueryClientProvider>);}
async function review(){fireEvent.change(await screen.findByLabelText('Motivo da abertura ou correção'),{target:{value:'Âncora conferida no extrato original'}});fireEvent.click(screen.getByRole('button',{name:'Revisar abertura ou correção'}));}
it('reviews anchor and effective date without an editable amount, then recovers the original period after lost reply',async()=>{
 mock.record.mockRejectedValueOnce(new Error('timeout'));const view=open();await review();expect(screen.getByText(/Saldo de 2026-01-01/)).toHaveTextContent('-R$ 12,00');expect(screen.queryByRole('spinbutton')).not.toBeInTheDocument();expect(mock.record).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar abertura ou correção'}));await screen.findByRole('alert');const original=mock.record.mock.calls[0][0];expect(original).toMatchObject({from:'2026-01-02',revision:'revision-one'});expect(original).not.toHaveProperty('balance_cents');
 view.unmount();open('2026-01-10');fireEvent.click(screen.getByRole('button',{name:'Retomar pedido de abertura'}));await waitFor(()=>expect(mock.record).toHaveBeenCalledTimes(2));expect(mock.record.mock.calls[1][0]).toEqual(original);expect(sessionStorage.getItem(key)).toBeNull();
});
it('preserves correction replay and displays who changed the opening',async()=>{
 const item={id:opening,effective_from:'2026-01-02',balance_cents:'-1200',actor_id:actor,actor_name:'Ana Financeiro',reason:'Abertura original',created_at:'2026-01-02T12:00:00Z',reversal:null};mock.read.mockResolvedValue({...context,opening:{...item,evidence_status:'requires_review'},history:[item]});mock.reverse.mockRejectedValueOnce(new Error('timeout'));const view=open();fireEvent.click(await screen.findByRole('button',{name:'Corrigir esta abertura'}));await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar abertura ou correção'}));await waitFor(()=>expect(mock.reverse).toHaveBeenCalledTimes(1));const original=mock.reverse.mock.calls[0][0];view.unmount();mock.read.mockResolvedValue({...context,history:[{...item,reversal:{id:crypto.randomUUID(),actor_id:actor,actor_name:'Gestor Paulo',reason:'Data incorreta',created_at:'2026-01-03T12:00:00Z'}}]});open();fireEvent.click(screen.getByRole('button',{name:'Retomar pedido de abertura'}));await waitFor(()=>expect(mock.reverse).toHaveBeenCalledTimes(2));expect(mock.reverse.mock.calls[1][0]).toEqual(original);expect(await screen.findByText(/Desfeita por Gestor Paulo/)).toBeInTheDocument();expect(screen.getByText(/Abertura manual · Desfeita/)).toBeInTheDocument();
});
it('blocks corrupt storage and missing eligible Brasília anchor',async()=>{
 sessionStorage.setItem(key,'invalid');const view=open();expect(await screen.findByRole('alert')).toHaveTextContent('Novos envios estão bloqueados');await screen.findByLabelText('Motivo da abertura ou correção');expect(screen.getByRole('button',{name:'Revisar abertura ou correção'})).toBeDisabled();view.unmount();sessionStorage.clear();mock.evidence.mockResolvedValue({...evidence,anchors:[{...evidence.anchors[0],offset_minutes:0}]});open();expect(await screen.findByText(/Sem âncora elegível/)).toBeInTheDocument();expect(screen.queryByLabelText('Motivo da abertura ou correção')).not.toBeInTheDocument();expect(mock.record).not.toHaveBeenCalled();
});
it('blocks a reviewed opening when evidence revision changes and preserves uncertain requests after known rejection',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});const view=open('2026-01-02',cache);await review();mock.evidence.mockResolvedValue({...evidence,revision:'revision-two'});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-period-evidence']});});await waitFor(()=>expect(screen.getByRole('button',{name:'Confirmar abertura ou correção'})).toBeDisabled());view.unmount();
 const original={kind:'record',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),account_id:account,from:'2026-01-02',to:'2026-01-31',revision:'revision-one',reason:'Pedido enviado anteriormente'}};sessionStorage.setItem(key,JSON.stringify({actor,account,pending:original}));mock.record.mockRejectedValueOnce(new AccountOpeningRejectedError('finance_opening_evidence_changed'));open();fireEvent.click(screen.getByRole('button',{name:'Retomar pedido de abertura'}));expect(await screen.findByRole('alert')).toHaveTextContent('preservado para retomada');expect(JSON.parse(sessionStorage.getItem(key)!).pending).toEqual(original);
});
it('blocks unavailable recovery storage and releases a known first-attempt rejection',async()=>{
 const view=open();await review();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('full');});fireEvent.click(screen.getByRole('button',{name:'Confirmar abertura ou correção'}));expect(await screen.findByRole('alert')).toHaveTextContent('Nenhuma abertura ou correção foi enviada');expect(mock.record).not.toHaveBeenCalled();view.unmount();vi.restoreAllMocks();mock.account.mockResolvedValue({id:account,tenant_id:tenant,name:'Banco QA',account_type:'checking',active:true});mock.read.mockResolvedValue(context);mock.evidence.mockResolvedValue(evidence);mock.record.mockRejectedValueOnce(new AccountOpeningRejectedError('finance_opening_evidence_changed'));open();await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar abertura ou correção'}));expect(await screen.findByRole('alert')).toHaveTextContent('As evidências mudaram');expect(sessionStorage.getItem(key)).toBeNull();await screen.findByRole('button',{name:'Revisar abertura ou correção'});
});
it('checks every opening-day timezone but does not require consistent closing anchors',async()=>{
 mock.evidence.mockResolvedValue({...evidence,anchors:[...evidence.anchors,{...evidence.anchors[0],verification_id:crypto.randomUUID(),offset_minutes:0}]});const view=open();expect(await screen.findByText(/Sem âncora elegível/)).toBeInTheDocument();expect(screen.getByText(/fuso incompatível/)).toBeInTheDocument();expect(screen.queryByLabelText('Motivo da abertura ou correção')).not.toBeInTheDocument();view.unmount();
 mock.evidence.mockResolvedValue({...evidence,arithmetic_status:'conflicting_anchors',anchors:[...evidence.anchors,{verification_id:crypto.randomUUID(),file_name:'outro.ofx',day:'2026-01-31',cents:'9999',offset_minutes:-180}]});open();await review();expect(screen.getByRole('button',{name:'Confirmar abertura ou correção'})).toBeEnabled();
});
it('keeps pending commands isolated when switching account and restores only the original account',async()=>{
 const otherAccount=crypto.randomUUID(),cache=new QueryClient({defaultOptions:{queries:{retry:false}}});mock.record.mockRejectedValueOnce(new Error('timeout'));
 const panel=(id:string)=><QueryClientProvider client={cache}><AccountOpeningReview tenant={tenant} actor={actor} account={id} from="2026-01-02" to="2026-01-31"/></QueryClientProvider>;
 const view=render(panel(account));fireEvent.click(screen.getByRole('button',{name:'Consultar abertura da conta'}));await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar abertura ou correção'}));await screen.findByRole('alert');const original=mock.record.mock.calls[0][0];view.rerender(panel(otherAccount));await screen.findByLabelText('Motivo da abertura ou correção');expect(screen.queryByRole('button',{name:'Retomar pedido de abertura'})).not.toBeInTheDocument();expect(JSON.parse(sessionStorage.getItem(key)!).pending.command).toEqual(original);expect(mock.read).toHaveBeenCalledWith(tenant,otherAccount,'2026-01-02','2026-01-31');
 view.rerender(panel(account));fireEvent.click(screen.getByRole('button',{name:'Retomar pedido de abertura'}));await waitFor(()=>expect(mock.record).toHaveBeenCalledTimes(2));expect(mock.record.mock.calls[1][0]).toEqual(original);
});
it('shows invalidated evidence warning and does not manufacture a book balance before the cutoff',async()=>{
 const item={id:opening,effective_from:'2026-01-10',balance_cents:'-1200',actor_id:actor,actor_name:'Financeiro QA',reason:'Corte conferido',created_at:'2026-01-10T12:00:00Z'};mock.read.mockResolvedValue({...context,opening:{...item,evidence_status:'requires_review'},book:null,history:[{...item,reversal:null}]});open();expect(await screen.findByRole('alert')).toHaveTextContent('evidência da abertura mudou');expect(screen.getByText(/período começa antes do corte/)).toBeInTheDocument();expect(screen.queryByText('Saldo final dos registros')).not.toBeInTheDocument();
});
