import {cleanup,render,screen} from '@testing-library/react';
import {afterEach,it,expect} from 'vitest';
import {buildAccountPeriodEvidenceIndex} from '@/lib/financial/accountPeriodEvidenceIndex';
import {accountPeriodEvidenceSchema,exportAccountPeriodEvidence} from '@/lib/financial/accountPeriodEvidenceContract';
import {AccountPeriodEvidenceIndexPanel} from '@/components/financial/AccountPeriodEvidenceIndexPanel';
const id=()=>crypto.randomUUID();
function fixture(){const movement=id(),actor=id(),event={id:id(),movement_id:movement,actor_id:actor,actor_name:'Maria preservada',reason:'Registro duplicado conferido',created_at:'2026-09-10T15:00:00Z',duplicate_of_movement_id:id(),replacement_movement_id:null};return {movement,event,data:accountPeriodEvidenceSchema.parse({version:1,tenant_id:id(),account_id:id(),closure_id:id(),closure:{from:'2026-08-01',to:'2026-08-31',revision:'a'.repeat(32),actor_id:id(),actor_name:'Financeiro',reason:'Conferência dos valores',created_at:'2026-09-01'},snapshot:{balances:{recorded_out_cents:'50000'},facts:{movements:[],movement_voids:[event],voided_movements:[{id:movement,amount_cents:50000,receipt_path:'original.pdf',receipt_evidence:{bucket:'receipts'}}],groups:[],group_reversals:[],opening_imports:[]},coverage:{dependencies:{imports:[]}}},dependencies:[],integrity:{snapshot_matches_revision:true,dependencies_match:true},reopening:null})};}
afterEach(cleanup);
it('indexes invalidation and original receipt without rewriting saved balances or export',()=>{const {data,event,movement}=fixture(),before=exportAccountPeriodEvidence(data),index=buildAccountPeriodEvidenceIndex(data);expect(index.manual_decisions).toContainEqual({...event,kind:'movement_void',active:true});expect(index.documents).toContainEqual({kind:'voided_movement_receipt',source_id:movement,path:'original.pdf',evidence:{bucket:'receipts'}});expect(index.coverage_issues).toEqual([]);expect(exportAccountPeriodEvidence(data)).toBe(before);expect((data.snapshot.balances as Record<string,unknown>).recorded_out_cents).toBe('50000');});
it('shows actor reason and linked IDs as invalidation rather than reconciliation reversal',()=>{const {data,event,movement}=fixture();render(<AccountPeriodEvidenceIndexPanel data={data}/>);expect(screen.getByText(/Invalidação manual de movimento/)).toBeInTheDocument();expect(screen.getByText(/Original excluído dos valores ativos/)).toBeInTheDocument();expect(screen.getByText(new RegExp(event.actor_id))).toBeInTheDocument();expect(screen.getByText('Motivo: Registro duplicado conferido')).toBeInTheDocument();expect(screen.getByText(`Movimento original: ${movement}`)).toBeInTheDocument();expect(screen.getByText(`Duplicidade do movimento: ${event.duplicate_of_movement_id}`)).toBeInTheDocument();expect(screen.getByText('Comprovante do original invalidado — fora dos valores ativos')).toBeInTheDocument();});
it('accepts old snapshots without new fields and diagnoses partial or contradictory new history',()=>{const {data,movement}=fixture();const facts=data.snapshot.facts as Record<string,unknown>;delete facts.movement_voids;delete facts.voided_movements;expect(buildAccountPeriodEvidenceIndex(data).coverage_issues).toEqual([]);facts.voided_movements=[{id:movement}];expect(buildAccountPeriodEvidenceIndex(data).coverage_issues).toContain('Invalidações de movimentos: conjunto preservado indisponível.');facts.movements=[{id:movement,receipt_path:null}];expect(buildAccountPeriodEvidenceIndex(data).coverage_issues).toContain(`Movimento presente como ativo e invalidado: ${movement}.`);});

it('flags incomplete voided receipt metadata without adding an active missing-receipt obligation',()=>{const {data,movement}=fixture();(data.snapshot.facts as Record<string,unknown>).voided_movements=[{id:movement,receipt_path:'original.pdf'}];const index=buildAccountPeriodEvidenceIndex(data);expect(index.coverage_issues).toContain(`Comprovante do original invalidado sem metadados preservados: ${movement}.`);expect(index.missing_movement_receipt_ids).toEqual([]);expect(index.documents).toContainEqual({kind:'voided_movement_receipt',source_id:movement,path:'original.pdf',evidence:null});});
