// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createAccountPeriodCloseDatabase} from './helpers/accountPeriodCloseDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {financeError} from '@/lib/financial/ledgerContract';
import {accountPeriodHistorySchema} from '@/lib/financial/accountPeriodCloseContract';
let db:Awaited<ReturnType<typeof createAccountPeriodCloseDatabase>>;
beforeAll(async()=>{db=await createAccountPeriodCloseDatabase();for(const file of ['20260910164256_finance_account_period_history.sql','20260910164923_finance_account_period_closure_evidence.sql','20260910165830_finance_period_manual_audit.sql'])await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});
afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function history(offset=0,limit=30){return accountPeriodHistorySchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_account_period_history($1,$2,$3,$4) v',[i.tenant,i.account,offset,limit])).rows[0].v);}
// Historical fixtures prove reading/reopening history, not positive eligibility.
async function fixtures(){const opening=randomUUID(),first=randomUUID(),second=randomUUID();await db.query("insert into finance_account_openings(id,tenant_id,bank_account_id,effective_from,balance_cents,evidence_to,evidence,actor_id,actor_name,reason) values($1,$2,$3,'2026-08-01',10000,'2026-07-31','{}',$4,'QA','Abertura histórica fixture')",[opening,i.tenant,i.account,i.operator]);
 for(const [id,from,to,parent] of [[first,'2026-08-01','2026-08-31',null],[second,'2026-09-01','2026-09-02',first]]){const request=randomUUID();await db.query("insert into finance_private.account_close_write_tickets values(txid_current(),$1,$2,$3,'finance_account_period_closures')",[i.tenant,request,i.operator]);await db.query("insert into finance_account_period_closures(id,tenant_id,account_id,period_start,period_end,opening_id,predecessor_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'QA','Fechamento histórico fixture',$11)",[id,i.tenant,i.account,from,to,opening,parent,{balances:{opening_cents:'10000',closing_cents:'10000'}},'a'.repeat(32),i.operator,request]);}return{first,second};}
it('returns full counts with paginated history and blocks reopening predecessors',async()=>{const ids=await fixtures();const page=await history(0,1);expect(page.total_count).toBe(2);expect(page.items).toHaveLength(1);expect(page.items[0]).toMatchObject({id:ids.second,active:true,can_reopen:true});expect((await history(1,1)).items[0]).toMatchObject({id:ids.first,can_reopen:false,active_descendant_ids:[ids.second]});expect((await history(2,1)).items).toEqual([]);});
it('preserves manual actor/reason and unlocks predecessor only after real reopen command',async()=>{const ids=await fixtures();const reason='Reabrir para corrigir evidência identificada';await financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:ids.second,revision:'a'.repeat(32),reason}]);const result=await history();expect(result.items[0]).toMatchObject({id:ids.second,active:false,can_reopen:false,reopening:{actor_id:i.operator,reason}});expect(result.items[1].can_reopen).toBe(true);await db.query("update tenant_memberships set role='operator' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);expect((await history()).items.every(x=>!x.can_reopen)).toBe(true);});
it('denies driver and invalid paging and explains a frozen period without suggesting date changes',async()=>{await expect(financeAs(db,i.driverUser,'select get_finance_account_period_history($1,$2)',[i.tenant,i.account])).rejects.toThrow('finance_access_denied');await expect(history(-1)).rejects.toThrow('finance_invalid_filters');expect(financeError(new Error('finance_account_period_closed'))).toContain('reabertura');});
it('returns preserved evidence with explicit integrity failures instead of reconstructing historical facts',async()=>{const ids=await fixtures();const read=()=>financeAs<{v:{snapshot:unknown;integrity:unknown;reopening:unknown}}>(db,i.operator,'select get_finance_account_period_evidence($1,$2,$3) v',[i.tenant,i.account,ids.second]);const before=(await read()).rows[0].v;expect(before.snapshot).toEqual({balances:{opening_cents:'10000',closing_cents:'10000'}});expect(before.integrity).toEqual({snapshot_matches_revision:false,dependencies_match:false});await financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:ids.second,revision:'a'.repeat(32),reason:'Reabrir preservando todas as evidências'}]);const after=(await read()).rows[0].v;expect(after.snapshot).toEqual(before.snapshot);expect(after.reopening).toMatchObject({actor_id:i.operator});});
it('protects evidence from cross-account, cross-tenant and mixed-driver reads',async()=>{const ids=await fixtures();for(const [tenant,account] of [[i.tenant,i.otherAccount],[i.otherTenant,i.account]])await expect(financeAs(db,i.operator,'select get_finance_account_period_evidence($1,$2,$3)',[tenant,account,ids.first])).rejects.toThrow();await db.query("insert into drivers(id,tenant_id,user_id,active) values($1,$2,$3,true)",[randomUUID(),i.tenant,i.operator]);await expect(financeAs(db,i.operator,'select get_finance_account_period_evidence($1,$2,$3)',[i.tenant,i.account,ids.first])).rejects.toThrow('finance_access_denied');});
it('keeps an actual reopening visible in the global manual audit with its actor and reason',async()=>{
 const ids=await fixtures(),reason='Reabertura conferida pela chefia';
 await financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:ids.second,revision:'a'.repeat(32),reason}]);
 const result=(await financeAs<{v:{total:number;manual_count:number;rows:Array<{manual_intervention:boolean;actor_id:string;reason:string}>}}>(db,i.operator,'select list_finance_audit_events($1,$2) v',[i.tenant,{manual_only:true,action:'account_period_reopened',actor_id:i.operator}])).rows[0].v;
 expect(result).toMatchObject({total:1,manual_count:1});expect(result.rows[0]).toMatchObject({manual_intervention:true,actor_id:i.operator,reason});
});
