import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {AccountPeriodCloseWorkspace} from '@/components/financial/AccountPeriodClosePanel';
import {AccountPeriodCloseRejectedError} from '@/lib/financial/accountPeriodCloseClient';
const mock=vi.hoisted(()=>({read:vi.fn(),history:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/accountPeriodCloseClient',()=>({readAccountPeriodClosePreview:mock.read,readAccountPeriodHistory:mock.history,submitAccountPeriodDecision:mock.submit,AccountPeriodCloseRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),closure=crypto.randomUUID(),from='2026-01-01',to='2026-01-31',revision='a'.repeat(32),key=`finance-account-period-decision:${tenant}:${actor}:${account}`;
const preview={version:1,tenant_id:tenant,account_id:account,from,to,currency:'BRL',timezone:'America/Sao_Paulo',revision,eligible:true,can_execute:true,blockers:[],opening_id:crypto.randomUUID(),predecessor_id:null,balances:{opening_cents:'10000',closing_cents:'15000',bank_in_cents:'10000',bank_out_cents:'5000',recorded_in_cents:'10000',recorded_out_cents:'5000'}};
const history={version:1,tenant_id:tenant,account_id:account,total_count:0,offset:0,limit:30,can_execute:true,items:[]};
const item={id:closure,from,to,revision,actor_id:actor,actor_name:'Maria financeira',reason:'Conferência anterior completa',created_at:'2026-02-01',active:true,can_reopen:true,active_descendant_ids:[],opening_cents:'10000',closing_cents:'15000',reopening:null};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(preview);mock.history.mockResolvedValue(history);mock.submit.mockResolvedValue({account_id:account,closure_id:closure});});afterEach(()=>cleanup());
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><AccountPeriodCloseWorkspace tenant={tenant} actor={actor} account={account} from={from} to={to}/></QueryClientProvider>);}
async function prepare(){fireEvent.click(await screen.findByRole('checkbox'));fireEvent.change(screen.getByLabelText('Motivo da decisão bancária'),{target:{value:'Conferência integral para fechar este período'}});fireEvent.click(screen.getByRole('button',{name:'Revisar fechamento bancário'}));}
it('requires declaration and review and replays the original request after lost response',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await screen.findByRole('checkbox');expect(screen.getByRole('button',{name:'Revisar fechamento bancário'})).toBeDisabled();await prepare();expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar fechamento bancário'}));await screen.findByText(/pedido original foi preservado/);const original=mock.submit.mock.calls[0][0];view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar decisão bancária original'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('separates administrator capacity from eligibility and blocks corrupted recovery',async()=>{mock.read.mockResolvedValue({...preview,can_execute:false});mock.history.mockResolvedValue({...history,can_execute:false});open();await screen.findByText(/Consulta disponível/);expect(screen.queryByRole('button',{name:'Revisar fechamento bancário'})).not.toBeInTheDocument();cleanup();mock.read.mockResolvedValue(preview);sessionStorage.setItem(key,'broken');open();await screen.findByText(/Novas decisões estão bloqueadas/);expect(await screen.findByRole('button',{name:'Revisar fechamento bancário'})).toBeDisabled();});
it('disables a changed preview and hides stale facts on failure',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await prepare();mock.read.mockResolvedValue({...preview,revision:'b'.repeat(32)});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-account-period-close-preview']});});await screen.findByText(/A conferência mudou/);expect(screen.getByRole('button',{name:'Confirmar fechamento bancário'})).toBeDisabled();mock.read.mockRejectedValueOnce(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-account-period-close-preview']});});await screen.findByText(/Não foi possível consultar a elegibilidade/);expect(screen.queryByLabelText('Resultado da conferência para fechamento')).not.toBeInTheDocument();});
it('reopens from history even when new preview is blocked and preserves closure identity',async()=>{mock.read.mockResolvedValue({...preview,eligible:false,blockers:[{code:'period_already_closed',source_table:null,source_ids:[],scope:'account'}]});mock.history.mockResolvedValue({...history,total_count:1,items:[item]});open();fireEvent.click(await screen.findByRole('button',{name:`Revisar reabertura de ${from} a ${to}`}));fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Motivo da decisão bancária'),{target:{value:'Reabrir para corrigir evidência bancária'}});fireEvent.click(screen.getByRole('button',{name:'Revisar decisão de reabertura'}));expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar reabertura bancária'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(1));expect(mock.submit.mock.calls[0][0]).toMatchObject({kind:'reopen',command:{closure_id:closure,revision}});expect(screen.getByText(/Decisão manual por Maria financeira/)).toBeInTheDocument();});
it('shows descendants without automatic cascade and paginates account history',async()=>{const descendant=crypto.randomUUID();mock.history.mockResolvedValue({...history,total_count:31,items:[{...item,can_reopen:false,active_descendant_ids:[descendant]}]});open();await screen.findByText(/fechamentos posteriores dependentes/);expect(screen.getByText(descendant)).toBeInTheDocument();expect(screen.queryByRole('button',{name:`Revisar reabertura de ${from} a ${to}`})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Próximos fechamentos'}));await waitFor(()=>expect(mock.history).toHaveBeenLastCalledWith(tenant,account,30));});
it('releases review after a known first rollback',async()=>{mock.submit.mockRejectedValueOnce(new AccountPeriodCloseRejectedError('finance_period_close_changed'));open();await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar fechamento bancário'}));await screen.findByText(/conferência mudou desde a revisão/);await waitFor(()=>expect(sessionStorage.getItem(key)).toBeNull());expect(screen.getByRole('button',{name:'Revisar fechamento bancário'})).not.toBeDisabled();});
