import {beforeEach,it,expect,vi} from 'vitest';
import {readAccountPeriodEvidence} from '@/lib/financial/accountPeriodEvidenceClient';
import {accountPeriodEvidenceSchema,exportAccountPeriodEvidence} from '@/lib/financial/accountPeriodEvidenceContract';
const mock=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mock.rpc}}));
const tenant=crypto.randomUUID(),account=crypto.randomUUID(),closure=crypto.randomUUID();
const evidence={version:1 as const,tenant_id:tenant,account_id:account,closure_id:closure,closure:{from:'2026-01-01',to:'2026-01-31',revision:'a'.repeat(32),actor_id:crypto.randomUUID(),actor_name:'Maria',reason:'Conferência do banco',created_at:'2026-02-01'},snapshot:{balances:{opening_cents:'10000'},original_path:'retained/statement.ofx',unknown_future_field:{ids:['one','two']}},dependencies:[{source_kind:'finance_movements',source_id:crypto.randomUUID()}],integrity:{snapshot_matches_revision:false,dependencies_match:true},reopening:null};
beforeEach(()=>vi.clearAllMocks());
it('returns exact authorized data including failed integrity without generating source URLs',async()=>{mock.rpc.mockResolvedValueOnce({data:evidence,error:null});const result=await readAccountPeriodEvidence(tenant,account,closure);expect(JSON.parse(exportAccountPeriodEvidence(result))).toEqual(evidence);expect(mock.rpc).toHaveBeenCalledExactlyOnceWith('get_finance_account_period_evidence',{_tenant_id:tenant,_account_id:account,_closure_id:closure});expect(result.integrity.snapshot_matches_revision).toBe(false);});
it('rejects cross-account closure responses and invalid integrity metadata',async()=>{mock.rpc.mockResolvedValueOnce({data:{...evidence,account_id:crypto.randomUUID()},error:null});await expect(readAccountPeriodEvidence(tenant,account,closure)).rejects.toThrow();expect(accountPeriodEvidenceSchema.safeParse({...evidence,integrity:{snapshot_matches_revision:'true',dependencies_match:true}}).success).toBe(false);expect(JSON.parse(exportAccountPeriodEvidence({...evidence,extra_metadata:{preserved:true}}))).toHaveProperty('extra_metadata.preserved',true);});
