import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {AccountPeriodEvidencePanel,AccountPeriodEvidenceWorkspace} from '@/components/financial/AccountPeriodEvidencePanel';
const mock=vi.hoisted(()=>({read:vi.fn(),readExport:vi.fn(),create:vi.fn(),revoke:vi.fn()}));vi.mock('@/lib/financial/accountPeriodEvidenceClient',()=>({readAccountPeriodEvidence:mock.read,readAccountPeriodEvidenceExport:mock.readExport}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),closure=crypto.randomUUID();
const evidence={version:1,tenant_id:tenant,account_id:account,closure_id:closure,closure:{from:'2026-01-01',to:'2026-01-31',revision:'a'.repeat(32),actor_id:actor,actor_name:'Maria',reason:'Conferência original',created_at:'2026-02-01'},snapshot:{balances:{opening_cents:'10000',closing_cents:'15000',bank_in_cents:'10000',bank_out_cents:'5000',recorded_in_cents:'10000',recorded_out_cents:'5000'},facts:{movements:[{id:'movement-1',nature:'payment',direction:'out',description:'Fornecedor',occurred_on:'2026-01-15',amount_cents:5000}]}},dependencies:Array.from({length:31},(_,index)=>({source_kind:'finance_movements',source_id:`dependency-${index}`})),integrity:{snapshot_matches_revision:false,dependencies_match:true},reopening:{id:crypto.randomUUID(),actor_id:actor,actor_name:'João',reason:'Correção da evidência',created_at:'2026-02-02'}};
beforeEach(()=>{vi.clearAllMocks();mock.read.mockImplementation((_tenant:string,_account:string,_closure:string,movementOffset=0,dependencyOffset=0)=>Promise.resolve({...evidence,snapshot:{...evidence.snapshot,facts:{...evidence.snapshot.facts,movements:evidence.snapshot.facts.movements.slice(movementOffset,movementOffset+30)}},dependencies:evidence.dependencies.slice(dependencyOffset,dependencyOffset+30),movement_page:{offset:movementOffset,limit:30,total:evidence.snapshot.facts.movements.length},dependency_page:{offset:dependencyOffset,limit:30,total:evidence.dependencies.length}}));mock.readExport.mockResolvedValue(evidence);mock.create.mockReturnValue('blob:local-export');vi.stubGlobal('URL',{createObjectURL:mock.create,revokeObjectURL:mock.revoke});});afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.restoreAllMocks();});
function open(lazy=false){return render(<QueryClientProvider client={new QueryClient()}>{lazy?<AccountPeriodEvidencePanel tenant={tenant} actor={actor} account={account} closure={closure}/>:<AccountPeriodEvidenceWorkspace tenant={tenant} actor={actor} account={account} closure={closure}/>}</QueryClientProvider>);}
it('loads on demand, shows preserved bank/movement categories and pages dependencies on the server',async()=>{open(true);expect(mock.read).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Evidências do fechamento'}));await screen.findByText(/Há divergência na integridade/);expect(screen.getByText(/Reaberto por João/)).toBeInTheDocument();expect(screen.getByText(/Pagamento · movimento movement-1/)).toBeInTheDocument();expect(mock.read).toHaveBeenLastCalledWith(tenant,account,closure,0,0);fireEvent.click(screen.getByRole('button',{name:'Próximas evidências vinculadas'}));await screen.findByText(/dependency-30/);expect(mock.read).toHaveBeenLastCalledWith(tenant,account,closure,0,30);expect(mock.read).toHaveBeenCalledTimes(2);});
it('fetches the integral snapshot only when the export is explicitly requested',async()=>{const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});open();await screen.findByText(/Decisão manual por Maria/);expect(mock.create).not.toHaveBeenCalled();expect(mock.readExport).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Exportar evidências do fechamento em JSON'}));await waitFor(()=>expect(mock.create.mock.calls[0][0]).toBeInstanceOf(Blob));expect(mock.readExport).toHaveBeenCalledExactlyOnceWith(tenant,account,closure);expect(click).toHaveBeenCalledTimes(1);expect(mock.revoke).toHaveBeenCalledWith('blob:local-export');expect(mock.read).toHaveBeenCalledTimes(1);});
it('hides old evidence and export after failed refresh',async()=>{open();await screen.findByText(/Decisão manual por Maria/);mock.read.mockRejectedValueOnce(new Error('offline'));fireEvent.click(screen.getByRole('button',{name:'Atualizar evidências preservadas'}));await screen.findByText(/Não foi possível consultar as evidências/);await waitFor(()=>expect(screen.queryByRole('button',{name:'Exportar evidências do fechamento em JSON'})).not.toBeInTheDocument());});
