// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createAccountPeriodCloseDatabase,seedAccountCloseStatement} from './helpers/accountPeriodCloseDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {accountPeriodEvidenceSchema} from '@/lib/financial/accountPeriodEvidenceContract';
import {accountPeriodClosePreviewSchema,accountPeriodCloseResultSchema,accountPeriodReopenResultSchema} from '@/lib/financial/accountPeriodCloseContract';
let db:Awaited<ReturnType<typeof createAccountPeriodCloseDatabase>>;
beforeAll(async()=>{db=await createAccountPeriodCloseDatabase(true);},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where user_id=$1",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
const base=()=>({version:1,tenant_id:i.tenant,request_id:randomUUID(),reason:'Conferência do período bancário completo'});
async function rpc(name:string,p:unknown){return(await financeAs<{v:unknown}>(db,i.operator,`select ${name}($1::jsonb) v`,[p])).rows[0].v;}
async function preview(){return accountPeriodClosePreviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select preview_finance_account_period_close($1,$2,$3,$4) v',[i.tenant,i.account,'2026-08-01','2026-08-31'])).rows[0].v);}
async function prepare(){await seedAccountCloseStatement(db,'2026-07-31',10000);await seedAccountCloseStatement(db,'2026-08-31',10000);await db.exec('select finance_private.run_automatic_reconciliation_queue()');const scope={account_id:i.account,from:'2026-08-01',to:'2026-08-31'};const ev=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_statement_period_evidence($1,$2,$3,$4) v',[i.tenant,i.account,scope.from,scope.to])).rows[0].v;await rpc('record_finance_account_opening',{...base(),...scope,revision:ev.revision});const cv=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_statement_coverage_review($1,$2,$3,$4) v',[i.tenant,i.account,scope.from,scope.to])).rows[0].v;await rpc('record_finance_statement_coverage_approval',{...base(),...scope,revision:cv.revision,originals_obtained_from_bank:true,complete_period_confirmed:true});const cut=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,i.account,scope.from,scope.to])).rows[0].v;await rpc('review_finance_legacy_cut',{...base(),...scope,revision:cut.revision,sources_reviewed:true});return scope;}
it('real evidence opening coverage cut and guards produce eligible close, replay and reopen',async()=>{const scope=await prepare(),p=await preview();expect(p.blockers).toEqual([]);expect(p.eligible).toBe(true);const command={...base(),...scope,revision:p.revision},closed=accountPeriodCloseResultSchema.parse(await rpc('close_finance_account_period',command));expect(await rpc('close_finance_account_period',command)).toEqual(closed);expect((await preview()).eligible).toBe(false);const readEvidence=async()=>accountPeriodEvidenceSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_account_period_evidence($1,$2,$3) v',[i.tenant,i.account,closed.closure_id])).rows[0].v);const evidence=await readEvidence();expect(evidence.integrity).toEqual({snapshot_matches_revision:true,dependencies_match:true});const reopen={...base(),closure_id:closed.closure_id,revision:closed.revision};accountPeriodReopenResultSchema.parse(await rpc('reopen_finance_account_period',reopen));expect((await readEvidence()).snapshot).toEqual(evidence.snapshot);expect((await readEvidence()).integrity).toEqual(evidence.integrity);expect((await preview()).eligible).toBe(true);expect((await db.query<{n:number}>('select count(*)::int n from finance_movements')).rows[0].n).toBe(0);});
it('closed source rejects retroactive movement and new review, reopening allows corrected review',async()=>{const scope=await prepare(),p=await preview();const closed=accountPeriodCloseResultSchema.parse(await rpc('close_finance_account_period',{...base(),...scope,revision:p.revision}));await expect(rpc('record_finance_movement',{...base(),bank_account_id:i.account,direction:'in',nature:'receipt',amount_cents:1000,occurred_on:'2026-08-10',description:'Recebimento retroativo',beneficiary_name:'Cliente QA'})).rejects.toThrow('closed');const cut=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,i.account,scope.from,scope.to])).rows[0].v;await expect(rpc('review_finance_legacy_cut',{...base(),...scope,revision:cut.revision,sources_reviewed:true})).rejects.toThrow('closed');await rpc('reopen_finance_account_period',{...base(),closure_id:closed.closure_id,revision:closed.revision});await rpc('review_finance_legacy_cut',{...base(),...scope,revision:cut.revision,sources_reviewed:true});});
async function approveScope(from:string,to:string,opening=false){const scope={account_id:i.account,from,to};if(opening){const evidence=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_statement_period_evidence($1,$2,$3,$4) v',[i.tenant,i.account,from,to])).rows[0].v;await rpc('record_finance_account_opening',{...base(),...scope,revision:evidence.revision});}const coverage=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_statement_coverage_review($1,$2,$3,$4) v',[i.tenant,i.account,from,to])).rows[0].v;await rpc('record_finance_statement_coverage_approval',{...base(),...scope,revision:coverage.revision,originals_obtained_from_bank:true,complete_period_confirmed:true});const cut=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,i.account,from,to])).rows[0].v;await rpc('review_finance_legacy_cut',{...base(),...scope,revision:cut.revision,sources_reviewed:true});return scope;}
it('closes actual recorded money reconciled to a verified bank entry',async()=>{await seedAccountCloseStatement(db,'2026-07-31',10000);const statement=await seedAccountCloseStatement(db,'2026-08-31',11000,'2026-08-01','2026-08-31',[{day:'2026-08-10',cents:1000}]);const movement=await rpc('record_finance_movement',{...base(),bank_account_id:i.account,direction:'in',nature:'receipt',amount_cents:1000,occurred_on:'2026-08-10',description:'Entrada do cliente',beneficiary_name:'Cliente QA'}) as {movement_id:string};await db.exec('select finance_private.run_automatic_reconciliation_queue()');const context=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_reconciliation_context($1,$2,$3) v',[i.tenant,[movement.movement_id],statement.entryIds])).rows[0].v;await rpc('reconcile_finance_bank_group',{...base(),movement_ids:[movement.movement_id],bank_entry_ids:statement.entryIds,expected_revision:context.revision,account_evidence:'Conta e titular confirmados no extrato bancário'});const scope=await approveScope('2026-08-01','2026-08-31',true),p=await preview();expect(p.blockers).toEqual([]);expect(p.balances).toMatchObject({bank_in_cents:'1000',recorded_in_cents:'1000',closing_cents:'11000'});const before=(await db.query('select * from finance_movements')).rows;await rpc('close_finance_account_period',{...base(),...scope,revision:p.revision});expect((await db.query('select * from finance_movements')).rows).toEqual(before);});
it('closes the next contiguous month with equal anchor and refuses reopening its predecessor',async()=>{await seedAccountCloseStatement(db,'2026-06-30',10000,'2026-07-01','2026-07-31');await seedAccountCloseStatement(db,'2026-07-31',10000,'2026-07-01','2026-07-31');await seedAccountCloseStatement(db,'2026-08-31',10000,'2026-08-01','2026-08-31');await db.exec('select finance_private.run_automatic_reconciliation_queue()');const july=await approveScope('2026-07-01','2026-07-31',true);const jp=accountPeriodClosePreviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select preview_finance_account_period_close($1,$2,$3,$4) v',[i.tenant,i.account,july.from,july.to])).rows[0].v);expect(jp.blockers).toEqual([]);const first=accountPeriodCloseResultSchema.parse(await rpc('close_finance_account_period',{...base(),...july,revision:jp.revision}));const august=await approveScope('2026-08-01','2026-08-31');const ap=await preview();expect(ap.blockers).toEqual([]);expect(ap.predecessor_id).toBe(first.closure_id);expect(ap.balances.opening_cents).toBe('10000');await rpc('close_finance_account_period',{...base(),...august,revision:ap.revision});await expect(rpc('reopen_finance_account_period',{...base(),closure_id:first.closure_id,revision:first.revision})).rejects.toThrow('descendants');});
