// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createAccountPeriodCloseDatabase,seedAccountCloseStatement} from './helpers/accountPeriodCloseDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createAccountPeriodCloseDatabase>>;
beforeAll(async()=>{db=await createAccountPeriodCloseDatabase(true);},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
// A historical closed snapshot exercises guards, not eligibility. The integrated
// producer/classifier tests separately must prove actual positive close commands.
async function historicalClose(){const opening=randomUUID(),closure=randomUUID(),request=randomUUID();
 await db.query("insert into finance_account_openings(id,tenant_id,bank_account_id,effective_from,balance_cents,evidence_to,evidence,actor_id,actor_name,reason) values($1,$2,$3,'2026-08-01',10000,'2026-07-31','{}',$4,'QA','Abertura histórica fixture')",[opening,i.tenant,i.account,i.operator]);
 await db.query("insert into finance_private.account_close_write_tickets values(txid_current(),$1,$2,$3,'finance_account_period_closures')",[i.tenant,request,i.operator]);
 await db.query("insert into finance_account_period_closures(id,tenant_id,account_id,period_start,period_end,opening_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,$3,'2026-08-01','2026-08-31',$4,$5,$6,$7,'QA','Fechamento histórico fixture',$8)",[closure,i.tenant,i.account,opening,{balances:{closing_cents:'10000'}},'a'.repeat(32),i.operator,request]);return{opening,closure};}
async function movement(day:string){return financeAs(db,i.operator,'select record_finance_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:100,occurred_on:day,description:'Pagamento registrado',beneficiary_name:'Contraparte',reason:'Registro financeiro conferido'}]);}
it('blocks retroactive money through the real movement command while later money remains usable',async()=>{await historicalClose();await expect(movement('2026-08-15')).rejects.toThrow('finance_account_period_closed');await movement('2026-09-01');expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:1});});
it('preserves opening, account identity and immutable snapshot, but permits the account label',async()=>{const s=await historicalClose();await db.exec('savepoint opening_guard');await expect(db.query("insert into finance_account_opening_reversals(tenant_id,opening_id,actor_id,actor_name,reason) values($1,$2,$3,'QA','Reversão da abertura usada')",[i.tenant,s.opening,i.operator])).rejects.toThrow('finance_account_period_closed');await db.exec('rollback to savepoint opening_guard');await db.query("update bank_accounts set name='Conta com novo rótulo' where id=$1",[i.account]);await db.exec('savepoint identity_guard');await expect(db.query("update bank_accounts set account_number='999' where id=$1",[i.account])).rejects.toThrow('finance_account_period_closed');await db.exec('rollback to savepoint identity_guard');});
it('accepts a following statement and native future evidence without reopening the previous month',async()=>{await historicalClose();await seedAccountCloseStatement(db,'2026-09-30',10000,'2026-09-01','2026-09-30');expect((await db.query('select count(*)::int n from finance_statement_verifications')).rows[0]).toEqual({n:1});});
it('accepts an exactly corroborating boundary anchor and rejects contradictory native evidence',async()=>{await historicalClose();await seedAccountCloseStatement(db,'2026-08-31',10000,'2026-09-01','2026-09-30');await db.exec('savepoint anchor_guard');await expect(seedAccountCloseStatement(db,'2026-08-31',9999,'2026-09-01','2026-09-30')).rejects.toThrow('finance_closed_anchor_conflict');await db.exec('rollback to savepoint anchor_guard');});
it('reopens through the real audited command with replay and then permits retroactive correction',async()=>{const s=await historicalClose();const p={version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:s.closure,revision:'a'.repeat(32),reason:'Reabrir para corrigir lançamento identificado'};const first=await financeAs(db,i.operator,'select reopen_finance_account_period($1) v',[p]);expect(await financeAs(db,i.operator,'select reopen_finance_account_period($1) v',[p])).toEqual(first);await movement('2026-08-15');expect((await db.query("select count(*)::int n from finance_events where action='account_period_reopened'")).rows[0]).toEqual({n:1});});
it('denies an operator command and prevents privileged inserts without the internal command ticket',async()=>{const s=await historicalClose();await db.query("update tenant_memberships set role='operator' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await expect(financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:s.closure,revision:'a'.repeat(32),reason:'Solicitação de usuário operador'}])).rejects.toThrow('finance_close_access_denied');await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await db.exec('savepoint ticket_guard');await expect(db.query("insert into finance_account_period_reopenings(tenant_id,closure_id,expected_snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,'revision',$3,'QA','Tentativa sem comando interno',gen_random_uuid())",[i.tenant,s.closure,i.operator])).rejects.toThrow('finance_period_close_command_required');await db.exec('rollback to savepoint ticket_guard');});
it('completes an identified transfer after the cutoff without changing its frozen departure',async()=>{const destination=randomUUID();await db.query("insert into bank_accounts(id,tenant_id,name,active,account_number) values($1,$2,'Destino',true,'555-6')",[destination,i.tenant]);const departure=(await financeAs<{v:{departure_id:string;movement_id:string}}>(db,i.operator,'select record_finance_transfer_stage($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),stage:'depart',source_account_id:i.account,destination_account_id:destination,amount_cents:1000,occurred_on:'2026-08-20',reason:'Transferência bancária iniciada',occurred:true}])).rows[0].v;const s=await historicalClose();await db.query("insert into finance_account_period_dependencies values($1,$2,'finance_transfer_departures',$3,'revision',$4,'2026-08-01','2026-08-31','composition_snapshot')",[i.tenant,s.closure,departure.departure_id,i.account]);await financeAs(db,i.operator,'select record_finance_transfer_stage($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),stage:'arrive',departure_id:departure.departure_id,occurred_on:'2026-09-01',reason:'Chegada bancária no mês seguinte',occurred:true}]);expect((await db.query('select count(*)::int n from finance_internal_transfers')).rows[0]).toEqual({n:1});expect((await db.query('select occurred_on::text from finance_movements where id=$1',[departure.movement_id])).rows[0]).toEqual({occurred_on:'2026-08-20'});});
it('blocks OLD and NEW dates when a legacy bank row moves into the closed period',async()=>{await historicalClose();const id=randomUUID();await db.query("insert into bank_transactions(id,tenant_id,bank_account_id,posted_at,amount,transaction_type) values($1,$2,$3,'2026-09-05',10,'debit')",[id,i.tenant,i.account]);await db.exec('savepoint oldnew');await expect(db.query("update bank_transactions set posted_at='2026-08-15' where id=$1",[id])).rejects.toThrow('finance_account_period_closed');await db.exec('rollback to savepoint oldnew');});
it('prevents reopening a predecessor while a contiguous descendant remains closed',async()=>{const s=await historicalClose(),next=randomUUID(),request=randomUUID();await db.query("insert into finance_private.account_close_write_tickets values(txid_current(),$1,$2,$3,'finance_account_period_closures')",[i.tenant,request,i.operator]);await db.query("insert into finance_account_period_closures(id,tenant_id,account_id,period_start,period_end,opening_id,predecessor_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,$3,'2026-09-01','2026-09-02',$4,$5,'{}',$6,$7,'QA','Descendente histórico fixture',$8)",[next,i.tenant,i.account,s.opening,s.closure,'b'.repeat(32),i.operator,request]);await expect(financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:s.closure,revision:'a'.repeat(32),reason:'Tentativa de reabrir período anterior'}])).rejects.toThrow('finance_period_has_descendants');});
it('allows the future refund leg without mutating the referenced closed receipt',async()=>{await historicalClose();const bank=randomUUID();await db.query("insert into bank_transactions(id,tenant_id,bank_account_id,posted_at,amount,transaction_type) values($1,$2,$3,'2026-09-05',10,'debit')",[bank,i.tenant,i.account]);await db.query("select finance_private.assert_closed_source_mutable($1,'receivable_payment_reversals',$2)",[i.tenant,{id:randomUUID(),tenant_id:i.tenant,payment_id:randomUUID(),bank_transaction_id:bank,effective_at:'2026-09-05T12:00:00Z'}]);await expect(db.query("select finance_private.assert_closed_source_mutable($1,'receivable_payment_reversals',$2)",[i.tenant,{id:randomUUID(),tenant_id:i.tenant,bank_account_id:i.account,effective_at:'2026-08-05T12:00:00Z'}])).rejects.toThrow('finance_account_period_closed');});
