import {it,expect,vi} from 'vitest';
import {readAccountOpening,recordAccountOpening,reverseAccountOpening,AccountOpeningRejectedError} from '@/lib/financial/accountOpeningClient';
const mock=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mock.rpc}}));
const tenant=crypto.randomUUID(),account=crypto.randomUUID(),opening=crypto.randomUUID();
const command={version:1 as const,tenant_id:tenant,request_id:crypto.randomUUID(),account_id:account,from:'2026-01-02',to:'2026-01-31',revision:'snapshot',reason:'Âncora revisada no OFX'};
it('requires correct request identity and no created cash',async()=>{const data={version:1,tenant_id:tenant,request_id:command.request_id,opening_id:opening,confirmed:true,cash_created:false};mock.rpc.mockResolvedValueOnce({data,error:null});await expect(recordAccountOpening(command)).resolves.toMatchObject({cash_created:false});mock.rpc.mockResolvedValueOnce({data:{...data,request_id:crypto.randomUUID()},error:null});await expect(recordAccountOpening(command)).rejects.toThrow('fora do contexto');mock.rpc.mockResolvedValueOnce({data:{...data,cash_created:true},error:null});await expect(recordAccountOpening(command)).rejects.toThrow();});
it('validates correction identity and classifies transaction rejection',async()=>{const reversal={version:1 as const,tenant_id:tenant,request_id:crypto.randomUUID(),opening_id:opening,reason:'Abertura com data incorreta'};mock.rpc.mockResolvedValueOnce({error:null,data:{...reversal,reversal_id:crypto.randomUUID(),confirmed:true,cash_changed:false}});await expect(reverseAccountOpening(reversal)).resolves.toMatchObject({cash_changed:false});mock.rpc.mockResolvedValueOnce({data:null,error:{code:'55000',message:'finance_opening_already_reversed'}});await expect(reverseAccountOpening(reversal)).rejects.toBeInstanceOf(AccountOpeningRejectedError);});
it('rejects context from a different account or unavailable evidence status',async()=>{const data={version:1,tenant_id:tenant,account_id:crypto.randomUUID(),from:command.from,to:command.to,opening:null,book:null,history:[],can_close:false};mock.rpc.mockResolvedValueOnce({error:null,data});await expect(readAccountOpening(tenant,account,command.from,command.to)).rejects.toThrow('fora do contexto');mock.rpc.mockResolvedValueOnce({error:null,data:{...data,account_id:account,opening:{id:opening,effective_from:command.from,balance_cents:'0',actor_id:tenant,actor_name:'QA',reason:'Conferido',created_at:'2026-01-02'}}});await expect(readAccountOpening(tenant,account,command.from,command.to)).rejects.toThrow();});
it('classifies the migrations evidence-changed 40001 as rollback, while transport failure stays uncertain',async()=>{
 mock.rpc.mockResolvedValueOnce({data:null,error:{code:'40001',message:'finance_opening_evidence_changed'}});await expect(recordAccountOpening(command)).rejects.toBeInstanceOf(AccountOpeningRejectedError);
 mock.rpc.mockResolvedValueOnce({data:null,error:{code:'504',message:'timeout'}});await expect(recordAccountOpening(command)).rejects.not.toBeInstanceOf(AccountOpeningRejectedError);
});
it('rejects mismatched evidence types, count totals and effective dates even in reversed history',async()=>{
 const evidence={version:1,type:'cash_count_v1',currency:'BRL',effective_from:'2026-01-02',timezone:'America/Sao_Paulo',counted_at_boundary:'start_of_day',custodian_name:'Ana QA',counts:[{denomination_cents:100,quantity:2}],total_cents:'200'};
 const item={id:opening,effective_from:'2026-01-02',balance_cents:'200',actor_id:tenant,actor_name:'Financeiro QA',reason:'Contagem original',created_at:'2026-01-02',evidence_type:'cash_count_v1',evidence,reversal:{id:crypto.randomUUID(),actor_id:tenant,actor_name:'Gestor QA',reason:'Correção auditada',created_at:'2026-01-03'}};
 const base={version:1,tenant_id:tenant,account_id:account,from:command.from,to:command.to,opening:null,book:null,history:[item],can_close:false};
 mock.rpc.mockResolvedValueOnce({error:null,data:base});await expect(readAccountOpening(tenant,account,command.from,command.to)).resolves.toMatchObject({history:[{evidence_type:'cash_count_v1'}]});
 for(const altered of [{...item,evidence:{opening_anchors:[]}},{...item,evidence_type:'bank_statement_v1'},{...item,balance_cents:'300'},{...item,effective_from:'2026-01-03'},{...item,evidence:{...evidence,counts:[{denomination_cents:100,quantity:3}]}}]){mock.rpc.mockResolvedValueOnce({error:null,data:{...base,history:[altered]}});await expect(readAccountOpening(tenant,account,command.from,command.to)).rejects.toThrow();}
});
