import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import type {AuthChangeEvent,Session} from '@supabase/supabase-js';
import {useState,StrictMode} from 'react';
import {AuthProvider,useAuth} from '@/hooks/useAuth';
import {TenantProvider,useTenant} from '@/hooks/useTenant';
import {GlobalAlert} from '@/components/GlobalAlert';
import {confirmAction,promptAction,useAlertStore} from '@/hooks/useAlertStore';

const mock=vi.hoisted(()=>({listeners:new Set<(event:AuthChangeEvent,session:Session|null)=>void>(),getSession:vi.fn(),getUser:vi.fn(),signOut:vi.fn(),rpc:vi.fn(),toast:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{auth:{getSession:mock.getSession,getUser:mock.getUser,signOut:mock.signOut,onAuthStateChange:(cb:(event:AuthChangeEvent,session:Session|null)=>void)=>{mock.listeners.add(cb);return {data:{subscription:{unsubscribe:()=>mock.listeners.delete(cb)}}};}},rpc:mock.rpc}}));
vi.mock('@/hooks/use-toast',()=>({useToast:()=>({toast:mock.toast})}));
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};}
function session(id:string,token=id):Session{return {user:{id},access_token:token,refresh_token:'synthetic',expires_in:3600,token_type:'bearer'} as Session;}
const membership=(tenant:string,role='operator')=>({tenant_id:tenant,tenant_name:tenant,role,plan_key:'qa',timezone:'America/Sao_Paulo'});
let client:QueryClient,current:Session|null;
async function emit(id:string|null,event:AuthChangeEvent=id?'SIGNED_IN':'SIGNED_OUT',token?:string){current=id?session(id,token):null;await act(async()=>{mock.listeners.forEach(cb=>cb(event,current));});}
function Identity(){const {user,signOut,backendUnavailable}=useAuth();return <><output aria-label="actor">{user?.id??'none'}</output><output aria-label="availability">{String(backendUnavailable)}</output><button onClick={()=>{void signOut();}}>Sair QA</button></>;}
function TenantIdentity(){const {currentTenant,currentRole,setCurrentTenantId}=useTenant();const [draft,setDraft]=useState('');return <><output aria-label="tenant">{currentTenant?.id??'none'}</output><output aria-label="role">{currentRole??'none'}</output><input aria-label="draft QA" value={draft} onChange={e=>setDraft(e.target.value)}/><button onClick={()=>setCurrentTenantId('tenant-b')}>Trocar tenant QA</button><button onClick={()=>setCurrentTenantId('unrelated')}>Tenant inválido QA</button></>;}
function Story({tenant=false,read=false}:{tenant?:boolean;read?:boolean}){return <QueryClientProvider client={client}><GlobalAlert/><AuthProvider><Identity/>{tenant?<TenantProvider><TenantIdentity/>{read?<LegacyQuery/>:null}</TenantProvider>:null}</AuthProvider></QueryClientProvider>;}
function LegacyQuery(){const {currentTenant}=useTenant();const {data}=useQuery({queryKey:['legacy-unscoped-data'],enabled:!!currentTenant,queryFn:async()=>currentTenant?.id,staleTime:Infinity});return <output aria-label="legacy">{data??'none'}</output>;}
beforeEach(()=>{vi.clearAllMocks();current=null;mock.listeners.clear();localStorage.clear();client=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:120000}}});mock.getSession.mockResolvedValue({data:{session:null},error:null});mock.getUser.mockImplementation(async()=>({data:{user:current?.user??null}}));mock.signOut.mockImplementation(async()=>{await emit(null);return {error:null};});mock.rpc.mockImplementation(()=>{const request=Promise.resolve({data:[membership('tenant-a'),membership('tenant-b')],error:null});return Object.assign(request,{abortSignal:()=>request});});});
afterEach(()=>{cleanup();client.clear();useAlertStore.getState().onCancel?.();useAlertStore.getState().hideAlert();vi.restoreAllMocks();vi.useRealTimers();});

describe('real session and tenant providers',()=>{
 it('ignores an initial session response that arrives after logout',async()=>{const initial=deferred<{data:{session:Session};error:null}>();mock.getSession.mockReturnValue(initial.promise);render(<Story/>);await emit('actor-a');await emit(null);await act(async()=>initial.resolve({data:{session:session('actor-a')},error:null}));expect(screen.getByLabelText('actor')).toHaveTextContent('none');});
 it('ignores an initial session response that arrives after switching account',async()=>{const initial=deferred<{data:{session:Session};error:null}>();mock.getSession.mockReturnValue(initial.promise);render(<Story/>);await emit('actor-b');await act(async()=>initial.resolve({data:{session:session('actor-a')},error:null}));expect(screen.getByLabelText('actor')).toHaveTextContent('actor-b');});
 it('clears old query and mutation cache but preserves durable commands',async()=>{render(<Story/>);await emit('actor-a');client.setQueryData(['driver_settlements','tenant-a'],['private QA']);client.getMutationCache().build(client,{mutationKey:['old-command']});localStorage.setItem('agvlog:settlement-adjustment:v1:tenant-a:actor-a','pending QA');await emit('actor-b');expect(client.getQueryData(['driver_settlements','tenant-a'])).toBeUndefined();expect(client.getMutationCache().getAll()).toHaveLength(0);expect(localStorage.getItem('agvlog:settlement-adjustment:v1:tenant-a:actor-a')).toBe('pending QA');});
 it('does not clear data on a redundant sign-in or ordinary token refresh',async()=>{render(<Story/>);await emit('actor-a');client.setQueryData(['stable'],123);await emit('actor-a');await emit('actor-a','TOKEN_REFRESHED','refreshed');expect(client.getQueryData(['stable'])).toBe(123);});
 it('reports logout refusal instead of silently pretending success',async()=>{render(<Story/>);await emit('actor-a');mock.signOut.mockResolvedValue({error:new Error('offline QA')});localStorage.setItem('agvlog_tenant_id','tenant-a');fireEvent.click(screen.getByText('Sair QA'));await waitFor(()=>expect(mock.toast).toHaveBeenCalledWith(expect.objectContaining({variant:'destructive'})));expect(screen.getByLabelText('actor')).toHaveTextContent('actor-a');expect(localStorage.getItem('agvlog_tenant_id')).toBe('tenant-a');});
 it('clears tenant and roles immediately on logout',async()=>{render(<Story tenant/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));await emit(null);expect(screen.getByLabelText('tenant')).toHaveTextContent('none');expect(screen.getByLabelText('role')).toHaveTextContent('none');});
 it('rejects selecting a tenant absent from current memberships',async()=>{render(<Story tenant/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));fireEvent.click(screen.getByText('Tenant inválido QA'));expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a');});
 it('does not reuse even an unscoped legacy query after switching tenants',async()=>{render(<Story tenant read/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('legacy')).toHaveTextContent('tenant-a'));fireEvent.click(screen.getByText('Trocar tenant QA'));await waitFor(()=>expect(screen.getByLabelText('legacy')).toHaveTextContent('tenant-b'));});
 it('cancels in-flight reads and ignores late completion after account replacement',async()=>{render(<Story/>);await emit('actor-a');const pending=deferred<string>();let signal:AbortSignal|undefined;const result=client.fetchQuery({queryKey:['late-private'],queryFn:context=>{signal=context.signal;return pending.promise;}}).catch(()=>undefined);await emit('actor-b');expect(signal?.aborted).toBe(true);pending.resolve('private actor-a');await result;expect(client.getQueryData(['late-private'])).toBeUndefined();});
 it('ignores a tenant response from the previous actor even if the transport ignores abort',async()=>{const pending=deferred<{data:ReturnType<typeof membership>[];error:null}>();mock.rpc.mockImplementationOnce(()=>Object.assign(pending.promise,{abortSignal:()=>pending.promise}));render(<Story tenant/>);await emit('actor-a');await emit('actor-b');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));await act(async()=>pending.resolve({data:[membership('old-actor-tenant','owner')],error:null}));expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a');expect(screen.getByLabelText('role')).toHaveTextContent('operator');});
 it('preserves a draft on ordinary refresh but removes it on tenant replacement',async()=>{render(<Story tenant/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));fireEvent.change(screen.getByLabelText('draft QA'),{target:{value:'private draft'}});await emit('actor-a','TOKEN_REFRESHED','renewed');await waitFor(()=>expect(mock.rpc.mock.calls.length).toBeGreaterThan(1));expect(screen.getByLabelText('draft QA')).toHaveValue('private draft');fireEvent.click(screen.getByText('Trocar tenant QA'));expect(screen.getByLabelText('draft QA')).toHaveValue('');});
 it('hides memberships on failed revalidation and recovers with an explicit retry',async()=>{render(<Story tenant/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));mock.rpc.mockImplementationOnce(()=>{const value=Promise.resolve({data:null,error:new Error('denied QA')});return Object.assign(value,{abortSignal:()=>value});});await emit('actor-a','TOKEN_REFRESHED','renewed');await screen.findByRole('alert');expect(screen.queryByLabelText('tenant')).not.toBeInTheDocument();fireEvent.click(screen.getByText('Tentar novamente'));await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));});
 it('does not let a delayed successful logout response clear the next account',async()=>{render(<Story/>);await emit('actor-a');const pending=deferred<{error:null}>();mock.signOut.mockReturnValue(pending.promise);fireEvent.click(screen.getByText('Sair QA'));await emit('actor-b');await act(async()=>pending.resolve({error:null}));expect(screen.getByLabelText('actor')).toHaveTextContent('actor-b');});
 it('survives storage denial without exposing an unverified tenant',async()=>{vi.spyOn(Storage.prototype,'getItem').mockImplementation(()=>{throw new Error('storage denied');});vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('quota');});vi.spyOn(Storage.prototype,'removeItem').mockImplementation(()=>{throw new Error('storage denied');});render(<Story tenant/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));await emit(null);expect(screen.getByLabelText('tenant')).toHaveTextContent('none');});
 it('recovers from bootstrap timeout after an authoritative auth event',async()=>{vi.useFakeTimers();mock.getSession.mockReturnValue(new Promise(()=>{}));render(<Story/>);await act(async()=>{await vi.advanceTimersByTimeAsync(8001);});expect(screen.getByLabelText('availability')).toHaveTextContent('true');await emit('actor-a');expect(screen.getByLabelText('availability')).toHaveTextContent('false');expect(screen.getByLabelText('actor')).toHaveTextContent('actor-a');});
 it('bounds a hung membership read and exposes no prior permissions',async()=>{vi.useFakeTimers();mock.rpc.mockImplementation(()=>{const request=new Promise(()=>{});return {abortSignal:()=>request};});render(<Story tenant/>);await emit('actor-a');await act(async()=>{await vi.advanceTimersByTimeAsync(8100);});expect(screen.getByRole('alert')).toHaveTextContent('Não foi possível confirmar seus acessos');expect(screen.queryByLabelText('role')).not.toBeInTheDocument();});
 it('unsubscribes under StrictMode and ignores completions after unmount',async()=>{const pending=deferred<{data:{session:Session};error:null}>();mock.getSession.mockReturnValue(pending.promise);const view=render(<StrictMode><Story/></StrictMode>);expect(mock.listeners.size).toBe(1);view.unmount();expect(mock.listeners.size).toBe(0);await act(async()=>pending.resolve({data:{session:session('actor-a')},error:null}));expect(client.getQueryCache().getAll()).toHaveLength(0);});
 it('cancels a global confirmation when replacing the account',async()=>{render(<Story/>);await emit('actor-a');let pending!:Promise<boolean>;act(()=>{pending=confirmAction('Ação privada da conta A');});expect(screen.getByRole('alertdialog')).toBeInTheDocument();await emit('actor-b');expect(screen.queryByRole('alertdialog')).not.toBeInTheDocument();await expect(pending).resolves.toBe(false);expect(useAlertStore.getState().description).toBe('');});
 it('cancels a global prompt when replacing the tenant',async()=>{render(<Story tenant/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));let pending!:Promise<string|null>;act(()=>{pending=promptAction('Justificativa privada do tenant A');});fireEvent.click(screen.getByText('Trocar tenant QA'));expect(screen.queryByRole('alertdialog')).not.toBeInTheDocument();await expect(pending).resolves.toBeNull();});
 it('keeps a global confirmation through an ordinary same-context refresh',async()=>{render(<Story tenant/>);await emit('actor-a');await waitFor(()=>expect(screen.getByLabelText('tenant')).toHaveTextContent('tenant-a'));let pending!:Promise<boolean>;act(()=>{pending=confirmAction('Ação do contexto atual');});await emit('actor-a','TOKEN_REFRESHED','same-context-refreshed');await waitFor(()=>expect(mock.rpc.mock.calls.length).toBeGreaterThan(1));expect(screen.getByRole('alertdialog')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Confirmar'}));await expect(pending).resolves.toBe(true);});
});
