import {beforeEach,it,expect,vi} from 'vitest';
import {createCashForecastOutbox,pendingCashForecast,cashForecastKey} from '@/lib/financial/cashForecastViewOutbox';
import {forecastIds as i,forecastInput as input,forecastSuccess} from './helpers/cashForecastViewFixture';
function setup(send:ReturnType<typeof vi.fn>){return createCashForecastOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),assertContext:()=>{},changed:()=>{},lock:async<T,>(_key:string,work:()=>Promise<T>)=>work(),send});}
beforeEach(()=>localStorage.clear());
it('recovers exact input after unknown and keeps uncertain request after known rejection',async()=>{const send=vi.fn().mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce({data:null,error:{code:'40001'}}).mockImplementationOnce(async c=>forecastSuccess(c));const box=setup(send);await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow('lost');await expect(box.recover(i.tenant,i.actor)).rejects.toMatchObject({code:'40001'});expect(pendingCashForecast(localStorage,i.tenant,i.actor)).not.toBeNull();await box.recover(i.tenant,i.actor);expect(send.mock.calls[2][0]).toEqual(send.mock.calls[0][0]);expect(pendingCashForecast(localStorage,i.tenant,i.actor)).toBeNull();});
it('clears only first definitive rejection and preserves incompatible actor response',async()=>{const send=vi.fn().mockResolvedValueOnce({data:null,error:{code:'23514'}}).mockImplementationOnce(async c=>({data:{...forecastSuccess(c).data,actor_id:crypto.randomUUID()},error:null}));const box=setup(send);await expect(box.submit(i.tenant,i.actor,input)).rejects.toMatchObject({code:'23514'});expect(pendingCashForecast(localStorage,i.tenant,i.actor)).toBeNull();await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow();expect(pendingCashForecast(localStorage,i.tenant,i.actor)).not.toBeNull();});
it('does not erase a different tab request after the original response',async()=>{const foreign='preserved-by-another-tab';const send=vi.fn().mockImplementation(async c=>{localStorage.setItem(cashForecastKey(i.tenant,i.actor),foreign);return forecastSuccess(c);});await setup(send).submit(i.tenant,i.actor,input);expect(localStorage.getItem(cashForecastKey(i.tenant,i.actor))).toBe(foreign);});

it('does not send after context changes',async()=>{const send=vi.fn();const box=createCashForecastOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{},assertContext:()=>{throw new Error('changed tenant');},lock:async<T,>(_key:string,work:()=>Promise<T>)=>work(),send});await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow('changed tenant');expect(send).not.toHaveBeenCalled();});
