import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {CashPeriodCloseWorkspace} from '@/components/financial/CashPeriodClosePanel';
import {CashPeriodRejectedError} from '@/lib/financial/cashPeriodClient';
const mock=vi.hoisted(()=>({counts:vi.fn(),preview:vi.fn(),history:vi.fn(),submit:vi.fn()}));
vi.mock('@/lib/financial/cashPeriodClient',()=>({readCashPeriodCounts:mock.counts,readCashPeriodPreview:mock.preview,submitCashPeriodDecision:mock.submit,CashPeriodRejectedError:class extends Error{}}));
vi.mock('@/lib/financial/accountPeriodCloseClient',()=>({readAccountPeriodHistory:mock.history,AccountPeriodCloseRejectedError:class extends Error{}}));
vi.mock('@/components/financial/LegacyCutReview',()=>({LegacyCutReview:()=>null}));vi.mock('@/components/financial/AccountPeriodEvidencePanel',()=>({AccountPeriodEvidencePanel:()=>null}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),count=crypto.randomUUID(),closure=crypto.randomUUID(),key=`finance-cash-period-decision:${tenant}:${actor}:${account}`,from='2026-01-01',to='2026-01-31';
const row={id:count,tenant_id:tenant,account_id:account,period_end:to,evidence_type:'cash_count_v1',currency:'BRL',timezone:'America/Sao_Paulo',boundary:'end_of_day',counts:[{denomination_cents:50,quantity:170}],total_cents:'8500',custodian_name:'João',actor_id:actor,actor_name:'Maria',reason:'Contagem física conferida',request_id:crypto.randomUUID(),revision:'b'.repeat(32),created_at:'2026-02-01',reversal:null,can_reverse:true};
const counts={version:1,tenant_id:tenant,account_id:account,period_end:to,page:1,page_size:30,total:1,active_count_id:count,can_record:false,can_reverse:true,rows:[row]};
const preview={version:1,tenant_id:tenant,account_id:account,from,to,currency:'BRL',timezone:'America/Sao_Paulo',evidence_type:'cash_count_v1',revision:'a'.repeat(32),eligible:true,can_execute:true,blockers:[],opening_id:crypto.randomUUID(),predecessor_id:null,count:row,balances:{opening_cents:'10000',in_cents:'1000',out_cents:'2500',expected_closing_cents:'8500',counted_closing_cents:'8500',difference_cents:'0',closing_cents:'8500'}};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.counts.mockResolvedValue(counts);mock.preview.mockResolvedValue(preview);mock.history.mockResolvedValue({version:1,tenant_id:tenant,account_id:account,total_count:0,offset:0,limit:30,can_execute:true,items:[]});mock.submit.mockResolvedValue({account_id:account,counted_cents:'10000'});});afterEach(()=>cleanup());
function open(end=to,cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><CashPeriodCloseWorkspace tenant={tenant} actor={actor} account={account} from={from} to={end}/></QueryClientProvider>);}
async function select(){fireEvent.click(await screen.findByRole('radio'));await screen.findByText('Sem diferença');}
function decision(){fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Motivo da decisão sobre o caixa'),{target:{value:'Contagem e movimentos conferidos'}});fireEvent.click(screen.getByRole('button',{name:'Revisar decisão sobre o caixa'}));}
it('requires explicit count selection and review and blocks a changed preview',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(to,cache);await screen.findByRole('radio');expect(mock.preview).not.toHaveBeenCalled();await select();decision();expect(mock.submit).not.toHaveBeenCalled();mock.preview.mockResolvedValue({...preview,revision:'c'.repeat(32),eligible:false,blockers:[{code:'cash_count_difference',source_table:null,source_ids:[],scope:'account'}],balances:{...preview.balances,difference_cents:'-500',expected_closing_cents:'9000'}});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-cash-period-close-preview']});});await screen.findByText('Falta: R$ 5,00');expect(screen.getByRole('button',{name:'Confirmar decisão sobre o caixa'})).toBeDisabled();expect(mock.submit).not.toHaveBeenCalled();});
it('records count only after denomination review and recovers the original date after lost response and period switch',async()=>{mock.counts.mockResolvedValue({...counts,active_count_id:null,total:0,rows:[],can_record:true});mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();fireEvent.change(await screen.findByLabelText('Responsável pela guarda do caixa'),{target:{value:'João'}});fireEvent.change(screen.getByLabelText('Quantidade final de R$ 100,00'),{target:{value:'1'}});fireEvent.change(screen.getByLabelText('Motivo da contagem final'),{target:{value:'Conferência física de encerramento'}});fireEvent.click(screen.getByRole('button',{name:'Revisar contagem final'}));expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar registro da contagem final'}));await screen.findByText(/decisão original foi preservada/);const original=mock.submit.mock.calls[0][0];expect(original.command).toMatchObject({period_end:to,counted_at_boundary:'end_of_day',account_id:account});view.unmount();open('2026-02-28');fireEvent.click(await screen.findByRole('button',{name:'Retomar decisão original do caixa'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('blocks corrupted storage and releases a first known rejection for fresh review',async()=>{sessionStorage.setItem(key,'broken');open();await screen.findByText(/recuperar a decisão/);expect(await screen.findByRole('radio')).toBeDisabled();cleanup();sessionStorage.clear();mock.submit.mockRejectedValueOnce(new CashPeriodRejectedError('finance_cash_count_changed'));open();await select();decision();fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão sobre o caixa'}));await screen.findByText(/contagem mudou/);await waitFor(()=>expect(sessionStorage.getItem(key)).toBeNull());expect(await screen.findByRole('radio')).not.toBeDisabled();});
it('uses row permission for count correction and reopens history independently of failed cash preview',async()=>{mock.counts.mockResolvedValue({...counts,rows:[{...row,can_reverse:false}]});mock.preview.mockRejectedValue(new Error('offline'));mock.history.mockResolvedValue({version:1,tenant_id:tenant,account_id:account,total_count:1,offset:0,limit:30,can_execute:true,items:[{id:closure,from,to,revision:'d'.repeat(32),actor_id:actor,actor_name:'Maria',reason:'Caixa conferido',created_at:'2026-02-01',active:true,can_reopen:true,active_descendant_ids:[],opening_cents:'10000',closing_cents:'8500',reopening:null}]});open();await screen.findByRole('radio');expect(screen.queryByRole('button',{name:`Revisar correção da contagem ${count}`})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('radio'));await screen.findByText(/Não foi possível conferir o saldo/);fireEvent.click(screen.getByRole('button',{name:`Revisar reabertura de ${from} a ${to}`}));decision();fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão sobre o caixa'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledOnce());expect(mock.submit.mock.calls[0][0]).toMatchObject({kind:'reopen',command:{closure_id:closure,revision:'d'.repeat(32)}});});
it('closes only the explicitly selected cash count after final review',async()=>{open();await select();decision();fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão sobre o caixa'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledOnce());expect(mock.submit.mock.calls[0][0]).toMatchObject({kind:'close',command:{account_id:account,from,to,count_id:count,revision:preview.revision}});expect(await screen.findByText(/Caixa fechado/)).toBeInTheDocument();});
it('retains denomination fields after the first definitive count rejection',async()=>{mock.counts.mockResolvedValue({...counts,active_count_id:null,total:0,rows:[],can_record:true});mock.submit.mockRejectedValueOnce(new CashPeriodRejectedError('finance_cash_count_busy'));open();fireEvent.change(await screen.findByLabelText('Responsável pela guarda do caixa'),{target:{value:'João'}});fireEvent.change(screen.getByLabelText('Quantidade final de R$ 100,00'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Motivo da contagem final'),{target:{value:'Conferência física de encerramento'}});fireEvent.click(screen.getByRole('button',{name:'Revisar contagem final'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar registro da contagem final'}));await screen.findByText(/Outra operação está alterando/);expect(await screen.findByLabelText('Quantidade final de R$ 100,00')).toHaveValue('2');expect(screen.getByLabelText('Responsável pela guarda do caixa')).toHaveValue('João');expect(sessionStorage.getItem(key)).toBeNull();});
