// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {financeIds as i} from './helpers/financeLedgerDatabase';
import {cashForecastCollectorSchema} from '@/lib/financial/cashForecastCollectorContract';
import {projectCollectedCashForecast} from '@/lib/financial/cashForecastCollectorProjection';
import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createCashForecastAgendaDatabase} from './helpers/cashForecastAgendaDatabase';
import {installCustomerCreditCapturedPredecessors} from './helpers/customerCreditApplicationDatabase';
it('applies cancellation credit once in the real forecast while preserving bank records',async()=>{
 const db=await createCashForecastAgendaDatabase();try{
  const lifecycle=readFileSync('supabase/migrations/20260830192908_audit_client_invoice_lifecycle.sql','utf8');
  const commandTable=lifecycle.match(/create table public\.client_invoice_commands\([\s\S]*?\n\);/)![0];
  // Composite identity keys required by the original invoice command foreign keys.
  await db.exec('alter table public.client_invoices add unique(tenant_id,id);alter table public.closing_reports add unique(tenant_id,id)');
  await db.exec(commandTable);
  await db.exec('alter table public.receivables add column cte_document_id uuid');
  const fiscalContext=readFileSync('supabase/migrations/20260910012152_finance_receivable_fiscal_context.sql','utf8');
  await db.exec(fiscalContext.slice(0,fiscalContext.indexOf('do $context$')));
  await installCustomerCreditCapturedPredecessors(db);
  await db.exec(readFileSync('supabase/migrations/20260911101312_finance_customer_credit_applications.sql','utf8'));
  await db.exec(readFileSync('supabase/migrations/20260911102519_finance_cash_forecast_applied_credit_balance.sql','utf8'));
  await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);
  await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);
  const payer=randomUUID(),original=randomUUID();
  await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Crédito para previsão',true)",[payer,i.tenant]);
  await db.query("insert into receivables(id,tenant_id,client_id,amount,received_amount,status,description,due_date) values($1,$2,$3,1000,0,'pending','Origem recebida',current_date+5)",[original,i.tenant,payer]);
  const context=(await db.query<{v:{revision:string}}> ('select public._receivable_financial_snapshot($1,$2) v',[i.tenant,original])).rows[0].v;
  const day=(await db.query<{v:string}>("select (clock_timestamp() at time zone 'America/Sao_Paulo')::date::text v")).rows[0].v;
  await db.query('select public.apply_receivable_financial_command($1)',[{version:1,tenant_id:i.tenant,actor_id:i.operator,request_id:randomUUID(),receivable_id:original,expected_revision:context.revision,action:'receive',amount_cents:60000,effective_date:day,bank_account_id:i.account,method:'pix',reason:'Recebimento real na fixture de previsão'}]);
  const emission=randomUUID(),observation=randomUUID(),origin=randomUUID(),source=randomUUID();
  // Existing fiscal facts in an isolated fixture; no provider/issuer is called.
  await db.query("insert into hub_fiscal_emissions(id,tenant_id,doc_type,environment,status,dispatch_state,cte_document_id,access_key,authorization_protocol,number,sync_attempts,created_at,updated_at) values($1,$2,'cte','production','cancelled','recorded',$3,$4,$5,'1',0,clock_timestamp(),clock_timestamp())",[emission,i.tenant,source,'1'.repeat(44),'2'.repeat(15)]);
  await db.query("insert into finance_fiscal_observations(id,tenant_id,emission_id,snapshot_hash,snapshot) values($1,$2,$3,'fixture-cancelled-observation','{}')",[observation,i.tenant,emission]);
  await db.query("insert into finance_fiscal_receivable_origins(id,tenant_id,doc_type,source_id,fiscal_identity,emission_id,receivable_id,observation_id,state,basis) values($1,$2,'cte',$3,'fixture-credit-forecast',$4,$5,$6,'active',$7)",[origin,i.tenant,source,emission,original,observation,{payer_id:payer}]);
  expect((await db.query<{v:unknown}>('select finance_private.release_cancelled_receipts($1,$2,$3) v',[i.tenant,origin,observation])).rows[0].v).toBe(null);
  await db.query("update finance_fiscal_receivable_origins set state='cancelled' where id=$1",[origin]);
  const credit=(await db.query<{id:string}>('select id from finance_customer_credits where receivable_id=$1',[original])).rows[0].id;
  const target=(await db.query<{id:string}>("insert into receivables(tenant_id,client_id,amount,received_amount,status,description,due_date) values($1,$2,500,0,'pending','Destino do crédito',current_date+5) returning id",[i.tenant,payer])).rows[0].id;
  const collect=async()=>cashForecastCollectorSchema.parse((await db.query<{v:unknown}>('select finance_private.cash_forecast_collect($1,current_date-1,current_date+30) v',[i.tenant])).rows[0].v);
  let collection=await collect();expect(collection.unassigned_credit_cents).toBe('60000');
  const capture=(await db.query<{v:{snapshot_id:string}}> ('select finance_private.record_cash_forecast_snapshot($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),cutoff:collection.cutoff,period_end:collection.period_end,source_revision:collection.revision,title:'Antes da aplicação do crédito',reason:'Preservar previsão anterior à decisão'}])).rows[0].v;
  const preserved=async()=>(await db.query('select to_jsonb(s) v from finance_private.cash_forecast_snapshots s where id=$1',[capture.snapshot_id])).rows;
  const originalCapture=await preserved();
  const beforeBank=(await db.query('select to_jsonb(b) v from bank_transactions b order by id')).rows;
  const beforePayments=(await db.query('select to_jsonb(p) v from receivables_payments p order by id')).rows;
  const preview=(await db.query<{v:{revision:string,eligible:boolean}}>('select finance_private.customer_credit_application_context($1,$2,$3,$4,null) v',[i.tenant,credit,target,'40000'])).rows[0].v;
  expect(preview.eligible).toBe(true);
  const application=(await db.query<{v:{application_id:string}}> ('select finance_private.record_customer_credit_application($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),credit_id:credit,receivable_id:target,application_id:null,action:'apply',amount_cents:'40000',expected_revision:preview.revision,reason:'Vincular crédito já recebido à nova dívida'}])).rows[0].v;
  collection=await collect();expect(collection.unassigned_credit_cents).toBe('20000');
  expect(collection.origins.find(r=>r.source_id===target)).toMatchObject({nominal_cents:'50000',fulfilled_cents:'0',reserved_credit_cents:'40000',valid:true});
  const reviewAgenda=async()=>{const c=await collect();await db.query('select finance_private.record_cash_forecast_agenda($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),economic_key:'receivable:'+target,action:'set',expected_on:c.period_end,expected_revision:c.revision,cutoff:c.cutoff,period_end:c.period_end,reason:'Conferir expectativa sobre o saldo restante'}]);};
  await reviewAgenda();collection=await collect();
  expect(projectCollectedCashForecast(collection,collection).projection!.scheduled.confirmed_in_cents).toBe('10000');
  const second=(await db.query<{id:string}>("insert into receivables(tenant_id,client_id,amount,received_amount,status,description,due_date) values($1,$2,200,0,'pending','Segundo destino do crédito',current_date+5) returning id",[i.tenant,payer])).rows[0].id;
  const secondPreview=(await db.query<{v:{revision:string,eligible:boolean}}> ('select finance_private.customer_credit_application_context($1,$2,$3,$4,null) v',[i.tenant,credit,second,'20000'])).rows[0].v;
  expect(secondPreview.eligible).toBe(true);
  await db.query('select finance_private.record_customer_credit_application($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),credit_id:credit,receivable_id:second,application_id:null,action:'apply',amount_cents:'20000',expected_revision:secondPreview.revision,reason:'Vincular saldo remanescente ao segundo título'}]);
  collection=await collect();expect(collection.unassigned_credit_cents).toBe('0');expect(collection.credits[0]).toMatchObject({amount_cents:'0',valid:true});
  expect(collection.source_issues.some(x=>x.code==='unassigned_customer_credit')).toBe(false);
  const projected=projectCollectedCashForecast(collection,collection);expect(projected.projection!.scheduled.confirmed_in_cents).toBe('10000');
  expect((await db.query<{v:unknown}>('select finance_private.project_collected_cash_forecast($1) v',[collection])).rows[0].v).toEqual(projected);
  expect((await db.query('select to_jsonb(b) v from bank_transactions b order by id')).rows).toEqual(beforeBank);
  expect((await db.query('select to_jsonb(p) v from receivables_payments p order by id')).rows).toEqual(beforePayments);
  const receiveContext=(await db.query<{v:{revision:string}}> ('select public._receivable_financial_snapshot($1,$2) v',[i.tenant,target])).rows[0].v;
  await db.query('select public.apply_receivable_financial_command($1)',[{version:1,tenant_id:i.tenant,actor_id:i.operator,request_id:randomUUID(),receivable_id:target,expected_revision:receiveContext.revision,action:'receive',amount_cents:10000,effective_date:day,bank_account_id:i.account,method:'pix',reason:'Receber somente saldo que falta após crédito'}]);
  collection=await collect();expect(collection.origins.find(r=>r.source_id===target)).toMatchObject({fulfilled_cents:'10000',reserved_credit_cents:'40000'});
  expect(projectCollectedCashForecast(collection,collection).projection!.scheduled.confirmed_in_cents).toBe('0');
  expect(collection.origins.find(r=>r.source_id===target)!.agenda?.stale).toBe(true);
  expect(collection.source_issues.some(r=>r.code==='forecast_agenda_source_changed'&&r.source_ids.includes(target))).toBe(false);
  const afterRealCashBank=(await db.query('select to_jsonb(b) v from bank_transactions b order by id')).rows;
  const afterRealCashPayments=(await db.query('select to_jsonb(p) v from receivables_payments p order by id')).rows;
  expect(afterRealCashBank.length).toBe(beforeBank.length+1);expect(afterRealCashPayments.length).toBe(beforePayments.length+1);
  const releasePreview=(await db.query<{v:{revision:string,eligible:boolean}}> ('select finance_private.customer_credit_application_context($1,$2,$3,$4,$5) v',[i.tenant,credit,target,'40000',application.application_id])).rows[0].v;
  expect(releasePreview.eligible).toBe(true);
  await db.query('select finance_private.record_customer_credit_application($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),credit_id:credit,receivable_id:target,application_id:application.application_id,action:'release',amount_cents:'40000',expected_revision:releasePreview.revision,reason:'Liberar aplicação sem simular devolução bancária'}]);
  collection=await collect();expect(collection.unassigned_credit_cents).toBe('40000');expect(collection.source_issues.some(r=>r.code==='forecast_agenda_source_changed'&&r.source_ids.includes(target))).toBe(true);await reviewAgenda();collection=await collect();expect(projectCollectedCashForecast(collection,collection).projection!.scheduled.confirmed_in_cents).toBe('40000');
  await db.exec('savepoint source_review');
  await db.query("update finance_fiscal_receivable_origins set state='review' where id=$1",[origin]);
  const uncertain=await collect();expect(uncertain.unassigned_credit_cents).toBe(null);
  expect(uncertain.credits[0]).toMatchObject({valid:false,amount_cents:null});
  expect(uncertain.origins.find(r=>r.source_id===second)).toMatchObject({valid:false,nominal_cents:null,fulfilled_cents:null,reserved_credit_cents:null});
  expect(projectCollectedCashForecast(uncertain,uncertain).projection!.confirmed.complete).toBe(false);
  await db.exec('rollback to source_review');
  expect(await preserved()).toEqual(originalCapture);
  expect((await db.query('select to_jsonb(b) v from bank_transactions b order by id')).rows).toEqual(afterRealCashBank);
  expect((await db.query('select to_jsonb(p) v from receivables_payments p order by id')).rows).toEqual(afterRealCashPayments);
  expect((await db.query<{v:boolean}>("select has_function_privilege('authenticated','finance_private.forecast_customer_credit_evidence(uuid,uuid)','execute') v")).rows[0].v).toBe(false);
 }finally{await db.close();}
},30000);
