// @vitest-environment node
import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createCashForecastAgendaDatabase} from './helpers/cashForecastAgendaDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {cashForecastAgendaPreviewSchema,cashForecastAgendaResultSchema} from '@/lib/financial/cashForecastAgendaContract';
let db:Awaited<ReturnType<typeof createCashForecastAgendaDatabase>>;
const boundary=()=>readFileSync('supabase/migrations/20260911100348_finance_cash_forecast_agenda_public_boundary.sql','utf8');
beforeAll(async()=>{db=await createCashForecastAgendaDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});afterEach(async()=>db.exec('rollback'));afterAll(async()=>db.close());
async function install(){await db.exec(boundary());}
async function seed(){const client=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Agenda publica QA',true)",[client,i.tenant]);const id=(await db.query<{id:string}>("insert into receivables(tenant_id,client_id,amount,received_amount,status,due_date,description) values($1,$2,150,0,'pending',current_date-5,'Agenda publica preservada') returning id",[i.tenant,client])).rows[0].id;const dates=(await db.query<{cutoff:string,end:string}>("select (current_date-1)::text cutoff,(current_date+30)::text end")).rows[0];return{id,key:'receivable:'+id,...dates};}
async function preview(s:{key:string,cutoff:string,end:string}){return cashForecastAgendaPreviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select preview_finance_cash_forecast_agenda($1,$2,$3,$4) v',[i.tenant,s.cutoff,s.end,s.key])).rows[0].v);}
async function payload(s:{key:string,cutoff:string,end:string},action:'set'|'clear'='set'){const p=await preview(s);return {version:1,tenant_id:i.tenant,request_id:randomUUID(),cutoff:s.cutoff,period_end:s.end,economic_key:s.key,action,expected_on:action==='set'?s.end:null,expected_revision:p.revision,reason:'Data prevista revisada pelo financeiro'};}
async function write(p:unknown){return cashForecastAgendaResultSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select record_finance_cash_forecast_agenda($1) v',[p])).rows[0].v);}
it('captures the actual private catalogue used by the promotion',async()=>{if(process.env.CAPTURE_AGENDA_PUBLIC==='1'){const functions=(await db.query("select p.oid::regprocedure::text signature,md5(replace(p.prosrc,E'\\r\\n',E'\\n')) prosrc_md5,p.prosecdef,p.provolatile,p.proconfig,p.proacl::text acl from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='finance_private' and p.proname in('cash_forecast_collect','cash_forecast_collect_before_agenda','cash_forecast_agenda_preview','record_cash_forecast_agenda','forecast_agenda_projection_input','project_collected_cash_forecast','preserve_event','audit_events') order by signature")).rows;const triggers=(await db.query("select tgname,tgrelid::regclass::text relation,tgfoid::regprocedure::text function,tgtype,tgenabled,tgdeferrable,tginitdeferred,tgnargs,pg_get_expr(tgqual,tgrelid) qual from pg_trigger where tgrelid='finance_private.cash_forecast_agenda_events'::regclass order by tgname")).rows;writeFileSync('docs/qa/finance-cash-forecast-agenda-core-catalog-2026-09-11.json',JSON.stringify({functions,triggers},null,2)+'\n');}expect((await db.query<{v:boolean}>("select has_function_privilege('authenticated','finance_private.record_cash_forecast_agenda(jsonb)','execute') v")).rows[0].v).toBe(false);});
it('publishes a scoped preview and set/replay/clear with immutable due date',async()=>{await install();const s=await seed();const original=(await db.query('select to_jsonb(r) v from receivables r where id=$1',[s.id])).rows;const ctx=await preview(s);expect(ctx).toMatchObject({tenant_id:i.tenant,actor_id:i.operator,eligible:true,can_execute:true});const p=await payload(s);const result=await write(p);expect(await write(p)).toEqual(result);expect((await preview(s)).origin).toMatchObject({expected_on:s.end,expected_date_source:'reviewed_date',agenda:{stale:false}});await write(await payload(s,'clear'));expect((await preview(s)).origin.expected_date_source).toBe('due_date');expect((await db.query('select to_jsonb(r) v from receivables r where id=$1',[s.id])).rows).toEqual(original);expect((await db.query<{n:number}>('select count(*)::int n from finance_private.cash_forecast_agenda_events')).rows[0].n).toBe(2);});
it('rejects stale revision, another tenant, mixed driver, anon/raw and revoked replay',async()=>{await install();const s=await seed();const p=await payload(s);await expect(financeAs(db,i.operator,'select finance_private.record_cash_forecast_agenda($1)',[p])).rejects.toMatchObject({code:'42501'});await expect(write({...p,tenant_id:i.otherTenant})).rejects.toMatchObject({code:'42501'});await db.exec('savepoint anon;set role anon');await expect(db.query('select preview_finance_cash_forecast_agenda($1,$2,$3,$4)',[i.tenant,s.cutoff,s.end,s.key])).rejects.toMatchObject({code:'42501'});await db.exec('rollback to savepoint anon');await db.exec('savepoint mixed');await db.query("insert into tenant_memberships(tenant_id,user_id,role,active) values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(write(p)).rejects.toMatchObject({code:'42501'});await db.exec('rollback to savepoint mixed');await write(p);await expect(write({...p,request_id:randomUUID()})).rejects.toMatchObject({code:'40001'});await db.query('update tenant_memberships set active=false where tenant_id=$1 and user_id=$2',[i.tenant,i.operator]);await expect(write(p)).rejects.toMatchObject({code:'42501'});});
it('fails closed on unavailable dispatcher and refuses altered immutable trigger',async()=>{await db.exec('savepoint drift;drop trigger preserve_cash_forecast_agenda on finance_private.cash_forecast_agenda_events;create trigger preserve_cash_forecast_agenda before update on finance_private.cash_forecast_agenda_events for each row when(false) execute function finance_private.preserve_event()');await expect(install()).rejects.toMatchObject({code:'55000'});await db.exec('rollback to savepoint drift');await install();const s=await seed();await db.exec('revoke execute on function finance_private.dispatch_cash_forecast_agenda(jsonb) from authenticated');expect((await preview(s)).can_execute).toBe(false);});

it('rolls back agenda and central audit together when the audit append fails',async()=>{await install();const s=await seed();const p=await payload(s);await db.exec("create function public.qa_agenda_audit_fault() returns trigger language plpgsql as $$begin if new.action in('cash_forecast_agenda_set','cash_forecast_agenda_cleared') then raise exception 'qa_agenda_audit_fault';end if;return new;end$$;create trigger qa_agenda_audit_fault before insert on finance_events for each row execute function public.qa_agenda_audit_fault()");await expect(write(p)).rejects.toThrow('qa_agenda_audit_fault');expect((await db.query<{n:number}>('select count(*)::int n from finance_private.cash_forecast_agenda_events')).rows[0].n).toBe(0);await db.exec('drop trigger qa_agenda_audit_fault on finance_events');const result=await write(p);expect(await write(p)).toEqual(result);expect((await db.query<{n:number}>("select count(*)::int n from finance_events where action='cash_forecast_agenda_set' and entity_id=$1",[result.event_id])).rows[0].n).toBe(1);});
