// @vitest-environment node
import {beforeAll,beforeEach,afterAll,afterEach,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {createCashForecastCollectorDatabase} from './helpers/cashForecastCollectorDatabase';
import {installCashForecastPureProjection} from './helpers/cashForecastPureProjectionDatabase';
import {financeIds as i,financeAs} from './helpers/financeLedgerDatabase';
import {cashForecastCollectorSchema} from '@/lib/financial/cashForecastCollectorContract';
import {projectCollectedCashForecast} from '@/lib/financial/cashForecastCollectorProjection';
let db:Awaited<ReturnType<typeof createCashForecastCollectorDatabase>>;
beforeAll(async()=>{db=await createCashForecastCollectorDatabase();await installCashForecastPureProjection(db);},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function compare(){const value=cashForecastCollectorSchema.parse((await db.query<{v:unknown}>("select finance_private.cash_forecast_collect($1,'2026-08-31',current_date+30) v",[i.tenant])).rows[0].v);const expected=projectCollectedCashForecast(value,value);const actual=(await db.query<{v:unknown}>('select finance_private.project_collected_cash_forecast($1::jsonb) v',[JSON.stringify(value)])).rows[0].v;expect(actual).toEqual(expected);return expected;}
async function payer(){const id=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Cliente de equivalência',true)",[id,i.tenant]);return id;}
async function rpc<T>(name:string,args:unknown[]){return(await financeAs<{v:T}>(db,i.operator,`select ${name}(${args.map((_,j)=>'$'+(j+1)).join(',')}) v`,args)).rows[0].v;}
it('matches full SQL collection of1005 freight sources, not merchandise',async()=>{const client=await payer();await db.query("insert into fiscal_documents(id,tenant_id,document_type,status,client_id,issue_date,freight_value,value,is_duplicate) select gen_random_uuid(),$1,'inbound','pending',$2,'2026-08-01',1.01,999999,false from generate_series(1,1005)",[i.tenant,client]);const result=await compare();expect(result.collection.counts.origins).toBe(1005);expect(result.projection?.rows).toHaveLength(1005);expect(result.projection?.unscheduled.unbilled_cents).toBe('101505');},30000);
it('matches canonical partial receipt money and remaining title from real commands',async()=>{const client=await payer();const title=(await db.query<{id:string}>("insert into receivables(tenant_id,client_id,amount,received_amount,status,due_date,description) values($1,$2,150,0,'pending','2026-10-10','Título de equivalência') returning id",[i.tenant,client])).rows[0].id;const base=()=>({version:1,tenant_id:i.tenant,request_id:randomUUID(),reason:'Conferência de equivalência da projeção'});const movement=await rpc<{movement_id:string}>('record_finance_movement',[{...base(),bank_account_id:i.account,direction:'in',nature:'receipt',amount_cents:5000,occurred_on:'2026-09-01',description:'Recebimento parcial comprovado',beneficiary_name:'Cliente de equivalência'}]);const ctx=await rpc<{revision:string}>('get_receivable_financial_context',[i.tenant,title]);await rpc('apply_receivable_financial_command',[{...base(),actor_id:i.operator,receivable_id:title,expected_revision:ctx.revision,action:'receive',amount_cents:5000,effective_date:'2026-09-01',bank_account_id:i.account,method:'pix',movement_id:movement.movement_id}]);const result=await compare();expect(result.projection?.recorded_totals.in_cents).toBe('5000');expect(result.projection?.rows.find(r=>r.source_id===title)?.remaining_cents).toBe('10000');},30000);
it('keeps malformed historical credit and paid title indeterminate in the real collection',async()=>{const client=await payer();await db.query("insert into payables(id,tenant_id,supplier_name,amount,paid_amount,status,description,due_date) values(gen_random_uuid(),$1,'Fornecedor',150,150,'paid','Sem prova','2026-10-01')",[i.tenant]);await db.query("insert into finance_customer_credits(id,tenant_id,payer_id,origin_id,receivable_id,payment_id,bank_transaction_id,observation_id,amount_cents,receipt_snapshot) values($1,$2,$3,$4,$5,$6,$7,$8,3000,'{}')",[randomUUID(),i.tenant,client,randomUUID(),randomUUID(),randomUUID(),randomUUID(),randomUUID()]);const result=await compare();expect(result.projection?.unassigned_credit_cents).toBeNull();expect(result.projection?.confirmed.closing_cents).toBeNull();expect(result.collection.origins.some(r=>!r.valid&&r.nominal_cents===null)).toBe(true);},30000);
