// @vitest-environment node
import {beforeAll,afterAll,it,expect} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {projectCollectedCashForecast} from '@/lib/financial/cashForecastCollectorProjection';
import type {CashForecastCollector} from '@/lib/financial/cashForecastCollectorContract';
import {installCashForecastPureProjection} from './helpers/cashForecastPureProjectionDatabase';
let db:PGlite;beforeAll(async()=>{db=new PGlite();await db.exec('create schema finance_private;create role anon;create role authenticated;create role service_role;');await installCashForecastPureProjection(db);},30000);afterAll(async()=>{await db?.close();});
const id=()=>crypto.randomUUID(),rev='a'.repeat(32);
function fixture():CashForecastCollector{const account=id();return {version:1,tenant_id:id(),actor_id:id(),captured_at:'2026-09-11T12:00:00Z',revision:rev,basis:'current_company_cash_forecast',cutoff:'2026-09-10',period_end:'2026-09-30',account_scope:{mode:'whole_company',account_ids:[account]},base:{as_of:'2026-09-10',amount_cents:'100000',confirmation:'bank_confirmed',components:[{account_id:account,account_kind:'bank',source_table:'finance_account_openings',source_id:id(),source_revision:rev,amount_cents:'100000',confirmation:'bank_confirmed'}]},origins:[{economic_key:'title',source_table:'receivables',source_id:id(),source_revision:rev,direction:'in',scenario:'confirmed',nominal_cents:'10000',fulfilled_cents:'6000',reserved_credit_cents:'0',expected_on:'2026-09-20',expected_date_source:'due_date',valid:true}],recorded_after_cutoff:[{movement_id:id(),account_id:account,source_revision:rev,occurred_on:'2026-09-11',direction:'in',amount_cents:'6000',confirmation:'recorded'}],unassigned_credit_cents:'0',credits:[],source_issues:[],counts:{accounts:1,origins:1,movements:1,credits:0}};}
async function sql(c:unknown){return (await db.query<{v:unknown}>('select finance_private.project_collected_cash_forecast($1::jsonb) v',[JSON.stringify(c)])).rows[0].v;}
async function same(c:CashForecastCollector){const expected=projectCollectedCashForecast(c,c);expect(await sql(c)).toEqual(expected);return expected;}
it('matches partial receipt once, reserved credit, outputs, timing and >1000 sources',async()=>{const c=fixture();expect((await same(c)).projection?.confirmed.closing_cents).toBe('110000');c.origins=Array.from({length:1005},(_,n)=>({...c.origins[0],economic_key:'origin'+n,source_id:id(),direction:n%2?'out':'in',nominal_cents:'10000',fulfilled_cents:'6000',reserved_credit_cents:'1000',expected_on:n%7===0?null:n%7===1?'2026-09-01':n%7===2?'2026-10-01':'2026-09-20',expected_date_source:n%7===0?'unknown':'due_date'}));c.counts.origins=c.origins.length;expect((await same(c)).projection?.rows).toHaveLength(1005);},30000);
it('matches mixed account bases, provisional base and unknown component',async()=>{const c=fixture();const cash=id();c.account_scope.account_ids.push(cash);c.counts.accounts=2;c.base.components.push({account_id:cash,account_kind:'cash',source_table:'finance_account_openings',source_id:id(),source_revision:rev,amount_cents:'2000',confirmation:'cash_count'});c.base.amount_cents='102000';c.base.confirmation='mixed_confirmed';await same(c);c.base.components[1].confirmation='provisional';c.base.confirmation='provisional';await same(c);c.base.components[1].confirmation='unverified';c.base.components[1].amount_cents=null;c.base.amount_cents=null;c.base.confirmation='unverified';await same(c);});
it('matches issue scopes, invalid origins and unknown credits without zero',async()=>{const c=fixture();c.origins.push({...c.origins[0],economic_key:'unbilled',source_id:id(),source_table:'fiscal_documents',scenario:'unbilled',valid:false,nominal_cents:null,fulfilled_cents:null,reserved_credit_cents:null});c.counts.origins=2;expect((await same(c)).projection?.confirmed.complete).toBe(true);c.origins[1].scenario='confirmed';expect((await same(c)).projection?.confirmed.complete).toBe(false);c.credits.push({credit_id:id(),payer_id:id(),source_payment_id:id(),source_revision:rev,valid:false,amount_cents:null});c.counts.credits=1;c.unassigned_credit_cents=null;expect((await same(c)).projection?.unassigned_credit_cents).toBeNull();});
it('returns projectionnull for no accounts and respects capture day in Sao Paulo',async()=>{const c=fixture();c.captured_at='2026-09-12T01:00:00Z';await same(c);c.account_scope.account_ids=[];c.base={as_of:c.cutoff,amount_cents:null,confirmation:'unverified',components:[]};c.counts.accounts=0;c.recorded_after_cutoff=[];c.counts.movements=0;expect((await same(c)).projection).toBeNull();});
it('rejects incoherence instead of clamping counts, coverage, accounts, dates or money',async()=>{const changes:Array<(c:CashForecastCollector)=>void>=[c=>{c.counts.origins=0;},c=>{c.base.amount_cents='0';},c=>{c.origins[0].fulfilled_cents='10001';},c=>{c.origins[0].nominal_cents='NaN';},c=>{c.recorded_after_cutoff[0].account_id=id();},c=>{c.recorded_after_cutoff[0].occurred_on='2026-09-12';},c=>{c.base.components[0].confirmation='cash_count';},c=>{c.unassigned_credit_cents='1';},c=>{c.origins.push({...c.origins[0]});c.counts.origins=2;},c=>{c.period_end='2026-02-30';},c=>{c.captured_at='2026-09-11T24:00:00Z';}];for(const change of changes){const c=fixture();change(c);await expect(sql(c)).rejects.toThrow();expect(()=>projectCollectedCashForecast(c,c)).toThrow();}});
it('has no grants and uses no definer or mutable database state',async()=>{const r=await db.query<{prosecdef:boolean;provolatile:string;proconfig:string[];anon:boolean;authenticated:boolean;service:boolean}>("select prosecdef,provolatile,proconfig,has_function_privilege('anon',oid,'execute') anon,has_function_privilege('authenticated',oid,'execute') authenticated,has_function_privilege('service_role',oid,'execute') service from pg_proc where oid='finance_private.project_collected_cash_forecast(jsonb)'::regprocedure");expect(r.rows[0]).toEqual({prosecdef:false,provolatile:'i',proconfig:['search_path=""'],anon:false,authenticated:false,service:false});});

it('preserves issue scope and positive unassigned credits without guessing their allocation',async()=>{const c=fixture();c.base.amount_cents='-100000';c.base.components[0].amount_cents='-100000';c.source_issues=[{scope:'expanded',code:'freight_under_review',source_ids:[]}];expect((await same(c)).projection?.confirmed.closing_cents).toBe('-90000');c.source_issues[0].scope='all';expect((await same(c)).projection?.confirmed.closing_cents).toBeNull();c.source_issues=[];c.credits=[{credit_id:id(),payer_id:id(),source_payment_id:id(),source_revision:rev,amount_cents:'1000',valid:true}];c.counts.credits=1;c.unassigned_credit_cents='1000';const result=await same(c);expect(result.projection?.rows[0].remaining_cents).toBe('4000');expect(result.issues).toContainEqual({code:'unassigned_customer_credit',source_ids:[]});});
