// @vitest-environment node
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';
import {createCashForecastCollectorDatabase} from './helpers/cashForecastCollectorDatabase';import {financeIds as i} from './helpers/financeLedgerDatabase';
import {cashForecastCollectorSchema} from '@/lib/financial/cashForecastCollectorContract';import {projectCollectedCashForecast} from '@/lib/financial/cashForecastCollectorProjection';
let db:Awaited<ReturnType<typeof createCashForecastCollectorDatabase>>;
beforeAll(async()=>{db=await createCashForecastCollectorDatabase();await db.exec(readFileSync('docs/qa/finance-manual-audit-predecessor-2026-09-11.sql','utf8'));for(const n of ['20260911084618_finance_cash_forecast_pure_projection','20260911084626_finance_cash_forecast_preserved_snapshots','20260911094523_finance_current_manual_audit_actions','20260911094505_finance_cash_forecast_audited_agenda'])await db.exec(readFileSync('supabase/migrations/'+n+'.sql','utf8'));},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});afterEach(async()=>db.exec('rollback'));afterAll(async()=>db?.close());
async function collect(){return cashForecastCollectorSchema.parse((await db.query<{v:unknown}>("select finance_private.cash_forecast_collect($1,current_date-1,current_date+30) v",[i.tenant])).rows[0].v);}
async function seed(){const client=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Agenda QA',true)",[client,i.tenant]);return(await db.query<{id:string}>("insert into receivables(tenant_id,client_id,amount,received_amount,status,due_date,description) values($1,$2,150,0,'pending',current_date-5,'Agenda preservada') returning id",[i.tenant,client])).rows[0].id;}
async function command(id:string,action='set'){const c=await collect();return{version:1,tenant_id:i.tenant,request_id:randomUUID(),cutoff:c.cutoff,period_end:c.period_end,economic_key:'receivable:'+id,action,expected_on:action==='set'?c.period_end:null,expected_revision:c.revision,reason:'Revisão explícita da data prevista'};}
async function write(p:unknown){return(await db.query<{v:unknown}>('select finance_private.record_cash_forecast_agenda($1) v',[p])).rows[0].v;}
it('sets/replays/clears reviewed date without changing due date or a preserved capture; SQL/TS remain equal',async()=>{const id=await seed(),initial=await collect();const save=(await db.query<{v:{snapshot_id:string}}>('select finance_private.record_cash_forecast_snapshot($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),cutoff:initial.cutoff,period_end:initial.period_end,source_revision:initial.revision,title:'Agenda antes da revisão',reason:'Preservação antes de revisar agenda'}])).rows[0].v;const original=(await db.query<{v:unknown}>('select finance_private.read_cash_forecast_snapshot($1,$2) v',[i.tenant,save.snapshot_id])).rows[0].v;const p=await command(id);const result=await write(p);expect(await write(p)).toEqual(result);let c=await collect();const row=c.origins[0];expect(row).toMatchObject({expected_on:c.period_end,expected_date_source:'reviewed_date',original_expected_on:initial.origins[0].expected_on,agenda:{stale:false}});expect(row.agenda!.history).toHaveLength(1);expect((await db.query<{v:unknown}>('select finance_private.project_collected_cash_forecast($1) v',[c])).rows[0].v).toEqual(projectCollectedCashForecast(c,c));await write(await command(id,'clear'));c=await collect();expect(c.origins[0]).toMatchObject({expected_on:initial.origins[0].expected_on,expected_date_source:'due_date'});expect(c.origins[0].agenda!.history).toHaveLength(2);expect((await db.query<{v:unknown}>('select finance_private.read_cash_forecast_snapshot($1,$2) v',[i.tenant,save.snapshot_id])).rows[0].v).toEqual(original);expect((await db.query<{n:number}>('select count(*)::int n from finance_movements')).rows[0].n).toBe(0);});
it('rejects stale revision, invalid date and replay conflict; source change marks date stale',async()=>{const id=await seed(),p=await command(id);await write(p);for(const bad of [{...p,request_id:randomUUID()},{...p,reason:'Outro motivo revisado'}]){await db.exec('savepoint bad');await expect(write(bad)).rejects.toBeDefined();await db.exec('rollback to bad');}await db.query('update receivables set amount=200 where id=$1',[id]);let c=await collect();expect(c.origins[0]).toMatchObject({expected_on:null,expected_date_source:'unknown',agenda:{stale:true}});expect(c.source_issues.some(x=>x.code==='forecast_agenda_source_changed')).toBe(true);await write(await command(id));c=await collect();expect(c.origins[0].agenda!.stale).toBe(false);const invalid={...await command(id),expected_on:'2020-01-01'};await db.exec('savepoint past');await expect(write(invalid)).rejects.toMatchObject({code:'22023'});await db.exec('rollback to past');expect((await db.query<{n:number}>('select count(*)::int n from finance_private.cash_forecast_agenda_events')).rows[0].n).toBe(2);});

it('denies foreign/mixed access, missing source and rolls back journal on failure',async()=>{const id=await seed();const p=await command(id);for(const bad of [{...p,tenant_id:i.otherTenant},{...p,economic_key:'receivable:'+randomUUID()},{...p,expected_on:null}]){await db.exec('savepoint bad');await expect(write(bad)).rejects.toBeDefined();await db.exec('rollback to bad');}await db.exec('savepoint mixed');await db.query('insert into drivers(id,tenant_id,user_id,active) values($1,$2,$3,true)',[randomUUID(),i.tenant,i.operator]);await expect(write(p)).rejects.toMatchObject({code:'42501'});await db.exec('rollback to mixed');await db.exec('savepoint atomic');await write(p);await db.exec('rollback to atomic');expect((await db.query<{n:number}>('select count(*)::int n from finance_private.cash_forecast_agenda_events')).rows[0].n).toBe(0);for(const role of ['authenticated','anon','service_role'])expect((await db.query<{v:boolean}>('select has_function_privilege($1,$2,\'execute\') v',[role,'finance_private.record_cash_forecast_agenda(jsonb)'])).rows[0].v).toBe(false);await write(p);await db.query('update tenant_memberships set active=false where tenant_id=$1 and user_id=$2',[i.tenant,i.operator]);await expect(write(p)).rejects.toMatchObject({code:'42501'});});
it('rejects malformed agenda history and maintains immutable events',async()=>{const id=await seed();await write(await command(id));const c=await collect();const forged=structuredClone(c);forged.origins[0].agenda!.history[0].previous_id=randomUUID();await db.exec('savepoint malformed');await expect(db.query('select finance_private.project_collected_cash_forecast($1)',[forged])).rejects.toMatchObject({code:'22023'});await db.exec('rollback to malformed');await db.exec('savepoint immutable');await expect(db.exec("update finance_private.cash_forecast_agenda_events set reason='Reescrever histórico'")).rejects.toBeDefined();await db.exec('rollback to immutable');expect((await collect()).revision).toBe(c.revision);});

it('schedules an actual payable independently and leaves its nominal and due date intact',async()=>{const id=(await db.query<{id:string}>("insert into payables(id,tenant_id,supplier_name,amount,paid_amount,status,description,due_date) values(gen_random_uuid(),$1,'Agenda fornecedor',150,0,'pending','Agenda saída',current_date+5) returning id",[i.tenant])).rows[0].id;const c=await collect(),row=c.origins.find(x=>x.source_id===id)!;expect(row.valid).toBe(true);const before=(await db.query('select to_jsonb(p) v from payables p where id=$1',[id])).rows[0];await write({...await command(id),economic_key:'payable:'+id});const next=await collect();expect(next.origins.find(x=>x.source_id===id)).toMatchObject({direction:'out',expected_on:next.period_end,expected_date_source:'reviewed_date'});expect((await db.query('select to_jsonb(p) v from payables p where id=$1',[id])).rows[0]).toEqual(before);expect(next.origins.find(x=>x.source_id===id)!.agenda!.history[0].original_expected_on).toBe(row.expected_on);});

it('schedules actual unbilled freight only in expanded scenario, preserves original undated source and clears it',async()=>{const payer=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Frete agenda',true)",[payer,i.tenant]);const doc=(await db.query<{id:string}>("insert into fiscal_documents(id,tenant_id,document_type,status,client_id,issue_date,freight_value,value,is_duplicate) values(gen_random_uuid(),$1,'inbound','pending',$2,current_date-10,125.50,999999,false) returning id",[i.tenant,payer])).rows[0].id;const c=await collect(),row=c.origins.find(x=>x.source_id===doc)!;expect(row).toMatchObject({valid:true,scenario:'unbilled',expected_on:null,nominal_cents:'12550'});const p={...await command(doc),economic_key:row.economic_key};await write(p);let next=await collect();expect(next.origins.find(x=>x.source_id===doc)).toMatchObject({expected_on:p.expected_on,original_expected_on:null,original_expected_date_source:'unknown',agenda:{stale:false}});const projected=projectCollectedCashForecast(next,next);expect(projected.projection!.scheduled).toMatchObject({confirmed_in_cents:'0',unbilled_in_cents:'12550'});expect((await db.query<{v:unknown}>('select finance_private.project_collected_cash_forecast($1) v',[next])).rows[0].v).toEqual(projected);await write({...await command(doc,'clear'),economic_key:row.economic_key});next=await collect();expect(next.origins.find(x=>x.source_id===doc)).toMatchObject({expected_on:null,expected_date_source:'unknown'});expect(projectCollectedCashForecast(next,next).projection!.unscheduled.unbilled_cents).toBe('12550');expect((await db.query('select freight_value,value from fiscal_documents where id=$1',[doc])).rows).toEqual([{freight_value:'125.50',value:'999999'}]);});
it('keeps both agenda actions visible in central manual audit and rejects coherent-looking forged dates',async()=>{const id=await seed();await write(await command(id));const c=await collect();for(const forged of [(()=>{const x=structuredClone(c);x.origins[0].expected_on=c.cutoff;return x;})(),(()=>{const x=structuredClone(c);x.origins[0].agenda!.stale=true;return x;})()]){expect(cashForecastCollectorSchema.safeParse(forged).success).toBe(false);await db.exec('savepoint forged');await expect(db.query('select finance_private.project_collected_cash_forecast($1)',[forged])).rejects.toMatchObject({code:'22023'});await db.exec('rollback to forged');}await write(await command(id,'clear'));const audit=(await db.query<{v:{total:number,rows:Array<{action:string,manual_intervention:boolean}>}}>("select finance_private.audit_events($1,'{\"manual_only\":true}') v",[i.tenant])).rows[0].v;expect(audit.rows.filter(r=>r.action.startsWith('cash_forecast_agenda_')).map(r=>[r.action,r.manual_intervention]).sort()).toEqual([['cash_forecast_agenda_cleared',true],['cash_forecast_agenda_set',true]]);});
