import {beforeEach,it,expect,vi} from 'vitest';
import {createCashForecastAgendaOutbox,pendingCashForecastAgenda,cashForecastAgendaKey} from '@/lib/financial/cashForecastAgendaOutbox';
import {agendaIds as i,agendaInput as input,agendaSuccess} from './helpers/cashForecastAgendaFixture';
function setup(send:ReturnType<typeof vi.fn>){return createCashForecastAgendaOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),assertContext:()=>{},changed:()=>{},lock:async<T,>(_key:string,work:()=>Promise<T>)=>work(),send});}
beforeEach(()=>localStorage.clear());
it('recovers exact input after unknown and keeps uncertain request after known rejection',async()=>{const send=vi.fn().mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce({data:null,error:{code:'40001'}}).mockImplementationOnce(async c=>agendaSuccess(c));const box=setup(send);await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow('lost');await expect(box.recover(i.tenant,i.actor)).rejects.toMatchObject({code:'40001'});expect(pendingCashForecastAgenda(localStorage,i.tenant,i.actor)).not.toBeNull();await box.recover(i.tenant,i.actor);expect(send.mock.calls[2][0]).toEqual(send.mock.calls[0][0]);expect(pendingCashForecastAgenda(localStorage,i.tenant,i.actor)).toBeNull();});
it('clears only first definitive rejection and preserves incompatible actor response',async()=>{const send=vi.fn().mockResolvedValueOnce({data:null,error:{code:'23514'}}).mockImplementationOnce(async c=>({data:{...agendaSuccess(c).data,actor_id:crypto.randomUUID()},error:null}));const box=setup(send);await expect(box.submit(i.tenant,i.actor,input)).rejects.toMatchObject({code:'23514'});expect(pendingCashForecastAgenda(localStorage,i.tenant,i.actor)).toBeNull();await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow();expect(pendingCashForecastAgenda(localStorage,i.tenant,i.actor)).not.toBeNull();});
it('does not erase a different tab request after the original response',async()=>{const foreign='preserved-by-another-tab';const send=vi.fn().mockImplementation(async c=>{localStorage.setItem(cashForecastAgendaKey(i.tenant,i.actor),foreign);return agendaSuccess(c);});await setup(send).submit(i.tenant,i.actor,input);expect(localStorage.getItem(cashForecastAgendaKey(i.tenant,i.actor))).toBe(foreign);});

it('does not send after context changes',async()=>{const send=vi.fn();const box=createCashForecastAgendaOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{},assertContext:()=>{throw new Error('changed tenant');},lock:async<T,>(_key:string,work:()=>Promise<T>)=>work(),send});await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow('changed tenant');expect(send).not.toHaveBeenCalled();});

it('keeps the original request when action or date in the response is incompatible',async()=>{for(const patch of [{action:'clear',expected_on:null},{expected_on:'2026-10-03'},{economic_key:'another-source'}]){localStorage.clear();const send=vi.fn().mockImplementation(async c=>({data:{...agendaSuccess(c).data,...patch},error:null}));await expect(setup(send).submit(i.tenant,i.actor,input)).rejects.toThrow();expect(pendingCashForecastAgenda(localStorage,i.tenant,i.actor)).not.toBeNull();}});
