import {it,expect} from 'vitest';
import {projectCashForecast,type CashForecastBasis} from '@/lib/financial/cashForecastProjection';
import {cashForecastCollectorSchema} from '@/lib/financial/cashForecastCollectorContract';
import {cashForecastAgendaPreviewSchema} from '@/lib/financial/cashForecastAgendaContract';
const id=()=>crypto.randomUUID(),rev='a'.repeat(32);
function basis():CashForecastBasis {const account=id();return {version:1,tenant_id:id(),account_ids:[account],captured_at:'2026-09-11T12:00:00Z',cutoff:'2026-09-10',period_end:'2026-09-30',base:{amount_cents:'0',as_of:'2026-09-10',source_id:id(),source_revision:rev,confirmation:'bank_confirmed'},origins:[{economic_key:'receivable:test',source_table:'receivables',source_id:id(),source_revision:rev,direction:'in',scenario:'confirmed',nominal_cents:'100000',fulfilled_cents:'90000',reserved_credit_cents:'0',discount_cents:'10000',loss_cents:'0',adjustment_cents:'10000',expected_on:null,expected_date_source:'unknown'}],recorded_after_cutoff:[{movement_id:id(),account_id:account,source_revision:rev,occurred_on:'2026-09-11',direction:'in',amount_cents:'90000',confirmation:'recorded'}],unassigned_credit_cents:'0',source_issues:[]};}
it('removes discounted balance from future cash while retaining only actual recorded money',()=>{const b=basis(),original=JSON.stringify(b);const p=projectCashForecast(b);expect(p.rows[0]).toMatchObject({remaining_cents:'0',timing:'already_covered',fulfilled_cents:'90000',discount_cents:'10000'});expect(p.scheduled.confirmed_in_cents).toBe('0');expect(p.recorded_totals.in_cents).toBe('90000');expect(p.confirmed).toEqual({complete:true,closing_cents:'90000'});expect(JSON.stringify(b)).toBe(original);});
it('reopens only the reversed adjustment and keeps old projections unchanged',()=>{const b=basis(),saved=projectCashForecast(b),serialized=JSON.stringify(saved);b.origins[0].discount_cents='5000';b.origins[0].adjustment_cents='5000';b.origins[0].expected_on='2026-09-20';b.origins[0].expected_date_source='due_date';expect(projectCashForecast(b).scheduled.confirmed_in_cents).toBe('5000');expect(JSON.stringify(saved)).toBe(serialized);const legacy={...b.origins[0]};delete legacy.discount_cents;delete legacy.loss_cents;delete legacy.adjustment_cents;b.origins=[legacy];expect(projectCashForecast(b).scheduled.confirmed_in_cents).toBe('10000');});
it('rejects partial, unknown, inconsistent and excessive adjustments without defaulting to zero',()=>{for(const change of [{discount_cents:undefined},{loss_cents:null},{adjustment_cents:'9999'},{discount_cents:'10001',adjustment_cents:'10001'}]){const b=basis();Object.assign(b.origins[0],change);expect(()=>projectCashForecast(b)).toThrow();}});
it('preserves invalid origin diagnostics and denies a new agenda for fully adjusted titles',()=>{const originSchema=cashForecastCollectorSchema.innerType().shape.origins.element;const b=basis(),row={...b.origins[0],valid:true};expect(originSchema.parse(row).discount_cents).toBe('10000');const preview={version:1,tenant_id:b.tenant_id,actor_id:id(),cutoff:b.cutoff,period_end:b.period_end,revision:rev,origin:row,eligible:true,can_execute:true};expect(cashForecastAgendaPreviewSchema.safeParse(preview).success).toBe(false);expect(cashForecastAgendaPreviewSchema.safeParse({...preview,eligible:false,can_execute:false}).success).toBe(true);const unknown={...row,valid:false,nominal_cents:null,fulfilled_cents:null,reserved_credit_cents:null,discount_cents:null,loss_cents:null,adjustment_cents:null};expect(originSchema.parse(unknown).adjustment_cents).toBeNull();expect(originSchema.safeParse({...unknown,discount_cents:'0'}).success).toBe(false);});

it('separates loss and applied credit without projecting or recording either as cash',()=>{const b=basis();b.recorded_after_cutoff=[];Object.assign(b.origins[0],{fulfilled_cents:'0',reserved_credit_cents:'30000',discount_cents:'0',loss_cents:'70000',adjustment_cents:'70000'});const p=projectCashForecast(b);expect(p.rows[0]).toMatchObject({remaining_cents:'0',fulfilled_cents:'0',reserved_credit_cents:'30000',loss_cents:'70000'});expect(p.recorded_totals).toEqual({in_cents:'0',out_cents:'0'});expect(p.scheduled.confirmed_in_cents).toBe('0');expect(p.confirmed.closing_cents).toBe('0');});
