// @vitest-environment node
import {afterAll,afterEach,beforeAll,beforeEach,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {createCashForecastCollectorDatabase} from './helpers/cashForecastCollectorDatabase';
import {moneyPackageFixture} from './helpers/periodMoneyPackageFixture';
import {projectCashForecast,type CashForecastBasis} from '@/lib/financial/cashForecastProjection';
import {compareCashForecast} from '@/lib/financial/cashForecastComparison';
import {financeIds as i,financeAs} from './helpers/financeLedgerDatabase';
import {seedAccountCloseStatement} from './helpers/accountPeriodCloseDatabase';
let db:Awaited<ReturnType<typeof createCashForecastCollectorDatabase>>;
beforeAll(async()=>{db=await createCashForecastCollectorDatabase();for(const file of ['20260911084618_finance_cash_forecast_pure_projection','20260911084626_finance_cash_forecast_preserved_snapshots','20260911090341_finance_cash_forecast_preserved_comparison'])await db.exec(readFileSync('supabase/migrations/'+file+'.sql','utf8'));},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});afterEach(async()=>db.exec('rollback'));afterAll(async()=>db?.close());
function setup(){const actual=moneyPackageFixture();const basis:CashForecastBasis={version:1,tenant_id:actual.tenant_id,account_ids:actual.account_scope.selected_ids,captured_at:'2026-08-01T12:00:00Z',cutoff:'2026-07-31',period_end:'2026-08-31',base:{amount_cents:'1100',as_of:'2026-07-31',source_id:randomUUID(),source_revision:'original',confirmation:'provisional'},origins:[['in','600'],['out','350']].map(([direction,amount])=>({economic_key:randomUUID(),source_table:'receivables',source_id:randomUUID(),source_revision:'original',direction:direction as 'in'|'out',scenario:'confirmed',nominal_cents:amount,fulfilled_cents:'0',reserved_credit_cents:'0',expected_on:'2026-08-15',expected_date_source:'due_date'})),recorded_after_cutoff:[],unassigned_credit_cents:'0',source_issues:[]};return{actual,basis};}
async function pure(p:unknown,a:unknown){return(await db.query<{v:unknown}>('select finance_private.cash_forecast_comparison($1,$2) v',[p,a])).rows[0].v;}
it('matches TypeScript gross-flow decomposition and does not call equal closing a match',async()=>{const {actual,basis}=setup();for(const opening of ['1100','1000']){basis.base.amount_cents=opening;const original=projectCashForecast(basis),before=JSON.stringify(original);expect(await pure(original,actual)).toEqual(compareCashForecast(original,actual));expect(JSON.stringify(original)).toBe(before);}expect(compareCashForecast(projectCashForecast(basis),actual).confirmed).toMatchObject({matches:false,differences:{closing_cents:'0',opening_cents:'100',in_cents:'-100'}});});
it('preserves independent scenario availability and unknown realized coverage',async()=>{const {actual,basis}=setup();basis.source_issues=[{scope:'expanded',code:'fiscal_pending',source_ids:[]}];let p=projectCashForecast(basis);expect(await pure(p,actual)).toEqual(compareCashForecast(p,actual));expect(compareCashForecast(p,actual).confirmed.available).toBe(true);expect(compareCashForecast(p,actual).expanded.available).toBe(false);actual.monetary_totals_valid=false;actual.totals={opening_cents:null,in_cents:null,out_cents:null,closing_cents:null};actual.transfer_classification_valid=false;actual.transfer_totals={internal_pair_cents:null,in_excluding_internal_pairs_cents:null,out_excluding_internal_pairs_cents:null};p=projectCashForecast(basis);expect(await pure(p,actual)).toEqual(compareCashForecast(p,actual));});
it('rejects altered preserved equations, scope mismatches and fabricated realized sums',async()=>{const {actual,basis}=setup();const original=projectCashForecast(basis);const cases=[{p:{...original,tenant_id:randomUUID()},a:actual},{p:{...original,account_ids:[randomUUID()]},a:actual},{p:{...original,period_end:'2026-09-30'},a:actual},{p:{...original,confirmed:{...original.confirmed,closing_cents:'1250'}},a:actual},{p:original,a:{...actual,totals:{...actual.totals,in_cents:'501'}}}];for(const row of cases){expect(()=>compareCashForecast(row.p,row.a)).toThrow();await db.exec('savepoint invalid');await expect(pure(row.p,row.a)).rejects.toMatchObject({code:'22023'});await db.exec('rollback to invalid');}});
const commandBase=()=>({version:1,tenant_id:i.tenant,request_id:randomUUID(),reason:'Conferência preservada de previsão e realizado'});
async function rpc<T>(name:string,args:unknown[]){return(await financeAs<{v:T}>(db,i.operator,`select ${name}(${args.map((_,j)=>'$'+(j+1)).join(',')}) v`,args)).rows[0].v;}
async function capture(cutoff:string,end:string){const c=(await db.query<{v:{revision:string}}>('select finance_private.cash_forecast_collect($1,$2,$3) v',[i.tenant,cutoff,end])).rows[0].v;return(await db.query<{v:{snapshot_id:string,content_hash:string}}>('select finance_private.record_cash_forecast_snapshot($1) v',[{...commandBase(),cutoff,period_end:end,source_revision:c.revision,title:'Previsão original conferida'}])).rows[0].v;}
it('compares a real preserved snapshot to a real closing, never to a modified current receivable',async()=>{
 const days=(await db.query<{today:string,cutoff:string}>("select current_date::text today,(current_date-1)::text cutoff")).rows[0],scope={account_id:i.account,from:days.today,to:days.today};
 await seedAccountCloseStatement(db,days.cutoff,10000,days.today,days.today);await seedAccountCloseStatement(db,days.today,10000,days.today,days.today);await db.exec('select finance_private.run_automatic_reconciliation_queue()');
 const opening=await rpc<{revision:string}>('get_finance_statement_period_evidence',[i.tenant,i.account,days.today,days.today]);await rpc('record_finance_account_opening',[{...commandBase(),...scope,revision:opening.revision}]);
 const payer=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Cliente da previsão',true)",[payer,i.tenant]);const title=(await db.query<{id:string}>("insert into receivables(tenant_id,client_id,amount,received_amount,status,due_date,description) values($1,$2,100,0,'pending',current_date,'Previsão mantida') returning id",[i.tenant,payer])).rows[0].id;
 const saved=await capture(days.cutoff,days.today);const original=(await db.query<{v:{projection:ReturnType<typeof projectCashForecast>,content_hash:string}}>('select finance_private.read_cash_forecast_snapshot($1,$2) v',[i.tenant,saved.snapshot_id])).rows[0].v;
 // Advance only the isolated database clock after the real capture. Production
 // coverage forbids closing an unfinished day; no guard or capture result is stubbed.
 await db.exec("create or replace function pg_catalog.clock_timestamp() returns timestamptz language sql volatile as $$select transaction_timestamp()+interval '2 days'$$; create or replace function pg_catalog.statement_timestamp() returns timestamptz language sql stable as $$select transaction_timestamp()+interval '2 days'$$");
 await db.query('update receivables set amount=500 where id=$1',[title]);
 for(const [writer,reader,extra] of [['record_finance_statement_coverage_approval','get_finance_statement_coverage_review',{originals_obtained_from_bank:true,complete_period_confirmed:true}],['review_finance_legacy_cut','get_finance_legacy_cut_review',{sources_reviewed:true}]] as const){const context=await rpc<{revision:string}>(reader,[i.tenant,i.account,days.today,days.today]);await rpc(writer,[{...commandBase(),...scope,revision:context.revision,...extra}]);}
 const preview=await rpc<{revision:string,blockers:unknown[]}>('preview_finance_account_period_close',[i.tenant,i.account,days.today,days.today]);expect(preview.blockers).toEqual([]);const closed=await rpc<{closure_id:string,revision:string}>('close_finance_account_period',[{...commandBase(),...scope,revision:preview.revision}]);
 type Result={actor_id:string,content_hash:string,unavailable_reason:string|null,comparison:ReturnType<typeof compareCashForecast>};
 const compare=async()=>(await db.query<{v:Result}>('select finance_private.compare_cash_forecast_snapshot($1,$2) v',[i.tenant,saved.snapshot_id])).rows[0].v;
 const actual=await rpc('get_finance_period_money_package',[i.tenant,days.today,days.today,[i.account]]);const result=await compare();expect(result.comparison).toEqual(compareCashForecast(original.projection,actual));expect(result.comparison.confirmed).toMatchObject({available:true,matches:false,differences:{opening_cents:'0',in_cents:'-10000',out_cents:'0',closing_cents:'-10000'}});expect(result.content_hash).toBe(saved.content_hash);
 const viewer=randomUUID();await db.query("insert into tenant_memberships(tenant_id,user_id,role,active) values($1,$2,'operator',true)",[i.tenant,viewer]);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[viewer]);expect((await compare()).actor_id).toBe(viewer);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);
 await rpc('reopen_finance_account_period',[{...commandBase(),closure_id:closed.closure_id,revision:closed.revision}]);expect((await compare()).comparison.confirmed).toEqual({available:false,matches:false,expected:null,actual:null,differences:null});expect((await db.query<{v:unknown}>('select finance_private.read_cash_forecast_snapshot($1,$2) v',[i.tenant,saved.snapshot_id])).rows[0].v).toEqual(original);
 await db.exec('savepoint foreign_scope');await expect(db.query('select finance_private.compare_cash_forecast_snapshot($1,$2)',[i.otherTenant,saved.snapshot_id])).rejects.toMatchObject({code:'42501'});await db.exec('rollback to foreign_scope');await db.query('insert into drivers(id,tenant_id,user_id,active) values($1,$2,$3,true)',[randomUUID(),i.tenant,i.operator]);await expect(compare()).rejects.toMatchObject({code:'42501'});
},30000);
it('returns explicit unavailability for a preserved capture without accounts or a projection',async()=>{
 await db.query('delete from bank_accounts where tenant_id=$1',[i.tenant]);const days=(await db.query<{today:string,cutoff:string}>("select current_date::text today,(current_date-1)::text cutoff")).rows[0];const saved=await capture(days.cutoff,days.today);const result=(await db.query<{v:{comparison:unknown,unavailable_reason:string}}>('select finance_private.compare_cash_forecast_snapshot($1,$2) v',[i.tenant,saved.snapshot_id])).rows[0].v;expect(result).toMatchObject({comparison:null,unavailable_reason:'forecast_projection_unavailable'});
 for(const role of ['anon','authenticated','service_role'])expect((await db.query<{v:boolean}>('select has_function_privilege($1,$2,\'execute\') v',[role,'finance_private.compare_cash_forecast_snapshot(uuid,uuid)'])).rows[0].v).toBe(false);
});
