// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {afterAll,afterEach,beforeAll,beforeEach,expect,it} from 'vitest';
import {createCashForecastCollectorDatabase} from './helpers/cashForecastCollectorDatabase';
import {financeIds as i,financeAs} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createCashForecastCollectorDatabase>>;
const boundary=()=>readFileSync('supabase/migrations/20260911090256_finance_cash_forecast_public_boundary.sql','utf8');
beforeAll(async()=>{db=await createCashForecastCollectorDatabase();for(const name of ['20260911084618_finance_cash_forecast_pure_projection','20260911084626_finance_cash_forecast_preserved_snapshots','20260911085621_finance_cash_forecast_public_readers'])await db.exec(readFileSync('supabase/migrations/'+name+'.sql','utf8'));await db.exec(boundary());},30000);
beforeEach(async()=>{await db.exec('begin');});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
type Preview={tenant_id:string;actor_id:string;revision:string;cutoff:string;period_end:string;can_record:boolean};
async function preview(actor=i.operator,tenant=i.tenant,revision:string|null=null){return(await financeAs<{v:Preview}>(db,actor,"select preview_finance_cash_forecast($1,'2026-08-31',current_date+30,$2) v",[tenant,revision])).rows[0].v;}
async function seed(){const client=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Public forecast QA',true)",[client,i.tenant]);await db.query("insert into receivables(tenant_id,client_id,amount,received_amount,status,due_date,description) select $1,$2,10,0,'pending',current_date+10,'Public source' from generate_series(1,32)",[i.tenant,client]);return preview();}
function payload(p:Preview){return{version:1,tenant_id:i.tenant,request_id:randomUUID(),cutoff:p.cutoff,period_end:p.period_end,source_revision:p.revision,title:'Public captured forecast',reason:'Conferência pública preservada'};}
async function capture(p:ReturnType<typeof payload>,actor=i.operator){return(await financeAs<{v:{snapshot_id:string;content_hash:string}}>(db,actor,'select record_finance_cash_forecast($1) v',[p])).rows[0].v;}
async function snapshot(id:string,actor=i.operator,tenant=i.tenant){return(await financeAs<{v:{actor_id:string;viewer_actor_id:string;summary:{revision:string}}}>(db,actor,'select get_finance_cash_forecast_snapshot($1,$2) v',[tenant,id])).rows[0].v;}
async function sources(p:Preview,id:string|null,page=1,actor=i.operator){return(await financeAs<{v:{total:number;rows:Array<{source_id:string}>;revision:string}}>(db,actor,'select get_finance_cash_forecast_sources($1,$2,$3,$4,$5,$6,$7) v',[i.tenant,p.cutoff,p.period_end,id,'origins',page,p.revision])).rows[0].v;}
async function history(page=1,revision:string|null=null){return(await financeAs<{v:{total:number;rows:Array<{snapshot_id:string}>;revision:string}}>(db,i.operator,'select get_finance_cash_forecast_history($1,$2,$3) v',[i.tenant,page,revision])).rows[0].v;}
it('captures through authenticated public dispatch, replays exact evidence and pages preserved sources after live changes',async()=>{const p=await seed();expect(p).toMatchObject({tenant_id:i.tenant,actor_id:i.operator,can_record:true});const command=payload(p),saved=await capture(command),first=await snapshot(saved.snapshot_id);const one=await sources(p,saved.snapshot_id),two=await sources(p,saved.snapshot_id,2);expect(one.total).toBe(32);expect(one.rows).toHaveLength(30);expect(two.rows).toHaveLength(2);expect(new Set([...one.rows,...two.rows].map(r=>r.source_id)).size).toBe(32);await db.query('update receivables set amount=99 where id=$1',[one.rows[0].source_id]);await expect(preview(i.operator,i.tenant,p.revision)).rejects.toMatchObject({code:'40001'});await expect(sources(p,null,2)).rejects.toMatchObject({code:'40001'});expect(await capture(command)).toEqual(saved);expect(await snapshot(saved.snapshot_id)).toEqual(first);expect(await sources(p,saved.snapshot_id,2)).toEqual(two);expect((await history()).total).toBe(1);expect((await db.query('select count(*)::int n from finance_private.cash_forecast_snapshots')).rows).toEqual([{n:1}]);});
it('requires revision for next history pages and rejects a stale catalogue after a new real capture',async()=>{const p=await seed();for(let n=0;n<31;n++)await capture({...payload(p),title:'Capture '+n});const first=await history(),last=await history(2,first.revision);expect(first.total).toBe(31);expect(first.rows).toHaveLength(30);expect(last.rows).toHaveLength(1);expect(new Set([...first.rows,...last.rows].map(r=>r.snapshot_id)).size).toBe(31);await expect(history(2,null)).rejects.toMatchObject({code:'22023'});await capture(payload(p));await expect(history(2,first.revision)).rejects.toMatchObject({code:'40001'});},30000);
it('reauthorizes replay, separates historical author from viewer and denies foreign, driver and mixed-driver access',async()=>{const p=await seed(),command=payload(p),saved=await capture(command);const viewer=randomUUID();await db.query("insert into auth.users(id,email,raw_user_meta_data) values($1,'viewer@example.test','{}')",[viewer]);await db.query("insert into tenant_memberships(tenant_id,user_id,role,active) values($1,$2,'operator',true)",[i.tenant,viewer]);const viewed=await snapshot(saved.snapshot_id,viewer);expect(viewed.actor_id).toBe(i.operator);expect(viewed.viewer_actor_id).toBe(viewer);await expect(preview(i.operator,i.otherTenant)).rejects.toMatchObject({code:'42501'});await expect(snapshot(saved.snapshot_id,i.operator,i.otherTenant)).rejects.toMatchObject({code:'42501'});await expect(preview(i.driverUser)).rejects.toMatchObject({code:'42501'});await expect(capture(command,i.driverUser)).rejects.toMatchObject({code:'42501'});await db.query('insert into drivers(id,tenant_id,user_id,active) values($1,$2,$3,true)',[randomUUID(),i.tenant,i.operator]);await expect(snapshot(saved.snapshot_id)).rejects.toMatchObject({code:'42501'});await expect(capture(command)).rejects.toMatchObject({code:'42501'});await expect(sources(p,saved.snapshot_id)).rejects.toMatchObject({code:'42501'});await expect(history()).rejects.toMatchObject({code:'42501'});});
it('does not grant anonymous, service or raw private access and rejects stale capture without a row',async()=>{const p=await seed();for(const role of ['anon','service_role']){const acl=await db.query<{allowed:boolean}>("select has_function_privilege($1,'public.record_finance_cash_forecast(jsonb)','execute') or has_function_privilege($1,'public.preview_finance_cash_forecast(uuid,date,date,text)','execute') allowed",[role]);expect(acl.rows[0].allowed).toBe(false);}await expect(financeAs(db,i.operator,'select * from finance_private.cash_forecast_snapshots')).rejects.toMatchObject({code:'42501'});await expect(financeAs(db,i.operator,'select finance_private.record_cash_forecast_snapshot($1)',[payload(p)])).rejects.toMatchObject({code:'42501'});await expect(preview('')).rejects.toMatchObject({code:'42501'});await db.query('update receivables set amount=20 where tenant_id=$1',[i.tenant]);await expect(capture(payload(p))).rejects.toMatchObject({code:'40001'});expect((await db.query('select count(*)::int n from finance_private.cash_forecast_snapshots')).rows).toEqual([{n:0}]);});
it('rejects promotion when a pinned private body has changed',async()=>{const definition=(await db.query<{body:string}>("select pg_get_functiondef('finance_private.validate_forecast_json(jsonb,jsonb)'::regprocedure) body")).rows[0].body;const end=definition.lastIndexOf('$function$');expect(end).toBeGreaterThan(0);await db.exec(definition.slice(0,end)+'\n-- altered dependency body\n'+definition.slice(end));await db.exec('savepoint pin');await expect(db.exec(boundary())).rejects.toThrow('finance_forecast_dependency_changed');await db.exec('rollback to pin');});
it('rejects promotion when raw grants or the preservation guard are changed',async()=>{await db.exec('savepoint grant_drift');await db.exec('grant execute on function finance_private.project_collected_cash_forecast(jsonb) to authenticated');await expect(db.exec(boundary())).rejects.toThrow('finance_forecast_dependency_changed');await db.exec('rollback to grant_drift');await db.exec('alter table finance_private.cash_forecast_snapshots disable trigger preserve_cash_forecast_snapshot');await db.exec('savepoint guard_drift');await expect(db.exec(boundary())).rejects.toThrow('finance_forecast_snapshot_guard_missing');await db.exec('rollback to guard_drift');});
