import {render,screen,cleanup} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {CashForecastComparisonResultView} from '@/components/financial/CashForecastComparisonPanel';
import {cashForecastComparisonResultSchema,type CashForecastComparisonResult} from '@/lib/financial/cashForecastComparisonContract';
vi.mock('@/lib/financial/cashForecastComparisonClient',()=>({readCashForecastComparison:vi.fn()}));
afterEach(cleanup);
function fixture():CashForecastComparisonResult{return {version:1,tenant_id:'10000000-0000-0000-0000-000000000001',actor_id:'20000000-0000-0000-0000-000000000001',snapshot_id:'30000000-0000-0000-0000-000000000001',source_revision:'saved',content_hash:'immutable',unavailable_reason:null,comparison:{tenant_id:'10000000-0000-0000-0000-000000000001',account_ids:['40000000-0000-0000-0000-000000000001'],period:{from:'2026-08-01',to:'2026-08-31'},original_captured_at:'2026-07-31T12:00:00Z',realized_captured_at:'2026-09-01T12:00:00Z',realized_revision:'closed',base_confirmation:'provisional',whole_company_scope:false,flow_basis:'gross_cash',cause_attribution:'not_determined',confirmed:{available:true,matches:false,expected:{opening_cents:'1000',in_cents:'600',out_cents:'350',closing_cents:'1250'},actual:{opening_cents:'1100',in_cents:'500',out_cents:'350',closing_cents:'1250'},differences:{opening_cents:'100',in_cents:'-100',out_cents:'0',closing_cents:'0'}},expanded:{available:false,matches:false,expected:null,actual:null,differences:null}}};}
it('shows gross differences and independent unavailability without declaring equal closing a match',()=>{render(<CashForecastComparisonResultView result={cashForecastComparisonResultSchema.parse(fixture())}/>);expect(screen.getByRole('columnheader',{name:'Previsto'})).toBeInTheDocument();expect(screen.getByRole('columnheader',{name:'Realizado'})).toBeInTheDocument();expect(screen.getByRole('columnheader',{name:'Diferença'})).toBeInTheDocument();expect(screen.getByText('Há diferenças em relação à previsão.')).toBeInTheDocument();expect(screen.getByText(/cenário ou fechamento sem valores determinados/)).toBeInTheDocument();expect(screen.getByText(/não abrange toda a empresa/)).toBeInTheDocument();expect(screen.getByText(/base original permanece provisória/)).toBeInTheDocument();expect(screen.queryByText('Os quatro valores coincidem.')).not.toBeInTheDocument();expect(screen.getByText(/não identificam sua causa/)).toBeInTheDocument();});
it('renders missing projection explicitly without monetary zero',()=>{const f=fixture();f.comparison=null;f.unavailable_reason='forecast_projection_unavailable';render(<CashForecastComparisonResultView result={f}/>);expect(screen.getByRole('status')).toHaveTextContent('não contém uma projeção determinada');expect(screen.queryByText('Fechamento')).not.toBeInTheDocument();});
it('rejects invalid differences and contradictory availability',()=>{const f=fixture();f.comparison!.confirmed.matches=true;expect(cashForecastComparisonResultSchema.safeParse(f).success).toBe(false);f.comparison=null;expect(cashForecastComparisonResultSchema.safeParse(f).success).toBe(false);});

it('rejects actual versus expected mismatch even when differences conserve their own equation',()=>{const f=fixture();f.comparison!.confirmed.actual!.opening_cents='1200';f.comparison!.confirmed.actual!.closing_cents='1350';expect(cashForecastComparisonResultSchema.safeParse(f).success).toBe(false);});
