import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {AccountOpeningWorkspace} from '@/components/financial/AccountOpeningReview';
const mock=vi.hoisted(()=>({account:vi.fn(),context:vi.fn(),record:vi.fn(),evidence:vi.fn(),bank:vi.fn(),reverse:vi.fn()}));
vi.mock('@/lib/financial/cashOpeningClient',()=>({readOpeningAccount:mock.account,recordCashOpening:mock.record}));
vi.mock('@/lib/financial/accountOpeningClient',()=>({readAccountOpening:mock.context,recordAccountOpening:mock.bank,reverseAccountOpening:mock.reverse,AccountOpeningRejectedError:class extends Error{}}));
vi.mock('@/lib/financial/periodEvidenceClient',()=>({readPeriodEvidence:mock.evidence}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),key=`finance-account-opening:${tenant}:${actor}:${account}`;
const context={version:1,tenant_id:tenant,account_id:account,from:'2026-01-02',to:'2026-01-31',opening:null,book:null,history:[],can_close:false};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.account.mockResolvedValue({id:account,tenant_id:tenant,name:'Caixa sede',account_type:'cash',active:true});mock.context.mockResolvedValue(context);mock.record.mockResolvedValue({balance_cents:'20500'});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(from='2026-01-02'){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><AccountOpeningWorkspace tenant={tenant} actor={actor} account={account} from={from} to="2026-01-31"/></QueryClientProvider>);}
async function review(){fireEvent.change(await screen.findByLabelText('Responsável pela guarda do caixa'),{target:{value:'Ana Custódia'}});fireEvent.change(screen.getByLabelText('Quantidade de R$ 100,00'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Quantidade de R$ 5,00'),{target:{value:'1'}});fireEvent.change(screen.getByLabelText('Motivo da contagem'),{target:{value:'Contagem presencial no início do dia'}});fireEvent.click(screen.getByRole('button',{name:'Revisar contagem'}));}
it('reviews a physical count and recovers the exact original day after response loss without OFX',async()=>{
 mock.record.mockRejectedValueOnce(new Error('timeout'));const view=open();await review();expect(mock.evidence).not.toHaveBeenCalled();expect(mock.bank).not.toHaveBeenCalled();expect(mock.record).not.toHaveBeenCalled();expect(screen.getByText('Total revisado: R$ 205,00')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Confirmar contagem de abertura'}));await screen.findByRole('alert');const original=mock.record.mock.calls[0][0];expect(original).toMatchObject({effective_from:'2026-01-02',custodian_name:'Ana Custódia'});expect(original).not.toHaveProperty('balance_cents');
 view.unmount();open('2026-01-10');fireEvent.click(screen.getByRole('button',{name:'Retomar pedido de abertura'}));await waitFor(()=>expect(mock.record).toHaveBeenCalledTimes(2));expect(mock.record.mock.calls[1][0]).toEqual(original);expect(await screen.findByText(/Contagem confirmada pelo servidor: R\$ 205,00/)).toBeInTheDocument();expect(sessionStorage.getItem(key)).toBeNull();
});
it('blocks fractional quantities and storage failure before sending',async()=>{
 open();await review();fireEvent.click(screen.getByRole('button',{name:'Voltar à contagem'}));fireEvent.change(screen.getByLabelText('Quantidade de R$ 100,00'),{target:{value:'1,5'}});expect(screen.getByRole('button',{name:'Revisar contagem'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Quantidade de R$ 100,00'),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:'Revisar contagem'}));vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('full');});fireEvent.click(screen.getByRole('button',{name:'Confirmar contagem de abertura'}));expect(await screen.findByRole('alert')).toHaveTextContent('Nenhuma abertura ou correção foi enviada');expect(mock.record).not.toHaveBeenCalled();
});
it('keeps denomination details and custodian in history after reversal',async()=>{
 const item={id:crypto.randomUUID(),effective_from:'2026-01-02',balance_cents:'20500',actor_id:actor,actor_name:'Financeiro QA',reason:'Contagem original',created_at:'2026-01-02T00:00:00-03:00',evidence_type:'cash_count_v1',evidence:{version:1,type:'cash_count_v1',currency:'BRL',effective_from:'2026-01-02',timezone:'America/Sao_Paulo',counted_at_boundary:'start_of_day',custodian_name:'Ana Custódia',counts:[{denomination_cents:10000,quantity:2},{denomination_cents:500,quantity:1}],total_cents:'20500'},reversal:{id:crypto.randomUUID(),actor_id:actor,actor_name:'Gestor QA',reason:'Contagem corrigida',created_at:'2026-01-03'}};mock.context.mockResolvedValue({...context,history:[item]});open();expect(await screen.findByText(/Contagem física preservada/)).toBeInTheDocument();expect(screen.getByText('Responsável pela guarda: Ana Custódia')).toBeInTheDocument();expect(screen.getByText('R$ 100,00 × 2 = R$ 200,00')).toBeInTheDocument();expect(screen.getByText(/Desfeita por Gestor QA/)).toBeInTheDocument();
});
it('never offers physical counting for a bank or inactive cash account',async()=>{
 mock.account.mockResolvedValue({id:account,tenant_id:tenant,name:'Banco',account_type:'checking',active:true});mock.evidence.mockResolvedValue({opening_balance_cents:null,anchors:[],revision:'none'});const view=open();await waitFor(()=>expect(mock.evidence).toHaveBeenCalled());expect(screen.queryByLabelText('Responsável pela guarda do caixa')).not.toBeInTheDocument();view.unmount();mock.account.mockResolvedValue({id:account,tenant_id:tenant,name:'Caixa',account_type:'cash',active:false});open();expect(await screen.findByRole('alert')).toHaveTextContent('caixa está inativo');expect(screen.queryByLabelText('Responsável pela guarda do caixa')).not.toBeInTheDocument();
});
