import {beforeEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor,act} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {CashForecastAgendaWorkspace} from '@/components/financial/CashForecastAgendaDialog';
import {CashForecastAgendaConfirmation} from '@/components/financial/CashForecastAgendaConfirmation';
import {CashForecastAgendaHistory} from '@/components/financial/CashForecastAgendaHistory';
import {CashForecastSources} from '@/components/financial/CashForecastSources';
import {agendaIds as i,agendaPreview as p,agendaSuccess} from './helpers/cashForecastAgendaFixture';
import {forecastPreview} from './helpers/cashForecastViewFixture';
const m=vi.hoisted(()=>({read:vi.fn(),send:vi.fn(),sources:vi.fn()}));
vi.mock('@/lib/financial/cashForecastAgendaClient',async original=>({...await original<typeof import('@/lib/financial/cashForecastAgendaClient')>(),readCashForecastAgenda:m.read,sendCashForecastAgenda:m.send}));
vi.mock('@/lib/financial/cashForecastViewClient',async original=>({...await original<typeof import('@/lib/financial/cashForecastViewClient')>(),readCashForecastSources:m.sources}));
beforeEach(()=>{cleanup();localStorage.clear();vi.clearAllMocks();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async<T,>(_key:string,work:()=>Promise<T>)=>work()}});});
function review(action:'set'|'clear'='set'){fireEvent.change(screen.getByLabelText('Alteração da agenda'),{target:{value:action}});if(action==='set')fireEvent.change(screen.getByLabelText('Data esperada'),{target:{value:'2026-10-02'}});fireEvent.change(screen.getByLabelText('Motivo da revisão'),{target:{value:'Data combinada com cliente'}});fireEvent.click(screen.getByText('Conferir revisão da agenda'));fireEvent.click(screen.getByRole('checkbox'));}
it('keeps due date separate and clears only the manual expectation after explicit confirmation',async()=>{m.send.mockImplementation(async c=>agendaSuccess(c));m.read.mockResolvedValue(p);render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><CashForecastAgendaWorkspace tenant={i.tenant} actor={i.actor} economicKey={p.origin.economic_key} cutoff={p.cutoff} end={p.period_end}/></QueryClientProvider>);await screen.findByLabelText('Motivo da revisão');expect(screen.getByText(/Vencimento na origem: 2026-09-20/)).toBeInTheDocument();review('clear');fireEvent.click(screen.getByText('Confirmar revisão da agenda'));await screen.findByText(/Revisão de agenda registrada/);expect(m.send.mock.calls[0][0]).toMatchObject({action:'clear',expected_on:null,expected_revision:p.revision,economic_key:p.origin.economic_key});expect(m.send.mock.calls[0][0]).not.toHaveProperty('due_date');});
it('replays original date/revision after uncertain response and a changed current preview',async()=>{m.send.mockRejectedValueOnce(new Error('lost')).mockImplementationOnce(async c=>agendaSuccess(c));const refresh=vi.fn().mockRejectedValue(new Error('cache'));const view=render(<CashForecastAgendaConfirmation tenant={i.tenant} actor={i.actor} economicKey={p.origin.economic_key} preview={p} refresh={refresh}/>);review();fireEvent.click(screen.getByText('Confirmar revisão da agenda'));await screen.findByText('Recuperar revisão da agenda');view.rerender(<CashForecastAgendaConfirmation tenant={i.tenant} actor={i.actor} economicKey="other" preview={undefined} refresh={refresh}/>);expect(screen.getByText(/Pedido de outra origem/)).toBeInTheDocument();fireEvent.click(screen.getByText('Recuperar revisão da agenda'));await screen.findByText(/Revisão de agenda registrada/);expect(m.send.mock.calls[1][0]).toEqual(m.send.mock.calls[0][0]);expect(screen.getByRole('alert')).toHaveTextContent('foi registrada');});
it('hides permission while refetching and on API error',async()=>{m.read.mockResolvedValue(p);const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><CashForecastAgendaWorkspace tenant={i.tenant} actor={i.actor} economicKey={p.origin.economic_key} cutoff={p.cutoff} end={p.period_end}/></QueryClientProvider>);await screen.findByLabelText('Motivo da revisão');let reject!:(e:Error)=>void;m.read.mockImplementation(()=>new Promise((_resolve,no)=>{reject=no;}));fireEvent.click(screen.getByText('Atualizar agenda'));await waitFor(()=>expect(screen.queryByLabelText('Motivo da revisão')).not.toBeInTheDocument());await act(async()=>reject(new Error('missing')));await screen.findByText(/A agenda está indisponível/);expect(m.send).not.toHaveBeenCalled();});
it('shows stale manual history with author and original due date',()=>{render(<CashForecastAgendaHistory origin={{...p.origin,expected_on:null,expected_date_source:'unknown',original_expected_on:'2026-09-20',original_expected_date_source:'due_date',agenda:{event_id:i.event,revision:'d'.repeat(32),stale:true,history:[{id:i.event,ordinal:1,previous_id:null,action:'set',expected_on:'2026-10-02',source_revision:'b'.repeat(32),original_expected_on:'2026-09-20',original_expected_date_source:'due_date',actor_id:i.actor,actor_name:'Operador conferido',reason:'Cliente pediu nova expectativa',created_at:'2026-09-11T12:00:00Z'}]}}}/>);expect(screen.getByRole('alert')).toHaveTextContent('não é usada na previsão');expect(screen.getByText(/Operador conferido/)).toHaveTextContent(i.actor);expect(screen.getByText(/Cliente pediu nova expectativa/)).toBeInTheDocument();});
it('offers revision only on current sources, preserving historical read-only evidence',async()=>{m.sources.mockResolvedValue({version:1,tenant_id:i.tenant,actor_id:i.actor,snapshot_id:null,kind:'origins',page:1,page_size:30,total:1,revision:forecastPreview.revision,rows:[p.origin]});const onAgenda=vi.fn();const cache=new QueryClient();const view=render(<QueryClientProvider client={cache}><CashForecastSources tenant={i.tenant} actor={i.actor} summary={forecastPreview} snapshotId={null} onChanged={vi.fn()} onAgenda={onAgenda}/></QueryClientProvider>);fireEvent.click(await screen.findByText('Revisar data esperada desta origem'));expect(onAgenda).toHaveBeenCalledWith(p.origin.economic_key,p.origin.source_id);view.rerender(<QueryClientProvider client={cache}><CashForecastSources tenant={i.tenant} actor={i.actor} summary={forecastPreview} snapshotId={i.snapshot} onChanged={vi.fn()} onAgenda={onAgenda}/></QueryClientProvider>);await screen.findByText(/cadastro atual/);expect(screen.queryByText('Revisar data esperada desta origem')).not.toBeInTheDocument();});

it('invalidates only current projections and sources while preserved snapshot cache stays intact',async()=>{m.send.mockImplementation(async c=>agendaSuccess(c));m.read.mockResolvedValue({...p,origin:{...p.origin,expected_on:null,expected_date_source:'unknown'}});const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});const current=['finance-cash-forecast-sources',i.tenant,i.actor,null,p.revision,'origins',1];const preserved=['finance-cash-forecast-sources',i.tenant,i.actor,i.snapshot,p.revision,'origins',1];const snapshot=['finance-cash-forecast-snapshot',i.tenant,i.actor,i.snapshot];cache.setQueryData(current,{marker:'current'});cache.setQueryData(preserved,{marker:'original'});cache.setQueryData(snapshot,{marker:'snapshot'});render(<QueryClientProvider client={cache}><CashForecastAgendaWorkspace tenant={i.tenant} actor={i.actor} economicKey={p.origin.economic_key} cutoff={p.cutoff} end={p.period_end}/></QueryClientProvider>);await screen.findByLabelText('Motivo da revisão');expect(screen.getByText(/Vencimento na origem: Não informado/)).toBeInTheDocument();review();fireEvent.click(screen.getByText('Confirmar revisão da agenda'));await screen.findByText(/Revisão de agenda registrada/);await waitFor(()=>expect(cache.getQueryState(current)?.isInvalidated).toBe(true));expect(cache.getQueryState(preserved)?.isInvalidated).toBe(false);expect(cache.getQueryData(preserved)).toEqual({marker:'original'});expect(cache.getQueryState(snapshot)?.isInvalidated).toBe(false);});
