// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createClosedPeriodLateCompositionDatabase} from './helpers/closedPeriodLateCompositionDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createClosedPeriodLateCompositionDatabase>>;
beforeAll(async()=>{db=await createClosedPeriodLateCompositionDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(direction='out'){const movement=randomUUID(),opening=randomUUID(),closure=randomUUID(),request=randomUUID(),payable=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,$5,'payment',5000,'2026-08-15','Pagamento','Fornecedor',$4)",[movement,i.tenant,i.account,i.operator,direction]);await db.query("insert into payables(id,tenant_id,supplier_name,category,amount,status) values($1,$2,'Fornecedor','other',50,'approved')",[payable,i.tenant]);await db.query("insert into finance_account_openings(id,tenant_id,bank_account_id,effective_from,balance_cents,evidence_to,evidence,actor_id,actor_name,reason) values($1,$2,$3,'2026-08-01',10000,'2026-08-31','{}',$4,'QA','Abertura histórica fixture')",[opening,i.tenant,i.account,i.operator]);await db.query("insert into finance_private.account_close_write_tickets values(txid_current(),$1,$2,$3,'finance_account_period_closures')",[i.tenant,request,i.operator]);await db.query("insert into finance_account_period_closures(id,tenant_id,account_id,period_start,period_end,opening_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,$3,'2026-08-01','2026-08-31',$4,'{}',$5,$6,'QA','Fechamento histórico fixture',$7)",[closure,i.tenant,i.account,opening,'a'.repeat(32),i.operator,request]);await db.query("insert into finance_account_period_dependencies values($1,$2,'finance_movements',$3,'revision',$4,'2026-08-01','2026-08-31','money')",[i.tenant,closure,movement,i.account]);return{movement,payable,closure};}
it('permits the real payable allocation command after close with final canonical proof and exact replay',async()=>{const s=await seed(),snapshot=(await db.query('select snapshot from finance_account_period_closures')).rows;const p={version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:s.movement,payable_id:s.payable,amount_cents:5000,method:'pix',reason:'Detalhamento tardio do pagamento já registrado'};const result=await financeAs(db,i.operator,'select apply_finance_payable_movement($1) v',[p]);await db.exec('set constraints all immediate');expect(await financeAs(db,i.operator,'select apply_finance_payable_movement($1) v',[p])).toEqual(result);expect((await db.query('select snapshot from finance_account_period_closures')).rows).toEqual(snapshot);expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:1});});
it('rejects an unlinked retroactive payment at constraint flush, without a caller flag',async()=>{const s=await seed();await db.exec('savepoint invalid_projection');await db.query("insert into payables_payments(tenant_id,payable_id,amount,paid_at,bank_account_id,method) values($1,$2,50,'2026-08-15T12:00:00Z',$3,'pix')",[i.tenant,s.payable,i.account]);await expect(db.exec('set constraints all immediate')).rejects.toThrow('finance_account_period_closed');await db.exec('rollback to savepoint invalid_projection');expect((await db.query('select count(*)::int n from payables_payments')).rows[0]).toEqual({n:0});});
it('still rejects new retroactive money immediately',async()=>{await seed();await expect(financeAs(db,i.operator,'select record_finance_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:5000,occurred_on:'2026-08-15',description:'Novo dinheiro',beneficiary_name:'Fornecedor',reason:'Tentativa de nova saída no período'}])).rejects.toThrow('finance_account_period_closed');});
it('requires the final exact receipt and bank projection chain before allowing a late allocation',async()=>{const s=await seed('in'),title=randomUUID(),payment=randomUUID(),bank=randomUUID(),command=randomUUID();await db.query("insert into receivables(id,tenant_id,amount,status,description) values($1,$2,50,'pending','Título conferido')",[title,i.tenant]);await db.query("insert into receivable_financial_commands(id,tenant_id,actor_id,request_id,receivable_id,action,reason,payload_hash,before_snapshot,after_snapshot,response) values($1,$2,$3,gen_random_uuid(),$4,'receive','Recebimento conferido','hash','{}','{}','{}')",[command,i.tenant,i.operator,title]);await db.query("insert into bank_transactions(id,tenant_id,bank_account_id,posted_at,amount,transaction_type) values($1,$2,$3,'2026-08-15T12:00:00Z',50,'credit')",[bank,i.tenant,i.account]);await db.query("insert into receivables_payments(id,tenant_id,receivable_id,amount,received_at,bank_account_id,method,bank_transaction_id,financial_command_id) values($1,$2,$3,50,'2026-08-15T12:00:00Z',$4,'pix',$5,$6)",[payment,i.tenant,title,i.account,bank,command]);await db.query("insert into finance_receivable_movement_links(tenant_id,command_id,payment_id,bank_transaction_id,movement_id,action) values($1,$2,$3,$4,$5,'receive')",[i.tenant,command,payment,bank,s.movement]);await db.exec('set constraints all immediate');expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:1});});
it('rejects altered account data at the deferred boundary rather than treating a foreign account as outside scope',async()=>{const s=await seed();await db.exec('savepoint foreign_projection');await db.query("insert into payables_payments(tenant_id,payable_id,amount,paid_at,bank_account_id,method) values($1,$2,50,'2026-08-15T12:00:00Z',$3,'pix')",[i.tenant,s.payable,i.otherAccount]);await expect(db.exec('set constraints all immediate')).rejects.toThrow('finance_account_period_closed');await db.exec('rollback to savepoint foreign_projection');});
it('rechecks access when the deferred proof executes and rolls back the entire pending allocation',async()=>{const s=await seed();await db.exec('savepoint revoked_pending');await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:s.movement,payable_id:s.payable,amount_cents:5000,method:'pix',reason:'Detalhamento com autorização inicialmente válida'}]);await db.query('update tenant_memberships set active=false where tenant_id=$1 and user_id=$2',[i.tenant,i.operator]);await expect(db.exec('set constraints all immediate')).rejects.toThrow('finance_access_denied');await db.exec('rollback to savepoint revoked_pending');expect((await db.query('select count(*)::int n from payables_payments')).rows[0]).toEqual({n:0});expect((await db.query("select count(*)::int n from finance_events where action='closed_period_composition_recorded'")).rows[0]).toEqual({n:0});});
