import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {CostDispositionsWorkspace} from '@/components/financial/CostDispositionsPanel';
import {CostDispositionsChangedError} from '@/lib/financial/costDispositionsClient';
import {regularizationIds as i,regularizedCoverage as coverage} from './helpers/unloadingCostRegularizationFixture';
const m=vi.hoisted(()=>({read:vi.fn()}));vi.mock('@/lib/financial/costDispositionsClient',async original=>({...await original<object>(),readCostDispositions:m.read}));
const page={version:1,tenant_id:i.tenant,page:1,page_size:30,total:31,revision:'a'.repeat(32),needs_review_count:0,gross_reserved_cents:'15000',applied_cents:'12000',residual_cents:'3000',driver_custody_cents:'3000',payment_recovery_cents:'0',rows:[{expense_id:i.expense,charge_id:i.charge,payable_id:null,description:'Custo sob responsabilidade',occurred_on:'2026-09-01',coverage}]};
beforeEach(()=>vi.clearAllMocks());afterEach(cleanup);
function open(){const cache=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity}}});render(<QueryClientProvider client={cache}><CostDispositionsWorkspace tenant={i.tenant} actor={i.actor}/></QueryClientProvider>);return cache;}
it('reloads page one with a fresh epoch after changed revision even with infinite cache freshness',async()=>{m.read.mockResolvedValueOnce(page).mockRejectedValueOnce(new CostDispositionsChangedError('A consulta mudou')).mockResolvedValueOnce({...page,revision:'b'.repeat(32),rows:[{...page.rows[0],description:'Conferência atualizada'}]});open();await screen.findByText('Custo sob responsabilidade');fireEvent.click(screen.getByText('Próxima página de pendências'));await screen.findByText('Conferência atualizada');expect(m.read).toHaveBeenNthCalledWith(2,i.tenant,2,page.revision);expect(m.read).toHaveBeenLastCalledWith(i.tenant,1,null);expect(screen.queryByText('Custo sob responsabilidade')).not.toBeInTheDocument();});
it('hides old balances after failure instead of showing them as current',async()=>{m.read.mockResolvedValue(page);const cache=open();await screen.findByText('Custo sob responsabilidade');m.read.mockRejectedValue(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-cost-dispositions']});});await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Não foi possível'));expect(screen.queryByText('Custo sob responsabilidade')).not.toBeInTheDocument();});
