import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {CostDispositionReturnConfirmation} from '@/components/financial/CostDispositionReturnConfirmation';
import {CostDispositionReturnWorkspace} from '@/components/financial/CostDispositionReturnDialog';
import {CostDispositionReturnHistory} from '@/components/financial/CostDispositionReturnHistory';
import {CostDispositionsWorkspace} from '@/components/financial/CostDispositionsPanel';
import {regularizedCoverage} from './helpers/unloadingCostRegularizationFixture';
import {CostReturnMovementPicker} from '@/components/financial/CostReturnMovementPicker';
import {CostReturnMovementOptionsChangedError} from '@/lib/financial/costDispositionReturnClient';
import {returnIds as i,returnPreview as p,returnOptions as options,returnSuccess} from './helpers/costDispositionReturnFixture';
const m=vi.hoisted(()=>({read:vi.fn(),options:vi.fn(),send:vi.fn(),portfolio:vi.fn()}));vi.mock('@/lib/financial/costDispositionReturnClient',()=>({readCostDispositionReturn:m.read,readCostReturnMovementOptions:m.options,sendCostDispositionReturn:m.send,CostReturnMovementOptionsChangedError:class extends Error{constructor(){super('As entradas disponíveis mudaram. A consulta foi reiniciada.');}}}));
vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentRole:'admin'})}));vi.mock('@/hooks/useFinanceLedger',()=>({useFinanceAccess:()=>({data:true,isPending:false,isFetchedAfterMount:true,error:null})}));vi.mock('@/lib/financial/costDispositionsClient',async original=>({...await original<object>(),readCostDispositions:m.portfolio}));
beforeEach(()=>{localStorage.clear();vi.clearAllMocks();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_key:string,work:()=>Promise<unknown>)=>work()}});});afterEach(cleanup);
it('shows historical30 returned10 pending20 with actor and reason without bank confirmation',()=>{render(<CostDispositionReturnHistory disposition={{...p.disposition!,returned_cents:'1000',open_cents:'2000',resolution_status:'partial',returns:[{id:crypto.randomUUID(),request_id:crypto.randomUUID(),incoming_movement_id:i.incoming,amount_cents:'1000',occurred_on:'2026-09-11',actor_id:i.actor,actor_name:'Operador',reason:'Retorno parcial conferido',created_at:'2026-09-11T08:00:00Z'}]}}/>);expect(screen.getByText('Responsabilidade original: R$ 30,00')).toBeInTheDocument();expect(screen.getByText('Devolução registrada: R$ 10,00')).toBeInTheDocument();expect(screen.getByText('Pendente: R$ 20,00')).toBeInTheDocument();expect(screen.getByText(/Retorno parcial conferido/)).toBeInTheDocument();expect(screen.getByText(/conferência bancária permanece separada/)).toBeInTheDocument();});
it('keeps confirmed success terminal after refresh fails',async()=>{m.send.mockImplementation(async c=>returnSuccess(c));render(<CostDispositionReturnConfirmation tenant={i.tenant} actor={i.actor} dispositionId={i.disposition} preview={p} refresh={async()=>{throw new Error('offline');}}/>);fireEvent.change(screen.getByLabelText('Motivo da devolução'),{target:{value:'Devolução parcial conferida'}});fireEvent.click(screen.getByText('Revisar devolução'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar devolução'));await screen.findByText(/Devolução registrada: R\$ 10,00/);expect(screen.getByRole('alert')).toHaveTextContent('foi confirmada');expect(screen.queryByText('Confirmar devolução')).not.toBeInTheDocument();expect(m.send).toHaveBeenCalledOnce();});
it('invalidates preview when amount changes and hides stale read errors without sending',async()=>{m.options.mockResolvedValue(options);m.read.mockResolvedValue(p);const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><CostDispositionReturnWorkspace tenant={i.tenant} actor={i.actor} dispositionId={i.disposition}/></QueryClientProvider>);fireEvent.click(await screen.findByText('Selecionar entrada Retorno do motorista'));fireEvent.change(screen.getByLabelText('Valor devolvido (R$)'),{target:{value:'10,00'}});fireEvent.click(screen.getByText('Conferir devolução'));await screen.findByLabelText('Motivo da devolução');fireEvent.change(screen.getByLabelText('Valor devolvido (R$)'),{target:{value:'11,00'}});expect(screen.queryByLabelText('Motivo da devolução')).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Valor devolvido (R$)'),{target:{value:'10,00'}});fireEvent.click(screen.getByText('Conferir devolução'));await screen.findByLabelText('Motivo da devolução');m.read.mockRejectedValue(new Error('missing RPC'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-cost-return-preview']});});await waitFor(()=>expect(screen.queryByLabelText('Prévia da devolução')).not.toBeInTheDocument());expect(screen.queryByLabelText('Motivo da devolução')).not.toBeInTheDocument();expect(m.send).not.toHaveBeenCalled();});
it('restarts first page after revision drift despite Infinity cached first page',async()=>{m.options.mockResolvedValueOnce(options).mockRejectedValueOnce(new CostReturnMovementOptionsChangedError()).mockResolvedValueOnce({...options,revision:'f'.repeat(32),rows:[]});const cache=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity}}});render(<QueryClientProvider client={cache}><CostReturnMovementPicker tenant={i.tenant} actor={i.actor} dispositionId={i.disposition} onSelect={vi.fn()} onInvalidate={vi.fn()}/></QueryClientProvider>);await screen.findByText('Selecionar entrada Retorno do motorista');fireEvent.click(screen.getByText('Próxima página de entradas'));await waitFor(()=>expect(m.options).toHaveBeenCalledTimes(3));expect(m.options.mock.calls[2].slice(4)).toEqual([1,null]);expect(screen.queryByText('Selecionar entrada Retorno do motorista')).not.toBeInTheDocument();});

it('recovers the same request after a lost response even without a fresh preview',async()=>{m.send.mockRejectedValueOnce(new Error('lost')).mockImplementationOnce(async c=>returnSuccess(c));const refresh=vi.fn().mockResolvedValue(undefined);const view=render(<CostDispositionReturnConfirmation tenant={i.tenant} actor={i.actor} dispositionId={i.disposition} preview={p} refresh={refresh}/>);fireEvent.change(screen.getByLabelText('Motivo da devolução'),{target:{value:'Devolução parcial conferida'}});fireEvent.click(screen.getByText('Revisar devolução'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar devolução'));await screen.findByText('Recuperar pedido de devolução');view.rerender(<CostDispositionReturnConfirmation tenant={i.tenant} actor={i.actor} dispositionId={i.disposition} preview={undefined} refresh={refresh}/>);fireEvent.click(screen.getByText('Recuperar pedido de devolução'));await screen.findByText(/Devolução registrada: R\$ 10,00/);expect(m.send.mock.calls[1][0]).toEqual(m.send.mock.calls[0][0]);});

it('opens the selected responsibility from the portfolio and queries its own incoming options only',async()=>{m.portfolio.mockResolvedValue({version:1,tenant_id:i.tenant,page:1,page_size:30,total:1,revision:'a'.repeat(32),needs_review_count:0,gross_reserved_cents:'15000',applied_cents:'12000',residual_cents:'3000',driver_custody_cents:'3000',payment_recovery_cents:'0',returned_cents:'1000',open_cents:'2000',driver_custody_open_cents:'2000',payment_recovery_open_cents:'0',rows:[{expense_id:i.expense,charge_id:i.charge,payable_id:null,description:'Descarga conferida',occurred_on:'2026-09-11',coverage:{...regularizedCoverage,dispositions:[{...p.disposition!,returned_cents:'1000',open_cents:'2000',resolution_status:'partial'}]}}]});m.options.mockResolvedValue(options);const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><CostDispositionsWorkspace tenant={i.tenant} actor={i.actor}/></QueryClientProvider>);fireEvent.click(await screen.findByText('Conferir devolução de Motorista identificado'));await screen.findByRole('dialog');await screen.findByText('Selecionar entrada Retorno do motorista');expect(m.options).toHaveBeenCalledWith(i.tenant,i.actor,i.disposition,'',1,null);expect(m.send).not.toHaveBeenCalled();});
