import {beforeEach,expect,it,vi} from 'vitest';
import {readCustomerCreditOptions,readCustomerCreditPreview,sendCustomerCredit} from '@/lib/financial/customerCreditClient';
import {creditIds as i,creditPreview,creditCommand} from './helpers/customerCreditFixture';
const state=vi.hoisted(()=>({rpc:vi.fn(),receivers:[] as unknown[]}));const rpc=state.rpc;vi.mock('@/integrations/supabase/client',()=>{const client={rpc:function(this:unknown,...args:unknown[]){state.receivers.push(this);if(this!==client)throw Error('SDK receiver missing');return state.rpc(...args);}};return {supabase:client};});beforeEach(()=>{rpc.mockReset();state.receivers.length=0;});
it('uses the reviewed RPC and rejects foreign scope without a raw update fallback',async()=>{rpc.mockResolvedValueOnce({data:creditPreview,error:null});await readCustomerCreditPreview(i.tenant,i.actor,i.credit,i.target,'40000',null);expect(rpc).toHaveBeenLastCalledWith('preview_finance_customer_credit_application',{_tenant_id:i.tenant,_credit_id:i.credit,_receivable_id:i.target,_amount_cents:'40000',_application_id:null});rpc.mockResolvedValueOnce({data:{...creditPreview,actor_id:i.payer},error:null});await expect(readCustomerCreditPreview(i.tenant,i.actor,i.credit,i.target,'40000',null)).rejects.toThrow();rpc.mockResolvedValue({data:null,error:{code:'PGRST202'}});expect(await sendCustomerCredit(creditCommand)).toMatchObject({error:{code:'PGRST202'}});expect(rpc).toHaveBeenLastCalledWith('record_finance_customer_credit_application',{_payload:creditCommand});});
it('retains filters and revision in catalog requests and validates server echo',async()=>{const q={kind:'credits' as const,credit_id:null,payer_id:null,search:'Alfa',available_only:true,offset:0,limit:30,expected_revision:null};const result={version:1,tenant_id:i.tenant,actor_id:i.actor,...q,total:0,next_offset:null,revision:'a'.repeat(32),rows:[],can_execute:false};const {expected_revision:_,...data}=result;rpc.mockResolvedValue({data,error:null});await readCustomerCreditOptions(i.tenant,i.actor,q);expect(rpc).toHaveBeenLastCalledWith('get_finance_customer_credit_options',{_tenant_id:i.tenant,_query:q});rpc.mockResolvedValue({data:{...data,search:'outra'},error:null});await expect(readCustomerCreditOptions(i.tenant,i.actor,q)).rejects.toThrow();});
it('preserves the Supabase client receiver for real SDK method semantics',async()=>{
 const {supabase}=await import('@/integrations/supabase/client');rpc.mockResolvedValue({data:creditPreview,error:null});
 await readCustomerCreditPreview(i.tenant,i.actor,i.credit,i.target,'40000',null);expect(rpc).toHaveBeenCalledOnce();expect(state.receivers).toEqual([supabase]);
});
