// @vitest-environment node
import {it,expect} from 'vitest';import {randomUUID} from 'node:crypto';
import {createCustomerCreditApplicationDatabase} from './helpers/customerCreditApplicationDatabase';
import {operationIds as i,operationRpc} from './helpers/operationOutcomeDatabase';
import {financialCommand,financialPayload} from './helpers/receivableFinancialDatabase';
it('a new real cancelled observation changes the source fingerprint while preserving the same valid credit',async()=>{
 const db=await createCustomerCreditApplicationDatabase();try{await db.exec('begin');await db.query("insert into auth.users values($1,'credit-review@example.test','{}') on conflict(id) do nothing",[i.operator]);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);const payer=randomUUID(),cte=randomUUID(),emission=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Credit review payer',true)",[payer,i.tenant]);await db.query('insert into cte_documents(id,tenant_id,client_id,freight_value,net_value) values($1,$2,$3,100,100)',[cte,i.tenant,payer]);await db.query("insert into hub_fiscal_emissions(id,tenant_id,doc_type,environment,status,dispatch_state,cte_document_id,access_key,authorization_protocol,number) values($1,$2,'cte','production','authorized','recorded',$3,$4,$5,'123')",[emission,i.tenant,cte,'1'.repeat(44),'2'.repeat(15)]);
 const process=async()=>{const id=(await db.query<{id:string}>('select id from finance_fiscal_observations where emission_id=$1 order by observed_order desc limit 1',[emission])).rows[0].id;return(await operationRpc<{v:{status:string,receivable_id:string,issue:string|null}}>(db,'select process_finance_fiscal_observation($1,$2) v',[i.tenant,id])).rows[0].v;};const first=await process();expect(first.status).toBe('applied');await db.query("insert into bank_accounts(id,tenant_id,name) values('cf600000-0000-4000-8000-000000000001',$1,'Credit review bank')",[i.tenant]);await financialCommand(db,await financialPayload(db,first.receivable_id));await db.query("update hub_fiscal_emissions set status='cancelled' where id=$1",[emission]);expect((await process()).status).toBe('applied');const credit=(await db.query<{id:string}>('select id from finance_customer_credits where receivable_id=$1',[first.receivable_id])).rows[0].id;
 const proof=async()=>{return(await db.query<{v:{valid:boolean,source_revision:string}}>('select finance_private.forecast_customer_credit_evidence($1,$2) v',[i.tenant,credit])).rows[0].v;};const before=await proof();expect(before.valid).toBe(true);const original=(await db.query('select to_jsonb(c) v from finance_customer_credits c where id=$1',[credit])).rows;
 await db.query('update hub_fiscal_emissions set provider_document_version=2 where id=$1',[emission]);expect((await process()).status).toBe('applied');const after=await proof();expect(after.valid).toBe(true);expect(after.source_revision).not.toBe(before.source_revision);expect((await db.query('select to_jsonb(c) v from finance_customer_credits c where id=$1',[credit])).rows).toEqual(original);expect((await db.query<{n:number}>('select count(*)::int n from bank_transactions')).rows[0].n).toBe(1);await db.exec('rollback');}finally{await db.close();}
},30000);
