import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {CustomerCreditConfirmation} from '@/components/financial/CustomerCreditConfirmation';
import {CustomerCreditReview} from '@/components/financial/CustomerCreditReview';
import {CustomerCreditCatalogue} from '@/components/financial/CustomerCreditPanel';
import {customerCreditPreviewSchema,type CustomerCreditCommand} from '@/lib/financial/customerCreditContract';
import {CustomerCreditChangedError} from '@/lib/financial/customerCreditClient';
import {creditIds as i,creditPreview,creditResult} from './helpers/customerCreditFixture';
const mocks=vi.hoisted(()=>({send:vi.fn(),read:vi.fn(),options:vi.fn()}));
vi.mock('@/lib/financial/customerCreditClient',async original=>({...await original<typeof import('@/lib/financial/customerCreditClient')>(),sendCustomerCredit:(v:unknown)=>mocks.send(v),readCustomerCreditPreview:(...v:unknown[])=>mocks.read(...v),readCustomerCreditOptions:(...v:unknown[])=>mocks.options(...v)}));
vi.mock('@/components/financial/FinanceAccessBoundary',()=>({FinanceAccessBoundary:({children}:{children:React.ReactNode})=>children}));
const preview=customerCreditPreviewSchema.parse(creditPreview);
const wrapper=(node:React.ReactNode,cache=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity}}}))=><QueryClientProvider client={cache}>{node}</QueryClientProvider>;
beforeEach(()=>{localStorage.clear();Object.values(mocks).forEach(m=>m.mockReset());Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async<T,>(_key:string,work:()=>Promise<T>)=>work()}});});afterEach(cleanup);
function confirm(){fireEvent.change(screen.getByLabelText('Motivo'),{target:{value:'Aplicação conferida'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar aplicação'));}
it('recovers exact lost request and keeps terminal success despite refresh failure',async()=>{mocks.send.mockRejectedValueOnce(Error('network')).mockImplementationOnce(async(c:CustomerCreditCommand)=>({data:{...creditResult,request_id:c.request_id},error:null}));const refresh=vi.fn().mockRejectedValue(Error('refresh'));const view=render(<CustomerCreditConfirmation tenant={i.tenant} actor={i.actor} preview={preview} refresh={refresh}/>);confirm();await screen.findByText('Recuperar pedido de crédito');view.rerender(<CustomerCreditConfirmation tenant={i.tenant} actor={i.actor} preview={{...preview,amount_cents:'10000',revision:'b'.repeat(32)}} refresh={refresh}/>);expect(screen.getByText(/^Aplicar /)).toHaveTextContent('400,00');fireEvent.click(screen.getByText('Recuperar pedido de crédito'));await screen.findByText(/Aplicação registrada/);expect(mocks.send.mock.calls[0][0]).toEqual(mocks.send.mock.calls[1][0]);expect(screen.getByRole('alert')).toHaveTextContent('foi registrada');expect(screen.queryByText('Confirmar aplicação')).not.toBeInTheDocument();});
it('invalidates preview on amount edit and hides stale data during refetch',async()=>{mocks.read.mockResolvedValue(preview);const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(wrapper(<CustomerCreditReview tenant={i.tenant} actor={i.actor} creditId={i.credit} receivableId={i.target} applicationId={null} label="Fatura 500"/>,cache));fireEvent.change(screen.getByLabelText('Valor'),{target:{value:'400'}});fireEvent.click(screen.getByText('Conferir crédito'));await screen.findByLabelText('Motivo');let finish!:(v:unknown)=>void;mocks.read.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-customer-credit-preview']});});await waitFor(()=>expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument());await act(async()=>finish(preview));await screen.findByLabelText('Motivo');fireEvent.change(screen.getByLabelText('Valor'),{target:{value:'100'}});expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument();expect(mocks.send).not.toHaveBeenCalled();});
it('restarts stale pages through a fresh request even with infinite cache freshness',async()=>{const row={credit_id:i.credit,payer_id:i.payer,payer_name:'Cliente Alfa',original_cents:'60000',applied_cents:'0',released_cents:'0',available_cents:'60000',valid:true,revision:'a'.repeat(32),source_payment_id:i.event,created_at:'2026-09-11T12:00:00Z'};const base={version:1,tenant_id:i.tenant,actor_id:i.actor,kind:'credits',credit_id:null,payer_id:null,search:'',available_only:false,offset:0,limit:30,total:31,next_offset:30,revision:'a'.repeat(32),rows:Array.from({length:30},(_,n)=>({...row,credit_id:`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`})),can_execute:false};mocks.options.mockResolvedValueOnce(base).mockRejectedValueOnce(new CustomerCreditChangedError('changed')).mockResolvedValueOnce({...base,total:1,next_offset:null,revision:'b'.repeat(32),rows:[row]});render(wrapper(<CustomerCreditCatalogue tenant={i.tenant} actor={i.actor} kind="credits" creditId={null}/>));await screen.findByText(/31 registros/);fireEvent.click(screen.getByText('Próxima página'));await screen.findByText(/1 registros/);expect(mocks.options).toHaveBeenCalledTimes(3);expect(mocks.options.mock.calls[2][2]).toMatchObject({offset:0,expected_revision:null});});
it('blocks another actor and non-executable previews',()=>{const view=render(<CustomerCreditConfirmation tenant={i.tenant} actor={i.payer} preview={preview} refresh={async()=>{}}/>);expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument();view.rerender(<CustomerCreditConfirmation tenant={i.tenant} actor={i.actor} preview={{...preview,can_execute:false}} refresh={async()=>{}}/>);expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument();});
it('refreshes mounted catalog and portfolio after apply while keeping the confirmed outcome',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity}}});const invalidate=vi.spyOn(cache,'invalidateQueries');
 mocks.read.mockResolvedValue(preview);mocks.send.mockImplementation(async(c:CustomerCreditCommand)=>({data:{...creditResult,request_id:c.request_id},error:null}));
 render(wrapper(<CustomerCreditReview tenant={i.tenant} actor={i.actor} creditId={i.credit} receivableId={i.target} applicationId={null} label="Fatura 500"/>,cache));
 const keys=[['finance-customer-credit-options',i.tenant,i.actor,'history'],['finance-receivable-portfolio',i.tenant,i.actor],['receivables',i.tenant,i.actor]];
 keys.forEach(key=>cache.setQueryData(key,{fixture:true}));
 fireEvent.change(screen.getByLabelText('Valor'),{target:{value:'400'}});fireEvent.click(screen.getByText('Conferir crédito'));await screen.findByLabelText('Motivo');confirm();await screen.findByText(/Aplicação registrada/);
 await waitFor(()=>expect(mocks.read).toHaveBeenCalledTimes(2));expect(invalidate).toHaveBeenCalled();keys.forEach(key=>expect(cache.getQueryState(key)?.isInvalidated).toBe(true));expect(screen.queryByText('Confirmar aplicação')).not.toBeInTheDocument();
});
