import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {CustomerCreditRefundConfirmation} from '@/components/financial/CustomerCreditRefundConfirmation';
import {CustomerCreditRefundReview} from '@/components/financial/CustomerCreditRefundReview';
import {CustomerCreditRefundPanel} from '@/components/financial/CustomerCreditRefundPanel';
import {CustomerCreditRefundChangedError} from '@/lib/financial/customerCreditRefundClient';
import {customerCreditRefundPreviewSchema,type CustomerCreditRefundCommand} from '@/lib/financial/customerCreditRefundContract';
import {refundPreview,refundResult,refundIds as i} from './helpers/customerCreditRefundFixture';
const m=vi.hoisted(()=>({read:vi.fn(),send:vi.fn(),options:vi.fn()}));vi.mock('@/lib/financial/customerCreditRefundClient',async original=>({...await original<typeof import('@/lib/financial/customerCreditRefundClient')>(),readCustomerCreditRefundPreview:(...v:unknown[])=>m.read(...v),sendCustomerCreditRefund:(v:unknown)=>m.send(v),readCustomerCreditRefundOptions:(...v:unknown[])=>m.options(...v)}));
const p=customerCreditRefundPreviewSchema.parse(refundPreview);const wrap=(node:React.ReactNode,cache=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity}}}))=><QueryClientProvider client={cache}>{node}</QueryClientProvider>;
beforeEach(()=>{Object.values(m).forEach(f=>f.mockReset());localStorage.clear();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async<T,>(_key:string,work:()=>Promise<T>)=>work()}});});afterEach(cleanup);
function confirm(){fireEvent.change(screen.getByLabelText('Motivo'),{target:{value:'Devolução conferida'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar vínculo de devolução'));}
it('shows documents and distinct before/after values then hides permission on edit/refetch',async()=>{m.read.mockResolvedValue(p);const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(wrap(<CustomerCreditRefundReview tenant={i.tenant} actor={i.actor} creditId={i.credit} movementId={i.event}/>,cache));fireEvent.change(screen.getByLabelText('Valor da devolução'),{target:{value:'100'}});fireEvent.click(screen.getByText('Conferir devolução'));await screen.findByLabelText('Motivo');expect(screen.getByText(/Pagador:/)).toHaveTextContent('12345678901');expect(screen.getByText(/Crédito disponível antes:/)).toHaveTextContent(/600,00.*500,00/);expect(screen.getByText(/Capacidade da saída antes:/)).toHaveTextContent(/150,00.*50,00/);let done!:(v:unknown)=>void;m.read.mockImplementation(()=>new Promise(resolve=>{done=resolve;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-customer-credit-refund-preview']});});await waitFor(()=>expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument());await act(async()=>done(p));await screen.findByLabelText('Motivo');fireEvent.change(screen.getByLabelText('Valor da devolução'),{target:{value:'50'}});expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument();expect(m.send).not.toHaveBeenCalled();});
it('recovers original movement and effects after lost response, without repeating after confirmed cache failure',async()=>{m.send.mockRejectedValueOnce(Error('lost')).mockImplementationOnce(async(c:CustomerCreditRefundCommand)=>({data:{...refundResult,request_id:c.request_id},error:null}));const refresh=vi.fn().mockRejectedValue(Error('cache'));const v=render(<CustomerCreditRefundConfirmation tenant={i.tenant} actor={i.actor} preview={p} refresh={refresh}/>);confirm();await screen.findByText('Recuperar pedido de devolução');v.rerender(<CustomerCreditRefundConfirmation tenant={i.tenant} actor={i.actor} preview={undefined} refresh={refresh}/>);expect(screen.getByText(/Pedido preservado/)).toHaveTextContent(i.event);fireEvent.click(screen.getByText('Recuperar pedido de devolução'));await screen.findByText(/Devolução vinculada à saída/);expect(m.send.mock.calls[1][0]).toEqual(m.send.mock.calls[0][0]);expect(screen.getByRole('alert')).toHaveTextContent('foi registrada');expect(screen.queryByText('Confirmar vínculo de devolução')).not.toBeInTheDocument();});
it('restarts stale movement pages and never offers selection from the old page',async()=>{const row={movement_id:i.event,bank_account_id:i.target,bank_account_name:'Banco A',occurred_on:'2026-09-11',amount_cents:'20000',used_cents:'5000',available_cents:'15000',beneficiary_name:'Cliente Alfa',beneficiary_document:'12345678901',revision:'a'.repeat(32)};const base={version:1,tenant_id:i.tenant,actor_id:i.actor,credit_id:i.credit,payer_id:i.payer,kind:'movements',search:'',offset:0,limit:30,total:31,next_offset:30,revision:'a'.repeat(32),can_execute:false,rows:Array.from({length:30},(_,n)=>({...row,movement_id:`30000000-0000-4000-8000-${String(n).padStart(12,'0')}`}))};m.options.mockResolvedValueOnce(base).mockRejectedValueOnce(new CustomerCreditRefundChangedError('stale')).mockResolvedValueOnce({...base,total:0,next_offset:null,rows:[],revision:'b'.repeat(32)});render(wrap(<CustomerCreditRefundPanel tenant={i.tenant} actor={i.actor} creditId={i.credit}/>));await screen.findByText(/31 saídas compatíveis/);fireEvent.click(screen.getByText('Próxima página'));await screen.findByText(/0 saídas compatíveis/);expect(m.options).toHaveBeenCalledTimes(3);expect(m.options.mock.calls[2][3]).toMatchObject({offset:0,expected_revision:null});expect(screen.queryByText('Conferir saída de 2026-09-11')).not.toBeInTheDocument();});
