import {beforeEach,expect,it,vi} from 'vitest';
import {createDriverAdvanceReturnOutbox,driverAdvanceReturnKey,pendingDriverAdvanceReturn} from '@/lib/financial/driverAdvanceReturnOutbox';
import {reaisToCents} from '@/lib/financial/driverAdvanceReturnContract';

const scope={tenant:'10000000-0000-4000-8000-000000000001',actor:'10000000-0000-4000-8000-000000000002',advance:'10000000-0000-4000-8000-000000000003',incoming:'10000000-0000-4000-8000-000000000004',request:'10000000-0000-4000-8000-000000000005',returned:'10000000-0000-4000-8000-000000000006'};
const input={advance_movement_id:scope.advance,incoming_movement_id:scope.incoming,amount_cents:'5000',expected_revision:'a'.repeat(32),reason:'Devolução bancária conferida com o motorista',expected_open_cents:'0'};
const result=(command:Record<string,unknown>)=>({version:1,confirmed:true,tenant_id:scope.tenant,actor_id:scope.actor,request_id:command.request_id,return_id:scope.returned,advance_movement_id:scope.advance,incoming_movement_id:scope.incoming,amount_cents:'5000',cash_created:false,expense_created:false,open_cents:'0'});
beforeEach(()=>localStorage.clear());
it('converts Brazilian currency input to integer cents',()=>{expect(reaisToCents('50,00')).toBe('5000');expect(reaisToCents('1.234,56')).toBe('123456');expect(reaisToCents('0,00')).toBeNull();});
function build(send:ReturnType<typeof vi.fn>,context=()=>{}){return createDriverAdvanceReturnOutbox({storage:localStorage,uuid:()=>scope.request,assertContext:context,changed:()=>{},lock:async(_key,work)=>work(),send:send as Parameters<typeof createDriverAdvanceReturnOutbox>[0]['send']});}
it('preserves an uncertain request and replays the exact same command',async()=>{const send=vi.fn().mockRejectedValueOnce(Error('network')).mockImplementationOnce(async command=>({data:result(command),error:null})),outbox=build(send);await expect(outbox.submit(scope.tenant,scope.actor,input)).rejects.toThrow('network');const pending=pendingDriverAdvanceReturn(localStorage,scope.tenant,scope.actor);expect(pending?.payload.request_id).toBe(scope.request);await expect(outbox.recover(scope.tenant,scope.actor)).resolves.toMatchObject({request_id:scope.request,open_cents:'0'});expect(send.mock.calls[1][0]).toEqual(send.mock.calls[0][0]);expect(localStorage.getItem(driverAdvanceReturnKey(scope.tenant,scope.actor))).toBeNull();});
it('keeps the request when the actor context changes after sending',async()=>{let valid=true;const send=vi.fn(async command=>{valid=false;return{data:result(command),error:null};}),outbox=build(send,()=>{if(!valid)throw Error('context changed');});await expect(outbox.submit(scope.tenant,scope.actor,input)).rejects.toThrow('context changed');expect(pendingDriverAdvanceReturn(localStorage,scope.tenant,scope.actor)?.payload.request_id).toBe(scope.request);});
it('clears a new request after a definitive database rejection',async()=>{const send=vi.fn(async()=>({data:null,error:{code:'42501'}})),outbox=build(send);await expect(outbox.submit(scope.tenant,scope.actor,input)).rejects.toMatchObject({code:'42501'});expect(localStorage.getItem(driverAdvanceReturnKey(scope.tenant,scope.actor))).toBeNull();});
