import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {DriverAdvanceReturns} from '@/components/financial/DriverAdvanceReturns';

const mock=vi.hoisted(()=>({positions:vi.fn(),options:vi.fn(),preview:vi.fn(),send:vi.fn()}));
vi.mock('@/lib/financial/driverAdvanceReturnClient',()=>({readDriverAdvancePositions:(...args:unknown[])=>mock.positions(...args),readDriverAdvanceReturnOptions:(...args:unknown[])=>mock.options(...args),readDriverAdvanceReturnPreview:(...args:unknown[])=>mock.preview(...args),sendDriverAdvanceReturn:(...args:unknown[])=>mock.send(...args)}));
const i={tenant:'10000000-0000-4000-8000-000000000001',actor:'10000000-0000-4000-8000-000000000002',advance:'10000000-0000-4000-8000-000000000003',incoming:'10000000-0000-4000-8000-000000000004',account:'10000000-0000-4000-8000-000000000005',driver:'10000000-0000-4000-8000-000000000006',returned:'10000000-0000-4000-8000-000000000007'};
const position={version:1 as const,tenant_id:i.tenant,actor_id:i.actor,movement_id:i.advance,driver_id:i.driver,bank_account_id:i.account,occurred_on:'2026-09-01',amount_cents:'50000',allocated_cents:'45000',returned_cents:'0',open_cents:'5000',verified:true,issue:null,revision:'a'.repeat(32),history:[],account_name:'Banco principal',driver_name:'Motorista QA',history_count:0};
const positions={version:1 as const,tenant_id:i.tenant,actor_id:i.actor,page:1,page_size:30 as const,total:1,revision:'b'.repeat(32),rows:[position]};
const options={version:1 as const,tenant_id:i.tenant,actor_id:i.actor,advance_movement_id:i.advance,search:'',page:1,page_size:30 as const,total:1,revision:'c'.repeat(32),rows:[{id:i.incoming,bank_account_id:i.account,bank_account_name:'Banco principal',occurred_on:'2026-09-02',beneficiary_name:'Motorista QA',description:'Devolução do motorista',amount_cents:'5000',used_cents:'0',available_cents:'5000'}]};
const preview={version:1 as const,tenant_id:i.tenant,actor_id:i.actor,advance_movement_id:i.advance,incoming_movement_id:i.incoming,amount_cents:'5000',position:{...position,account_name:undefined,driver_name:undefined,history_count:undefined},incoming:{movement_id:i.incoming,bank_account_id:i.account,occurred_on:'2026-09-02',amount_cents:'5000',used_cents:'0',available_cents:'5000',counterparty_name:'Motorista QA'},effects:{open_before_cents:'5000',open_after_cents:'0',cash_created:false as const,expense_created:false as const,original_movement_changed:false as const},eligible:true,can_execute:true,blockers:[],revision:'d'.repeat(32)};
beforeEach(()=>{localStorage.clear();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async<T,>(_key:string,work:()=>Promise<T>)=>work()}});mock.positions.mockReset().mockResolvedValue(positions);mock.options.mockReset().mockResolvedValue(options);mock.preview.mockReset().mockResolvedValue(preview);mock.send.mockReset().mockImplementation(async command=>({data:{version:1,confirmed:true,tenant_id:i.tenant,actor_id:i.actor,request_id:command.request_id,return_id:i.returned,advance_movement_id:i.advance,incoming_movement_id:i.incoming,amount_cents:'5000',cash_created:false,expense_created:false,open_cents:'0'},error:null}));});afterEach(cleanup);
function open(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><DriverAdvanceReturns tenant={i.tenant} actor={i.actor}/></QueryClientProvider>);}
it('links an existing bank entry only after preview and explicit acknowledgement',async()=>{open();fireEvent.click(await screen.findByRole('button',{name:'Vincular devolução registrada'}));const select=await screen.findByLabelText('Entrada bancária devolvida');fireEvent.change(select,{target:{value:i.incoming}});expect(select).toHaveValue(i.incoming);const amountInput=screen.getByLabelText('Valor devolvido');fireEvent.change(amountInput,{target:{value:'50,00'}});expect(amountInput).toHaveValue('50,00');expect(screen.queryByText(/Informe um valor maior/)).not.toBeInTheDocument();const review=screen.getByRole('button',{name:'Conferir devolução'});expect(review).toBeEnabled();fireEvent.click(review);await waitFor(()=>expect(mock.preview).toHaveBeenCalledWith(i.tenant,i.actor,i.advance,i.incoming,'5000'));await screen.findByText(/Saldo antes:/);expect(screen.getByText('Confirmar vinculação')).toBeDisabled();fireEvent.change(screen.getByLabelText('Motivo da vinculação'),{target:{value:'Entrada bancária devolvida conferida'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar vinculação'));await screen.findByText(/Nenhum dinheiro novo foi criado/);expect(mock.send).toHaveBeenCalledOnce();expect(mock.send.mock.calls[0][0]).toMatchObject({tenant_id:i.tenant,advance_movement_id:i.advance,incoming_movement_id:i.incoming,amount_cents:'5000',expected_revision:preview.revision});});
it('hides stale preview while a refetch fails and never sends',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><DriverAdvanceReturns tenant={i.tenant} actor={i.actor}/></QueryClientProvider>);fireEvent.click(await screen.findByRole('button',{name:'Vincular devolução registrada'}));fireEvent.change(await screen.findByLabelText('Entrada bancária devolvida'),{target:{value:i.incoming}});fireEvent.change(screen.getByLabelText('Valor devolvido'),{target:{value:'50,00'}});fireEvent.click(screen.getByText('Conferir devolução'));await screen.findByText(/Saldo antes:/);mock.preview.mockRejectedValueOnce(Error('offline'));fireEvent.click(screen.getByText('Conferir devolução'));await waitFor(()=>expect(screen.queryByText(/Saldo antes:/)).not.toBeInTheDocument());expect(screen.getByText(/Não foi possível conferir esta devolução/)).toBeInTheDocument();expect(mock.send).not.toHaveBeenCalled();});
it('blocks new returns while recovery is corrupt and enables them after explicit discard',async()=>{const key=`agvlog:driver-advance-return:v1:${i.tenant}:${i.actor}`;localStorage.setItem(key,'broken');open();expect(await screen.findByRole('button',{name:'Vincular devolução registrada'})).toBeDisabled();expect(screen.getByRole('alert')).toHaveTextContent('pedido de devolução salvo está inconsistente');fireEvent.click(screen.getByRole('button',{name:'Descartar recuperação incompatível'}));expect(localStorage.getItem(key)).toBeNull();expect(screen.getByRole('button',{name:'Vincular devolução registrada'})).toBeEnabled();expect(screen.getByText(/Você pode iniciar uma nova devolução/)).toBeInTheDocument();expect(mock.send).not.toHaveBeenCalled();});
