import {expect,it} from 'vitest';
import {employeeAdvancePaymentCommandSchema,employeeAdvancePaymentPreviewSchema,employeeAdvancePaymentResultSchema} from '@/lib/financial/employeeAdvancePaymentContract';
const id=()=>crypto.randomUUID(),tenant=id(),actor=id(),advance=id(),movement=id();
function preview(){return{version:1,tenant_id:tenant,actor_id:actor,advance_id:advance,movement_id:movement,amount_cents:'4000',revision:'a'.repeat(32),eligible:true,can_pay:true,can_execute:true,blockers:[],advance:{version:1,tenant_id:tenant,advance_id:advance,employee_id:id(),employee_name:'Pessoa',employee_document:null,driver_id:null,status:'approved',payable_id:id(),payable_status:'approved',verified:true,issues:[],revision:'b'.repeat(32),amount_cents:'10000',paid_cents:'0',open_cents:'10000',payment_count:0},movement:{id:movement,bank_account_id:id(),occurred_on:'2026-09-11',beneficiary_name:'Pessoa',beneficiary_document:null,amount_cents:'5000',available_cents:'5000',identity_verified:true},effects:{cash_created:false,expense_created:false,create_payable:false,approve_payable:false,paid_before_cents:'0',paid_after_cents:'4000',open_after_cents:'6000'}};}
it('accepts a partial payment with preserved nominal and remaining balance',()=>{const v=preview();expect(employeeAdvancePaymentPreviewSchema.parse(v).effects.open_after_cents).toBe('6000');expect(employeeAdvancePaymentCommandSchema.parse({version:1,tenant_id:tenant,request_id:id(),advance_id:advance,movement_id:movement,amount_cents:'4000',expected_revision:v.revision,method:'pix',reason:'Saída conferida'}).amount_cents).toBe('4000');});
it('rejects mismatched identity, unproven composition, excess capacity and incorrect effects',()=>{const original=preview();for(const edit of [(v:ReturnType<typeof preview>)=>{v.advance.tenant_id=id();},(v:ReturnType<typeof preview>)=>{v.movement.identity_verified=false;},(v:ReturnType<typeof preview>)=>{v.movement.available_cents='3999';},(v:ReturnType<typeof preview>)=>{v.effects.paid_after_cents='4001';},(v:ReturnType<typeof preview>)=>{v.advance.verified=false;}]){const v=structuredClone(original);edit(v);expect(employeeAdvancePaymentPreviewSchema.safeParse(v).success).toBe(false);}expect(employeeAdvancePaymentPreviewSchema.safeParse({...original,advance:{...original.advance,verified:false,amount_cents:null,paid_cents:null,open_cents:null},movement:null}).success).toBe(false);});
it('rejects declaring a partial payment fully paid or creating cash',()=>{const result={version:1,confirmed:true,tenant_id:tenant,actor_id:actor,request_id:id(),advance_id:advance,payable_id:id(),payment_id:id(),link_id:id(),movement_id:movement,amount_cents:'4000',status:'approved',paid_cents:'4000',open_cents:'6000',cash_created:false,expense_created:false};expect(employeeAdvancePaymentResultSchema.safeParse(result).success).toBe(true);expect(employeeAdvancePaymentResultSchema.safeParse({...result,status:'paid'}).success).toBe(false);expect(employeeAdvancePaymentResultSchema.safeParse({...result,cash_created:true}).success).toBe(false);});

it('safeParse rejects malformed monetary strings without throwing and preserves reason bytes',()=>{for(const field of ['amount_cents','paid_cents','open_cents'] as const){const v=preview();v.advance[field]='not-money';expect(()=>employeeAdvancePaymentPreviewSchema.safeParse(v)).not.toThrow();expect(employeeAdvancePaymentPreviewSchema.safeParse(v).success).toBe(false);}for(const field of ['paid_before_cents','paid_after_cents','open_after_cents'] as const){const v=preview();v.effects[field]='no';expect(()=>employeeAdvancePaymentPreviewSchema.safeParse(v)).not.toThrow();expect(employeeAdvancePaymentPreviewSchema.safeParse(v).success).toBe(false);}const command={version:1,tenant_id:tenant,request_id:id(),advance_id:advance,movement_id:movement,amount_cents:'4000',expected_revision:'a'.repeat(32),method:'pix',reason:'  Saída conferida  '};expect(employeeAdvancePaymentCommandSchema.parse(command).reason).toBe(command.reason);expect(employeeAdvancePaymentCommandSchema.safeParse({...command,reason:'curto'}).success).toBe(false);});
