import {beforeEach,expect,it,vi} from 'vitest';
import {createEmployeeAdvancePaymentOutbox,pendingEmployeeAdvancePayment} from '@/lib/financial/employeeAdvancePaymentOutbox';
const i={tenant:crypto.randomUUID(),actor:crypto.randomUUID(),advance:crypto.randomUUID(),movement:crypto.randomUUID(),request:crypto.randomUUID(),event:crypto.randomUUID()};
const advanceInput={advance_id:i.advance,movement_id:i.movement,amount_cents:'4000',expected_revision:'a'.repeat(32),method:'pix' as const,reason:'Saída conferida',expected:{paid_cents:'4000',open_cents:'6000'}};
const advanceResult={version:1,confirmed:true,tenant_id:i.tenant,actor_id:i.actor,request_id:i.request,advance_id:i.advance,payable_id:crypto.randomUUID(),payment_id:crypto.randomUUID(),link_id:crypto.randomUUID(),movement_id:i.movement,amount_cents:'4000',status:'approved',paid_cents:'4000',open_cents:'6000',cash_created:false,expense_created:false};
beforeEach(()=>localStorage.clear());
function setup(){const send=vi.fn(),changed=vi.fn();return{send,outbox:createEmployeeAdvancePaymentOutbox({storage:localStorage,uuid:()=>i.request,changed,assertContext:()=>{},lock:async<T>(_key:string,work:()=>Promise<T>)=>work(),send})};}
it('persists before send and replays exact request after unknown',async()=>{const {send,outbox}=setup();send.mockImplementationOnce(async()=>{expect(pendingEmployeeAdvancePayment(localStorage,i.tenant,i.actor)?.payload.request_id).toBe(i.request);throw Error('network');}).mockResolvedValueOnce({data:advanceResult,error:null});await expect(outbox.submit(i.tenant,i.actor,advanceInput)).rejects.toThrow();expect(pendingEmployeeAdvancePayment(localStorage,i.tenant,i.actor)).not.toBeNull();await expect(outbox.recover(i.tenant,i.actor)).resolves.toMatchObject({advance_id:i.advance});expect(send.mock.calls[0][0]).toEqual(send.mock.calls[1][0]);expect(pendingEmployeeAdvancePayment(localStorage,i.tenant,i.actor)).toBeNull();});
it('clears known first rejection but retains the same rejection after an unknown attempt',async()=>{const {send,outbox}=setup();send.mockResolvedValue({data:null,error:{code:'40001',message:'changed'}});await expect(outbox.submit(i.tenant,i.actor,advanceInput)).rejects.toMatchObject({code:'40001'});expect(pendingEmployeeAdvancePayment(localStorage,i.tenant,i.actor)).toBeNull();send.mockRejectedValueOnce(Error('lost'));await expect(outbox.submit(i.tenant,i.actor,advanceInput)).rejects.toThrow();await expect(outbox.recover(i.tenant,i.actor)).rejects.toMatchObject({code:'40001'});expect(pendingEmployeeAdvancePayment(localStorage,i.tenant,i.actor)).not.toBeNull();});
it('rejects cross actor identities and preserves original request',async()=>{const {send,outbox}=setup();send.mockResolvedValue({data:{...advanceResult,actor_id:i.advance},error:null});await expect(outbox.submit(i.tenant,i.actor,advanceInput)).rejects.toThrow();expect(pendingEmployeeAdvancePayment(localStorage,i.tenant,i.actor)).not.toBeNull();await expect(outbox.submit(i.tenant,i.actor,{...advanceInput,amount_cents:'1'})).rejects.toThrow();expect(send).toHaveBeenCalledTimes(1);});
it('does not remove another tab record after receiving its own result',async()=>{const {send,outbox}=setup();send.mockImplementation(async()=>{const key=`agvlog:employee-advance-payment:v1:${i.tenant}:${i.actor}`;const row=JSON.parse(localStorage.getItem(key)!);row.payload.request_id=i.event;localStorage.setItem(key,JSON.stringify(row));return{data:advanceResult,error:null};});await outbox.submit(i.tenant,i.actor,advanceInput);expect(pendingEmployeeAdvancePayment(localStorage,i.tenant,i.actor)?.payload.request_id).toBe(i.event);});
