import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {EmployeeAdvancePaymentConfirmation} from '@/components/financial/EmployeeAdvancePaymentConfirmation';
import {employeeAdvancePaymentPreviewSchema} from '@/lib/financial/employeeAdvancePaymentContract';
import {advancePaymentPreview,paymentScope as scope} from './helpers/employeeAdvancePaymentFixture';
const mock=vi.hoisted(()=>({send:vi.fn()}));vi.mock('@/lib/financial/employeeAdvancePaymentClient',()=>({sendEmployeeAdvancePayment:(...args:unknown[])=>mock.send(...args)}));
beforeEach(()=>{localStorage.clear();mock.send.mockReset();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async<T,>(_key:string,work:()=>Promise<T>)=>work()}});});afterEach(cleanup);
function data(){return employeeAdvancePaymentPreviewSchema.parse(advancePaymentPreview());}
function result(command:Record<string,unknown>){return{version:1,confirmed:true,tenant_id:scope.tenant,actor_id:scope.actor,request_id:command.request_id,advance_id:scope.advance,payable_id:crypto.randomUUID(),payment_id:crypto.randomUUID(),link_id:crypto.randomUUID(),movement_id:scope.movement,amount_cents:'4000',status:'approved',paid_cents:'4000',open_cents:'6000',cash_created:false,expense_created:false};}
function confirm(){fireEvent.change(screen.getByLabelText('Motivo do vínculo'),{target:{value:'Saída do funcionário conferida'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar vínculo do pagamento'));}
it('preserves an unknown payment and replays original even after the preview changes',async()=>{mock.send.mockRejectedValueOnce(Error('network')).mockImplementationOnce(async(command:Record<string,unknown>)=>({data:result(command),error:null}));const refresh=vi.fn(async()=>{}),v=data();const view=render(<EmployeeAdvancePaymentConfirmation {...scope} preview={v} refresh={refresh}/>);confirm();await screen.findByText('Recuperar pagamento preservado');const original=mock.send.mock.calls[0][0];view.rerender(<EmployeeAdvancePaymentConfirmation {...scope} preview={{...v,revision:'c'.repeat(32)}} refresh={refresh}/>);fireEvent.click(screen.getByText('Recuperar pagamento preservado'));await screen.findByText(/Pagamento vinculado:/);expect(mock.send.mock.calls[1][0]).toEqual(original);expect(refresh).toHaveBeenCalledOnce();});
it('keeps confirmation terminal when refresh fails and invalidates acknowledgement on new preview',async()=>{mock.send.mockImplementation(async(command:Record<string,unknown>)=>({data:result(command),error:null}));const refresh=vi.fn(async()=>{throw Error('refetch');}),v=data();const view=render(<EmployeeAdvancePaymentConfirmation {...scope} preview={v} refresh={refresh}/>);fireEvent.change(screen.getByLabelText('Motivo do vínculo'),{target:{value:'Saída conferida com funcionário'}});fireEvent.click(screen.getByRole('checkbox'));view.rerender(<EmployeeAdvancePaymentConfirmation {...scope} preview={{...v,revision:'d'.repeat(32)}} refresh={refresh}/>);expect(screen.getByText('Confirmar vínculo do pagamento')).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar vínculo do pagamento'));await screen.findByText(/vínculo foi confirmado, mas/);expect(screen.queryByText('Confirmar vínculo do pagamento')).not.toBeInTheDocument();expect(mock.send).toHaveBeenCalledOnce();});
it('does not clear a pending request after the actor context changes during send',async()=>{let finish!:(value:unknown)=>void;mock.send.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));const v=data(),refresh=vi.fn(async()=>{});const view=render(<EmployeeAdvancePaymentConfirmation {...scope} preview={v} refresh={refresh}/>);confirm();await waitFor(()=>expect(mock.send).toHaveBeenCalledOnce());view.unmount();await act(async()=>finish({data:result(mock.send.mock.calls[0][0]),error:null}));expect(localStorage.length).toBe(1);expect(refresh).not.toHaveBeenCalled();});
