// @vitest-environment node
import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {it,expect} from 'vitest';
import {createPayrollRecordedAdvanceDatabase} from './helpers/payrollRecordedAdvanceDatabase';import {financeIds as i,financeAs} from './helpers/financeLedgerDatabase';
it('registers once, approves and cancels auditably while denying raw interactive mutations',async()=>{const db=await createPayrollRecordedAdvanceDatabase();try{
 await db.exec(readFileSync('supabase/migrations/20260911125548_finance_employee_advance_audited_lifecycle.sql','utf8'));await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);
 const employee=randomUUID();await db.query("insert into employees(id,tenant_id,name) values($1,$2,'Lifecycle employee')",[employee,i.tenant]);const day=(await db.query<{v:string}>("select (now() at time zone 'America/Sao_Paulo')::date::text v")).rows[0].v;
 const payload={version:1,tenant_id:i.tenant,request_id:randomUUID(),employee_id:employee,amount_cents:'10000',advance_date:day,reason:'Audited employee advance registration',payment_method:'bank_transfer',payment_reference:null,create_payable:false};
 const result=(await db.query<{v:{advance_id:string,status:string}}> ('select finance_private.record_employee_advance($1) v',[payload])).rows[0].v;expect(result.status).toBe('pending');
 expect((await db.query<{v:unknown}>('select finance_private.record_employee_advance($1) v',[payload])).rows[0].v).toEqual(result);expect((await db.query<{n:number}>('select count(*)::int n from employee_advances where employee_id=$1',[employee])).rows[0].n).toBe(1);
 await db.exec('savepoint raw');await expect(financeAs(db,i.operator,"update employee_advances set status='approved' where id=$1",[result.advance_id])).rejects.toMatchObject({code:'42501'});await db.exec('rollback to savepoint raw');
 for(const action of ['approve','cancel']){const ctx=(await db.query<{v:{eligible:boolean,revision:string}}>('select finance_private.employee_advance_action_context($1,$2,$3) v',[i.tenant,result.advance_id,action])).rows[0].v;expect(ctx.eligible).toBe(true);const command={version:1,tenant_id:i.tenant,request_id:randomUUID(),advance_id:result.advance_id,action,expected_revision:ctx.revision,reason:'Manager reviewed employee advance action'};
 const done=(await db.query<{v:{status:string}}> ('select finance_private.apply_employee_advance_action($1) v',[command])).rows[0].v;expect(done.status).toBe(action==='approve'?'approved':'cancelled');expect((await db.query<{v:unknown}>('select finance_private.apply_employee_advance_action($1) v',[command])).rows[0].v).toEqual(done);}
 const titledPayload={...payload,request_id:randomUUID(),create_payable:true,reason:'Audited titled employee advance registration'};
 const titled=(await db.query<{v:{advance_id:string;payable_id:string;status:string}}>('select finance_private.record_employee_advance($1) v',[titledPayload])).rows[0].v;
 expect(titled.status).toBe('pending');expect((await db.query('select status from payables where id=$1',[titled.payable_id])).rows[0]).toEqual({status:'pending'});
 const titledApproval=(await db.query<{v:{eligible:boolean;revision:string}}>("select finance_private.employee_advance_action_context($1,$2,'approve') v",[i.tenant,titled.advance_id])).rows[0].v;expect(titledApproval.eligible).toBe(true);
 await db.query('select finance_private.apply_employee_advance_action($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),advance_id:titled.advance_id,action:'approve',expected_revision:titledApproval.revision,reason:'Manager separately approved titled advance'}]);
 expect((await db.query<{n:number}>("select count(*)::int n from finance_events where tenant_id=$1 and entity_id=$2 and action='employee_advance_approved'",[i.tenant,titled.advance_id])).rows[0].n).toBe(1);
 expect((await db.query<{n:number}>('select count(*)::int n from bank_transactions')).rows[0].n).toBe(0);await db.exec('set constraints all immediate;rollback');
 }finally{await db.close();}},60000);
