// @vitest-environment node
import type {PGlite} from '@electric-sql/pglite';
import {afterAll,afterEach,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import {createEventChatDatabase,eventChatIds as i,eventChatSql,eventContext,eventPayload,eventSend,eventList,legacyEventSend} from './helpers/eventChatDatabase';
import {chatActor} from './helpers/driverChatDatabase';
import {operationRpc} from './helpers/operationOutcomeDatabase';
import {ownerStatement} from './helpers/deliveryAttemptDatabase';
let db:PGlite;beforeAll(async()=>{db=await createEventChatDatabase(true);});afterAll(()=>db?.close());beforeEach(async()=>{await db.exec('begin');await chatActor(db);});afterEach(()=>db.exec('rollback'));
const count=async()=>(await db.query<{n:number}>('select count(*)::int n from operational_event_messages')).rows[0].n;
describe('recoverable event chat',{timeout:15000},()=>{
 it('derives both identities and delivers the operation reply in the same occurrence',async()=>{
  expect(await eventSend(db,await eventPayload(db))).toMatchObject({event_id:i.event,confirmed:true,message:{sender_role:'driver',sender_name:'Motorista QA',driver_id:i.driver,conversation_user_id:i.user}});
  await chatActor(db,i.operator);await eventSend(db,await eventPayload(db,i.operator));await chatActor(db);expect((await eventList(db)).messages).toHaveLength(2);
 });
 it('replays the exact acknowledgement and refuses a different body for the same request',async()=>{const p=await eventPayload(db),a=await eventSend(db,p);expect(await eventSend(db,p)).toEqual(a);await expect(eventSend(db,{...p,message:'Changed'})).rejects.toThrow('request_mismatch');expect(await count()).toBe(1);});
 it('rejects forged identity, attachments, another tenant and unrelated events',async()=>{const p=await eventPayload(db);for(const extra of [{sender_role:'owner'},{sender_name:'Forjado'},{attachment_url:'https://invalid.test/x'}])await expect(eventSend(db,{...p,...extra})).rejects.toThrow('invalid_payload');await expect(eventSend(db,{...p,actor_id:i.operator})).rejects.toThrow('not_authorized');await expect(eventSend(db,{...p,event_id:i.foreignEvent})).rejects.toThrow('not_authorized');await expect(eventContext(db,i.peerEvent)).rejects.toThrow('not_authorized');});
 it('closes legacy insert and enforces immutable confirmed messages',async()=>{await expect(legacyEventSend(db)).rejects.toThrow('permission denied');await eventSend(db,await eventPayload(db));await expect(ownerStatement(db,"update operational_event_messages set message='Changed'")).rejects.toThrow('immutable');await expect(ownerStatement(db,'delete from operational_event_messages')).rejects.toThrow('immutable');});
 it('does not grant the new trip driver the original explicit event driver conversation or event row',async()=>{await eventSend(db,await eventPayload(db));await db.query('update dispatch_trips set driver_id=$1 where id=$2',[i.peerDriver,i.trip]);await chatActor(db,i.peerUser);await expect(eventList(db)).rejects.toThrow('not_authorized');expect((await operationRpc(db,'select * from operational_event_messages')).rows).toEqual([]);expect((await operationRpc(db,'select * from operational_events where id=$1',[i.event])).rows).toEqual([]);await chatActor(db);expect((await eventList(db)).messages).toHaveLength(1);});
 it('revocation denies reads, replay and table access despite an active driver profile',async()=>{const p=await eventPayload(db);await eventSend(db,p);await db.query('update tenant_memberships set active=false where user_id=$1',[i.user]);await expect(eventList(db)).rejects.toThrow('not_authorized');await expect(eventSend(db,p)).rejects.toThrow('not_authorized');expect((await operationRpc(db,'select * from operational_event_messages')).rows).toEqual([]);expect((await operationRpc(db,'select * from operational_events')).rows).toEqual([]);});
 it('prevents new operation sends to a revoked recipient while preserving its old acknowledgement',async()=>{await chatActor(db,i.operator);const p=await eventPayload(db,i.operator),a=await eventSend(db,p);await db.query('update tenant_memberships set active=false where user_id=$1',[i.user]);expect((await eventContext(db)).can_send).toBe(false);expect(await eventSend(db,p)).toEqual(a);await expect(eventSend(db,await eventPayload(db,i.operator))).rejects.toThrow('recipient_unavailable');});
 it('preserves an internal-only discussion and never shares it automatically after assigning a driver',async()=>{await chatActor(db,i.operator);const p=await eventPayload(db,i.operator,i.unassignedEvent);expect(await eventContext(db,i.unassignedEvent)).toMatchObject({driver_id:null,audience:'operation',can_send:true});await eventSend(db,p);await db.query('update operational_events set driver_id=$1 where id=$2',[i.driver,i.unassignedEvent]);await chatActor(db);expect((await eventList(db,i.unassignedEvent)).messages).toEqual([]);await chatActor(db,i.operator);expect(await eventSend(db,p)).toMatchObject({confirmed:true,driver_id:null});expect((await eventList(db,i.unassignedEvent)).messages).toHaveLength(1);});
 it('resolves trip and stop ownership only when the event has no explicit driver',async()=>{await db.query('update operational_events set driver_id=null,dispatch_trip_id=null where id=$1',[i.event]);expect((await eventContext(db)).driver_id).toBe(i.driver);await eventSend(db,await eventPayload(db));});
 it('fails closed on inconsistent stop/trip or cross-tenant bindings',async()=>{await chatActor(db,i.operator);await db.query('update operational_events set dispatch_trip_id=$1 where id=$2',[i.peerEvent,i.event]);await expect(eventContext(db)).rejects.toThrow('invalid_binding');await db.query('update operational_events set dispatch_trip_id=null,driver_id=$1 where id=$2',[i.foreignDriver,i.event]);await expect(eventContext(db)).rejects.toThrow('invalid_binding');});
 it('rejects stale context and does not expose old messages after event driver reassignment',async()=>{await chatActor(db,i.operator);const p=await eventPayload(db,i.operator);await eventSend(db,p);const next=await eventPayload(db,i.operator);await db.query('update operational_events set driver_id=$1 where id=$2',[i.peerDriver,i.event]);await expect(eventSend(db,next)).rejects.toThrow('context_changed');await chatActor(db,i.peerUser);expect((await eventList(db)).messages).toEqual([]);});
 it('does not reveal original messages after driver account replacement',async()=>{await eventSend(db,await eventPayload(db));await db.query('update drivers set user_id=$1 where id=$2',[i.peerUser,i.driver]);await chatActor(db,i.peerUser);expect((await eventList(db)).messages).toEqual([]);});
 it('pages newest-first with a scoped stable cursor',async()=>{for(let n=0;n<51;n++)await eventSend(db,await eventPayload(db,i.user,i.event,'Mensagem '+n));const first=await eventList(db),second=await eventList(db,i.event,first.next_cursor);expect(first.messages).toHaveLength(50);expect(second.messages).toHaveLength(1);expect(new Set([...first.messages,...second.messages].map(m=>m.id)).size).toBe(51);await chatActor(db,i.operator);await expect(eventList(db,i.peerEvent,first.next_cursor)).rejects.toThrow('invalid_cursor');});
 it('rolls back a late message failure and accepts the exact retry',async()=>{const p=await eventPayload(db);await db.exec("create function qa_event_chat_fail() returns trigger language plpgsql as $$begin raise exception 'QA late event message failure';end;$$;create trigger z_qa_event_chat_fail after insert on operational_event_messages for each row execute function qa_event_chat_fail();");await expect(eventSend(db,p)).rejects.toThrow('QA late event message failure');expect(await count()).toBe(0);await db.exec('drop trigger z_qa_event_chat_fail on operational_event_messages');await eventSend(db,p);expect(await count()).toBe(1);});
 it('requires administrative MFA and rejects a client or anonymous actor',async()=>{await chatActor(db,i.admin);await expect(eventContext(db)).rejects.toThrow('mfa_required');await chatActor(db,i.admin,'aal2');const p=await eventPayload(db,i.admin);await eventSend(db,p);await chatActor(db,i.admin);await expect(eventSend(db,p)).rejects.toThrow('mfa_required');await chatActor(db,i.client);await expect(eventContext(db)).rejects.toThrow('not_authorized');await db.exec("select set_config('request.jwt.claim.sub','',false)");await expect(eventContext(db)).rejects.toThrow('not_authorized');});
 it('validates message bounds and the recipient snapshot',async()=>{const p=await eventPayload(db);for(const message of ['', '   ','x'.repeat(4001),null,123])await expect(eventSend(db,{...p,message})).rejects.toThrow('invalid_message');await expect(eventSend(db,{...p,driver_id:i.peerDriver})).rejects.toThrow('context_changed');expect(await count()).toBe(0);});
 it('uses invoker wrappers and denies helper, anonymous and service access',async()=>{for(const fn of ['get_event_chat_context(uuid,uuid)','list_event_chat_messages(uuid,uuid,jsonb)','send_event_chat_message(jsonb)'])expect((await db.query<{ok:boolean}>("select not prosecdef and not has_function_privilege('anon',oid,'execute') and not has_function_privilege('service_role',oid,'execute') ok from pg_proc where oid=$1::regprocedure",[fn])).rows[0].ok).toBe(true);expect((await db.query<{ok:boolean}>("select has_function_privilege('authenticated','driver_chat_private.event_binding(uuid,uuid)','execute') ok")).rows[0].ok).toBe(false);});
 it('preserves legacy rows without assigning them to the current driver account',async()=>{const legacy=await createEventChatDatabase();try{await legacy.exec('begin');await chatActor(legacy);await legacyEventSend(legacy);await legacy.exec('commit');const rows=(await legacy.query('select id,message,created_at from operational_event_messages')).rows;await legacy.exec(eventChatSql());expect((await legacy.query('select id,message,created_at from operational_event_messages')).rows).toEqual(rows);await legacy.exec('begin');await chatActor(legacy);expect((await eventList(legacy)).messages).toEqual([]);await chatActor(legacy,i.operator);expect((await eventList(legacy)).messages[0].verified_sender).toBe(false);await legacy.exec('rollback');}finally{await legacy.close();}});
});
