import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {ExpenseBatchDialog} from '@/components/financial/ExpenseBatchDialog';
import {newExpenseLine,type ExpenseBatchDraft,type ExpenseLineDraft} from '@/lib/financial/expenseBatchContract';
const mock=vi.hoisted(()=>({record:vi.fn(),movement:{id:'',label:'Envio único de R$ 500',remaining_cents:50000,driver_id:''}}));
vi.mock('@/lib/financial/ledgerClient',()=>({recordExpenseBatch:mock.record,FinanceRejectedError:class extends Error{}}));
vi.mock('@/components/financial/FinanceOptionPicker',()=>({FinanceOptionPicker:({label,kind,onChange}:{label:string;kind:string;onChange:(v:unknown)=>void})=><button type="button" onClick={()=>{if(kind==='movements')onChange(mock.movement);}}>{label}</button>}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),driver=crypto.randomUUID(),trip=crypto.randomUUID(),key=`finance-expense-batch:${tenant}:${actor}`;
function seed(lines:ExpenseLineDraft[]=[{...newExpenseLine('office'),description:'Lanche',category:'food' as const,date:'2026-01-02',amount:'50,00',supplierName:'Padaria',document:'NF100',receiptPath:`${tenant}/finance-batches/comprovante.pdf`,receiptName:'comprovante.pdf',allocations:[]}],context:ExpenseBatchDraft['context']='office'){sessionStorage.setItem(key,JSON.stringify({request:null,draft:{context,trip:context==='trip'?{id:trip,label:'Viagem',driver_id:driver}:null,description:'Gastos conferidos',reason:'Conferência de retorno',lines}}));}
function open(){return render(<ExpenseBatchDialog tenant={tenant} actor={actor} onClose={vi.fn()} onRecorded={vi.fn()}/>);}
beforeEach(()=>{sessionStorage.clear();vi.clearAllMocks();mock.record.mockResolvedValue({confirmed:true});mock.movement.id=crypto.randomUUID();mock.movement.driver_id=driver;seed();});afterEach(()=>cleanup());
it('reuses only descriptive data with unique IDs and focuses new value; keyboard inserts after focused row without submitting',async()=>{open();const original=JSON.parse(sessionStorage.getItem(key)!).draft.lines[0];fireEvent.click(screen.getByRole('button',{name:'Reutilizar dados do gasto 1'}));await waitFor(()=>expect(screen.getByLabelText('Valor 2')).toHaveFocus());const rows=JSON.parse(sessionStorage.getItem(key)!).draft.lines;expect(rows[1]).toMatchObject({category:'food',description:'Lanche',date:'2026-01-02',supplierName:'Padaria',amount:'',document:'',receiptPath:'',receiptName:'',noReceiptReason:'',delivery:null,allocations:[]});expect(rows[1].id).not.toBe(original.id);fireEvent.keyDown(screen.getByLabelText('Descrição 1'),{key:'Enter',ctrlKey:true});await waitFor(()=>expect(screen.getByLabelText('Categoria 2')).toHaveFocus());expect(screen.getAllByRole('region',{name:/Gasto \d/})).toHaveLength(3);expect(mock.record).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Remover gasto 2'}));await waitFor(()=>expect(screen.getByLabelText('Categoria 2')).toHaveFocus());expect(JSON.parse(sessionStorage.getItem(key)!).draft.lines[1].id).toBe(rows[1].id);});
it('opens collapsed receipt details and focuses missing justification when review fails',async()=>{seed([{...newExpenseLine('office'),description:'Lanche',category:'food',date:'2026-01-02',amount:'50,00',supplierName:'Padaria',document:'',receiptPath:'',receiptName:'',allocations:[]}]);open();fireEvent.click(screen.getByRole('button',{name:'Recolher detalhes dos gastos'}));const details=screen.getByLabelText('Motivo sem comprovante 1').closest('details');await waitFor(()=>expect(details).not.toHaveAttribute('open'));fireEvent.click(screen.getByRole('button',{name:'Revisar lote'}));expect(await screen.findByRole('alert')).toHaveTextContent('anexe o comprovante');await waitFor(()=>expect(details).toHaveAttribute('open'));await waitFor(()=>expect(screen.getByLabelText('Motivo sem comprovante 1')).toHaveFocus());expect(mock.record).not.toHaveBeenCalled();});
it('keeps one shared transfer with three categorized expenses and delivery evidence through review',async()=>{const supplier=crypto.randomUUID(),stop=crypto.randomUUID(),base=newExpenseLine('trip');seed([{...base,id:crypto.randomUUID(),category:'fuel',description:'Combustível',amount:'300,00',date:'2026-01-02',supplierName:'Posto',document:'',receiptPath:`${tenant}/finance-batches/fuel.pdf`,receiptName:'fuel.pdf'},{...base,id:crypto.randomUUID(),category:'food',description:'Lanche',amount:'50,00',date:'2026-01-02',supplierName:'Padaria',document:'',receiptPath:`${tenant}/finance-batches/food.pdf`,receiptName:'food.pdf'},{...base,id:crypto.randomUUID(),category:'unloading',description:'Descarga',amount:'150,00',date:'2026-01-02',supplierName:'Prestador',document:'',receiptPath:`${tenant}/finance-batches/unloading.pdf`,receiptName:'unloading.pdf',delivery:{id:stop,label:'Entrega',delivery:{revision:'revision',issue:null,supplier_id:supplier,supplier_name:'Fornecedor NF',delivery_stop_id:stop,trip_id:trip}}}], 'trip');open();fireEvent.click(screen.getByRole('button',{name:'Envio compartilhado'}));fireEvent.click(screen.getByRole('button',{name:'Distribuir saldo entre os gastos'}));expect(within(screen.getByLabelText('Resumo do lote')).getByText(/Vinculado R\$ 500,00/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Revisar lote'}));fireEvent.click(screen.getByRole('button',{name:'Registrar lote conferido'}));await waitFor(()=>expect(mock.record).toHaveBeenCalledOnce());expect(mock.record.mock.calls[0][0].items).toEqual(expect.arrayContaining([expect.objectContaining({category:'fuel',amount_cents:30000,allocations:[{movement_id:mock.movement.id,amount_cents:30000}]}),expect.objectContaining({category:'food',amount_cents:5000,allocations:[{movement_id:mock.movement.id,amount_cents:5000}]}),expect.objectContaining({category:'unloading',amount_cents:15000,stop_id:stop,receipt_path:`${tenant}/finance-batches/unloading.pdf`,allocations:[{movement_id:mock.movement.id,amount_cents:15000}]})]));});

it('shows excess allocation in toolbar and batch summary while preventing registration',async()=>{seed([{...newExpenseLine('trip'),description:'Lanche',amount:'50,00',date:'2026-01-02',supplierName:'Padaria',receiptPath:`${tenant}/finance-batches/lanche.pdf`,receiptName:'lanche.pdf',allocations:[{movement:mock.movement,amount:'60,00'}]}],'trip');open();expect(screen.getByText('Excesso vinculado: R$ 10,00')).toBeInTheDocument();expect(within(screen.getByLabelText('Resumo do lote')).getByText(/Excesso vinculado: R\$ 10,00/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Revisar lote'}));await waitFor(()=>expect(screen.getByLabelText('Valor vinculado 1.1')).toHaveFocus());expect(screen.queryByRole('button',{name:'Registrar lote conferido'})).not.toBeInTheDocument();expect(mock.record).not.toHaveBeenCalled();});
it('focuses the date or delivery selector for the corresponding validation problem',async()=>{seed([{...newExpenseLine('office'),description:'Lanche',amount:'50,00',date:'',supplierName:'Padaria',noReceiptReason:'Comprovante solicitado'}]);const view=open();fireEvent.click(screen.getByRole('button',{name:'Revisar lote'}));await waitFor(()=>expect(screen.getByLabelText('Data 1')).toHaveFocus());view.unmount();seed([{...newExpenseLine('trip'),category:'unloading',description:'Descarga',amount:'50,00',supplierName:'Prestador',receiptPath:`${tenant}/finance-batches/descarga.pdf`,receiptName:'descarga.pdf'}],'trip');open();fireEvent.click(screen.getByRole('button',{name:'Revisar lote'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Entrega 1'})).toHaveFocus());expect(mock.record).not.toHaveBeenCalled();});
