import {beforeEach,it,expect,vi} from 'vitest';
import {prepareExpenseReceiptIntent,prepareBatchReceipt} from '@/lib/financial/expenseBatchReceiptClient';
const m=vi.hoisted(()=>({rpc:vi.fn(),upload:vi.fn()}));vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:m.rpc}}));vi.mock('@/lib/financial/uploadArtifactRecovery',()=>({uploadRecoverableFinanceArtifact:m.upload}));
const actor=crypto.randomUUID(),input={tenant_id:crypto.randomUUID(),batch_request_id:crypto.randomUUID(),expense_id:crypto.randomUUID(),context:'office' as const,trip_id:null,stop_id:null},intent=crypto.randomUUID();
beforeEach(()=>{localStorage.clear();vi.clearAllMocks();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_key:string,_options:unknown,fn:()=>Promise<unknown>)=>fn()}});m.rpc.mockImplementation(async(_name:string,{_payload}:{_payload:object})=>({data:{..._payload,actor_id:actor,intent_id:intent},error:null}));});
it('persists the same preparation request after a lost response and rejects another actor response',async()=>{m.rpc.mockResolvedValueOnce({data:null,error:{message:'network'}});await expect(prepareExpenseReceiptIntent(input,actor)).rejects.toThrow('sem confirmação');await prepareExpenseReceiptIntent(input,actor);expect(m.rpc.mock.calls[1][1]).toEqual(m.rpc.mock.calls[0][1]);m.rpc.mockImplementation(async(_name:string,{_payload}:{_payload:object})=>({data:{..._payload,actor_id:crypto.randomUUID(),intent_id:intent},error:null}));await expect(prepareExpenseReceiptIntent(input,actor)).rejects.toThrow('outro pedido');});
it('allocates a different intent request for changed context and does not upload unsupported files',async()=>{await prepareExpenseReceiptIntent(input,actor);await prepareExpenseReceiptIntent({...input,context:'personnel'},actor);expect(m.rpc.mock.calls[1][1]._payload.request_id).not.toBe(m.rpc.mock.calls[0][1]._payload.request_id);await expect(prepareBatchReceipt(input,actor,new File(['pdf'],'proof.pdf'))).rejects.toThrow('JPEG');expect(m.upload).not.toHaveBeenCalled();});
it('uses the prepared intent as artifact source and refuses quarantine as attached evidence',async()=>{m.upload.mockResolvedValueOnce({usable:false,state:'quarantined'});await expect(prepareBatchReceipt(input,actor,new File(['png'],'photo.png'))).rejects.toThrow('quarentena');expect(m.upload).toHaveBeenCalledWith(expect.objectContaining({sourceType:'expense_draft',sourceId:intent,actorId:actor}));m.upload.mockResolvedValueOnce({usable:true,state:'sanitized_derivative',artifact_id:crypto.randomUUID(),original:{sha256:'a'.repeat(64)}});expect(await prepareBatchReceipt(input,actor,new File(['png'],'photo.png'))).toMatchObject({intentId:intent,expenseId:input.expense_id,batchRequestId:input.batch_request_id});});

it('supports maintenance and other contexts and an extensionless JPEG identified by MIME',async()=>{await prepareExpenseReceiptIntent({...input,context:'maintenance'},actor);await prepareExpenseReceiptIntent({...input,context:'other'},actor);m.upload.mockResolvedValueOnce({usable:true,state:'sanitized_derivative',artifact_id:crypto.randomUUID(),original:{sha256:'a'.repeat(64)}});await prepareBatchReceipt(input,actor,new File(['photo'],'camera',{type:'image/jpeg'}));expect(m.upload).toHaveBeenCalledWith(expect.objectContaining({format:'jpeg'}));});
