import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {ExpenseCancellationWorkspace} from '@/components/financial/ExpenseCancellationReview';
import {ExpenseCancellationRejectedError} from '@/lib/financial/expenseCancellationClient';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));
vi.mock('@/lib/financial/expenseCancellationClient',()=>({readExpenseCancellation:mock.read,submitExpenseCancellation:mock.submit,ExpenseCancellationRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),expense=crypto.randomUUID(),key=`finance-expense-cancellation:${tenant}:${actor}:${expense}`;
const preview={version:1,tenant_id:tenant,expense_id:expense,revision:'a'.repeat(32),eligible:true,issue:null,can_execute:true,snapshot:{expense:{id:expense,tenant_id:tenant,batch_id:crypto.randomUUID(),description:'Lanche registrado duas vezes',category:'food',occurred_on:'2026-09-01'},payable:{id:crypto.randomUUID()}},cancellation:null,effects:{cost_removed_cents:'2500',obligation_cancelled_cents:'2500',cash_changed:false}};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(preview);mock.submit.mockResolvedValue({confirmed:true});});afterEach(cleanup);
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><ExpenseCancellationWorkspace tenant={tenant} actor={actor} expenseId={expense}/></QueryClientProvider>);}
async function review(){fireEvent.change(await screen.findByLabelText('Motivo do cancelamento'),{target:{value:'Gasto duplicado confirmado com recibo'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar cancelamento do gasto'}));}
it('requires review and preserves original command after uncertain response and remount',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await review();expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar cancelamento do gasto'}));await screen.findByText(/Não foi possível confirmar a resposta/);const original=mock.submit.mock.calls[0][0];view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar cancelamento do gasto'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);expect(sessionStorage.getItem(key)).toBeNull();});
it('unlocks a first known rollback but preserves previously uncertain requests',async()=>{mock.submit.mockRejectedValueOnce(new ExpenseCancellationRejectedError('finance_expense_cancellation_changed'));open();await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar cancelamento do gasto'}));await screen.findByText(/As informações mudaram/);expect(sessionStorage.getItem(key)).toBeNull();expect(await screen.findByLabelText('Motivo do cancelamento')).toHaveValue('Gasto duplicado confirmado com recibo');});
it('blocks corrupted storage and hides stale data after query failure',async()=>{sessionStorage.setItem(key,'broken');const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await screen.findByText(/Novos cancelamentos estão bloqueados/);expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();mock.read.mockRejectedValue(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-expense-cancellation']});});expect(await screen.findByText(/Não foi possível consultar o gasto/)).toBeInTheDocument();expect(screen.queryByText(/Custo a retirar/)).not.toBeInTheDocument();});
it('shows cancelled original with manual author and reason and no new action',async()=>{mock.read.mockResolvedValue({...preview,eligible:false,issue:'finance_expense_already_cancelled',cancellation:{id:crypto.randomUUID(),actor_id:actor,actor_name:'Maria',reason:'Duplicidade conferida',created_at:'2026-09-10'}});open();await screen.findByText(/Cancelamento manual por Maria/);expect(screen.getByText('Motivo: Duplicidade conferida')).toBeInTheDocument();expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();});
it('blocks confirmation when authoritative revision changes',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await review();mock.read.mockResolvedValue({...preview,revision:'b'.repeat(32)});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-expense-cancellation']});});expect(await screen.findByRole('button',{name:'Confirmar cancelamento do gasto'})).toBeDisabled();});
