import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {ExpenseBatchPaste} from '@/components/financial/ExpenseBatchPaste';
import {appendPastedExpenses} from '@/lib/financial/expenseBatchPaste';
import {ExpenseBatchDialog} from '@/components/financial/ExpenseBatchDialog';
import {newExpenseLine} from '@/lib/financial/expenseBatchContract';
const mock=vi.hoisted(()=>({record:vi.fn(),prepare:vi.fn()}));vi.mock('@/lib/financial/expenseBatchReceiptClient',()=>({prepareBatchReceipt:(...args:unknown[])=>mock.prepare(...args)}));vi.mock('@/lib/financial/ledgerClient',()=>({recordExpenseBatch:mock.record,FinanceRejectedError:class extends Error{}}));vi.mock('@/components/financial/FinanceOptionPicker',()=>({FinanceOptionPicker:({label}:{label:string})=><button type="button">{label}</button>}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),key=`finance-expense-batch:${tenant}:${actor}`;
beforeEach(()=>{sessionStorage.clear();mock.record.mockReset();sessionStorage.setItem(key,JSON.stringify({request:null,batchRequest:crypto.randomUUID(),draft:{context:'office',trip:null,description:'Existente',reason:'Conferência original',lines:[{...newExpenseLine('office'),description:'Gasto preservado',amount:'10,00',receiptPath:`${tenant}/original`,receiptName:'Original',supplierName:'Fornecedor'}]}}));});afterEach(cleanup);
function show(){render(<ExpenseBatchDialog tenant={tenant} actor={actor} onClose={()=>{}} onRecorded={()=>{}}/>);fireEvent.click(screen.getByText('Colar linhas de planilha'));}
it('previews and explicitly appends without overwriting existing lines or submitting, preserving in session',async()=>{show();const original=JSON.parse(sessionStorage.getItem(key)!).draft.lines[0],batch=JSON.parse(sessionStorage.getItem(key)!).batchRequest;fireEvent.change(screen.getByLabelText('Células copiadas'),{target:{value:'food\tLanche\t0,29\t11/09/2026\tPadaria\noffice\tPapel\t20,50\t11/09/2026\tLoja'}});fireEvent.click(screen.getByText('Conferir colagem'));expect(screen.getByRole('table',{name:'Prévia da colagem'})).toHaveTextContent('Lanche');expect(screen.getAllByRole('region',{name:/Gasto \d/})).toHaveLength(1);fireEvent.click(screen.getByText('Adicionar linhas ao rascunho'));await waitFor(()=>expect(screen.getAllByRole('region',{name:/Gasto \d/})).toHaveLength(3));const saved=JSON.parse(sessionStorage.getItem(key)!);expect(saved.draft.lines[0]).toEqual(original);expect(saved.batchRequest).toBe(batch);expect(new Set(saved.draft.lines.map((r:{id:string})=>r.id)).size).toBe(3);expect(saved.draft.lines[1]).toMatchObject({amount:'0,29',receiptPath:'',noReceiptReason:'',allocations:[]});expect(mock.record).not.toHaveBeenCalled();expect(screen.queryByText('Adicionar linhas ao rascunho')).not.toBeInTheDocument();});
it('shows per-line errors and requires another preview after changing input or context',()=>{show();fireEvent.change(screen.getByLabelText('Células copiadas'),{target:{value:'food\tLanche\t1.005\t11/09/2026'}});fireEvent.click(screen.getByText('Conferir colagem'));expect(screen.getByText('Adicionar linhas ao rascunho')).toBeDisabled();expect(screen.getByRole('table')).toHaveTextContent('duas casas decimais');fireEvent.change(screen.getByLabelText('Células copiadas'),{target:{value:'food\tLanche\t1,00\t11/09/2026'}});expect(screen.queryByText('Adicionar linhas ao rascunho')).not.toBeInTheDocument();fireEvent.click(screen.getByText('Conferir colagem'));fireEvent.change(screen.getByLabelText('Origem dos gastos'),{target:{value:'maintenance'}});expect(screen.queryByText('Adicionar linhas ao rascunho')).not.toBeInTheDocument();expect(mock.record).not.toHaveBeenCalled();});

it('appends during another row upload without unlocking that row or losing its eventual proof',async()=>{let finish!:(value:unknown)=>void;mock.prepare.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));show();const initial=JSON.parse(sessionStorage.getItem(key)!);fireEvent.change(screen.getByLabelText('Comprovante 1'),{target:{files:[new File(['png'],'proof.png',{type:'image/png'})]}});expect(screen.getByLabelText('Descrição 1')).toBeDisabled();expect(screen.getByText('Revisar lote')).toBeDisabled();fireEvent.change(screen.getByLabelText('Células copiadas'),{target:{value:'food\tNovo gasto\t1,00\t11/09/2026'}});fireEvent.click(screen.getByText('Conferir colagem'));fireEvent.click(screen.getByText('Adicionar linhas ao rascunho'));expect(screen.getByLabelText('Descrição 1')).toBeDisabled();expect(screen.getByLabelText('Descrição 2')).toBeEnabled();await act(async()=>finish({tenantId:tenant,actorId:actor,batchRequestId:initial.batchRequest,expenseId:initial.draft.lines[0].id,context:'office',tripId:null,stopId:null,intentId:crypto.randomUUID(),artifactId:crypto.randomUUID(),sha256:'a'.repeat(64),name:'proof.png'}));await waitFor(()=>expect(JSON.parse(sessionStorage.getItem(key)!).draft.lines[0].preparedReceipt?.artifactId).toBeTruthy());expect(JSON.parse(sessionStorage.getItem(key)!).draft.lines[1].description).toBe('Novo gasto');expect(mock.record).not.toHaveBeenCalled();});

it('retains the preview and reports a stale-capacity rejection without claiming append success',()=>{
 const original={context:'office' as const,trip:null,description:'Lote',reason:'Conferência',lines:Array.from({length:200},()=>newExpenseLine('office'))};
 const onAppend=vi.fn((rows:Parameters<typeof appendPastedExpenses>[1])=>{appendPastedExpenses(original,rows);});
 render(<ExpenseBatchPaste context="office" existingCount={1} disabled={false} onAppend={onAppend}/>);
 fireEvent.click(screen.getByText('Colar linhas de planilha'));
 fireEvent.change(screen.getByLabelText('Células copiadas'),{target:{value:'food\tLanche\t1,00\t11/09/2026'}});
 fireEvent.click(screen.getByText('Conferir colagem'));fireEvent.click(screen.getByText('Adicionar linhas ao rascunho'));
 expect(onAppend).toHaveBeenCalledOnce();expect(screen.getByRole('status')).toHaveTextContent('200');
 expect(screen.queryByText(/gastos adicionados ao rascunho/)).not.toBeInTheDocument();
 expect(screen.getByRole('table',{name:'Prévia da colagem'})).toBeInTheDocument();expect(original.lines).toHaveLength(200);
});
