import {beforeEach,it,expect,vi} from 'vitest';
import {readExpenseCancellation,submitExpenseCancellation,ExpenseCancellationRejectedError} from '@/lib/financial/expenseCancellationClient';
import {expenseCancellationPreviewSchema} from '@/lib/financial/expenseCancellationContract';
const mock=vi.hoisted(()=>vi.fn());vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mock}}));
const tenant=crypto.randomUUID(),expense=crypto.randomUUID(),command={version:1 as const,tenant_id:tenant,request_id:crypto.randomUUID(),expense_id:expense,revision:'a'.repeat(32),reason:'Duplicidade conferida'};
beforeEach(()=>mock.mockReset());
it('rejects successful result belonging to another expense',async()=>{mock.mockResolvedValue({error:null,data:{...command,expense_id:crypto.randomUUID(),cancellation_id:crypto.randomUUID(),payable_id:null,amount_cents:'1200',confirmed:true,cash_changed:false}});await expect(submitExpenseCancellation(command)).rejects.toThrow('Resposta fora');});
it('distinguishes definitive rollback from uncertain transport error',async()=>{mock.mockResolvedValue({data:null,error:{code:'40001',message:'finance_expense_cancellation_changed'}});await expect(submitExpenseCancellation(command)).rejects.toBeInstanceOf(ExpenseCancellationRejectedError);mock.mockResolvedValue({data:null,error:{message:'timeout'}});await expect(submitExpenseCancellation(command)).rejects.not.toBeInstanceOf(ExpenseCancellationRejectedError);});
it('rejects incomplete eligible effects and queries explicit expense identity',async()=>{const data={version:1,tenant_id:tenant,expense_id:expense,revision:command.revision,eligible:true,issue:null,can_execute:true,snapshot:{expense:{id:expense,tenant_id:tenant,batch_id:crypto.randomUUID(),description:'Gasto',category:'food',occurred_on:'2026-09-01'},payable:null},cancellation:null,effects:{cost_removed_cents:null,obligation_cancelled_cents:null,cash_changed:false}};expect(expenseCancellationPreviewSchema.safeParse(data).success).toBe(false);mock.mockResolvedValue({error:null,data});await expect(readExpenseCancellation(tenant,expense)).rejects.toThrow();expect(mock).toHaveBeenCalledWith('preview_finance_expense_cancellation',{_tenant_id:tenant,_expense_id:expense});});
