import userEvent from '@testing-library/user-event';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {ExpenseBatchDialog} from '@/components/financial/ExpenseBatchDialog';
import {newExpenseLine,buildExpenseBatch} from '@/lib/financial/expenseBatchContract';
const m=vi.hoisted(()=>({prepare:vi.fn(),record:vi.fn()}));vi.mock('@/lib/financial/expenseBatchReceiptClient',()=>({prepareBatchReceipt:m.prepare}));vi.mock('@/lib/financial/ledgerClient',async original=>({...await original<object>(),recordExpenseBatch:m.record}));vi.mock('@/components/financial/FinanceOptionPicker',()=>({FinanceOptionPicker:({label}:{label:string})=><button type="button">{label}</button>}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),trip=crypto.randomUUID(),stop=crypto.randomUUID(),supplier=crypto.randomUUID(),key=`finance-expense-batch:${tenant}:${actor}`;
function seed(){const line={...newExpenseLine('trip'),category:'unloading',description:'Descarga conferida',amount:'150,00',supplierName:'Prestador',payeeType:'supplier',delivery:{id:stop,label:'Entrega 1',delivery:{revision:'v1',issue:null,supplier_id:supplier,supplier_name:'Fornecedor NF',delivery_stop_id:stop,trip_id:trip}}};sessionStorage.setItem(key,JSON.stringify({request:null,draft:{context:'trip',trip:{id:trip,label:'Viagem 1'},description:'Gastos da viagem',reason:'Conferência dos gastos',lines:[line]}}));}
function open(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ExpenseBatchDialog tenant={tenant} actor={actor} onClose={()=>{}} onRecorded={()=>{}}/></QueryClientProvider>);}
beforeEach(()=>{sessionStorage.clear();vi.clearAllMocks();seed();m.prepare.mockImplementation(async(input:Record<string,unknown>,who:string,file:File)=>({tenantId:input.tenant_id,actorId:who,batchRequestId:input.batch_request_id,expenseId:input.expense_id,context:input.context,tripId:input.trip_id,stopId:input.stop_id,intentId:crypto.randomUUID(),artifactId:crypto.randomUUID(),sha256:'a'.repeat(64),name:file.name}));});afterEach(cleanup);
it('prepares unloading receipt in the same dialog and recovers the identical batch without a legacy path or false absence reason',async()=>{m.record.mockRejectedValueOnce(new Error('network')).mockResolvedValueOnce({confirmed:true});const first=open();const saved=JSON.parse(sessionStorage.getItem(key)!);expect(saved.batchRequest).toMatch(/^[a-f0-9-]{36}$/);fireEvent.change(screen.getByLabelText('Comprovante 1'),{target:{files:[new File(['png'],'receipt.png',{type:'image/png'})]}});await screen.findByText(/Cópia validada preparada/);expect(m.prepare).toHaveBeenCalledWith(expect.objectContaining({batch_request_id:saved.batchRequest,expense_id:saved.draft.lines[0].id,trip_id:trip,stop_id:stop}),actor,expect.any(File));fireEvent.click(screen.getByText('Revisar lote'));fireEvent.click(screen.getByText('Registrar lote conferido'));await waitFor(()=>expect(m.record).toHaveBeenCalledOnce());const command=m.record.mock.calls[0][0];expect(command.request_id).toBe(saved.batchRequest);expect(command.items[0]).toMatchObject({receipt_intent_id:expect.any(String),receipt_artifact_id:expect.any(String)});expect(command.items[0]).not.toHaveProperty('receipt_path');expect(command.items[0]).not.toHaveProperty('no_receipt_reason');await screen.findByText(/Pedido preservado/);first.unmount();open();fireEvent.click(screen.getByText('Reenviar mesmo lote'));await waitFor(()=>expect(m.record).toHaveBeenCalledTimes(2));expect(m.record.mock.calls[1][0]).toEqual(command);expect(m.prepare).toHaveBeenCalledOnce();});
it('invalidates prepared evidence when context changes and rejects a receipt from another actor or batch',async()=>{open();fireEvent.change(screen.getByLabelText('Comprovante 1'),{target:{files:[new File(['png'],'receipt.png')]}});await screen.findByText(/Cópia validada preparada/);const saved=JSON.parse(sessionStorage.getItem(key)!);expect(()=>buildExpenseBatch(saved.draft,tenant,crypto.randomUUID(),actor)).toThrow('outra origem');expect(()=>buildExpenseBatch(saved.draft,tenant,saved.batchRequest,crypto.randomUUID())).toThrow('outra origem');fireEvent.change(screen.getByLabelText('Origem dos gastos'),{target:{value:'office'}});await waitFor(()=>expect(JSON.parse(sessionStorage.getItem(key)!).draft.lines[0].preparedReceipt).toBeNull());expect(screen.queryByText(/Cópia validada preparada/)).not.toBeInTheDocument();});
it('does not accept a late prepared receipt after unmount and preserves the early batch identity across draft recovery',async()=>{let resolve!:(v:unknown)=>void;m.prepare.mockImplementation(()=>new Promise(r=>{resolve=r;}));const view=open(),first=JSON.parse(sessionStorage.getItem(key)!);fireEvent.change(screen.getByLabelText('Comprovante 1'),{target:{files:[new File(['png'],'receipt.png')]}});view.unmount();await act(async()=>resolve({intentId:crypto.randomUUID()}));open();expect(JSON.parse(sessionStorage.getItem(key)!).batchRequest).toBe(first.batchRequest);expect(screen.queryByText(/Cópia validada preparada/)).not.toBeInTheDocument();});

it('keeps registration locked until every concurrent row upload finishes',async()=>{
 const saved=JSON.parse(sessionStorage.getItem(key)!);saved.draft.lines.push({...saved.draft.lines[0],id:crypto.randomUUID(),category:'food',delivery:null});sessionStorage.setItem(key,JSON.stringify(saved));
 const pending:Array<{input:Record<string,unknown>;who:string;file:File;resolve:(value:unknown)=>void}>=[];m.prepare.mockImplementation((input:Record<string,unknown>,who:string,file:File)=>new Promise(resolve=>pending.push({input,who,file,resolve})));open();
 fireEvent.change(screen.getByLabelText('Comprovante 1'),{target:{files:[new File(['a'],'a.png')]}});fireEvent.change(screen.getByLabelText('Comprovante 2'),{target:{files:[new File(['b'],'b.png')]}});
 expect(pending).toHaveLength(2);const finish=(n:number)=>{const {input,who,file,resolve}=pending[n];resolve({tenantId:input.tenant_id,actorId:who,batchRequestId:input.batch_request_id,expenseId:input.expense_id,context:input.context,tripId:input.trip_id,stopId:input.stop_id,intentId:crypto.randomUUID(),artifactId:crypto.randomUUID(),sha256:'a'.repeat(64),name:file.name});};
 await act(async()=>finish(1));expect(screen.getByText('Revisar lote')).toBeDisabled();await act(async()=>finish(0));expect(screen.getByText('Revisar lote')).toBeEnabled();const final=JSON.parse(sessionStorage.getItem(key)!);expect(final.draft.lines.every((line:{preparedReceipt:unknown})=>!!line.preparedReceipt)).toBe(true);expect(buildExpenseBatch(final.draft,tenant,final.batchRequest,actor).items.every(item=>'receipt_artifact_id' in item&&!!item.receipt_artifact_id)).toBe(true);expect(m.record).not.toHaveBeenCalled();
});

it('shows confirmed image limits and keeps rejected dimensions out of the prepared batch',async()=>{m.prepare.mockRejectedValueOnce(new Error('Original recebido em quarentena. A imagem excede o limite de dimensões; envie uma versão menor. Nenhum comprovante foi vinculado a este gasto.'));open();expect(screen.getByText(/5.242.880 bytes.*2 megapixels/)).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Comprovante 1'),{target:{files:[new File(['png'],'large.png')]}});await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('limite de dimensões');expect(screen.queryByText(/Cópia validada preparada/)).not.toBeInTheDocument();expect(JSON.parse(sessionStorage.getItem(key)!).draft.lines[0].preparedReceipt).toBeNull();expect(m.record).not.toHaveBeenCalled();});

it('allows typing another row during upload while protecting the uploading row, scope and final send',async()=>{
 const saved=JSON.parse(sessionStorage.getItem(key)!);saved.draft.lines.push({...saved.draft.lines[0],id:crypto.randomUUID(),category:'food',delivery:null});sessionStorage.setItem(key,JSON.stringify(saved));
 let finish!:()=>void;m.prepare.mockImplementation((input:Record<string,unknown>,who:string,file:File)=>new Promise(resolve=>{finish=()=>resolve({tenantId:input.tenant_id,actorId:who,batchRequestId:input.batch_request_id,expenseId:input.expense_id,context:input.context,tripId:input.trip_id,stopId:input.stop_id,intentId:crypto.randomUUID(),artifactId:crypto.randomUUID(),sha256:'a'.repeat(64),name:file.name});}));
 const user=userEvent.setup();open();const initial=JSON.parse(sessionStorage.getItem(key)!);
 await user.upload(screen.getByLabelText('Comprovante 1'),new File(['png'],'receipt.png',{type:'image/png'}));
 expect(screen.getByLabelText('Descrição 1')).toBeDisabled();expect(screen.getByRole('button',{name:'Remover gasto 1'})).toBeDisabled();expect(screen.getByLabelText('Origem dos gastos')).toBeDisabled();expect(screen.getByRole('button',{name:'Distribuir saldo entre os gastos'})).toBeDisabled();expect(screen.getByText('Revisar lote')).toBeDisabled();
 expect(screen.getByLabelText('Descrição 2')).toBeEnabled();await user.clear(screen.getByLabelText('Descrição 2'));await user.type(screen.getByLabelText('Descrição 2'),'Lanche durante a viagem');await user.clear(screen.getByLabelText('Valor 2'));await user.type(screen.getByLabelText('Valor 2'),'25,00');await user.click(screen.getByRole('button',{name:'Adicionar gasto'}));expect(screen.getByLabelText('Categoria 3')).toBeEnabled();
 await act(async()=>finish());const latest=JSON.parse(sessionStorage.getItem(key)!);expect(latest.batchRequest).toBe(initial.batchRequest);expect(latest.draft.lines[0].id).toBe(initial.draft.lines[0].id);expect(latest.draft.lines[0].preparedReceipt).not.toBeNull();expect(latest.draft.lines[1]).toMatchObject({id:initial.draft.lines[1].id,description:'Lanche durante a viagem',amount:'25,00'});expect(latest.draft.lines).toHaveLength(3);expect(m.record).not.toHaveBeenCalled();
});
