// @vitest-environment node
import {randomUUID} from 'node:crypto';import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createManualExpenseCancellationDatabase} from './helpers/manualExpenseCancellationDatabase';import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createManualExpenseCancellationDatabase>>;
beforeAll(async()=>{db=await createManualExpenseCancellationDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(receipt=false){const path=`${i.tenant}/payable-payments/${randomUUID()}.pdf`;if(receipt)await db.query("insert into storage.objects(bucket_id,name,metadata) values('receipts',$1,'{\"mimetype\":\"application/pdf\",\"size\":1234}')",[path]);const original_request_id=randomUUID();const r=(await financeAs<{v:{payable_id:string}}>(db,i.operator,'select record_finance_manual_expense($1) v',[{version:1,tenant_id:i.tenant,request_id:original_request_id,supplier_name:'Papelaria QA',category:'office',description:'Material registrado em duplicidade',amount_cents:5000,competence_date:'2026-01-20',reason:'Registro da despesa para conferência',...(receipt?{receipt_path:path}:{})}])).rows[0].v;return{...r,original_request_id,path};}
async function payload(payable:string){const context=(await db.query<{v:{revision:string}}>('select finance_private.manual_expense_cancellation_context($1,$2) v',[i.tenant,payable])).rows[0].v;return{version:1,tenant_id:i.tenant,request_id:randomUUID(),payable_id:payable,revision:context.revision,reason:'Cancelamento auditado de despesa duplicada'};}
it('cancels manual cost and exact obligation preserving command, receipt and replay without a new expense',async()=>{const s=await seed(true),p=await payload(s.payable_id);const r=await financeAs(db,i.operator,'select cancel_finance_manual_expense($1) v',[p]);expect(await financeAs(db,i.operator,'select cancel_finance_manual_expense($1) v',[p])).toEqual(r);expect((await db.query('select status,amount::text from payables')).rows[0]).toEqual({status:'cancelled',amount:'50.00'});expect((await db.query('select count(*)::int n from finance_manual_expense_evidence')).rows[0]).toEqual({n:1});expect((await db.query('select count(*)::int n from finance_expense_items')).rows[0]).toEqual({n:0});expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:0});expect((await db.query<{v:{total_cents:string;rows:{cancelled:boolean}[]}}>("select finance_private.recorded_costs($1,'{}') v",[i.tenant])).rows[0].v).toMatchObject({total_cents:'0',rows:[{cancelled:true}]});});

it('does not hide a cost behind cancelled status without an audit event',async()=>{const s=await seed();await db.query("update payables set status='cancelled' where id=$1",[s.payable_id]);const summary=(await db.query<{v:{totals_valid:boolean;total_cents:null;invalid_count:number}}>('select finance_private.recorded_cost_summary($1,null,null,null,null) v',[i.tenant])).rows[0].v;expect(summary).toMatchObject({totals_valid:false,total_cents:null,invalid_count:1});expect((await db.query<{v:{rows:{cancelled:boolean;needs_review:boolean}[]}}>("select finance_private.recorded_costs($1,'{}') v",[i.tenant])).rows[0].v.rows[0]).toMatchObject({cancelled:false,needs_review:true});});
it('rejects stale review, invalid request and driver authorization',async()=>{const s=await seed(),p=await payload(s.payable_id);await expect(financeAs(db,i.driverUser,'select cancel_finance_manual_expense($1)',[p])).rejects.toThrow('finance_access_denied');await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[{...p,amount_cents:5000}])).rejects.toThrow('finance_invalid_payload');await db.query("update payables set notes='Mudança após revisão' where id=$1",[s.payable_id]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[p])).rejects.toThrow('finance_manual_expense_cancellation_changed');await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[p])).rejects.toThrow('finance_access_denied');});
it('preserves paid inconsistencies and changed amount as unresolved costs',async()=>{const s=await seed();await db.query("update payables set status='paid' where id=$1",[s.payable_id]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(s.payable_id)])).rejects.toThrow('finance_manual_expense_source_inconsistent');await db.query("update payables set status='pending',amount=60 where id=$1",[s.payable_id]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(s.payable_id)])).rejects.toThrow('finance_manual_expense_source_inconsistent');expect((await db.query('select count(*)::int n from finance_manual_expense_cancellations')).rows[0]).toEqual({n:0});});
it('preserves original receipt retention after cancellation and blocks reactivation or deletion',async()=>{const s=await seed(true);await financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(s.payable_id)]);await db.exec('savepoint protected');await expect(db.query("update payables set status='pending' where id=$1",[s.payable_id])).rejects.toThrow('finance_manual_expense_already_cancelled');await db.exec('rollback to savepoint protected');await expect(db.query('delete from payables where id=$1',[s.payable_id])).rejects.toThrow('finance_manual_expense_already_cancelled');await db.exec('rollback to savepoint protected');await expect(db.query('delete from storage.objects where name=$1',[s.path])).rejects.toThrow('finance_receipt_retention_required');await db.exec('rollback to savepoint protected');await expect(db.query('delete from finance_manual_expense_cancellations')).rejects.toThrow();await db.exec('rollback to savepoint protected');});
it('rejects duplicate original command identity and prevents ambiguous cancellation',async()=>{const s=await seed();await db.query("insert into finance_commands(tenant_id,request_id,actor_id,action,payload,result) select tenant_id,$1,actor_id,action,payload,result from finance_commands where request_id=$2",[randomUUID(),s.original_request_id]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(s.payable_id)])).rejects.toThrow('finance_manual_expense_source_inconsistent');});
it('keeps historical payments as blockers even when the payable cache says pending',async()=>{const s=await seed();await db.query("insert into payables_payments(tenant_id,payable_id,amount,method,paid_at,created_by,bank_account_id) values($1,$2,10,'pix','2026-01-20',$3,$4)",[i.tenant,s.payable_id,i.operator,i.account]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(s.payable_id)])).rejects.toThrow('finance_manual_expense_money_dependency');expect((await db.query('select count(*)::int n from payables_payments')).rows[0]).toEqual({n:1});});
it('blocks a closed interval through the same source resolver and leaves money and original unchanged',async()=>{const s=await seed();await db.query("insert into finance_account_period_closures(tenant_id,account_id,period_start,period_end,opening_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,'2026-01-01','2026-01-31',$3,'{}','historical fixture',$4,'QA','Historical closed account fixture',$5)",[i.tenant,i.account,randomUUID(),i.operator,randomUUID()]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(s.payable_id)])).rejects.toThrow('finance_manual_expense_closed_period_dependency');});
it('blocks existing advance materialization and forbids a new one after cancellation',async()=>{const s=await seed(),employee=randomUUID();await db.query("insert into employees(id,tenant_id,name) values($1,$2,'Funcionário QA')",[employee,i.tenant]);await db.query("insert into employee_advances(tenant_id,employee_id,amount,advance_date,status,payable_id) values($1,$2,50,'2026-01-20','approved',$3)",[i.tenant,employee,s.payable_id]);await expect(financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(s.payable_id)])).rejects.toThrow('finance_manual_expense_materialization_dependency');const separate=await seed();await financeAs(db,i.operator,'select cancel_finance_manual_expense($1)',[await payload(separate.payable_id)]);await db.exec('savepoint dependent');await expect(db.query("insert into employee_advances(tenant_id,employee_id,amount,advance_date,status,payable_id) values($1,$2,50,'2026-01-20','approved',$3)",[i.tenant,employee,separate.payable_id])).rejects.toThrow('finance_manual_expense_already_cancelled');await db.exec('rollback to savepoint dependent');});
