// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createExpenseCancellationDatabase} from './helpers/expenseCancellationDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createExpenseCancellationDatabase>>;
beforeAll(async()=>{db=await createExpenseCancellationDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(){const cost=randomUUID();await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:'office',description:'Compra incorreta registrada',reason:'Registro de compra conferido',items:[{id:cost,category:'office',amount_cents:5000,occurred_on:'2026-01-20',description:'Material registrado em duplicidade',supplier_name:'Papelaria QA',payee_type:'supplier',no_receipt_reason:'Documento solicitado ao fornecedor',allocations:[]}]}]);return cost;}
async function payload(cost:string){const c=(await db.query<{v:{revision:string}}>('select finance_private.expense_cancellation_context($1,$2) v',[i.tenant,cost])).rows[0].v;return{version:1,tenant_id:i.tenant,request_id:randomUUID(),expense_id:cost,revision:c.revision,reason:'Cancelamento de compra registrada em duplicidade'};}
it('cancels exact open obligation and cost, retaining source and replay without money',async()=>{const cost=await seed(),p=await payload(cost);const r=await financeAs(db,i.operator,'select cancel_finance_expense($1) v',[p]);expect(await financeAs(db,i.operator,'select cancel_finance_expense($1) v',[p])).toEqual(r);expect((await db.query('select status from payables')).rows[0]).toEqual({status:'cancelled'});expect((await db.query('select count(*)::int n from finance_expense_items')).rows[0]).toEqual({n:1});expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:0});});
it('retains original history while excluding cancelled cost from both server KPIs and candidate eligibility',async()=>{const cost=await seed();const before=(await db.query<{v:string}>('select finance_private.maintenance_labor_revision($1,$2,$3) v',[i.tenant,randomUUID(),cost])).rows[0].v;await financeAs(db,i.operator,'select cancel_finance_expense($1)',[await payload(cost)]);const costs=(await db.query<{v:{total_cents:string;rows:{cancelled:boolean}[]}}>("select finance_private.recorded_costs($1,'{}') v",[i.tenant])).rows[0].v;expect(costs.total_cents).toBe('0');expect((await db.query<{v:{total_cents:string}}>('select finance_private.recorded_cost_summary($1,null,null,null,null) v',[i.tenant])).rows[0].v.total_cents).toBe('0');expect(costs.rows[0].cancelled).toBe(true);expect((await db.query('select finance_private.maintenance_labor_issue($1,$2,$3) v',[i.tenant,randomUUID(),cost])).rows[0]).toEqual({v:'finance_expense_already_cancelled'});expect(before).toHaveLength(32);});
it('rejects stale previews, drivers and mixed driver membership without changing cost',async()=>{const cost=await seed(),p=await payload(cost);await expect(financeAs(db,i.driverUser,'select cancel_finance_expense($1)',[p])).rejects.toThrow('finance_access_denied');await db.query("update payables set description='Alteração após revisão' where source_id=$1",[cost]);await expect(financeAs(db,i.operator,'select cancel_finance_expense($1)',[p])).rejects.toThrow('finance_expense_cancellation_changed');await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(financeAs(db,i.operator,'select cancel_finance_expense($1)',[p])).rejects.toThrow('finance_access_denied');});
it('blocks duplicated obligation and paid status without pretending zero payments is unpaid',async()=>{const cost=await seed();await db.query("update payables set status='paid' where source_id=$1",[cost]);expect((await db.query<{v:{issue:string}}>('select finance_private.expense_cancellation_context($1,$2) v',[i.tenant,cost])).rows[0].v.issue).toBe('finance_expense_payable_inconsistent');await db.query("update payables set status='pending' where source_id=$1",[cost]);await db.query("insert into payables(tenant_id,supplier_name,category,description,amount,status,source_table,source_id) values($1,'Duplicado','other','Título duplicado',50,'pending','finance_expense_items',$2)",[i.tenant,cost]);await expect(financeAs(db,i.operator,'select cancel_finance_expense($1)',[await payload(cost)])).rejects.toThrow('finance_expense_payable_inconsistent');});
it('prevents cancelled payable reactivation and a future duplicate materialization',async()=>{const cost=await seed();await financeAs(db,i.operator,'select cancel_finance_expense($1)',[await payload(cost)]);await db.exec('savepoint protected');await expect(db.query("update payables set status='pending' where source_id=$1",[cost])).rejects.toThrow('finance_expense_already_cancelled');await db.exec('rollback to savepoint protected');await expect(db.query("insert into payables(tenant_id,supplier_name,category,description,amount,status,source_table,source_id) values($1,'Duplicado','other','Título duplicado',50,'pending','finance_expense_items',$2)",[i.tenant,cost])).rejects.toThrow('finance_expense_already_cancelled');await db.exec('rollback to savepoint protected');await expect(db.query('delete from finance_expense_cancellations')).rejects.toThrow();await db.exec('rollback to savepoint protected');});
it('resolves driver payee from the real original command, separately from the establishment',async()=>{const cost=randomUUID(),trip=randomUUID(),supplier=randomUUID();await db.query("insert into clients(id,tenant_id,company_name) values($1,$2,'Restaurante QA')",[supplier,i.tenant]);await db.query("insert into dispatch_trips(id,tenant_id,driver_id,status,actual_end_at) values($1,$2,$3,'completed','2026-01-20T12:00:00Z')",[trip,i.tenant,i.driver]);await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:'trip',trip_id:trip,description:'Refeição registrada em duplicidade',reason:'Registro completo para conferência',items:[{id:cost,category:'food',amount_cents:5000,occurred_on:'2026-01-20',description:'Refeição do motorista',supplier_id:supplier,supplier_name:'Restaurante QA',payee_type:'driver',no_receipt_reason:'Documento solicitado ao fornecedor',allocations:[]}]}]);expect((await db.query('select count(*)::int n from finance_private.canonical_trip_costs($1,$2)',[i.tenant,trip])).rows[0]).toEqual({n:1});await financeAs(db,i.operator,'select cancel_finance_expense($1)',[await payload(cost)]);expect((await db.query('select count(*)::int n from finance_private.canonical_trip_costs($1,$2)',[i.tenant,trip])).rows[0]).toEqual({n:0});});

it('blocks existing allocation without deleting the recorded movement',async()=>{const cost=await seed(),movement=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,'out','payment',1000,'2026-01-20','Saída já existente','Papelaria QA',$4)",[movement,i.tenant,i.account,i.operator]);await db.query('insert into finance_expense_allocations(tenant_id,expense_id,movement_id,amount_cents,created_by) values($1,$2,$3,1000,$4)',[i.tenant,cost,movement,i.operator]);await expect(financeAs(db,i.operator,'select cancel_finance_expense($1)',[await payload(cost)])).rejects.toThrow('finance_expense_money_dependency');expect((await db.query('select amount_cents::text from finance_movements')).rows[0]).toEqual({amount_cents:'1000'});});
it('blocks closed period via the actual frozen-source resolver before exposing eligibility',async()=>{const cost=await seed();await db.query("insert into finance_account_period_closures(tenant_id,account_id,period_start,period_end,opening_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,'2026-01-01','2026-01-31',$3,'{}','historical fixture',$4,'QA','Historical closed account fixture',$5)",[i.tenant,i.account,randomUUID(),i.operator,randomUUID()]);expect((await db.query<{v:{issue:string;eligible:boolean}}>('select finance_private.expense_cancellation_context($1,$2) v',[i.tenant,cost])).rows[0].v).toMatchObject({eligible:false,issue:'finance_expense_closed_period_dependency'});await expect(financeAs(db,i.operator,'select cancel_finance_expense($1)',[await payload(cost)])).rejects.toThrow('finance_expense_closed_period_dependency');});


it('keeps existing maintenance claims as an explicit dependency',async()=>{const cost=await seed();await db.query("insert into finance_maintenance_cost_claims(tenant_id,cost_id,source_kind,source_id,link_id) values($1,$2,'labor',$3,$4)",[i.tenant,cost,randomUUID(),randomUUID()]);await expect(financeAs(db,i.operator,'select cancel_finance_expense($1)',[await payload(cost)])).rejects.toThrow('finance_expense_source_association_dependency');expect((await db.query('select count(*)::int n from finance_expense_cancellations')).rows[0]).toEqual({n:0});});
