import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {useState} from 'react';
import {afterEach,it,expect,vi} from 'vitest';
import {FinanceOptionPicker} from '@/components/financial/FinanceOptionPicker';
import type {FinanceOption} from '@/lib/financial/expenseBatchContract';
const read=vi.hoisted(()=>vi.fn(async():Promise<{total:number;rows:Array<{id:string;label:string;remaining_cents?:number}>}>=>({total:1,rows:[{id:crypto.randomUUID(),label:'Fornecedor de teste'}]})));vi.mock('@/lib/financial/ledgerClient',()=>({readExpenseOptions:read}));afterEach(()=>cleanup());
it('focuses search on opening and returns to the selector after choosing or escaping',async()=>{const change=vi.fn();render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><FinanceOptionPicker tenant={crypto.randomUUID()} actor={crypto.randomUUID()} kind="suppliers" label="Fornecedor 1" value={null} onChange={change}/></QueryClientProvider>);const trigger=screen.getByRole('button',{name:'Fornecedor 1: Selecionar'});fireEvent.click(trigger);expect(screen.getByLabelText('Buscar Fornecedor 1')).toHaveFocus();fireEvent.click(await screen.findByRole('button',{name:'Fornecedor de teste'}));expect(trigger).toHaveFocus();expect(change).toHaveBeenCalledOnce();fireEvent.click(trigger);fireEvent.keyDown(screen.getByLabelText('Buscar Fornecedor 1'),{key:'Escape'});expect(trigger).toHaveFocus();expect(trigger).toHaveAttribute('aria-expanded','false');});

it('keeps a valid choice but blocks cached money until a refetch returns the reduced balance',async()=>{const id=crypto.randomUUID(),tenant=crypto.randomUUID(),actor=crypto.randomUUID(),change=vi.fn();read.mockResolvedValueOnce({total:1,rows:[{id,label:'Envio conferido',remaining_cents:10_000}]});const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});function Story(){const[value,setValue]=useState<FinanceOption|null>(null);return <FinanceOptionPicker tenant={tenant} actor={actor} kind="movements" label="Envio" value={value} onChange={option=>{change(option);setValue(option);}}/>;}render(<QueryClientProvider client={cache}><Story/></QueryClientProvider>);const trigger=screen.getByRole('button',{name:'Envio: Selecionar'});fireEvent.click(trigger);fireEvent.click(await screen.findByRole('button',{name:'Envio conferido · Disponível R$ 100,00'}));expect(trigger).toHaveAccessibleName('Envio: Envio conferido');expect(change).toHaveBeenCalledOnce();let finish!:(value:{total:number;rows:Array<{id:string;label:string;remaining_cents?:number}>})=>void;read.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));fireEvent.click(trigger);await waitFor(()=>expect(screen.queryByRole('button',{name:'Envio conferido · Disponível R$ 100,00'})).not.toBeInTheDocument());expect(screen.getByRole('status')).toHaveTextContent('Conferindo opções');expect(trigger).toHaveAccessibleName('Envio: Envio conferido');expect(change).toHaveBeenCalledOnce();await act(async()=>finish({total:1,rows:[{id,label:'Envio conferido',remaining_cents:2_500}]}));const refreshed=await screen.findByRole('button',{name:'Envio conferido · Disponível R$ 25,00'});expect(screen.queryByRole('button',{name:'Envio conferido · Disponível R$ 100,00'})).not.toBeInTheDocument();fireEvent.click(refreshed);expect(change).toHaveBeenCalledTimes(2);expect(change).toHaveBeenLastCalledWith(expect.objectContaining({id,remaining_cents:2_500}));});
