// @vitest-environment node
import {it,expect} from 'vitest';import {readFileSync} from 'node:fs';import {createFinanceForwardBlockDatabase} from './helpers/financeForwardBlockDatabase';
it('validates descriptors atomically and keeps retries no-op without executing a scheduler',async()=>{const {db}=await createFinanceForwardBlockDatabase('20260910212551',true);try{
await db.exec(`create schema cron;create table cron.job(jobid bigint primary key,jobname text,schedule text,command text,active boolean,database text,username text);
create function cron.alter_job(job_id bigint,schedule text default null,command text default null,database text default null,username text default null,active boolean default null) returns void language plpgsql as $$begin raise exception 'qa_scheduler_not_executed';end$$;`);
await db.query("insert into cron.job values(24,'finance-fiscal-projection-every-minute','* * * * *',$1,true,'postgres','postgres'),(25,'finance-bank-reconciliation-every-minute','* * * * *',$2,true,'postgres','postgres'),(999,'unrelated','0 0 * * *','select 1',false,'postgres','postgres')",["SET statement_timeout = '25s'; SELECT finance_private.run_fiscal_queue(50);","SET statement_timeout = '25s'; SELECT finance_private.run_automatic_reconciliation_queue();"]);
const sql=readFileSync('supabase/rollouts/20260911043147_finance_known_workers_resume_via_api.sql','utf8');const before=(await db.query('select * from cron.job order by jobid')).rows;await db.exec('begin');await db.exec(sql);await db.exec(sql);expect((await db.query('select * from cron.job order by jobid')).rows).toEqual(before);await db.exec('rollback');
await db.exec("update cron.job set active=false where jobid=24;update cron.job set command='select 42' where jobid=25;");await db.exec('begin');await expect(db.exec(sql)).rejects.toThrow('finance_worker_job_changed');await db.exec('rollback');expect((await db.query<{v:boolean}>('select active v from cron.job where jobid=24')).rows[0].v).toBe(false);
await db.query('update cron.job set command=$1 where jobid=25',["SET statement_timeout = '25s'; SELECT finance_private.run_automatic_reconciliation_queue();"]);await db.exec('begin');await expect(db.exec(sql)).rejects.toThrow('qa_scheduler_not_executed');await db.exec('rollback');expect((await db.query<{v:boolean}>('select active v from cron.job where jobid=24')).rows[0].v).toBe(false);
}finally{await db.close();}},120000);
