// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createStockAcquisitionDatabase} from './helpers/stockAcquisitionDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createStockAcquisitionDatabase>>;
beforeAll(async()=>{db=await createStockAcquisitionDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});
afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(category='maintenance'){const inbound=randomUUID(),item=randomUUID(),cost=randomUUID(),supplier=randomUUID();
 await db.query("insert into clients(id,tenant_id,company_name) values($1,$2,'Fornecedor conferido')",[supplier,i.tenant]);
 await db.query("insert into stock_items(id,tenant_id,name,category,unit) values($1,$2,'Filtro','filter','un')",[item,i.tenant]);
 await db.query("insert into stock_movements(id,tenant_id,stock_item_id,movement_type,quantity,unit_cost,total_cost,reason,moved_at) values($1,$2,$3,'inbound',10,5,50,'purchase','2026-01-20')",[inbound,i.tenant,item]);
 await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:category==='office'?'office':'maintenance',description:'Compra de filtros',reason:'Compra integral conferida',items:[{id:cost,category,document_number:'NF-123',amount_cents:5000,occurred_on:'2026-01-20',description:'Filtros para estoque',supplier_id:supplier,supplier_name:'Fornecedor conferido',payee_type:'supplier',no_receipt_reason:'Documento solicitado ao fornecedor',allocations:[]}]}]);return{inbound,item,cost,supplier};}
async function revision(s:Awaited<ReturnType<typeof seed>>){return(await db.query<{v:string}>('select finance_private.stock_acquisition_revision($1,$2,$3) v',[i.tenant,s.inbound,s.cost])).rows[0].v;}
async function payload(s:Awaited<ReturnType<typeof seed>>){return{version:1,tenant_id:i.tenant,request_id:randomUUID(),inbound_movement_id:s.inbound,cost_id:s.cost,revision:await revision(s),reason:'Conferi a compra pelo documento original',same_purchase_confirmed:true,quantity:'10',document_number:'NF-123'};}
async function link(p:Record<string,unknown>,actor=i.operator){return(await financeAs<{v:Record<string,unknown>}>(db,actor,'select associate_finance_stock_acquisition($1) v',[p])).rows[0].v;}
async function reverse(s:Awaited<ReturnType<typeof seed>>,id:unknown){return(await financeAs<{v:Record<string,unknown>}>(db,i.operator,'select reverse_finance_stock_acquisition_association($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),link_id:id,revision:await revision(s),reason:'Desfazendo associação após conferência'}])).rows[0].v;}
it('associates and replays without changing purchase, payable, cash or quantity',async()=>{const s=await seed(),p=await payload(s),before=(await db.query('select * from payables')).rows;const r=await link(p);expect(r).toMatchObject({amount_cents:'5000',quantity:'10',cash_changed:false,cost_created:false,obligation_created:false});expect(await link(p)).toEqual(r);expect((await db.query('select * from payables')).rows).toEqual(before);expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:0});});
it('rejects declarations, drivers and stale source review',async()=>{const s=await seed(),p=await payload(s);await expect(link({...p,same_purchase_confirmed:false})).rejects.toThrow('finance_invalid_payload');await expect(link({...p,quantity:'9'})).rejects.toThrow('declaration_mismatch');await expect(link(p,i.driverUser)).rejects.toThrow('finance_access_denied');await db.query("update stock_movements set reason='adjustment' where id=$1",[s.inbound]);await expect(link(p)).rejects.toThrow('finance_stock_acquisition_changed');});
it('guards OLD tenant and catalog identity, then permits correction after reversal',async()=>{const s=await seed(),r=await link(await payload(s));await db.exec('savepoint guard');await expect(db.query('update stock_movements set tenant_id=$1 where id=$2',[i.otherTenant,s.inbound])).rejects.toThrow('source_protected');await db.exec('rollback to savepoint guard');await expect(db.query("update stock_items set unit='kg' where id=$1",[s.item])).rejects.toThrow('source_protected');await db.exec('rollback to savepoint guard');await reverse(s,r.link_id);await db.query("update stock_movements set quantity=11 where id=$1",[s.inbound]);expect((await db.query("select source_snapshot->'inbound'->>'quantity' q from finance_stock_acquisition_links")).rows[0]).toEqual({q:'10'});});
it('shared claim prevents direct or labor reuse and releases only association',async()=>{const s=await seed(),r=await link(await payload(s));expect((await db.query("select source_kind from finance_maintenance_cost_claims")).rows[0]).toEqual({source_kind:'stock_acquisition'});await db.exec('savepoint claim');await expect(db.query("insert into finance_maintenance_cost_claims values($1,$2,'labor',$3,$4)",[i.tenant,s.cost,randomUUID(),randomUUID()])).rejects.toThrow('duplicate key');await db.exec('rollback to savepoint claim');await reverse(s,r.link_id);expect((await db.query('select count(*)::int n from finance_maintenance_cost_claims')).rows[0]).toEqual({n:0});});
it('blocks reversal with explicit consumption dependency and limits its capacity',async()=>{const s=await seed(),r=await link(await payload(s));await db.query("insert into finance_stock_acquisition_dependencies values($1,$2,'consumption',$3,2,1000)",[i.tenant,r.link_id,randomUUID()]);await expect(reverse(s,r.link_id)).rejects.toThrow('has_dependents');await db.exec('savepoint capacity');await expect(db.query("insert into finance_stock_acquisition_dependencies values($1,$2,'consumption',$3,9,4500)",[i.tenant,r.link_id,randomUUID()])).rejects.toThrow('capacity_exceeded');await db.exec('rollback to savepoint capacity');});
it('keeps invalid values and nonpurchase movements in explicit review',async()=>{const s=await seed();await db.query("update stock_movements set total_cost='NaN' where id=$1",[s.inbound]);await expect(link(await payload(s))).rejects.toThrow('invalid_value');await db.query("update stock_movements set total_cost=50,movement_type='consumption' where id=$1",[s.inbound]);await expect(link(await payload(s))).rejects.toThrow('not_purchase');});
it('real labor commands share the acquisition claim in both orders',async()=>{const s=await seed(),order=randomUUID();await db.query("insert into maintenance_orders(id,tenant_id,order_number,status,opened_at,labor_cost) values($1,$2,'OS shared','completed','2026-01-01',50)",[order,i.tenant]);
 const labor=async()=>{const v=(await db.query<{v:string}>('select finance_private.maintenance_labor_revision($1,$2,$3) v',[i.tenant,order,s.cost])).rows[0].v;return financeAs<{v:Record<string,unknown>}>(db,i.operator,'select associate_finance_maintenance_labor($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),order_id:order,cost_id:s.cost,revision:v,reason:'Mão de obra conferida na ordem',same_labor_confirmed:true}]);};
 const r=await link(await payload(s));await expect(labor()).rejects.toThrow('already_associated');await reverse(s,r.link_id);await labor();await expect(link(await payload(s))).rejects.toThrow('already_associated');});
it('keeps office purchase category when adopting PPE inventory',async()=>{const s=await seed('office');await db.query("update stock_items set category='ppe' where id=$1",[s.item]);await link(await payload(s));expect((await db.query('select category,amount_cents::text from finance_expense_items where id=$1',[s.cost])).rows[0]).toEqual({category:'office',amount_cents:'5000'});expect((await db.query('select count(*)::int n from finance_expense_items')).rows[0]).toEqual({n:1});});
