// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createMaintenanceLaborDatabase} from './helpers/maintenanceLaborDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createMaintenanceLaborDatabase>>;
beforeAll(async()=>{db=await createMaintenanceLaborDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});
afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(){const order=randomUUID(),cost=randomUUID(),supplier=randomUUID();
 await db.query("insert into clients(id,tenant_id,company_name) values($1,$2,'Oficina cadastrada')",[supplier,i.tenant]);
 await db.query("insert into maintenance_orders(id,tenant_id,order_number,status,opened_at,labor_cost,parts_cost,total_cost,supplier_vendor) values($1,$2,'OS QA','completed','2026-01-01',50,70,120,'Texto antigo diferente')",[order,i.tenant]);
 await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:'maintenance',description:'Mão de obra externa',reason:'Registro de serviço conferido',items:[{id:cost,category:'service',amount_cents:5000,occurred_on:'2026-01-20',description:'Serviço oficina',supplier_id:supplier,supplier_name:'Oficina cadastrada',payee_type:'supplier',no_receipt_reason:'Recibo solicitado à oficina',allocations:[]}]}]);return{order,cost,supplier};}
async function payload(s:Awaited<ReturnType<typeof seed>>){const revision=(await db.query<{v:string}>('select finance_private.maintenance_labor_revision($1,$2,$3) v',[i.tenant,s.order,s.cost])).rows[0].v;return{version:1,tenant_id:i.tenant,request_id:randomUUID(),order_id:s.order,cost_id:s.cost,revision,reason:'Conferi a mão de obra e o fornecedor pelo documento',same_labor_confirmed:true};}
async function link(p:Record<string,unknown>,actor=i.operator){return(await financeAs<{v:Record<string,unknown>}>(db,actor,'select associate_finance_maintenance_labor($1) v',[p])).rows[0].v;}
async function reverse(id:unknown){return(await financeAs<{v:Record<string,unknown>}>(db,i.operator,'select reverse_finance_maintenance_labor_association($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),link_id:id,reason:'Associação incorreta após nova conferência'}])).rows[0].v;}
it('links only labor to a real canonical cost, preserves money/debt and replays exactly',async()=>{const s=await seed(),p=await payload(s),before=(await db.query('select * from payables')).rows;const r=await link(p);expect(r).toMatchObject({amount_cents:'5000',cash_created:false,obligation_created:false});expect(await link(p)).toEqual(r);expect((await db.query('select * from payables')).rows).toEqual(before);expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:0});expect((await db.query('select supplier_id,source_snapshot->\'order\'->>\'parts_cost\' parts from finance_maintenance_labor_links')).rows[0]).toEqual({supplier_id:s.supplier,parts:'70'});});
it('requires explicit declaration, rejects drivers and duplicate active association',async()=>{const s=await seed(),p=await payload(s);await expect(link({...p,same_labor_confirmed:false})).rejects.toThrow('finance_invalid_payload');await expect(link(p,i.driverUser)).rejects.toThrow('finance_access_denied');await link(p);await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_labor_already_associated');});
it('detects stale source and payable context',async()=>{const s=await seed(),p=await payload(s);await db.query("update payables set notes='Revisão adicional' where id=(select payable_id from finance_expense_items where id=$1)",[s.cost]);await expect(link(p)).rejects.toThrow('finance_maintenance_labor_changed');const q=await payload(s);await db.query('update maintenance_orders set labor_cost=51 where id=$1',[s.order]);await expect(link(q)).rejects.toThrow('finance_maintenance_labor_changed');await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_labor_source_mismatch');});
it('blocks a second obligation derived from the OS',async()=>{const s=await seed();await db.query("insert into payables(tenant_id,supplier_name,category,amount,source_table,source_id) values($1,'Fornecedor','maintenance',50,'maintenance_orders',$2)",[i.tenant,s.order]);await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_labor_obligation_conflict');});
it('keeps operational notes editable, protects active financial identity and allows audited re-review after reversal',async()=>{const s=await seed(),r=await link(await payload(s));await db.query("update maintenance_orders set notes='Observação operacional' where id=$1",[s.order]);await db.exec('savepoint guarded');await expect(db.query('update maintenance_orders set labor_cost=51 where id=$1',[s.order])).rejects.toThrow('finance_maintenance_labor_source_protected');await db.exec('rollback to savepoint guarded');expect(await reverse(r.link_id)).toMatchObject({cash_changed:false,obligation_changed:false});await db.query('update maintenance_orders set labor_cost=51 where id=$1',[s.order]);expect((await db.query("select source_snapshot->'order'->>'labor_cost' value from finance_maintenance_labor_links")).rows[0]).toEqual({value:'50'});await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_labor_source_mismatch');});
it('rejects invalid or unfinished labor without adopting the order header',async()=>{const s=await seed();await db.query("update maintenance_orders set status='in_progress' where id=$1",[s.order]);await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_labor_order_not_completed');await db.query("update maintenance_orders set status='completed',labor_cost='NaN' where id=$1",[s.order]);await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_labor_invalid_value');});
it('rejects a cancelled canonical obligation instead of presenting it as incorporated cost',async()=>{const s=await seed();await db.query("update payables set status='cancelled' where id=(select payable_id from finance_expense_items where id=$1)",[s.cost]);await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_labor_target_obligation_invalid');});
