// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
import {createClosedPeriodLateCompositionDatabase} from './helpers/closedPeriodLateCompositionDatabase';
import {financeIds as i,financeAs} from './helpers/financeLedgerDatabase';
import {legacyCutReviewSchema} from '@/lib/financial/legacyCutReviewContract';
let db:Awaited<ReturnType<typeof createClosedPeriodLateCompositionDatabase>>;
beforeAll(async()=>{db=await createClosedPeriodLateCompositionDatabase();await db.exec('alter table finance_settlement_movement_links drop constraint finance_settlement_movement_links_payment_id_key');},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where user_id=$1",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
const read=async()=>legacyCutReviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,i.account,'2026-01-01','2026-01-31'])).rows[0].v);
async function seed(){const settlement=randomUUID(),payment=randomUUID(),link=randomUUID();await db.query("insert into driver_settlements(id,tenant_id,driver_id,status,driver_payable_amount) values($1,$2,$3,'approved',5)",[settlement,i.tenant,i.driver]);await db.query("insert into driver_settlement_payments(id,tenant_id,settlement_id,amount,paid_at) values($1,$2,$3,5,'2026-01-11T01:00:00Z')",[payment,i.tenant,settlement]);const movement=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'driver_advance',driver_id:i.driver,amount_cents:500,occurred_on:'2026-01-10',description:'Saída para motorista',beneficiary_name:'Motorista QA',reason:'Pagamento do acerto conferido'}])).rows[0].v.movement_id;await db.query('insert into finance_settlement_movement_links(id,tenant_id,settlement_id,payment_id,movement_id,amount_cents,created_by) values($1,$2,$3,$4,$5,500,$6)',[link,i.tenant,settlement,payment,movement,i.operator]);return {settlement,payment,link,movement};}
async function review(){const p=await read();await financeAs(db,i.operator,'select review_finance_legacy_cut($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from:'2026-01-01',to:'2026-01-31',revision:p.revision,reason:'Conferência do acerto e da saída exata',sources_reviewed:true}]);}
it('exact active settlement mapping approves its cut without creating money or payments',async()=>{const f=await seed(),before=(await db.query('select * from finance_movements')).rows,p=await read();expect(p.manifest.classifier_version).toBe('2');expect(p.blockers).toEqual([]);expect(p.manifest.sources[0]).toMatchObject({source_id:f.payment,account_id:i.account,occurred_on:'2026-01-10',movement_ids:[f.movement],classification:'exact_canonical_mapping'});await review();expect((await read()).approved).toBe(true);expect((await db.query('select * from finance_movements')).rows).toEqual(before);expect((await db.query('select * from driver_settlement_payments')).rows).toHaveLength(1);});
it('reversal releases the association but retains a pending historical payment; fresh exact link resolves it',async()=>{const f=await seed();await review();await db.query("insert into finance_settlement_link_reversals(tenant_id,link_id,created_by,actor_name,reason) values($1,$2,$3,'Autor QA','Vínculo de acerto corrigido')",[i.tenant,f.link,i.operator]);expect((await read()).approved).toBe(false);expect((await read()).blockers).toHaveLength(1);await db.query('insert into finance_settlement_movement_links(tenant_id,settlement_id,payment_id,movement_id,amount_cents,created_by) values($1,$2,$3,$4,500,$5)',[i.tenant,f.settlement,f.payment,f.movement,i.operator]);expect((await read()).blockers).toEqual([]);await review();expect((await read()).history).toHaveLength(2);});
it.each(['driver','date','amount','parent'])('rejects mismatched settlement %s rather than hiding the account',async mismatch=>{const f=await seed();if(mismatch==='driver')await db.query('update driver_settlements set driver_id=$1 where id=$2',[randomUUID(),f.settlement]);if(mismatch==='date')await db.query("update driver_settlement_payments set paid_at='2026-01-12T12:00:00Z' where id=$1",[f.payment]);if(mismatch==='amount')await db.query('update finance_settlement_movement_links set amount_cents=499 where id=$1',[f.link]);if(mismatch==='parent')await db.query('update finance_settlement_movement_links set settlement_id=$1 where id=$2',[randomUUID(),f.link]);const p=await read();expect(p.blockers.length).toBeGreaterThan(0);expect(p.manifest.sources[0].account_id).toBeNull();});
it('shared outgoing capacity includes payable reservations',async()=>{const f=await seed();await db.query('insert into finance_payable_movement_links(tenant_id,movement_id,payable_id,payment_id,amount_cents,created_by) values($1,$2,$3,$4,1,$5)',[i.tenant,f.movement,randomUUID(),randomUUID(),i.operator]);expect((await read()).blockers.length).toBeGreaterThan(0);});
it('multiple active links cannot select one account and suppress ambiguity',async()=>{const f=await seed();await db.query('insert into finance_settlement_movement_links(tenant_id,settlement_id,payment_id,movement_id,amount_cents,created_by) values($1,$2,$3,$4,500,$5)',[i.tenant,f.settlement,f.payment,f.movement,i.operator]);const p=await read();expect(p.blockers).toHaveLength(1);expect(p.manifest.sources[0].account_id).toBeNull();});
it('driver identity must belong to the tenant even when both corrupted sides share the same ID',async()=>{await seed();await db.query('update drivers set tenant_id=$1 where id=$2',[i.otherTenant,i.driver]);expect((await read()).blockers.length).toBeGreaterThan(0);});
