import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,it,expect,vi} from 'vitest';
import Financial from '@/pages/Financial';
const mock=vi.hoisted(()=>({portfolio:vi.fn().mockResolvedValue({}),cost:vi.fn().mockResolvedValue({}),fiscal:vi.fn().mockResolvedValue({})}));
vi.mock('@/components/financial/UnbilledFreightPanel',()=>({UnbilledFreightPanel:()=> <p>Previsão com filtros próprios</p>}));
vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentTenant:{id:'tenant'}})}));vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'actor'}})}));vi.mock('react-router-dom',()=>({useNavigate:()=>vi.fn()}));vi.mock('@/hooks/useClients',()=>({useClients:()=>({data:[{id:'client',company_name:'Cliente QA',active:true}]})}));vi.mock('@/hooks/useCostCenters',()=>({useCostCenters:()=>({fullData:[{id:'center-id',name:'Centro QA',active:true}]})}));
vi.mock('@/lib/financial/receivablePortfolioClient',()=>({readReceivablePortfolio:mock.portfolio}));vi.mock('@/lib/financial/recordedCostSummaryClient',()=>({readRecordedCostSummary:mock.cost}));vi.mock('@/lib/financial/fiscalDashboardClient',()=>({readFiscalDashboard:mock.fiscal}));vi.mock('@/components/financial/ReceivablePortfolio',()=>({ReceivablePortfolioCard:()=>null,ReceivablePortfolioStatus:()=>null}));vi.mock('@/components/financial/RecordedCostSummary',()=>({RecordedCostCard:()=>null,RecordedCostSummary:()=>null}));vi.mock('@/components/financial/FiscalDashboardSummary',()=>({FiscalDashboardCard:()=>null,FiscalDashboardSummary:()=>null}));afterEach(()=>{cleanup();vi.clearAllMocks();});
it('applies the proper filters to each server summary only after explicit apply, keeping forecast filters independent',async()=>{
 render(<QueryClientProvider client={new QueryClient()}><Financial/></QueryClientProvider>);await waitFor(()=>expect(mock.portfolio).toHaveBeenCalledTimes(1));fireEvent.change(screen.getByLabelText('Data inicial'),{target:{value:'2026-01-01'}});fireEvent.change(screen.getByLabelText('Data final'),{target:{value:'2026-01-31'}});fireEvent.change(screen.getByLabelText('Cliente — carteira e fiscal'),{target:{value:'client'}});fireEvent.change(screen.getByLabelText('Tipo fiscal'),{target:{value:'nfse'}});fireEvent.change(screen.getByLabelText('Categoria dos custos registrados'),{target:{value:'payroll'}});fireEvent.change(screen.getByLabelText('Centro de custo dos registros incorporados'),{target:{value:'center-id'}});expect(mock.portfolio).toHaveBeenCalledTimes(1);await waitFor(()=>expect(screen.getByRole('button',{name:'Aplicar filtros'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Aplicar filtros'}));await waitFor(()=>expect(mock.fiscal).toHaveBeenLastCalledWith('tenant',{from:'2026-01-01',to:'2026-01-31',client:'client',docType:'nfse'}));expect(mock.cost).toHaveBeenLastCalledWith('tenant',{from:'2026-01-01',to:'2026-01-31',category:'payroll',costCenter:'center-id'});expect(mock.portfolio).toHaveBeenLastCalledWith('tenant',{from:'2026-01-01',to:'2026-01-31',client:'client'});expect(screen.getByText(/Previsão com filtros próprios/)).toBeInTheDocument();
});
