// @vitest-environment node
import {readFileSync} from 'node:fs';
import {afterEach,expect,it} from 'vitest';
import {createFinanceLedgerDatabase,financeIds} from './helpers/financeLedgerDatabase';
const opened:Array<Awaited<ReturnType<typeof createFinanceLedgerDatabase>>>=[];
const migration=readFileSync('supabase/migrations/20260910224136_finance_active_workspace_access.sql','utf8');
async function fixture(){const db=await createFinanceLedgerDatabase();opened.push(db);await db.exec(`create schema private;create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create table public.client_portal_access(user_id uuid,tenant_id uuid,active boolean);`);const source=readFileSync('supabase/migrations/20260910131125_active_tenant_auth_context.sql','utf8');for(const name of ['user_can_access_tenant','request_tenant_id','is_request_tenant_member']){const start=source.indexOf('create or replace function private.'+name+'(');const end=source.indexOf('$function$;',start)+'$function$;'.length;await db.exec(source.slice(start,end));}await db.exec(readFileSync('supabase/migrations/20260910140823_require_matching_active_tenant_claim.sql','utf8'));await db.query("select set_config('request.jwt.claim.sub',$1,false)",[financeIds.operator]);return db;}
async function allowed(db:Awaited<ReturnType<typeof fixture>>,claim:string|null,header:string|null=claim,tenant=financeIds.tenant){await db.query("select set_config('request.jwt.claims',$1,false),set_config('request.headers',$2,false)",[JSON.stringify({role:'authenticated',...(claim?{active_tenant_id:claim}:{})}),JSON.stringify(header?{'x-agvlog-tenant-id':header}:{})]);await db.exec('set role authenticated');try{return (await db.query<{allowed:boolean}>('select finance_private.can_access($1) allowed',[tenant])).rows[0].allowed;}catch(error){expect(error).toMatchObject({code:expect.stringMatching(/^(42501|22023)$/)});return false;}finally{await db.exec('reset role');}}
afterEach(async()=>{for(const db of opened.splice(0))await db.close();});
it('requires a matching signed workspace even when the actor belongs to both tenants',async()=>{const db=await fixture();await db.query("insert into tenant_memberships values($1,$2,'admin',true)",[financeIds.otherTenant,financeIds.operator]);await db.exec(migration);expect(await allowed(db,null,financeIds.tenant)).toBe(false);expect(await allowed(db,financeIds.tenant,financeIds.otherTenant)).toBe(false);expect(await allowed(db,financeIds.otherTenant,financeIds.otherTenant,financeIds.tenant)).toBe(false);expect(await allowed(db,financeIds.tenant)).toBe(true);expect(await allowed(db,financeIds.otherTenant,financeIds.otherTenant,financeIds.otherTenant)).toBe(true);});
it('denies inactive, driver and mixed identities with a valid workspace',async()=>{const db=await fixture();await db.exec(migration);await db.query("update tenant_memberships set active=false where user_id=$1",[financeIds.operator]);expect(await allowed(db,financeIds.tenant)).toBe(false);await db.query("update tenant_memberships set active=true where user_id=$1",[financeIds.operator]);await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[financeIds.tenant,financeIds.operator]);expect(await allowed(db,financeIds.tenant)).toBe(false);await db.query("delete from tenant_memberships where user_id=$1 and role='driver'",[financeIds.operator]);await db.query('update drivers set user_id=$1 where id=$2',[financeIds.operator,financeIds.driver]);expect(await allowed(db,financeIds.tenant)).toBe(false);});
it('never activates an existing staged false gate and preserves its ACL',async()=>{const db=await fixture();await db.exec("create or replace function finance_private.can_access(_tenant uuid) returns boolean language sql stable security definer set search_path='' as $$select false;$$;");const before=await db.query("select prosrc,proacl::text from pg_proc where oid='finance_private.can_access(uuid)'::regprocedure");await db.exec(migration);expect((await db.query("select prosrc,proacl::text from pg_proc where oid='finance_private.can_access(uuid)'::regprocedure")).rows).toEqual(before.rows);expect(await allowed(db,financeIds.tenant)).toBe(false);});
it('rejects an unknown preexisting access definition',async()=>{const db=await fixture();await db.exec("create or replace function finance_private.can_access(_tenant uuid) returns boolean language sql stable security definer set search_path='' as $$select true;$$;");await expect(db.exec(migration)).rejects.toThrow('finance_access_contract_changed');});
