// @vitest-environment node
import {it,expect} from 'vitest';import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {createReceivableFinancialDatabase} from './helpers/receivableFinancialDatabase';import {installFinanceFiscalInvoiceLifecycleFixture} from './helpers/financeFiscalInvoiceLifecycleFixture';import {operationIds as i,operationRpc} from './helpers/operationOutcomeDatabase';
it('captures only existing eligible fiscal facts, idempotently, preserving sources and existing titles',async()=>{
const {db}=await createReceivableFinancialDatabase(true,false);const emissionIds:string[]=[];let existingTitle='';
try{await db.exec('create table auth.users(id uuid primary key)');await db.exec(readFileSync('supabase/migrations/20260909212104_finance_ledger_foundation.sql','utf8'));
const exec=db.exec.bind(db);db.exec=(async(...args:Parameters<typeof db.exec>)=>{
if(args[0].includes('create table public.finance_fiscal_observations')){
 const payer=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Pagador QA',true)",[payer,i.tenant]);
 for(let n=0;n<6;n++){const cte=randomUUID(),emission=randomUUID();emissionIds.push(emission);await db.query('insert into cte_documents(id,tenant_id,client_id,freight_value,net_value) values($1,$2,$3,100,100)',[cte,i.tenant,payer]);await db.query("insert into hub_fiscal_emissions(id,tenant_id,doc_type,environment,status,dispatch_state,cte_document_id,access_key,authorization_protocol,number) values($1,$2,'cte',$3,$4,$5,$6,$7,$8,'123')",[emission,i.tenant,n===5?'homologation':'production',n===2?'rejected':'authorized',n===4?'legacy':'recorded',cte,String(n+1).repeat(44),n===1?null:'2'.repeat(15)]);if(n===3){existingTitle=randomUUID();await db.query("insert into receivables(id,tenant_id,client_id,cte_document_id,description,amount,status,received_amount) values($1,$2,$3,$4,'Título preexistente',100,'pending',0)",[existingTitle,i.tenant,payer,cte]);}}
}return exec(...args);}) as typeof db.exec;
await installFinanceFiscalInvoiceLifecycleFixture(db);db.exec=exec;
const before=(await db.query('select to_jsonb(e) v from hub_fiscal_emissions e order by id')).rows;expect((await db.query('select * from finance_fiscal_observations')).rows).toHaveLength(0);
const capture=readFileSync('supabase/rollouts/20260911040114_finance_existing_fiscal_observation_capture.sql','utf8');await db.exec('begin');await db.exec(capture);const observed=(await db.query('select * from finance_fiscal_observations order by observed_order')).rows;expect(observed).toHaveLength(4);await db.exec(capture);expect((await db.query('select * from finance_fiscal_observations order by observed_order')).rows).toEqual(observed);expect((await db.query('select * from receivables')).rows).toHaveLength(1);expect((await db.query('select to_jsonb(e) v from hub_fiscal_emissions e order by id')).rows).toEqual(before);
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);const results=[];for(const emission of emissionIds.slice(0,4)){const id=(await db.query<{id:string}>('select id from finance_fiscal_observations where emission_id=$1',[emission])).rows[0].id;results.push((await operationRpc<{v:{status:string;issue:string|null;receivable_id:string|null}}>(db,'select process_finance_fiscal_observation($1,$2) v',[i.tenant,id])).rows[0].v);}
expect(results[0].status).toBe('applied');expect(results[1].status).toBe('review');expect(results[3].issue).toBe('existing_receivable_requires_adoption');expect((await db.query('select * from receivables')).rows).toHaveLength(2);expect((await db.query('select * from receivables where id=$1',[existingTitle])).rows).toHaveLength(1);expect((await db.query('select * from bank_transactions')).rows).toHaveLength(0);expect((await db.query('select to_jsonb(e) v from hub_fiscal_emissions e order by id')).rows).toEqual(before);await db.exec('rollback');
}finally{await db.close();}
},60000);
