// @vitest-environment node
import {randomUUID,createHash} from 'node:crypto';
import {writeFileSync} from 'node:fs';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createVoidAwareMonetaryProofDatabase} from './helpers/voidAwareMonetaryProofDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {legacyCutReviewSchema} from '@/lib/financial/legacyCutReviewContract';
let db:Awaited<ReturnType<typeof createVoidAwareMonetaryProofDatabase>>;
beforeAll(async()=>{db=await createVoidAwareMonetaryProofDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(){const advance=randomUUID(),employee=randomUUID(),payable=randomUUID();await db.query("insert into employees(id,tenant_id,name) values($1,$2,'Funcionário conferido')",[employee,i.tenant]);await db.query("insert into employee_advances(id,tenant_id,employee_id,amount,advance_date,status,payable_id) values($1,$2,$3,50,'2026-08-01','paid',$4)",[advance,i.tenant,employee,payable]);await db.query("insert into payables(id,tenant_id,supplier_name,category,amount,status,source_table,source_id) values($1,$2,'Funcionário','payroll',50,'approved','employee_advances',$3)",[payable,i.tenant,advance]);return{advance,payable,employee};}
async function pay(s:Awaited<ReturnType<typeof seed>>,cents:number,day='2026-08-15',account=i.account){const movement=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,'out','payment',$4,$5,'Adiantamento','Funcionário',$6)",[movement,i.tenant,account,cents,day,i.operator]);await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:movement,payable_id:s.payable,amount_cents:cents,method:'pix',reason:'Adiantamento conferido com pagamento'}]);return movement;}

async function seedVoid(movement:string){const original=randomUUID(),request=randomUUID();await db.query("insert into finance_commands(tenant_id,request_id,actor_id,action,payload,result) values($1,$2,$3,'qa_historical_origin','{}','{}'),($1,$4,$3,'qa_historical_void','{}','{}')",[i.tenant,original,i.operator,request]);await db.query("insert into finance_movement_voids(tenant_id,movement_id,original_request_id,request_id,kind,actor_id,actor_name,reason,revision,source_snapshot) values($1,$2,$3,$4,'void',$5,'QA','Historically inconsistent linked void fixture',md5('fixture'),jsonb_build_object('movement_id',$2::uuid::text))",[i.tenant,movement,original,request,i.operator]);}
async function proof(id:string){return(await db.query<{v:Record<string,unknown>}>("select finance_private.paid_projection_chain($1,'employee_advances',$2) v",[i.tenant,id])).rows[0].v;}
async function cut(){return legacyCutReviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,"select get_finance_legacy_cut_review($1,$2,'2026-08-01','2026-08-31') v",[i.tenant,i.account])).rows[0].v);}
it('compiles all five effective monetary proof consumers',async()=>{expect((await db.query("select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='finance_private' and p.proname=any($1)",[['legacy_integrity_rows','legacy_cut_manifest','paid_projection_chain','legacy_cut_settlement_evidence','payable_portfolio_evidence']])).rows[0]).toEqual({n:5});});
it('invalidates paid advance proof, preserves footprints and payment, and exposes the source issue in the real review',async()=>{const s=await seed(),movement=await pay(s,5000);await db.exec('set constraints all immediate;set constraints all deferred');const before=await proof(s.advance),review=await cut(),payments=(await db.query('select * from payables_payments')).rows;expect(before.valid).toBe(true);await seedVoid(movement);const after=await proof(s.advance);expect(after).toMatchObject({valid:false,issue:'paid_projection_movement_voided',footprints:before.footprints});expect(after.revision).not.toBe(before.revision);expect((await db.query('select * from payables_payments')).rows).toEqual(payments);const changed=await cut();expect(changed.revision).not.toBe(review.revision);expect(changed.blockers.length).toBeGreaterThan(0);expect((await db.query<{issues:string[]}>('select issues from finance_private.legacy_integrity_rows($1) where source_id=$2',[i.tenant,s.advance])).rows[0].issues).toContain('source_movement_voided');});
it('keeps paid obligation IDs and invalidates totals rather than reopening debt',async()=>{const s=await seed(),movement=await pay(s,5000);await db.exec('set constraints all immediate;set constraints all deferred');const read=async()=>(await db.query<{v:Record<string,unknown>}>('select finance_private.payable_portfolio_evidence($1,$2) v',[i.tenant,s.payable])).rows[0].v;const before=await read(),title=(await db.query('select status,paid_amount from payables where id=$1',[s.payable])).rows[0];expect(before,JSON.stringify(before)).toMatchObject({valid:true});await seedVoid(movement);const after=await read();expect(after).toMatchObject({valid:false,issues:expect.arrayContaining(['payment_movement_voided']),payment_ids:before.payment_ids,nominal_cents:null,paid_cents:null,open_cents:null});expect((await db.query('select status,paid_amount from payables where id=$1',[s.payable])).rows[0]).toEqual(title);});
it('changes cut revision without blocking a free corrected movement',async()=>{const movement=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,'out','payment',5000,'2026-08-15','Manual','Fornecedor',$4)",[movement,i.tenant,i.account,i.operator]);const before=await cut();expect(before.blockers).toEqual([]);await seedVoid(movement);const after=await cut();expect(after.revision).not.toBe(before.revision);expect(after.blockers).toEqual([]);});

async function approve(){const p=await cut();await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await financeAs(db,i.operator,'select review_finance_legacy_cut($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from:'2026-08-01',to:'2026-08-31',revision:p.revision,reason:'Conferência das origens históricas e correções',sources_reviewed:true}]);}
it('invalidates an approved cut on a free void then permits a new explicit review',async()=>{const movement=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,'out','payment',5000,'2026-08-15','Manual','Fornecedor',$4)",[movement,i.tenant,i.account,i.operator]);await approve();expect((await cut()).current).toBe(true);await seedVoid(movement);expect((await cut()).current).toBe(false);await approve();expect(await cut()).toMatchObject({current:true,approved:true,history:expect.any(Array)});expect((await cut()).history).toHaveLength(2);});
it('retains exact settlement money IDs while rejecting the void payment proof',async()=>{const settlement=randomUUID(),payment=randomUUID(),movement=randomUUID();await db.query("insert into driver_settlements(id,tenant_id,driver_id,status,driver_payable_amount) values($1,$2,$3,'approved',50)",[settlement,i.tenant,i.driver]);await db.query("insert into driver_settlement_payments(id,tenant_id,settlement_id,amount,paid_at) values($1,$2,$3,50,'2026-08-15T15:00:00Z')",[payment,i.tenant,settlement]);await db.query("insert into finance_movements(id,tenant_id,bank_account_id,driver_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,$4,'out','driver_advance',5000,'2026-08-15','Acerto','Motorista',$5)",[movement,i.tenant,i.account,i.driver,i.operator]);await db.query('insert into finance_settlement_movement_links(tenant_id,settlement_id,payment_id,movement_id,amount_cents,created_by) values($1,$2,$3,$4,5000,$5)',[i.tenant,settlement,payment,movement,i.operator]);const read=async()=>(await db.query<{v:Record<string,unknown>}>('select finance_private.legacy_cut_settlement_evidence($1,$2) v',[i.tenant,payment])).rows[0].v;const before=await read();expect(before.valid).toBe(true);await seedVoid(movement);expect(await read()).toMatchObject({valid:false,issue:'settlement_movement_voided',account_id:i.account,movement_ids:[movement]});const review=await cut();expect(review.blockers.length).toBeGreaterThan(0);expect((await db.query('select count(*)::int n from driver_settlement_payments')).rows[0]).toEqual({n:1});});

it('propagates void evidence through an undated payroll already_paid source without altering its amount',async()=>{const s=await seed(),movement=await pay(s,5000),period=randomUUID(),entry=randomUUID(),item=randomUUID();await db.query("insert into payroll_periods(id,tenant_id,period_name,period_start,period_end,status) values($1,$2,'Agosto','2026-08-01','2026-08-31','draft')",[period,i.tenant]);await db.query("insert into payroll_entries(id,tenant_id,payroll_period_id,employee_id,entry_type,status) values($1,$2,$3,$4,'employee','draft')",[entry,i.tenant,period,s.employee]);await db.query("insert into payroll_entry_items(id,tenant_id,payroll_period_id,payroll_entry_id,employee_id,item_type,nature,description,amount,source_table,source_id) values($1,$2,$3,$4,$5,'advance','already_paid','Adiantamento já recebido',50,'employee_advances',$6)",[item,i.tenant,period,entry,s.employee,s.advance]);await db.exec('set constraints all immediate;set constraints all deferred');const read=async()=>(await db.query<{v:Record<string,unknown>}>("select finance_private.paid_projection_chain($1,'payroll_entry_items',$2) v",[i.tenant,item])).rows[0].v;const before=await read();expect(before.valid).toBe(true);await seedVoid(movement);const after=await read();expect(after.valid).toBe(false);expect(after.revision).not.toBe(before.revision);expect((await db.query<{v:unknown[]}>('select finance_private.source_movement_void_evidence($1,$2,$3) v',[i.tenant,'payroll_entry_items',item])).rows[0].v).toHaveLength(1);expect((await db.query('select amount::text amount,nature from payroll_entry_items where id=$1',[item])).rows[0]).toMatchObject({nature:'already_paid'});expect((await cut()).blockers.length).toBeGreaterThan(0);});

it('exports effective installed proof definitions and hashes for integration review',async()=>{const rows=(await db.query<{signature:string;definition:string}>("select p.oid::regprocedure::text signature,pg_get_functiondef(p.oid) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='finance_private' and p.proname=any($1) order by p.proname",[['legacy_integrity_rows','legacy_cut_manifest','paid_projection_chain','legacy_cut_settlement_evidence','payable_portfolio_evidence','source_movement_void_evidence']])).rows;expect(rows).toHaveLength(6);writeFileSync('docs/qa/finance-void-aware-monetary-proofs-effective-2026-09-10.json',JSON.stringify({fixture:'createVoidAwareMonetaryProofDatabase',definitions:rows.map(r=>({...r,sha256:createHash('sha256').update(r.definition).digest('hex')}))},null,2)+'\n');});
