// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createCashPeriodCloseDatabase} from './helpers/cashPeriodCloseDatabase';
import {financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createCashPeriodCloseDatabase>>;
beforeAll(async()=>{db=await createCashPeriodCloseDatabase();await db.exec(readFileSync('supabase/migrations/20260910175310_finance_cash_account_identity_scope.sql','utf8'));},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function historicalClose(cash:boolean){const opening=randomUUID(),request=randomUUID();await db.query("update bank_accounts set account_type=$1,bank_code='001',branch_number='1234',account_number='123-4' where id=$2",[cash?'cash':'checking',i.account]);await db.query("insert into finance_account_openings(id,tenant_id,bank_account_id,effective_from,balance_cents,evidence_to,evidence,actor_id,actor_name,reason) values($1,$2,$3,'2026-01-01',0,'2026-01-31','{}',$4,'QA','Historical identity guard fixture')",[opening,i.tenant,i.account,i.operator]);await db.query("insert into finance_private.account_close_write_tickets values(txid_current(),$1,$2,$3,'finance_account_period_closures')",[i.tenant,request,i.operator]);await db.query("insert into finance_account_period_closures(tenant_id,account_id,period_start,period_end,opening_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,'2026-01-01','2026-01-31',$3,'{}',$4,$5,'QA','Historical identity guard fixture',$6)",[i.tenant,i.account,opening,'a'.repeat(32),i.operator,request]);}
it('allows a separate cash account after a cash closure even with identical legacy bank fields',async()=>{await historicalClose(true);await db.query("insert into bank_accounts(id,tenant_id,name,account_type,active,bank_code,branch_number,account_number) values($1,$2,'Outro caixa','cash',true,'001','1234','123-4')",[randomUUID(),i.tenant]);});
it('allows cash after a closed bank while preserving duplicate bank rejection',async()=>{await historicalClose(false);await db.query("insert into bank_accounts(id,tenant_id,name,account_type,active,bank_code,branch_number,account_number) values($1,$2,'Caixa','cash',true,'001','1234','123-4')",[randomUUID(),i.tenant]);await expect(db.query("insert into bank_accounts(id,tenant_id,name,account_type,active,bank_code,branch_number,account_number) values($1,$2,'Banco duplicado','checking',true,'001','1234','123-4')",[randomUUID(),i.tenant])).rejects.toThrow('finance_closed_account_identity_conflict');});
it('still protects the identity and deletion of the actual closed cash account',async()=>{await historicalClose(true);await db.exec('savepoint own_identity');await expect(db.query("update bank_accounts set account_type='checking' where id=$1",[i.account])).rejects.toThrow('finance_account_period_closed');await db.exec('rollback to savepoint own_identity');await expect(db.query('delete from bank_accounts where id=$1',[i.account])).rejects.toThrow('finance_account_period_closed');});
