// @vitest-environment node
import {randomUUID} from 'node:crypto';import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createMovementCorrectionContextDatabase} from './helpers/movementCorrectionContextDatabase';import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createMovementCorrectionContextDatabase>>;beforeAll(async()=>{db=await createMovementCorrectionContextDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function movement(){return(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:5000,occurred_on:'2026-08-15',description:'Saída manual registrada',beneficiary_name:'Fornecedor QA',reason:'Registro manual para conferência'}])).rows[0].v.movement_id;}
async function read(id:string){return(await db.query<{v:{eligible:boolean;readiness:unknown;blockers:Array<{code:string}>;revision:string;effects:unknown;dependencies:Record<string,unknown[]>}}>('select finance_private.movement_correction_context($1,$2) v',[i.tenant,id])).rows[0].v;}
it('identifies a real free manual recording and prospective outgoing deltas without writing money',async()=>{const id=await movement(),before=(await db.query('select * from finance_movements')).rows,r=await read(id);expect(r,JSON.stringify(r)).toMatchObject({eligible:true,effects:{computation:'prospective_invalidation',bank_money_transacted:false,inflow_delta_cents:'0',outflow_delta_cents:'-5000',balance_delta_cents:'5000'}});expect((await db.query('select * from finance_movements')).rows).toEqual(before);});

it('keeps a real payable payment and its full historical link graph as blockers',async()=>{const id=await movement(),payable=randomUUID();await db.query("insert into payables(id,tenant_id,supplier_name,category,amount,status) values($1,$2,'Fornecedor','other',50,'approved')",[payable,i.tenant]);await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:id,payable_id:payable,amount_cents:5000,method:'pix',reason:'Pagamento conferido antes da correção'}]);await db.exec('set constraints all immediate;set constraints all deferred');const r=await read(id);expect(r.blockers).toContainEqual(expect.objectContaining({code:'payable_payment_history'}));expect(r.dependencies.payables_payments).toHaveLength(1);expect(r.dependencies.payables).toHaveLength(1);expect(r.eligible).toBe(false);});
it('retains reconciliation history after its real reversal row',async()=>{const id=await movement(),group=randomUUID();await db.query("insert into finance_reconciliation_groups(id,tenant_id,bank_account_id,direction,amount_cents,movement_ids,bank_entry_ids,method,actor_id,actor_name,reason,account_evidence,evidence_snapshot) values($1,$2,$3,'out',5000,array[$4::uuid],array[$5::uuid],'manual',$6,'QA','Grupo histórico de conciliação','Conta conferida no histórico','{}')",[group,i.tenant,i.account,id,randomUUID(),i.operator]);await db.query("insert into finance_reconciliation_reversals(tenant_id,group_id,actor_id,actor_name,reason) values($1,$2,$3,'QA','Reversão da correspondência histórica')",[i.tenant,group,i.operator]);const r=await read(id);expect(r.eligible).toBe(false);expect(r.blockers).toContainEqual(expect.objectContaining({code:'reconciliation_history'}));expect(r.dependencies.finance_reconciliation_reversals).toHaveLength(1);});
it('detects disabled guards and same-name permissive replacement implementations',async()=>{const id=await movement();await db.exec('alter table finance_expense_allocations disable trigger a_finance_active_movement_reference');expect((await read(id)).blockers).toContainEqual(expect.objectContaining({code:'movement_correction_runtime_not_ready'}));await db.exec('alter table finance_expense_allocations enable trigger a_finance_active_movement_reference');expect((await read(id)).eligible).toBe(true);await db.exec("create or replace function finance_private.guard_active_financial_movement_reference() returns trigger language plpgsql security definer set search_path='' as $$begin return new;end$$");expect((await read(id)).blockers).toContainEqual(expect.objectContaining({code:'movement_correction_runtime_not_ready'}));});
it('rejects unknown origin, foreign identity and mixed driver without exposing another tenant',async()=>{const id=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,'out','payment',5000,'2026-08-15','Manual legado','Fornecedor',$4)",[id,i.tenant,i.account,i.operator]);expect((await read(id)).blockers).toContainEqual(expect.objectContaining({code:'manual_origin_unverified'}));await db.exec('savepoint missing');await expect(read(randomUUID())).rejects.toThrow('finance_movement_not_found');await db.exec('rollback to savepoint missing');await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(read(id)).rejects.toThrow('finance_access_denied');});
async function freeze(movement:string){const opening=randomUUID(),closure=randomUUID(),request=randomUUID();await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await db.query("insert into finance_account_openings(id,tenant_id,bank_account_id,effective_from,balance_cents,evidence_to,evidence,actor_id,actor_name,reason) values($1,$2,$3,'2026-08-01',10000,'2026-08-31','{}',$4,'QA','Abertura histórica fixture')",[opening,i.tenant,i.account,i.operator]);await db.query("insert into finance_private.account_close_write_tickets values(txid_current(),$1,$2,$3,'finance_account_period_closures')",[i.tenant,request,i.operator]);await db.query("insert into finance_account_period_closures(id,tenant_id,account_id,period_start,period_end,opening_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,$3,'2026-08-01','2026-08-31',$4,'{}',$5,$6,'QA','Fechamento histórico fixture',$7)",[closure,i.tenant,i.account,opening,'a'.repeat(32),i.operator,request]);await db.query("insert into finance_account_period_dependencies values($1,$2,'finance_movements',$3,'revision',$4,'2026-08-01','2026-08-31','money')",[i.tenant,closure,movement,i.account]);return closure;}

it('blocks active closed money, then permits preview after actual reopening while preserving history',async()=>{const id=await movement();await db.exec('set constraints all immediate;set constraints all deferred');const closure=await freeze(id),closed=await read(id);expect(closed.blockers).toContainEqual(expect.objectContaining({code:'finance_account_period_closed'}));await financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:closure,revision:'a'.repeat(32),reason:'Reabertura para revisar registro financeiro'}]);const reopened=await read(id);expect(reopened,JSON.stringify(reopened)).toMatchObject({eligible:true});expect(reopened.revision).not.toBe(closed.revision);expect(reopened.dependencies.finance_account_period_closures).toHaveLength(1);expect(reopened.dependencies.finance_account_period_reopenings).toHaveLength(1);});

it('blocks exact polymorphic obligations and normalizes UUID references in other commands',async()=>{const id=await movement(),before=await read(id);await db.query("insert into payables(tenant_id,supplier_name,category,amount,status,source_table,source_id) values($1,'Fornecedor','other',50,'approved','finance_movements',$2)",[i.tenant,id]);const linked=await read(id);expect(linked.blockers).toContainEqual(expect.objectContaining({code:'payable_obligation_history'}));expect(linked.revision).not.toBe(before.revision);await db.query("insert into finance_commands(tenant_id,request_id,actor_id,action,payload,result) values($1,$2,$3,'historical_dependency',jsonb_build_object('movement_id',$4::text),'{}')",[i.tenant,randomUUID(),i.operator,'{'+id.toUpperCase()+'}']);expect((await read(id)).blockers).toContainEqual(expect.objectContaining({code:'other_command_reference'}));});
it('blocks transfer legs even if a contradictory manual origin exists',async()=>{const id=await movement(),other=await movement();await db.query('insert into finance_internal_transfers(tenant_id,outgoing_id,incoming_id,created_by) values($1,$2,$3,$4)',[i.tenant,id,other,i.operator]);expect((await read(id)).blockers).toContainEqual(expect.objectContaining({code:'transfer_history'}));});
it('detects candidate reader and active-view option drift',async()=>{const id=await movement();await db.exec('savepoint reader_change');const body=(await db.query<{v:string}>("select pg_get_functiondef('finance_private.manual_expense_movements(uuid,text,integer)'::regprocedure) v")).rows[0].v;await db.exec(body.replace('from finance_private.active_movements','from public.finance_movements'));expect((await read(id)).blockers).toContainEqual(expect.objectContaining({code:'movement_correction_runtime_not_ready'}));await db.exec('rollback to savepoint reader_change');await db.exec('alter view finance_private.active_movements reset(security_invoker)');expect((await read(id)).blockers).toContainEqual(expect.objectContaining({code:'movement_correction_runtime_not_ready'}));});
