// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {it,expect} from 'vitest';
import {createLegacyReceivableAssociationDatabase} from './helpers/legacyReceivableAssociationDatabase';
import {createFinancialScenario,financialCommand,financialPayload,financialContext} from './helpers/receivableFinancialDatabase';
import {operationIds as i,operationRpc} from './helpers/operationOutcomeDatabase';
import {legacyCutReviewSchema} from '@/lib/financial/legacyCutReviewContract';
it('real receive, allocation correction and reuse preserve one movement and an eligible legacy cut',async()=>{const db=await createLegacyReceivableAssociationDatabase();try{const baseline=readFileSync('supabase/migrations/20260824224152_baseline.sql','utf8');for(const name of ['driver_settlements','closing_reports','loads','employees','payroll_entries','payroll_periods','bank_statement_imports']){if((await db.query<{v:boolean}>('select to_regclass($1) is not null v',['public.'+name])).rows[0].v)continue;const ddl=baseline.match(new RegExp(`CREATE TABLE public\\.${name} \\([\\s\\S]*?\\n\\);`))![0];await db.exec(ddl);}await db.exec(readFileSync('supabase/migrations/20260910151011_finance_legacy_integrity_inventory.sql','utf8'));await db.exec(readFileSync('supabase/migrations/20260910163116_finance_legacy_cut_reviews.sql','utf8'));await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);const s=await createFinancialScenario(db);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);const first=await financialPayload(db,s.receivable),receipt=await financialCommand(db,first),movement=(await db.query<{id:string}>('select id from finance_movements')).rows[0].id;const read=async()=>legacyCutReviewSchema.parse((await operationRpc<{v:unknown}>(db,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,s.bank,first.effective_date,first.effective_date])).rows[0].v);const before=await read();expect(before.blockers).toEqual([]);await operationRpc(db,'select correct_finance_receipt_allocation($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),payment_id:receipt.payment_id,expected_revision:(await financialContext(db,s.receivable)).revision,reason:'Corrigir a baixa antes de realocar a entrada'}]);await financialCommand(db,await financialPayload(db,s.receivable,{movement_id:movement}));const after=await read();expect(after.revision).not.toBe(before.revision);expect(after.manifest.evidence.finance_receipt_allocation_corrections).toHaveLength(1);expect(after.manifest.sources.some(x=>x.source_id===receipt.payment_id&&x.classification==='corrected_receipt_projection')).toBe(true);expect(after.blockers).toEqual([]);await operationRpc(db,'select review_finance_legacy_cut($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:s.bank,from:first.effective_date,to:first.effective_date,revision:after.revision,reason:'Conferência das projeções corrigidas',sources_reviewed:true}]);expect((await read()).approved).toBe(true);expect((await db.query('select * from finance_movements')).rows).toHaveLength(1);await db.exec('rollback');}finally{await db.close();}},30000);
