// @vitest-environment node
import {randomUUID} from 'node:crypto';import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createPeriodMoneyPackageDatabase} from './helpers/periodMoneyPackageDatabase';import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {periodMoneyPackageSchema} from '@/lib/financial/periodMoneyPackageContract';
let db:Awaited<ReturnType<typeof createPeriodMoneyPackageDatabase>>;beforeAll(async()=>{db=await createPeriodMoneyPackageDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await db.query("update bank_accounts set account_type='cash' where id=$1",[i.account]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function opening(cents=10000){await financeAs(db,i.operator,'select record_finance_cash_opening($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,effective_from:'2026-01-01',custodian_name:'Responsável QA',counts:[{denomination_cents:1,quantity:cents}],reason:'Contagem inicial de caixa físico'}]);}
async function money(direction:string,cents:number,day='2026-01-02'){await financeAs(db,i.operator,'select record_finance_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction,nature:'other',amount_cents:cents,occurred_on:day,description:'Movimento físico do caixa',beneficiary_name:'Responsável',reason:'Registro físico conferido'}]);}
async function count(cents:number,end='2026-01-31'){return(await financeAs<{v:{count_id:string;revision:string}}>(db,i.operator,'select record_finance_cash_period_count($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,period_end:end,counts:[{denomination_cents:1,quantity:cents}],custodian_name:'Responsável QA',reason:'Conferência física no encerramento',counted_at_boundary:'end_of_day'}])).rows[0].v;}
async function review(from='2026-01-01',to='2026-01-31'){const p=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,i.account,from,to])).rows[0].v;await financeAs(db,i.operator,'select review_finance_legacy_cut($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from,to,revision:p.revision,sources_reviewed:true,reason:'Origens monetárias conferidas integralmente'}]);}
async function preview(id:string,from='2026-01-01',to='2026-01-31'){return(await financeAs<{v:{eligible:boolean;revision:string;blockers:unknown[];balances:Record<string,string>}}>(db,i.operator,'select preview_finance_cash_period_close($1,$2,$3,$4,$5) v',[i.tenant,i.account,from,to,id])).rows[0].v;}
async function close(id:string,from='2026-01-01',to='2026-01-31'){const p=await preview(id,from,to);return(await financeAs<{v:{closure_id:string;revision:string}}>(db,i.operator,'select close_finance_cash_period($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from,to,count_id:id,revision:p.revision,reason:'Fechamento do caixa após contagem'}])).rows[0].v;}

async function read(accounts:string[]=[i.account],from='2026-01-01',to='2026-01-31'){return periodMoneyPackageSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_period_money_package($1,$2,$3,$4) v',[i.tenant,from,to,accounts])).rows[0].v);}
it('loads all accounts including inactive without inventing zero money for an empty selection',async()=>{const other=randomUUID();await db.query("insert into bank_accounts(id,tenant_id,name,account_type,active) values($1,$2,'Conta encerrada','cash',false)",[other,i.tenant]);const r=await read([]);expect(r.monetary_totals_valid).toBe(false);expect(r.account_scope.available.map(x=>x.id)).toContain(other);expect(r.totals.opening_cents).toBeNull();});
it('aggregates a real frozen cash closure and preserves a stable content revision',async()=>{await opening();await money('in',1000);await money('out',2500);const c=await count(8500);await review();await close(c.count_id);const r=await read();expect(r).toMatchObject({monetary_totals_valid:true,transfer_classification_valid:true,totals:{opening_cents:'10000',in_cents:'1000',out_cents:'2500',closing_cents:'8500'}});expect(r.accounts[0].closures[0].evidence_kind).toBe('cash_count');expect((await read()).revision).toBe(r.revision);});

async function cashClosure(account:string,total:number,from='2026-01-01',to='2026-01-31',initial:number|null=10000){const base={version:1,tenant_id:i.tenant,reason:'Conferência monetária integral do caixa físico'};if(initial!==null)await financeAs(db,i.operator,'select record_finance_cash_opening($1)',[{...base,request_id:randomUUID(),account_id:account,effective_from:from,custodian_name:'Responsável QA',counts:[{denomination_cents:1,quantity:initial}]}]);const c=(await financeAs<{v:{count_id:string}}>(db,i.operator,'select record_finance_cash_period_count($1) v',[{...base,request_id:randomUUID(),account_id:account,period_end:to,counts:[{denomination_cents:1,quantity:total}],custodian_name:'Responsável QA',counted_at_boundary:'end_of_day'}])).rows[0].v;const cut=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,account,from,to])).rows[0].v;await financeAs(db,i.operator,'select review_finance_legacy_cut($1)',[{...base,request_id:randomUUID(),account_id:account,from,to,revision:cut.revision,sources_reviewed:true}]);const p=(await financeAs<{v:{revision:string;blockers:unknown[]}}>(db,i.operator,'select preview_finance_cash_period_close($1,$2,$3,$4,$5) v',[i.tenant,account,from,to,c.count_id])).rows[0].v;expect(p.blockers).toEqual([]);return(await financeAs<{v:{closure_id:string;revision:string}}>(db,i.operator,'select close_finance_cash_period($1) v',[{...base,request_id:randomUUID(),account_id:account,from,to,count_id:c.count_id,revision:p.revision}])).rows[0].v;}
async function secondAccount(){const account=randomUUID();await db.query("insert into bank_accounts(id,tenant_id,name,account_type,active) values($1,$2,'Segundo caixa','cash',true)",[account,i.tenant]);return account;}
it('uses first opening and last closing across contiguous monthly closures',async()=>{await cashClosure(i.account,10000);await cashClosure(i.account,10000,'2026-02-01','2026-02-28',null);const r=await read([i.account],'2026-01-01','2026-02-28');expect(r).toMatchObject({monetary_totals_valid:true,totals:{opening_cents:'10000',closing_cents:'10000',in_cents:'0',out_cents:'0'}});expect(r.accounts[0].closures).toHaveLength(2);expect((await read([i.account],'2026-01-02','2026-02-28')).monetary_totals_valid).toBe(false);});
it('eliminates an internal pair once while keeping gross flows and the cash equation intact',async()=>{const other=await secondAccount();await financeAs(db,i.operator,'select record_finance_internal_transfer($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),source_account_id:i.account,destination_account_id:other,amount_cents:1000,debited_on:'2026-01-15',credited_on:'2026-01-15',reason:'Transferência física conferida entre caixas',both_recorded:true}]);await cashClosure(i.account,9000);await cashClosure(other,1000,'2026-01-01','2026-01-31',0);const r=await read([other,i.account]);expect(r).toMatchObject({monetary_totals_valid:true,transfer_classification_valid:true,totals:{opening_cents:'10000',in_cents:'1000',out_cents:'1000',closing_cents:'10000'},transfer_totals:{internal_pair_cents:'1000',in_excluding_internal_pairs_cents:'0',out_excluding_internal_pairs_cents:'0'}});expect(r.transfers).toHaveLength(1);expect((await read([i.account,other])).revision).toBe(r.revision);const partial=await read([i.account]);expect(partial.account_scope.complete).toBe(false);expect(partial.transfers[0].classification).toBe('scope_boundary_out');expect(partial.transfer_totals.internal_pair_cents).toBe('0');});
it('keeps a frozen departure in transit when its arrival is recorded after that cut',async()=>{const other=await secondAccount();const departure=(await financeAs<{v:{departure_id:string}}>(db,i.operator,'select record_finance_transfer_stage($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),stage:'depart',source_account_id:i.account,destination_account_id:other,amount_cents:1000,occurred_on:'2026-01-30',occurred:true,reason:'Saída física conferida para outro caixa'}])).rows[0].v;await cashClosure(i.account,9000);const before=await read();expect(before.transfers[0].classification).toBe('in_transit');await financeAs(db,i.operator,'select record_finance_transfer_stage($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),stage:'arrive',departure_id:departure.departure_id,occurred_on:'2026-02-02',occurred:true,reason:'Chegada física conferida no próximo corte'}]);const after=await read();expect(after.transfers).toEqual(before.transfers);expect(after.totals).toEqual(before.totals);expect(after.revision).toBe(before.revision);});
it('returns unknown for reopened or missing coverage and denies mixed driver/foreign/duplicate scope',async()=>{const c=await cashClosure(i.account,10000);await financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:c.closure_id,revision:c.revision,reason:'Reabertura para conferir os registros'}]);const r=await read();expect(r.monetary_totals_valid).toBe(false);expect(r.totals.closing_cents).toBeNull();expect(r.accounts[0].closures[0].reopening).not.toBeNull();await expect(read([randomUUID()])).rejects.toThrow('finance_account_not_found');await expect(read([i.account,i.account])).rejects.toThrow('finance_duplicate_account_selection');await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(read()).rejects.toThrow('finance_access_denied');});

// Deliberately damaged historical fixtures: application guards are restored
// immediately. This does not claim that production commands can edit a closure.
async function historicalSnapshot(closure:string,change:(s:Record<string,unknown>)=>void){const snap=(await db.query<{snapshot:Record<string,unknown>}>('select snapshot from finance_account_period_closures where id=$1',[closure])).rows[0].snapshot;change(snap);delete snap.revision;const revision=(await db.query<{v:string}>('select md5($1::jsonb::text) v',[snap])).rows[0].v;snap.revision=revision;await db.exec('alter table finance_account_period_closures disable trigger user');await db.query('update finance_account_period_closures set snapshot=$1,snapshot_revision=$2 where id=$3',[snap,revision,closure]);await db.exec('alter table finance_account_period_closures enable trigger user');}
it.each([null,{}])('keeps proven gross balances when historical transfer metadata is malformed: %j',async value=>{const c=await cashClosure(i.account,10000);await historicalSnapshot(c.closure_id,s=>{(s.facts as Record<string,unknown>).transfers=value;});const r=await read();expect(r).toMatchObject({monetary_totals_valid:true,transfer_classification_valid:false,totals:{opening_cents:'10000',closing_cents:'10000'},transfer_totals:{internal_pair_cents:null,in_excluding_internal_pairs_cents:null,out_excluding_internal_pairs_cents:null}});expect(r.issues).toContain('transfer_manifest_invalid');});
it('treats an unknown movement nature as classification uncertainty, not as non-transfer money',async()=>{await money('in',1000);const c=await cashClosure(i.account,11000);await historicalSnapshot(c.closure_id,s=>{const facts=s.facts as {movements:Array<Record<string,unknown>>};facts.movements[0].nature=null;});const r=await read();expect(r.monetary_totals_valid).toBe(true);expect(r.transfer_classification_valid).toBe(false);expect(r.issues).toContain('invalid_movement_nature');});
it('diagnoses invalid monetary source identity and date without breaking the whole response contract',async()=>{await money('in',1000);const c=await cashClosure(i.account,11000);await historicalSnapshot(c.closure_id,s=>{const facts=s.facts as {movements:Array<Record<string,unknown>>};facts.movements[0].id='invalid-id';facts.movements[0].occurred_on=null;facts.movements[0].direction=null;});const r=await read();expect(r.monetary_totals_valid).toBe(false);expect(r.totals.closing_cents).toBeNull();expect(r.accounts[0].movement_ids).toEqual([]);expect(r.accounts[0].issues).toContain('movement_manifest_invalid');});

it('returns distinct public movement IDs while preserving duplicate-source diagnostics',async()=>{await money('in',1000);const c=await cashClosure(i.account,11000);await historicalSnapshot(c.closure_id,s=>{const facts=s.facts as {movements:Array<Record<string,unknown>>};facts.movements.push({...facts.movements[0]});});const r=await read();expect(r.monetary_totals_valid).toBe(false);expect(r.accounts[0].movement_ids).toHaveLength(1);expect(r.accounts[0].issues).toContain('duplicate_movement_manifest');});
