// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createCashPeriodCloseDatabase} from './helpers/cashPeriodCloseDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {accountPeriodEvidenceSchema} from '@/lib/financial/accountPeriodEvidenceContract';
let db:Awaited<ReturnType<typeof createCashPeriodCloseDatabase>>;
beforeAll(async()=>{db=await createCashPeriodCloseDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await db.query("update bank_accounts set account_type='cash' where id=$1",[i.account]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function opening(cents=10000){await financeAs(db,i.operator,'select record_finance_cash_opening($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,effective_from:'2026-01-01',custodian_name:'Responsável QA',counts:[{denomination_cents:1,quantity:cents}],reason:'Contagem inicial de caixa físico'}]);}
async function money(direction:string,cents:number,day='2026-01-02'){await financeAs(db,i.operator,'select record_finance_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction,nature:'other',amount_cents:cents,occurred_on:day,description:'Movimento físico do caixa',beneficiary_name:'Responsável',reason:'Registro físico conferido'}]);}
async function count(cents:number,end='2026-01-31'){return(await financeAs<{v:{count_id:string;revision:string}}>(db,i.operator,'select record_finance_cash_period_count($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,period_end:end,counts:[{denomination_cents:1,quantity:cents}],custodian_name:'Responsável QA',reason:'Conferência física no encerramento',counted_at_boundary:'end_of_day'}])).rows[0].v;}
async function review(from='2026-01-01',to='2026-01-31'){const p=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,i.account,from,to])).rows[0].v;await financeAs(db,i.operator,'select review_finance_legacy_cut($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from,to,revision:p.revision,sources_reviewed:true,reason:'Origens monetárias conferidas integralmente'}]);}
async function preview(id:string,from='2026-01-01',to='2026-01-31'){return(await financeAs<{v:{eligible:boolean;revision:string;blockers:unknown[];balances:Record<string,string>}}>(db,i.operator,'select preview_finance_cash_period_close($1,$2,$3,$4,$5) v',[i.tenant,i.account,from,to,id])).rows[0].v;}
async function close(id:string,from='2026-01-01',to='2026-01-31'){const p=await preview(id,from,to);return(await financeAs<{v:{closure_id:string;revision:string}}>(db,i.operator,'select close_finance_cash_period($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from,to,count_id:id,revision:p.revision,reason:'Fechamento do caixa após contagem'}])).rows[0].v;}
it('closes real counted cash without bank evidence or additional money',async()=>{await opening();await money('in',1000);await money('out',2500);const c=await count(8500);await review();const p=await preview(c.count_id);expect(p.balances).toMatchObject({opening_cents:'10000',expected_closing_cents:'8500',counted_closing_cents:'8500',difference_cents:'0'});expect(p.blockers).toEqual([]);expect(p.eligible).toBe(true);await close(c.count_id);expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:2});expect((await db.query('select count(*)::int n from finance_bank_entries')).rows[0]).toEqual({n:0});});
async function reverseCount(c:{count_id:string;revision:string}){return financeAs(db,i.operator,'select reverse_finance_cash_period_count($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),count_id:c.count_id,revision:c.revision,reason:'Contagem anterior incorreta após conferência'}]);}
async function reopen(c:{closure_id:string;revision:string}){return financeAs(db,i.operator,'select reopen_finance_account_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),closure_id:c.closure_id,revision:c.revision,reason:'Reabertura auditada para nova conferência'}]);}
it('persists shortage and surplus without automatic money adjustment',async()=>{await opening();const shortage=await count(9500);await review();expect((await preview(shortage.count_id)).balances.difference_cents).toBe('-500');await expect(close(shortage.count_id)).rejects.toThrow('finance_period_close_blocked');await reverseCount(shortage);const surplus=await count(10500);expect((await preview(surplus.count_id)).balances.difference_cents).toBe('500');await expect(close(surplus.count_id)).rejects.toThrow('finance_period_close_blocked');expect((await db.query('select count(*)::int n from finance_cash_period_counts')).rows[0]).toEqual({n:2});expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:0});});
it('closes zero cash and protects the count and retroactive money until reopening',async()=>{await opening(0);const c=await count(0);await review();const closed=await close(c.count_id);await expect(reverseCount(c)).rejects.toThrow('finance_account_period_closed');await expect(money('in',100)).rejects.toThrow('finance_account_period_closed');const snapshot=(await db.query('select snapshot from finance_account_period_closures')).rows;await reopen(closed);await reverseCount(c);expect((await db.query('select snapshot from finance_account_period_closures')).rows).toEqual(snapshot);});
it('requires contiguous successors and blocks reopening their predecessor',async()=>{await opening();const first=await count(10000);await review();const closed=await close(first.count_id);const next=await count(10000,'2026-02-28');await review('2026-02-01','2026-02-28');expect((await preview(next.count_id,'2026-02-01','2026-02-28')).eligible).toBe(true);await close(next.count_id,'2026-02-01','2026-02-28');await expect(reopen(closed)).rejects.toThrow('finance_period_has_descendants');});
it('rejects stale preview after money changes and keeps duplicate counts explicit',async()=>{await opening();const c=await count(10000);await review();const p=await preview(c.count_id);await money('in',100);await expect(financeAs(db,i.operator,'select close_finance_cash_period($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from:'2026-01-01',to:'2026-01-31',count_id:c.count_id,revision:p.revision,reason:'Fechamento pela revisão anterior'}])).rejects.toThrow('finance_period_close_changed');await expect(count(10000)).rejects.toThrow('finance_cash_count_already_active');});
it('rejects bank account counts, unfinished day and driver access',async()=>{await db.query("update bank_accounts set account_type='checking' where id=$1",[i.account]);await expect(count(100)).rejects.toThrow('finance_cash_account_required');await db.query("update bank_accounts set account_type='cash' where id=$1",[i.account]);const today=(await db.query<{day:string}>("select to_char((clock_timestamp() at time zone 'America/Sao_Paulo')::date,'YYYY-MM-DD') as day")).rows[0].day;await expect(count(0,today)).rejects.toThrow('finance_cash_period_not_ended');await expect(financeAs(db,i.driverUser,'select preview_finance_cash_period_close($1,$2,$3,$4,$5)',[i.tenant,i.account,'2026-01-01','2026-01-31',randomUUID()])).rejects.toThrow('finance_access_denied');});
it('replays count and close exactly without second records',async()=>{await opening();const payload={version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,period_end:'2026-01-31',counts:[{denomination_cents:10000,quantity:1}],custodian_name:'Responsável QA',reason:'Contagem final conferida integralmente',counted_at_boundary:'end_of_day'};const call=()=>financeAs<{v:{count_id:string}}>(db,i.operator,'select record_finance_cash_period_count($1) v',[payload]);const c=await call();expect(await call()).toEqual(c);await review();const p=await preview(c.rows[0].v.count_id);const cmd={version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from:'2026-01-01',to:'2026-01-31',count_id:c.rows[0].v.count_id,revision:p.revision,reason:'Fechamento conferido integralmente'};const result=await financeAs(db,i.operator,'select close_finance_cash_period($1)',[cmd]);expect(await financeAs(db,i.operator,'select close_finance_cash_period($1)',[cmd])).toEqual(result);expect((await db.query('select count(*)::int n from finance_account_period_closures')).rows[0]).toEqual({n:1});});
it('exports immutable cash evidence through the real reader before and after reopening',async()=>{await opening();const c=await count(10000);await review();const closed=await close(c.count_id);const read=async()=>accountPeriodEvidenceSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_account_period_evidence($1,$2,$3) v',[i.tenant,i.account,closed.closure_id])).rows[0].v);const before=await read();expect(before.integrity).toEqual({snapshot_matches_revision:true,dependencies_match:true});expect(before.snapshot.evidence_type).toBe('cash_count_v1');await reopen(closed);const after=await read();expect(after.snapshot).toEqual(before.snapshot);expect(after.integrity).toEqual(before.integrity);});
it('includes only the cash footprint of an advance paid partly through a bank account',async()=>{await opening();const employee=randomUUID(),advance=randomUUID(),payable=randomUUID(),bank=randomUUID();await db.query("insert into bank_accounts(id,tenant_id,name,account_type,active) values($1,$2,'Banco','checking',true)",[bank,i.tenant]);await db.query("insert into employees(id,tenant_id,name) values($1,$2,'Funcionário')",[employee,i.tenant]);await db.query("insert into employee_advances(id,tenant_id,employee_id,amount,advance_date,status,payable_id) values($1,$2,$3,50,'2026-01-01','paid',$4)",[advance,i.tenant,employee,payable]);await db.query("insert into payables(id,tenant_id,supplier_name,category,amount,status,source_table,source_id) values($1,$2,'Funcionário','payroll',50,'approved','employee_advances',$3)",[payable,i.tenant,advance]);for(const [account,cents] of [[i.account,2000],[bank,3000]] as const){const movement=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:account,direction:'out',nature:'payment',amount_cents:cents,occurred_on:'2026-01-02',description:'Adiantamento do funcionário',beneficiary_name:'Funcionário',reason:'Pagamento de adiantamento conferido'}])).rows[0].v.movement_id;await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:movement,payable_id:payable,amount_cents:cents,method:'other',reason:'Parcela do adiantamento conferida'}]);}await db.exec('set constraints all immediate');const c=await count(8000);await review();expect((await preview(c.count_id)).balances.expected_closing_cents).toBe('8000');await close(c.count_id);expect((await db.query('select count(*)::int n from payables_payments')).rows[0]).toEqual({n:2});});
it('counts the real bank-to-cash transfer leg without inventing revenue or bank evidence',async()=>{await opening();const bank=randomUUID();await db.query("insert into bank_accounts(id,tenant_id,name,account_type,active) values($1,$2,'Banco','checking',true)",[bank,i.tenant]);await financeAs(db,i.operator,'select record_finance_internal_transfer($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),source_account_id:bank,destination_account_id:i.account,amount_cents:2000,debited_on:'2026-01-02',credited_on:'2026-01-03',both_recorded:true,reason:'Saque transferido para caixa físico'}]);const c=await count(12000);await review();expect((await preview(c.count_id)).balances.in_cents).toBe('2000');await close(c.count_id);expect((await db.query("select count(*)::int n from finance_movements where nature='transfer'")).rows[0]).toEqual({n:2});});
