// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createClosedPeriodLateCompositionDatabase} from './helpers/closedPeriodLateCompositionDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createClosedPeriodLateCompositionDatabase>>;
const sql=readFileSync('docs/qa/finance-paid-projection-chain-model.sql','utf8');
type Model={advance_candidates:Array<{source_id:string;necessary_money_conditions:boolean;payment_leg_count:number;title_count:number}>;already_paid_candidates:unknown[]};
beforeAll(async()=>{db=await createClosedPeriodLateCompositionDatabase();const baseline=readFileSync('supabase/migrations/20260824224152_baseline.sql','utf8');await db.exec(baseline.match(/CREATE TABLE public\.financial_obligations \([\s\S]*?\n\);/)![0]);const view=readFileSync('supabase/migrations/20260910143833_finance_legacy_payable_associations.sql','utf8').match(/create or replace view finance_private\.active_payable_payments[\s\S]*?;/)![0];await db.exec(view);},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
const model=async()=>Object.values((await db.query<Record<string,Model>>(sql,[i.tenant])).rows[0])[0];
async function seed(){const advance=randomUUID(),employee=randomUUID(),payable=randomUUID();await db.query("insert into employee_advances(id,tenant_id,employee_id,amount,advance_date,status,payable_id) values($1,$2,$3,50,'2026-08-01','paid',$4)",[advance,i.tenant,employee,payable]);await db.query("insert into payables(id,tenant_id,supplier_name,category,amount,status,source_table,source_id) values($1,$2,'Funcionário','other',50,'approved','employee_advances',$3)",[payable,i.tenant,advance]);return{advance,payable};}
it('compiles full read-only graph and EXPLAIN on real source schemas',async()=>{expect((await db.query('explain '+sql,[i.tenant])).rows.length).toBeGreaterThan(0);expect(await model()).toMatchObject({advance_candidates:[],already_paid_candidates:[]});});
it('paid status and exact title ID do not prove money',async()=>{const s=await seed();expect((await model()).advance_candidates).toEqual([expect.objectContaining({source_id:s.advance,title_count:1,payment_leg_count:0,necessary_money_conditions:false})]);});
it('real canonical payable command supplies the exact monetary leg, without inferring employee identity',async()=>{const s=await seed(),movement=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,'out','payment',5000,'2026-08-15','Adiantamento','Funcionário',$4)",[movement,i.tenant,i.account,i.operator]);await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:movement,payable_id:s.payable,amount_cents:5000,method:'pix',reason:'Pagamento de adiantamento conferido'}]);await db.exec('set constraints all immediate');expect((await model()).advance_candidates).toEqual([expect.objectContaining({source_id:s.advance,title_count:1,payment_leg_count:1,necessary_money_conditions:true,employee_identity_matches:false})]);});
