// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
import type {PGlite} from '@electric-sql/pglite';
import {createReceivableFinancialDatabase,financialCommand,financialPayload,financialContext} from './helpers/receivableFinancialDatabase';
import {operationIds as i,operationRpc} from './helpers/operationOutcomeDatabase';
import {installFinanceFiscalInvoiceLifecycleFixture} from './helpers/financeFiscalInvoiceLifecycleFixture';
let db:PGlite;
beforeAll(async()=>{({db}=await createReceivableFinancialDatabase(true,false));await db.exec('create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb)');await db.query("insert into auth.users values($1,'qa@example.test','{}')",[i.operator]);await db.exec(readFileSync('supabase/migrations/20260909212104_finance_ledger_foundation.sql','utf8'));await installFinanceFiscalInvoiceLifecycleFixture(db);},30000);
beforeEach(async()=>{await db.exec('begin');});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function source(){const payer=randomUUID(),cte=randomUUID(),emission=randomUUID();await db.query("insert into clients(id,tenant_id,company_name,active) values($1,$2,'Cliente fiscal QA',true)",[payer,i.tenant]);await db.query('insert into cte_documents(id,tenant_id,client_id,freight_value,net_value) values($1,$2,$3,100,100)',[cte,i.tenant,payer]);await db.query("insert into hub_fiscal_emissions(id,tenant_id,doc_type,environment,status,dispatch_state,cte_document_id,access_key,authorization_protocol,number) values($1,$2,'cte','production','authorized','recorded',$3,$4,$5,'123')",[emission,i.tenant,cte,'1'.repeat(44),'2'.repeat(15)]);return emission;}
async function process(emission:string){const id=(await db.query<{id:string}>('select id from finance_fiscal_observations where emission_id=$1 order by observed_order desc limit 1',[emission])).rows[0].id;return(await operationRpc<{result:{status:string;receivable_id:string;issue:string|null}}>(db,'select process_finance_fiscal_observation($1,$2) result',[i.tenant,id])).rows[0].result;}
it('cancels a paid fiscal origin with real receipt intact and shared ledger net zero',async()=>{const emission=await source(),first=await process(emission);expect(first.issue).toBeNull();expect(first.status).toBe('applied');await db.query("insert into bank_accounts(id,tenant_id,name) values('cf600000-0000-4000-8000-000000000001',$1,'Banco QA')",[i.tenant]);const payment=await financialCommand(db,await financialPayload(db,first.receivable_id));const before=(await db.query('select to_jsonb(p) p from receivables_payments p')).rows;await db.query("update hub_fiscal_emissions set status='cancelled' where id=$1",[emission]);expect(await process(emission)).toMatchObject({status:'applied'});expect(await process(emission)).toMatchObject({status:'applied'});expect((await db.query('select to_jsonb(p) p from receivables_payments p')).rows).toEqual(before);expect((await db.query('select net::text,payment_count::text,valid from _receivable_ledger_evidence($1,$2)',[i.tenant,first.receivable_id])).rows[0]).toEqual({net:'0',payment_count:'1',valid:true});expect(await financialContext(db,first.receivable_id)).toMatchObject({received_cents:0,open_cents:0,can_receive:false,requires_reconciliation:false});expect((await db.query('select payment_id from finance_customer_credits')).rows).toEqual([{payment_id:payment.payment_id}]);expect((await db.query('select count(*)::int n from bank_transactions')).rows[0]).toEqual({n:1});});
it('rejects reapplication and keeps private evidence ungranted',async()=>{await db.exec('savepoint bad');await expect(db.exec(readFileSync('supabase/rollouts/finance_fiscal_cancellation_credits_invoice_lifecycle.sql','utf8'))).rejects.toThrow();await db.exec('rollback to bad');expect((await db.query("select has_function_privilege('authenticated','public._receivable_ledger_evidence(uuid,uuid)','execute') allowed")).rows[0]).toEqual({allowed:false});});
