// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createPaidProjectionChainDatabase} from './helpers/paidProjectionChainDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {legacyCutReviewSchema} from '@/lib/financial/legacyCutReviewContract';
let db:Awaited<ReturnType<typeof createPaidProjectionChainDatabase>>;
beforeAll(async()=>{db=await createPaidProjectionChainDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(){const advance=randomUUID(),employee=randomUUID(),payable=randomUUID();await db.query("insert into employees(id,tenant_id,name) values($1,$2,'Funcionário conferido')",[employee,i.tenant]);await db.query("insert into employee_advances(id,tenant_id,employee_id,amount,advance_date,status,payable_id) values($1,$2,$3,50,'2026-08-01','paid',$4)",[advance,i.tenant,employee,payable]);await db.query("insert into payables(id,tenant_id,supplier_name,category,amount,status,source_table,source_id) values($1,$2,'Funcionário','payroll',50,'approved','employee_advances',$3)",[payable,i.tenant,advance]);return{advance,payable,employee};}
async function pay(s:Awaited<ReturnType<typeof seed>>,cents:number,day='2026-08-15',account=i.account){const movement=randomUUID();await db.query("insert into finance_movements(id,tenant_id,bank_account_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,'out','payment',$4,$5,'Adiantamento','Funcionário',$6)",[movement,i.tenant,account,cents,day,i.operator]);await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:movement,payable_id:s.payable,amount_cents:cents,method:'pix',reason:'Adiantamento conferido com pagamento'}]);return movement;}
const chain=async(id:string,table='employee_advances')=>(await db.query<{v:{valid:boolean;issue:string|null;footprints:Array<{account_id:string;occurred_on:string}>}}>('select finance_private.paid_projection_chain($1,$2,$3) v',[i.tenant,table,id])).rows[0].v;
it('does not accept a paid status without real active payments',async()=>{const s=await seed();expect(await chain(s.advance)).toMatchObject({valid:false,issue:'advance_not_fully_paid'});});
it('resolves actual payable payments across two accounts and days before cut filtering',async()=>{const s=await seed(),account=randomUUID();await db.query('insert into bank_accounts(id,tenant_id,active) values($1,$2,true)',[account,i.tenant]);await pay(s,2000);await pay(s,3000,'2026-09-01',account);await db.exec('set constraints all immediate');const result=await chain(s.advance);expect(result.valid).toBe(true);expect(result.footprints).toEqual(expect.arrayContaining([expect.objectContaining({account_id:i.account,occurred_on:'2026-08-15'}),expect.objectContaining({account_id:account,occurred_on:'2026-09-01'})]));const manifest=(await db.query<{v:{sources:Array<{source_table:string;source_id:string;classification:string;footprints:unknown[]}>}}>("select finance_private.legacy_cut_manifest($1,$2,'2026-08-01','2026-08-31') v",[i.tenant,i.account])).rows[0].v;expect(manifest.sources.find(x=>x.source_id===s.advance)).toMatchObject({classification:'exact_projection_alias',footprints:expect.any(Array)});expect(manifest.sources.find(x=>x.source_id===s.advance)?.footprints).toHaveLength(1);});
it('rejects mismatched employee identity even when money is fully linked',async()=>{const s=await seed();await pay(s,5000);await db.query('update employee_advances set driver_id=$1 where id=$2',[randomUUID(),s.advance]);expect((await chain(s.advance)).valid).toBe(false);});
async function payroll(s:Awaited<ReturnType<typeof seed>>){const period=randomUUID(),entry=randomUUID(),item=randomUUID();await db.query("insert into payroll_periods(id,tenant_id,period_name,period_start,period_end,status) values($1,$2,'Agosto','2026-08-01','2026-08-31','draft')",[period,i.tenant]);await db.query("insert into payroll_entries(id,tenant_id,payroll_period_id,employee_id,entry_type,status) values($1,$2,$3,$4,'employee','draft')",[entry,i.tenant,period,s.employee]);await db.query("insert into payroll_entry_items(id,tenant_id,payroll_period_id,payroll_entry_id,employee_id,item_type,nature,description,amount,source_table,source_id) values($1,$2,$3,$4,$5,'advance','already_paid','Adiantamento já recebido',50,'employee_advances',$6)",[item,i.tenant,period,entry,s.employee,s.advance]);return{period,entry,item};}
it('resolves undated already_paid through the exact advance and rejects duplicate coverage',async()=>{const s=await seed();await pay(s,5000);const p=await payroll(s);expect((await chain(p.item,'payroll_entry_items')).valid).toBe(true);await db.query("insert into payroll_entry_items(tenant_id,payroll_period_id,payroll_entry_id,employee_id,item_type,nature,description,amount,source_table,source_id) select tenant_id,payroll_period_id,payroll_entry_id,employee_id,item_type,nature,description,amount,source_table,source_id from payroll_entry_items where id=$1",[p.item]);expect(await chain(p.item,'payroll_entry_items')).toMatchObject({valid:false,issue:'paid_projection_duplicate_source'});});
async function freeze(movement:string){const opening=randomUUID(),closure=randomUUID(),request=randomUUID();await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await db.query("insert into finance_account_openings(id,tenant_id,bank_account_id,effective_from,balance_cents,evidence_to,evidence,actor_id,actor_name,reason) values($1,$2,$3,'2026-08-01',10000,'2026-08-31','{}',$4,'QA','Abertura histórica fixture')",[opening,i.tenant,i.account,i.operator]);await db.query("insert into finance_private.account_close_write_tickets values(txid_current(),$1,$2,$3,'finance_account_period_closures')",[i.tenant,request,i.operator]);await db.query("insert into finance_account_period_closures(id,tenant_id,account_id,period_start,period_end,opening_id,snapshot,snapshot_revision,actor_id,actor_name,reason,request_id) values($1,$2,$3,'2026-08-01','2026-08-31',$4,'{}',$5,$6,'QA','Fechamento histórico fixture',$7)",[closure,i.tenant,i.account,opening,'a'.repeat(32),i.operator,request]);await db.query("insert into finance_account_period_dependencies values($1,$2,'finance_movements',$3,'revision',$4,'2026-08-01','2026-08-31','money')",[i.tenant,closure,movement,i.account]);return closure;}
it('allows undated late payroll projection only from exact frozen money at deferred flush',async()=>{const s=await seed(),movement=await pay(s,5000);await db.exec('set constraints all immediate;set constraints all deferred');await freeze(movement);const before=(await db.query('select snapshot from finance_account_period_closures')).rows;const p=await payroll(s);await db.exec('set constraints all immediate');expect((await chain(p.item,'payroll_entry_items')).valid).toBe(true);expect((await db.query('select snapshot from finance_account_period_closures')).rows).toEqual(before);expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:1});});
it('rejects revoked permission at deferred projection validation',async()=>{const s=await seed(),movement=await pay(s,5000);await db.exec('set constraints all immediate;set constraints all deferred');await freeze(movement);await payroll(s);await db.query('update tenant_memberships set active=false where tenant_id=$1 and user_id=$2',[i.tenant,i.operator]);await expect(db.exec('set constraints all immediate')).rejects.toThrow('finance_access_denied');});
it('permits only restricted paid transition backed by the same frozen advance payments',async()=>{const s=await seed(),movement=await pay(s,5000);await db.query("update employee_advances set status='approved' where id=$1",[s.advance]);await db.exec('set constraints all immediate;set constraints all deferred');await freeze(movement);await db.query("update employee_advances set status='paid',paid_at='2026-08-15' where id=$1",[s.advance]);await db.exec('set constraints all immediate');expect((await chain(s.advance)).valid).toBe(true);});
it('fails deferred late already_paid when the advance has no proven payment',async()=>{const s=await seed(),other=await seed(),movement=await pay(other,5000);await db.exec('set constraints all immediate;set constraints all deferred');await freeze(movement);await payroll(s);await expect(db.exec('set constraints all immediate')).rejects.toThrow('finance_account_period_closed');});
it('reuses settlement mapping and rejects contradictory payroll metadata',async()=>{const s=await seed(),p=await payroll(s),settlement=randomUUID(),payment=randomUUID(),movement=randomUUID();await db.query('update employees set driver_id=$1 where id=$2',[i.driver,s.employee]);await db.query('update payroll_entries set driver_id=$1 where id=$2',[i.driver,p.entry]);await db.query("insert into driver_settlements(id,tenant_id,driver_id,status,driver_payable_amount) values($1,$2,$3,'approved',50)",[settlement,i.tenant,i.driver]);await db.query("insert into driver_settlement_payments(id,tenant_id,settlement_id,amount,paid_at) values($1,$2,$3,50,'2026-08-15T15:00:00Z')",[payment,i.tenant,settlement]);await db.query("insert into finance_movements(id,tenant_id,bank_account_id,driver_id,direction,nature,amount_cents,occurred_on,description,beneficiary_name,created_by) values($1,$2,$3,$4,'out','driver_advance',5000,'2026-08-15','Acerto','Motorista',$5)",[movement,i.tenant,i.account,i.driver,i.operator]);await db.query('insert into finance_settlement_movement_links(tenant_id,settlement_id,payment_id,movement_id,amount_cents,created_by) values($1,$2,$3,$4,5000,$5)',[i.tenant,settlement,payment,movement,i.operator]);await db.query("update payroll_entry_items set driver_id=$1,source_table='driver_settlement_payments',source_id=$2 where id=$3",[i.driver,payment,p.item]);expect((await chain(p.item,'payroll_entry_items')).valid).toBe(true);await db.query("update payroll_entry_items set source_metadata=jsonb_build_object('movement_id',$1::text) where id=$2",[randomUUID(),p.item]);expect(await chain(p.item,'payroll_entry_items')).toMatchObject({valid:false,issue:'paid_projection_metadata_mismatch'});});
it('does not bypass the original guard for an approved advance carrying a retroactive paid_at',async()=>{const s=await seed(),movement=await pay(s,5000);await db.exec('set constraints all immediate;set constraints all deferred');await freeze(movement);await expect(db.query("insert into employee_advances(tenant_id,employee_id,amount,advance_date,status,paid_at) values($1,$2,20,'2026-08-01','approved','2026-08-15')",[i.tenant,s.employee])).rejects.toThrow('finance_account_period_closed');});
it('parses real review RPC for unresolved and multicount paid projections with the current UI contract',async()=>{const s=await seed();const read=async()=>legacyCutReviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,"select get_finance_legacy_cut_review($1,$2,'2026-08-01','2026-08-31') v",[i.tenant,i.account])).rows[0].v);expect((await read()).blockers.length).toBeGreaterThan(0);const account=randomUUID();await db.query('insert into bank_accounts(id,tenant_id,active) values($1,$2,true)',[account,i.tenant]);await pay(s,2000);await pay(s,3000,'2026-09-01',account);expect((await read()).manifest.sources.find(x=>x.source_id===s.advance)?.classification).toBe('exact_projection_alias');});
