// @vitest-environment node
import {randomUUID} from 'node:crypto';import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {withLegacyReceiptSeed} from './helpers/legacyReceivableAssociationDatabase';
import {createActiveMovementFinancialDatabase} from './helpers/activeMovementFinancialDatabase';import {operationIds as i,operationRpc} from './helpers/operationOutcomeDatabase';import {createFinancialScenario,financialPayload,financialCommand} from './helpers/receivableFinancialDatabase';
let db:Awaited<ReturnType<typeof createActiveMovementFinancialDatabase>>;
beforeAll(async()=>{db=await createActiveMovementFinancialDatabase('incoming');},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function movement(bank:string,day:string){return(await operationRpc<{v:{movement_id:string}}>(db,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:bank,direction:'in',nature:'receipt',amount_cents:5000,occurred_on:day,description:'Entrada manual registrada',beneficiary_name:'Cliente QA',reason:'Registro de recebimento para conferência'}])).rows[0].v.movement_id;}
async function seedVoid(id:string){const request=randomUUID();await db.query("insert into finance_commands(tenant_id,request_id,actor_id,action,payload,result) values($1,$2,$3,'qa_void_fixture','{}','{}')",[i.tenant,request,i.operator]);await db.query("insert into finance_movement_voids(tenant_id,movement_id,original_request_id,request_id,kind,actor_id,actor_name,reason,revision,source_snapshot) select $1,$2,c.request_id,$3,'void',$4,'QA','Historical void fixture for dependency guard',md5('fixture'),jsonb_build_object('movement',to_jsonb(m)) from finance_movements m join finance_commands c on c.tenant_id=m.tenant_id and c.action='record_movement' and c.result->>'movement_id'=m.id::text where m.tenant_id=$1 and m.id=$2",[i.tenant,id,request,i.operator]);}
it('preserves the real fiscal receipt projection with an active selected movement',async()=>{const s=await createFinancialScenario(db),p=await financialPayload(db,s.receivable),id=await movement(s.bank,p.effective_date);const result=await financialCommand(db,{...p,movement_id:id});expect(result.payment_id).toBeTruthy();await db.exec('set constraints all immediate;set constraints all deferred');expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:1});expect((await db.query('select finance_private.receipt_movement_used_cents($1,$2)::text used',[i.tenant,id])).rows[0]).toEqual({used:'1000'});expect((await db.query('select finance_private.available_movement_cents($1,$2,\'in\')::text available',[i.tenant,id])).rows[0]).toEqual({available:'4000'});});
it('rejects a void reference atomically in the actual receipt and fiscal command chain',async()=>{const s=await createFinancialScenario(db),p=await financialPayload(db,s.receivable),id=await movement(s.bank,p.effective_date);await seedVoid(id);await expect(financialCommand(db,{...p,movement_id:id})).rejects.toThrow('finance_movement_voided');expect((await db.query('select count(*)::int n from receivables_payments')).rows[0]).toEqual({n:0});expect((await db.query('select count(*)::int n from bank_transactions')).rows[0]).toEqual({n:0});});
it('rejects an audited legacy receipt association to void money without changing its old receipt',async()=>{const s=await createFinancialScenario(db),p=await financialPayload(db,s.receivable),id=await movement(s.bank,p.effective_date),payment=randomUUID();await withLegacyReceiptSeed(db,()=>db.query("insert into receivables_payments(id,tenant_id,receivable_id,amount,received_at,bank_account_id,method,created_by) values($1,$2,$3,10,$4,$5,'pix',$6)",[payment,i.tenant,s.receivable,p.effective_date+'T12:00:00-03:00',s.bank,i.operator]));await seedVoid(id);const revision=(await db.query<{v:string}>('select finance_private.legacy_receivable_source_revision($1,$2) v',[i.tenant,payment])).rows[0].v;await expect(operationRpc(db,'select associate_finance_legacy_receivable_payment($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),payment_id:payment,movement_id:id,revision,existing_receipt_confirmed:true,reason:'Associação de recebimento antigo conferida'}])).rejects.toThrow('finance_movement_voided');expect((await db.query('select count(*)::int n from receivables_payments')).rows[0]).toEqual({n:1});});
it('rejects a different payment that aliases a bank transaction already linked to void money',async()=>{const s=await createFinancialScenario(db),p=await financialPayload(db,s.receivable),id=await movement(s.bank,p.effective_date);const receipt=await financialCommand(db,{...p,movement_id:id});await db.exec('set constraints all immediate;set constraints all deferred');await seedVoid(id);const title=(await db.query<{id:string}>("insert into payables(tenant_id,supplier_name,category,amount,status) values($1,'Alias indevido','other',10,'approved') returning id",[i.tenant])).rows[0].id;await db.exec('savepoint alias');await expect(db.query("insert into payables_payments(tenant_id,payable_id,amount,paid_at,bank_account_id,method,bank_transaction_id,created_by) values($1,$2,10,$3,$4,'pix',$5,$6)",[i.tenant,title,p.effective_date+'T12:00:00-03:00',s.bank,receipt.bank_transaction_id,i.operator])).rejects.toThrow('finance_movement_voided');await db.exec('rollback to savepoint alias');expect((await db.query('select count(*)::int n from receivables_payments')).rows[0]).toEqual({n:1});});
