// @vitest-environment node
import {randomUUID} from 'node:crypto';import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createActiveMovementFinancialDatabase} from './helpers/activeMovementFinancialDatabase';import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createActiveMovementFinancialDatabase>>;
beforeAll(async()=>{db=await createActiveMovementFinancialDatabase('outgoing');},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function movement(driver=false){const r=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:5000,occurred_on:'2026-01-20',description:'Saída manual registrada',beneficiary_name:'Fornecedor QA',reason:'Registro de saída para conferência',...(driver?{driver_id:i.driver}:{})}])).rows[0].v;return r.movement_id;}
async function seedVoid(id:string){const request=randomUUID();await db.query("insert into finance_commands(tenant_id,request_id,actor_id,action,payload,result) values($1,$2,$3,'qa_void_fixture','{}','{}')",[i.tenant,request,i.operator]);await db.query("insert into finance_movement_voids(tenant_id,movement_id,original_request_id,request_id,kind,actor_id,actor_name,reason,revision,source_snapshot) select $1,$2,c.request_id,$3,'void',$4,'QA','Historical void fixture for dependency guard',md5('fixture'),jsonb_build_object('movement',to_jsonb(m)) from finance_movements m join finance_commands c on c.tenant_id=m.tenant_id and c.action='record_movement' and c.result->>'movement_id'=m.id::text where m.tenant_id=$1 and m.id=$2",[i.tenant,id,request,i.operator]);}
async function payable(){return(await db.query<{id:string}>("insert into payables(tenant_id,supplier_name,category,amount,status) values($1,'Fornecedor QA','other',50,'approved') returning id",[i.tenant])).rows[0].id;}
it('rejects the real payable writer on a void movement and keeps the obligation unpaid',async()=>{const id=await movement(),title=await payable();await seedVoid(id);expect((await db.query('select finance_private.available_movement_cents($1,$2,\'out\')::text cents',[i.tenant,id])).rows[0]).toEqual({cents:'0'});await expect(financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),payable_id:title,movement_id:id,amount_cents:5000,method:'pix',reason:'Tentativa de pagamento com saída inválida'}])).rejects.toThrow('finance_movement_voided');expect((await db.query('select count(*)::int n from payables_payments')).rows[0]).toEqual({n:0});});
it('allows actual payment allocation and never reopens it merely because historical void data exists',async()=>{const id=await movement(),title=await payable();await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),payable_id:title,movement_id:id,amount_cents:5000,method:'pix',reason:'Pagamento com saída válida conferida'}]);await db.exec('set constraints all immediate;set constraints all deferred');const before=(await db.query('select * from finance_private.active_payable_payments')).rows;await seedVoid(id);expect((await db.query('select * from finance_private.active_payable_payments')).rows).toEqual(before);expect((await db.query('select finance_private.movement_used_cents($1,$2)::text cents',[i.tenant,id])).rows[0]).toEqual({cents:'5000'});expect((await db.query('select finance_private.available_movement_cents($1,$2,\'out\')::text cents',[i.tenant,id])).rows[0]).toEqual({cents:'0'});});
it('rejects a real batch expense allocation over void money without creating cost or obligation',async()=>{const id=await movement();await seedVoid(id);await expect(financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:'office',description:'Despesa com referência inválida',reason:'Conferência de gasto da sede',items:[{id:randomUUID(),category:'office',amount_cents:5000,occurred_on:'2026-01-20',description:'Compra para a sede',supplier_name:'Fornecedor QA',no_receipt_reason:'Documento solicitado ao fornecedor',allocations:[{movement_id:id,amount_cents:5000}]}]}])).rejects.toThrow('finance_movement_voided');expect((await db.query('select count(*)::int n from finance_expense_items')).rows[0]).toEqual({n:0});expect((await db.query('select count(*)::int n from payables')).rows[0]).toEqual({n:0});});
it('rejects linking an existing settlement payment to void money, preserving that old payment',async()=>{const id=await movement(true),settlement=randomUUID(),payment=randomUUID();await db.query("insert into driver_settlements(id,tenant_id,driver_id,status) values($1,$2,$3,'approved')",[settlement,i.tenant,i.driver]);await db.query("insert into driver_settlement_payments(id,tenant_id,settlement_id,amount,paid_at) values($1,$2,$3,50,'2026-01-20T12:00:00Z')",[payment,i.tenant,settlement]);await seedVoid(id);await expect(financeAs(db,i.operator,'select link_finance_settlement_payment($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),payment_id:payment,movement_id:id,reason:'Associação de pagamento de acerto conferida'}])).rejects.toThrow('finance_movement_voided');expect((await db.query('select count(*)::int n from driver_settlement_payments')).rows[0]).toEqual({n:1});});
it('checks final payment graph when a void is injected after the payment link in the same transaction',async()=>{const id=await movement(),title=await payable();await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),payable_id:title,movement_id:id,amount_cents:5000,method:'pix',reason:'Pagamento com saída válida conferida'}]);await db.exec('savepoint before_void');await seedVoid(id);await expect(db.exec('set constraints all immediate')).rejects.toThrow('finance_movement_voided');await db.exec('rollback to savepoint before_void');await db.exec('set constraints all immediate;set constraints all deferred');});
it('denies foreign movement identity and active mixed-driver access',async()=>{const id=await movement();await db.exec('savepoint bad_reference');await expect(db.query('select finance_private.assert_active_movement_reference($1,$2)',[i.tenant,randomUUID()])).rejects.toThrow('finance_movement_reference_invalid');await db.exec('rollback to savepoint bad_reference');await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(db.query('select finance_private.assert_active_movement_reference($1,$2)',[i.tenant,id])).rejects.toThrow('finance_access_denied');await db.exec('rollback to savepoint bad_reference');});
it('runs the active-reference BEFORE guards first in the actual installed trigger order',async()=>{const tables=['finance_expense_allocations','finance_payable_movement_links','finance_settlement_movement_links','finance_receivable_movement_links','finance_legacy_receipt_movement_links','payables_payments','driver_settlement_payments','receivables_payments'];const rows=(await db.query<{table_name:string;name:string;fn:string}>("select c.relname table_name,t.tgname name,p.proname fn from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_proc p on p.oid=t.tgfoid where c.relname=any($1) and not t.tgisinternal and t.tgenabled<>'D' and (t.tgtype::int & 2)=2 and (t.tgtype::int & 4)=4 order by c.relname,t.tgname collate \"C\"",[tables])).rows;for(const table of tables){const first=rows.find(r=>r.table_name===table);expect(first?.fn).toMatch(/^guard_(active_financial_movement_reference|payment_active_movement_references)$/);}});
