// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createMaintenanceDirectPartDatabase} from './helpers/maintenanceDirectPartDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createMaintenanceDirectPartDatabase>>;
beforeAll(async()=>{db=await createMaintenanceDirectPartDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});
afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function seed(){const order=randomUUID(),part=randomUUID(),cost=randomUUID(),supplier=randomUUID();
 await db.query("insert into clients(id,tenant_id,company_name) values($1,$2,'Oficina cadastrada')",[supplier,i.tenant]);
 await db.query("insert into maintenance_orders(id,tenant_id,order_number,status,opened_at,labor_cost,parts_cost,total_cost,supplier_vendor) values($1,$2,'OS QA','completed','2026-01-01',50,70,120,'Texto antigo diferente')",[order,i.tenant]);
 await db.query("insert into maintenance_parts(id,tenant_id,maintenance_order_id,item_description,quantity,unit_cost,total_cost) values($1,$2,$3,'Peça direta',2,25,50)",[part,i.tenant,order]);
 await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:'maintenance',description:'Mão de obra externa',reason:'Registro de serviço conferido',items:[{id:cost,category:'maintenance',document_number:'NF-123',amount_cents:5000,occurred_on:'2026-01-20',description:'Serviço oficina',supplier_id:supplier,supplier_name:'Oficina cadastrada',payee_type:'supplier',no_receipt_reason:'Recibo solicitado à oficina',allocations:[]}]}]);return{order,part,cost,supplier};}
async function payload(s:Awaited<ReturnType<typeof seed>>){const revision=(await db.query<{v:string}>('select finance_private.maintenance_direct_part_revision($1,$2,$3) v',[i.tenant,s.part,s.cost])).rows[0].v;return{version:1,tenant_id:i.tenant,request_id:randomUUID(),part_id:s.part,cost_id:s.cost,revision,reason:'Conferi a mão de obra e o fornecedor pelo documento',same_part_confirmed:true,classification:'direct_purchase',quantity:'2',document_number:'NF-123'};}
async function link(p:Record<string,unknown>,actor=i.operator){return(await financeAs<{v:Record<string,unknown>}>(db,actor,'select associate_finance_maintenance_direct_part($1) v',[p])).rows[0].v;}
async function reverse(id:unknown){return(await financeAs<{v:Record<string,unknown>}>(db,i.operator,'select reverse_finance_maintenance_direct_part_association($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),link_id:id,reason:'Associação incorreta após nova conferência'}])).rows[0].v;}
it('associates integral direct purchase without money or debt and preserves exact replay',async()=>{const s=await seed(),p=await payload(s),before=(await db.query('select * from payables')).rows;const r=await link(p);expect(r).toMatchObject({part_id:s.part,amount_cents:'5000',cash_created:false,obligation_created:false});expect(await link(p)).toEqual(r);expect((await db.query('select * from payables')).rows).toEqual(before);expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:0});});
it('requires classification, quantity and document declarations and rejects drivers',async()=>{const s=await seed(),p=await payload(s);await expect(link({...p,classification:'consumption'})).rejects.toThrow('finance_invalid_payload');await expect(link({...p,quantity:'3'})).rejects.toThrow('finance_maintenance_direct_part_declaration_mismatch');await expect(link({...p,document_number:'NF-999'})).rejects.toThrow('finance_maintenance_direct_part_declaration_mismatch');await expect(link(p,i.driverUser)).rejects.toThrow('finance_access_denied');});
it('blocks the same target from labor, then releases its database reservation on reversal',async()=>{const s=await seed(),r=await link(await payload(s));const v=(await db.query<{v:string}>('select finance_private.maintenance_labor_revision($1,$2,$3) v',[i.tenant,s.order,s.cost])).rows[0].v;const labor={version:1,tenant_id:i.tenant,request_id:randomUUID(),order_id:s.order,cost_id:s.cost,revision:v,reason:'Conferência da mão de obra da OS',same_labor_confirmed:true};await expect(financeAs(db,i.operator,'select associate_finance_maintenance_labor($1)',[labor])).rejects.toThrow('finance_maintenance_cost_already_associated');await reverse(r.link_id);expect((await db.query('select count(*)::int n from finance_maintenance_cost_claims')).rows[0]).toEqual({n:0});});
it('database constraint rejects a duplicate target even in privileged direct insertion',async()=>{const s=await seed();await link(await payload(s));await db.exec('savepoint duplicate_claim');await expect(db.exec('insert into finance_maintenance_labor_links(tenant_id,order_id,cost_id,supplier_id,amount_cents,actor_id,actor_name,reason,source_snapshot) select tenant_id,order_id,cost_id,supplier_id,amount_cents,actor_id,actor_name,reason,source_snapshot from finance_maintenance_direct_part_links')).rejects.toThrow('duplicate key');await db.exec('rollback to savepoint duplicate_claim');});
it('keeps snapshots, protects an active part and permits corrected review after reversal',async()=>{const s=await seed(),r=await link(await payload(s));await db.exec('savepoint protected_part');await expect(db.query('update maintenance_parts set quantity=3 where id=$1',[s.part])).rejects.toThrow('finance_maintenance_direct_part_source_protected');await db.exec('rollback to savepoint protected_part');await reverse(r.link_id);await db.query('update maintenance_parts set quantity=3 where id=$1',[s.part]);expect((await db.query("select source_snapshot->'part'->>'quantity' v from finance_maintenance_direct_part_links")).rows[0]).toEqual({v:'2'});await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_direct_part_invalid_value');});
it('does not adopt stock consumption or inconsistent amounts',async()=>{const s=await seed();await db.query('update maintenance_parts set stock_movement_id=gen_random_uuid() where id=$1',[s.part]);await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_part_stock_consumption');await db.query("update maintenance_parts set stock_movement_id=null,total_cost='NaN' where id=$1",[s.part]);await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_direct_part_invalid_value');});
it('accepts a catalog ID, protects the OS and blocks later stock movement until association reversal',async()=>{const s=await seed(),catalog=randomUUID();await db.query("insert into stock_items(id,tenant_id,name,category,unit) values($1,$2,'Peça','other','un')",[catalog,i.tenant]);await db.query('update maintenance_parts set stock_item_id=$1 where id=$2',[catalog,s.part]);const r=await link(await payload(s));await db.exec('savepoint os_guard');await expect(db.query("update maintenance_orders set status='cancelled' where id=$1",[s.order])).rejects.toThrow('finance_maintenance_direct_part_source_protected');await db.exec('rollback to savepoint os_guard');const stock=()=>db.query("insert into stock_movements(tenant_id,stock_item_id,maintenance_order_id,movement_type,quantity,unit_cost,total_cost,reason) values($1,$2,$3,'out',2,25,50,'Consumo conferido')",[i.tenant,catalog,s.order]);await db.exec('savepoint stock_guard');await expect(stock()).rejects.toThrow('finance_maintenance_part_stock_requires_review');await db.exec('rollback to savepoint stock_guard');await reverse(r.link_id);await stock();await expect(link(await payload(s))).rejects.toThrow('finance_maintenance_part_stock_requires_review');});
it('keeps labor revision current with cross-component reservations',async()=>{const s=await seed();const before=(await db.query<{v:string}>('select finance_private.maintenance_labor_revision($1,$2,$3) v',[i.tenant,s.order,s.cost])).rows[0].v;await link(await payload(s));const after=(await db.query<{v:string}>('select finance_private.maintenance_labor_revision($1,$2,$3) v',[i.tenant,s.order,s.cost])).rows[0].v;expect(after).not.toBe(before);});
it('protects the original tenant when moving an associated order is attempted',async()=>{const s=await seed();await link(await payload(s));await db.exec('savepoint tenant_move');await expect(db.query('update maintenance_orders set tenant_id=$1 where id=$2',[randomUUID(),s.order])).rejects.toThrow('finance_maintenance_direct_part_source_protected');await db.exec('rollback to savepoint tenant_move');expect((await db.query('select tenant_id from maintenance_orders where id=$1',[s.order])).rows[0]).toEqual({tenant_id:i.tenant});});
