// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
import {createLegacyIntegrityDatabase} from './helpers/legacyIntegrityDatabase';
import {legacyCutReviewSchema} from '../lib/financial/legacyCutReviewContract';
import {financeIds as i,financeAs} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createLegacyIntegrityDatabase>>;
beforeAll(async()=>{db=await createLegacyIntegrityDatabase();await db.exec("alter table receivables_payments add column financial_command_id uuid;alter table finance_payable_movement_links add column origin text default 'canonical'");const correction=readFileSync('supabase/migrations/20260910025658_finance_receipt_allocation_corrections.sql','utf8').match(/create table public\.finance_receipt_allocation_corrections\([\s\S]*?\n\);/)![0].replace(/,\s*foreign key\([^;]+?(?=,\s*foreign key|\s*\n\);)/gi,'');await db.exec(correction);const sql=readFileSync('supabase/migrations/20260910145616_finance_legacy_receipt_associations.sql','utf8');for(const name of ['finance_legacy_receipt_movement_links','finance_legacy_receipt_link_reversals']){let ddl=sql.match(new RegExp(`create table public\\.${name}\\([\\s\\S]*?\\n\\);`))![0];ddl=ddl.replace(/ references public\.\w+\([^)]*\)/g,'').replace(/,\s*foreign key\([^;]+?(?=,\s*foreign key|\s*\n\);)/gi,'');await db.exec(ddl);}await db.exec(readFileSync('supabase/migrations/20260910163116_finance_legacy_cut_reviews.sql','utf8'));},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
const preview=async()=> legacyCutReviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,i.account,'2026-01-01','2026-01-31'])).rows[0].v);
const admin=()=>db.query("update tenant_memberships set role='admin' where user_id=$1",[i.operator]);
const command=async()=>({version:1,tenant_id:i.tenant,request_id:randomUUID(),account_id:i.account,from:'2026-01-01',to:'2026-01-31',revision:(await preview()).revision,reason:'Conferi todas as fontes do corte bancário',sources_reviewed:true});
const review=async(p:unknown)=>(await financeAs<Record<string,unknown>>(db,i.operator,'select review_finance_legacy_cut($1) v',[p])).rows[0].v;
it('empty account has explicit positive approval and exact replay without money',async()=>{legacyCutReviewSchema.parse(await preview());expect((await preview()).can_review).toBe(false);await admin();const p=await command(),result=await review(p);expect(await review(p)).toEqual(result);expect(await preview()).toMatchObject({current:true,approved:true,status:'approved',blockers:[]});expect((await db.query<{n:number}>('select count(*)::int n from finance_movements')).rows[0].n).toBe(0);expect((await db.query<{n:number}>('select count(*)::int n from finance_legacy_cut_reviews')).rows[0].n).toBe(1);});
it('operator can preview but cannot approve and mixed driver remains excluded',async()=>{await expect(review(await command())).rejects.toThrow('access_denied');await admin();await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(preview()).rejects.toThrow('access_denied');});
it('new canonical movement invalidates source review and stale approval rejects atomically',async()=>{await admin();const p=await command();await review(p);await financeAs(db,i.operator,'select record_finance_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:1000,occurred_on:'2026-01-10',description:'Pagamento conferido',beneficiary_name:'Oficina',reason:'Registro de pagamento real'}]);expect(await preview()).toMatchObject({current:false,approved:false,status:'needs_review'});await expect(review({...p,request_id:randomUUID()})).rejects.toThrow('finance_legacy_cut_changed');await review(await command());expect((await preview()).approved).toBe(true);});
it('undated unknown monetary source blocks every potential account and cannot be approved',async()=>{await admin();await db.query("insert into payroll_entry_items(id,tenant_id,payroll_entry_id,payroll_period_id,employee_id,item_type,nature,source_table,source_id,description,amount) values($1,$2,$3,gen_random_uuid(),gen_random_uuid(),'advance','already_paid','unknown',$4,'Histórico sem data',25)",[randomUUID(),i.tenant,randomUUID(),randomUUID()]);const p=await preview();expect(p.blockers[0].code).toBe('legacy_source_date_unknown');expect(p.manifest.sources).toHaveLength(1);await expect(review(await command())).rejects.toThrow('finance_legacy_cut_unresolved');});
it('foreign account and immutable review are protected',async()=>{await admin();await review(await command());await db.exec('savepoint immutable');await expect(db.exec("update finance_legacy_cut_reviews set reason='Alteração posterior não permitida'" )).rejects.toThrow('finance_immutable_record');await db.exec('rollback to savepoint immutable');await expect(financeAs(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4)',[i.otherTenant,i.account,'2026-01-01','2026-01-31'])).rejects.toThrow('access_denied');});
async function mappedReceipt(){const parent=randomUUID(),payment=randomUUID(),tx=randomUUID();await db.query("insert into receivables(id,tenant_id,amount,status) values($1,$2,10,'received')",[parent,i.tenant]);await db.query("insert into bank_transactions(id,tenant_id,bank_account_id,posted_at,amount,transaction_type,raw_payload) values($1,$2,$3,'2026-01-10T12:00:00Z',10,'credit','{}')",[tx,i.tenant,i.account]);await db.query("insert into receivables_payments(id,tenant_id,receivable_id,amount,received_at,bank_account_id,bank_transaction_id) values($1,$2,$3,10,'2026-01-10T12:00:00Z',$4,$5)",[payment,i.tenant,parent,i.account,tx]);const response=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'in',nature:'receipt',amount_cents:1000,occurred_on:'2026-01-10',description:'Recebimento identificado',beneficiary_name:'Cliente cadastrado',reason:'Identificação do recebimento antigo'}])).rows[0].v;const cmd=randomUUID();await db.query('update receivables_payments set financial_command_id=$1 where id=$2',[cmd,payment]);await db.query("insert into finance_receivable_movement_links(tenant_id,command_id,payment_id,bank_transaction_id,movement_id,action) values($1,$2,$3,$4,$5,'receive')",[i.tenant,cmd,payment,tx,response.movement_id]);return{parent,payment,tx,movement:response.movement_id};}
it('exact receipt and bank alias approve, amount drift invalidates without creating money',async()=>{await admin();const f=await mappedReceipt(),p=await preview();legacyCutReviewSchema.parse(p);expect(p.blockers).toEqual([]);expect(p.manifest.sources.map((x:{classification:string})=>x.classification)).toEqual(['exact_canonical_mapping','exact_projection_alias']);await review(await command());await db.query('update receivables_payments set amount=11 where id=$1',[f.payment]);expect((await preview()).approved).toBe(false);expect((await preview()).blockers.length).toBeGreaterThan(0);});
it('all 31 unknown dated sources remain blocking, never a page-limited completeness check',async()=>{await admin();for(let n=0;n<31;n++)await db.query("insert into driver_settlement_payments(id,tenant_id,settlement_id,amount,paid_at) values($1,$2,$3,10,'2026-01-10T12:00:00Z')",[randomUUID(),i.tenant,randomUUID()]);const p=await preview();expect(p.manifest.source_count).toBe(31);expect(p.blockers).toHaveLength(31);await expect(review(await command())).rejects.toThrow('unresolved');});
it('invalid and cross-tenant monetary sources cannot disappear or receive approval',async()=>{await admin();const f=await mappedReceipt();await db.query("update receivables_payments set received_at='infinity',bank_account_id=$1,amount='NaN' where id=$2",[i.otherAccount,f.payment]);const p=await preview();expect(p.manifest.sources.some(x=>x.source_id===f.payment&&x.amount_cents===null&&x.occurred_on===null)).toBe(true);await expect(review(await command())).rejects.toThrow('unresolved');});
it('two exact links cannot consume more than movement capacity and history remains append-only',async()=>{await admin();const f=await mappedReceipt();await review(await command());const parent=randomUUID(),payment=randomUUID();await db.query("insert into receivables(id,tenant_id,amount,status) values($1,$2,10,'received')",[parent,i.tenant]);await db.query("insert into receivables_payments(id,tenant_id,receivable_id,amount,received_at,bank_account_id) values($1,$2,$3,10,'2026-01-10T12:00:00Z',$4)",[payment,i.tenant,parent,i.account]);const cmd=randomUUID(),tx=randomUUID();await db.query("insert into bank_transactions(id,tenant_id,bank_account_id,posted_at,amount,transaction_type,raw_payload) values($1,$2,$3,'2026-01-10T12:00:00Z',10,'credit','{}')",[tx,i.tenant,i.account]);await db.query('update receivables_payments set financial_command_id=$1,bank_transaction_id=$2 where id=$3',[cmd,tx,payment]);await db.query("insert into finance_receivable_movement_links(tenant_id,command_id,payment_id,bank_transaction_id,movement_id,action) values($1,$2,$3,$4,$5,'receive')",[i.tenant,cmd,payment,tx,f.movement]);expect((await preview()).blockers.some(x=>x.code==='legacy_mapping_capacity_exceeded')).toBe(true);expect((await preview()).history).toHaveLength(1);await expect(review(await command())).rejects.toThrow('unresolved');});
it('legacy receipt association is accepted only while its exact link is active',async()=>{await admin();const f=await mappedReceipt();await db.query('delete from finance_receivable_movement_links where payment_id=$1',[f.payment]);const link=randomUUID();await db.query("insert into finance_legacy_receipt_movement_links(id,tenant_id,payment_id,receivable_id,movement_id,amount_cents,created_by,actor_name,reason,source_snapshot) values($1,$2,$3,$4,$5,1000,$6,'Autor antigo','Conferência da associação antiga','{}')",[link,i.tenant,f.payment,f.parent,f.movement,i.operator]);expect((await preview()).blockers).toEqual([]);await review(await command());await db.query("insert into finance_legacy_receipt_link_reversals(tenant_id,link_id,created_by,actor_name,reason) values($1,$2,$3,'Autor atual','Vínculo antigo corrigido')",[i.tenant,link,i.operator]);expect((await preview()).approved).toBe(false);expect((await preview()).blockers.length).toBeGreaterThan(0);});
it('a canonical link with an unrelated payment command never suppresses the source',async()=>{await admin();const f=await mappedReceipt();await db.query('update finance_receivable_movement_links set command_id=$1 where payment_id=$2',[randomUUID(),f.payment]);const p=await preview();expect(p.blockers.some(x=>x.source_id===f.payment)).toBe(true);await expect(review(await command())).rejects.toThrow('unresolved');});
it('cross-account refund belongs to its outgoing bank account and refund day, never incoming parent',async()=>{await admin();const f=await mappedReceipt(),account=randomUUID(),tx=randomUUID(),refund=randomUUID();await db.query('insert into bank_accounts(id,tenant_id,active) values($1,$2,true)',[account,i.tenant]);await db.query("insert into bank_transactions(id,tenant_id,bank_account_id,posted_at,amount,transaction_type,raw_payload) values($1,$2,$3,'2026-02-02T01:00:00Z',10,'debit','{}')",[tx,i.tenant,account]);await db.query("insert into receivable_payment_reversals(id,tenant_id,receivable_id,payment_id,bank_transaction_id,financial_command_id,amount,effective_at,reason,created_by) values($1,$2,$3,$4,$5,$6,10,'2026-02-02T01:00:00Z','Devolução em outra conta',$7)",[refund,i.tenant,f.parent,f.payment,tx,randomUUID(),i.operator]);const get=async(a:string,from:string,to:string)=>legacyCutReviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_legacy_cut_review($1,$2,$3,$4) v',[i.tenant,a,from,to])).rows[0].v);expect((await get(account,'2026-02-01','2026-02-28')).manifest.sources).toEqual(expect.arrayContaining([expect.objectContaining({source_id:refund,account_id:account,occurred_on:'2026-02-01'})]));expect((await get(i.account,'2026-02-01','2026-02-28')).manifest.sources.some(x=>x.source_id===refund)).toBe(false);expect((await get(account,'2026-01-01','2026-01-31')).manifest.sources.some(x=>x.source_id===refund)).toBe(false);});
it.each(['canonical','legacy_adoption'])('reversed %s payable retains its distinct money semantics',async origin=>{await admin();const title=randomUUID(),payment=randomUUID(),link=randomUUID();await db.query("insert into payables(id,tenant_id,supplier_name,category,description,amount,due_date,status) values($1,$2,'Fornecedor','other','Título conferido',10,'2026-01-10','paid')",[title,i.tenant]);await db.query("insert into payables_payments(id,tenant_id,payable_id,amount,paid_at,bank_account_id,method) values($1,$2,$3,10,'2026-01-10T12:00:00Z',$4,'pix')",[payment,i.tenant,title,i.account]);const m=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:1000,occurred_on:'2026-01-10',description:'Pagamento conferido',beneficiary_name:'Fornecedor QA',reason:'Registro de pagamento real'}])).rows[0].v.movement_id;await db.query('insert into finance_payable_movement_links(id,tenant_id,movement_id,payable_id,payment_id,amount_cents,created_by,origin) values($1,$2,$3,$4,$5,1000,$6,$7)',[link,i.tenant,m,title,payment,i.operator,origin]);await db.query("insert into finance_payable_link_reversals(tenant_id,link_id,created_by,actor_name,reason) values($1,$2,$3,'Autor QA','Vínculo corrigido após conferência')",[i.tenant,link,i.operator]);const p=await preview();if(origin==='canonical'){expect(p.blockers).toEqual([]);expect(p.manifest.sources[0].classification).toBe('reversed_canonical_payment_projection');await review(await command());}else{expect(p.blockers).toHaveLength(1);await expect(review(await command())).rejects.toThrow('unresolved');}expect((await db.query('select * from payables_payments')).rows).toHaveLength(1);});
