// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createStockConsumptionDatabase} from './helpers/stockConsumptionDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createStockConsumptionDatabase>>;
beforeAll(async()=>{db=await createStockConsumptionDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function acquisition(q='10',c=100000,itemId?:string){const inbound=randomUUID(),item=itemId??randomUUID(),cost=randomUUID(),supplier=randomUUID();await db.query("insert into clients(id,tenant_id,company_name) values($1,$2,'Fornecedor')",[supplier,i.tenant]);if(!itemId)await db.query("insert into stock_items(id,tenant_id,name,category,unit) values($1,$2,'Filtro','filter','un')",[item,i.tenant]);
 await db.query("insert into stock_movements(id,tenant_id,stock_item_id,movement_type,quantity,unit_cost,total_cost,reason,moved_at) values($1,$2,$3,'inbound',$4,$5,$6,'purchase','2026-01-01')",[inbound,i.tenant,item,q,String(c/100/Number(q)),String(c/100)]);
 // 1 cent/3 units needs exact numeric division in the database for the historical source declaration.
 await db.query('update stock_movements set unit_cost=total_cost/quantity where id=$1',[inbound]);
 await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:'maintenance',description:'Compra estoque',reason:'Compra conferida pelo documento',items:[{id:cost,category:'maintenance',document_number:'NF-123',amount_cents:c,occurred_on:'2026-01-01',description:'Filtros adquiridos',supplier_id:supplier,supplier_name:'Fornecedor',payee_type:'supplier',no_receipt_reason:'Documento solicitado ao fornecedor',allocations:[]}]}]);
 const revision=(await db.query<{v:string}>('select finance_private.stock_acquisition_revision($1,$2,$3) v',[i.tenant,inbound,cost])).rows[0].v;
 const result=(await financeAs<{v:{link_id:string}}>(db,i.operator,'select associate_finance_stock_acquisition($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),inbound_movement_id:inbound,cost_id:cost,revision,quantity:q,document_number:'NF-123',same_purchase_confirmed:true,reason:'Identidade da aquisição conferida'}])).rows[0].v;return{item,link:result.link_id};}
async function source(item:string,q:string){const part=randomUUID(),movement=randomUUID(),order=randomUUID();await db.query("insert into maintenance_orders(id,tenant_id,order_number,status,opened_at) values($1,$2,'OS consumo','completed','2026-01-20')",[order,i.tenant]);await db.query("insert into stock_movements(id,tenant_id,stock_item_id,maintenance_order_id,movement_type,quantity,unit_cost,total_cost,reason,moved_at) values($1,$2,$3,$4,'consumption',$5,0,0,'maintenance','2026-01-20')",[movement,i.tenant,item,order,q]);await db.query("insert into maintenance_parts(id,tenant_id,maintenance_order_id,stock_item_id,stock_movement_id,item_description,quantity,unit_cost,total_cost) values($1,$2,$3,$4,$5,'Filtro',$6,0,0)",[part,i.tenant,order,item,movement,q]);return{part,movement,order};}
async function payload(s:Awaited<ReturnType<typeof source>>,lines:{acquisition_link_id:string;quantity:string}[]){const preview=(await db.query<{v:{revision:string}}>('select finance_private.stock_consumption_preview($1,$2,$3,$4) v',[i.tenant,s.part,s.movement,JSON.stringify(lines)])).rows[0].v;return{version:1,tenant_id:i.tenant,request_id:randomUUID(),maintenance_part_id:s.part,consumption_movement_id:s.movement,lines,revision:preview.revision,reason:'Consumo e origem física conferidos',same_stock_origin_confirmed:true,discrepancy_confirmed:true};}
async function apply(p:Record<string,unknown>){return(await financeAs<{v:Record<string,unknown>}>(db,i.operator,'select attribute_finance_stock_consumption($1) v',[p])).rows[0].v;}
async function reverse(id:unknown){const revision=(await db.query<{v:string}>('select finance_private.stock_consumption_reversal_revision($1,$2) v',[i.tenant,id])).rows[0].v;return financeAs(db,i.operator,'select reverse_finance_stock_consumption_attribution($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),attribution_id:id,revision,reason:'Corrigindo apenas a atribuição financeira'}]);}
it('attributes 2+3 units without another cost and preserves replay',async()=>{const a=await acquisition(),s=await source(a.item,'2'),p=await payload(s,[{acquisition_link_id:a.link,quantity:'2'}]);const r=await apply(p);expect(r.attributed_cents).toBe('20000');expect(await apply(p)).toEqual(r);const s2=await source(a.item,'3');expect((await apply(await payload(s2,[{acquisition_link_id:a.link,quantity:'3'}]))).attributed_cents).toBe('30000');expect((await db.query('select count(*)::int n from finance_expense_items')).rows[0]).toEqual({n:1});expect((await db.query('select count(*)::int n from finance_movements')).rows[0]).toEqual({n:0});});
it('uses multiple explicit acquisitions and reverses their exact reservations',async()=>{const a=await acquisition(),b=await acquisition('5',10000,a.item),s=await source(a.item,'4');const r=await apply(await payload(s,[{acquisition_link_id:a.link,quantity:'1'},{acquisition_link_id:b.link,quantity:'3'}]));expect(r.attributed_cents).toBe('16000');await reverse(r.attribution_id);expect((await db.query('select count(*)::int n from finance_stock_acquisition_dependencies')).rows[0]).toEqual({n:0});expect((await db.query('select count(*)::int n from finance_stock_consumption_lines')).rows[0]).toEqual({n:2});});
it('requires explicit discrepancy confirmation and rejects duplicate acquisition IDs',async()=>{const a=await acquisition(),s=await source(a.item,'2'),p=await payload(s,[{acquisition_link_id:a.link,quantity:'2'}]);await expect(apply({...p,discrepancy_confirmed:false})).rejects.toThrow('discrepancy_confirmation_required');await expect(payload(s,[{acquisition_link_id:a.link,quantity:'1'},{acquisition_link_id:a.link,quantity:'1'}])).rejects.toThrow('invalid_lines');});
it('conserves 1 cent across 3 units and returns exact original cents on middle reversal',async()=>{const a=await acquisition('3',1);const results:Record<string,unknown>[]=[];for(let k=0;k<3;k++){const s=await source(a.item,'1');results.push(await apply(await payload(s,[{acquisition_link_id:a.link,quantity:'1'}])));}expect(results.map(r=>r.attributed_cents)).toEqual(['0','0','1']);await reverse(results[1].attribution_id);const s=await source(a.item,'1');expect((await apply(await payload(s,[{acquisition_link_id:a.link,quantity:'1'}]))).attributed_cents).toBe('0');expect((await db.query('select sum(amount_cents)::text cents,sum(quantity)::text qty from finance_stock_acquisition_dependencies')).rows[0]).toEqual({cents:'1',qty:'3'});});
it('rejects stale availability and preserves source identity until reversal',async()=>{const a=await acquisition(),s=await source(a.item,'2'),old=await payload(s,[{acquisition_link_id:a.link,quantity:'2'}]);const other=await source(a.item,'1');await apply(await payload(other,[{acquisition_link_id:a.link,quantity:'1'}]));await expect(apply(old)).rejects.toThrow('finance_stock_consumption_changed');const r=await apply(await payload(s,[{acquisition_link_id:a.link,quantity:'2'}]));await db.exec('savepoint source_guard');await expect(db.query('update maintenance_parts set tenant_id=$1 where id=$2',[i.otherTenant,s.part])).rejects.toThrow('source_protected');await db.exec('rollback to savepoint source_guard');await reverse(r.attribution_id);await db.query("update maintenance_parts set quantity=3 where id=$1",[s.part]);});
it('accepts decimal physical quantities and returns last residual cent exactly',async()=>{const a=await acquisition('3',1),s=await source(a.item,'0.5');const first=await apply(await payload(s,[{acquisition_link_id:a.link,quantity:'0.5'}]));expect(first.attributed_cents).toBe('0');const last=await source(a.item,'2.5');const r=await apply(await payload(last,[{acquisition_link_id:a.link,quantity:'2.5'}]));expect(r.attributed_cents).toBe('1');await reverse(r.attribution_id);const replacement=await source(a.item,'2.5');expect((await apply(await payload(replacement,[{acquisition_link_id:a.link,quantity:'2.5'}]))).attributed_cents).toBe('1');});
it('rejects drivers and insufficient second acquisition without partial reservations',async()=>{const a=await acquisition('1',100),b=await acquisition('1',200,a.item),s=await source(a.item,'3'),p=await payload(s,[{acquisition_link_id:a.link,quantity:'1'},{acquisition_link_id:b.link,quantity:'2'}]);await expect(financeAs(db,i.driverUser,'select attribute_finance_stock_consumption($1)',[p])).rejects.toThrow('finance_access_denied');await expect(apply(p)).rejects.toThrow('capacity_exceeded');expect((await db.query('select count(*)::int n from finance_stock_acquisition_dependencies')).rows[0]).toEqual({n:0});expect((await db.query('select count(*)::int n from finance_stock_consumption_attributions')).rows[0]).toEqual({n:0});});
it('protects dependency reservations against direct deletion without audited reversal',async()=>{const a=await acquisition(),s=await source(a.item,'2');await apply(await payload(s,[{acquisition_link_id:a.link,quantity:'2'}]));await db.exec('savepoint dependency_delete');await expect(db.exec('delete from finance_stock_acquisition_dependencies')).rejects.toThrow('correction_required');await db.exec('rollback to savepoint dependency_delete');expect((await db.query('select total_cost::text from maintenance_parts where id=$1',[s.part])).rows[0]).toEqual({total_cost:'0'});});
