// @vitest-environment node
import {afterAll,afterEach,beforeAll,beforeEach,expect,it} from 'vitest';
import {createFiscalReadinessDatabase,prepareFiscal,claimFiscal} from './helpers/fiscalReadinessDatabase';
let context:Awaited<ReturnType<typeof createFiscalReadinessDatabase>>;
beforeAll(async()=>{context=await createFiscalReadinessDatabase();},30000);
beforeEach(async()=>{await context.db.exec('begin');});afterEach(async()=>{await context.db.exec('rollback');});afterAll(async()=>{await context.db.close();});
async function uncertain(){const doc=await prepareFiscal(context.db,context.emitter,context.client);const claim=await claimFiscal(context.db,context.emitter,doc.id);await context.db.query("update hub_fiscal_emissions set dispatch_state='uncertain',last_response='{\"error\":{\"code\":\"TRANSPORT_UNCERTAIN\"}}' where id=$1",[claim.emission.id]);return {doc,claim};}
async function attest(id:string,overrides:Record<string,unknown>={}){await context.db.query("update hub_fiscal_emissions set dispatch_reconciliation=$2::jsonb||jsonb_build_object('payload_md5',md5(request_payload::text)) where id=$1",[id,JSON.stringify({resolution:'confirmed_not_sent_local_configuration',resume_authorized:true,operator_confirmed_provider_absence:true,preflight:{baseConfigured:false},provider_lookup:{httpStatus:200,providerSuccess:true,recordsReturned:0},...overrides})]);}
it('keeps an uncertain operation blocked without explicit evidence',async()=>{const {doc}=await uncertain();expect((await claimFiscal(context.db,context.emitter,doc.id)).dispatch).toBe(false);});
it('consumes an audited resume only once while preserving identity and full payload',async()=>{const {doc,claim}=await uncertain();await attest(claim.emission.id);const resumed=await claimFiscal(context.db,context.emitter,doc.id);expect(resumed.dispatch).toBe(true);expect(resumed.emission).toMatchObject({id:claim.emission.id,request_payload:claim.emission.request_payload});expect((await claimFiscal(context.db,context.emitter,doc.id)).dispatch).toBe(false);expect((await context.db.query('select count(*)::int n from hub_fiscal_emissions')).rows).toEqual([{n:1}]);});
it('does not grant another retry after the resumed transport becomes uncertain',async()=>{const {doc,claim}=await uncertain();await attest(claim.emission.id);await claimFiscal(context.db,context.emitter,doc.id);await context.db.query("update hub_fiscal_emissions set dispatch_state='uncertain' where id=$1",[claim.emission.id]);expect((await claimFiscal(context.db,context.emitter,doc.id)).dispatch).toBe(false);});
it('does not resume if the persisted snapshot changed after reconciliation',async()=>{const {doc,claim}=await uncertain();await attest(claim.emission.id);await context.db.query("update hub_fiscal_emissions set request_payload=request_payload||'{\"changed\":true}' where id=$1",[claim.emission.id]);expect((await claimFiscal(context.db,context.emitter,doc.id)).dispatch).toBe(false);});
it('does not treat a provider lookup alone as proof of a local non-send',async()=>{const {doc,claim}=await uncertain();await attest(claim.emission.id,{preflight:{baseConfigured:true}});expect((await claimFiscal(context.db,context.emitter,doc.id)).dispatch).toBe(false);});
it('keeps reconciliation evidence unwritable by the browser',async()=>{const {claim}=await uncertain();await context.db.exec('set role authenticated');await expect(context.db.query('update hub_fiscal_emissions set dispatch_reconciliation=$2::jsonb where id=$1',[claim.emission.id,'{}'])).rejects.toThrow();});
