import {act,cleanup,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {FiscalDashboardCard,FiscalDashboardSummary} from '@/components/financial/FiscalDashboardSummary';
import {useFiscalDashboardSummary} from '@/hooks/useFiscalDashboardSummary';
const read=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/fiscalDashboardClient',()=>({readFiscalDashboard:read}));
const result={total_count:1003,active_count:1001,cancelled_count:1,review_count:1,invalid_count:0,totals_valid:true,net_cents:'95000',gross_cents:'100000',withheld_cents:'5000',kinds:[{doc_type:'nfse',active_count:1001,net_cents:'95000'}],months:[{month:'2026-09',net_cents:'95000'}],pending_jobs:200};
beforeEach(()=>{vi.clearAllMocks();read.mockResolvedValue(result);});afterEach(cleanup);
function Fixture(){const state=useFiscalDashboardSummary('tenant','actor',{from:null,to:null,client:'client',docType:'nfse'});return <><FiscalDashboardCard state={state}/><FiscalDashboardSummary state={state}/></>;}
function open(cache=new QueryClient()){return render(<QueryClientProvider client={cache}><Fixture/></QueryClientProvider>);}
it('labels incorporation basis and global pending jobs while separating retained from net',async()=>{open();expect(await screen.findByText(/1003 origem/)).toHaveTextContent('1001 ativa');expect(screen.getByText('R$ 1.000,00')).toBeInTheDocument();expect(screen.getByText('R$ 50,00')).toBeInTheDocument();expect(screen.getAllByText('R$ 950,00').length).toBeGreaterThan(0);expect(screen.getByText(/200 processamento/)).toHaveTextContent('todas as datas e clientes');expect(screen.getByText(/dia da incorporação/)).toBeInTheDocument();});
it('does not replace invalid or absent incorporated origins by a claim of no fiscal revenue',async()=>{read.mockResolvedValue({...result,invalid_count:1,totals_valid:false,net_cents:null,gross_cents:null,withheld_cents:null,kinds:[],months:[]});const view=open();expect(await screen.findByRole('alert')).toHaveTextContent('valores estão indisponíveis');expect(screen.queryByText(/R\$/)).not.toBeInTheDocument();view.unmount();read.mockResolvedValue({...result,total_count:0,active_count:0,cancelled_count:0,review_count:0,net_cents:'0',gross_cents:'0',withheld_cents:'0',kinds:[],months:[]});open();expect(await screen.findByText(/não significa ausência de documentos emitidos/)).toBeInTheDocument();});
it('hides stale totals while fetching and after an error',async()=>{const cache=new QueryClient();open(cache);await screen.findByText(/1003 origem/);let reject!:(e:Error)=>void;read.mockImplementationOnce(()=>new Promise((_,no)=>{reject=no;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-fiscal-dashboard-summary']});});await waitFor(()=>expect(screen.queryByText(/1003 origem/)).not.toBeInTheDocument());expect(screen.queryByText(/R\$/)).not.toBeInTheDocument();await act(async()=>{reject(new Error('offline'));});expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível consultar');});
