// @vitest-environment node
import {createRequire} from 'node:module';import {it,expect,vi} from 'vitest';
import {downloadExistingXml,inspectExistingXml,type XmlReader,type EmissionIdentity} from '../../supabase/functions/finance-fiscal-evidence-preview/preview';
const require=createRequire(import.meta.url);const {SaxesParser}=createRequire(require.resolve('jsdom'))('saxes');
const parser=()=>new SaxesParser({xmlns:true}) as XmlReader;
const e:EmissionIdentity={id:crypto.randomUUID(),tenant_id:crypto.randomUUID(),doc_type:'cte',environment:'production',status:'authorized',dispatch_state:'recorded',hub_document_id:crypto.randomUUID(),access_key:'1'.repeat(44),emitter_cnpj:'12345678000199',number:'123',series:'1',authorization_protocol:'2'.repeat(15)};
const xml=`<?xml version="1.0"?><cteProc versao="4.00" xmlns="http://www.portalfiscal.inf.br/cte"><CTe><infCte versao="4.00" Id="CTe${e.access_key}"><ide><tpAmb>1</tpAmb><nCT>123</nCT><serie>1</serie></ide><emit><CNPJ>${e.emitter_cnpj}</CNPJ></emit><vPrest><vTPrest>123.45</vTPrest></vPrest><infCTeNorm><infDoc><infNFe><chave>1</chave></infNFe><infNFe><chave>2</chave></infNFe></infDoc></infCTeNorm></infCte></CTe><protCTe versao="4.00"><infProt><tpAmb>1</tpAmb><chCTe>${e.access_key}</chCTe><nProt>${e.authorization_protocol}</nProt><cStat>100</cStat></infProt></protCTe></cteProc>`;
const inspect=(s=xml,identity=e)=>inspectExistingXml(new TextEncoder().encode(s),identity,parser);
it('parses a CT-e processed-envelope fixture, keeps cents exact, and never permits projection',async()=>{expect(await inspect()).toMatchObject({issues:[],amount_cents:'12345',signature_verified:false,can_project:false,can_receive:false});});
it('rejects DTD, malformed XML, duplicate decisive value and fractional cents',async()=>{await expect(inspect('<!DOCTYPE x>'+xml)).rejects.toThrow('external_entities');await expect(inspect('<bad>')).rejects.toThrow('xml_invalid');expect((await inspect(xml.replace('123.45','123.456'))).issues).toContain('xml_amount_invalid');expect((await inspect(xml.replace('</vTPrest>','</vTPrest><vTPrest>10</vTPrest>'))).issues).toContain('xml_amount_invalid');});
it('does not treat mismatched key/emitter/protocol or inactive emission as authorized',async()=>{expect((await inspect(xml,{...e,emitter_cnpj:'00000000000000'})).issues).toContain('xml_emission_identity_mismatch');expect((await inspect(xml,{...e,authorization_protocol:'3'.repeat(15)})).issues).toContain('stored_protocol_differs');expect((await inspect(xml,{...e,status:'cancelled'})).issues).toContain('stored_emission_not_authorized');});
it('keeps unreviewed municipal NFS-e layout unresolved, never guesses values',async()=>{const r=await inspect('<CompNfse xmlns="http://www.abrasf.org.br/nfse.xsd"><Nfse><InfNfse><Numero>1</Numero></InfNfse></Nfse></CompNfse>',{...e,doc_type:'nfse'});expect(r).toMatchObject({amount_cents:null,protocol:null,can_project:false,issues:['nfse_authorization_layout_not_reviewed']});});
it('downloads exactly one existing hub ID by GET, rejects redirects and URL/JSON fallbacks',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(xml,{headers:{'Content-Type':'application/xml'}}));await downloadExistingXml('https://rvgcsmuyvesusbxsqevr.supabase.co/functions/v1','server-token',e.hub_document_id,fetcher);expect(fetcher).toHaveBeenCalledOnce();const [url,options]=fetcher.mock.calls[0];expect(String(url)).toBe(`https://rvgcsmuyvesusbxsqevr.supabase.co/functions/v1/hub_documents_file?id=${e.hub_document_id}&kind=xml`);expect(options).toMatchObject({method:'GET',redirect:'manual'});fetcher.mockResolvedValue(new Response(null,{status:302,headers:{Location:'http://127.0.0.1'}}));await expect(downloadExistingXml('https://rvgcsmuyvesusbxsqevr.supabase.co/functions/v1','x',e.hub_document_id,fetcher)).rejects.toThrow('unavailable');fetcher.mockResolvedValue(new Response(JSON.stringify({url:'http://127.0.0.1'})));await expect(downloadExistingXml('https://rvgcsmuyvesusbxsqevr.supabase.co/functions/v1','x',e.hub_document_id,fetcher)).rejects.toThrow('unsupported');await expect(downloadExistingXml('http://127.0.0.1','x',e.hub_document_id,fetcher)).rejects.toThrow('not_allowed');});

it('rejects streaming oversize and foreign-namespace identity fields',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(new Uint8Array(2_000_001)));await expect(downloadExistingXml('https://rvgcsmuyvesusbxsqevr.supabase.co/functions/v1','x',e.hub_document_id,fetcher)).rejects.toThrow('too_large');expect((await inspect(xml.replace('<CNPJ>','<CNPJ xmlns="urn:untrusted">'))).issues).toContain('xml_emission_identity_mismatch');});

it('keeps older CT-e versions unresolved and bounds request streams before decoding',async()=>{expect((await inspect(xml.replace('versao="4.00"','versao="3.00"'))).issues).toContain('cte_xml_version_unsupported');const {readBoundedBody}=await import('../../supabase/functions/secure-upload/bounded-request');await expect(readBoundedBody(new Request('https://example.test',{method:'POST',body:'a'.repeat(2049)}),2048)).rejects.toThrow();});
