import {beforeEach,it,expect,vi} from 'vitest';
import {readFiscalDashboard} from '@/lib/financial/fiscalDashboardClient';
import {fiscalDashboardSchema} from '@/lib/financial/fiscalDashboardContract';
const rpc=vi.hoisted(()=>vi.fn());vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc}}));beforeEach(()=>rpc.mockReset());
const tenant=crypto.randomUUID(),filters={from:null,to:null,client:null,docType:'all' as const};
const result={version:1,tenant_id:tenant,from:null,to:null,client_id:null,doc_type:'all',basis:'fiscal_receivable_origins',date_basis:'incorporated_at',total_count:1003,active_count:1001,cancelled_count:1,review_count:1,invalid_count:0,totals_valid:true,net_cents:'95000',gross_cents:'100000',withheld_cents:'5000',kinds:[{doc_type:'nfse',active_count:1001,net_cents:'95000'}],months:[{month:'2026-09',net_cents:'95000'}],pending_jobs:200,pending_jobs_scope:'tenant_all_dates'};
it('queries all incorporated origins and preserves gross net and withholdings distinctly',async()=>{rpc.mockResolvedValue({data:result,error:null});expect((await readFiscalDashboard(tenant,filters)).active_count).toBe(1001);expect(rpc).toHaveBeenCalledWith('get_finance_fiscal_dashboard_summary',{_tenant_id:tenant,_from:null,_to:null,_client_id:null,_doc_type:'all'});});
it('rejects wrong scope, invented bank/date basis and totals that diverge from groups',async()=>{for(const override of [{client_id:crypto.randomUUID()},{doc_type:'cte'},{date_basis:'issue_date'},{pending_jobs_scope:'filtered'},{gross_cents:'99000'},{kinds:[{...result.kinds[0],net_cents:'90000'}]},{total_count:1004}]){rpc.mockResolvedValue({data:{...result,...override},error:null});await expect(readFiscalDashboard(tenant,filters)).rejects.toThrow();}});
it('requires null amounts for all groups when an active origin is invalid',()=>{const invalid={...result,invalid_count:1,totals_valid:false,net_cents:null,gross_cents:null,withheld_cents:null,kinds:[{doc_type:'nfse',active_count:1001,net_cents:null}],months:[{month:'2026-09',net_cents:null}]};expect(fiscalDashboardSchema.safeParse(invalid).success).toBe(true);expect(fiscalDashboardSchema.safeParse({...invalid,net_cents:'0'}).success).toBe(false);});
