import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {LegacyPayableAssociationWorkspace} from '@/components/financial/LegacyPayableAssociation';
import {LegacyPayableRejectedError} from '@/lib/financial/legacyPayableAssociationClient';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/legacyPayableAssociationClient',()=>({readLegacyPayableAssociation:mock.read,submitLegacyPayableAssociation:mock.submit,LegacyPayableRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),payment=crypto.randomUUID(),movement=crypto.randomUUID(),link=crypto.randomUUID(),key=`finance-legacy-payable-association:${tenant}:${actor}:${payment}`;
const row={id:movement,bank_account_id:crypto.randomUUID(),account_name:'Banco operação',beneficiary_name:'Fornecedor QA',description:'Saída histórica',occurred_on:'2026-01-10',bank_reference:'ref-123',amount_cents:'60000',remaining_cents:'50000'};
const context={version:1,tenant_id:tenant,payment_id:payment,revision:'source-1',page:1,page_size:20,total:1,rows:[row],payment:{id:payment,payable_id:crypto.randomUUID(),bank_account_id:row.bank_account_id,account_name:row.account_name,supplier_name:row.beneficiary_name,paid_on:row.occurred_on,amount_cents:'50000',bank_transaction_id:null,driver_id:null},eligible:true,issue:null,active_link:null,history_total:0,history:[]};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(context);mock.submit.mockResolvedValue({payment_id:payment});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(id=payment,cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><LegacyPayableAssociationWorkspace tenant={tenant} actor={actor} payment={id}/></QueryClientProvider>);}
async function review(reverse=false){if(!reverse)fireEvent.click(await screen.findByRole('radio'));fireEvent.change(await screen.findByLabelText('Motivo da associação ou correção'),{target:{value:'Origem do pagamento antigo conferida'}});fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção'}));}
it('reviews an explicit candidate and replays the original command after a lost reply',async()=>{
 mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await review();expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção'}));await screen.findByRole('alert');const original=mock.submit.mock.calls[0][0];expect(original.command).toMatchObject({payment_id:payment,movement_id:movement});expect(original.command).not.toHaveProperty('amount_cents');view.unmount();mock.read.mockResolvedValue({...context,rows:[],total:0,active_link:link});open();fireEvent.click(screen.getByRole('button',{name:'Retomar associação original'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);expect(sessionStorage.getItem(key)).toBeNull();
});
it('recovers a reversal with permanent authorship and does not claim the payment was undone',async()=>{
 const item={id:link,movement_id:movement,amount_cents:'50000',actor_id:actor,actor_name:'Ana Financeiro',reason:'Pagamento histórico conferido',created_at:'2026-02-01',origin:'legacy_adoption',reversal:null};mock.read.mockResolvedValue({...context,active_link:link,history_total:1,history:[item]});mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();fireEvent.click(await screen.findByRole('button',{name:'Desfazer associação ativa'}));await review(true);fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(1));const original=mock.submit.mock.calls[0][0];expect(original.kind).toBe('reverse');view.unmount();mock.read.mockResolvedValue({...context,history_total:1,history:[{...item,reversal:{id:crypto.randomUUID(),actor_id:actor,actor_name:'Gestor Paulo',reason:'Saída incorreta identificada',created_at:'2026-02-02'}}]});open();fireEvent.click(screen.getByRole('button',{name:'Retomar associação original'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);expect(await screen.findByText(/Desfeita por Gestor Paulo/)).toBeInTheDocument();expect(screen.getByText('Pagamento preservado; esta correção não reabre o título.')).toBeInTheDocument();
});
it('hides stale candidates after a failed refresh and does not turn missing candidates into a new payment',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});const view=open(payment,cache);await review();mock.read.mockRejectedValue(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-legacy-payable-association']});});await screen.findByText(/Não foi possível consultar o pagamento/);expect(screen.queryByRole('radio')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Confirmar associação ou correção'})).not.toBeInTheDocument();view.unmount();mock.read.mockResolvedValue({...context,total:0,rows:[]});open();expect(await screen.findByText(/não significa que é necessário pagar novamente/)).toBeInTheDocument();expect(mock.submit).not.toHaveBeenCalled();
});
it('blocks corrupt or unavailable persistence',async()=>{
 sessionStorage.setItem(key,'corrupt');const view=open();expect(await screen.findByRole('alert')).toHaveTextContent('bloqueadas');expect(await screen.findByRole('radio')).toBeDisabled();view.unmount();sessionStorage.clear();const next=open();await review();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('full');});fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção'}));expect(await screen.findByRole('alert')).toHaveTextContent('Nenhuma associação foi enviada');expect(mock.submit).not.toHaveBeenCalled();next.unmount();
});
it('paginates history even when no movement candidate remains',async()=>{
 mock.read.mockResolvedValue({...context,active_link:link,total:0,rows:[],history_total:21});open();fireEvent.click(await screen.findByRole('button',{name:'Próxima'}));await waitFor(()=>expect(mock.read).toHaveBeenCalledWith(tenant,payment,2));expect(await screen.findByText('Página 2')).toBeInTheDocument();
});
it('requires another review if the visible payment or available capacity changes',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(payment,cache);await review();mock.read.mockResolvedValue({...context,rows:[{...row,remaining_cents:'45000'}]});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-legacy-payable-association']});});await waitFor(()=>expect(screen.getByRole('button',{name:'Confirmar associação ou correção'})).toBeDisabled());expect(mock.submit).not.toHaveBeenCalled();
});
it('binds review to source revision and retains that revision after an uncertain request is rejected',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}}),view=open(payment,cache);await review();mock.read.mockResolvedValue({...context,revision:'source-2'});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-legacy-payable-association']});});await waitFor(()=>expect(screen.getByRole('button',{name:'Confirmar associação ou correção'})).toBeDisabled());view.unmount();
 const original={kind:'associate',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),payment_id:payment,movement_id:movement,revision:'source-1',reason:'Pedido enviado antes da mudança'}};sessionStorage.setItem(key,JSON.stringify({actor,payment,pending:original}));mock.submit.mockRejectedValueOnce(new LegacyPayableRejectedError('finance_legacy_payment_changed'));open();fireEvent.click(screen.getByRole('button',{name:'Retomar associação original'}));expect(await screen.findByRole('alert')).toHaveTextContent('preservado para retomada');expect(mock.submit).toHaveBeenLastCalledWith(original);expect(JSON.parse(sessionStorage.getItem(key)!).pending).toEqual(original);
});
it('allows review after first known rejection but preserves previously uncertain commands',async()=>{
 mock.submit.mockRejectedValueOnce(new LegacyPayableRejectedError('finance_movement_overallocated'));const view=open();await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção'}));await screen.findByText(/O vínculo foi recusado/);expect(sessionStorage.getItem(key)).toBeNull();view.unmount();const original=mock.submit.mock.calls[0][0];sessionStorage.setItem(key,JSON.stringify({actor,payment,pending:original}));mock.submit.mockRejectedValueOnce(new LegacyPayableRejectedError('finance_movement_overallocated'));const next=open();fireEvent.click(screen.getByRole('button',{name:'Retomar associação original'}));expect(await screen.findByRole('alert')).toHaveTextContent('preservado para retomada');next.unmount();open(crypto.randomUUID());await screen.findByRole('radio');expect(screen.queryByRole('button',{name:'Retomar associação original'})).not.toBeInTheDocument();expect(JSON.parse(sessionStorage.getItem(key)!).pending).toEqual(original);
});
