import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {LegacyCutReviewWorkspace} from '@/components/financial/LegacyCutReview';
import {legacyCutReviewSchema} from '@/lib/financial/legacyCutReviewContract';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/legacyCutReviewClient',()=>({readLegacyCutReview:mock.read,submitLegacyCutReview:mock.submit,LegacyCutRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),from='2026-01-01',to='2026-01-31';
const context={version:1,tenant_id:tenant,account_id:account,from,to,revision:'a'.repeat(32),current:false,approved:false,can_review:true,status:'not_approved',review_id:null,approval:null,history:[],blockers:[],manifest:{version:1,tenant_id:tenant,account_id:account,from,to,revision:'a'.repeat(32),classifier_version:'1',source_count:0,sources:[],evidence:{bank_transactions:[],receivables_payments:[]},integrity:[],blockers:[]}};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(context);mock.submit.mockResolvedValue({});});afterEach(()=>cleanup());
function open(client=new QueryClient()){return render(<QueryClientProvider client={client}><LegacyCutReviewWorkspace tenant={tenant} actor={actor} account={account} from={from} to={to}/></QueryClientProvider>);}
it('invalidates a cached cash closure preview after reviewing its legacy sources',async()=>{
 const client=new QueryClient(),key=['finance-cash-period-close-preview',tenant,actor,account,from,to,crypto.randomUUID()];
 client.setQueryData(key,{eligible:false,blockers:[{code:'legacy_cut_requires_review'}]});
 open(client);await screen.findByText(/Nenhuma origem monetária/);
 fireEvent.change(screen.getByLabelText('Motivo da revisão do corte'),{target:{value:'Fontes históricas do caixa conferidas'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar decisão do corte'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar revisão do corte'}));
 await screen.findByText(/Revisão do corte registrada com autoria/);expect(client.getQueryState(key)?.isInvalidated).toBe(true);
});
it('shows paid projection installments without presenting another cash expense',async()=>{
 const id=crypto.randomUUID(),payment=crypto.randomUUID(),movement=crypto.randomUUID(),link=crypto.randomUUID();
 const source={source_table:'employee_advances',source_id:id,occurred_on:null,account_id:account,amount_cents:null,movement_ids:[movement],classification:'exact_projection_alias',chain_revision:'b'.repeat(32),footprints:[{payment_id:payment,link_id:link,movement_id:movement,account_id:account,occurred_on:from,amount_cents:'2000'}]};
 mock.read.mockResolvedValue(legacyCutReviewSchema.parse({...context,manifest:{...context.manifest,classifier_version:'3',source_count:1,sources:[source],evidence:{employee_advances:[{id}],[`paid_projection_chain:employee_advances:${id}`]:[{valid:true,footprints:source.footprints}]}}}));
 open();await screen.findByText(/Pagamento já representado nos movimentos, sem nova saída/);
 const installments=screen.getByRole('list',{name:'Parcelas comprovadas nesta conta e período'});
 expect(installments).toHaveTextContent(payment);expect(installments).toHaveTextContent(movement);expect(installments).toHaveTextContent('20,00');
 expect(screen.queryByText(/Origem precisa de resolução/)).not.toBeInTheDocument();expect(mock.submit).not.toHaveBeenCalled();
});
it('does not approve an empty manifest automatically and recovers the original review',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await screen.findByText(/Nenhuma origem monetária/);fireEvent.change(screen.getByLabelText('Motivo da revisão do corte'),{target:{value:'Fontes históricas conferidas integralmente'}});expect(screen.getByRole('button',{name:'Revisar decisão do corte'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar decisão do corte'}));expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar revisão do corte'}));await screen.findByText(/pedido original foi preservado/);const original=mock.submit.mock.calls[0][0];expect(original.sources_reviewed).toBe(true);view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar revisão do corte'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('shows unresolved source IDs and read-only capability without inventing monetary totals',async()=>{const id=crypto.randomUUID();mock.read.mockResolvedValue({...context,can_review:false,blockers:[{code:'legacy_source_account_unknown',source_table:'bank_transactions',source_id:id}]});open();expect(await screen.findByText(/conta da origem não está identificada/)).toHaveTextContent(id);expect(screen.queryByRole('button',{name:'Revisar decisão do corte'})).not.toBeInTheDocument();expect(screen.getByText(/seus valores não são distribuídos nem somados/)).toBeInTheDocument();});
it('blocks corrupt recovery and hides prior facts after fetch error',async()=>{sessionStorage.setItem(`finance-legacy-cut-review:${tenant}:${actor}:${account}`,'broken');open();await screen.findByText(/Novas revisões estão bloqueadas/);await screen.findByText(/Nenhuma origem monetária/);mock.read.mockRejectedValueOnce(new Error('offline'));fireEvent.click(screen.getByRole('button',{name:'Atualizar manifesto do corte'}));await screen.findByText(/Não foi possível consultar o corte/);expect(screen.queryByText(/Nenhuma origem monetária/)).not.toBeInTheDocument();expect(mock.submit).not.toHaveBeenCalled();});
it('preserves invalid paid-proof installments and explicitly shows missing linkage',async()=>{const source={source_table:'employee_advances',source_id:crypto.randomUUID(),occurred_on:null,account_id:account,amount_cents:null,movement_ids:[],classification:'integrity_failure',footprints:[{payment_id:crypto.randomUUID(),link_id:null,movement_id:crypto.randomUUID(),account_id:null,occurred_on:null,amount_cents:'2000'}]};mock.read.mockResolvedValue({...context,manifest:{...context.manifest,source_count:1,sources:[source]}});open();await screen.findByText(/Parcelas preservadas com comprovação inconsistente — não representam nova saída/);expect(screen.getByRole('list',{name:'Parcelas preservadas com comprovação inconsistente'})).toHaveTextContent(source.footprints[0].payment_id);expect(screen.getByText(/Não identificado — comprovação incompleta/)).toBeInTheDocument();expect(screen.getByText('IDs dos movimentos não identificados nesta consulta; comprovação incompleta.')).toBeInTheDocument();});
