import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {LegacyCostAssociationWorkspace} from '@/components/financial/LegacyCostAssociation';
import {LegacyCostRejectedError} from '@/lib/financial/legacyCostAssociationClient';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/legacyCostAssociationClient',()=>({readLegacyCostAssociation:mock.read,submitLegacyCostAssociation:mock.submit,LegacyCostRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),expense=crypto.randomUUID(),cost=crypto.randomUUID(),link=crypto.randomUUID(),key=`finance-legacy-cost-association:${tenant}:${actor}:${expense}`;
const row={cost_id:cost,batch_id:crypto.randomUUID(),description:'Combustível da viagem',category:'fuel',amount_cents:'50000',occurred_on:'2026-01-10',issue:null,revision:'a'.repeat(32)};
const context={version:1,tenant_id:tenant,expense_id:expense,page:1,page_size:30,total:1,source:{id:expense,trip_id:crypto.randomUUID(),driver_id:crypto.randomUUID(),description:null,category:'fuel',amount_cents:'50000',occurred_on:'2026-01-10',approval_status:'approved',payment_source:'company_account',reimbursable:false,issue:null},active_link:null,history:{total:0,rows:[]},candidates:[row]};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(context);mock.submit.mockResolvedValue({expense_id:expense});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><LegacyCostAssociationWorkspace tenant={tenant} actor={actor} expense={expense}/></QueryClientProvider>);}
async function prepare(){fireEvent.click(await screen.findByRole('radio'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de custo'),{target:{value:'Duas origens do mesmo gasto conferidas'}});fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de custo'}));}
it('requires identity declaration and review, preserves exact request after lost response',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();fireEvent.click(await screen.findByRole('radio'));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de custo'),{target:{value:'Conferência integral da origem'}});expect(screen.getByRole('button',{name:'Revisar associação ou correção de custo'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de custo'}));expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de custo'}));await screen.findByText(/pedido original foi preservado/);const original=mock.submit.mock.calls[0][0];expect(original.command.same_expense_confirmed).toBe(true);view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar associação ou correção de custo'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('blocks corrupted or wrong-origin saved storage',async()=>{sessionStorage.setItem(key,JSON.stringify({actor,expense:'wrong',pending:{}}));open();await screen.findByText(/Novas associações e correções estão bloqueadas/);expect(await screen.findByRole('radio')).toBeDisabled();expect(mock.submit).not.toHaveBeenCalled();});
it('rejects changed preview and hides stale options on error',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await prepare();mock.read.mockRejectedValueOnce(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-legacy-cost-context']});});await screen.findByRole('alert');expect(screen.queryByRole('radio')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Confirmar associação ou correção de custo'})).not.toBeInTheDocument();expect(mock.submit).not.toHaveBeenCalled();});
it('known first rejection releases editing while historical reversal retains audit',async()=>{mock.submit.mockRejectedValueOnce(new LegacyCostRejectedError('finance_legacy_cost_changed'));open();await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de custo'}));await screen.findByText(/dados de uma das origens mudaram/);await waitFor(()=>expect(sessionStorage.getItem(key)).toBeNull());expect(await screen.findByRole('radio')).not.toBeDisabled();});
it('reverses only the active association with permanent authorship',async()=>{const active={id:link,cost_id:cost,amount_cents:'50000',actor_id:actor,actor_name:'Maria financeira',reason:'Identidade conferida anteriormente',created_at:'2026-01-10T12:00:00Z'};mock.read.mockResolvedValue({...context,active_link:active,history:{total:1,rows:[{...active,reversal:null}]}});open();fireEvent.click(await screen.findByRole('button',{name:'Desfazer associação ativa'}));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de custo'),{target:{value:'Correção de origem escolhida incorretamente'}});fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de custo'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de custo'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(1));expect(mock.submit.mock.calls[0][0]).toMatchObject({kind:'reverse',command:{link_id:link}});expect(screen.getAllByText(/Maria financeira/).length).toBeGreaterThan(0);});
