import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {MaintenanceDirectPartAssociationWorkspace} from '@/components/financial/MaintenanceDirectPartAssociation';
import {MaintenanceDirectPartRejectedError} from '@/lib/financial/maintenanceDirectPartAssociationClient';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/maintenanceDirectPartAssociationClient',()=>({readMaintenanceDirectPartAssociation:mock.read,submitMaintenanceDirectPartAssociation:mock.submit,MaintenanceDirectPartRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),part=crypto.randomUUID(),order=crypto.randomUUID(),cost=crypto.randomUUID(),supplier=crypto.randomUUID(),link=crypto.randomUUID(),key=`finance-maintenance-direct-part-association:${tenant}:${actor}:${part}`;
const row={cost_id:cost,batch_id:crypto.randomUUID(),description:'Compra de peça',category:'maintenance',amount_cents:'50000',occurred_on:'2026-01-10',supplier_id:supplier,supplier_name:'Peças Cadastradas',document_number:'NF-456',issue:null,revision:'a'.repeat(32)};
const context={version:1,tenant_id:tenant,part_id:part,order_id:order,page:1,page_size:30,search:'',total:1,source:{id:part,order_id:order,order_number:'OS-1',order_status:'completed',description:'Peça',quantity:'2.00',unit_cost_cents:'25000',total_cost_cents:'50000',stock_item_id:null,stock_movement_id:null},active_link:null,history:{total:0,rows:[]},candidates:[row]};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(context);mock.submit.mockResolvedValue({part_id:part,order_id:order});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><MaintenanceDirectPartAssociationWorkspace tenant={tenant} actor={actor} part={part}/></QueryClientProvider>);}
async function choose(){fireEvent.click(await screen.findByRole('radio'));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de compra direta'),{target:{value:'Compra direta e documento conferidos'}});}
function fields(quantity='2',document='NF-456'){fireEvent.change(screen.getByLabelText('Quantidade da compra direta'),{target:{value:quantity}});fireEvent.change(screen.getByLabelText('Documento da compra direta'),{target:{value:document}});}
async function prepare(){await choose();fields();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de compra direta'}));}
it('requires quantity document and direct purchase declaration and recovers original after uncertain reply',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await choose();fields('3','wrong');fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'Revisar associação ou correção de compra direta'})).toBeDisabled();fields();fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de compra direta'}));expect(mock.submit).not.toHaveBeenCalled();expect(screen.getByText(/quantidade 2, documento NF-456/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de compra direta'}));await screen.findByText(/pedido original foi preservado/);const original=mock.submit.mock.calls[0][0];expect(original.command).toMatchObject({part_id:part,cost_id:cost,classification:'direct_purchase',quantity:'2',document_number:'NF-456',same_part_confirmed:true});view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar associação ou correção de compra direta'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('blocks storage corruption and stock consumption',async()=>{sessionStorage.setItem(key,'broken');open();await screen.findByText(/recuperar o pedido/);expect(await screen.findByRole('radio')).toBeDisabled();cleanup();sessionStorage.clear();mock.read.mockResolvedValue({...context,source:{...context.source,stock_movement_id:crypto.randomUUID()}});open();await screen.findByText(/Consumo não pode ser associado/);expect(await screen.findByRole('radio')).toBeDisabled();});
it('rejects changed document/supplier preview and hides stale options on failure',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await prepare();mock.read.mockResolvedValue({...context,candidates:[{...row,document_number:'NEW',supplier_id:crypto.randomUUID(),revision:'b'.repeat(32)}]});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-maintenance-direct-part-context']});});await screen.findByText(/contexto mudou/);expect(screen.getByRole('button',{name:'Confirmar associação ou correção de compra direta'})).toBeDisabled();mock.read.mockRejectedValueOnce(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-maintenance-direct-part-context']});});await screen.findByRole('alert');expect(screen.queryByRole('radio')).not.toBeInTheDocument();});
it('releases editing after first known rollback and preserves reversal authorship',async()=>{mock.submit.mockRejectedValueOnce(new MaintenanceDirectPartRejectedError('finance_maintenance_direct_part_changed'));open();await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de compra direta'}));await screen.findByText(/A peça, o custo ou seu fornecedor mudaram/);await waitFor(()=>expect(sessionStorage.getItem(key)).toBeNull());expect(await screen.findByRole('radio')).not.toBeDisabled();cleanup();const active={id:link,cost_id:cost,supplier_id:supplier,amount_cents:'50000',actor_id:actor,actor_name:'Maria',reason:'Compra direta conferida',created_at:'2026-01-10'};mock.read.mockResolvedValue({...context,active_link:active,history:{total:1,rows:[{...active,reversal:null}]}});open();fireEvent.click(await screen.findByRole('button',{name:'Desfazer associação ativa'}));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de compra direta'),{target:{value:'Correção do vínculo da compra direta'}});fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de compra direta'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de compra direta'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toMatchObject({kind:'reverse',command:{link_id:link}});expect(screen.getAllByText(/Maria/).length).toBeGreaterThan(0);});
