import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {MaintenanceCostContextWorkspace} from '@/components/financial/MaintenanceCostContextPanel';
const mock=vi.hoisted(()=>({read:vi.fn()}));vi.mock('@/lib/financial/maintenanceCostContextClient',()=>({readMaintenanceCostContext:mock.read}));
const part={id:'part-1',stock_item_id:'item-1',stock_movement_id:'stock-1',description:'Peça declarada',quantity:'2.00',unit_cost_cents:'1000',total_cost_cents:'2000',issues:['part_stock_mismatch']};
const context={page:1,page_size:30,header:{id:'order-1',order_number:'OS-1',status:'open',opened_on:null,description:'Manutenção antiga',supplier_name:null,parts_cents:'2000',labor_cents:'1000',total_cents:'3000',issues:['header_parts_mismatch']},parts:{total:31,rows:[part]},stock:{total:1,rows:[{id:'stock-1',stock_item_id:'item-1',maintenance_order_id:'other-order',movement_type:'exit',quantity:null,unit_cost_cents:null,total_cost_cents:null,occurred_on:null,issues:['stock_order_mismatch','stock_movement_not_a_payment']}]}};
beforeEach(()=>{vi.clearAllMocks();mock.read.mockResolvedValue(context);});afterEach(()=>cleanup());
function open(){return render(<QueryClientProvider client={new QueryClient()}><MaintenanceCostContextWorkspace tenant="tenant" actor="actor" order="order-1"/></QueryClientProvider>);}
it('separates header parts and physical stock, showing IDs and review without decisions',async()=>{open();await screen.findByText('Cabeçalho declarado: OS-1');expect(screen.getByLabelText('Peças registradas na OS')).toBeInTheDocument();expect(screen.getByLabelText('Movimentos de estoque relacionados')).toBeInTheDocument();expect(screen.getByText(/total de todas as peças registradas difere/)).toBeInTheDocument();expect(screen.getByText(/Não some essas três representações/)).toBeInTheDocument();expect(screen.getByText('OS referenciada: other-order')).toBeInTheDocument();expect(screen.getByText(/Quantidade declarada: Não determinada/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Confirmar|Aprovar|Pagar/})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Associar mão de obra a custo existente'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Próximos componentes'}));await waitFor(()=>expect(mock.read).toHaveBeenLastCalledWith('tenant','order-1',2));});
it('hides previous components after a failed refresh without assuming empty inventory',async()=>{open();await screen.findByText('Cabeçalho declarado: OS-1');mock.read.mockRejectedValueOnce(new Error('offline'));fireEvent.click(screen.getByRole('button',{name:'Atualizar componentes da OS'}));await screen.findByRole('alert');expect(screen.queryByText('Cabeçalho declarado: OS-1')).not.toBeInTheDocument();expect(screen.queryByText('Nenhuma peça nesta página.')).not.toBeInTheDocument();});
