import {beforeEach,it,expect,vi} from 'vitest';
import {readMaintenanceCostContext} from '@/lib/financial/maintenanceCostContextClient';
import {maintenanceCostContextSchema} from '@/lib/financial/maintenanceCostContextContract';
const mock=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mock.rpc}}));
const tenant=crypto.randomUUID(),order=crypto.randomUUID();
const context={version:1,tenant_id:tenant,order_id:order,page:2,page_size:30,revision:'a'.repeat(32),coverage_complete:false,recognized_cost_cents:null,header:{id:order,order_number:'OS-1',status:'open',opened_on:null,description:null,supplier_name:null,parts_cents:null,labor_cents:'10000',total_cents:null,issues:['invalid_date','invalid_declared_value']},parts:{total:1001,rows:[]},stock:{total:0,rows:[]}};
beforeEach(()=>vi.clearAllMocks());
it('reads an unbounded count with explicit page and keeps indeterminate values',async()=>{mock.rpc.mockResolvedValueOnce({data:context,error:null});expect((await readMaintenanceCostContext(tenant,order,2)).parts.total).toBe(1001);expect(mock.rpc).toHaveBeenCalledWith('get_finance_maintenance_cost_context',{_tenant_id:tenant,_order_id:order,_page:2});expect(context.recognized_cost_cents).toBeNull();});
it('rejects claimed recognition/completeness, duplicate component IDs and incompatible order',async()=>{expect(maintenanceCostContextSchema.safeParse({...context,recognized_cost_cents:'0'}).success).toBe(false);expect(maintenanceCostContextSchema.safeParse({...context,coverage_complete:true}).success).toBe(false);expect(maintenanceCostContextSchema.safeParse({...context,header:{...context.header,id:crypto.randomUUID()}}).success).toBe(false);const part={id:crypto.randomUUID(),stock_item_id:null,stock_movement_id:null,description:'Peça',quantity:'1.50',unit_cost_cents:'200',total_cost_cents:'300',issues:[]};expect(maintenanceCostContextSchema.safeParse({...context,parts:{total:2,rows:[part,part]}}).success).toBe(false);mock.rpc.mockResolvedValueOnce({data:{...context,tenant_id:crypto.randomUUID()},error:null});await expect(readMaintenanceCostContext(tenant,order,2)).rejects.toThrow();});
