import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {MaintenanceLaborAssociationWorkspace} from '@/components/financial/MaintenanceLaborAssociation';
import {MaintenanceLaborRejectedError} from '@/lib/financial/maintenanceLaborAssociationClient';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/maintenanceLaborAssociationClient',()=>({readMaintenanceLaborAssociation:mock.read,submitMaintenanceLaborAssociation:mock.submit,MaintenanceLaborRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),order=crypto.randomUUID(),cost=crypto.randomUUID(),link=crypto.randomUUID(),key=`finance-maintenance-labor-association:${tenant}:${actor}:${order}`;
const row={cost_id:cost,batch_id:crypto.randomUUID(),description:'Combustível da viagem',category:'fuel',amount_cents:'50000',occurred_on:'2026-01-10',supplier_id:crypto.randomUUID(),supplier_name:'Oficina Cadastrada',issue:null,revision:'a'.repeat(32)};
const context={version:1,tenant_id:tenant,order_id:order,page:1,page_size:30,search:'',total:1,source:{id:order,trip_id:crypto.randomUUID(),driver_id:crypto.randomUUID(),order_number:'OS-1',status:'completed',labor_cents:'50000',supplier_name:'Texto antigo',opened_on:'2026-01-10'},active_link:null,history:{total:0,rows:[]},candidates:[row]};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(context);mock.submit.mockResolvedValue({order_id:order});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><MaintenanceLaborAssociationWorkspace tenant={tenant} actor={actor} order={order}/></QueryClientProvider>);}
async function prepare(){fireEvent.click(await screen.findByRole('radio'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de mão de obra'),{target:{value:'Duas origens do mesmo gasto conferidas'}});fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de mão de obra'}));}
it('requires identity declaration and review, preserves exact request after lost response',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();fireEvent.click(await screen.findByRole('radio'));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de mão de obra'),{target:{value:'Conferência integral da origem'}});expect(screen.getByRole('button',{name:'Revisar associação ou correção de mão de obra'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de mão de obra'}));expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de mão de obra'}));await screen.findByText(/pedido original foi preservado/);const original=mock.submit.mock.calls[0][0];expect(original.command.same_labor_confirmed).toBe(true);view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar associação ou correção de mão de obra'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('blocks corrupted or wrong-origin saved storage',async()=>{sessionStorage.setItem(key,JSON.stringify({actor,order:'wrong',pending:{}}));open();await screen.findByText(/Novas associações e correções estão bloqueadas/);expect(await screen.findByRole('radio')).toBeDisabled();expect(mock.submit).not.toHaveBeenCalled();});
it('rejects changed preview and hides stale options on error',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await prepare();mock.read.mockRejectedValueOnce(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-maintenance-labor-context']});});await screen.findByRole('alert');expect(screen.queryByRole('radio')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Confirmar associação ou correção de mão de obra'})).not.toBeInTheDocument();expect(mock.submit).not.toHaveBeenCalled();});
it('known first rejection releases editing while historical reversal retains audit',async()=>{mock.submit.mockRejectedValueOnce(new MaintenanceLaborRejectedError('finance_maintenance_labor_changed'));open();await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de mão de obra'}));await screen.findByText(/dados da OS, custo ou fornecedor mudaram/);await waitFor(()=>expect(sessionStorage.getItem(key)).toBeNull());expect(await screen.findByRole('radio')).not.toBeDisabled();});
it('reverses only the active association with permanent authorship',async()=>{const active={id:link,cost_id:cost,amount_cents:'50000',supplier_id:row.supplier_id,actor_id:actor,actor_name:'Maria financeira',reason:'Identidade conferida anteriormente',created_at:'2026-01-10T12:00:00Z'};mock.read.mockResolvedValue({...context,active_link:active,history:{total:1,rows:[{...active,reversal:null}]}});open();fireEvent.click(await screen.findByRole('button',{name:'Desfazer associação ativa'}));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de mão de obra'),{target:{value:'Correção de origem escolhida incorretamente'}});fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de mão de obra'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de mão de obra'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(1));expect(mock.submit.mock.calls[0][0]).toMatchObject({kind:'reverse',command:{link_id:link}});expect(screen.getAllByText(/Maria financeira/).length).toBeGreaterThan(0);});

it('keeps OS supplier text distinct, blocks missing supplier ID and invalidates changed supplier preview',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await prepare();expect(screen.getByText(/Fornecedor escrito na OS: Texto antigo/)).toBeInTheDocument();expect(screen.getByText(/fornecedor Oficina Cadastrada/)).toBeInTheDocument();mock.read.mockResolvedValue({...context,candidates:[{...row,supplier_id:crypto.randomUUID(),supplier_name:'Outro fornecedor',revision:'b'.repeat(32)}]});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-maintenance-labor-context']});});await screen.findByText(/contexto mudou/);expect(screen.getByRole('button',{name:'Confirmar associação ou correção de mão de obra'})).toBeDisabled();cleanup();mock.read.mockResolvedValue({...context,candidates:[{...row,supplier_id:null,supplier_name:null}]});open();expect(await screen.findByRole('radio')).toBeDisabled();});
it('applies literal search and resets the candidate page without automatic selection',async()=>{mock.read.mockResolvedValue({...context,total:31});open();await screen.findByRole('radio');fireEvent.click(screen.getByRole('button',{name:'Próximos vínculos'}));await waitFor(()=>expect(mock.read).toHaveBeenLastCalledWith(tenant,order,2,''));fireEvent.change(screen.getByLabelText('Buscar custo de mão de obra'),{target:{value:'Oficina 100%'}});fireEvent.click(screen.getByRole('button',{name:'Buscar custos'}));await waitFor(()=>expect(mock.read).toHaveBeenLastCalledWith(tenant,order,1,'Oficina 100%'));expect(await screen.findByRole('radio')).not.toBeChecked();});
