import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {ManualExpenseCancellationWorkspace} from '@/components/financial/ManualExpenseCancellationReview';
import {ManualExpenseCancellationRejectedError} from '@/lib/financial/manualExpenseCancellationClient';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));
vi.mock('@/lib/financial/manualExpenseCancellationClient',()=>({readManualExpenseCancellation:mock.read,submitManualExpenseCancellation:mock.submit,ManualExpenseCancellationRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),expense=crypto.randomUUID(),key=`finance-manual-expense-cancellation:${tenant}:${actor}:${expense}`;
const preview={version:1,tenant_id:tenant,payable_id:expense,revision:'a'.repeat(32),eligible:true,issue:null,can_execute:true,original_request_id:crypto.randomUUID(),snapshot:{payable:{id:expense,tenant_id:tenant,description:'Lanche registrado duas vezes',category:'food',supplier_name:'Fornecedor'},command:null,evidence:[]},cancellation:null,effects:{cost_removed_cents:'2500',obligation_cancelled_cents:'2500',cash_changed:false}};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(preview);mock.submit.mockResolvedValue({confirmed:true});});afterEach(cleanup);
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><ManualExpenseCancellationWorkspace tenant={tenant} actor={actor} payableId={expense}/></QueryClientProvider>);}
async function review(){fireEvent.change(await screen.findByLabelText('Motivo do cancelamento'),{target:{value:'Gasto duplicado confirmado com recibo'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar cancelamento da despesa avulsa'}));}
it('requires review and preserves original command after uncertain response and remount',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await review();expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar cancelamento da despesa avulsa'}));await screen.findByText(/Não foi possível confirmar a resposta/);const original=mock.submit.mock.calls[0][0];view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar cancelamento da despesa avulsa'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);expect(sessionStorage.getItem(key)).toBeNull();});
it('unlocks a first known rollback but preserves previously uncertain requests',async()=>{mock.submit.mockRejectedValueOnce(new ManualExpenseCancellationRejectedError('finance_manual_expense_cancellation_changed'));open();await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar cancelamento da despesa avulsa'}));await screen.findByText(/A despesa mudou/);expect(sessionStorage.getItem(key)).toBeNull();expect(await screen.findByLabelText('Motivo do cancelamento')).toHaveValue('Gasto duplicado confirmado com recibo');});
it('blocks corrupted storage and hides stale data after query failure',async()=>{sessionStorage.setItem(key,'broken');const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await screen.findByText(/Novos cancelamentos estão bloqueados/);expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();mock.read.mockRejectedValue(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-manual-expense-cancellation']});});expect(await screen.findByText(/Não foi possível consultar a despesa avulsa/)).toBeInTheDocument();expect(screen.queryByText(/Custo a retirar/)).not.toBeInTheDocument();});
it('shows cancelled original with manual author and reason and no new action',async()=>{mock.read.mockResolvedValue({...preview,eligible:false,issue:'finance_manual_expense_already_cancelled',cancellation:{id:crypto.randomUUID(),actor_id:actor,actor_name:'Maria',reason:'Duplicidade conferida',created_at:'2026-09-10'}});open();await screen.findByText(/Cancelamento manual por Maria/);expect(screen.getByText('Motivo: Duplicidade conferida')).toBeInTheDocument();expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();});
it('blocks confirmation when authoritative revision changes',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await review();mock.read.mockResolvedValue({...preview,revision:'b'.repeat(32)});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-manual-expense-cancellation']});});expect(await screen.findByRole('button',{name:'Confirmar cancelamento da despesa avulsa'})).toBeDisabled();});

it('keeps a previously uncertain command even when retry returns a known rejection',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout')).mockRejectedValueOnce(new ManualExpenseCancellationRejectedError('finance_manual_expense_cancellation_changed'));open();await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar cancelamento da despesa avulsa'}));await screen.findByText(/Não foi possível confirmar a resposta/);const saved=sessionStorage.getItem(key);fireEvent.click(screen.getByRole('button',{name:'Retomar cancelamento da despesa avulsa'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(sessionStorage.getItem(key)).toBe(saved);expect(screen.getByRole('button',{name:'Retomar cancelamento da despesa avulsa'})).toBeInTheDocument();});
