import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {MovementVoidConfirmation} from '@/components/financial/MovementVoidConfirmation';
import type {MovementCorrectionPreview} from '@/lib/financial/movementCorrectionPreviewContract';
const send=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/movementVoidCommandClient',()=>({submitMovementVoid:send,MovementVoidRejectedError:class extends Error{}}));
import {MovementVoidRejectedError} from '@/lib/financial/movementVoidCommandClient';
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),movementId=crypto.randomUUID(),account=crypto.randomUUID();
const originalRequest=crypto.randomUUID();
const effects={account_id:account,occurred_on:'2026-09-01',inflow_delta_cents:'0',outflow_delta_cents:'-100',balance_delta_cents:'100'};
const preview={tenant_id:tenant,movement_id:movementId,revision:'a'.repeat(32),eligible:true,can_execute:true,origin:{original_request_id:originalRequest},effects} as MovementCorrectionPreview;
function mount(value:MovementCorrectionPreview|null=preview,movement=movementId){return render(<QueryClientProvider client={new QueryClient()}><MovementVoidConfirmation key={movement} tenant={tenant} actor={actor} movementId={movement} preview={value??undefined}/></QueryClientProvider>);}
function prepare(){fireEvent.change(screen.getByLabelText('Motivo da invalidação'),{target:{value:'Registro incluído por engano'}});fireEvent.click(screen.getByText('Revisar invalidação'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar invalidação'));}
afterEach(()=>{cleanup();localStorage.clear();send.mockReset();});
it('preserves exact request across lost response, remount and a later known rejection',async()=>{send.mockRejectedValueOnce(Error('offline')).mockRejectedValueOnce(new MovementVoidRejectedError('finance_movement_correction_changed'));mount();prepare();await screen.findByText(/Não foi possível confirmar o resultado/);const original=send.mock.calls[0][0];cleanup();mount(null);fireEvent.click(screen.getByText('Retomar pedido de invalidação'));await screen.findByText(/O movimento ou seus vínculos mudaram/);expect(send.mock.calls[1][0]).toEqual(original);expect(screen.getByText('Retomar pedido de invalidação')).toBeInTheDocument();expect(screen.queryByLabelText('Motivo da invalidação')).not.toBeInTheDocument();});
it('unlocks a known first rejection and never reuses the request for another movement',async()=>{send.mockRejectedValueOnce(new MovementVoidRejectedError('finance_movement_correction_blocked'));mount();prepare();await screen.findByText(/O movimento possui impedimentos/);expect(screen.getByLabelText('Motivo da invalidação')).toBeInTheDocument();expect(localStorage.length).toBe(0);cleanup();mount(null,crypto.randomUUID());expect(screen.queryByText('Retomar pedido de invalidação')).not.toBeInTheDocument();});
it('hides confirmation on stale preview and blocks corrupt stored requests',()=>{mount(null);expect(screen.queryByText('Revisar invalidação')).not.toBeInTheDocument();cleanup();localStorage.setItem(`finance-movement-void:${tenant}:${actor}:${movementId}`,'{bad');mount();expect(screen.getByText(/pedido salvo está inconsistente/)).toBeInTheDocument();expect(send).not.toHaveBeenCalled();});
it('does not acknowledge a response with a different actor or effect',async()=>{send.mockResolvedValue({actor_id:crypto.randomUUID(),effects});mount();prepare();await screen.findByText(/Não foi possível confirmar o resultado/);expect(screen.getByText('Retomar pedido de invalidação')).toBeInTheDocument();});
it('acknowledges matching confirmation and clears the durable request',async()=>{send.mockResolvedValue({original_request_id:originalRequest,actor_id:actor,actor_name:'Gestor',created_at:'2026-09-10',reason:'Registro incluído por engano',effects});mount();prepare();await screen.findByText(/Registro invalidado por Gestor/);expect(localStorage.length).toBe(0);});

it('does not overwrite a request saved by another tab before submission',async()=>{mount();const other={actor,original_request_id:originalRequest,command:{version:1,tenant_id:tenant,movement_id:movementId,request_id:crypto.randomUUID(),revision:'a'.repeat(32),reason:'Pedido de outra aba preservado'},effects};localStorage.setItem(`finance-movement-void:${tenant}:${actor}:${movementId}`,JSON.stringify(other));prepare();await screen.findByText(/outro pedido já está salvo/);expect(send).not.toHaveBeenCalled();expect(JSON.parse(localStorage.getItem(`finance-movement-void:${tenant}:${actor}:${movementId}`)!)).toEqual(other);});
it('preserves another tab request arriving while confirmation is in flight',async()=>{let resolve!:(value:unknown)=>void;send.mockImplementation(()=>new Promise(done=>{resolve=done;}));mount();prepare();const key=`finance-movement-void:${tenant}:${actor}:${movementId}`,other=JSON.parse(localStorage.getItem(key)!);other.command.request_id=crypto.randomUUID();localStorage.setItem(key,JSON.stringify(other));resolve({original_request_id:originalRequest,actor_id:actor,actor_name:'Gestor',created_at:'2026-09-10',reason:'Registro incluído por engano',effects});await screen.findByText(/Registro invalidado por Gestor/);expect(JSON.parse(localStorage.getItem(key)!)).toEqual(other);});
it('reports refresh failure separately after confirmed success',async()=>{const cache=new QueryClient();vi.spyOn(cache,'invalidateQueries').mockRejectedValue(Error('cache'));send.mockResolvedValue({original_request_id:originalRequest,actor_id:actor,actor_name:'Gestor',created_at:'2026-09-10',reason:'Registro incluído por engano',effects});render(<QueryClientProvider client={cache}><MovementVoidConfirmation tenant={tenant} actor={actor} movementId={movementId} preview={preview}/></QueryClientProvider>);prepare();await screen.findByText(/as listas não foram atualizadas/);expect(screen.getByText(/Registro invalidado por Gestor/)).toBeInTheDocument();expect(localStorage.length).toBe(0);});

it('preserves the request when the original recording request differs',async()=>{send.mockResolvedValue({original_request_id:crypto.randomUUID(),actor_id:actor,effects});mount();prepare();await screen.findByText(/Não foi possível confirmar o resultado/);expect(screen.getByText('Retomar pedido de invalidação')).toBeInTheDocument();});
