import {beforeEach,it,expect,vi} from 'vitest';
import {submitMovementVoid,MovementVoidRejectedError} from '@/lib/financial/movementVoidCommandClient';
import {movementVoidResultSchema} from '@/lib/financial/movementVoidCommandContract';
const rpc=vi.hoisted(()=>vi.fn());vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc}}));beforeEach(()=>rpc.mockReset());
function fixture(){const command={version:1 as const,tenant_id:crypto.randomUUID(),request_id:crypto.randomUUID(),movement_id:crypto.randomUUID(),revision:'a'.repeat(32),reason:'  Registro conferido e invalidado  '};const result={version:1,tenant_id:command.tenant_id,request_id:command.request_id,movement_id:command.movement_id,original_request_id:crypto.randomUUID(),correction_id:crypto.randomUUID(),kind:'void',confirmed:true,bank_money_transacted:false,recorded_balance_changed:true,actor_id:crypto.randomUUID(),actor_name:'Financeiro QA',reason:command.reason.trim(),created_at:'2026-09-10T12:00:00+00:00',effects:{computation:'prospective_invalidation',bank_money_transacted:false,recorded_balance_changed:true,account_id:crypto.randomUUID(),occurred_on:'2026-09-01',inflow_delta_cents:'0',outflow_delta_cents:'-5000',balance_delta_cents:'5000'}};return{command,result};}
it('sends the unchanged durable command and validates the scoped confirmation',async()=>{const {command,result}=fixture();rpc.mockResolvedValue({data:result,error:null});expect(await submitMovementVoid(command)).toEqual(result);expect(rpc).toHaveBeenCalledExactlyOnceWith('void_finance_manual_movement',{_payload:command});});
it('distinguishes definite SQL rollback from an unknown transport outcome',async()=>{const {command}=fixture();rpc.mockResolvedValueOnce({data:null,error:{code:'40001',message:'finance_movement_correction_changed'}});await expect(submitMovementVoid(command)).rejects.toBeInstanceOf(MovementVoidRejectedError);rpc.mockRejectedValueOnce(new Error('network lost'));await expect(submitMovementVoid(command)).rejects.not.toBeInstanceOf(MovementVoidRejectedError);rpc.mockResolvedValueOnce({data:null,error:{code:'XX000',message:'unknown error'}});await expect(submitMovementVoid(command)).rejects.not.toBeInstanceOf(MovementVoidRejectedError);});
it('keeps wrong-identity or malformed replies uncertain instead of treating them as a rejection',async()=>{const {command,result}=fixture();for(const change of [{request_id:crypto.randomUUID()},{movement_id:crypto.randomUUID()},{tenant_id:crypto.randomUUID()},{reason:'Motivo de outro pedido'},{confirmed:false}]){rpc.mockResolvedValueOnce({data:{...result,...change},error:null});await expect(submitMovementVoid(command)).rejects.not.toBeInstanceOf(MovementVoidRejectedError);}});
it('rejects impossible monetary confirmations and validates malformed deltas without throwing during safeParse',()=>{const {result}=fixture();for(const change of [{inflow_delta_cents:'5000',outflow_delta_cents:'0',balance_delta_cents:'5000'},{inflow_delta_cents:'-100',outflow_delta_cents:'-5100',balance_delta_cents:'5000'},{inflow_delta_cents:'0',outflow_delta_cents:'-5000',balance_delta_cents:'4000'},{inflow_delta_cents:'0',outflow_delta_cents:'NaN',balance_delta_cents:'5000'}])expect(movementVoidResultSchema.safeParse({...result,effects:{...result.effects,...change}}).success).toBe(false);});
it('rejects invalid local payloads before issuing a request',async()=>{const {command}=fixture();await expect(submitMovementVoid({...command,reason:'x'})).rejects.toThrow();expect(rpc).not.toHaveBeenCalled();});
