import {act,cleanup,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,it,expect,vi} from 'vitest';
import {MovementCorrectionReviewWorkspace} from '@/components/financial/MovementCorrectionReview';
const mock=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/movementCorrectionPreviewClient',()=>({readMovementCorrectionPreview:mock}));
afterEach(cleanup);
it('shows conditional effects and source IDs without any execution action',async()=>{const tenant=crypto.randomUUID(),movement=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID();mock.mockResolvedValue({tenant_id:tenant,movement_id:movement,eligible:false,can_execute:false,origin:{verified:false,issue:'recording_origin_unproven',original_request_id:null,snapshot:{movement:{description:'Movimento para revisão',beneficiary_name:'Fornecedor',occurred_on:'2026-09-01',amount_cents:50000,direction:'out',nature:'payment',bank_account_id:account,created_by:actor,created_at:'2026-09-01'},recording_events:[]}},void:null,blockers:[{code:'closed_period',source_table:'finance_account_period_dependencies',source_ids:[movement]}],readiness:{ready:false,missing:['guard']},dependencies:{finance_account_period_dependencies:[{source_id:movement,affected_from:'2026-09-01',affected_to:'2026-09-30'}]},effects:{account_id:account,occurred_on:'2026-09-01',inflow_delta_cents:'0',outflow_delta_cents:'-50000',balance_delta_cents:'50000'}});render(<QueryClientProvider client={new QueryClient()}><MovementCorrectionReviewWorkspace tenant={tenant} actor={actor} movementId={movement}/></QueryClientProvider>);await screen.findByText('Movimento para revisão · Fornecedor');expect(screen.getByText(/Variação do saldo representado: R\$ 500,00/)).toBeInTheDocument();expect(screen.getByText(/não uma correção realizada/)).toBeInTheDocument();expect(screen.getByText(/2026-09-01 a 2026-09-30/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Confirmar|Invalidar|Substituir/})).not.toBeInTheDocument();expect(mock).toHaveBeenCalledWith(tenant,movement);});

it('hides cached eligibility and effects while updating and after a query error',async()=>{const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),movement=crypto.randomUUID(),cache=new QueryClient({defaultOptions:{queries:{retry:false}}});mock.mockResolvedValue({eligible:true,origin:{verified:true,issue:null,original_request_id:crypto.randomUUID(),snapshot:{movement:{description:'Prévia elegível',beneficiary_name:'Fornecedor',occurred_on:'2026-09-01',amount_cents:100,direction:'out',nature:'other',bank_account_id:crypto.randomUUID(),created_by:actor,created_at:'2026-09-01'},recording_events:[]}},void:null,blockers:[],readiness:{ready:true,missing:[]},dependencies:{},effects:{account_id:crypto.randomUUID(),occurred_on:'2026-09-01',inflow_delta_cents:'0',outflow_delta_cents:'-100',balance_delta_cents:'100'}});render(<QueryClientProvider client={cache}><MovementCorrectionReviewWorkspace tenant={tenant} actor={actor} movementId={movement}/></QueryClientProvider>);await screen.findByText(/A consulta não encontrou impedimentos/);let reject!:(error:Error)=>void;mock.mockImplementationOnce(()=>new Promise((_resolve,fail)=>{reject=fail;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-movement-correction-preview',tenant,actor,movement]});});await screen.findByText('Consultando origem, dependências e efeitos…');expect(screen.queryByText(/A consulta não encontrou impedimentos/)).not.toBeInTheDocument();expect(screen.queryByText(/Variação do saldo representado/)).not.toBeInTheDocument();await act(async()=>{reject(new Error('offline'));});await screen.findByText(/Nenhuma elegibilidade ou efeito foi presumido/);expect(screen.queryByText(/Prévia elegível/)).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Confirmar|Invalidar/})).not.toBeInTheDocument();});
