import {beforeEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {OpenComplementExtinctionWorkspace,OpenComplementExtinctionDetails} from '@/components/financial/OpenComplementExtinctionDialog';
import {OpenComplementExtinctionConfirmation} from '@/components/financial/OpenComplementExtinctionConfirmation';
import {ExpenseComplementExtinctionHistory} from '@/components/financial/ExpenseComplementExtinctionHistory';
import {extinctionIds as i,extinctionPreview,extinctionSuccess} from './helpers/openComplementExtinctionFixture';
const m=vi.hoisted(()=>({read:vi.fn(),send:vi.fn(),role:'admin'}));
vi.mock('@/lib/financial/openComplementExtinctionClient',()=>({readOpenComplementExtinction:m.read,sendOpenComplementExtinction:m.send}));
vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentRole:m.role})}));
vi.mock('@/lib/financial/invalidateAccountReview',()=>({invalidateAccountReview:vi.fn().mockResolvedValue(undefined)}));
beforeEach(()=>{cleanup();localStorage.clear();vi.clearAllMocks();m.role='admin';Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async<T,>(_key:string,work:()=>Promise<T>)=>work()}});});
function review(){fireEvent.change(screen.getByLabelText('Motivo da extinção'),{target:{value:'Custo conferido com documentos'}});fireEvent.click(screen.getByText('Revisar extinção do complemento'));fireEvent.click(screen.getByRole('checkbox'));}
it('shows cancelled historical nominal versus zero due and no fictitious debt at equality',()=>{render(<OpenComplementExtinctionDetails data={extinctionPreview('10000')}/>);expect(screen.getByText(/nominal histórico R\$ 50,00.*devido proposto R\$ 0,00/)).toBeInTheDocument();expect(screen.getByText(/não há excedente nem nova dívida/)).toBeInTheDocument();expect(screen.getByText(/Nenhum dinheiro será movimentado/)).toBeInTheDocument();});
it('requires explicit source application and invalidates the checked proposal on editing',async()=>{const p=extinctionPreview();m.read.mockResolvedValueOnce({...p,eligible:false,can_execute:false,proposal:{amount_cents:'8000',dispositions:[]},dispositions:p.dispositions.map(d=>({...d,applied_cents:'0',residual_cents:'10000'}))}).mockResolvedValueOnce(p);render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><OpenComplementExtinctionWorkspace tenant={i.tenant} actor={i.actor} chargeId={i.charge}/></QueryClientProvider>);fireEvent.change(screen.getByLabelText('Custo corrigido (R$)'),{target:{value:'80'}});fireEvent.click(screen.getByText('Consultar fontes do custo'));await screen.findByLabelText('Valor aplicado da fonte 1');expect(screen.queryByLabelText('Motivo da extinção')).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Valor aplicado da fonte 1'),{target:{value:'80'}});fireEvent.click(screen.getByText('Conferir aplicação e saldos pendentes'));await screen.findByLabelText('Motivo da extinção');expect(m.read.mock.calls[1][3].dispositions).toEqual(p.proposal.dispositions);fireEvent.change(screen.getByLabelText('Valor aplicado da fonte 1'),{target:{value:'70'}});await waitFor(()=>expect(screen.queryByLabelText('Motivo da extinção')).not.toBeInTheDocument());expect(m.send).not.toHaveBeenCalled();});
it('recovers exact excess/responsibility after uncertain reply and keeps confirmed state on refresh failure',async()=>{m.send.mockRejectedValueOnce(new Error('lost')).mockImplementationOnce(async c=>extinctionSuccess(c));const p=extinctionPreview(),refresh=vi.fn().mockRejectedValue(new Error('cache'));const view=render(<OpenComplementExtinctionConfirmation tenant={i.tenant} actor={i.actor} chargeId={i.charge} preview={p} canConfirm refresh={refresh}/>);review();expect(screen.getByText(/saldo de R\$ 20,00/)).toBeInTheDocument();fireEvent.click(screen.getByText('Confirmar extinção do complemento'));await screen.findByText('Recuperar extinção do complemento');view.rerender(<OpenComplementExtinctionConfirmation tenant={i.tenant} actor={i.actor} chargeId={i.charge} preview={undefined} canConfirm refresh={refresh}/>);expect(screen.getByText(/responsável/)).toHaveTextContent(i.responsible);fireEvent.click(screen.getByText('Recuperar extinção do complemento'));await screen.findByText(/Complemento cancelado para a descarga/);expect(m.send.mock.calls[1][0]).toEqual(m.send.mock.calls[0][0]);expect(screen.getByRole('alert')).toHaveTextContent('foi confirmada');expect(screen.queryByText('Confirmar extinção do complemento')).not.toBeInTheDocument();});
it('keeps manual author reason history and refuses operator confirmation',()=>{const p=extinctionPreview();render(<OpenComplementExtinctionConfirmation tenant={i.tenant} actor={i.actor} chargeId={i.charge} preview={p} canConfirm={false} refresh={vi.fn()}/>);expect(screen.queryByLabelText('Motivo da extinção')).not.toBeInTheDocument();render(<ExpenseComplementExtinctionHistory value={{id:crypto.randomUUID(),regularization_id:crypto.randomUUID(),request_id:crypto.randomUUID(),actor_id:i.actor,reason:'Documento da extinção',created_at:'2026-09-11T10:00:00Z',cancelled_nominal_cents:'5000',residual_cents:'2000'}}/>);expect(screen.getByText(/Autor/)).toHaveTextContent(i.actor);expect(screen.getByText('Motivo: Documento da extinção')).toBeInTheDocument();expect(screen.getByText(/Devoluções posteriores/)).toBeInTheDocument();});
