// @vitest-environment node
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {installCashForecastCollectorSources} from './helpers/cashForecastCollectorDatabase';
import {openComplementExtinctionPreviewSchema,openComplementExtinctionResultSchema} from '@/lib/financial/openComplementExtinctionContract';
import {cashForecastCollectorSchema} from '@/lib/financial/cashForecastCollectorContract';
import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
import {createUnloadingCostCorrectionDatabase} from './helpers/unloadingCostCorrectionDatabase';
import {installExtinctionCoreScenario} from './helpers/openComplementExtinctionDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createUnloadingCostCorrectionDatabase>>;
const migration=()=>readFileSync('supabase/migrations/20260911094310_finance_open_complement_extinction_public_boundary.sql','utf8');
beforeAll(async()=>{db=await createUnloadingCostCorrectionDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});
afterEach(async()=>db.exec('rollback'));afterAll(async()=>db.close());
async function setup(){const s=await installExtinctionCoreScenario(db);if(process.env.CAPTURE_EXTINCTION_PUBLIC==='1'){const functions=(await db.query("select p.oid::regprocedure::text signature,md5(replace(p.prosrc,E'\\r\\n',E'\\n')) prosrc_md5,p.prosecdef,p.provolatile,p.proconfig,p.proacl::text acl from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='finance_private' and p.proname in('open_complement_before_extinction','open_complement_extinction_context','extinguish_open_unloading_complement','consume_complement_extinction_ticket','expense_cost_before_returns','expense_cost_effective','expense_cost_coverage','guard_open_complement_source','cost_before_extinction_returns','expense_cost_before_open_complement','guard_cost_regularization_source','guard_effective_unloading_cost','guard_payable_revision_approval','check_open_complement_chain') order by signature")).rows;const triggers=(await db.query("select tgname,tgrelid::regclass::text relation,tgfoid::regprocedure::text function,tgtype,tgenabled,tgdeferrable,tginitdeferred,tgnargs,pg_get_expr(tgqual,tgrelid) qual from pg_trigger where tgname in('zz_complement_extinction_ticket','check_complement_extinction','preserve_complement_extinction','a_open_complement_payable','a_open_complement_covered_cost','a_payable_revision_approval','finance_effective_unloading_payable','a_cost_regularization_guard','cost_return_capacity','cost_return_chain') order by relation,tgname")).rows;writeFileSync('docs/qa/finance-complement-extinction-core-catalog-2026-09-11.json',JSON.stringify({functions,triggers},null,2)+'\n');}await db.exec(migration());return s;}

const base=()=>({version:1,tenant_id:i.tenant,request_id:randomUUID(),reason:'Extinguir complemento mantendo reserva e responsabilidade'});
async function preview(charge:string,proposal:unknown){const v=(await financeAs<{v:{revision:string,eligible:boolean,can_execute:boolean,tenant_id:string,actor_id:string,dispositions:Array<{source_kind:string,source_id:string,responsible_id:string,disposition_type:string,gross_reserved_cents:string}>,[key:string]:unknown}}>(db,i.operator,'select preview_finance_open_complement_extinction($1,$2,$3) v',[i.tenant,charge,proposal])).rows[0].v;expect(v).not.toHaveProperty('_evidence');return openComplementExtinctionPreviewSchema.parse(v);}
async function prepare(s:{unloading_id:string}){const discovery=await preview(s.unloading_id,{amount_cents:'8000',dispositions:[]});expect(discovery.can_execute).toBe(false);expect(discovery.dispositions).toHaveLength(1);const d=discovery.dispositions[0];expect(d.gross_reserved_cents).toBe('10000');const proposal={amount_cents:'8000',dispositions:[{source_kind:d.source_kind,source_id:d.source_id,responsible_id:d.responsible_id,disposition_type:d.disposition_type,applied_cents:'8000'}]};return {proposal,preview:await preview(s.unloading_id,proposal)};}
async function command(payload:unknown){return openComplementExtinctionResultSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select extinguish_finance_open_complement($1) v',[payload])).rows[0].v);}
it('discovers canonical sources and executes/replays the authenticated exact proposal',async()=>{const s=await setup();const ready=await prepare(s);expect(ready.preview).toMatchObject({can_execute:true,eligible:true,tenant_id:i.tenant,actor_id:i.operator});const payload={...base(),charge_id:s.unloading_id,expense_id:s.id,payable_id:s.payable_id,proposal:ready.proposal,revision:ready.preview.revision};const result=await command(payload);expect(result).toMatchObject({confirmed:true,actor_id:i.operator,payable_id:s.payable_id,payable_status:'cancelled',effects:{residual_cents:'2000',cash_changed:false,capacity_released_cents:'0'}});expect(await command(payload)).toEqual(result);await db.exec('set constraints all immediate');await expect(command({...payload,reason:'Outro texto para mesmo identificador'})).rejects.toMatchObject({code:'23505'});});
it('denies anon/private entry, tenant mismatch, mixed driver and revoked replay',async()=>{const s=await setup();const ready=await prepare(s);const payload={...base(),charge_id:s.unloading_id,expense_id:s.id,payable_id:s.payable_id,proposal:ready.proposal,revision:ready.preview.revision};await expect(financeAs(db,i.operator,'select finance_private.extinguish_open_unloading_complement($1)',[payload])).rejects.toMatchObject({code:'42501'});await expect(command({...payload,tenant_id:i.otherTenant})).rejects.toMatchObject({code:'42501'});await db.exec('savepoint anon;set role anon');await expect(db.query('select preview_finance_open_complement_extinction($1,$2,$3)',[i.tenant,s.unloading_id,ready.proposal])).rejects.toMatchObject({code:'42501'});await db.exec('rollback to savepoint anon');await db.exec('savepoint mixed');await db.query("insert into tenant_memberships(tenant_id,user_id,role,active) values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(command(payload)).rejects.toMatchObject({code:'42501'});await db.exec('rollback to savepoint mixed');await command(payload);await db.query('update tenant_memberships set active=false where tenant_id=$1 and user_id=$2',[i.tenant,i.operator]);await expect(command(payload)).rejects.toMatchObject({code:'42501'});});
it('rejects changed identity and exposes unavailable execution when dispatcher is revoked',async()=>{const s=await setup();const ready=await prepare(s);await expect(command({...base(),charge_id:s.unloading_id,expense_id:randomUUID(),payable_id:s.payable_id,proposal:ready.proposal,revision:ready.preview.revision})).rejects.toMatchObject({code:'40001'});await db.exec('revoke execute on function finance_private.dispatch_open_complement_extinction(jsonb) from authenticated');expect((await preview(s.unloading_id,ready.proposal)).can_execute).toBe(false);});
it('refuses promotion when exact trigger events or WHEN clause drift',async()=>{await installExtinctionCoreScenario(db);for(const ddl of ["drop trigger zz_complement_extinction_ticket on payables;create trigger zz_complement_extinction_ticket before delete on payables for each row execute function finance_private.consume_complement_extinction_ticket()","drop trigger zz_complement_extinction_ticket on payables;create trigger zz_complement_extinction_ticket before update on payables for each row when(false) execute function finance_private.consume_complement_extinction_ticket()","grant execute on function finance_private.extinguish_open_unloading_complement(jsonb) to authenticated"]){await db.exec('savepoint drift');await db.exec(ddl);await expect(db.exec(migration())).rejects.toMatchObject({code:'55000'});await db.exec('rollback to savepoint drift');}await db.exec(migration());});
it('keeps the cancelled historical nominal out of forecast future outflow with comparison90341 installed',async()=>{const s=await setup();await installCashForecastCollectorSources(db);for(const n of ['20260911084618_finance_cash_forecast_pure_projection','20260911084626_finance_cash_forecast_preserved_snapshots','20260911085621_finance_cash_forecast_public_readers','20260911090256_finance_cash_forecast_public_boundary','20260911090341_finance_cash_forecast_preserved_comparison'])await db.exec(readFileSync('supabase/migrations/'+n+'.sql','utf8'));const dates=(await db.query<{cutoff:string,end:string}>("select (current_date-1)::text cutoff,current_date::text end")).rows[0];const collect=async()=>cashForecastCollectorSchema.parse((await db.query<{v:unknown}>('select finance_private.cash_forecast_collect($1,$2,$3) v',[i.tenant,dates.cutoff,dates.end])).rows[0].v);const before=await collect();expect(before.origins.find(x=>x.source_id===s.payable_id)).toMatchObject({valid:true,nominal_cents:'5000',fulfilled_cents:'0'});const ready=await prepare(s);await command({...base(),charge_id:s.unloading_id,expense_id:s.id,payable_id:s.payable_id,proposal:ready.proposal,revision:ready.preview.revision});const after=await collect();expect(after.revision).not.toBe(before.revision);expect(after.origins.find(x=>x.source_id===s.payable_id)).toBeUndefined();expect((await db.query('select status,trunc(amount*100)::text nominal from payables where id=$1',[s.payable_id])).rows).toEqual([{status:'cancelled',nominal:'5000'}]);});
