// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {expect,it,vi} from 'vitest';
import {createPayableXmlOutbox,pendingPayableXml} from '@/lib/financial/payableXmlOutbox';
import {payableXmlMoney,type PayableXmlCommand} from '@/lib/financial/payableXmlContract';
const tenant=randomUUID(),actor=randomUUID();
const input={artifact_id:randomUUID(),payable_id:null,expected_revision:null,fields:{supplier_name:'Fornecedor NF-e',category:'supplier',description:'Parcela 1',amount_cents:'61728',due_date:'2026-09-30',competence_date:null,document_number:'123/1',status:'pending' as const,notes:null}};
function fixture(){const m=new Map<string,string>();const storage={getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>{m.set(k,v);},removeItem:(k:string)=>{m.delete(k);}};const send=vi.fn<(p:PayableXmlCommand)=>Promise<{data:unknown;error:unknown}>>();const assertContext=vi.fn();const box=createPayableXmlOutbox({storage,uuid:randomUUID,assertContext,changed:()=>{},lock:async<T>(_key:string,work:()=>Promise<T>)=>work(),send});return{box,storage,send,assertContext};}
const result=(p:PayableXmlCommand)=>({version:1,confirmed:true,tenant_id:tenant,actor_id:actor,request_id:p.request_id,payable_id:randomUUID(),artifact_id:p.artifact_id,link_id:randomUUID(),amount_cents:p.fields.amount_cents,original_preserved:true,cash_changed:false,fiscal_document_created:false});
it('persists exact reviewed installment before send and recovers an unknown result without a second request',async()=>{const f=fixture();f.send.mockImplementationOnce(async p=>{expect(pendingPayableXml(f.storage,tenant,actor)?.payload).toEqual(p);throw Error('network unknown');});await expect(f.box.submit(tenant,actor,input)).rejects.toThrow('unknown');const original=pendingPayableXml(f.storage,tenant,actor)!.payload;f.send.mockImplementationOnce(async p=>({data:result(p),error:null}));await f.box.recover(tenant,actor);expect(f.send.mock.calls[1][0]).toEqual(original);expect(pendingPayableXml(f.storage,tenant,actor)).toBeNull();});
it('does not clear another actor response or permit replacing a pending command',async()=>{const f=fixture();f.send.mockImplementation(async p=>({data:{...result(p),actor_id:randomUUID()},error:null}));await expect(f.box.submit(tenant,actor,input)).rejects.toThrow();expect(pendingPayableXml(f.storage,tenant,actor)).not.toBeNull();await expect(f.box.submit(tenant,actor,{...input,fields:{...input.fields,amount_cents:'1'}})).rejects.toThrow();expect(f.send).toHaveBeenCalledOnce();});
it('rejects impossible fiscal/money success claims and refuses stale-context cleanup',async()=>{const f=fixture();f.send.mockImplementation(async p=>({data:{...result(p),cash_changed:true},error:null}));await expect(f.box.submit(tenant,actor,input)).rejects.toThrow();expect(pendingPayableXml(f.storage,tenant,actor)).not.toBeNull();f.assertContext.mockImplementation(()=>{throw Error('workspace changed');});await expect(f.box.recover(tenant,actor)).rejects.toThrow('workspace changed');expect(f.send).toHaveBeenCalledOnce();});
it('converts cents exactly and rejects hidden fractional cents or nonfinite values',()=>{expect(payableXmlMoney('0.29')).toBe('29');expect(payableXmlMoney('617.28')).toBe('61728');for(const s of ['1.005','NaN','Infinity','0','9999999999999'])expect(()=>payableXmlMoney(s)).toThrow();});
