vi.mock('@/components/financial/PayableAccountPayment',()=>({PayableAccountPayment:()=>null}));
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
vi.mock('@/components/financial/PayableAccountPayment',()=>({PayableAccountPayment:()=>null}));
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,it,expect,vi} from 'vitest';
import PayablePaymentDialog from '@/components/financial/PayablePaymentDialog';
import type {Payable} from '@/hooks/usePayables';
const mock=vi.hoisted(()=>({history:vi.fn(),signed:vi.fn()}));
vi.mock('@/hooks/useFinancialPayments',()=>({usePayablePayments:mock.history,PAYMENT_METHOD_LABELS:{pix:'PIX'}}));vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentTenant:{id:'tenant'}})}));vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'actor'}})}));vi.mock('@/components/financial/PayableMovementLink',()=>({PayableMovementLink:()=>null}));vi.mock('@/components/financial/PayableLinkReversal',()=>({PayableLinkReversal:()=> <p>Reversão canônica</p>}));vi.mock('@/components/financial/LegacyPayableAssociation',()=>({LegacyPayableAssociation:()=> <p>Associação de pagamento antigo</p>}));afterEach(cleanup);
vi.mock('@/integrations/supabase/client',()=>({supabase:{storage:{from:()=>({createSignedUrl:mock.signed})}}}));
it('never offers canonical payment reversal for a legacy association and keeps its paid meaning',()=>{
 mock.history.mockReturnValue({data:{page_revision:'a'.repeat(32),total:3,rows:[{id:'old',amount:500,method:'pix',paid_at:'2026-01-10',link_id:'old-link',link_origin:'legacy_adoption',reversal:{actor_name:'Ana',created_at:'2026-02-02',reason:'Correção de associação'}},{id:'unlinked',amount:100,method:'pix',paid_at:'2026-01-10',link_origin:null},{id:'canonical',amount:300,method:'pix',paid_at:'2026-01-10',link_id:'new-link',link_origin:'canonical'}]},isFetching:false});
 render(<QueryClientProvider client={new QueryClient()}><PayablePaymentDialog payable={{id:'payable',supplier_name:'Fornecedor',amount:900} as Payable} open onOpenChange={()=>{}}/></QueryClientProvider>);expect(screen.getAllByText('Reversão canônica')).toHaveLength(1);expect(screen.getAllByText('Associação de pagamento antigo')).toHaveLength(2);expect(screen.getByText(/pagamento antigo foi preservado/)).toBeInTheDocument();expect(screen.queryByText('Esta baixa não compõe o total pago atual.')).not.toBeInTheDocument();
});
it('retries the payment history without closing the payable dialog',()=>{const refetch=vi.fn();mock.history.mockReturnValue({data:undefined,error:new Error('offline'),isFetching:false,refetch});render(<QueryClientProvider client={new QueryClient()}><PayablePaymentDialog payable={{id:'payable',supplier_name:'Fornecedor',amount:900} as Payable} open onOpenChange={()=>{}}/></QueryClientProvider>);expect(screen.getByRole('alert')).toHaveTextContent('Não foi possível carregar o histórico');fireEvent.click(screen.getByRole('button',{name:'Atualizar histórico'}));expect(refetch).toHaveBeenCalledTimes(1);});
it('keeps the first-page revision when requesting the next history page',()=>{const revision='b'.repeat(32);mock.history.mockReturnValue({data:{page_revision:revision,total:31,rows:[{id:'canonical',amount:300,method:'pix',paid_at:'2026-01-10',link_id:'new-link',link_origin:'canonical',reversal:null}]},isFetching:false,refetch:vi.fn()});render(<QueryClientProvider client={new QueryClient()}><PayablePaymentDialog payable={{id:'payable',supplier_name:'Fornecedor',amount:900} as Payable} open onOpenChange={()=>{}}/></QueryClientProvider>);fireEvent.click(screen.getByRole('button',{name:'Próxima'}));expect(mock.history).toHaveBeenLastCalledWith('payable',2,revision);});
it('creates a fresh private receipt URL on every click',async()=>{const path='tenant/payable-payments/proof.pdf',replace=vi.fn(),close=vi.fn();vi.spyOn(window,'open').mockReturnValue({opener:{},location:{replace},close} as unknown as Window);mock.signed.mockResolvedValue({data:{signedUrl:'https://signed.example/proof'},error:null});mock.history.mockReturnValue({data:{page_revision:'c'.repeat(32),total:1,rows:[{id:'canonical',tenant_id:'tenant',payable_id:'payable',amount:300,method:'pix',paid_at:'2026-01-10',notes:null,attachment_url:path,account_name:null,link_id:'new-link',movement_id:'movement',link_origin:'canonical',reversal:null}]},isFetching:false,refetch:vi.fn()});render(<QueryClientProvider client={new QueryClient()}><PayablePaymentDialog payable={{id:'payable',supplier_name:'Fornecedor',amount:900} as Payable} open onOpenChange={()=>{}}/></QueryClientProvider>);fireEvent.click(screen.getByRole('button',{name:'Abrir comprovante da baixa'}));await vi.waitFor(()=>expect(mock.signed).toHaveBeenCalledTimes(1));fireEvent.click(screen.getByRole('button',{name:'Abrir comprovante da baixa'}));await vi.waitFor(()=>expect(mock.signed).toHaveBeenCalledTimes(2));expect(mock.signed).toHaveBeenLastCalledWith(path,300);expect(replace).toHaveBeenCalledWith('https://signed.example/proof');});
