// @vitest-environment node
import {randomUUID,createHash} from 'node:crypto';
import {SaxesParser} from 'saxes';
import {beforeEach,expect,it,vi} from 'vitest';
import {inspectPayableXml,type PayableXmlReader} from '../../supabase/functions/finance-payable-xml/xml';
import {preservePayableXml} from '../../supabase/functions/finance-payable-xml/workflow';
import {payableNfeXml} from './helpers/payableNfeFixture';
import {preservePayableXmlFile,sendPayableXml} from '@/lib/financial/payableXmlClient';
const mock=vi.hoisted(()=>({rpc:vi.fn(),invoke:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mock.rpc,functions:{invoke:mock.invoke}}}));
const tenant=randomUUID(),actor=randomUUID(),request=randomUUID(),artifact=randomUUID(),bytes=new TextEncoder().encode(payableNfeXml),hash=createHash('sha256').update(bytes).digest('hex');
const summary=inspectPayableXml(bytes,()=>new SaxesParser({xmlns:true}) as unknown as PayableXmlReader);
const safe=(state='original_quarantined')=>({version:1,tenant_id:tenant,actor_id:actor,request_id:request,artifact_id:artifact,sha256:hash,size_bytes:bytes.length,state,summary:state==='reserved'?null:summary,signature_verified:false,antivirus_verified:false});
beforeEach(()=>vi.clearAllMocks());
it('uses the fixed service path and sends real parsed summary after upload, with no payable write in Edge',async()=>{let done=false;const caller=vi.fn(async()=>({data:safe(done?'original_quarantined':'reserved'),error:null}));const service=vi.fn(async(name:string,args:Record<string,unknown>)=>{if(name==='prepare_finance_payable_xml')return{data:{artifact:safe('reserved'),ticket:randomUUID(),bucket:'payable-xml-quarantine',path:`${tenant}/${actor}/${request}/original`},error:null};expect((args._payload as {summary:unknown}).summary).toEqual(summary);done=true;return{data:safe(),error:null};});const put=vi.fn(async(path:string,actual:Uint8Array)=>{expect(path).toBe(`${tenant}/${actor}/${request}/original`);expect(actual).toEqual(bytes);});const v=await preservePayableXml({tenant,actor,request,bytes},{caller,service,put,parser:()=>new SaxesParser({xmlns:true}) as unknown as PayableXmlReader});expect(v).toEqual(safe());expect(service.mock.calls.map(c=>c[0])).toEqual(['prepare_finance_payable_xml','finish_finance_payable_xml']);expect(JSON.stringify(v)).not.toMatch(/ticket|original_path/);});
it('does not finalize on storage failure',async()=>{const service=vi.fn(async()=>({data:{artifact:safe('reserved'),ticket:randomUUID(),bucket:'payable-xml-quarantine',path:`${tenant}/${actor}/${request}/original`},error:null}));await expect(preservePayableXml({tenant,actor,request,bytes},{caller:async()=>({data:safe('reserved'),error:null}),service,put:async()=>{throw Error('offline');},parser:()=>new SaxesParser({xmlns:true}) as unknown as PayableXmlReader})).rejects.toThrow('offline');expect(service).toHaveBeenCalledOnce();});
it('client preserves SDK receiver and same file request after an uncertain upload',async()=>{const client=(await import('@/integrations/supabase/client')).supabase;mock.rpc.mockImplementation(function(this:unknown){expect(this).toBe(client);return Promise.resolve({data:null,error:null});});await sendPayableXml({version:1,tenant_id:tenant,request_id:request,artifact_id:artifact,payable_id:null,expected_revision:null,fields:{supplier_name:'Emissor',category:'supplier',description:null,amount_cents:'123456',due_date:null,competence_date:null,document_number:null,status:'pending',notes:null}});const records=new Map<string,string>(),storage={getItem:(k:string)=>records.get(k)??null,setItem:(k:string,v:string)=>{records.set(k,v);}};const file=new File([bytes],'nota.xml',{type:'application/xml'});mock.invoke.mockResolvedValueOnce({data:null,error:Error('network')});await expect(preservePayableXmlFile(tenant,actor,file,storage)).rejects.toThrow('não foi salva');const previous=mock.invoke.mock.calls[0][1].body.get('request_id');mock.invoke.mockImplementationOnce(async(_name:string,args:{body:FormData})=>({data:{...safe(),request_id:args.body.get('request_id')},error:null}));await preservePayableXmlFile(tenant,actor,file,storage);expect(mock.invoke.mock.calls[1][1].body.get('request_id')).toBe(previous);expect(mock.invoke.mock.calls[1][1].body.get('file')).toBe(file);});
