// @vitest-environment node
import {payableXmlArtifactSchema,payableXmlResultSchema,payableXmlContextSchema} from '@/lib/financial/payableXmlContract';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {beforeAll,beforeEach,afterEach,afterAll,expect,it} from 'vitest';
import {createUploadQuarantineDatabase,quarantineMigration} from './helpers/uploadQuarantineDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createUploadQuarantineDatabase>>;
beforeAll(async()=>{db=await createUploadQuarantineDatabase();await db.exec(quarantineMigration);await db.exec('alter table storage.buckets add column if not exists allowed_mime_types text[]');const baseline=readFileSync('supabase/migrations/20260824224152_baseline.sql','utf8');const start=baseline.indexOf('CREATE OR REPLACE FUNCTION public.is_tenant_operator_or_admin(');await db.exec(baseline.slice(start,baseline.indexOf('$function$;',start)+11));await db.exec(readFileSync('supabase/migrations/20260914195721_finance_payable_xml_preserved_attachments.sql','utf8'));},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true),set_config('request.jwt.claims',$2,true),set_config('request.headers',$3,true)",[i.operator,JSON.stringify({active_tenant_id:i.tenant,role:'authenticated'}),JSON.stringify({'x-agvlog-tenant-id':i.tenant})]);});afterEach(async()=>db.exec('rollback'));afterAll(async()=>db?.close());
async function service(sql:string,args:unknown[]=[]){await db.exec('savepoint service_call;set role service_role');try{const r=await db.query<{v:Record<string,unknown>}>(sql,args);await db.exec('reset role;release savepoint service_call');return r.rows[0].v;}catch(e){await db.exec('rollback to savepoint service_call');throw e;}}
async function reserve(){const payload={version:1,tenant_id:i.tenant,request_id:randomUUID(),sha256:'a'.repeat(64),size_bytes:50};const artifact=(await financeAs<{v:{artifact_id:string}}>(db,i.operator,'select reserve_finance_payable_xml($1) v',[payload])).rows[0].v;return {payload,artifact};}
it('reserves privately, denies cross tenant/mixed driver and browser service calls',async()=>{const s=await reserve();expect(payableXmlArtifactSchema.safeParse(s.artifact).success).toBe(true);expect(JSON.stringify(s.artifact)).not.toMatch(/ticket|original_path/);await expect(financeAs(db,i.operator,'select reserve_finance_payable_xml($1)',[{...s.payload,tenant_id:i.otherTenant}])).rejects.toMatchObject({code:'42501'});await expect(financeAs(db,i.operator,'select prepare_finance_payable_xml($1,$2,$3)',[i.tenant,i.operator,s.artifact.artifact_id])).rejects.toMatchObject({code:'42501'});await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(service('select prepare_finance_payable_xml($1,$2,$3) v',[i.tenant,i.operator,s.artifact.artifact_id])).rejects.toMatchObject({code:'42501'});});
it('preserves storage evidence and creates one payable/link for exact replay',async()=>{const s=await reserve();const p=await service('select prepare_finance_payable_xml($1,$2,$3) v',[i.tenant,i.operator,s.artifact.artifact_id]);await db.query("insert into storage.objects(bucket_id,name,metadata,user_metadata) values('payable-xml-quarantine',$1,$2,$3)",[p.path,{size:50,mimetype:'application/octet-stream'},{artifact_id:s.artifact.artifact_id,sha256:s.payload.sha256,size_bytes:50,kind:'quarantined_payable_xml'}]);await service('select finish_finance_payable_xml($1) v',[{artifact_id:s.artifact.artifact_id,ticket:p.ticket,summary:{kind:'nfe',emitter_name:'EMITENTE TESTE',emitter_document:'12345678000190',document_number:'123',series:'1',issue_date:'2026-09-14',amount_cents:'123456',access_key:'1'.repeat(44),signature_verified:false,antivirus_verified:false}}]);const payload={version:1,tenant_id:i.tenant,request_id:randomUUID(),artifact_id:s.artifact.artifact_id,payable_id:null,expected_revision:null,fields:{supplier_name:'Fornecedor XML',category:'supplier',description:'Revisado',amount_cents:'61728',due_date:'2026-09-30',competence_date:'2026-09-14',document_number:'123/1',status:'pending',notes:null}};const call=()=>financeAs<{v:{payable_id:string}}>(db,i.operator,'select record_finance_payable_xml($1) v',[payload]);const first=(await call()).rows[0].v;expect(payableXmlResultSchema.safeParse(first).success).toBe(true);const context=(await financeAs<{v:unknown}>(db,i.operator,'select get_finance_payable_xml_context($1,$2) v',[i.tenant,first.payable_id])).rows[0].v;expect(payableXmlContextSchema.safeParse(context).success).toBe(true);expect((await call()).rows[0].v).toEqual(first);expect((await db.query('select amount::text from payables where id=$1',[first.payable_id])).rows[0]).toEqual({amount:'617.28'});expect((await db.query('select count(*)::int n from payable_xml_private.links')).rows).toEqual([{n:1}]);expect((await financeAs(db,i.operator,"select name from storage.objects where bucket_id='payable-xml-quarantine'")).rows).toEqual([]);});

it('rejects missing hashes, fake summaries, expired tickets and changed request bodies',async()=>{await expect(financeAs(db,i.operator,'select reserve_finance_payable_xml($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),size_bytes:50}])).rejects.toMatchObject({code:'22023'});const s=await reserve();const p=await service('select prepare_finance_payable_xml($1,$2,$3) v',[i.tenant,i.operator,s.artifact.artifact_id]);await expect(service('select finish_finance_payable_xml($1) v',[{artifact_id:s.artifact.artifact_id,ticket:p.ticket,summary:{kind:'nfe',signature_verified:false,antivirus_verified:false}}])).rejects.toMatchObject({code:'22023'});await expect(financeAs(db,i.operator,'select reserve_finance_payable_xml($1)',[{...s.payload,sha256:'b'.repeat(64)}])).rejects.toMatchObject({code:'22023'});await db.query("update payable_xml_private.artifacts set expires_at=clock_timestamp()-interval '1 second' where id=$1",[s.artifact.artifact_id]);await expect(service('select prepare_finance_payable_xml($1,$2,$3) v',[i.tenant,i.operator,s.artifact.artifact_id])).rejects.toMatchObject({code:'42501'});});
it('separates equal request UUIDs by actor and denies original overwrite or broad browser read',async()=>{const s=await reserve(),other=randomUUID();await db.query("insert into auth.users(id,email) values($1,'xml-other@example.test')",[other]);await db.query("insert into tenant_memberships values($1,$2,'operator',true)",[i.tenant,other]);const second=(await financeAs<{v:{artifact_id:string}}>(db,other,'select reserve_finance_payable_xml($1) v',[s.payload])).rows[0].v;const one=await service('select prepare_finance_payable_xml($1,$2,$3) v',[i.tenant,i.operator,s.artifact.artifact_id]),two=await service('select prepare_finance_payable_xml($1,$2,$3) v',[i.tenant,other,second.artifact_id]);expect(one.path).not.toBe(two.path);expect(one.path).toContain(i.operator);expect(two.path).toContain(other);await db.query("insert into storage.objects(bucket_id,name,metadata) values('payable-xml-quarantine',$1,'{}')",[one.path]);await db.exec('create policy xml_unrelated_broad_read on storage.objects for select to authenticated using(true)');expect((await financeAs(db,i.operator,"select name from storage.objects where bucket_id='payable-xml-quarantine'")).rows).toEqual([]);await db.exec('savepoint immutable');await expect(db.query("update storage.objects set metadata='{}' where bucket_id='payable-xml-quarantine'")).rejects.toMatchObject({code:'55000'});await db.exec('rollback to savepoint immutable');});

async function preserved(){const s=await reserve();const p=await service('select prepare_finance_payable_xml($1,$2,$3) v',[i.tenant,i.operator,s.artifact.artifact_id]);await db.query("insert into storage.objects(bucket_id,name,metadata,user_metadata) values('payable-xml-quarantine',$1,$2,$3)",[p.path,{size:50,mimetype:'application/octet-stream'},{artifact_id:s.artifact.artifact_id,sha256:s.payload.sha256,size_bytes:50,kind:'quarantined_payable_xml'}]);await service('select finish_finance_payable_xml($1) v',[{artifact_id:s.artifact.artifact_id,ticket:p.ticket,summary:{kind:'nfe',emitter_name:'EMITENTE TESTE',emitter_document:'12345678000190',document_number:'123',series:'1',issue_date:'2026-09-14',amount_cents:'123456',access_key:'1'.repeat(44),signature_verified:false,antivirus_verified:false}}]);return s;}
it('blocks reimporting the same NF-e as a second active title but allows an attachment update of the original title',async()=>{const first=await preserved();const base={version:1,tenant_id:i.tenant,request_id:randomUUID(),artifact_id:first.artifact.artifact_id,payable_id:null as string|null,expected_revision:null as string|null,fields:{supplier_name:'Fornecedor XML',category:'supplier',description:'Documento',amount_cents:'123456',due_date:null,competence_date:null,document_number:'123/1',status:'pending',notes:null}};const saved=(await financeAs<{v:{payable_id:string}}>(db,i.operator,'select record_finance_payable_xml($1) v',[base])).rows[0].v;const next=await preserved(),duplicate={...base,request_id:randomUUID(),artifact_id:next.artifact.artifact_id};await expect(financeAs(db,i.operator,'select record_finance_payable_xml($1)',[duplicate])).rejects.toMatchObject({code:'55000',message:'payable_xml_already_registered'});const ctx=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_payable_xml_context($1,$2) v',[i.tenant,saved.payable_id])).rows[0].v;const updated=(await financeAs<{v:{payable_id:string}}>(db,i.operator,'select record_finance_payable_xml($1) v',[{...duplicate,request_id:randomUUID(),payable_id:saved.payable_id,expected_revision:ctx.revision}])).rows[0].v;expect(updated.payable_id).toBe(saved.payable_id);expect((await db.query('select count(distinct payable_id)::int n from payable_xml_private.links')).rows).toEqual([{n:1}]);});
