import {beforeEach,it,expect,vi} from 'vitest';
import {createPayableApprovalOutbox,pendingPayableApproval,payableApprovalKey} from '@/lib/financial/payableApprovalOutbox';
import {approvalIds as i,approvalInput as input,approvalSuccess} from './helpers/payableApprovalFixture';
function setup(send:ReturnType<typeof vi.fn>){return createPayableApprovalOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),assertContext:()=>{},changed:()=>{},lock:async<T,>(_key:string,work:()=>Promise<T>)=>work(),send});}
beforeEach(()=>localStorage.clear());
it('recovers exact input after unknown and keeps uncertain request after known rejection',async()=>{const send=vi.fn().mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce({data:null,error:{code:'40001'}}).mockImplementationOnce(async c=>approvalSuccess(c));const box=setup(send);await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow('lost');await expect(box.recover(i.tenant,i.actor)).rejects.toMatchObject({code:'40001'});expect(pendingPayableApproval(localStorage,i.tenant,i.actor)).not.toBeNull();await box.recover(i.tenant,i.actor);expect(send.mock.calls[2][0]).toEqual(send.mock.calls[0][0]);expect(pendingPayableApproval(localStorage,i.tenant,i.actor)).toBeNull();});
it('clears only first definitive rejection and preserves incompatible actor response',async()=>{const send=vi.fn().mockResolvedValueOnce({data:null,error:{code:'23514'}}).mockImplementationOnce(async c=>({data:{...approvalSuccess(c).data,actor_id:crypto.randomUUID()},error:null}));const box=setup(send);await expect(box.submit(i.tenant,i.actor,input)).rejects.toMatchObject({code:'23514'});expect(pendingPayableApproval(localStorage,i.tenant,i.actor)).toBeNull();await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow();expect(pendingPayableApproval(localStorage,i.tenant,i.actor)).not.toBeNull();});
it('does not erase a different tab request after the original response',async()=>{const foreign='preserved-by-another-tab';const send=vi.fn().mockImplementation(async c=>{localStorage.setItem(payableApprovalKey(i.tenant,i.actor),foreign);return approvalSuccess(c);});await setup(send).submit(i.tenant,i.actor,input);expect(localStorage.getItem(payableApprovalKey(i.tenant,i.actor))).toBe(foreign);});

it('keeps wrong status, value, cost revision and tenant responses pending',async()=>{for(const patch of [{status:'pending'},{amount_cents:'2000'},{cost_revision:'b'.repeat(32)},{tenant_id:crypto.randomUUID()}]){localStorage.clear();const send=vi.fn().mockImplementation(async c=>({data:{...approvalSuccess(c).data,...patch},error:null}));await expect(setup(send).submit(i.tenant,i.actor,input)).rejects.toThrow();expect(pendingPayableApproval(localStorage,i.tenant,i.actor)).not.toBeNull();}});
it('does not send after context changes',async()=>{const send=vi.fn();const box=createPayableApprovalOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{},assertContext:()=>{throw new Error('changed tenant');},lock:async<T,>(_key:string,work:()=>Promise<T>)=>work(),send});await expect(box.submit(i.tenant,i.actor,input)).rejects.toThrow('changed tenant');expect(send).not.toHaveBeenCalled();});
