// @vitest-environment node
import {payablePortfolioSchema} from '@/lib/financial/payablePortfolioContract';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createPaidProjectionChainDatabase} from './helpers/paidProjectionChainDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createPaidProjectionChainDatabase>>;
type Portfolio={revision:string;total_titles:number;invalid_titles:number;totals_valid:boolean;nominal_cents:string|null;paid_cents:string|null;open_cents:string|null;rows:Array<{source_id:string;status:string;issues:string[];valid:boolean}>};
beforeAll(async()=>{db=await createPaidProjectionChainDatabase();const baseline=readFileSync('supabase/migrations/20260824224152_baseline.sql','utf8');await db.exec(baseline.match(/CREATE OR REPLACE FUNCTION public\._recalc_payable_paid\([\s\S]*?\$function\$;/)![0]);await db.exec('create trigger qa_recalc_payable after insert or update or delete on payables_payments for each row execute function _recalc_payable_paid()');const reversal=readFileSync('supabase/migrations/20260910003529_finance_payable_link_reversal.sql','utf8');await db.exec(reversal.slice(reversal.indexOf('create function finance_private.reverse_payable_link'),reversal.indexOf('create function finance_private.payable_payment_history')));await db.exec(readFileSync('supabase/migrations/20260910180040_finance_payable_portfolio.sql','utf8'));},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
const read=async(filters={},page=1,revision:string|null=null,actor=i.operator)=>payablePortfolioSchema.parse((await financeAs<{v:Portfolio}>(db,actor,'select get_finance_payable_portfolio($1,$2,$3,$4) v',[i.tenant,filters,page,revision])).rows[0].v);
async function title(amount=50,status='approved'){const id=randomUUID();await db.query("insert into payables(id,tenant_id,supplier_name,category,amount,status,due_date) values($1,$2,'Fornecedor','other',$3,$4,'2026-01-15')",[id,i.tenant,amount,status]);return id;}
it('empty portfolio gives exact zero and stable revision',async()=>{expect(await read()).toMatchObject({total_titles:0,totals_valid:true,nominal_cents:'0',paid_cents:'0',open_cents:'0'});expect((await read()).revision).toBe((await read()).revision);});
it('full aggregate exceeds1000 and details share same revision',async()=>{await db.query("insert into payables(tenant_id,supplier_name,category,amount,status,due_date) select $1,'Fornecedor','other',1,'approved','2026-01-15' from generate_series(1,1005)",[i.tenant]);const p=await read();expect(p).toMatchObject({total_titles:1005,nominal_cents:'100500',totals_valid:true});expect(p.rows).toHaveLength(30);expect((await read({},34,p.revision)).rows).toHaveLength(15);await title();await expect(read({},2,p.revision)).rejects.toThrow('finance_payable_portfolio_changed');});
it('real partial allocation supplies paid amount and prevents workflow paid without money',async()=>{const id=await title();const m=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:2000,occurred_on:'2026-01-15',description:'Pagamento fornecedor',beneficiary_name:'Fornecedor',reason:'Pagamento conferido e registrado'}])).rows[0].v;await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:m.movement_id,payable_id:id,amount_cents:2000,method:'pix',reason:'Parcela conferida do título'}]);expect((await read()).rows[0].issues).toEqual([]);expect(await read()).toMatchObject({totals_valid:true,paid_cents:'2000',open_cents:'3000'});await title(10,'paid');expect(await read()).toMatchObject({totals_valid:false,nominal_cents:null});});
it('keeps unknown/NaN/date evidence visible and excludes only clean cancellation',async()=>{await title(1,'cancelled');const id=await title(2,'mystery');await db.query("update payables set amount='NaN',created_at='infinity',due_date='infinity' where id=$1",[id]);const p=await read({from:'2026-01-01',to:'2026-01-31'});expect(p.total_titles).toBe(2);expect(p.invalid_titles).toBe(1);expect(p.rows.find(x=>x.source_id===id)?.issues).toContain('invalid_amount');expect(p.rows.find(x=>x.source_id===id)?.issues).toContain('invalid_due_date');});
it('rejects drivers and isolates tenant',async()=>{await title();await db.query("insert into payables(tenant_id,supplier_name,category,amount,status) values($1,'Outro','other',100,'approved')",[i.otherTenant]);expect((await read()).total_titles).toBe(1);await expect(read({},1,null,i.driverUser)).rejects.toThrow('finance_access_denied');});
async function pay(id:string,cents=2000){const m=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:cents,occurred_on:'2026-01-15',description:'Pagamento fornecedor',beneficiary_name:'Fornecedor',reason:'Pagamento conferido e registrado'}])).rows[0].v;await financeAs(db,i.operator,'select apply_finance_payable_movement($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:m.movement_id,payable_id:id,amount_cents:cents,method:'pix',reason:'Parcela conferida do título'}]);return(await db.query<{id:string}>('select id from finance_payable_movement_links where payable_id=$1',[id])).rows[0].id;}
it('canonical reversal removes active payment, changes revision and preserves nominal obligation',async()=>{const id=await title(),link=await pay(id),before=await read();await financeAs(db,i.operator,'select reverse_finance_payable_link($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),link_id:link,reason:'Corrigindo associação de pagamento conferida'}]);const after=await read();expect(after).toMatchObject({totals_valid:true,nominal_cents:'5000',paid_cents:'0',open_cents:'5000'});expect(after.revision).not.toBe(before.revision);expect((await db.query<{n:number}>('select count(*)::int n from payables_payments')).rows[0].n).toBe(1);});
it('reversed legacy adoption keeps historical payment pending resolution instead of treating it as unpaid cash',async()=>{const id=await title(),link=await pay(id);await db.query("update finance_payable_movement_links set origin='legacy_adoption' where id=$1",[link]);await db.query("insert into finance_payable_link_reversals(tenant_id,link_id,created_by,actor_name,reason) values($1,$2,$3,'QA','Correção da associação legada')",[i.tenant,link,i.operator]);const p=await read();expect(p.totals_valid).toBe(false);expect(p.rows[0].issues).toContain('payment_money_chain_unresolved');});
it('date basis is explicit, SP midnight is exact and missing due dates stay in undated section',async()=>{const id=await title(),undated=await title();await db.query("update payables set created_at='2026-02-01T02:30:00Z',due_date='2026-02-15' where id=$1",[id]);await db.query('update payables set due_date=null where id=$1',[undated]);const due=await read({date_basis:'due_date',from:'2026-01-01',to:'2026-01-31'});expect(due.rows.map(x=>x.source_id)).toEqual([undated]);const created=await read({date_basis:'created_at',from:'2026-01-31',to:'2026-01-31'});expect(created.rows.map(x=>x.source_id)).toEqual([id]);});
it('cancelled with active payment and mixed driver/operator permission cannot be hidden',async()=>{const id=await title();await pay(id);await db.query("update payables set status='cancelled' where id=$1",[id]);expect((await read()).rows[0].issues).toContain('cancelled_with_active_payment');await db.query("insert into tenant_memberships(tenant_id,user_id,role,active) values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(read()).rejects.toThrow('finance_access_denied');});
it('rejects malformed filter types and keeps orphan links as a monetary issue',async()=>{await expect(read({from:123})).rejects.toThrow('finance_invalid_filters');const id=await title();await db.query('insert into finance_payable_movement_links(tenant_id,movement_id,payable_id,payment_id,amount_cents,created_by) values($1,$2,$3,$4,100,$5)',[i.tenant,randomUUID(),id,randomUUID(),i.operator]);expect((await read()).rows[0].issues).toContain('orphan_payment_link');});
it('shared capacity change invalidates title totals and page revision',async()=>{const id=await title(),link=await pay(id),before=await read();const movement=(await db.query<{movement_id:string}>('select movement_id from finance_payable_movement_links where id=$1',[link])).rows[0].movement_id;await db.query('insert into finance_payable_movement_links(tenant_id,movement_id,payable_id,payment_id,amount_cents,created_by) values($1,$2,$3,$4,1,$5)',[i.tenant,movement,randomUUID(),randomUUID(),i.operator]);expect((await read()).rows[0].issues).toContain('payment_money_chain_unresolved');await expect(read({},1,before.revision)).rejects.toThrow('finance_payable_portfolio_changed');});
