import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {PayablePortfolioWorkspace} from '@/components/financial/PayablePortfolioPanel';
const mock=vi.hoisted(()=>({read:vi.fn()}));vi.mock('@/lib/financial/payablePortfolioClient',()=>({readPayablePortfolio:mock.read}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),revision='a'.repeat(32),filters={date_basis:'due_date',from:null,to:null,category:null,supplier_id:null,search:null,status:null,source:null};
const row={source_id:crypto.randomUUID(),status:'cancelled',description:'Compra cancelada',supplier_id:null,supplier_name:'Fornecedor',due_on:null,created_on:'2026-09-01',date_in_range:false,origin:{source_table:'finance_expense_items',source_id:crypto.randomUUID()},declared_amount:'25.00',declared_paid:'0.00',payment_ids:[],issues:[],nominal_cents:'0',paid_cents:'0',open_cents:'0'};
const data={version:1,tenant_id:tenant,...filters,as_of:'2026-09-10',revision,page:1,total_titles:31,cancelled_titles:1,invalid_titles:0,undated_titles:1,totals_valid:true,nominal_cents:'250000',paid_cents:'50000',open_cents:'200000',overdue_cents:'100000',status_counts:[{status:'cancelled',count:1},{status:'pending',count:30}],issue_counts:[],rows:[row]};
beforeEach(()=>{mock.read.mockReset();mock.read.mockResolvedValue(data);});afterEach(cleanup);
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){const manage=vi.fn();render(<QueryClientProvider client={cache}><PayablePortfolioWorkspace tenant={tenant} actor={actor} onManage={manage}/></QueryClientProvider>);return {cache,manage};}
it('uses full server totals, retains cancelled and undated titles, and navigates to management',async()=>{const {manage}=open();await screen.findByText('Compra cancelada');expect(screen.getByText('R$ 2.500,00')).toBeInTheDocument();expect(screen.getByText(/31 título\(s\) no filtro/)).toBeInTheDocument();expect(screen.getByText('Original preservado; excluído dos valores ativos')).toBeInTheDocument();expect(screen.getByText('Sem atribuição ao período')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Gerenciar contas a pagar'}));expect(manage).toHaveBeenCalledOnce();});
it('pins next page to revision and restarts page one when server detects a change',async()=>{mock.read.mockResolvedValueOnce(data).mockRejectedValueOnce({code:'40001',message:'finance_payable_portfolio_changed'}).mockResolvedValue({...data,revision:'b'.repeat(32),nominal_cents:'350000'});open();fireEvent.click(await screen.findByRole('button',{name:'Próximos títulos a pagar'}));await screen.findByText(/A carteira mudou durante a navegação/);await screen.findByText('R$ 3.500,00');expect(mock.read).toHaveBeenNthCalledWith(2,tenant,filters,2,revision);expect(mock.read).toHaveBeenLastCalledWith(tenant,filters,1,null);});
it('hides stale amounts during failure and never renders invalid totals as zero',async()=>{const {cache}=open();await screen.findByText('R$ 2.500,00');mock.read.mockRejectedValue(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-payable-portfolio']});});expect(await screen.findByText(/Não foi possível consultar a carteira/)).toBeInTheDocument();expect(screen.queryByText('R$ 2.500,00')).not.toBeInTheDocument();mock.read.mockResolvedValue({...data,invalid_titles:1,totals_valid:false,nominal_cents:null,paid_cents:null,open_cents:null,overdue_cents:null,rows:[],issue_counts:[{issue:'declared_paid_mismatch',count:1}]});fireEvent.click(screen.getByRole('button',{name:'Tentar consultar carteira novamente'}));await screen.findByText(/Totais indeterminados/);expect(screen.getAllByText('Indeterminado')).toHaveLength(4);expect(screen.queryByText('R$ 0,00')).not.toBeInTheDocument();});
it('applies its own explicit date basis and resets pagination',async()=>{open();await screen.findByText('Compra cancelada');fireEvent.change(screen.getByLabelText('Data usada na carteira'),{target:{value:'created_at'}});fireEvent.change(screen.getByLabelText('Contas a pagar — início'),{target:{value:'2026-08-01'}});fireEvent.click(screen.getByRole('button',{name:'Consultar contas a pagar'}));await waitFor(()=>expect(mock.read).toHaveBeenLastCalledWith(tenant,{...filters,date_basis:'created_at',from:'2026-08-01'},1,null));});

it('opens an exact title on a later server page without loading the full collection',async()=>{
 const lastId=crypto.randomUUID(),onOpen=vi.fn();
 mock.read.mockResolvedValueOnce({...data,total_titles:1005,rows:[row]}).mockResolvedValueOnce({...data,page:2,total_titles:1005,rows:[{...row,source_id:lastId,description:'Conta da segunda página'}]});
 render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><PayablePortfolioWorkspace tenant={tenant} actor={actor} onOpen={onOpen}/></QueryClientProvider>);
 await screen.findByText('Compra cancelada');expect(screen.getByText('R$ 2.500,00')).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Próximos títulos a pagar'}));await screen.findByText('Conta da segunda página');
 fireEvent.click(screen.getByRole('button',{name:'Baixas'}));expect(onOpen).toHaveBeenCalledWith(lastId,'payments');
 fireEvent.click(screen.getByRole('button',{name:'Abrir conta'}));expect(onOpen).toHaveBeenLastCalledWith(lastId,'edit');
 expect(mock.read).toHaveBeenLastCalledWith(tenant,filters,2,revision);
});

it('sends text, state, origin and category to the server as one global filter',async()=>{open();await screen.findByText('Compra cancelada');fireEvent.change(screen.getByLabelText('Buscar conta'),{target:{value:'nota 42'}});fireEvent.change(screen.getByLabelText('Situação da conta'),{target:{value:'partial'}});fireEvent.change(screen.getByLabelText('Origem da conta'),{target:{value:'manual'}});fireEvent.change(screen.getByLabelText('Categoria da conta'),{target:{value:'fuel'}});fireEvent.click(screen.getByRole('button',{name:'Consultar contas a pagar'}));await waitFor(()=>expect(mock.read).toHaveBeenLastCalledWith(tenant,{...filters,search:'nota 42',status:'partial',source:'manual',category:'fuel'},1,null));});
