import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import Payables from '@/pages/Payables';
import {payableNfeXml} from './helpers/payableNfeFixture';
const mock=vi.hoisted(()=>({tenant:'11111111-1111-4111-8111-111111111111',id:'22222222-2222-4222-8222-222222222222',single:vi.fn(),eq:vi.fn(),select:vi.fn(),from:vi.fn(),mutate:vi.fn(),create:vi.fn(),upload:vi.fn(),discard:vi.fn(),send:vi.fn(),success:vi.fn(),error:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:mock.from}}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'33333333-3333-4333-8333-333333333333'}})}));
vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentTenant:{id:mock.tenant}})}));
vi.mock('@/hooks/useSonnerToast',()=>({useSonnerToast:()=>({error:mock.error,success:mock.success,warning:vi.fn()})}));
vi.mock('@/hooks/usePayables',async()=>{const real=await vi.importActual<typeof import('@/hooks/usePayables')>('@/hooks/usePayables');return {...real,usePayables:()=>{throw new Error('unbounded list is forbidden');},useCreatePayable:()=>({isPending:false,mutateAsync:mock.create}),useUpdatePayable:()=>({isPending:false,mutateAsync:mock.mutate})};});
vi.mock('@/components/financial/FinanceAccessBoundary',()=>({FinanceAccessBoundary:({children}:{children:React.ReactNode})=>children}));
vi.mock('@/components/financial/PayablePortfolioPanel',()=>({PayablePortfolioPanel:({onOpen}:{onOpen:(id:string,action:string)=>void})=><><button onClick={()=>onOpen(mock.id,'payments')}>Abrir baixa da página</button><button onClick={()=>onOpen(mock.id,'edit')}>Editar conta</button></>}));
vi.mock('@/components/financial/PayablePaymentDialog',()=>({default:({payable}:{payable:{id:string}|null})=>payable?<p>Pagamento {payable.id}</p>:null}));
vi.mock('@/components/financial/ManualExpenseDialog',()=>({default:()=>null}));
vi.mock('@/lib/financial/payableXmlClient',()=>({preservePayableXmlFile:(...args:unknown[])=>mock.upload(...args),discardPayableXmlUpload:(...args:unknown[])=>mock.discard(...args),readPayableXmlContext:async()=>({revision:'a'.repeat(32),payable:(await mock.single()).data}),sendPayableXml:(...args:unknown[])=>mock.send(...args),payableXmlError:(e:Error)=>e.message,payableXmlUploadKey:()=> 'test-upload'}));
vi.mock('@/components/financial/PayableApprovalDialog',()=>({PayableApprovalDialog:({payableId}:{payableId:string})=><p>Prévia de aprovação {payableId}</p>}));

beforeEach(()=>{vi.clearAllMocks();localStorage.clear();mock.from.mockReturnValue({select:mock.select});mock.select.mockReturnValue({eq:mock.eq});mock.eq.mockReturnValue({eq:mock.eq,single:mock.single});mock.single.mockResolvedValue({data:{id:mock.id,tenant_id:mock.tenant,supplier_name:'Original',amount:20,status:'pending',source_table:null,source_id:null,updated_at:'2026-09-22T12:00:00Z'},error:null});mock.upload.mockRejectedValue(Error('Não foi possível preservar o XML. A conta não foi salva; mantenha os campos e tente novamente.'));mock.discard.mockResolvedValue(false);});afterEach(cleanup);
async function load(){const file=new File([payableNfeXml],'nota-teste.xml',{type:'application/xml'});Object.defineProperty(file,'text',{value:async()=>payableNfeXml});fireEvent.change(screen.getByLabelText('Selecionar XML fiscal'),{target:{files:[file]}});await screen.findByDisplayValue('EMITENTE TESTE');return file;}
it('advertises NF-e only, exposes labelled fields and rejects NFS-e before changing or saving the account',async()=>{render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><Payables/></QueryClientProvider>);fireEvent.click(screen.getByText('Nova conta'));expect(screen.getByRole('button',{name:'Importar XML NF-e'})).toBeInTheDocument();expect(screen.getByLabelText('Fornecedor *')).toBeInTheDocument();expect(screen.getByLabelText('Valor (R$) *')).toBeInTheDocument();expect(screen.getByLabelText('Vencimento')).toBeInTheDocument();expect(screen.getByLabelText('Competência')).toBeInTheDocument();expect(screen.getByLabelText('Nº documento')).toBeInTheDocument();expect(screen.getByLabelText('Observações')).toBeInTheDocument();const nfse='<Nfse><InfNfse><Numero>123</Numero><Servico><Valores><ValorServicos>1234.56</ValorServicos></Valores></Servico></InfNfse></Nfse>',file=new File([nfse],'servico.xml',{type:'application/xml'});Object.defineProperty(file,'text',{value:async()=>nfse});fireEvent.change(screen.getByLabelText('Selecionar XML fiscal'),{target:{files:[file]}});await waitFor(()=>expect(mock.error).toHaveBeenCalledWith('Este cadastro aceita somente XML de NF-e.'));expect(screen.queryByText(/XML selecionado:/)).not.toBeInTheDocument();expect(screen.getByText('Criar')).toBeEnabled();expect(mock.upload).not.toHaveBeenCalled();expect(mock.create).not.toHaveBeenCalled();});
it.each(['create','update'] as const)('preserves real XML autofill and prevents %s after upload rejection',async(action)=>{render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><Payables/></QueryClientProvider>);fireEvent.click(screen.getByText(action==='create'?'Nova conta':'Editar conta'));await screen.findByLabelText('Selecionar XML fiscal');const file=await load();expect(screen.getByDisplayValue('1234.56')).toBeInTheDocument();expect(screen.getByDisplayValue('2026-08-31')).toBeInTheDocument();expect(screen.getByDisplayValue('123/1')).toBeInTheDocument();fireEvent.click(screen.getByText(action==='create'?'Criar':'Salvar'));await screen.findByRole('alert');expect(screen.getByRole('alert')).toHaveTextContent('A conta não foi salva');expect(mock.upload).toHaveBeenCalledWith(mock.tenant,'33333333-3333-4333-8333-333333333333',file);expect(mock.create).not.toHaveBeenCalled();expect(mock.mutate).not.toHaveBeenCalled();expect(mock.success).not.toHaveBeenCalledWith(expect.stringMatching(/Conta criada|Conta atualizada/));expect(screen.getByDisplayValue('EMITENTE TESTE')).toBeInTheDocument();expect(screen.getByDisplayValue('1234.56')).toBeInTheDocument();expect(screen.getByText(/XML selecionado: nota-teste.xml/)).toBeInTheDocument();fireEvent.click(screen.getByText(action==='create'?'Criar':'Salvar'));await waitFor(()=>expect(mock.upload).toHaveBeenCalledTimes(2));expect(mock.upload.mock.calls[1][2]).toBe(file);expect(mock.create).not.toHaveBeenCalled();expect(mock.mutate).not.toHaveBeenCalled();});

it('recovers the original XML command after an unknown response without another upload or raw creation',async()=>{Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_key:string,work:()=>Promise<unknown>)=>work()}});const artifact=crypto.randomUUID();mock.upload.mockResolvedValue({artifact_id:artifact});mock.send.mockRejectedValueOnce(Error('Resposta interrompida'));render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><Payables/></QueryClientProvider>);fireEvent.click(screen.getByText('Nova conta'));await load();fireEvent.click(screen.getByText('Criar'));await screen.findByText('Recuperar pedido original');expect(mock.create).not.toHaveBeenCalled();const original=mock.send.mock.calls[0][0];mock.send.mockImplementationOnce(async p=>({data:{version:1,confirmed:true,tenant_id:p.tenant_id,actor_id:'33333333-3333-4333-8333-333333333333',request_id:p.request_id,payable_id:mock.id,artifact_id:artifact,link_id:crypto.randomUUID(),amount_cents:p.fields.amount_cents,original_preserved:true,cash_changed:false,fiscal_document_created:false},error:null}));fireEvent.click(screen.getByText('Recuperar pedido original'));await screen.findByText(`Conta ${mock.id} salva; XML original preservado.`);expect(mock.send.mock.calls[1][0]).toEqual(original);expect(mock.upload).toHaveBeenCalledOnce();expect(mock.create).not.toHaveBeenCalled();expect(mock.mutate).not.toHaveBeenCalled();});

it('keeps a confirmed save terminal when refreshing the portfolio fails',async()=>{Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_key:string,work:()=>Promise<unknown>)=>work()}});const artifact=crypto.randomUUID();mock.upload.mockResolvedValue({artifact_id:artifact});mock.send.mockImplementationOnce(async p=>({data:{version:1,confirmed:true,tenant_id:p.tenant_id,actor_id:'33333333-3333-4333-8333-333333333333',request_id:p.request_id,payable_id:mock.id,artifact_id:artifact,link_id:crypto.randomUUID(),amount_cents:p.fields.amount_cents,original_preserved:true,cash_changed:false,fiscal_document_created:false},error:null}));const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});vi.spyOn(cache,'invalidateQueries').mockRejectedValue(Error('refetch offline'));render(<QueryClientProvider client={cache}><Payables/></QueryClientProvider>);fireEvent.click(screen.getByText('Nova conta'));await load();fireEvent.click(screen.getByText('Criar'));await screen.findByText(/A conta e o XML foram salvos, mas a consulta não atualizou/);expect(screen.queryByText('Recuperar pedido original')).not.toBeInTheDocument();expect(mock.send).toHaveBeenCalledOnce();expect(mock.create).not.toHaveBeenCalled();});
it('discards a corrupt XML outbox together with any abandoned upload marker',async()=>{const actor='33333333-3333-4333-8333-333333333333',key=`agvlog:payable-xml:v1:${mock.tenant}:${actor}`;localStorage.setItem(key,'{"broken":true}');render(<QueryClientProvider client={new QueryClient()}><Payables/></QueryClientProvider>);expect(await screen.findByRole('alert')).toHaveTextContent('indisponível ou incompatível');fireEvent.click(screen.getByRole('button',{name:'Descartar XML abandonado'}));await screen.findByText(/recuperação incompatível descartados/);expect(localStorage.getItem(key)).toBeNull();expect(mock.discard).toHaveBeenCalledWith(mock.tenant,actor);expect(mock.send).not.toHaveBeenCalled();});
