import {beforeEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup,act} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {PayableApprovalWorkspace} from '@/components/financial/PayableApprovalDialog';
import {PayableApprovalConfirmation} from '@/components/financial/PayableApprovalConfirmation';
import {approvalIds as i,approvalPreview as p,approvalSuccess} from './helpers/payableApprovalFixture';
const m=vi.hoisted(()=>({read:vi.fn(),send:vi.fn(),role:'admin'}));
vi.mock('@/lib/financial/payableApprovalClient',async importOriginal=>({...await importOriginal<typeof import('@/lib/financial/payableApprovalClient')>(),readPayableApproval:m.read,sendPayableApproval:m.send}));
vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentRole:m.role})}));
vi.mock('@/lib/financial/invalidateAccountReview',()=>({invalidateAccountReview:vi.fn().mockResolvedValue(undefined)}));
beforeEach(()=>{cleanup();localStorage.clear();vi.clearAllMocks();m.role='admin';Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async<T,>(_key:string,work:()=>Promise<T>)=>work()}});});
function review(){fireEvent.change(screen.getByLabelText('Motivo da aprovação'),{target:{value:'Valor e documentos conferidos'}});fireEvent.click(screen.getByText('Revisar aprovação'));fireEvent.click(screen.getByRole('checkbox'));}
it('requires a new review after stale 50 becomes 20 and never auto approves the new value',async()=>{m.read.mockResolvedValueOnce(p).mockResolvedValue({...p,revision:'b'.repeat(32),obligation:{...p.obligation,amount_cents:'2000'}});m.send.mockResolvedValueOnce({data:null,error:{code:'40001',message:'finance_payable_approval_changed'}}).mockImplementationOnce(async c=>approvalSuccess(c));render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><PayableApprovalWorkspace tenant={i.tenant} actor={i.actor} payableId={i.payable}/></QueryClientProvider>);await screen.findByLabelText('Motivo da aprovação');review();fireEvent.click(screen.getByText('Confirmar aprovação'));await screen.findByText(/Valor da obrigação: R\$ 20,00/);expect(m.send).toHaveBeenCalledOnce();expect(m.send.mock.calls[0][0].amount_cents).toBe('5000');expect(screen.queryByText('Confirmar aprovação')).not.toBeInTheDocument();fireEvent.click(screen.getByText('Revisar aprovação'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByText('Confirmar aprovação'));await screen.findByText(/Aprovação confirmada/);expect(m.send.mock.calls[1][0]).toMatchObject({amount_cents:'2000',revision:'b'.repeat(32)});expect(m.send.mock.calls[1][0].request_id).not.toBe(m.send.mock.calls[0][0].request_id);});
it('recovers the original unknown request despite a different current value and preserves terminal success on cache failure',async()=>{m.send.mockRejectedValueOnce(new Error('lost')).mockImplementationOnce(async c=>approvalSuccess(c));const refresh=vi.fn().mockRejectedValue(new Error('cache unavailable'));const view=render(<PayableApprovalConfirmation tenant={i.tenant} actor={i.actor} payableId={i.payable} canConfirm preview={p} refresh={refresh}/>);review();fireEvent.click(screen.getByText('Confirmar aprovação'));await screen.findByText('Recuperar pedido de aprovação');view.rerender(<PayableApprovalConfirmation tenant={i.tenant} actor={i.actor} payableId={i.payable} canConfirm preview={{...p,obligation:{...p.obligation,amount_cents:'2000'}}} refresh={refresh}/>);expect(screen.getByText(/Valor preservado: R\$ 50,00/)).toBeInTheDocument();fireEvent.click(screen.getByText('Recuperar pedido de aprovação'));await screen.findByText(/Aprovação confirmada/);expect(m.send.mock.calls[1][0]).toEqual(m.send.mock.calls[0][0]);expect(screen.getByRole('alert')).toHaveTextContent('foi confirmada');expect(screen.queryByText('Confirmar aprovação')).not.toBeInTheDocument();});
it('hides cached permission during refetch and missing API without fallback',async()=>{m.read.mockResolvedValue(p);const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><PayableApprovalWorkspace tenant={i.tenant} actor={i.actor} payableId={i.payable}/></QueryClientProvider>);await screen.findByLabelText('Motivo da aprovação');let reject!:(error:Error)=>void;m.read.mockImplementation(()=>new Promise((_resolve,no)=>{reject=no;}));fireEvent.click(screen.getByText('Atualizar conferência'));await waitFor(()=>expect(screen.queryByLabelText('Motivo da aprovação')).not.toBeInTheDocument());await act(async()=>reject(new Error('PGRST202')));await screen.findByText(/consulta de aprovação está indisponível/);expect(m.send).not.toHaveBeenCalled();});
it('blocks a different actor and operator confirmation',()=>{render(<PayableApprovalConfirmation tenant={i.tenant} actor={crypto.randomUUID()} payableId={i.payable} canConfirm preview={p} refresh={vi.fn()}/>);expect(screen.queryByLabelText('Motivo da aprovação')).not.toBeInTheDocument();cleanup();render(<PayableApprovalConfirmation tenant={i.tenant} actor={i.actor} payableId={i.payable} canConfirm={false} preview={p} refresh={vi.fn()}/>);expect(screen.queryByLabelText('Motivo da aprovação')).not.toBeInTheDocument();});
