import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {PeriodMoneyPackageWorkspace} from '@/components/financial/PeriodMoneyPackagePanel';
vi.mock('@/components/financial/PeriodUnloadingFlowPanel',()=>({PeriodUnloadingFlowPanel:({onPackageOutdated}:{onPackageOutdated:()=>void})=><button onClick={onPackageOutdated}>Simular evidência de pacote alterado</button>}));
const read=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/periodMoneyPackageClient',()=>({readPeriodMoneyPackage:read}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),other=crypto.randomUUID();
const empty={opening_cents:null,in_cents:null,out_cents:null,closing_cents:null};
function fixture(selected=false){return {version:1,revision:"a".repeat(32),tenant_id:tenant,period:{from:'2026-09-01',to:'2026-09-10'},captured_at:'2026-09-10',account_scope:{selected_ids:selected?[account]:[],excluded_ids:selected?[other]:[account,other],complete:false,available:[{id:account,name:'Banco antigo',account_kind:'bank',active:false},{id:other,name:'Caixa sede',account_kind:'cash',active:true}]},accounts:selected?[{account_id:account,name:'Banco antigo',account_kind:'bank',coverage_complete:true,issues:[],balances:{opening_cents:'100',in_cents:'200',out_cents:'50',closing_cents:'250'},movement_ids:[],closures:[]}]:[],monetary_totals_valid:selected,totals:selected?{opening_cents:'100',in_cents:'200',out_cents:'50',closing_cents:'250'}:empty,transfer_classification_valid:false,transfer_totals:{internal_pair_cents:null,in_excluding_internal_pairs_cents:null,out_excluding_internal_pairs_cents:null},transfers:[],issues:[],limitations:[]};}
function mount(){const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><PeriodMoneyPackageWorkspace tenant={tenant} actor={actor}/></QueryClientProvider>);return cache;}
afterEach(()=>{cleanup();read.mockReset();});
it('loads the complete catalog without presenting zero and submits explicit inactive account selection',async()=>{read.mockResolvedValueOnce(fixture()).mockResolvedValue(fixture(true));mount();await screen.findByText(/seleção vazia carrega somente o catálogo/);expect(read.mock.calls[0][3]).toEqual([]);expect(screen.queryByText('R$ 0,00')).not.toBeInTheDocument();fireEvent.click(screen.getByLabelText(/Banco antigo.*Inativa/));fireEvent.click(screen.getByText('Conferir dinheiro do período'));await screen.findByText(/Somente as contas selecionadas/);expect(read.mock.calls[1][3]).toEqual([account]);expect(screen.getByText(/classificação das transferências está incompleta/)).toBeInTheDocument();expect(screen.getAllByText('R$ 2,50')).toHaveLength(2);});
it('hides stale money during refetch and after failure',async()=>{read.mockResolvedValue(fixture(true));const cache=mount();await screen.findByText(/Valores brutos das contas selecionadas/);let reject!:(error:Error)=>void;read.mockImplementation(()=>new Promise((_resolve,fail)=>{reject=fail;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-period-money-package',tenant,actor]});});await screen.findByText(/Consultando contas, cobertura/);expect(screen.queryByText(/Valores brutos das contas selecionadas/)).not.toBeInTheDocument();await act(async()=>{reject(Error('offline'));});await screen.findByText(/Nenhum saldo anterior foi mantido/);expect(screen.queryByText('R$ 2,50')).not.toBeInTheDocument();});
it('keeps null coverage indeterminate and preserves reopening authorship',async()=>{const data=fixture(true);data.monetary_totals_valid=false;data.totals=empty as unknown as typeof data.totals;data.accounts[0].coverage_complete=false;data.accounts[0].balances=empty as unknown as typeof data.accounts[0]['balances'];Object.assign(data.accounts[0],{closures:[{id:crypto.randomUUID(),from:'2026-09-01',to:'2026-09-10',active:false,evidence_kind:'bank_statement',actor_name:'Ana',actor_id:actor,created_at:'2026-09-10',reason:'Conferência do banco',integrity:{snapshot_matches_revision:true,dependencies_match:true},reopening:{id:crypto.randomUUID(),actor_name:'Bruno',actor_id:other,reason:'Correção de vínculo',created_at:'2026-09-11'}}]});read.mockResolvedValue(data);mount();await screen.findByText(/cobertura das contas selecionadas não permite/);expect(screen.getAllByText('Indeterminado')).toHaveLength(8);expect(screen.getByText(/Reaberto por Bruno/)).toBeInTheDocument();expect(screen.queryByText('R$ 0,00')).not.toBeInTheDocument();});
it('paginates available accounts without limiting the explicit all-account request',async()=>{const data=fixture();data.account_scope.available=Array.from({length:31},(_,index)=>({id:crypto.randomUUID(),name:`Conta ${index}`,account_kind:'bank',active:index!==30}));read.mockResolvedValue(data);mount();await screen.findByText(/seleção vazia carrega/);expect(screen.queryByLabelText(/Conta 30/)).not.toBeInTheDocument();fireEvent.click(screen.getByText('Próximas contas disponíveis'));expect(screen.getByLabelText(/Conta 30.*Inativa/)).toBeInTheDocument();fireEvent.click(screen.getByText('Selecionar todas as contas'));fireEvent.click(screen.getByText('Conferir dinheiro do período'));await act(async()=>{});expect(read.mock.calls.at(-1)?.[3]).toHaveLength(31);});


it('marks parent money totals as previous when the unloading child detects a changed package',async()=>{read.mockResolvedValue(fixture(true));mount();fireEvent.click(await screen.findByText('Simular evidência de pacote alterado'));expect(screen.getByText(/Os valores abaixo são da consulta anterior/)).toBeInTheDocument();fireEvent.click(screen.getByText('Atualizar conferência do pacote'));await act(async()=>{});expect(read).toHaveBeenCalledTimes(2);});
