import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {PeriodUnloadingFlowWorkspace} from '@/components/financial/PeriodUnloadingFlowPanel';
const read=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/periodUnloadingFlowClient',()=>({readPeriodUnloadingFlow:read,PeriodUnloadingFlowChangedError:class extends Error{},PeriodUnloadingMoneyPackageChangedError:class extends Error{}}));
import {PeriodUnloadingFlowChangedError,PeriodUnloadingMoneyPackageChangedError} from '@/lib/financial/periodUnloadingFlowClient';
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),account=crypto.randomUUID(),supplier=crypto.randomUUID();
function fixture(){return {revision:'b'.repeat(32),supplier_options:[{id:supplier,name:'Fornecedor original'}],origin_totals:{count:1,valid:true,amount_cents:'15000'},receipt_totals:{count:1,valid:true,amount_cents:'10000'},refund_totals:{count:0,valid:true,amount_cents:'0'},unknown_date_count:0,supplier_groups:[],total:1,page:1,page_size:50,captured_at:'2026-09-10',rows:[{event_id:crypto.randomUUID(),kind:'receipt',amount_cents:'10000',valid:true,issues:[],supplier_id:supplier,supplier_name:'Fornecedor original',economic_on:'2026-08-20',recorded_at:'2026-09-01',charge_id:crypto.randomUUID(),delivery_stop_id:crypto.randomUUID(),receivable_id:crypto.randomUUID(),original_due_date:'2026-08-30',movement_id:crypto.randomUUID(),bank_account_id:account,money_covered:true,sidecars:[],document_ids:[],closure_ids:[crypto.randomUUID()]}],money_links:[{movement_id:crypto.randomUUID(),bank_account_id:account,amount_cents:'30000',allocated_event_cents:'10000',money_covered:true,closure_ids:[],event_ids:[],issues:[]}],issues:[],limitations:[]};}
const refresh=vi.fn();function mount(cache=new QueryClient()){render(<QueryClientProvider client={cache}><PeriodUnloadingFlowWorkspace tenant={tenant} actor={actor} from="2026-08-01" to="2026-08-31" accountIds={[account]} moneyPackageRevision={'a'.repeat(32)} onRefreshPackage={refresh}/></QueryClientProvider>);return cache;}
afterEach(()=>{cleanup();read.mockReset();refresh.mockReset();});
it('keeps charge, receipt and the shared movement separate and uses the inherited scope',async()=>{read.mockResolvedValue(fixture());mount();await screen.findByText(/Descargas originadas/);expect(read.mock.calls[0][0]).toMatchObject({tenantId:tenant,accountIds:[account],expectedMoneyPackageRevision:'a'.repeat(32)});expect(screen.getByText(/Valor do movimento: R\$ 300,00 · alocado.*R\$ 100,00/)).toBeInTheDocument();expect(screen.getByText(/Não subtraia os recebimentos do período/)).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Fornecedor da descarga'),{target:{value:supplier}});fireEvent.click(screen.getByText('Aplicar fornecedor'));await act(async()=>{});expect(read.mock.calls.at(-1)?.[0].supplierId).toBe(supplier);});
it('hides all prior totals on package revision mismatch and refreshes the parent explicitly',async()=>{read.mockRejectedValue(new PeriodUnloadingMoneyPackageChangedError());mount();await screen.findByText(/O pacote de dinheiro mudou/);expect(screen.queryByText(/Descargas originadas/)).not.toBeInTheDocument();fireEvent.click(screen.getByText('Atualizar pacote do período'));expect(refresh).toHaveBeenCalledTimes(1);});
it('refreshes the first page after changed evidence despite an infinite cache lifetime',async()=>{const first=fixture();first.total=51;const next=fixture();next.receipt_totals={count:1,valid:false,amount_cents:null as unknown as string};read.mockResolvedValueOnce(first).mockRejectedValueOnce(new PeriodUnloadingFlowChangedError()).mockResolvedValueOnce(next);mount(new QueryClient({defaultOptions:{queries:{staleTime:Infinity}}}));await screen.findByText('Próxima página de descargas');fireEvent.click(screen.getByText('Próxima página de descargas'));await screen.findByText(/Valor indeterminado: há pendências/);expect(read).toHaveBeenCalledTimes(3);expect(read.mock.calls[2][0]).toMatchObject({page:1,expectedRevision:null});});
it('hides cached amounts during refresh and shows sidecar authorship without inventing an economic date',async()=>{const data=fixture();Object.assign(data.rows[0],{sidecars:[{kind:'legacy_association',id:crypto.randomUUID(),recorded_at:'2026-09-10',actor_id:actor}]});read.mockResolvedValue(data);const cache=mount();await screen.findByText(/Associação manual de recebimento antigo/);expect(screen.getByText(/sem data econômica presumida/)).toHaveTextContent(actor);read.mockImplementation(()=>new Promise(()=>{}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-period-unloading-flow',tenant,actor]});});await screen.findByText(/Consultando descargas/);expect(screen.queryByText(/Descargas originadas/)).not.toBeInTheDocument();});
it('renders signed amendments as manual economic adjustments, without missing-money warnings',async()=>{const data=fixture();const amendment=crypto.randomUUID();Object.assign(data,{version:2,adjustment_totals:{count:1,valid:true,amount_cents:'-3000'},net_origin_totals:{count:2,valid:true,amount_cents:'12000'}});Object.assign(data.rows[0],{kind:'adjustment',event_id:amendment,amendment_id:amendment,adjustment_leg:'release',amendment_actor_id:actor,amendment_actor_name:'Ana',amendment_reason:'Redução do direito de cobrança',amount_cents:'-3000',movement_id:null,bank_account_id:null,money_covered:false,closure_ids:[]});data.money_links=[];read.mockResolvedValue(data);mount();await screen.findByText(/Ajuste do direito de cobrança/);expect(screen.getByText(/Ajuste manual/)).toHaveTextContent('Ana');expect(screen.getByText(/Ajuste manual/)).toHaveTextContent('Redução do direito de cobrança');expect(screen.getByText(/Ajuste manual/)).toHaveClass('border-amber-600');expect(screen.getByText('Ajustes da cobrança').parentElement).toHaveTextContent('-R$ 30,00');expect(screen.getByText(/Líquido das cobranças originadas/).parentElement).toHaveTextContent('R$ 120,00');expect(screen.queryByText(/Cobertura do movimento não comprovada/)).not.toBeInTheDocument();});
