// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
import {createUnloadingCostCorrectionDatabase,installUnloadingCostCorrection,seedUnloadingRepairSource} from './helpers/unloadingCostCorrectionDatabase';
import {installPreparedReceiptCostPredecessors} from './helpers/preparedReceiptCostIntegrationDatabase';
import {prepareReceiptImageCallback} from './helpers/preparedReceiptImageCallback';
import {expenseReceiptIntentResultSchema} from '@/lib/financial/expenseBatchReceiptContract';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';

let db:Awaited<ReturnType<typeof createUnloadingCostCorrectionDatabase>>;
const candidate=()=>readFileSync('supabase/migrations/20260911064852_finance_batch_prepared_receipt_intents.sql','utf8');
beforeAll(async()=>{db=await createUnloadingCostCorrectionDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true),set_config('request.jwt.claims',$2,true),set_config('request.headers',$3,true)",[i.operator,JSON.stringify({active_tenant_id:i.tenant,role:'authenticated'}),JSON.stringify({'x-agvlog-tenant-id':i.tenant})]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await seedUnloadingRepairSource(db,true);await installUnloadingCostCorrection(db);await installPreparedReceiptCostPredecessors(db);});afterEach(async()=>db.exec('rollback'));afterAll(async()=>db.close());
it('installs the complete prepared receipt candidate and commits an office expense with a real finalized image',async()=>{
 await db.exec(candidate());const batch=randomUUID(),expense=randomUUID();const payload={version:1,tenant_id:i.tenant,request_id:randomUUID(),batch_request_id:batch,expense_id:expense,context:'office',trip_id:null,stop_id:null};
 const intent=expenseReceiptIntentResultSchema.parse((await financeAs<{v:{expense_id:string,intent_id:string}}>(db,i.operator,'select prepare_finance_expense_receipt_intent($1) v',[payload])).rows[0].v);expect(intent.expense_id).toBe(expense);
 const image=await prepareReceiptImageCallback(db,'expense_draft',intent.intent_id);await image.finalize();
 const command={version:1,tenant_id:i.tenant,request_id:batch,context:'office',description:'Gasto com comprovante preparado',reason:'Conferência do recibo antes do lote',items:[{id:expense,category:'office',description:'Compra administrativa',amount_cents:12000,occurred_on:'2026-08-02',supplier_name:'Prestador preservado',payee_type:'supplier',allocations:[],receipt_intent_id:intent.intent_id,receipt_artifact_id:image.reserved.artifact_id}]};
 const result=(await financeAs(db,i.operator,'select record_finance_expense_batch($1) v',[command])).rows;expect((await financeAs(db,i.operator,'select record_finance_expense_batch($1) v',[command])).rows).toEqual(result);await db.exec('set constraints all immediate;set constraints all deferred');
 expect((await db.query('select receipt_path,no_receipt_reason from finance_expense_items where id=$1',[expense])).rows).toEqual([{receipt_path:null,no_receipt_reason:null}]);expect((await db.query('select secure_upload_private.expense_receipt_count($1,$2)::int n',[i.tenant,expense])).rows).toEqual([{n:1}]);
});

it('records a prepared unloading receipt without a legacy path and preserves verified origin and correction eligibility',async()=>{
 await db.exec(candidate());const seed=(await db.query<{trip_id:string,supplier_id:string}>('select b.trip_id,e.supplier_id from finance_expense_items e join finance_expense_batches b on b.id=e.batch_id')).rows[0],stop=randomUUID(),doc=randomUUID();
 await db.query("insert into dispatch_stops(id,tenant_id,dispatch_trip_id,stop_order,status,client_id,destination) values($1,$2,$3,2,'completed',$4,'Segunda entrega')",[stop,i.tenant,seed.trip_id,seed.supplier_id]);await db.query("insert into fiscal_documents(id,tenant_id,client_id,supplier_id,document_type,status) values($1,$2,$3,$3,'inbound','ready')",[doc,i.tenant,seed.supplier_id]);await db.query('insert into dispatch_stop_documents(tenant_id,dispatch_stop_id,fiscal_document_id) values($1,$2,$3)',[i.tenant,stop,doc]);
 const delivery=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_delivery_context($1,$2) v',[i.tenant,stop])).rows[0].v;
 const batch=randomUUID(),expense=randomUUID(),intent=(await financeAs<{v:{intent_id:string}}>(db,i.operator,'select prepare_finance_expense_receipt_intent($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),batch_request_id:batch,expense_id:expense,context:'trip',trip_id:seed.trip_id,stop_id:stop}])).rows[0].v;const image=await prepareReceiptImageCallback(db,'expense_draft',intent.intent_id);await image.finalize();
 const payload={version:1,tenant_id:i.tenant,request_id:batch,context:'trip',trip_id:seed.trip_id,description:'Descarga com comprovante sanitizado',reason:'Recebimento seguro antes da confirmação',items:[{id:expense,category:'unloading',description:'Descarga preparada',amount_cents:15000,occurred_on:'2026-08-02',due_date:'2026-08-20',supplier_id:seed.supplier_id,supplier_name:'Prestador diferente do devedor',payee_type:'supplier',allocations:[],stop_id:stop,delivery_revision:delivery.revision,receipt_intent_id:intent.intent_id,receipt_artifact_id:image.reserved.artifact_id}]};
 await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[payload]);await db.exec('set constraints all immediate;set constraints all deferred');
 const charge=(await db.query<{unloading_id:string}>('select unloading_id from finance_expense_items where id=$1',[expense])).rows[0].unloading_id;const origin=(await db.query<{v:{origin_verified:boolean}}>('select finance_private.unloading_origin_base($1,$2) v',[i.tenant,charge])).rows[0].v;expect(origin.origin_verified).toBe(true);
 const cost=(await db.query<{v:{eligible:boolean,blockers:unknown[]}}>('select finance_private.unloading_cost_correction_context($1,$2,$3) v',[i.tenant,charge,'12000'])).rows[0].v;expect(cost.blockers).toEqual([]);expect(cost.eligible).toBe(true);
 const history=(await financeAs<{v:{receipts:{receipt_intent_id:string,evidence:{source_type:string}}[]}}>(db,i.operator,'select get_finance_expense_receipt_artifacts($1,$2) v',[i.tenant,expense])).rows[0].v;expect(history.receipts).toHaveLength(1);expect(history.receipts[0]).toMatchObject({receipt_intent_id:intent.intent_id,evidence:{source_type:'expense_draft'}});
});

it('rejects quarantine and mismatched lines, then rolls back a consumed first item when another item fails',async()=>{
 await db.exec(candidate());const batch=randomUUID(),expense=randomUUID();const p={version:1,tenant_id:i.tenant,request_id:randomUUID(),batch_request_id:batch,expense_id:expense,context:'office',trip_id:null,stop_id:null};const intent=expenseReceiptIntentResultSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select prepare_finance_expense_receipt_intent($1) v',[p])).rows[0].v);expect((await financeAs<{v:unknown}>(db,i.operator,'select prepare_finance_expense_receipt_intent($1) v',[p])).rows[0].v).toEqual(intent);
 const image=await prepareReceiptImageCallback(db,'expense_draft',intent.intent_id);const item={id:expense,category:'office',description:'Material de escritório',amount_cents:12000,occurred_on:'2026-08-02',supplier_name:'Fornecedor do recibo',payee_type:'supplier',allocations:[],receipt_intent_id:intent.intent_id,receipt_artifact_id:image.reserved.artifact_id},command={version:1,tenant_id:i.tenant,request_id:batch,context:'office',description:'Lote protegido integralmente',reason:'Conferência segura de todos os itens',items:[item]};
 await expect(financeAs(db,i.operator,'select record_finance_expense_batch($1)',[command])).rejects.toThrow('upload_receipt_not_usable');await image.finalize();
 await expect(financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{...command,items:[{...item,id:randomUUID()}]}])).rejects.toThrow('upload_receipt_intent_mismatch');
 await expect(financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{...command,items:[item,{...item,id:randomUUID(),amount_cents:0}]}])).rejects.toThrow('finance_invalid_expense_amount_or_date');
 expect((await db.query('select count(*)::int n from secure_upload_private.expense_receipt_consumptions')).rows).toEqual([{n:0}]);expect((await db.query('select count(*)::int n from secure_upload_private.expense_receipt_batch_tickets')).rows).toEqual([{n:0}]);expect((await db.query('select count(*)::int n from finance_expense_items where id=$1',[expense])).rows).toEqual([{n:0}]);
 await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[command]);await db.exec('set constraints all immediate;set constraints all deferred');
 await db.query('update tenant_memberships set active=false where tenant_id=$1 and user_id=$2',[i.tenant,i.operator]);await expect(financeAs(db,i.operator,'select record_finance_expense_batch($1)',[command])).rejects.toThrow('finance_access_denied');
});
