// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createPublicManualMovementVoidDatabase} from './helpers/publicManualMovementVoidDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {movementVoidResultSchema} from '@/lib/financial/movementVoidCommandContract';
import {movementCorrectionPreviewSchema} from '@/lib/financial/movementCorrectionPreviewContract';
let db:Awaited<ReturnType<typeof createPublicManualMovementVoidDatabase>>;
beforeAll(async()=>{db=await createPublicManualMovementVoidDatabase();},30000);beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[i.operator]);});afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function setup(direction='out'){const original=randomUUID(),id=(await financeAs<{v:{movement_id:string}}>(db,i.operator,'select record_finance_movement($1) v',[{version:1,tenant_id:i.tenant,request_id:original,bank_account_id:i.account,direction,nature:'other',amount_cents:5000,occurred_on:'2026-08-15',description:'Movimento registrado por engano',beneficiary_name:'Fornecedor QA',reason:'Registro manual original para conferência'}])).rows[0].v.movement_id;const p=await preview(id);return {id,original,payload:{version:1,tenant_id:i.tenant,request_id:randomUUID(),movement_id:id,revision:p.revision,reason:'Registro duplicado conferido pelo financeiro'}};}
async function preview(id:string){return movementCorrectionPreviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select preview_finance_movement_correction($1,$2) v',[i.tenant,id])).rows[0].v);}
async function command(payload:unknown,actor=i.operator){return movementVoidResultSchema.parse((await financeAs<{v:unknown}>(db,actor,'select void_finance_manual_movement($1) v',[payload])).rows[0].v);}
it('enables a free preview and executes the public command under authenticated without granting the original writer',async()=>{const s=await setup(),p=await preview(s.id);expect(p.can_execute).toBe(true);const privateContext=(await db.query<{v:{revision:string}}>('select finance_private.movement_correction_context($1,$2) v',[i.tenant,s.id])).rows[0].v;expect(p.revision).toBe(privateContext.revision);const r=await command(s.payload);expect(r).toMatchObject({confirmed:true,movement_id:s.id,original_request_id:s.original,bank_money_transacted:false,recorded_balance_changed:true});expect((await preview(s.id))).toMatchObject({can_execute:false,eligible:false,effects:null});expect((await db.query("select has_function_privilege('authenticated','finance_private.void_manual_movement(jsonb)','EXECUTE') direct,has_function_privilege('authenticated','public.void_finance_manual_movement(jsonb)','EXECUTE') api")).rows[0]).toEqual({direct:false,api:true});});
it('recovers the same result by replay without a second correction or audit event',async()=>{const s=await setup(),first=await command(s.payload);expect(await command(s.payload)).toEqual(first);expect((await db.query('select count(*)::int n from finance_movement_voids')).rows[0]).toEqual({n:1});expect((await db.query("select count(*)::int n from finance_events where action='movement_voided'")).rows[0]).toEqual({n:1});await expect(command({...s.payload,reason:'Outro motivo diferente para a mesma chave'})).rejects.toThrow('finance_request_conflict');});
it('denies a mixed driver and cross-tenant request including an old replay',async()=>{const s=await setup();await command(s.payload);await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(command(s.payload)).rejects.toThrow('finance_access_denied');await db.query("delete from tenant_memberships where tenant_id=$1 and user_id=$2 and role='driver'",[i.tenant,i.operator]);await expect(command({...s.payload,tenant_id:i.otherTenant,request_id:randomUUID()})).rejects.toThrow('finance_access_denied');});
it('does not present or execute availability after guard drift even if the movement itself is free',async()=>{const s=await setup();await db.exec('alter table finance_movement_voids disable trigger finance_manual_movement_void_command');const p=await preview(s.id);expect(p.eligible).toBe(true);expect(p.can_execute).toBe(false);expect(p.revision).toBe(s.payload.revision);await expect(command(s.payload)).rejects.toThrow('finance_movement_correction_runtime_not_ready');expect((await db.query('select count(*)::int n from finance_movement_voids')).rows[0]).toEqual({n:0});});
it('preserves original private ACL and rejects anon/service-role invocation',async()=>{expect((await db.query("select has_function_privilege('anon','public.void_finance_manual_movement(jsonb)','EXECUTE') anon,has_function_privilege('service_role','public.void_finance_manual_movement(jsonb)','EXECUTE') service,has_function_privilege('authenticated','finance_private.movement_void_command_runtime_state()','EXECUTE') internal")).rows[0]).toEqual({anon:false,service:false,internal:false});expect((await db.query("select snapshot=finance_private.movement_void_command_runtime_state() valid from finance_private.movement_void_command_baseline")).rows[0]).toEqual({valid:true});});
it('rejects stale preview after a newly recorded obligation and keeps money intact',async()=>{const s=await setup();await db.query("insert into payables(tenant_id,supplier_name,category,amount,status,source_table,source_id) values($1,'Fornecedor','other',50,'approved','finance_movements',$2)",[i.tenant,s.id]);expect((await preview(s.id)).can_execute).toBe(false);await expect(command(s.payload)).rejects.toThrow('finance_movement_correction_changed');expect((await db.query('select count(*)::int n from finance_private.active_movements where id=$1',[s.id])).rows[0]).toEqual({n:1});});

it.each(['public.void_finance_manual_movement(jsonb)','finance_private.dispatch_manual_movement_void(jsonb)'])('disables preview when authenticated EXECUTE is revoked from %s',async signature=>{const s=await setup();await db.exec('revoke execute on function '+signature+' from authenticated');expect((await preview(s.id))).toMatchObject({eligible:true,can_execute:false,revision:s.payload.revision});await expect(command(s.payload)).rejects.toThrow('permission denied');});
