import {afterEach,expect,it,vi} from 'vitest';
import {createReceivableAgreementOutbox,lockReceivableAgreement,pendingReceivableAgreement,type ReceivableAgreementInput} from '@/lib/financial/receivableAgreementOutbox';
import {receivableAgreementStorageKey,type ReceivableAgreementCommand,type ReceivableAgreementResult} from '@/lib/financial/receivableAgreementContract';
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),receivable=crypto.randomUUID(),installment=crypto.randomUUID();
const input:ReceivableAgreementInput={receivable_id:receivable,action:'create',expected_revision:'a'.repeat(32),reason:'Acordo aprovado pelo responsável',installments:[{id:installment,amount_cents:'10000',due_on:'2026-10-10'}]};
const result=(command:ReceivableAgreementCommand):ReceivableAgreementResult=>({version:1,confirmed:true,tenant_id:tenant,actor_id:actor,request_id:command.request_id,event_id:crypto.randomUUID(),agreement_id:crypto.randomUUID(),receivable_id:receivable,action:command.action,cash_changed:false,effects:{}});
const direct=async<T>(_key:string,work:()=>Promise<T>)=>work();
const box=(send:(command:ReceivableAgreementCommand)=>Promise<ReceivableAgreementResult>,assertContext=vi.fn())=>createReceivableAgreementOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),assertContext,changed:vi.fn(),lock:direct,send,isDefinitive:()=>false});
afterEach(()=>{localStorage.clear();vi.restoreAllMocks();try{delete (navigator as {locks?:LockManager}).locks;}catch{}});

it('replays exactly the durable command after reload',async()=>{const first=vi.fn(async()=>{throw Error('resposta perdida');});await expect(box(first).submit(tenant,actor,input)).rejects.toThrow('perdida');const pending=pendingReceivableAgreement(localStorage,tenant,actor)!;const raw=localStorage.getItem(receivableAgreementStorageKey(tenant,actor));const second=vi.fn(async(command:ReceivableAgreementCommand)=>result(command));await expect(box(second).recover(tenant,actor)).resolves.toMatchObject({request_id:pending.payload.request_id});expect(second).toHaveBeenCalledWith(JSON.parse(raw!).payload);expect(localStorage.getItem(receivableAgreementStorageKey(tenant,actor))).toBeNull();});
it('serializes fallback and uses the browser lock across tabs',async()=>{const order:string[]=[];let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});const one=lockReceivableAgreement('agreement',async()=>{order.push('one');await gate;return 1;}),two=lockReceivableAgreement('agreement',async()=>{order.push('two');return 2;});await vi.waitFor(()=>expect(order).toEqual(['one']));release();expect(await Promise.all([one,two])).toEqual([1,2]);expect(order).toEqual(['one','two']);const request=vi.fn(async(_key:string,work:()=>Promise<number>)=>work());Object.defineProperty(navigator,'locks',{configurable:true,value:{request}});await expect(lockReceivableAgreement('native',async()=>3)).resolves.toBe(3);expect(request).toHaveBeenCalled();});
it('keeps the original request when tenant or actor changes during transport',async()=>{let currentActor=actor;const assert=vi.fn((expectedTenant:string,expectedActor:string)=>{if(expectedTenant!==tenant||expectedActor!==currentActor)throw Error('sessão original');});const send=vi.fn(async(command:ReceivableAgreementCommand)=>{currentActor=crypto.randomUUID();return result(command);});await expect(box(send,assert).submit(tenant,actor,input)).rejects.toThrow('sessão original');expect(pendingReceivableAgreement(localStorage,tenant,actor)?.payload.receivable_id).toBe(receivable);expect(pendingReceivableAgreement(localStorage,tenant,currentActor)).toBeNull();});
it('does not erase a command replaced by a storage event from another tab',async()=>{const key=receivableAgreementStorageKey(tenant,actor),foreign=crypto.randomUUID();const send=vi.fn(async(command:ReceivableAgreementCommand)=>{const row=JSON.parse(localStorage.getItem(key)!);row.payload.request_id=foreign;localStorage.setItem(key,JSON.stringify(row));return result(command);});await box(send).submit(tenant,actor,input);expect(JSON.parse(localStorage.getItem(key)!).payload.request_id).toBe(foreign);});
