import {afterEach,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {ReceivableAdjustmentDialog} from '@/components/financial/ReceivableAdjustmentDialog';
import {adjustmentPreview,adjustmentIds as i} from './helpers/receivableAdjustmentFixture';
import {useEffect} from 'react';
const m=vi.hoisted(()=>({read:vi.fn(),history:vi.fn(),send:vi.fn()}));vi.mock('@/lib/financial/receivableAdjustmentClient',async original=>({...await original<typeof import('@/lib/financial/receivableAdjustmentClient')>(),readReceivableAdjustment:(...v:unknown[])=>m.read(...v),readReceivableAdjustmentHistory:(...v:unknown[])=>m.history(...v),sendReceivableAdjustment:(v:unknown)=>m.send(v)}));afterEach(cleanup);
vi.mock('@/components/financial/ReceivableInstallmentAllocationFields',()=>({ReceivableInstallmentAllocationFields:({onChange}:{onChange:(value:Record<string,never>)=>void})=>{useEffect(()=>onChange({}),[onChange]);return null;}}));
it('shows nominal/cash/discount separately and removes permission on edits or refetch',async()=>{localStorage.clear();m.read.mockResolvedValue(adjustmentPreview);m.history.mockResolvedValue({version:1,tenant_id:i.tenant,actor_id:i.actor,receivable_id:i.receivable,offset:0,limit:30,total:0,next_offset:null,revision:'a'.repeat(32),rows:[],can_execute:false});const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><ReceivableAdjustmentDialog tenant={i.tenant} actor={i.actor} receivable={i.receivable} onClose={()=>{}}/></QueryClientProvider>);fireEvent.change(screen.getByLabelText('Valor (R$)'),{target:{value:'100'}});fireEvent.click(screen.getByText('Conferir valores e autorização'));await screen.findByLabelText('Motivo');expect(screen.getByText('Cliente Alfa / Fatura 123')).toBeInTheDocument();expect(screen.getByRole('table')).toHaveTextContent('900,00');let resolve!:(v:typeof adjustmentPreview)=>void;m.read.mockImplementation(()=>new Promise<typeof adjustmentPreview>(done=>{resolve=done;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-receivable-adjustment-preview']});});await waitFor(()=>expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument());await act(async()=>resolve(adjustmentPreview));await screen.findByLabelText('Motivo');fireEvent.change(screen.getByLabelText('Categoria'),{target:{value:'loss'}});expect(screen.queryByLabelText('Motivo')).not.toBeInTheDocument();expect(m.send).not.toHaveBeenCalled();});
