import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {ReceivableAgreementPositionPanel} from "@/components/financial/ReceivableAgreementPositionPanel";
import {ReceivableAgreementDialog} from "@/components/financial/ReceivableAgreementDialog";
import {receivableAgreementStorageKey} from "@/lib/financial/receivableAgreementContract";
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),receivable=crypto.randomUUID(),report=crypto.randomUUID(),agreement=crypto.randomUUID(),installment=crypto.randomUUID();
const position={version:1 as const,tenant_id:tenant,actor_id:actor,verified:true,issue:null,receivable_id:receivable,agreement_id:agreement,revision:"a".repeat(32),status:"active" as const,open_cents:"12500",scheduled_open_cents:"12500",unallocated_open_cents:"0",requires_reallocation:false,history_count:1,installments:[{id:installment,agreement_id:agreement,ordinal:1,due_on:"2026-10-10",amount_cents:"12500",cash_cents:"0",credit_cents:"0",discount_cents:"0",loss_cents:"0",open_cents:"12500",status:"open" as const}]};
const mocks=vi.hoisted(()=>({position:vi.fn(),closing:vi.fn(),history:vi.fn()}));
vi.mock("@/lib/financial/receivableAgreementClient",()=>({
 readReceivableAgreementPosition:(...args:unknown[])=>mocks.position(...args),
 readClosingReceivableAgreement:(...args:unknown[])=>mocks.closing(...args),
 readReceivableAgreementHistory:(...args:unknown[])=>mocks.history(...args),
 previewReceivableAgreement:vi.fn(),sendReceivableAgreement:vi.fn(),
 receivableAgreementError:()=> "Falha na agenda",
}));
const mount=(node:React.ReactNode)=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{node}</QueryClientProvider>);
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();});
afterEach(cleanup);
it("shows the canonical installment in an invoice without creating another title",async()=>{mocks.position.mockResolvedValue(position);mount(<ReceivableAgreementPositionPanel tenant={tenant} actor={actor} receivable={receivable}/>);expect(await screen.findByRole("region",{name:"Parcelas da renegociação"})).toHaveTextContent("R$ 125,00");expect(screen.getByText(/título original permanece único/)).toBeInTheDocument();expect(mocks.position).toHaveBeenCalledWith(tenant,actor,receivable);});
it("resolves the receivable through a closing report in the same tenant",async()=>{mocks.closing.mockResolvedValue({receivable_id:receivable,agreement:position});mount(<ReceivableAgreementPositionPanel tenant={tenant} actor={actor} report={report}/>);expect(await screen.findByText(/10\/10\/2026/)).toBeInTheDocument();expect(mocks.closing).toHaveBeenCalledWith(tenant,actor,report);});
it("retries the agreement position without forcing the dialog to be reopened",async()=>{mocks.position.mockRejectedValueOnce(Error("offline")).mockResolvedValueOnce(position);mocks.history.mockResolvedValue({rows:[],total:0,next_offset:null});mount(<ReceivableAgreementDialog tenant={tenant} actor={actor} receivable={receivable} onClose={vi.fn()}/>);expect(await screen.findByRole("alert")).toHaveTextContent("Falha na agenda");fireEvent.click(screen.getByRole("button",{name:"Tentar novamente"}));expect(await screen.findByText(/Saldo aberto/)).toBeInTheDocument();expect(mocks.position).toHaveBeenCalledTimes(2);});
it("discards a corrupt saved agreement and only then enables a fresh proposal",async()=>{const key=receivableAgreementStorageKey(tenant,actor);localStorage.setItem(key,'{"broken":true}');mocks.position.mockResolvedValue(position);mocks.history.mockResolvedValue({rows:[],total:0,next_offset:null});mount(<ReceivableAgreementDialog tenant={tenant} actor={actor} receivable={receivable} onClose={vi.fn()}/>);const amount=await screen.findByLabelText("Valor da parcela 1 (R$)");expect(amount).toBeDisabled();expect(screen.getByRole("alert")).toHaveTextContent("bloqueadas até o descarte");fireEvent.click(screen.getByRole("button",{name:"Descartar pedido incompatível"}));expect(localStorage.getItem(key)).toBeNull();expect(amount).toBeEnabled();});
it("keeps agreement history pagination visible after the agreement is revoked",async()=>{mocks.position.mockResolvedValue({...position,status:"revoked",installments:[]});mocks.history.mockImplementation((_tenant,_actor,_receivable,offset)=>Promise.resolve({rows:[],total:31,next_offset:offset===0?30:null}));mount(<ReceivableAgreementDialog tenant={tenant} actor={actor} receivable={receivable} onClose={vi.fn()}/>);const next=await screen.findByRole("button",{name:"Próximas versões"});expect(next).toBeEnabled();fireEvent.click(next);await vi.waitFor(()=>expect(mocks.history).toHaveBeenLastCalledWith(tenant,actor,receivable,30,30,position.revision));});
it("stops adding installments at the server contract limit",async()=>{mocks.position.mockResolvedValue(position);mocks.history.mockResolvedValue({rows:[],total:0,next_offset:null});mount(<ReceivableAgreementDialog tenant={tenant} actor={actor} receivable={receivable} onClose={vi.fn()}/>);const add=await screen.findByRole("button",{name:"Adicionar parcela"});for(let count=1;count<100;count++)fireEvent.click(add);expect(screen.getByText("100 de 100 parcelas.")).toBeInTheDocument();expect(add).toBeDisabled();expect(screen.getAllByLabelText(/Valor da parcela \d+ \(R\$\)/)).toHaveLength(100);});
