import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {ReceivableFinancialDialog} from '@/components/financial/ReceivableFinancialDialog';
const state=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn(),children:vi.fn(),context:{} as Record<string,unknown>}));
vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentTenant:{id:'11111111-1111-4111-8111-111111111111'}})}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'22222222-2222-4222-8222-222222222222'}})}));
vi.mock('@/hooks/useReceivableFinancial',()=>({useReceivableFinancial:()=>({query:{data:state.context,isFetching:false,error:null,refetch:vi.fn()},submit:state.submit,isPending:false,pending:null,recoveryError:null})}));
vi.mock('@/hooks/useFinancialPayments',()=>({PAYMENT_METHODS:[],PAYMENT_METHOD_LABELS:{},uploadPaymentAttachment:vi.fn()}));
vi.mock('@/lib/financial/receivablePaymentsClient',()=>({readReceivablePayments:state.read,ReceivablePaymentsChangedError:class extends Error{}}));
vi.mock('@/components/financial/LegacyReceivableAssociation',()=>({LegacyReceivableAssociation:()=>{state.children();return null;}}));
vi.mock('@/components/financial/ReceiptAllocationCorrection',()=>({ReceiptAllocationCorrection:()=>null}));
vi.mock('@/components/financial/ReceivableMovementPicker',()=>({ReceivableMovementPicker:()=>null}));
import {ReceivablePaymentsChangedError} from '@/lib/financial/receivablePaymentsClient';
const tenant='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',title=crypto.randomUUID(),old=crypto.randomUUID();
const row={id:old,amount_cents:1000,received_at:'2026-08-01T12:00:00Z',notes:'Recebimento antigo',bank_account_name:'Banco',reversed_at:null,reversal_reason:null,credit_id:null,allocation_correction:null};
function init(){state.context={actor_id:actor,reference:'Título',revision:'a'.repeat(32),amount_cents:2000,received_cents:1000,open_cents:1000,can_reverse:true,can_receive:false,can_reconcile:false,payments:[],bank_accounts:[]};state.read.mockImplementation(({page}:{page:number})=>Promise.resolve({page,page_size:50,total:501,revision:'b'.repeat(32),rows:[{...row,id:page===11?old:`page-${page}`,notes:`Página de recebimentos ${page}`}]}));}
function mount(cache=new QueryClient()){return render(<QueryClientProvider client={cache}><ReceivableFinancialDialog tenantId={tenant} receivableId={title} onClose={()=>{}}/></QueryClientProvider>);}
afterEach(()=>{cleanup();state.read.mockReset();state.submit.mockReset();state.children.mockReset();});
it('selects a payment beyond the former 500 limit and submits the financial revision, not the list revision',async()=>{init();state.submit.mockResolvedValue({action:'reverse'});mount();for(let page=1;page<=10;page++){await screen.findByText(new RegExp(`Página de recebimentos ${page}$`));fireEvent.click(screen.getByText('Próxima página de recebimentos'));}await screen.findByText(/Página de recebimentos 11$/);fireEvent.click(screen.getByText('Selecionar para devolução'));fireEvent.click(screen.getByLabelText('Confirmo que o dinheiro já foi devolvido ao pagador'));fireEvent.change(screen.getByLabelText('Motivo da operação'),{target:{value:'Devolução já realizada ao pagador'}});fireEvent.click(screen.getByText('Confirmar operação'));await screen.findByText(/Pedido confirmado/);expect(state.submit).toHaveBeenCalledWith(expect.objectContaining({action:'reverse',payment_id:old,expected_revision:'a'.repeat(32)}));expect(state.context.payments).toEqual([]);});
it('clears selection on query refresh/error and prevents a refund with stale selection',async()=>{init();const cache=new QueryClient();mount(cache);await screen.findByText(/Página de recebimentos 1$/);fireEvent.click(screen.getByText('Selecionar para devolução'));expect(screen.getByText(/Selecionado: page-1/)).toBeInTheDocument();let reject!:(error:Error)=>void;state.read.mockImplementation(()=>new Promise((_resolve,fail)=>{reject=fail;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-receivable-payments',tenant,actor,title]});});await screen.findByText('Consultando recebimentos…');expect(screen.queryByText(/Selecionado: page-1/)).not.toBeInTheDocument();await act(async()=>reject(Error('offline')));expect(screen.getByText('Confirmar operação')).toBeDisabled();expect(state.submit).not.toHaveBeenCalled();});
it('recovers a changed page with a fresh generation under infinite cache lifetime',async()=>{init();state.read.mockReset().mockResolvedValueOnce({page:1,page_size:50,total:51,revision:'b'.repeat(32),rows:[row]}).mockRejectedValueOnce(new ReceivablePaymentsChangedError()).mockResolvedValueOnce({page:1,page_size:50,total:1,revision:'c'.repeat(32),rows:[{...row,notes:'Consulta renovada'}]});mount(new QueryClient({defaultOptions:{queries:{staleTime:Infinity}}}));await screen.findByText(/Recebimento antigo/);fireEvent.click(screen.getByText('Próxima página de recebimentos'));await screen.findByText(/Consulta renovada/);expect(state.read).toHaveBeenCalledTimes(3);expect(state.read.mock.calls[2][0]).toMatchObject({page:1,expectedRevision:null});});

it('does not mount fifty association queries until a receipt is expanded',async()=>{init();state.read.mockResolvedValue({page:1,page_size:50,total:50,revision:'b'.repeat(32),rows:Array.from({length:50},()=>({...row,id:crypto.randomUUID()}))});mount();await screen.findAllByText('Conferir vínculos');expect(state.children).not.toHaveBeenCalled();fireEvent.click(screen.getAllByText('Conferir vínculos')[0]);expect(state.children).toHaveBeenCalledTimes(1);});
it('keeps manual correction highlighted without opening auxiliary queries',async()=>{init();state.read.mockResolvedValue({page:1,page_size:50,total:1,revision:'b'.repeat(32),rows:[{...row,allocation_correction:{id:crypto.randomUUID(),actor_id:actor,actor_name:'Ana',reason:'Título incorreto corrigido',created_at:'2026-09-10T12:00:00Z'}}]});mount();const badge=await screen.findByText('Ajuste manual');expect(badge.parentElement).toHaveClass('border-amber-600');expect(screen.getByText(/Correção de vínculo por Ana/)).toBeInTheDocument();expect(state.children).not.toHaveBeenCalled();});
it('shows the unloading origin issue separately from totals and preserves an authorized refund',async()=>{init();state.context={...state.context,source_issue:'finance_unloading_source_mismatch',source_revision:'c'.repeat(32),requires_reconciliation:false,can_receive:false,can_reverse:true};state.submit.mockResolvedValue({action:'reverse'});mount();await screen.findByText(/A origem da descarga diverge deste título/);expect(screen.queryByText(/O histórico e as projeções divergem/)).not.toBeInTheDocument();expect(screen.queryByRole('option',{name:'Registrar recebimento'})).not.toBeInTheDocument();fireEvent.click(await screen.findByText('Selecionar para devolução'));fireEvent.click(screen.getByLabelText('Confirmo que o dinheiro já foi devolvido ao pagador'));fireEvent.change(screen.getByLabelText('Motivo da operação'),{target:{value:'Dinheiro devolvido ao pagador'}});expect(screen.getByText('Confirmar operação')).not.toBeDisabled();fireEvent.click(screen.getByText('Confirmar operação'));await screen.findByText(/Pedido confirmado: Estornar recebimento/);expect(state.submit).toHaveBeenCalledWith(expect.objectContaining({action:'reverse',payment_id:'page-1',expected_revision:'a'.repeat(32)}));});
