import {beforeEach,expect,it,vi} from 'vitest';
import {createReceivableAdjustmentOutbox,pendingReceivableAdjustment} from '@/lib/financial/receivableAdjustmentOutbox';
import {adjustmentIds as i,adjustmentInput,adjustmentResult} from './helpers/receivableAdjustmentFixture';
beforeEach(()=>localStorage.clear());
function setup(){const send=vi.fn(),changed=vi.fn();return{send,outbox:createReceivableAdjustmentOutbox({storage:localStorage,uuid:()=>i.request,changed,assertContext:()=>{},lock:async<T>(_key:string,work:()=>Promise<T>)=>work(),send})};}
it('persists before send and replays exact request after unknown',async()=>{const {send,outbox}=setup();send.mockImplementationOnce(async()=>{expect(pendingReceivableAdjustment(localStorage,i.tenant,i.actor)?.payload.request_id).toBe(i.request);throw Error('network');}).mockResolvedValueOnce({data:adjustmentResult,error:null});await expect(outbox.submit(i.tenant,i.actor,adjustmentInput)).rejects.toThrow();expect(pendingReceivableAdjustment(localStorage,i.tenant,i.actor)).not.toBeNull();await expect(outbox.recover(i.tenant,i.actor)).resolves.toMatchObject({receivable_id:i.receivable});expect(send.mock.calls[0][0]).toEqual(send.mock.calls[1][0]);expect(pendingReceivableAdjustment(localStorage,i.tenant,i.actor)).toBeNull();});
it('clears known first rejection but retains the same rejection after an unknown attempt',async()=>{const {send,outbox}=setup();send.mockResolvedValue({data:null,error:{code:'40001',message:'changed'}});await expect(outbox.submit(i.tenant,i.actor,adjustmentInput)).rejects.toMatchObject({code:'40001'});expect(pendingReceivableAdjustment(localStorage,i.tenant,i.actor)).toBeNull();send.mockRejectedValueOnce(Error('lost'));await expect(outbox.submit(i.tenant,i.actor,adjustmentInput)).rejects.toThrow();await expect(outbox.recover(i.tenant,i.actor)).rejects.toMatchObject({code:'40001'});expect(pendingReceivableAdjustment(localStorage,i.tenant,i.actor)).not.toBeNull();});
it('rejects cross actor or release application identities and preserves original request',async()=>{const {send,outbox}=setup();send.mockResolvedValue({data:{...adjustmentResult,actor_id:i.receivable},error:null});await expect(outbox.submit(i.tenant,i.actor,adjustmentInput)).rejects.toThrow();expect(pendingReceivableAdjustment(localStorage,i.tenant,i.actor)).not.toBeNull();await expect(outbox.submit(i.tenant,i.actor,{...adjustmentInput,amount_cents:'1'})).rejects.toThrow();expect(send).toHaveBeenCalledTimes(1);});
it('does not remove another tab record after receiving its own result',async()=>{const {send,outbox}=setup();send.mockImplementation(async()=>{const key=`agvlog:receivable-adjustment:v1:${i.tenant}:${i.actor}`;const row=JSON.parse(localStorage.getItem(key)!);row.payload.request_id=i.event;localStorage.setItem(key,JSON.stringify(row));return{data:adjustmentResult,error:null};});await outbox.submit(i.tenant,i.actor,adjustmentInput);expect(pendingReceivableAdjustment(localStorage,i.tenant,i.actor)?.payload.request_id).toBe(i.event);});
