import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {MemoryRouter} from 'react-router-dom';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import Receivables from '@/pages/Receivables';
const tenant='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',title='33333333-3333-4333-8333-333333333333',supplier='44444444-4444-4444-8444-444444444444';
const mocks=vi.hoisted(()=>({from:vi.fn(),read:vi.fn(),origin:vi.fn(),update:vi.fn(),eq:vi.fn(),toast:vi.fn(),repair:vi.fn(),correction:vi.fn(),role:'admin'}));
vi.mock('@/components/financial/UnloadingProjectionRepairDialog',()=>({UnloadingProjectionRepairDialog:(props:{tenant:string;actor:string;chargeId:string;onClose:()=>void})=>{mocks.repair(props);return <button onClick={props.onClose}>Fechar reparação consultada</button>;}}));
vi.mock('@/components/financial/UnloadingOriginCorrectionDialog',()=>({UnloadingOriginCorrectionDialog:(props:{tenant:string;actor:string;chargeId:string;onOpenChange:(open:boolean)=>void})=>{mocks.correction(props);return <button onClick={()=>props.onOpenChange(false)}>Fechar correção consultada</button>;}}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:mocks.from}}));
vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentTenant:{id:'11111111-1111-4111-8111-111111111111'},currentRole:mocks.role})}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'22222222-2222-4222-8222-222222222222'}})}));
vi.mock('@/hooks/useClients',()=>({useClients:()=>({data:[]})}));
vi.mock('@/lib/financial/receivablesPageClient',()=>({readReceivablesPage:mocks.read}));
vi.mock('@/hooks/useReceivablePortfolio',()=>({useReceivablePortfolio:()=>({}),portfolioValue:()=>'-'}));
vi.mock('@/components/financial/FiscalXmlUpload',()=>({default:()=> <div>Importação XML disponível</div>}));
vi.mock('@/components/financial/ReceivablePaymentDialog',()=>({default:()=>null}));
vi.mock('@/hooks/useSonnerToast',()=>({useSonnerToast:()=>({success:mocks.toast,error:mocks.toast})}));
const row={id:title,tenant_id:tenant,description:'Frete de referência',amount:150,received_amount:0,status:'pending',client_id:supplier,client_invoice_id:null,due_date:'2026-09-20',clients:null,notes:'Nota original',invoice_number:'NF original'};
beforeEach(()=>{vi.clearAllMocks();mocks.role='admin';mocks.read.mockResolvedValue({rows:[row],page:1,page_size:50,total:1,total_unfiltered:1});mocks.origin.mockResolvedValue({data:{id:crypto.randomUUID(),tenant_id:tenant,receivable_id:title,supplier_id:supplier,delivery_stop_id:crypto.randomUUID(),amount_cents:15000,source_snapshot:{supplier_name:'Fornecedor da entrega'}},error:null});const chain={eq:mocks.eq,select:()=>chain,single:async()=>({data:row,error:null}),maybeSingle:mocks.origin};mocks.eq.mockImplementation(()=>chain);mocks.update.mockImplementation(()=>chain);mocks.from.mockImplementation(()=>({select:()=>chain,update:mocks.update}));});
afterEach(cleanup);
function show(){render(<MemoryRouter><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><Receivables/></QueryClientProvider></MemoryRouter>);}
async function edit(){await screen.findByText(row.description);fireEvent.click(screen.getByText(row.description));return screen.findByRole('dialog');}
it('identifies discharge through the tenant-scoped FK and sends only the permitted fields',async()=>{show();const dialog=await edit();await within(dialog).findByText(/Fornecedor devedor: Fornecedor da entrega/);expect(mocks.eq).toHaveBeenCalledWith('tenant_id',tenant);expect(mocks.eq).toHaveBeenCalledWith('receivable_id',title);expect(within(dialog).queryByText('Importação XML disponível')).not.toBeInTheDocument();expect(within(dialog).getByDisplayValue('150')).toBeDisabled();expect(within(dialog).queryByLabelText('Status do título manual')).not.toBeInTheDocument();fireEvent.change(within(dialog).getByDisplayValue(row.description),{target:{value:'Descrição ajustada'}});fireEvent.click(within(dialog).getByText('Salvar'));await waitFor(()=>expect(mocks.update).toHaveBeenCalled());expect(mocks.update.mock.calls[0][0]).toEqual({description:'Descrição ajustada',due_date:'2026-09-20',invoice_number:'NF original',notes:'Nota original',updated_by:actor,updated_at:expect.any(String)});expect(mocks.eq).toHaveBeenCalledWith('id',title);expect(mocks.eq.mock.calls.filter(([field])=>field==='tenant_id').length).toBeGreaterThanOrEqual(2);});
it('blocks saving when origin cannot be verified',async()=>{mocks.origin.mockResolvedValue({data:null,error:Error('network')});show();const dialog=await edit();await within(dialog).findByText(/Não foi possível verificar a origem/);expect(within(dialog).getByText('Salvar')).toBeDisabled();expect(mocks.update).not.toHaveBeenCalled();});
it('does not query origin for a new title',async()=>{show();fireEvent.click(screen.getByRole('button',{name:/Novo Título/}));await screen.findByRole('dialog');expect(screen.getByText('Importação XML disponível')).toBeInTheDocument();expect(mocks.origin).not.toHaveBeenCalled();});


it('does not infer unloading origin from a description and keeps ordinary editing available',async()=>{mocks.origin.mockResolvedValue({data:null,error:null});show();const dialog=await edit();await within(dialog).findByText('Importação XML disponível');expect(within(dialog).getByDisplayValue('150')).not.toBeDisabled();expect(within(dialog).getByLabelText('Status do título manual')).toBeInTheDocument();});
it('keeps save blocked while lookup is unresolved and rejects a response from another tenant',async()=>{let resolve!:(value:unknown)=>void;mocks.origin.mockImplementation(()=>new Promise(done=>{resolve=done;}));show();const dialog=await edit();expect(within(dialog).getByText('Salvar')).toBeDisabled();resolve({data:{id:crypto.randomUUID(),tenant_id:crypto.randomUUID(),receivable_id:title,supplier_id:supplier,delivery_stop_id:crypto.randomUUID(),amount_cents:15000,source_snapshot:{}},error:null});await within(dialog).findByText(/Não foi possível verificar a origem/);expect(within(dialog).getByText('Salvar')).toBeDisabled();expect(mocks.update).not.toHaveBeenCalled();});

it('opens read-only repair for the charge identified by the FK and closes it without a write',async()=>{show();const dialog=await edit();fireEvent.click(await within(dialog).findByText('Conferir reparação do título'));const source=await mocks.origin.mock.results[0].value;expect(mocks.repair).toHaveBeenCalledWith(expect.objectContaining({tenant,actor,chargeId:source.data.id}));fireEvent.click(screen.getByText('Fechar reparação consultada'));expect(screen.queryByText('Fechar reparação consultada')).not.toBeInTheDocument();expect(mocks.update).not.toHaveBeenCalled();});

it('opens collection correction for the FK charge only for an administrator and closes without a write',async()=>{show();const dialog=await edit();fireEvent.click(await within(dialog).findByText('Corrigir cobrança da descarga'));const source=await mocks.origin.mock.results[0].value;expect(mocks.correction).toHaveBeenCalledWith(expect.objectContaining({tenant,actor,chargeId:source.data.id}));fireEvent.click(screen.getByText('Fechar correção consultada'));expect(screen.queryByText('Fechar correção consultada')).not.toBeInTheDocument();expect(mocks.update).not.toHaveBeenCalled();});
it('does not expose collection correction to an operator',async()=>{mocks.role='operator';show();const dialog=await edit();await within(dialog).findByText(/Fornecedor devedor: Fornecedor da entrega/);expect(within(dialog).queryByText('Corrigir cobrança da descarga')).not.toBeInTheDocument();expect(mocks.correction).not.toHaveBeenCalled();});
