import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {ReceivableHistoryWorkspace,ReceivableHistoryDialog} from '@/components/financial/ReceivableHistoryDialog';
const access=vi.hoisted(()=>({allowed:true}));vi.mock('@/hooks/useTenant',()=>({useTenant:()=>({currentRole:'operator'})}));vi.mock('@/hooks/useFinanceLedger',()=>({useFinanceAccess:()=>({data:access.allowed,error:null,isPending:false,isFetchedAfterMount:true})}));
const read=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/receivableHistoryClient',()=>({readReceivableHistory:read,ReceivableHistoryChangedError:class extends Error{}}));
import {ReceivableHistoryChangedError} from '@/lib/financial/receivableHistoryClient';
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),title=crypto.randomUUID();
const snapshot={description:'Frete preservado',invoice_number:'NF 123',status:'partial',due_date:'2026-09-01',amount_cents:'100000',received_cents:'30000',client_id:actor,payer:{id:actor,tenant_id:tenant,company_name:'Fornecedor original'},source:{order_id:null,fiscal_document_id:null,load_id:null,client_invoice_id:null,closing_report_id:null},issues:[]};
function fixture(){return {version:1,tenant_id:tenant,receivable_id:null,revision:'a'.repeat(32),page:1,page_size:50,total:1,captured_at:'2026-09-10T12:00:00Z',coverage:{starts_at:'2026-09-10T10:00:00Z',baseline_kind:'existing_tenant',capture_basis:'transaction_capture_not_commit'},rows:[{event_order:'1',receivable_id:title,operation:'DELETE',captured_at:'2026-09-10T11:00:00Z',transaction_id:'1',actor_kind:'authenticated',actor_id:actor,actor_name:'Ana',before:snapshot,after:null,changed_fields:[]}],limitations:['not_a_historical_balance']};}
function mount(){const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={cache}><ReceivableHistoryWorkspace tenant={tenant} actor={actor}/></QueryClientProvider>);return cache;}
afterEach(()=>{cleanup();read.mockReset();access.allowed=true;});
it('shows a deleted title and exact captured amounts without claiming manual action or past balance',async()=>{read.mockResolvedValue(fixture());mount();await screen.findByText('Título excluído — histórico preservado');expect(screen.getByText(/R\$ 1.000,00/)).toBeInTheDocument();expect(screen.getByText(/Usuário autenticado: Ana/)).toBeInTheDocument();expect(screen.getByText(/estado anterior à captura é desconhecido/)).toBeInTheDocument();expect(read.mock.calls[0][0]).toMatchObject({tenantId:tenant,receivableId:null,page:1,expectedRevision:null});});
it('validates UUID filters and resets pagination on revision change without mixing rows',async()=>{const first=fixture();first.total=51;read.mockResolvedValueOnce(first).mockRejectedValueOnce(new ReceivableHistoryChangedError()).mockResolvedValue(fixture());mount();await screen.findByText('Título excluído — histórico preservado');fireEvent.change(screen.getByLabelText('ID do título (opcional)'),{target:{value:'invalid'}});fireEvent.click(screen.getByText('Consultar alterações'));expect(screen.getByRole('alert')).toHaveTextContent('ID de título válido');expect(read).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByText('Próxima página'));await screen.findByText(/histórico mudou durante a navegação/);await screen.findByText('Título excluído — histórico preservado');expect(read.mock.calls[1][0]).toMatchObject({page:2,expectedRevision:'a'.repeat(32)});expect(read.mock.calls[2][0]).toMatchObject({page:1,expectedRevision:null});});
it('hides cached events during refetch and failures',async()=>{read.mockResolvedValue(fixture());const cache=mount();await screen.findByText('Título excluído — histórico preservado');let reject!:(error:Error)=>void;read.mockImplementation(()=>new Promise((_resolve,fail)=>{reject=fail;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-receivable-history',tenant,actor]});});await screen.findByText('Consultando versões capturadas…');expect(screen.queryByText('Título excluído — histórico preservado')).not.toBeInTheDocument();await act(async()=>reject(Error('offline')));await screen.findByText(/Nenhum dado anterior foi mantido/);expect(screen.queryByText('Frete preservado')).not.toBeInTheDocument();});
it('distinguishes system capture and unknown cents from zero',async()=>{const data=fixture();Object.assign(data.rows[0],{actor_kind:'system',actor_id:null,actor_name:null,before:{...snapshot,amount_cents:null,received_cents:null,issues:['amount_invalid']}});read.mockResolvedValue(data);mount();await screen.findByText('Origem: sistema');expect(screen.getByText('Valor nominal: Indeterminado')).toBeInTheDocument();expect(screen.queryByText('R$ 0,00')).not.toBeInTheDocument();});

it('does not query history when the financial access check rejects a mixed profile',()=>{access.allowed=false;render(<QueryClientProvider client={new QueryClient()}><ReceivableHistoryDialog tenant={tenant} actor={actor} onClose={()=>{}}/></QueryClientProvider>);expect(screen.getByText('Acesso financeiro não permitido.')).toBeInTheDocument();expect(read).not.toHaveBeenCalled();});
it('submits an explicit UUID filter rather than relying on currently visible titles',async()=>{read.mockResolvedValue(fixture());mount();await screen.findByText('Título excluído — histórico preservado');const deleted=crypto.randomUUID();fireEvent.change(screen.getByLabelText('ID do título (opcional)'),{target:{value:deleted}});fireEvent.click(screen.getByText('Consultar alterações'));await act(async()=>{});expect(read.mock.calls.at(-1)?.[0]).toMatchObject({tenantId:tenant,receivableId:deleted,page:1,expectedRevision:null});});

it('fetches a new first page after revision rejection even with an indefinitely fresh cached first page',async()=>{const first=fixture();first.total=51;const renewed=fixture();renewed.revision='b'.repeat(32);renewed.rows[0].before={...snapshot,description:'Versão atualizada após revisão'};read.mockResolvedValueOnce(first).mockRejectedValueOnce(new ReceivableHistoryChangedError()).mockResolvedValueOnce(renewed);const cache=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity}}});render(<QueryClientProvider client={cache}><ReceivableHistoryWorkspace tenant={tenant} actor={actor}/></QueryClientProvider>);await screen.findByText(/Frete preservado/);fireEvent.click(screen.getByText('Próxima página'));await screen.findByText(/Versão atualizada após revisão/);expect(read).toHaveBeenCalledTimes(3);expect(read.mock.calls[2][0]).toMatchObject({page:1,expectedRevision:null});expect(screen.queryByText(/Frete preservado/)).not.toBeInTheDocument();expect(screen.getByText(/histórico mudou durante a navegação/)).toBeInTheDocument();});
