import {act,cleanup,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {RecordedCostCard,RecordedCostSummary} from '@/components/financial/RecordedCostSummary';
import {useRecordedCostSummary} from '@/hooks/useRecordedCostSummary';
const read=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/recordedCostSummaryClient',()=>({readRecordedCostSummary:read}));
const result={total_count:1501,cancelled_count:1,invalid_count:0,payroll_unclassified_count:0,recorded_date_count:1,totals_valid:true,total_cents:'50000',categories:[{category:'payroll',item_count:1501,amount_cents:'50000'}],cost_centers:[{cost_center_id:null,cost_center_name:null,item_count:1501,amount_cents:'50000'}],months:[{month:'2026-09',item_count:1501,amount_cents:'50000'}]};
beforeEach(()=>{vi.clearAllMocks();read.mockResolvedValue(result);});afterEach(cleanup);
function Fixture(){const state=useRecordedCostSummary('tenant','actor',{from:null,to:null,category:'payroll',costCenter:'unassigned'});return <><RecordedCostCard state={state}/><RecordedCostSummary state={state} onManage={()=>{}}/></>;}
function open(cache=new QueryClient()){return render(<QueryClientProvider client={cache}><Fixture/></QueryClientProvider>);}
it('presents server counts and explicit excluded coverage without calling costs bank outflow',async()=>{open();expect(await screen.findByText(/1501 registro\(s\) · 1 cancelado/)).toBeInTheDocument();expect(screen.getAllByText('R$ 500,00').length).toBeGreaterThan(0);expect(screen.getByText(/Custo não é saída bancária/)).toBeInTheDocument();expect(screen.getByText(/ordens de manutenção/)).toBeInTheDocument();expect(screen.getAllByRole('img')).toHaveLength(3);expect(read).toHaveBeenCalledWith('tenant',{from:null,to:null,category:'payroll',costCenter:'unassigned'});});
it('shows invalid costs as unavailable with undated and unclassified payroll diagnostics',async()=>{read.mockResolvedValue({...result,invalid_count:1,payroll_unclassified_count:1,totals_valid:false,total_cents:null,categories:[{category:null,item_count:1,amount_cents:null}],cost_centers:[],months:[{month:null,item_count:1,amount_cents:null}]});open();expect(await screen.findByRole('alert')).toHaveTextContent('folha sem classificação');expect(screen.getByText(/Categoria a revisar/)).toBeInTheDocument();expect(screen.getByText(/Sem data válida/)).toBeInTheDocument();expect(screen.queryByText(/R\$/)).not.toBeInTheDocument();expect(screen.queryByRole('img')).not.toBeInTheDocument();});
it('hides stale totals during refresh and does not replace failures by zero',async()=>{const cache=new QueryClient();open(cache);await screen.findByText(/1501 registro\(s\) · 1 cancelado/);let reject!:(e:Error)=>void;read.mockImplementationOnce(()=>new Promise((_,no)=>{reject=no;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-recorded-cost-summary']});});await waitFor(()=>expect(screen.queryByText(/1501 registro\(s\) · 1 cancelado/)).not.toBeInTheDocument());expect(screen.queryByText(/R\$/)).not.toBeInTheDocument();await act(async()=>{reject(new Error('offline'));});expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível consultar os custos');expect(screen.queryByText('R$ 0,00')).not.toBeInTheDocument();});
it('does not treat no covered costs as no company costs',async()=>{read.mockResolvedValue({...result,total_count:0,total_cents:'0',categories:[],cost_centers:[],months:[]});open();expect(await screen.findByText(/não comprova ausência de custos/)).toBeInTheDocument();});
