import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {SettlementPaymentWorkspace} from '@/components/financial/SettlementPaymentWorkspace';
import {SettlementPaymentRejectedError} from '@/lib/financial/settlementPaymentClient';
const mock=vi.hoisted(()=>({read:vi.fn(),record:vi.fn()}));vi.mock('@/lib/financial/settlementPaymentClient',()=>({readSettlementPaymentCandidates:mock.read,recordSettlementPayment:mock.record,settlementPaymentError:(e:Error)=>e.message,SettlementPaymentRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),settlement=crypto.randomUUID(),movement=crypto.randomUUID(),key=`finance-settlement-payment:${tenant}:${actor}:${settlement}`;
const data={version:1,tenant_id:tenant,settlement_id:settlement,amount_cents:10000,balance_cents:20000,page:1,page_size:20,total:1,rows:[{id:movement,description:'PIX motorista',occurred_on:'2026-01-01',amount_cents:50000,remaining_cents:20000,beneficiary_name:'Motorista QA',account_name:'Conta principal'}]};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(data);mock.record.mockResolvedValue({});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(initialAmount=100,allowNew=true,cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><SettlementPaymentWorkspace tenant={tenant} actor={actor} settlement={settlement} initialAmount={initialAmount} allowNew={allowNew} onClose={()=>{}}/></QueryClientProvider>);}
async function review(){fireEvent.click(await screen.findByRole('radio'));fireEvent.change(screen.getByLabelText('Motivo do registro'),{target:{value:'Pagamento já conferido com o motorista'}});fireEvent.click(screen.getByRole('button',{name:'Revisar pagamento'}));await screen.findByRole('button',{name:'Confirmar registro do pagamento'});}
it('reviews an existing movement and recovers the exact original request after response loss',async()=>{
 mock.record.mockRejectedValueOnce(new Error('Resposta perdida'));const view=open();await review();expect(mock.record).not.toHaveBeenCalled();expect(screen.getByText(/Data do pagamento: 2026-01-01/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Confirmar registro do pagamento'}));await screen.findByRole('alert');const original=mock.record.mock.calls[0][0];expect(original).toMatchObject({amount_cents:10000,movement_id:movement,method:'pix'});expect(original).not.toHaveProperty('paid_at');
 view.unmount();mock.read.mockRejectedValue(new Error('Acerto pago'));open(0,false);fireEvent.click(screen.getByRole('button',{name:'Retomar pagamento original'}));await screen.findByRole('status');expect(mock.record.mock.calls[1][0]).toEqual(original);expect(sessionStorage.getItem(key)).toBeNull();
});
it('blocks invalid amounts, corrupted recovery and storage failures before sending',async()=>{
 const view=open(0);expect(mock.read).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Valor pago (R$)'),{target:{value:'1,001'}});expect(mock.read).not.toHaveBeenCalled();view.unmount();sessionStorage.setItem(key,'invalid');open();expect(screen.getByRole('alert')).toHaveTextContent('Não foi possível recuperar');expect(mock.record).not.toHaveBeenCalled();
 cleanup();sessionStorage.clear();open();await review();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('full');});fireEvent.click(screen.getByRole('button',{name:'Confirmar registro do pagamento'}));expect(await screen.findByRole('alert')).toHaveTextContent('Nenhum pagamento foi enviado');expect(mock.record).not.toHaveBeenCalled();
});
it('releases the first confirmed rejection and hides stale capacity after refresh failure',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});mock.record.mockRejectedValueOnce(new SettlementPaymentRejectedError('finance_movement_overallocated'));open(100,true,cache);await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar registro do pagamento'}));expect(await screen.findByRole('alert')).toHaveTextContent('Pagamento recusado');expect(sessionStorage.getItem(key)).toBeNull();await screen.findByRole('radio');mock.read.mockRejectedValue(new Error('Consulta indisponível'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-settlement-payment-candidates']});});await waitFor(()=>expect(screen.queryByRole('radio')).not.toBeInTheDocument());expect(screen.getByRole('button',{name:'Revisar pagamento'})).toBeDisabled();
});
it('blocks a correction arriving while the confirmation is already open',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});const view=open(100,true,cache);await review();view.rerender(<QueryClientProvider client={cache}><SettlementPaymentWorkspace tenant={tenant} actor={actor} settlement={settlement} initialAmount={100} allowNew={false} onClose={()=>{}}/></QueryClientProvider>);expect(screen.getByRole('button',{name:'Confirmar registro do pagamento'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Confirmar registro do pagamento'}));expect(mock.record).not.toHaveBeenCalled();
});
it('preserves an uncertain restored request when a later attempt receives a known rejection',async()=>{
 const original={version:1,tenant_id:tenant,request_id:crypto.randomUUID(),settlement_id:settlement,movement_id:movement,amount_cents:10000,method:'pix',reason:'Pagamento previamente enviado'};
 sessionStorage.setItem(key,JSON.stringify({actor,command:original}));mock.record.mockRejectedValueOnce(new SettlementPaymentRejectedError('finance_access_denied'));open(0,false);fireEvent.click(screen.getByRole('button',{name:'Retomar pagamento original'}));expect(await screen.findByRole('alert')).toHaveTextContent('preservado para retomada');expect(JSON.parse(sessionStorage.getItem(key)!).command).toEqual(original);expect(mock.read).not.toHaveBeenCalled();
});

it('releases first movement concurrency rejection but preserves a retry after uncertainty',async()=>{mock.record.mockRejectedValueOnce(new SettlementPaymentRejectedError('finance_movement_use_busy'));const view=open();await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar registro do pagamento'}));await screen.findByRole('alert');expect(sessionStorage.getItem(key)).toBeNull();view.unmount();mock.record.mockRejectedValueOnce(new Error('timeout')).mockRejectedValueOnce(new SettlementPaymentRejectedError('finance_movement_use_busy'));open();await review();fireEvent.click(screen.getByRole('button',{name:'Confirmar registro do pagamento'}));await screen.findByRole('button',{name:'Retomar pagamento original'});const saved=sessionStorage.getItem(key);fireEvent.click(screen.getByRole('button',{name:'Retomar pagamento original'}));await waitFor(()=>expect(mock.record).toHaveBeenCalledTimes(3));expect(sessionStorage.getItem(key)).toBe(saved);expect(screen.getByRole('button',{name:'Retomar pagamento original'})).toBeInTheDocument();});
