import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {StatementCoverageReview,StatementCoverageWorkspace} from '@/components/financial/StatementCoverageReview';
import {CoverageRejectedError} from '@/lib/financial/statementCoverageClient';
import {tenant,actor,account,context,approval} from './statementCoverageFixture';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));
vi.mock('@/lib/financial/statementCoverageClient',()=>({readStatementCoverage:mock.read,submitStatementCoverage:mock.submit,CoverageRejectedError:class extends Error{}}));
const key=`finance-statement-coverage:${tenant}:${actor}:${account}`;
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(context);mock.submit.mockResolvedValue({});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(from=context.from,cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><StatementCoverageWorkspace tenant={tenant} actor={actor} account={account} from={from} to={context.to}/></QueryClientProvider>);}
async function prepare(){fireEvent.change(await screen.findByLabelText('Motivo da decisão'),{target:{value:'Originais e período conferidos'}});for(const checkbox of screen.queryAllByRole('checkbox'))fireEvent.click(checkbox);fireEvent.click(screen.getByRole('button',{name:'Revisar decisão de cobertura'}));}
it('requires two separate declarations and review, preserving the original approval after a lost reply across periods',async()=>{
 mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();fireEvent.change(await screen.findByLabelText('Motivo da decisão'),{target:{value:'Originais e período conferidos'}});const checks=screen.getAllByRole('checkbox');fireEvent.click(checks[0]);expect(screen.getByRole('button',{name:'Revisar decisão de cobertura'})).toBeDisabled();fireEvent.click(checks[1]);fireEvent.click(screen.getByRole('button',{name:'Revisar decisão de cobertura'}));expect(mock.submit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão de cobertura'}));await screen.findByRole('alert');const original=mock.submit.mock.calls[0][0];expect(original.command).toMatchObject({originals_obtained_from_bank:true,complete_period_confirmed:true,revision:'coverage-1'});view.unmount();open('2026-01-10');fireEvent.click(screen.getByRole('button',{name:'Retomar decisão de cobertura'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);expect(sessionStorage.getItem(key)).toBeNull();
});
it('blocks reviewed decisions after changed evidence and hides stale data after query failure',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(context.from,cache);await prepare();mock.read.mockResolvedValue({...context,revision:'changed'});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-statement-coverage-review']});});await waitFor(()=>expect(screen.getByRole('button',{name:'Confirmar decisão de cobertura'})).toBeDisabled());mock.read.mockRejectedValue(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-statement-coverage-review']});});expect(await screen.findByText(/Não foi possível consultar a cobertura/)).toBeInTheDocument();expect(screen.queryByText('Cobertura ainda não aprovada')).not.toBeInTheDocument();expect(mock.submit).not.toHaveBeenCalled();
});
it('recovers reversal while preserving permanent manual authorship and altered-evidence warning',async()=>{
 mock.read.mockResolvedValue({...context,status:'needs_review',current:false,can_approve:false,approval,history:[{...approval,reversal:null}]});mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();fireEvent.click(await screen.findByRole('button',{name:'Desfazer aprovação ativa'}));expect(screen.getByText(/As evidências mudaram depois/)).toBeInTheDocument();await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão de cobertura'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(1));const original=mock.submit.mock.calls[0][0];view.unmount();mock.read.mockResolvedValue({...context,status:'reversed',history:[{...approval,reversal:{actor_name:'Gestor Paulo',actor_id:actor,reason:'Arquivo incorreto identificado',created_at:'2026-02-02'}}]});open();fireEvent.click(screen.getByRole('button',{name:'Retomar decisão de cobertura'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);expect(await screen.findByText(/Desfeita por Gestor Paulo/)).toBeInTheDocument();expect(screen.getByText(/Aprovação manual · Desfeita/)).toBeInTheDocument();
});
it('blocks corrupted recovery storage and does not send when storage cannot persist',async()=>{
 sessionStorage.setItem(key,'broken');const view=open();await screen.findByLabelText('Motivo da decisão');expect(screen.getByRole('button',{name:'Revisar decisão de cobertura'})).toBeDisabled();view.unmount();sessionStorage.clear();open();await prepare();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('full');});fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão de cobertura'}));expect(await screen.findByRole('alert')).toHaveTextContent('Nenhuma aprovação ou correção foi enviada');expect(mock.submit).not.toHaveBeenCalled();
});
it('releases a known first rejection but preserves an already uncertain request',async()=>{
 mock.submit.mockRejectedValueOnce(new CoverageRejectedError('finance_coverage_evidence_changed'));const view=open();await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão de cobertura'}));await screen.findByText('As evidências mudaram. Atualize e faça uma nova revisão.');expect(sessionStorage.getItem(key)).toBeNull();await screen.findByRole('button',{name:'Revisar decisão de cobertura'});view.unmount();const original=mock.submit.mock.calls[0][0];sessionStorage.setItem(key,JSON.stringify({actor,account,pending:original}));mock.submit.mockRejectedValueOnce(new CoverageRejectedError('finance_coverage_evidence_changed'));open();fireEvent.click(screen.getByRole('button',{name:'Retomar decisão de cobertura'}));expect(await screen.findByRole('alert')).toHaveTextContent('preservado para retomada');expect(JSON.parse(sessionStorage.getItem(key)!).pending).toEqual(original);
});
it('isolates recovery when switching accounts and returns to the original request',async()=>{
 const cache=new QueryClient({defaultOptions:{queries:{retry:false}}}),other=crypto.randomUUID();
 const panel=(id:string)=><QueryClientProvider client={cache}><StatementCoverageReview tenant={tenant} actor={actor} account={id} from={context.from} to={context.to}/></QueryClientProvider>;
 mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=render(panel(account));fireEvent.click(screen.getByRole('button',{name:'Revisar cobertura dos extratos'}));await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar decisão de cobertura'}));await screen.findByRole('alert');const original=mock.submit.mock.calls[0][0];view.rerender(panel(other));await screen.findByLabelText('Motivo da decisão');expect(screen.queryByRole('button',{name:'Retomar decisão de cobertura'})).not.toBeInTheDocument();expect(JSON.parse(sessionStorage.getItem(key)!).pending).toEqual(original);view.rerender(panel(account));fireEvent.click(screen.getByRole('button',{name:'Retomar decisão de cobertura'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);
});
