import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {StockConsumptionWorkspace} from '@/components/financial/StockConsumptionAttribution';
import {StockConsumptionRejectedError} from '@/lib/financial/stockConsumptionClient';
const mock=vi.hoisted(()=>({read:vi.fn(),preview:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/stockConsumptionClient',()=>({readStockConsumptionContext:mock.read,previewStockConsumption:mock.preview,submitStockConsumption:mock.submit,StockConsumptionRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),part=crypto.randomUUID(),movement=crypto.randomUUID(),order=crypto.randomUUID(),first=crypto.randomUUID(),second=crypto.randomUUID(),attribution=crypto.randomUUID(),key=`finance-stock-consumption:${tenant}:${actor}:${part}:${movement}`;
const candidate=(id:string)=>({acquisition_link_id:id,inbound_movement_id:crypto.randomUUID(),cost_id:crypto.randomUUID(),supplier_id:crypto.randomUUID(),supplier_name:'Fornecedor',document_number:'NF123',acquired_on:'2026-01-01',quantity:'3',amount_cents:'1',available_quantity:'3',available_cents:'1',availability_issue:null});
const context={version:1,tenant_id:tenant,part_id:part,movement_id:movement,page:1,page_size:30,search:'',total:31,source:{part_id:part,movement_id:movement,order_id:order,order_number:'OS1',order_status:'completed',stock_item_id:crypto.randomUUID(),item_name:'Filtro',unit:'un',part_quantity:'2',movement_quantity:'2',movement_date:'2026-01-02',declared_part_cents:'5',declared_movement_cents:'5'},active_attribution:null,history:{total:0,rows:[]},candidates:[candidate(first)]};
const preview={version:1,tenant_id:tenant,part_id:part,movement_id:movement,revision:'a'.repeat(32),eligible:true,issue:null,policy:'remaining_balance_floor_v1',quantity:'2',declared_part_cents:'5',declared_movement_cents:'5',attributed_cents:'0',discrepancy:true,lines:[first,second].map(id=>({acquisition_link_id:id,quantity:'1',amount_cents:'0',available_quantity_before:'3',available_cents_before:'1',available_quantity_after:'2',available_cents_after:'1'})),snapshot:{}};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockImplementation(async(_t,_p,_m,page)=>({...context,page,candidates:page===1?context.candidates:[candidate(second)]}));mock.preview.mockResolvedValue(preview);mock.submit.mockResolvedValue({maintenance_part_id:part,consumption_movement_id:movement});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><StockConsumptionWorkspace tenant={tenant} actor={actor} part={part} movement={movement}/></QueryClientProvider>);}
async function select(){fireEvent.click(await screen.findByRole('button',{name:`Selecionar aquisição ${first}`}));fireEvent.change(screen.getByLabelText('Quantidade da aquisição 1'),{target:{value:'1.000000000000000000'}});fireEvent.click(screen.getByRole('button',{name:'Próximas aquisições'}));fireEvent.click(await screen.findByRole('button',{name:`Selecionar aquisição ${second}`}));fireEvent.change(screen.getByLabelText('Quantidade da aquisição 2'),{target:{value:'1'}});fireEvent.click(screen.getByRole('button',{name:'Calcular atribuição no servidor'}));await screen.findByText('Conferência calculada pelo servidor');}
function acknowledge(){fireEvent.click(screen.getByLabelText(/Conferi que estas aquisições/));fireEvent.click(screen.getByLabelText(/Reconheço a diferença/));fireEvent.change(screen.getByLabelText('Motivo da atribuição ou correção'),{target:{value:'Origem e diferença conferidas no fechamento da OS'}});}
it('keeps multiple selected IDs across pages, requires server preview and explicit discrepancy then replays uncertain original',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await select();expect(mock.submit).not.toHaveBeenCalled();expect(screen.getByLabelText('Quantidade da aquisição 1')).toHaveValue('1.000000000000000000');fireEvent.change(screen.getByLabelText('Motivo da atribuição ou correção'),{target:{value:'Origem conferida e validada'}});fireEvent.click(screen.getByLabelText(/Conferi que estas aquisições/));expect(screen.getByRole('button',{name:'Revisar atribuição ou correção'})).toBeDisabled();fireEvent.click(screen.getByLabelText(/Reconheço a diferença/));fireEvent.click(screen.getByRole('button',{name:'Revisar atribuição ou correção'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar atribuição ou correção'}));await screen.findByText(/pedido original foi preservado/);const original=mock.submit.mock.calls[0][0];expect(original.command).toMatchObject({maintenance_part_id:part,consumption_movement_id:movement,discrepancy_confirmed:true,lines:[{acquisition_link_id:first,quantity:'1.000000000000000000'},{acquisition_link_id:second,quantity:'1'}]});view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar atribuição ou correção original'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('blocks corrupted storage and hides obsolete preview after failure',async()=>{sessionStorage.setItem(key,'broken');open();await screen.findByText(/recuperar o pedido/);expect(await screen.findByRole('button',{name:`Selecionar aquisição ${first}`})).toBeDisabled();cleanup();sessionStorage.clear();const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await select();acknowledge();fireEvent.click(screen.getByRole('button',{name:'Revisar atribuição ou correção'}));mock.preview.mockRejectedValue(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-stock-consumption-preview']});});await screen.findByText(/Não foi possível calcular/);expect(screen.queryByText('Conferência calculada pelo servidor')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Confirmar atribuição ou correção'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Voltar à revisão'}));expect(mock.submit).not.toHaveBeenCalled();});
it('releases first known rollback and preserves source change blocking',async()=>{mock.submit.mockRejectedValueOnce(new StockConsumptionRejectedError('finance_stock_consumption_changed'));const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await select();acknowledge();fireEvent.click(screen.getByRole('button',{name:'Revisar atribuição ou correção'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar atribuição ou correção'}));await waitFor(()=>expect(sessionStorage.getItem(key)).toBeNull());expect(await screen.findByRole('button',{name:'Calcular atribuição no servidor'})).not.toBeDisabled();});
it('reverses the full attribution with current revision and preserves authorship',async()=>{const active={id:attribution,policy:'remaining_balance_floor_v1',revision:'b'.repeat(32),quantity:'2',attributed_cents:'0',actor_id:actor,actor_name:'Maria',reason:'Origens conferidas',created_at:'2026-01-01',lines:[]};mock.read.mockResolvedValue({...context,active_attribution:active,history:{total:1,rows:[{...active,reversal:null}]}});open();fireEvent.click(await screen.findByRole('button',{name:'Desfazer atribuição inteira'}));fireEvent.change(screen.getByLabelText('Motivo da atribuição ou correção'),{target:{value:'Correção da origem de material'}});fireEvent.click(screen.getByRole('button',{name:'Revisar atribuição ou correção'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar atribuição ou correção'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(1));expect(mock.submit.mock.calls[0][0]).toMatchObject({kind:'reverse',command:{attribution_id:attribution,revision:'b'.repeat(32)}});expect(screen.getAllByText(/Maria/).length).toBeGreaterThan(0);expect(mock.preview).not.toHaveBeenCalled();});

it('requires another calculation when source context changes after preview',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await select();acknowledge();fireEvent.click(screen.getByRole('button',{name:'Revisar atribuição ou correção'}));mock.read.mockResolvedValue({...context,page:2,source:{...context.source,movement_quantity:'3'},candidates:[candidate(second)]});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-stock-consumption-context']});});await screen.findByText(/O contexto mudou/);expect(screen.getByRole('button',{name:'Confirmar atribuição ou correção'})).toBeDisabled();expect(mock.submit).not.toHaveBeenCalled();});
