import {beforeEach,it,expect,vi} from 'vitest';
import {readStockAcquisitionAssociation,submitStockAcquisitionAssociation,readStockAcquisitionInventory} from '@/lib/financial/stockAcquisitionClient';
import {stockAcquisitionAssociateCommandSchema,stockAcquisitionContextSchema,stockAcquisitionReverseCommandSchema} from '@/lib/financial/stockAcquisitionContract';
const mock=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mock.rpc}}));
const tenant=crypto.randomUUID(),inbound=crypto.randomUUID(),item=crypto.randomUUID(),cost=crypto.randomUUID(),request=crypto.randomUUID(),link=crypto.randomUUID();
const command={version:1 as const,tenant_id:tenant,request_id:request,inbound_movement_id:inbound,cost_id:cost,revision:'a'.repeat(32),reason:'Compra e fornecedor conferidos',quantity:'2.00',document_number:'NF-456',same_purchase_confirmed:true as const};
const result={version:1,tenant_id:tenant,request_id:request,inbound_movement_id:inbound,stock_item_id:item,cost_id:cost,link_id:link,amount_cents:'50000',quantity:'2',confirmed:true,cash_changed:false,obligation_created:false,cost_created:false};
beforeEach(()=>vi.clearAllMocks());
it('requires quantity document and declaration and rejects mismatched source or created money',async()=>{for(const patch of [{quantity:'0'},{quantity:'1e3'},{document_number:''},{same_purchase_confirmed:false}])expect(stockAcquisitionAssociateCommandSchema.safeParse({...command,...patch}).success).toBe(false);mock.rpc.mockResolvedValueOnce({data:result,error:null});await expect(submitStockAcquisitionAssociation({kind:'associate',command})).resolves.toMatchObject(result);expect(mock.rpc).toHaveBeenCalledWith('associate_finance_stock_acquisition',{_payload:command});for(const patch of [{inbound_movement_id:crypto.randomUUID()},{cash_changed:true},{cost_created:true}]){mock.rpc.mockResolvedValueOnce({data:{...result,...patch},error:null});await expect(submitStockAcquisitionAssociation({kind:'associate',command})).rejects.toThrow();}});
it('checks origin identity and search scope without limiting inventory totals',async()=>{const context={version:1,tenant_id:tenant,inbound_movement_id:inbound,page:2,page_size:30,search:'NF%',total:1001,source:{id:inbound,stock_item_id:item,item_name:null,movement_type:'inbound',reason:'purchase',movement_date:null,quantity:null,unit_cost_cents:null,unit_cost_decimal:null,unit_price_policy:"rounded_extended_total_cents_v1",total_cost_cents:null},active_link:null,history:{total:0,rows:[]},candidates:[]};mock.rpc.mockResolvedValueOnce({data:context,error:null});expect((await readStockAcquisitionAssociation(tenant,inbound,2,'NF%')).total).toBe(1001);expect(stockAcquisitionContextSchema.safeParse({...context,source:{...context.source,id:cost}}).success).toBe(false);mock.rpc.mockResolvedValueOnce({data:{...context,search:'different'},error:null});await expect(readStockAcquisitionAssociation(tenant,inbound,2,'NF%')).rejects.toThrow();mock.rpc.mockResolvedValueOnce({data:{version:1,tenant_id:tenant,page:1,page_size:30,search:'',total:1005,associated_count:5,unassociated_count:1000,rows:[]},error:null});expect((await readStockAcquisitionInventory(tenant)).total).toBe(1005);});
it('requires current revision for reversal and preserves money and obligation',async()=>{const reverse={version:1 as const,tenant_id:tenant,request_id:request,link_id:link,revision:'b'.repeat(32),reason:command.reason};expect(stockAcquisitionReverseCommandSchema.safeParse({...reverse,revision:undefined}).success).toBe(false);mock.rpc.mockResolvedValueOnce({data:{...result,reversal_id:crypto.randomUUID()},error:null});await expect(submitStockAcquisitionAssociation({kind:'reverse',command:reverse})).resolves.toMatchObject({cash_changed:false,obligation_created:false,cost_created:false});expect(mock.rpc.mock.calls[0][0]).toBe('reverse_finance_stock_acquisition_association');});

it('preserves decimal text with additional scale without Number rounding',async()=>{const precise={...command,quantity:'2.000000000000000000000'};expect(stockAcquisitionAssociateCommandSchema.parse(precise).quantity).toBe(precise.quantity);mock.rpc.mockResolvedValueOnce({data:result,error:null});await submitStockAcquisitionAssociation({kind:'associate',command:precise});expect(mock.rpc.mock.calls[0][1]._payload.quantity).toBe(precise.quantity);});
