import {beforeEach,it,expect,vi} from 'vitest';
import {previewStockConsumption,submitStockConsumption,readStockConsumptionContext} from '@/lib/financial/stockConsumptionClient';
const mock=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mock.rpc}}));
const tenant=crypto.randomUUID(),part=crypto.randomUUID(),movement=crypto.randomUUID(),acquisition=crypto.randomUUID(),request=crypto.randomUUID(),attribution=crypto.randomUUID(),order=crypto.randomUUID();
const preview={version:1,tenant_id:tenant,part_id:part,movement_id:movement,revision:'a'.repeat(32),eligible:true,issue:null,policy:'remaining_balance_floor_v1',quantity:'1',declared_part_cents:'1',declared_movement_cents:'1',attributed_cents:'0',discrepancy:true,lines:[{acquisition_link_id:acquisition,quantity:'1',amount_cents:'0',available_quantity_before:'3',available_cents_before:'1',available_quantity_after:'2',available_cents_after:'1'}],snapshot:{}};
beforeEach(()=>vi.clearAllMocks());
it('validates preview identity and quantity echo without numeric rounding and preserves domain diagnostics',async()=>{const lines=[{acquisition_link_id:acquisition,quantity:'1.00000000000000000'}];mock.rpc.mockResolvedValueOnce({data:preview,error:null});expect((await previewStockConsumption(tenant,part,movement,lines)).attributed_cents).toBe('0');expect(mock.rpc.mock.calls[0][1]._lines).toEqual(lines);mock.rpc.mockResolvedValueOnce({data:{...preview,lines:[{...preview.lines[0],quantity:'2'}]},error:null});await expect(previewStockConsumption(tenant,part,movement,lines)).rejects.toThrow();mock.rpc.mockResolvedValueOnce({data:{...preview,eligible:false,issue:'finance_stock_consumption_source_not_found',attributed_cents:null,lines:[{...preview.lines[0],amount_cents:null}]},error:null});expect((await previewStockConsumption(tenant,part,movement,lines)).issue).toBe('finance_stock_consumption_source_not_found');});
it('sends attributed command with explicit discrepancy and rejects confirmation for another movement',async()=>{const command={version:1 as const,tenant_id:tenant,request_id:request,maintenance_part_id:part,consumption_movement_id:movement,revision:preview.revision,reason:'Quantidades e divergência conferidas',lines:[{acquisition_link_id:acquisition,quantity:'1'}],same_stock_origin_confirmed:true as const,discrepancy_confirmed:true},result={version:1,tenant_id:tenant,request_id:request,attribution_id:attribution,maintenance_part_id:part,consumption_movement_id:movement,order_id:order,quantity:'1',attributed_cents:'0',policy:'remaining_balance_floor_v1',cash_changed:false,cost_created:false,obligation_created:false,confirmed:true};mock.rpc.mockResolvedValueOnce({data:result,error:null});await submitStockConsumption({kind:'attribute',command});expect(mock.rpc).toHaveBeenCalledWith('attribute_finance_stock_consumption',{_payload:command});mock.rpc.mockResolvedValueOnce({data:{...result,consumption_movement_id:crypto.randomUUID()},error:null});await expect(submitStockConsumption({kind:'attribute',command})).rejects.toThrow();mock.rpc.mockResolvedValueOnce({data:{...result,reversal_id:crypto.randomUUID()},error:null});await submitStockConsumption({kind:'reverse',command:{version:1,tenant_id:tenant,request_id:request,attribution_id:attribution,revision:preview.revision,reason:command.reason}});expect(mock.rpc.mock.calls[2][0]).toBe('reverse_finance_stock_consumption_attribution');});
it('rejects context from another requested page before displaying stale acquisition data',async()=>{mock.rpc.mockResolvedValueOnce({data:{},error:null});await expect(readStockConsumptionContext(tenant,part,movement,2,'NF%')).rejects.toThrow();expect(mock.rpc).toHaveBeenCalledWith('get_finance_stock_consumption_context',{_tenant_id:tenant,_part_id:part,_movement_id:movement,_page:2,_search:'NF%'});});
