// @vitest-environment node
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createStockConsumptionDatabase} from './helpers/stockConsumptionDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
import {stockConsumptionContextSchema,stockConsumptionPreviewSchema} from '@/lib/financial/stockConsumptionContract';
let db:Awaited<ReturnType<typeof createStockConsumptionDatabase>>;const item=randomUUID(),part=randomUUID(),movement=randomUUID(),order=randomUUID(),supplier=randomUUID();
beforeAll(async()=>{db=await createStockConsumptionDatabase();await db.exec('create table finance_statement_imports(id uuid,tenant_id uuid,file_name text);create table finance_statement_rows(id uuid,tenant_id uuid,source_row integer)');for(const file of ['20260909233625_finance_audit_queries.sql','20260910160441_finance_maintenance_cost_context.sql','20260910170539_finance_stock_acquisition_readers.sql','20260910171734_finance_stock_consumption_readers.sql'])await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("insert into stock_items(id,tenant_id,name,category,unit) values($1,$2,'Filtro','filter','un')",[item,i.tenant]);await db.query("insert into clients(id,tenant_id,company_name) values($1,$2,'Fornecedor de filtros')",[supplier,i.tenant]);await db.query("insert into maintenance_orders(id,tenant_id,order_number,status) values($1,$2,'OS QA consumo','completed')",[order,i.tenant]);await db.query("insert into stock_movements(id,tenant_id,stock_item_id,maintenance_order_id,movement_type,quantity,unit_cost,total_cost,reason,moved_at) values($1,$2,$3,$4,'consumption',2,5,10,'maintenance','2026-01-20T14:00:00Z')",[movement,i.tenant,item,order]);await db.query("insert into maintenance_parts(id,tenant_id,maintenance_order_id,stock_item_id,stock_movement_id,item_description,quantity,unit_cost,total_cost) values($1,$2,$3,$4,$5,'Filtro consumido',2,5,10)",[part,i.tenant,order,item,movement]);});
afterEach(async()=>{await db.exec('rollback');});afterAll(async()=>{await db?.close();});
async function acquisitions(count=1){const ids:string[]=[];for(let n=0;n<count;n++){const inbound=randomUUID(),cost=randomUUID();await db.query("insert into stock_movements(id,tenant_id,stock_item_id,movement_type,quantity,unit_cost,total_cost,reason,moved_at) values($1,$2,$3,'inbound',10,5,50,'purchase','2026-01-01T14:00:00Z')",[inbound,i.tenant,item]);await financeAs(db,i.operator,'select record_finance_expense_batch($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),context:'maintenance',description:'Aquisição filtros',reason:'Aquisição conferida para o estoque',items:[{id:cost,category:'maintenance',description:'Filtros',amount_cents:5000,occurred_on:'2026-01-01',supplier_id:supplier,supplier_name:'Fornecedor',document_number:`NF-${n}`,payee_type:'supplier',no_receipt_reason:'Documento solicitado ao fornecedor',allocations:[]}]}]);const revision=(await db.query<{v:string}>('select finance_private.stock_acquisition_revision($1,$2,$3) v',[i.tenant,inbound,cost])).rows[0].v;const result=(await financeAs<{v:{link_id:string}}>(db,i.operator,'select associate_finance_stock_acquisition($1) v',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),inbound_movement_id:inbound,cost_id:cost,revision,quantity:'10',document_number:`NF-${n}`,same_purchase_confirmed:true,reason:'Compra conferida e identificada'}])).rows[0].v;ids.push(result.link_id);}return ids;}
async function context(page=1,search=''){return stockConsumptionContextSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select get_finance_stock_consumption_context($1,$2,$3,$4,$5) v',[i.tenant,part,movement,page,search])).rows[0].v);}
async function preview(lines:Array<{acquisition_link_id:string;quantity:string}>){return stockConsumptionPreviewSchema.parse((await financeAs<{v:unknown}>(db,i.operator,'select preview_finance_stock_consumption($1,$2,$3,$4) v',[i.tenant,part,movement,lines])).rows[0].v);}
it('paginates all acquisition candidates and previews explicitly selected IDs across pages',async()=>{await acquisitions(31);const first=await context(),second=await context(2);expect(first.total).toBe(31);expect(first.candidates).toHaveLength(30);expect(second.candidates).toHaveLength(1);const lines=[first.candidates[0],second.candidates[0]].map(row=>({acquisition_link_id:row.acquisition_link_id,quantity:'1'}));const p=await preview(lines);expect(p).toMatchObject({eligible:true,attributed_cents:'1000',discrepancy:false});expect(p.lines).toHaveLength(2);expect((await context(1,'%')).total).toBe(0);},30000);
it('preserves attribution and reversal history independently of candidate search',async()=>{const [link]=await acquisitions();const lines=[{acquisition_link_id:link,quantity:'2'}],p=await preview(lines);await financeAs(db,i.operator,'select attribute_finance_stock_consumption($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),maintenance_part_id:part,consumption_movement_id:movement,lines,revision:p.revision,reason:'Origem física do material conferida',same_stock_origin_confirmed:true,discrepancy_confirmed:false}]);const active=await context(2,'inexistente');expect(active.active_attribution).toMatchObject({quantity:'2',attributed_cents:'1000'});expect(active.history.total).toBe(1);expect((await context()).candidates[0]).toMatchObject({available_quantity:'8',available_cents:'4000'});await financeAs(db,i.operator,'select reverse_finance_stock_consumption_attribution($1)',[{version:1,tenant_id:i.tenant,request_id:randomUUID(),attribution_id:active.active_attribution!.id,revision:active.active_attribution!.revision,reason:'Revisão da origem sem alterar consumo físico'}]);const after=await context();expect(after.active_attribution).toBeNull();expect(after.history.rows[0].reversal?.actor_id).toBe(i.operator);expect(after.candidates[0]).toMatchObject({available_quantity:'10',available_cents:'5000'});expect((await db.query('select count(*)::int n from finance_expense_items')).rows[0]).toEqual({n:1});});
it('shows source disagreement without changing operational amounts',async()=>{const [link]=await acquisitions();await db.query('update maintenance_parts set total_cost=12 where id=$1',[part]);const data=await context(),p=await preview([{acquisition_link_id:link,quantity:'2'}]);expect(data.source.declared_part_cents).toBe('1200');expect(p).toMatchObject({eligible:true,discrepancy:true,attributed_cents:'1000'});expect((await context()).source.declared_part_cents).toBe('1200');});
it('rejects invalid scope and driver reads at the server',async()=>{await expect(context(0)).rejects.toThrow('finance_invalid_filters');await expect(financeAs(db,i.driverUser,'select get_finance_stock_consumption_context($1,$2,$3)',[i.tenant,part,movement])).rejects.toThrow('finance_access_denied');await expect(financeAs(db,i.operator,'select preview_finance_stock_consumption($1,$2,$3,$4)',[i.otherTenant,part,movement,[]])).rejects.toThrow('finance_access_denied');});
