import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {StockAcquisitionAssociationWorkspace} from '@/components/financial/StockAcquisitionAssociation';
import {StockAcquisitionRejectedError} from '@/lib/financial/stockAcquisitionClient';
const mock=vi.hoisted(()=>({read:vi.fn(),submit:vi.fn()}));vi.mock('@/lib/financial/stockAcquisitionClient',()=>({readStockAcquisitionAssociation:mock.read,submitStockAcquisitionAssociation:mock.submit,StockAcquisitionRejectedError:class extends Error{}}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),inbound=crypto.randomUUID(),cost=crypto.randomUUID(),supplier=crypto.randomUUID(),link=crypto.randomUUID(),key=`finance-stock-acquisition-association:${tenant}:${actor}:${inbound}`;
const row={cost_id:cost,batch_id:crypto.randomUUID(),description:'Compra de peça',category:'maintenance',amount_cents:'50000',occurred_on:'2026-01-10',supplier_id:supplier,supplier_name:'Peças Cadastradas',document_number:'NF-456',issue:null,revision:'a'.repeat(32)};
const context={version:1,tenant_id:tenant,inbound_movement_id:inbound,page:1,page_size:30,search:'',total:1,source:{id:inbound,quantity:'2.00',unit_cost_cents:'25000',unit_cost_decimal:'250',unit_price_policy:'rounded_extended_total_cents_v1',total_cost_cents:'50000',stock_item_id:crypto.randomUUID(),movement_type:'inbound',reason:'purchase',movement_date:'2026-01-10',item_name:'Filtro'},active_link:null,history:{total:0,rows:[]},candidates:[row]};
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mock.read.mockResolvedValue(context);mock.submit.mockResolvedValue({inbound_movement_id:inbound,});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
function open(cache=new QueryClient({defaultOptions:{queries:{retry:false}}})){return render(<QueryClientProvider client={cache}><StockAcquisitionAssociationWorkspace tenant={tenant} actor={actor} inbound={inbound}/></QueryClientProvider>);}
async function choose(){fireEvent.click(await screen.findByRole('radio'));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de aquisição de estoque'),{target:{value:'Aquisição de estoque e documento conferidos'}});}
function fields(quantity='2',document='NF-456'){fireEvent.change(screen.getByLabelText('Quantidade da aquisição de estoque'),{target:{value:quantity}});fireEvent.change(screen.getByLabelText('Documento da aquisição de estoque'),{target:{value:document}});}
async function prepare(){await choose();fields();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de aquisição de estoque'}));}
it('requires quantity document and purchase declaration and recovers original after uncertain reply',async()=>{mock.submit.mockRejectedValueOnce(new Error('timeout'));const view=open();await choose();fields('3','wrong');fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'Revisar associação ou correção de aquisição de estoque'})).toBeDisabled();fields();fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de aquisição de estoque'}));expect(mock.submit).not.toHaveBeenCalled();expect(screen.getByText(/quantidade 2, documento NF-456/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de aquisição de estoque'}));await screen.findByText(/pedido original foi preservado/);const original=mock.submit.mock.calls[0][0];expect(original.command).toMatchObject({inbound_movement_id:inbound,cost_id:cost,quantity:'2',document_number:'NF-456',same_purchase_confirmed:true});view.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retomar associação ou correção de aquisição de estoque'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toEqual(original);});
it('blocks storage corruption and stock consumption',async()=>{sessionStorage.setItem(key,'broken');open();await screen.findByText(/recuperar o pedido/);expect(await screen.findByRole('radio')).toBeDisabled();cleanup();sessionStorage.clear();mock.read.mockResolvedValue({...context,source:{...context.source,movement_type:'outbound'}});open();await screen.findByText(/não é uma entrada explicitamente/);expect(await screen.findByRole('radio')).toBeDisabled();});
it('rejects changed document/supplier preview and hides stale options on failure',async()=>{const cache=new QueryClient({defaultOptions:{queries:{retry:false}}});open(cache);await prepare();mock.read.mockResolvedValue({...context,candidates:[{...row,document_number:'NEW',supplier_id:crypto.randomUUID(),revision:'b'.repeat(32)}]});await act(async()=>{await cache.invalidateQueries({queryKey:['finance-stock-acquisition-context']});});await screen.findByText(/contexto mudou/);expect(screen.getByRole('button',{name:'Confirmar associação ou correção de aquisição de estoque'})).toBeDisabled();mock.read.mockRejectedValueOnce(new Error('offline'));await act(async()=>{await cache.invalidateQueries({queryKey:['finance-stock-acquisition-context']});});await screen.findByRole('alert');expect(screen.queryByRole('radio')).not.toBeInTheDocument();});
it('releases editing after first known rollback and preserves reversal authorship',async()=>{mock.submit.mockRejectedValueOnce(new StockAcquisitionRejectedError('finance_stock_acquisition_changed'));open();await prepare();fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de aquisição de estoque'}));await screen.findByText(/A entrada, o custo ou seus vínculos mudaram/);await waitFor(()=>expect(sessionStorage.getItem(key)).toBeNull());expect(await screen.findByRole('radio')).not.toBeDisabled();cleanup();const active={id:link,cost_id:cost,supplier_id:supplier,amount_cents:'50000',actor_id:actor,actor_name:'Maria',reason:'Aquisição de estoque conferida',created_at:'2026-01-10',quantity:'2',revision:'b'.repeat(32),dependencies:{ready:true,blocking_count:0,rows:[]}};mock.read.mockResolvedValue({...context,active_link:active,history:{total:1,rows:[{...active,reversal:null}]}});open();fireEvent.click(await screen.findByRole('button',{name:'Desfazer associação ativa'}));fireEvent.change(screen.getByLabelText('Motivo da associação ou correção de aquisição de estoque'),{target:{value:'Correção do vínculo da aquisição de estoque'}});fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de aquisição de estoque'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de aquisição de estoque'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(2));expect(mock.submit.mock.calls[1][0]).toMatchObject({kind:'reverse',command:{link_id:link,revision:'b'.repeat(32)}});expect(screen.getAllByText(/Maria/).length).toBeGreaterThan(0);});

it('blocks reversal until dependencies are ready and empty',async()=>{const active={id:link,cost_id:cost,supplier_id:supplier,quantity:'2',amount_cents:'50000',actor_id:actor,actor_name:'Maria',reason:'Compra conferida',created_at:'2026-01-10',revision:'a'.repeat(32),dependencies:{ready:true,blocking_count:1,rows:[{id:crypto.randomUUID()}]}};mock.read.mockResolvedValue({...context,active_link:active});open();expect(await screen.findByRole('button',{name:'Desfazer associação ativa'})).toBeDisabled();expect(screen.getByText(/Pendências: 1/)).toBeInTheDocument();expect(mock.submit).not.toHaveBeenCalled();});

it('accepts equivalent quantity text with extra scale for explicit review',async()=>{open();await choose();fields('2.000000000000000000');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Revisar associação ou correção de aquisição de estoque'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar associação ou correção de aquisição de estoque'}));await waitFor(()=>expect(mock.submit).toHaveBeenCalledTimes(1));expect(mock.submit.mock.calls[0][0].command.quantity).toBe('2.000000000000000000');});

it('shows the exact declared fractional unit price without calling it unknown',async()=>{mock.read.mockResolvedValue({...context,source:{...context.source,unit_cost_cents:null,unit_cost_decimal:'0.333333333333'}});open();expect(await screen.findByText(/unitário: R\$ 0,333333333333/)).toBeInTheDocument();});
