import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {TripMaterializedCorrectionWorkspace} from '@/components/control-tower/TripMaterializedCorrectionDialog';
const m=vi.hoisted(()=>({preview:vi.fn(),correct:vi.fn()}));vi.mock('@/lib/controlTower/tripMaterializedCorrection',async original=>({...await original<object>(),previewTripMaterializedCorrection:m.preview,correctMaterializedTrip:m.correct}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),trip=crypto.randomUUID(),key=`trip-materialized-correction:${tenant}:${actor}:${trip}`;
const preview={version:1,tenant_id:tenant,actor_id:actor,trip_id:trip,status:'in_transit',mode:'materialized_correction',revision:'a'.repeat(32),can_execute:true,clean_planned_trip:false,completed_correction:false,result:null,load_ids:[crypto.randomUUID()],stop_ids:[crypto.randomUUID()],dependency_counts:[{code:'payables',count:1},{code:'fiscal_review_required',count:1}],pending_stop_count:1};
function mount(done=vi.fn()){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><TripMaterializedCorrectionWorkspace tenant={tenant} actor={actor} trip={trip} onClose={vi.fn()} onCorrected={done}/></QueryClientProvider>);}
beforeEach(()=>{sessionStorage.clear();vi.clearAllMocks();m.preview.mockResolvedValue(preview);m.correct.mockResolvedValue({confirmed:true});});afterEach(cleanup);
async function confirm(){await screen.findByLabelText('Motivo da correção');fireEvent.change(screen.getByLabelText('Motivo da correção'),{target:{value:'Viagem iniciada a partir do planejamento incorreto'}});const checks=screen.getAllByRole('checkbox');fireEvent.click(checks[0]);fireEvent.click(checks[1]);await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Encerrar viagem com correção auditada'}));});}
it('requires reason and both preservation confirmations and shows dependencies as historical',async()=>{const done=vi.fn();mount(done);expect(await screen.findByText(/Há conta a pagar/)).toBeInTheDocument();expect(screen.getByText(/vínculo fiscal/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Encerrar viagem com correção auditada'})).toBeDisabled();await confirm();await waitFor(()=>expect(done).toHaveBeenCalledOnce());expect(m.correct).toHaveBeenCalledWith(expect.objectContaining({tenant_id:tenant,trip_id:trip,expected_revision:preview.revision,preserve_history_confirmed:true,fiscal_financial_unchanged_confirmed:true}),actor);expect(sessionStorage.getItem(key)).toBeNull();});
it('routes a clean planned trip back to the ordinary cancellation flow',async()=>{m.preview.mockResolvedValue({...preview,status:'planned',can_execute:false,clean_planned_trip:true,dependency_counts:[]});mount();expect(await screen.findByRole('alert')).toHaveTextContent('Cancelar viagem incorreta');expect(screen.queryByLabelText('Motivo da correção')).not.toBeInTheDocument();});
it('replays the same preserved request after an uncertain response',async()=>{m.correct.mockRejectedValueOnce(Error('Resposta sem confirmação'));const view=mount();await confirm();await screen.findByText('Resposta sem confirmação');const frozen=JSON.parse(sessionStorage.getItem(key)!);view.unmount();mount();await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Retomar correção da viagem'}));});await waitFor(()=>expect(m.correct).toHaveBeenCalledTimes(2));expect(m.correct.mock.calls[1]).toEqual([frozen,actor]);});
it('does not execute when a stored request is corrupt',async()=>{sessionStorage.setItem(key,'broken');mount();expect(await screen.findByRole('alert')).toHaveTextContent('não pôde ser lido');await confirm();expect(m.correct).not.toHaveBeenCalled();});
