import {act,fireEvent,render,screen,waitFor,cleanup} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {beforeEach,afterEach,expect,it,vi} from 'vitest';
import {TripCancellationWorkspace} from '@/components/control-tower/TripCancellationDialog';
const m=vi.hoisted(()=>({preview:vi.fn(),cancel:vi.fn()}));
vi.mock('@/lib/controlTower/tripCancellation',async original=>({...await original<object>(),previewTripCancellation:m.preview,cancelTrip:m.cancel}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),trip=crypto.randomUUID(),key=`trip-cancellation:${tenant}:${actor}:${trip}`;
const preview={version:1,tenant_id:tenant,actor_id:actor,trip_id:trip,status:'planned',revision:'a'.repeat(32),can_execute:true,blockers:[],load_ids:[crypto.randomUUID()],stop_ids:[crypto.randomUUID()]};
function mount(done=vi.fn()){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><TripCancellationWorkspace tenant={tenant} actor={actor} trip={trip} onClose={vi.fn()} onCancelled={done}/></QueryClientProvider>);}
beforeEach(()=>{sessionStorage.clear();vi.clearAllMocks();m.preview.mockResolvedValue(preview);m.cancel.mockResolvedValue({confirmed:true});});afterEach(cleanup);
async function confirm(){await screen.findByLabelText('Motivo do cancelamento');fireEvent.change(screen.getByLabelText('Motivo do cancelamento'),{target:{value:'Viagem cadastrada por engano'}});fireEvent.click(screen.getByRole('checkbox'));await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Confirmar cancelamento da viagem'}));});}
it('requires current preview, reason and explicit confirmation before recording a cancellation',async()=>{const done=vi.fn();mount(done);await screen.findByLabelText('Motivo do cancelamento');expect(screen.getByRole('button',{name:'Confirmar cancelamento da viagem'})).toBeDisabled();expect(m.cancel).not.toHaveBeenCalled();await confirm();await waitFor(()=>expect(done).toHaveBeenCalledOnce());expect(m.cancel).toHaveBeenCalledWith(expect.objectContaining({tenant_id:tenant,trip_id:trip,expected_revision:preview.revision,reason:'Viagem cadastrada por engano'}),actor);expect(sessionStorage.getItem(key)).toBeNull();});
it('shows financial blockers and offers no cancellation button',async()=>{m.preview.mockResolvedValue({...preview,can_execute:false,blockers:[{code:'payables',count:1}]});mount();await screen.findByText(/Há conta a pagar/);expect(screen.queryByRole('button',{name:'Confirmar cancelamento da viagem'})).not.toBeInTheDocument();expect(m.cancel).not.toHaveBeenCalled();});
it('recovers the same request after an uncertain response and reload',async()=>{m.cancel.mockRejectedValueOnce(Error('Resposta sem confirmação'));const view=mount();await confirm();await screen.findByText('Resposta sem confirmação');const frozen=JSON.parse(sessionStorage.getItem(key)!);view.unmount();mount();await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Retomar cancelamento'}));});await waitFor(()=>expect(m.cancel).toHaveBeenCalledTimes(2));expect(m.cancel.mock.calls[1]).toEqual([frozen,actor]);});
it('blocks new cancellation if the preserved request is unreadable',async()=>{sessionStorage.setItem(key,'broken');mount();await screen.findByText(/pedido preservado não pôde ser lido/);await screen.findByLabelText('Motivo do cancelamento');await confirm();expect(m.cancel).not.toHaveBeenCalled();expect(sessionStorage.getItem(key)).toBe('broken');});
