import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {UnbilledFreightPanel} from '@/components/financial/UnbilledFreightPanel';
const mock=vi.hoisted(()=>({summary:vi.fn(),origins:vi.fn()}));vi.mock('@/lib/financial/unbilledFreightClient',()=>({readUnbilledFreightSummary:mock.summary,readUnbilledFreightOrigins:mock.origins}));
const summary={total_origins:2,review_count:1,undated_count:0,totals_valid:false,forecast_cents:null,groups:[{state:'available',origin_count:1,forecast_cents:null},{state:'review',origin_count:1,forecast_cents:null}],months:[{month:'2026-09',origin_count:2,forecast_cents:null}],diagnostics:{unpriced_redelivery:1}};
const row={document_id:'nf',attempt_id:'attempt',client_id:null,origin_date:'2026-09-10',date_basis:'attempt_recorded_date',state:'review',freight_cents:null,issues:['unpriced_redelivery']};
beforeEach(()=>{vi.clearAllMocks();mock.summary.mockResolvedValue(summary);mock.origins.mockResolvedValue({total:31,rows:[row]});});afterEach(cleanup);
function open(cache=new QueryClient()){return render(<QueryClientProvider client={cache}><UnbilledFreightPanel tenant="tenant" actor="actor" clients={[{id:'client',label:'Cliente QA'}]}/></QueryClientProvider>);}
it('keeps unknown redelivery forecast indeterminate and shows exact NF/attempt provenance without merchandise values',async()=>{open();expect(await screen.findByText(/Previsão da parcela disponível: Indeterminada/)).toBeInTheDocument();expect(screen.getByText('NF: nf')).toBeInTheDocument();expect(screen.getByText('Tentativa: attempt')).toBeInTheDocument();expect(screen.getByText(/Registro da tentativa: 2026-09-10/)).toBeInTheDocument();expect(screen.queryByText(/R\$/)).not.toBeInTheDocument();expect(screen.getByText(/Não usa valor da mercadoria/)).toBeInTheDocument();expect(mock.origins).toHaveBeenCalledWith('tenant',{from:null,to:null,client:null},'review',1);});
it('applies its own dates and client, paginates list without changing summary and resets page for another state',async()=>{open();await screen.findByText('NF: nf');fireEvent.click(screen.getByRole('button',{name:'Próximas origens'}));await waitFor(()=>expect(mock.origins).toHaveBeenLastCalledWith('tenant',{from:null,to:null,client:null},'review',2));expect(mock.summary).toHaveBeenCalledTimes(1);fireEvent.change(screen.getByLabelText('Origem do frete — início'),{target:{value:'2026-01-01'}});fireEvent.change(screen.getByLabelText('Origem do frete — fim'),{target:{value:'2026-01-31'}});fireEvent.change(screen.getByLabelText('Cliente da previsão'),{target:{value:'client'}});expect(mock.summary).toHaveBeenCalledTimes(1);await waitFor(()=>expect(screen.getByRole('button',{name:'Consultar previsão de frete'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Consultar previsão de frete'}));await waitFor(()=>expect(mock.summary).toHaveBeenLastCalledWith('tenant',{from:'2026-01-01',to:'2026-01-31',client:'client'}));fireEvent.change(screen.getByLabelText('Estado das origens'),{target:{value:'uncertain'}});await waitFor(()=>expect(mock.origins).toHaveBeenLastCalledWith('tenant',{from:'2026-01-01',to:'2026-01-31',client:'client'},'uncertain',1));});
it('does not present reserved or authorized forecast exclusion as a zero freight price',async()=>{mock.summary.mockResolvedValue({...summary,review_count:0,totals_valid:true,forecast_cents:'50000',groups:[{state:'available',origin_count:1,forecast_cents:'50000'},{state:'authorized',origin_count:1,forecast_cents:'0'}]});open();expect(await screen.findByText('Previsão da parcela disponível: R$ 500,00')).toBeInTheDocument();expect(screen.getByText('Já autorizado',{selector:'p'})).toBeInTheDocument();expect(screen.getByText('Fora da parcela disponível prevista')).toBeInTheDocument();expect(screen.getByText(/não significam frete de valor zero/)).toBeInTheDocument();});
it('hides stale summary and list after failed refreshes without suggesting no pending origins',async()=>{const cache=new QueryClient();open(cache);await screen.findByText('NF: nf');mock.summary.mockRejectedValue(new Error('offline'));mock.origins.mockRejectedValue(new Error('offline'));await act(async()=>{await Promise.all([cache.invalidateQueries({queryKey:['finance-unbilled-freight-summary']}),cache.invalidateQueries({queryKey:['finance-unbilled-freight-origins']})]);});await screen.findByText(/Não foi possível consultar a previsão/);expect(screen.queryByText('NF: nf')).not.toBeInTheDocument();expect(screen.queryByText(/Previsão da parcela disponível:/)).not.toBeInTheDocument();expect(screen.queryByText(/Nenhuma origem nesta página/)).not.toBeInTheDocument();});
