import {afterEach,expect,it,vi} from 'vitest';
import {createUnloadingCostCorrectionOutbox,pendingUnloadingCostCorrection,unloadingCostCorrectionKey} from '@/lib/financial/unloadingCostCorrectionOutbox';
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),charge=crypto.randomUUID(),expense=crypto.randomUUID(),payable=crypto.randomUUID();
const expected={cost_before_cents:'15000',cost_after_cents:'12000',obligation_before_cents:'15000',obligation_after_cents:'12000',approval_reset:true,payable_status:'pending' as const};
const input={chargeId:charge,expenseId:expense,payableId:payable,amountCents:'12000',expected,revision:'a'.repeat(32),reason:'  Restaurar título pela origem  '};
const key=unloadingCostCorrectionKey(tenant,actor);
function fixture(){const send=vi.fn(),changed=vi.fn(),assertContext=vi.fn(),lock=vi.fn();const withLock=async<T>(lockKey:string,work:()=>Promise<T>):Promise<T>=>{lock(lockKey,work);return work();};const box=createUnloadingCostCorrectionOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),assertContext,changed,lock:withLock,send});return {box,send,changed,assertContext,lock};}
function result(command:{request_id:string}){return {version:1,tenant_id:tenant,actor_id:actor,request_id:command.request_id,charge_id:charge,expense_id:expense,payable_id:payable,amendment_id:crypto.randomUUID(),...expected,confirmed:true,cash_changed:false,collection_changed:false};}
afterEach(()=>{localStorage.clear();vi.restoreAllMocks();});
it('persists before transport and retains exact body, including whitespace, on lost response and replay',async()=>{const {box,send}=fixture();send.mockImplementationOnce(async command=>{expect(JSON.parse(localStorage.getItem(key)!).payload).toEqual(command);return {data:null,error:{message:'lost'}};}).mockImplementationOnce(async command=>({data:result(command),error:null}));await expect(box.submit(tenant,actor,input)).rejects.toMatchObject({message:'lost'});const raw=localStorage.getItem(key);expect(pendingUnloadingCostCorrection(localStorage,tenant,actor)?.payload.reason).toBe(input.reason);await expect(box.recover(tenant,actor)).resolves.toMatchObject({confirmed:true});expect(send.mock.calls[1][0]).toEqual(JSON.parse(raw!).payload);expect(localStorage.getItem(key)).toBeNull();});
it('clears only a first definitive rejection, retaining previously uncertain requests',async()=>{const {box,send}=fixture();send.mockResolvedValue({data:null,error:{code:'23514',message:'blocked'}});await expect(box.submit(tenant,actor,input)).rejects.toMatchObject({code:'23514'});expect(localStorage.getItem(key)).toBeNull();send.mockResolvedValueOnce({data:null,error:{message:'lost'}});await expect(box.submit(tenant,actor,input)).rejects.toBeTruthy();const raw=localStorage.getItem(key);await expect(box.recover(tenant,actor)).rejects.toMatchObject({code:'23514'});expect(localStorage.getItem(key)).toBe(raw);});
it.each(['tenant_id','actor_id','request_id','charge_id','expense_id','payable_id'])('preserves request when response %s mismatches',async field=>{const {box,send}=fixture();send.mockImplementation(async command=>({data:{...result(command),[field]:crypto.randomUUID()},error:null}));await expect(box.submit(tenant,actor,input)).rejects.toThrow();expect(localStorage.getItem(key)).not.toBeNull();});
it('coalesces identical in-flight input and rejects another scope or body',async()=>{const {box,send}=fixture();let resolve!:(value:unknown)=>void;send.mockImplementation(()=>new Promise(done=>{resolve=done;}));const first=box.submit(tenant,actor,input),same=box.submit(tenant,actor,{...input});expect(same).toBe(first);await expect(box.submit(tenant,actor,{...input,reason:'Outro motivo de reparação'})).rejects.toThrow('andamento');await expect(box.submit(tenant,crypto.randomUUID(),input)).rejects.toThrow('andamento');await vi.waitFor(()=>expect(send).toHaveBeenCalledTimes(1));resolve({data:result(send.mock.calls[0][0]),error:null});await first;});
it('does not erase another tab record that arrives while a request is being sent',async()=>{const {box,send}=fixture();send.mockImplementation(async command=>{const other=JSON.parse(localStorage.getItem(key)!);other.payload.request_id=crypto.randomUUID();localStorage.setItem(key,JSON.stringify(other));return {data:result(command),error:null};});await box.submit(tenant,actor,input);expect(JSON.parse(localStorage.getItem(key)!).payload.request_id).not.toBe(send.mock.calls[0][0].request_id);});
it('blocks corrupt storage and storage write failures before sending',async()=>{const {box,send}=fixture();localStorage.setItem(key,'broken');await expect(box.submit(tenant,actor,input)).rejects.toThrow();expect(send).not.toHaveBeenCalled();localStorage.clear();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('quota');});await expect(box.submit(tenant,actor,input)).rejects.toThrow('quota');expect(send).not.toHaveBeenCalled();});
it('does not overwrite an existing pending request with a new submit',async()=>{const {box,send}=fixture();send.mockResolvedValue({data:null,error:{message:'lost'}});await expect(box.submit(tenant,actor,input)).rejects.toBeTruthy();const raw=localStorage.getItem(key);await expect(box.submit(tenant,actor,{...input,chargeId:crypto.randomUUID()})).rejects.toThrow('Recupere');expect(localStorage.getItem(key)).toBe(raw);expect(send).toHaveBeenCalledTimes(1);});
it('uses the tenant and actor lock and checks context before and after transport',async()=>{const {box,send,lock,assertContext}=fixture();send.mockImplementation(async command=>({data:result(command),error:null}));await box.submit(tenant,actor,input);expect(lock).toHaveBeenCalledWith(key,expect.any(Function));expect(assertContext).toHaveBeenCalledWith(tenant,actor);expect(assertContext).toHaveBeenCalledTimes(3);});

it('retains a response with a different approval consequence or amount than the reviewed request',async()=>{const {box,send}=fixture();send.mockImplementation(async command=>({data:{...result(command),approval_reset:false},error:null}));await expect(box.submit(tenant,actor,input)).rejects.toThrow();expect(localStorage.getItem(key)).not.toBeNull();send.mockImplementation(async command=>({data:{...result(command),cost_after_cents:'11000'},error:null}));await expect(box.recover(tenant,actor)).rejects.toThrow();expect(localStorage.getItem(key)).not.toBeNull();});
