import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {UnloadingCancellationWorkspace,UnloadingCancellationDetails} from '@/components/financial/UnloadingCancellationDialog';
import {UnloadingCancellationConfirmation} from '@/components/financial/UnloadingCancellationConfirmation';
import {unloadingCancellationFixture} from './helpers/unloadingCancellationFixture';
const mock=vi.hoisted(()=>({read:vi.fn(),send:vi.fn()}));vi.mock('@/lib/financial/unloadingCancellationClient',async importOriginal=>({...await importOriginal<typeof import('@/lib/financial/unloadingCancellationClient')>(),readUnloadingCancellationPreview:mock.read,sendUnloadingCancellation:mock.send}));
afterEach(()=>{cleanup();localStorage.clear();vi.resetAllMocks();});
const preview=unloadingCancellationFixture();
function setupConfirmation(refresh=vi.fn().mockResolvedValue(undefined)){Object.defineProperty(navigator,'locks',{configurable:true,value:{request:(_key:string,work:()=>Promise<unknown>)=>work()}});return render(<UnloadingCancellationConfirmation tenant={preview.tenant_id} actor={preview.actor_id} chargeId={preview.charge_id} preview={preview} refresh={refresh}/>);}
async function confirm(){fireEvent.change(screen.getByLabelText('Motivo do cancelamento coordenado'),{target:{value:'Descarga cancelada após conferência conjunta'}});fireEvent.click(screen.getByText('Revisar cancelamento coordenado'));expect(screen.getByText('Confirmar cancelamento coordenado')).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));await act(async()=>fireEvent.click(screen.getByText('Confirmar cancelamento coordenado')));}
const success=(command:{request_id:string})=>({data:{version:1,tenant_id:preview.tenant_id,actor_id:preview.actor_id,request_id:command.request_id,charge_id:preview.charge_id,receivable_id:preview.origin.receivable_id,expense_id:preview.expense_id,payable_id:preview.payable_id,expense_cancellation_id:crypto.randomUUID(),origin_amendment_id:crypto.randomUUID(),confirmed:true,cash_changed:false,cost_removed_cents:'15000',obligation_cancelled_cents:'15000',collection_cancelled_cents:'15000'},error:null});
it('requires explicit separate-effects consent and keeps confirmation terminal despite cache failure',async()=>{mock.send.mockImplementation(async command=>success(command));setupConfirmation(vi.fn().mockRejectedValue(Error('cache')));await confirm();await screen.findByText(/Cancelamento coordenado confirmado para/);expect(screen.getByRole('alert')).toHaveTextContent('foi confirmado, mas a consulta');expect(screen.queryByText('Confirmar cancelamento coordenado')).not.toBeInTheDocument();expect(mock.send).toHaveBeenCalledTimes(1);});
it('recovers the exact original after response loss even when the preview is unavailable',async()=>{mock.send.mockRejectedValueOnce(Error('offline')).mockImplementationOnce(async command=>success(command));const ui=setupConfirmation();await confirm();await screen.findByText('Recuperar pedido de cancelamento coordenado');const original=mock.send.mock.calls[0][0];expect(screen.getByText(/Valores do pedido preservado/)).toHaveTextContent('cobrança');ui.rerender(<UnloadingCancellationConfirmation tenant={preview.tenant_id} actor={preview.actor_id} chargeId={preview.charge_id} preview={undefined} refresh={async()=>{}}/>);await act(async()=>fireEvent.click(screen.getByText('Recuperar pedido de cancelamento coordenado')));expect(mock.send.mock.calls[1][0]).toEqual(original);await screen.findByText(/Cancelamento coordenado confirmado para/);});
it('shows missing effects as unknown with blockers, without offering cancellation',()=>{render(<UnloadingCancellationDetails data={{...preview,eligible:false,can_execute:false,effects:{...preview.effects,obligation_cancelled_cents:null},blockers:[{code:'unloading_cost_materialized',source_table:'driver_settlement_items',source_ids:[crypto.randomUUID()]}]}}/>);expect(screen.getByText('Obrigação a cancelar: Indeterminado')).toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('já compõe um acerto');expect(screen.queryByText('Confirmar cancelamento coordenado')).not.toBeInTheDocument();});
it('hides the old preview when the date changes and fails closed on preview error',async()=>{mock.read.mockResolvedValueOnce(preview).mockRejectedValueOnce({code:'PGRST202'});render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><UnloadingCancellationWorkspace tenant={preview.tenant_id} actor={preview.actor_id} chargeId={preview.charge_id}/></QueryClientProvider>);fireEvent.change(screen.getByLabelText('Data econômica do cancelamento'),{target:{value:'2026-09-11'}});await act(async()=>fireEvent.click(screen.getByText('Conferir cancelamento coordenado')));await screen.findByText('Revisar cancelamento coordenado');fireEvent.change(screen.getByLabelText('Data econômica do cancelamento'),{target:{value:'2026-09-12'}});expect(screen.queryByText('Revisar cancelamento coordenado')).not.toBeInTheDocument();await act(async()=>fireEvent.click(screen.getByText('Conferir cancelamento coordenado')));await screen.findByRole('alert');expect(screen.queryByLabelText('Efeitos do cancelamento coordenado')).not.toBeInTheDocument();expect(mock.send).not.toHaveBeenCalled();});
