import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {UnloadingCostCorrectionWorkspace,UnloadingCostCorrectionDetails} from '@/components/financial/UnloadingCostCorrectionDialog';
import {UnloadingCostCorrectionConfirmation} from '@/components/financial/UnloadingCostCorrectionConfirmation';
import {unloadingCostCorrectionFixture} from './helpers/unloadingCostCorrectionFixture';
const mock=vi.hoisted(()=>({read:vi.fn(),send:vi.fn()}));vi.mock('@/lib/financial/unloadingCostCorrectionClient',()=>({readUnloadingCostCorrectionPreview:mock.read,sendUnloadingCostCorrection:mock.send}));
afterEach(()=>{cleanup();localStorage.clear();vi.resetAllMocks();});
const preview=unloadingCostCorrectionFixture();
const success=(command:{request_id:string})=>({data:{version:1,tenant_id:preview.tenant_id,actor_id:preview.actor_id,request_id:command.request_id,charge_id:preview.charge_id,expense_id:preview.expense_id,payable_id:preview.payable_id,amendment_id:crypto.randomUUID(),confirmed:true,cost_before_cents:'15000',cost_after_cents:'12000',obligation_before_cents:'15000',obligation_after_cents:'12000',approval_reset:true,payable_status:'pending',cash_changed:false,collection_changed:false},error:null});
function setup(refresh=vi.fn().mockResolvedValue(undefined)){Object.defineProperty(navigator,'locks',{configurable:true,value:{request:(_key:string,work:()=>Promise<unknown>)=>work()}});return render(<UnloadingCostCorrectionConfirmation tenant={preview.tenant_id} actor={preview.actor_id} chargeId={preview.charge_id} preview={preview} refresh={refresh}/>);}
async function confirm(){fireEvent.change(screen.getByLabelText('Motivo da correção de custo'),{target:{value:'Retificar valor do serviço conferido'}});fireEvent.click(screen.getByText('Revisar correção de custo'));expect(screen.getByRole('alert')).toHaveTextContent('O novo valor exige outra aprovação');expect(screen.getByText('Confirmar correção de custo')).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));await act(async()=>fireEvent.click(screen.getByText('Confirmar correção de custo')));}
it('makes reapproval explicit before consent and keeps a confirmed result terminal after cache failure',async()=>{mock.send.mockImplementation(async command=>success(command));setup(vi.fn().mockRejectedValue(Error('cache')));await confirm();await screen.findByText(/Correção de custo confirmada para/);expect(screen.getByText(/A conta voltou a pendente e precisa de nova aprovação/)).toBeInTheDocument();expect(screen.queryByText('Confirmar correção de custo')).not.toBeInTheDocument();expect(mock.send).toHaveBeenCalledTimes(1);});
it('recovers an exact request including the approved-to-pending consequence after losing the response',async()=>{mock.send.mockRejectedValueOnce(Error('offline')).mockImplementationOnce(async command=>success(command));const ui=setup();await confirm();await screen.findByText('Recuperar pedido de correção de custo');const original=mock.send.mock.calls[0][0];ui.rerender(<UnloadingCostCorrectionConfirmation tenant={preview.tenant_id} actor={preview.actor_id} chargeId={preview.charge_id} preview={undefined} refresh={async()=>{}}/>);expect(screen.getByText(/A aprovação anterior será retirada/)).toBeInTheDocument();await act(async()=>fireEvent.click(screen.getByText('Recuperar pedido de correção de custo')));expect(mock.send.mock.calls[1][0]).toEqual(original);});
it('shows original and current obligation and unchanged collection without deriving unknown current cost',()=>{render(<UnloadingCostCorrectionDetails data={{...preview,cost:{...preview.cost,verified:false,issue:'unverified',effective_amount_cents:null},eligible:false,can_execute:false,effects:{...preview.effects,cost_before_cents:null,cost_delta_cents:null}}}/>);expect(screen.getByText('Obrigação original: R$ 150,00')).toBeInTheDocument();expect(screen.getByText('Custo vigente: Indeterminado')).toBeInTheDocument();expect(screen.getByText('Cobrança inalterada')).toBeInTheDocument();expect(screen.queryByText('Confirmar correção de custo')).not.toBeInTheDocument();});
it('invalidates a reviewed reduction when changed to an increase and fails closed on an unavailable RPC',async()=>{mock.read.mockResolvedValueOnce(preview).mockRejectedValueOnce({code:'PGRST202'});render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><UnloadingCostCorrectionWorkspace tenant={preview.tenant_id} actor={preview.actor_id} chargeId={preview.charge_id}/></QueryClientProvider>);fireEvent.change(screen.getByLabelText('Novo custo (R$)'),{target:{value:'120,00'}});await act(async()=>fireEvent.click(screen.getByText('Conferir novo custo e obrigação')));await screen.findByText('Revisar correção de custo');fireEvent.change(screen.getByLabelText('Novo custo (R$)'),{target:{value:'180,00'}});expect(screen.queryByText('Revisar correção de custo')).not.toBeInTheDocument();await act(async()=>fireEvent.click(screen.getByText('Conferir novo custo e obrigação')));await screen.findByRole('alert');expect(mock.read).toHaveBeenLastCalledWith(expect.objectContaining({amountCents:'18000'}));expect(mock.send).not.toHaveBeenCalled();});

it('explains money dependencies as cost regularization rather than cancellation',()=>{render(<UnloadingCostCorrectionDetails data={{...preview,eligible:false,can_execute:false,blockers:[{code:'finance_expense_money_dependency',source_table:'finance_movements',source_ids:[crypto.randomUUID()]}]}}/>);expect(screen.getByText(/Este custo possui vínculos/)).toHaveAttribute('role','alert');expect(screen.queryByText(/O cancelamento simples/)).not.toBeInTheDocument();});
