import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {UnloadingProjectionRepairConfirmation} from '@/components/financial/UnloadingProjectionRepairConfirmation';
import type {UnloadingProjectionRepairContext} from '@/lib/financial/unloadingProjectionRepairContract';
import {unloadingProjectionRepairKey} from '@/lib/financial/unloadingProjectionRepairOutbox';
const send=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/unloadingProjectionRepairCommandClient',()=>({sendUnloadingProjectionRepair:send}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),charge=crypto.randomUUID(),title=crypto.randomUUID();
const preview={tenant_id:tenant,actor_id:actor,charge_id:charge,receivable_id:title,revision:'a'.repeat(32),can_execute:true,eligible:true} as UnloadingProjectionRepairContext;
function show(data:UnloadingProjectionRepairContext|undefined=preview,refresh=vi.fn().mockResolvedValue(undefined)){Object.defineProperty(navigator,'locks',{configurable:true,value:{request:(_key:string,work:()=>Promise<unknown>)=>work()}});return render(<UnloadingProjectionRepairConfirmation tenant={tenant} actor={actor} chargeId={charge} preview={data} refresh={refresh}/>);}
async function confirm(){fireEvent.change(screen.getByLabelText('Motivo da reparação'),{target:{value:'Restaurar conforme origem preservada'}});fireEvent.click(screen.getByText('Revisar reparação'));fireEvent.click(screen.getByRole('checkbox'));await act(async()=>fireEvent.click(screen.getByText('Confirmar reparação do título')));}
const success=(command:{request_id:string;charge_id:string})=>({data:{version:1,tenant_id:tenant,actor_id:actor,request_id:command.request_id,charge_id:command.charge_id,receivable_id:title,repair_id:crypto.randomUUID(),confirmed:true,cash_changed:false,charge_changed:false,cost_changed:false},error:null});
afterEach(()=>{cleanup();localStorage.clear();send.mockReset();});
it('preserves an unknown request and recovers the exact body after the preview changes',async()=>{send.mockRejectedValueOnce(Error('offline')).mockImplementationOnce(async command=>success(command));const ui=show();await confirm();await screen.findByText('Recuperar pedido de reparação');const original=send.mock.calls[0][0];ui.rerender(<UnloadingProjectionRepairConfirmation tenant={tenant} actor={actor} chargeId={charge} preview={{...preview,revision:'b'.repeat(32),can_execute:false}} refresh={async()=>{}}/>);await act(async()=>fireEvent.click(screen.getByText('Recuperar pedido de reparação')));await screen.findByText(/Reparação confirmada para/);expect(send.mock.calls[1][0]).toEqual(original);expect(localStorage.length).toBe(0);});
it('keeps confirmation terminal after a cache failure',async()=>{send.mockImplementation(async command=>success(command));show(preview,vi.fn().mockRejectedValue(Error('cache')));await confirm();await screen.findByText(/Reparação confirmada para/);expect(screen.getByRole('alert')).toHaveTextContent('foi confirmada, mas a consulta');expect(screen.queryByText('Revisar reparação')).not.toBeInTheDocument();expect(send).toHaveBeenCalledTimes(1);});
it('shows the original identities for another charge and responds to storage events',async()=>{show(undefined);const other=crypto.randomUUID();localStorage.setItem(unloadingProjectionRepairKey(tenant,actor),JSON.stringify({version:1,tenantId:tenant,actorId:actor,receivableId:title,payload:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),charge_id:other,revision:'a'.repeat(32),reason:'Motivo do pedido anterior'}}));await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key:unloadingProjectionRepairKey(tenant,actor)})));expect(screen.getByRole('alert')).toHaveTextContent('outra descarga');expect(screen.getByText(/Pedido preservado/)).toHaveTextContent(other);expect(screen.getByText('Motivo: Motivo do pedido anterior')).toBeInTheDocument();expect(send).not.toHaveBeenCalled();});
it('does not offer a fresh confirmation during refetch or corrupted storage',()=>{localStorage.setItem(unloadingProjectionRepairKey(tenant,actor),'broken');show(undefined);expect(screen.queryByText('Revisar reparação')).not.toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('inconsistente');expect(send).not.toHaveBeenCalled();});
