import {beforeEach,it,expect,vi} from 'vitest';
import {createUnloadingCostRegularizationOutbox,pendingUnloadingCostRegularization} from '@/lib/financial/unloadingCostRegularizationOutbox';
import {regularizationIds as i,regularizationPreview as p,regularizationProposal as proposal} from './helpers/unloadingCostRegularizationFixture';
const input={chargeId:i.charge,expenseId:i.expense,payableId:null,proposal,expected:p.effects,revision:p.revision,reason:'Conferência do custo e da responsabilidade'};
function setup(send:ReturnType<typeof vi.fn>){return createUnloadingCostRegularizationOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),assertContext:()=>{},changed:()=>{},lock:async<T,>(_key:string,work:()=>Promise<T>)=>work(),send});}
function success(command:Record<string,unknown>){return {data:{version:1,tenant_id:i.tenant,actor_id:i.actor,request_id:command.request_id,charge_id:i.charge,expense_id:i.expense,payable_id:null,regularization_id:crypto.randomUUID(),disposition_ids:[crypto.randomUUID()],confirmed:true,effects:p.effects},error:null};}
beforeEach(()=>localStorage.clear());
it('recovers exact source allocation and pending responsibility after unknown response',async()=>{const send=vi.fn().mockRejectedValueOnce(new Error('lost')).mockImplementationOnce(async(command)=>success(command));const outbox=setup(send);await expect(outbox.submit(i.tenant,i.actor,input)).rejects.toThrow('lost');expect(pendingUnloadingCostRegularization(localStorage,i.tenant,i.actor)?.payload.proposal).toEqual(proposal);await outbox.recover(i.tenant,i.actor);expect(send.mock.calls[1][0]).toEqual(send.mock.calls[0][0]);expect(pendingUnloadingCostRegularization(localStorage,i.tenant,i.actor)).toBeNull();});
it('preserves an uncertain request after later rejection or mismatched disposition effects',async()=>{const send=vi.fn().mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce({data:null,error:{code:'40001'}}).mockImplementationOnce(async(command)=>({...success(command),data:{...success(command).data,effects:{...p.effects,movement_capacity_released_cents:'3000'}}}));const outbox=setup(send);await expect(outbox.submit(i.tenant,i.actor,input)).rejects.toThrow();await expect(outbox.recover(i.tenant,i.actor)).rejects.toMatchObject({code:'40001'});await expect(outbox.recover(i.tenant,i.actor)).rejects.toThrow();expect(pendingUnloadingCostRegularization(localStorage,i.tenant,i.actor)).not.toBeNull();});
it('releases only a definitive first rejection and rejects a result for another actor',async()=>{const send=vi.fn().mockResolvedValueOnce({data:null,error:{code:'23514'}}).mockImplementationOnce(async(command)=>({data:{...success(command).data,actor_id:crypto.randomUUID()},error:null}));const outbox=setup(send);await expect(outbox.submit(i.tenant,i.actor,input)).rejects.toMatchObject({code:'23514'});expect(pendingUnloadingCostRegularization(localStorage,i.tenant,i.actor)).toBeNull();await expect(outbox.submit(i.tenant,i.actor,input)).rejects.toThrow('incompatível');expect(pendingUnloadingCostRegularization(localStorage,i.tenant,i.actor)).not.toBeNull();});
