import {regularizationPreview as preview} from './helpers/unloadingCostRegularizationFixture';
import {unloadingCostRegularizationPreviewSchema} from '@/lib/financial/unloadingCostRegularizationContract';
import {it,expect} from 'vitest';
import {unloadingCostRegularizationCommandSchema,unloadingCostRegularizationProposalSchema} from '@/lib/financial/unloadingCostRegularizationContract';
const source={source_kind:'expense_allocation',source_id:crypto.randomUUID(),applied_cents:'12000',disposition_type:'driver_custody',responsible_id:crypto.randomUUID()};
it('preserves exact per-source amounts and a nullable payable for a driver-funded cost',()=>{const value={version:1,tenant_id:crypto.randomUUID(),request_id:crypto.randomUUID(),charge_id:crypto.randomUUID(),expense_id:crypto.randomUUID(),payable_id:null,revision:'a'.repeat(32),proposal:{amount_cents:'12000',dispositions:[source]},reason:'  Conferência documentada do custo  '};expect(unloadingCostRegularizationCommandSchema.parse(value)).toEqual(value);});
it('rejects duplicate source allocation, negative coverage and imprecise numeric cents',()=>{expect(unloadingCostRegularizationProposalSchema.safeParse({amount_cents:'12000',dispositions:[source,source]}).success).toBe(false);expect(unloadingCostRegularizationProposalSchema.safeParse({amount_cents:'12000',dispositions:[{...source,applied_cents:'-1'}]}).success).toBe(false);expect(unloadingCostRegularizationProposalSchema.safeParse({amount_cents:12000,dispositions:[source]}).success).toBe(false);});

it('accepts diagnostic negative residual only when ineligible and rejects invented released capacity',()=>{expect(unloadingCostRegularizationPreviewSchema.safeParse(preview).success).toBe(true);expect(unloadingCostRegularizationPreviewSchema.safeParse({...preview,effects:{...preview.effects,movement_capacity_released_cents:'3000'}}).success).toBe(false);const invalid={...preview,eligible:false,can_execute:false,blockers:[{code:'finance_cost_disposition_mismatch',source_table:null,source_ids:[]}],dispositions:[{...preview.dispositions[0],applied_cents:'16000',residual_cents:'-1000'}],effects:{...preview.effects,applied_cents:'16000',residual_cents:'-1000',driver_custody_cents:'-1000'}};expect(unloadingCostRegularizationPreviewSchema.safeParse(invalid).success).toBe(true);expect(unloadingCostRegularizationPreviewSchema.safeParse({...invalid,eligible:true,can_execute:true}).success).toBe(false);});
