// @vitest-environment node
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {createUnloadingCostCorrectionDatabase,installUnloadingCostCorrection,seedUnloadingRepairSource} from './helpers/unloadingCostCorrectionDatabase';
import {financeIds as i,financeAs} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createUnloadingCostCorrectionDatabase>>;
beforeAll(async()=>{db=await createUnloadingCostCorrectionDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[i.operator]);await db.query("update tenant_memberships set role='admin' where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);});
afterEach(async()=>db.exec('rollback'));afterAll(async()=>db.close());
const base=()=>({version:1,tenant_id:i.tenant,request_id:randomUUID(),reason:'RegularizaÃ§Ã£o real com recuperaÃ§Ã£o identificada'});
async function rpc<T>(name:string,payload:unknown){return(await financeAs<{v:T}>(db,i.operator,'select '+name+'($1) v',[payload])).rows[0].v;}
const install=async()=>{await db.exec(readFileSync('supabase/migrations/20260911072557_finance_unloading_covered_cost_regularization.sql','utf8'));if(process.env.CAPTURE_COST_METADATA==='1'){const metadata=(await db.query("select p.oid::regprocedure::text signature,md5(p.prosrc) prosrc_md5,p.prosecdef,p.proconfig,p.proacl::text acl from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='finance_private' and p.proname in('expense_cost_effective','expense_cost_funding','unloading_cost_regularization_context','regularize_unloading_cost','guard_cost_regularization_source') order by p.proname")).rows;writeFileSync('docs/qa/finance-covered-cost-core-catalog-2026-09-11.json',JSON.stringify(metadata,null,2)+'\n');}};
async function seed(beneficiary?:string){const c=await seedUnloadingRepairSource(db,true);await installUnloadingCostCorrection(db);const baseline=readFileSync('supabase/migrations/20260824224152_baseline.sql','utf8');const recalc=baseline.match(/CREATE OR REPLACE FUNCTION public\._recalc_payable_paid\(\)[\s\S]*?\$function\$;/)?.[0];if(!recalc)throw new Error('real recalc missing');await db.exec(recalc.replace('FROM public.payables_payments WHERE','FROM finance_private.active_payable_payments WHERE'));await db.exec('create trigger trg_recalc_payable_paid after insert or delete or update on payables_payments for each row execute function public._recalc_payable_paid()');const e=(await db.query<{id:string,payable_id:string,supplier_id:string,supplier_name:string}>('select id,payable_id,supplier_id,supplier_name from finance_expense_items where unloading_id=$1',[c.charge_id])).rows[0];await db.query("update payables set status='approved' where id=$1",[e.payable_id]);const m=await rpc<{movement_id:string}>('record_finance_movement',{...base(),bank_account_id:i.account,direction:'out',nature:'payment',amount_cents:15000,occurred_on:'2026-08-02',description:'Pagamento do custo original',beneficiary_name:beneficiary??e.supplier_name});const payment=await rpc<{link_id:string,payment_id:string}>('apply_finance_payable_movement',{...base(),payable_id:e.payable_id,movement_id:m.movement_id,amount_cents:15000,method:'pix'});return {...c,...e,...m,...payment};}
type Context={revision:string,eligible:boolean,blockers:unknown[],effects:Record<string,unknown>};
const proposal=(s:{link_id:string,supplier_id:string},amount='12000')=>({amount_cents:amount,dispositions:[{source_kind:'payable_link',source_id:s.link_id,applied_cents:amount,disposition_type:'payment_recovery',responsible_id:s.supplier_id}]});
async function preview(charge:string,p:unknown){return(await db.query<{v:Context}>('select finance_private.unloading_cost_regularization_context($1,$2,$3) v',[i.tenant,charge,p])).rows[0].v;}
async function command(p:unknown){await db.exec('savepoint regularization_call');try{const v=(await db.query<{v:{regularization_id:string}}>('select finance_private.regularize_unloading_cost($1) v',[p])).rows[0].v;await db.exec('release savepoint regularization_call');return v;}catch(e){await db.exec('rollback to savepoint regularization_call');throw e;}}
it('preserves paid150 and reservation150 while recognizing recovery30 then50 with replay',async()=>{const s=await seed();const original=(await db.query("select jsonb_build_object('payable',(select to_jsonb(p) from payables p where id=$1),'payments',(select jsonb_agg(to_jsonb(p)) from payables_payments p),'movements',(select jsonb_agg(to_jsonb(m)) from finance_movements m),'expense',(select to_jsonb(e) from finance_expense_items e where id=$2)) v",[s.payable_id,s.id])).rows;await install();let p=proposal(s);let ctx=await preview(s.charge_id,p);expect(ctx.blockers).toEqual([]);const payload={...base(),charge_id:s.charge_id,expense_id:s.id,payable_id:s.payable_id,proposal:p,revision:ctx.revision};const r=await command(payload);expect(await command(payload)).toEqual(r);p=proposal(s,'10000');ctx=await preview(s.charge_id,p);expect(ctx.eligible).toBe(true);await command({...payload,request_id:randomUUID(),proposal:p,revision:ctx.revision});await db.exec('set constraints all immediate');expect((await db.query("select jsonb_build_object('payable',(select to_jsonb(p) from payables p where id=$1),'payments',(select jsonb_agg(to_jsonb(p)) from payables_payments p),'movements',(select jsonb_agg(to_jsonb(m)) from finance_movements m),'expense',(select to_jsonb(e) from finance_expense_items e where id=$2)) v",[s.payable_id,s.id])).rows).toEqual(original);expect((await db.query<{v:{verified:boolean,regularization:{residual_cents:string}}}>('select finance_private.expense_cost_effective($1,$2) v',[i.tenant,s.id])).rows[0].v).toMatchObject({verified:true,regularization:{residual_cents:'5000'}});expect((await db.query<{v:string}>('select finance_private.movement_used_cents($1,$2)::text v',[i.tenant,s.movement_id])).rows[0].v).toBe('15000');});
it('keeps an advance150 reserved and records driver responsibility30 without creating a payable',async()=>{
 await seedUnloadingRepairSource(db,true);await installUnloadingCostCorrection(db);
 const src=(await db.query<{trip_id:string,supplier_id:string,receipt_path:string}>('select b.trip_id,e.supplier_id,e.receipt_path from finance_expense_items e join finance_expense_batches b on b.id=e.batch_id')).rows[0];
 await db.query('update dispatch_trips set driver_id=$1 where id=$2',[i.driver,src.trip_id]);
 const stop=randomUUID(),doc=randomUUID(),expense=randomUUID();await db.query("insert into dispatch_stops(id,tenant_id,dispatch_trip_id,stop_order,status,client_id,destination) values($1,$2,$3,2,'completed',$4,'Entrega financiada')",[stop,i.tenant,src.trip_id,src.supplier_id]);await db.query("insert into fiscal_documents(id,tenant_id,client_id,supplier_id,document_type,status) values($1,$2,$3,$3,'inbound','ready')",[doc,i.tenant,src.supplier_id]);await db.query('insert into dispatch_stop_documents(tenant_id,dispatch_stop_id,fiscal_document_id) values($1,$2,$3)',[i.tenant,stop,doc]);
 const delivery=(await financeAs<{v:{revision:string}}>(db,i.operator,'select get_finance_delivery_context($1,$2) v',[i.tenant,stop])).rows[0].v;
 const movement=await rpc<{movement_id:string}>('record_finance_movement',{...base(),bank_account_id:i.account,direction:'out',nature:'driver_advance',driver_id:i.driver,amount_cents:15000,occurred_on:'2026-08-02',description:'Envio ao motorista com responsabilidade',beneficiary_name:'Motorista na data do envio'});
 await rpc('record_finance_expense_batch',{...base(),context:'trip',trip_id:src.trip_id,description:'Descarga coberta pelo envio original',items:[{id:expense,category:'unloading',description:'Descarga integralmente coberta',amount_cents:15000,occurred_on:'2026-08-02',supplier_id:src.supplier_id,supplier_name:'Prestador conferido',payee_type:'supplier',receipt_path:src.receipt_path,allocations:[{movement_id:movement.movement_id,amount_cents:15000}],stop_id:stop,delivery_revision:delivery.revision}]});
 const e=(await db.query<{unloading_id:string,payable_id:string|null}>('select unloading_id,payable_id from finance_expense_items where id=$1',[expense])).rows[0];expect(e.payable_id).toBeNull();const a=(await db.query<{id:string}>('select id from finance_expense_allocations where expense_id=$1',[expense])).rows[0];const original=(await db.query('select to_jsonb(a) v from finance_expense_allocations a where expense_id=$1',[expense])).rows;
 await install();const p={amount_cents:'12000',dispositions:[{source_kind:'expense_allocation',source_id:a.id,applied_cents:'12000',disposition_type:'driver_custody',responsible_id:i.driver}]};const ctx=await preview(e.unloading_id,p);expect(ctx.blockers).toEqual([]);expect(ctx.effects.driver_custody_cents).toBe('3000');await command({...base(),charge_id:e.unloading_id,expense_id:expense,payable_id:null,proposal:p,revision:ctx.revision});await db.exec('set constraints all immediate');expect((await db.query('select to_jsonb(a) v from finance_expense_allocations a where expense_id=$1',[expense])).rows).toEqual(original);expect((await db.query<{v:string}>('select finance_private.movement_used_cents($1,$2)::text v',[i.tenant,movement.movement_id])).rows[0].v).toBe('15000');await db.exec('alter table drivers add column if not exists name text');await db.query("update drivers set name='Nome alterado depois da captura' where id=$1",[i.driver]);expect((await db.query<{v:{verified:boolean}}>('select finance_private.expense_cost_effective($1,$2) v',[i.tenant,expense])).rows[0].v.verified).toBe(true);
});
it('denies reversal and further allocation, preserves atomic rollback and current tenant permissions',async()=>{
 const s=await seed();const reverseSql=readFileSync('supabase/migrations/20260910003529_finance_payable_link_reversal.sql','utf8');await db.exec(reverseSql.slice(reverseSql.indexOf('create function finance_private.reverse_payable_link'),reverseSql.indexOf('create function finance_private.payable_payment_history')));await install();const p=proposal(s),ctx=await preview(s.charge_id,p),payload={...base(),charge_id:s.charge_id,expense_id:s.id,payable_id:s.payable_id,proposal:p,revision:ctx.revision};
 await expect(command({...payload,revision:'0'.repeat(32)})).rejects.toMatchObject({code:'40001'});
 await db.exec("create function public.qa_regularization_fault() returns trigger language plpgsql as $$begin if new.action='unloading_cost_regularized' then raise exception 'qa_regularization_fault';end if;return new;end$$;create trigger qa_regularization_fault before insert on finance_events for each row execute function public.qa_regularization_fault()");await expect(command(payload)).rejects.toThrow('qa_regularization_fault');expect((await db.query('select count(*)::int n from finance_private.expense_cost_regularizations')).rows).toEqual([{n:0}]);expect((await db.query('select count(*)::int n from finance_private.expense_cost_dispositions')).rows).toEqual([{n:0}]);await db.exec('drop trigger qa_regularization_fault on finance_events');await command(payload);
 await expect(rpc('reverse_finance_payable_link',{...base(),link_id:s.link_id})).rejects.toThrow('finance_cost_disposition_requires_resolution');expect((await db.query('select count(*)::int n from finance_payable_link_reversals')).rows).toEqual([{n:0}]);
 await db.exec('savepoint allocation_attempt');await expect(db.query('insert into finance_expense_allocations(tenant_id,expense_id,movement_id,amount_cents,created_by) values($1,$2,$3,3000,$4)',[i.tenant,s.id,s.movement_id,i.operator])).rejects.toThrow('finance_cost_disposition_requires_resolution');await db.exec('rollback to savepoint allocation_attempt');
 await db.exec('savepoint mixed');await db.query("insert into tenant_memberships(tenant_id,user_id,role,active) values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(command(payload)).rejects.toMatchObject({code:'42501'});await db.exec('rollback to savepoint mixed');
 await expect(command({...payload,tenant_id:i.otherTenant})).rejects.toMatchObject({code:'42501'});await db.exec('set constraints all immediate');
});

it('rejects contradictory beneficiary evidence',async()=>{const s=await seed('Outra pessoa explicitamente registrada');await install();expect((await preview(s.charge_id,proposal(s))).blockers).toEqual(expect.arrayContaining([expect.objectContaining({code:'finance_cost_funding_unverified'})]));});
it('protects old payable identity and rejects incomplete or duplicated dispositions',async()=>{const s=await seed();await install();const p=proposal(s);const bad={...p,dispositions:[...p.dispositions,...p.dispositions]};expect((await preview(s.charge_id,bad)).eligible).toBe(false);const ctx=await preview(s.charge_id,p);await command({...base(),charge_id:s.charge_id,expense_id:s.id,payable_id:s.payable_id,proposal:p,revision:ctx.revision});await db.exec('savepoint old_identity');await expect(db.query('update payables set tenant_id=$1 where id=$2',[i.otherTenant,s.payable_id])).rejects.toThrow('finance_cost_disposition_requires_resolution');await db.exec('rollback to savepoint old_identity');await db.exec('set constraints all immediate');});
