import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {UnloadingOriginCorrectionConfirmation} from '@/components/financial/UnloadingOriginCorrectionConfirmation';
import type {UnloadingOriginCorrectionContext} from '@/lib/financial/unloadingOriginCorrectionContract';
import {unloadingOriginCorrectionKey} from '@/lib/financial/unloadingOriginCorrectionOutbox';
const send=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/unloadingOriginCorrectionClient',()=>({sendUnloadingOriginCorrection:send,unloadingOriginCorrectionErrorLabel:(e:unknown)=>e instanceof Error?e.message:'Não confirmado'}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),charge=crypto.randomUUID(),title=crypto.randomUUID();
const proposal={operation:'amend_origin' as const,supplier_id:crypto.randomUUID(),amount_cents:'12000',effective_on:'2026-09-11',collection_right_only:true as const};
const preview={proposal,tenant_id:tenant,actor_id:actor,charge_id:charge,receivable_id:title,revision:'a'.repeat(32),can_execute:true,eligible:true} as UnloadingOriginCorrectionContext;
function show(data:UnloadingOriginCorrectionContext|undefined=preview,refresh=vi.fn().mockResolvedValue(undefined)){Object.defineProperty(navigator,'locks',{configurable:true,value:{request:(_key:string,work:()=>Promise<unknown>)=>work()}});return render(<UnloadingOriginCorrectionConfirmation tenant={tenant} actor={actor} chargeId={charge} preview={data} refresh={refresh}/>);}
async function confirm(){fireEvent.change(screen.getByLabelText('Motivo da correção da cobrança'),{target:{value:'Restaurar conforme origem preservada'}});fireEvent.click(screen.getByText('Revisar correção da cobrança'));fireEvent.click(screen.getByRole('checkbox'));await act(async()=>fireEvent.click(screen.getByText('Confirmar correção da cobrança')));}
const success=(command:{request_id:string;charge_id:string})=>({data:{version:1,tenant_id:tenant,actor_id:actor,request_id:command.request_id,charge_id:command.charge_id,receivable_id:title,amendment_id:crypto.randomUUID(),confirmed:true,cash_changed:false,payable_changed:false,cost_changed:false},error:null});
afterEach(()=>{cleanup();localStorage.clear();send.mockReset();});
it('preserves an unknown request and recovers the exact body after the preview changes',async()=>{send.mockRejectedValueOnce(Error('offline')).mockImplementationOnce(async command=>success(command));const ui=show();await confirm();await screen.findByText('Recuperar pedido de correção da cobrança');const original=send.mock.calls[0][0];ui.rerender(<UnloadingOriginCorrectionConfirmation tenant={tenant} actor={actor} chargeId={charge} preview={{...preview,revision:'b'.repeat(32),can_execute:false}} refresh={async()=>{}}/>);await act(async()=>fireEvent.click(screen.getByText('Recuperar pedido de correção da cobrança')));await screen.findByText(/Correção da cobrança confirmada para/);expect(send.mock.calls[1][0]).toEqual(original);expect(localStorage.length).toBe(0);});
it('keeps confirmation terminal after a cache failure',async()=>{send.mockImplementation(async command=>success(command));show(preview,vi.fn().mockRejectedValue(Error('cache')));await confirm();await screen.findByText(/Correção da cobrança confirmada para/);expect(screen.getByRole('alert')).toHaveTextContent('foi confirmada, mas a consulta');expect(screen.queryByText('Revisar correção da cobrança')).not.toBeInTheDocument();expect(send).toHaveBeenCalledTimes(1);});
it('shows the original identities for another charge and responds to storage events',async()=>{show(undefined);const other=crypto.randomUUID();localStorage.setItem(unloadingOriginCorrectionKey(tenant,actor),JSON.stringify({version:1,tenantId:tenant,actorId:actor,receivableId:title,payload:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),charge_id:other,revision:'a'.repeat(32),proposal,reason:'Motivo do pedido anterior'}}));await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key:unloadingOriginCorrectionKey(tenant,actor)})));expect(screen.getByRole('alert')).toHaveTextContent('outra descarga');expect(screen.getByText(/Pedido preservado/)).toHaveTextContent(other);expect(screen.getByText('Motivo: Motivo do pedido anterior')).toBeInTheDocument();expect(send).not.toHaveBeenCalled();});
it('does not offer a fresh confirmation during refetch or corrupted storage',()=>{localStorage.setItem(unloadingOriginCorrectionKey(tenant,actor),'broken');show(undefined);expect(screen.queryByText('Revisar correção da cobrança')).not.toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('inconsistente');expect(send).not.toHaveBeenCalled();});
