import {cleanup,render,screen,within} from '@testing-library/react';
import {afterEach,expect,it} from 'vitest';
import {UnloadingOriginVersions,type UnloadingOriginVersionsModel} from '@/components/financial/UnloadingOriginVersions';
const supplier={id:'supplier-a',name:'Fornecedor A'};
const fixture=():UnloadingOriginVersionsModel=>({chargeId:'charge',deliveryId:'delivery',receivableId:'title',original:{supplier,amountCents:'15000',effectiveOn:'2026-01-01'},current:{status:'active',supplier,amountCents:'12000',versionId:'amendment'},adjustments:[{id:'amendment',operation:'amend',effectiveOn:'2026-02-01',capturedAt:'2026-03-01',actorId:'actor-a',actorName:'Ana',reason:'Redução do direito de cobrança',legs:[{supplier,deltaCents:'-3000'}]}],preservedCost:{expenseId:'expense',amountCents:'15000',payableId:'payable',payeeName:'Motorista'},historyComplete:true});
afterEach(cleanup);
it('separates original/current/preserved cost and identifies a negative manual adjustment',()=>{render(<UnloadingOriginVersions data={fixture()}/>);expect(within(screen.getByRole('region',{name:'Cobrança original'})).getByText('R$ 150,00')).toBeInTheDocument();expect(within(screen.getByRole('region',{name:'Cobrança vigente'})).getByText('R$ 120,00')).toBeInTheDocument();expect(screen.getByText(/ajuste -R\$ 30,00/)).toBeInTheDocument();expect(screen.getByText('Ajuste manual — alteração').parentElement).toHaveClass('border-amber-600');expect(screen.getByText('Ana (actor-a)')).toBeInTheDocument();expect(screen.getByText(/Gasto expense/)).toHaveTextContent('R$ 150,00');expect(screen.queryByRole('button')).not.toBeInTheDocument();});
it('keeps the cost and original visible after cancellation without fabricating a receipt',()=>{const data=fixture();data.current={...data.current,status:'cancelled',amountCents:'0'};data.adjustments[0]={...data.adjustments[0],operation:'cancel',legs:[{supplier,deltaCents:'-15000'}]};render(<UnloadingOriginVersions data={data}/>);expect(screen.getByText('Cobrança cancelada')).toBeInTheDocument();expect(screen.getByText(/Gasto expense/)).toHaveTextContent('R$ 150,00');expect(screen.getByText(/não desfaz o gasto/)).toBeInTheDocument();expect(screen.queryByRole('button')).not.toBeInTheDocument();});
it('does not turn unknown or partial information into zero or derive current value from a page',()=>{const data=fixture();data.current={status:'unknown',supplier:null,amountCents:null,versionId:null};data.historyComplete=false;data.preservedCost=null;render(<UnloadingOriginVersions data={data}/>);expect(screen.getByRole('alert')).toHaveTextContent('histórico exibido é parcial');expect(within(screen.getByRole('region',{name:'Cobrança vigente'})).getByText('Indeterminado')).toBeInTheDocument();expect(screen.queryByText('R$ 0,00')).not.toBeInTheDocument();expect(screen.getByText('Informação do custo indisponível nesta consulta.')).toBeInTheDocument();});
