import {afterEach,expect,it,vi} from 'vitest';
import {createUnloadingCancellationOutbox,pendingUnloadingCancellation,unloadingCancellationKey} from '@/lib/financial/unloadingCancellationOutbox';
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),charge=crypto.randomUUID(),receivable=crypto.randomUUID();
const expected={receivable_id:receivable,expense_id:crypto.randomUUID(),payable_id:crypto.randomUUID(),cost_removed_cents:'15000',obligation_cancelled_cents:'15000',collection_cancelled_cents:'12000'};
const input={chargeId:charge,expected,effectiveOn:'2026-09-11',revision:'a'.repeat(32),reason:'  Restaurar título pela origem  '};
const key=unloadingCancellationKey(tenant,actor);
function fixture(){const send=vi.fn(),changed=vi.fn(),assertContext=vi.fn(),lock=vi.fn();const withLock=async<T>(lockKey:string,work:()=>Promise<T>):Promise<T>=>{lock(lockKey,work);return work();};const box=createUnloadingCancellationOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),assertContext,changed,lock:withLock,send});return {box,send,changed,assertContext,lock};}
function result(command:{request_id:string}){return {version:1,tenant_id:tenant,actor_id:actor,request_id:command.request_id,charge_id:charge,...expected,expense_cancellation_id:crypto.randomUUID(),origin_amendment_id:crypto.randomUUID(),confirmed:true,cash_changed:false};}
afterEach(()=>{localStorage.clear();vi.restoreAllMocks();});
it('persists before transport and retains exact body, including whitespace, on lost response and replay',async()=>{const {box,send}=fixture();send.mockImplementationOnce(async command=>{expect(JSON.parse(localStorage.getItem(key)!).payload).toEqual(command);return {data:null,error:{message:'lost'}};}).mockImplementationOnce(async command=>({data:result(command),error:null}));await expect(box.submit(tenant,actor,input)).rejects.toMatchObject({message:'lost'});const raw=localStorage.getItem(key);expect(pendingUnloadingCancellation(localStorage,tenant,actor)?.payload.reason).toBe(input.reason);await expect(box.recover(tenant,actor)).resolves.toMatchObject({confirmed:true});expect(send.mock.calls[1][0]).toEqual(JSON.parse(raw!).payload);expect(localStorage.getItem(key)).toBeNull();});
it('clears only a first definitive rejection, retaining previously uncertain requests',async()=>{const {box,send}=fixture();send.mockResolvedValue({data:null,error:{code:'23514',message:'blocked'}});await expect(box.submit(tenant,actor,input)).rejects.toMatchObject({code:'23514'});expect(localStorage.getItem(key)).toBeNull();send.mockResolvedValueOnce({data:null,error:{message:'lost'}});await expect(box.submit(tenant,actor,input)).rejects.toBeTruthy();const raw=localStorage.getItem(key);await expect(box.recover(tenant,actor)).rejects.toMatchObject({code:'23514'});expect(localStorage.getItem(key)).toBe(raw);});
it.each(['tenant_id','actor_id','request_id','charge_id','receivable_id','expense_id','payable_id'])('preserves request when response %s mismatches',async field=>{const {box,send}=fixture();send.mockImplementation(async command=>({data:{...result(command),[field]:crypto.randomUUID()},error:null}));await expect(box.submit(tenant,actor,input)).rejects.toThrow();expect(localStorage.getItem(key)).not.toBeNull();});
it('coalesces identical in-flight input and rejects another scope or body',async()=>{const {box,send}=fixture();let resolve!:(value:unknown)=>void;send.mockImplementation(()=>new Promise(done=>{resolve=done;}));const first=box.submit(tenant,actor,input),same=box.submit(tenant,actor,{...input});expect(same).toBe(first);await expect(box.submit(tenant,actor,{...input,reason:'Outro motivo de reparação'})).rejects.toThrow('andamento');await expect(box.submit(tenant,crypto.randomUUID(),input)).rejects.toThrow('andamento');await vi.waitFor(()=>expect(send).toHaveBeenCalledTimes(1));resolve({data:result(send.mock.calls[0][0]),error:null});await first;});
it('does not erase another tab record that arrives while a request is being sent',async()=>{const {box,send}=fixture();send.mockImplementation(async command=>{const other=JSON.parse(localStorage.getItem(key)!);other.payload.request_id=crypto.randomUUID();localStorage.setItem(key,JSON.stringify(other));return {data:result(command),error:null};});await box.submit(tenant,actor,input);expect(JSON.parse(localStorage.getItem(key)!).payload.request_id).not.toBe(send.mock.calls[0][0].request_id);});
it('blocks corrupt storage and storage write failures before sending',async()=>{const {box,send}=fixture();localStorage.setItem(key,'broken');await expect(box.submit(tenant,actor,input)).rejects.toThrow();expect(send).not.toHaveBeenCalled();localStorage.clear();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('quota');});await expect(box.submit(tenant,actor,input)).rejects.toThrow('quota');expect(send).not.toHaveBeenCalled();});
it('does not overwrite an existing pending request with a new submit',async()=>{const {box,send}=fixture();send.mockResolvedValue({data:null,error:{message:'lost'}});await expect(box.submit(tenant,actor,input)).rejects.toBeTruthy();const raw=localStorage.getItem(key);await expect(box.submit(tenant,actor,{...input,chargeId:crypto.randomUUID()})).rejects.toThrow('Recupere');expect(localStorage.getItem(key)).toBe(raw);expect(send).toHaveBeenCalledTimes(1);});
it('uses the tenant and actor lock and checks context before and after transport',async()=>{const {box,send,lock,assertContext}=fixture();send.mockImplementation(async command=>({data:result(command),error:null}));await box.submit(tenant,actor,input);expect(lock).toHaveBeenCalledWith(key,expect.any(Function));expect(assertContext).toHaveBeenCalledWith(tenant,actor);expect(assertContext).toHaveBeenCalledTimes(3);});

it('preserves an uncertain request when confirmed monetary effects differ from the saved preview',async()=>{const {box,send}=fixture();send.mockImplementation(async command=>({data:{...result(command),cost_removed_cents:'1'},error:null}));await expect(box.submit(tenant,actor,input)).rejects.toThrow();expect(localStorage.getItem(key)).not.toBeNull();});

it('replays the same prior-origin identity after response loss and rejects a substituted origin event',async()=>{const {box,send}=fixture();const prior=crypto.randomUUID();const remaining={...input,priorOriginAmendmentId:prior,expected:{...expected,collection_cancelled_cents:'0'}};send.mockResolvedValueOnce({data:null,error:{message:'lost'}}).mockImplementationOnce(async command=>({data:{...result(command),collection_cancelled_cents:'0',origin_amendment_id:crypto.randomUUID()},error:null})).mockImplementationOnce(async command=>({data:{...result(command),collection_cancelled_cents:'0',origin_amendment_id:prior},error:null}));await expect(box.submit(tenant,actor,remaining)).rejects.toBeTruthy();const raw=localStorage.getItem(key);expect(JSON.parse(raw!).payload.prior_origin_amendment_id).toBe(prior);await expect(box.recover(tenant,actor)).rejects.toThrow('incompatível');expect(localStorage.getItem(key)).toBe(raw);await expect(box.recover(tenant,actor)).resolves.toMatchObject({origin_amendment_id:prior,collection_cancelled_cents:'0'});expect(send.mock.calls[1][0]).toEqual(send.mock.calls[0][0]);expect(send.mock.calls[2][0]).toEqual(send.mock.calls[0][0]);expect(localStorage.getItem(key)).toBeNull();});
it('requires prior identity for zero collection effect and forbids it for an active collection',async()=>{const {box,send}=fixture();await expect(box.submit(tenant,actor,{...input,expected:{...expected,collection_cancelled_cents:'0'}})).rejects.toThrow();await expect(box.submit(tenant,actor,{...input,priorOriginAmendmentId:crypto.randomUUID()})).rejects.toThrow();expect(send).not.toHaveBeenCalled();});
