import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {UnloadingOriginCorrectionWorkspace,UnloadingOriginCorrectionDetails} from '@/components/financial/UnloadingOriginCorrectionDialog';
import {originCorrectionFixture,originCorrectionIds as ids} from './helpers/unloadingOriginCorrectionFixture';
const mocks=vi.hoisted(()=>({read:vi.fn(),send:vi.fn(),options:vi.fn()}));vi.mock('@/lib/financial/unloadingOriginCorrectionClient',async importOriginal=>({...await importOriginal<typeof import('@/lib/financial/unloadingOriginCorrectionClient')>(),readUnloadingOriginCorrectionContext:mocks.read,sendUnloadingOriginCorrection:mocks.send,unloadingOriginCorrectionErrorLabel:()=> 'Não confirmado'}));
vi.mock('@/lib/financial/ledgerClient',async importOriginal=>({...await importOriginal<typeof import('@/lib/financial/ledgerClient')>(),readExpenseOptions:mocks.options}));
afterEach(()=>{cleanup();localStorage.clear();vi.clearAllMocks();});
it('shows cancelled collection separately from unchanged cost, payable and cash',()=>{const data=originCorrectionFixture();render(<UnloadingOriginCorrectionDetails data={{...data,proposal:{operation:'cancel_origin',effective_on:'2026-09-11',collection_right_only:true},target:{...data.original,status:'cancelled',amount_cents:'0'}}}/>);expect(screen.getByText('Direito de cobrança cancelado')).toBeInTheDocument();expect(screen.getByText('Custo: preservado, sem correção por esta operação.')).toBeInTheDocument();expect(screen.getByText('Conta a pagar: preservada, sem cancelamento ou mudança de valor.')).toBeInTheDocument();expect(screen.queryByText('Confirmar correção da cobrança')).not.toBeInTheDocument();});
it('hides an earlier preview after editing and during a failed new consultation',async()=>{mocks.options.mockResolvedValue({rows:[{id:ids.supplier,label:'Fornecedor A · 12.345.678/0001-90'}],total:1});mocks.read.mockResolvedValueOnce(originCorrectionFixture()).mockRejectedValueOnce(Error('offline'));render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><UnloadingOriginCorrectionWorkspace tenant={ids.tenant} actor={ids.actor} chargeId={ids.charge}/></QueryClientProvider>);fireEvent.click(screen.getByText('Fornecedor devedor: Selecionar'));fireEvent.click(await screen.findByText('Fornecedor A · 12.345.678/0001-90'));expect(screen.queryByLabelText('ID do fornecedor devedor')).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Valor proposto (R$)'),{target:{value:'120,00'}});fireEvent.change(screen.getByLabelText('Data econômica da correção'),{target:{value:'2026-09-11'}});await act(async()=>fireEvent.click(screen.getByText('Conferir proposta de cobrança')));await screen.findByText('Revisar correção da cobrança');fireEvent.change(screen.getByLabelText('Valor proposto (R$)'),{target:{value:'100,00'}});expect(screen.queryByText('Revisar correção da cobrança')).not.toBeInTheDocument();expect(screen.queryByLabelText('Cobrança Vigente')).not.toBeInTheDocument();await act(async()=>fireEvent.click(screen.getByText('Conferir proposta de cobrança')));await screen.findByRole('alert');expect(screen.queryByText('Revisar correção da cobrança')).not.toBeInTheDocument();expect(mocks.send).not.toHaveBeenCalled();expect(mocks.read.mock.calls[1][0]).toMatchObject({proposal:{amount_cents:'10000'}});});

it('uses paginated catalogue identity and invalidates the preview when the supplier changes',async()=>{const other=crypto.randomUUID();mocks.options.mockImplementation(async(_tenant,_kind,_term,_trip,page)=>({rows:[{id:page===1?ids.supplier:other,label:page===1?'Fornecedor A · documento A':'Fornecedor B · documento B'}],total:31}));mocks.read.mockResolvedValue(originCorrectionFixture());render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><UnloadingOriginCorrectionWorkspace tenant={ids.tenant} actor={ids.actor} chargeId={ids.charge}/></QueryClientProvider>);fireEvent.click(screen.getByText('Fornecedor devedor: Selecionar'));fireEvent.click(await screen.findByText('Fornecedor A · documento A'));fireEvent.change(screen.getByLabelText('Valor proposto (R$)'),{target:{value:'120,00'}});fireEvent.change(screen.getByLabelText('Data econômica da correção'),{target:{value:'2026-09-11'}});await act(async()=>fireEvent.click(screen.getByText('Conferir proposta de cobrança')));await screen.findByText('Revisar correção da cobrança');fireEvent.click(screen.getByText('Fornecedor devedor: Fornecedor A · documento A'));await screen.findByText('Fornecedor A · documento A');await act(async()=>fireEvent.click(screen.getByText('Próxima')));fireEvent.click(await screen.findByText('Fornecedor B · documento B'));expect(mocks.options).toHaveBeenLastCalledWith(ids.tenant,'suppliers','',null,2);expect(screen.queryByText('Revisar correção da cobrança')).not.toBeInTheDocument();expect(screen.queryByLabelText('Cobrança Vigente')).not.toBeInTheDocument();await act(async()=>fireEvent.click(screen.getByText('Conferir proposta de cobrança')));expect(mocks.read).toHaveBeenLastCalledWith(expect.objectContaining({proposal:expect.objectContaining({supplier_id:other})}));expect(mocks.send).not.toHaveBeenCalled();});
