import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import {UnloadingProjectionRepairWorkspace} from '@/components/financial/UnloadingProjectionRepairDialog';
const send=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/unloadingProjectionRepairCommandClient',()=>({sendUnloadingProjectionRepair:send}));
const read=vi.hoisted(()=>vi.fn());vi.mock('@/lib/financial/unloadingProjectionRepairClient',()=>({readUnloadingProjectionRepairContext:read}));
const tenant=crypto.randomUUID(),actor=crypto.randomUUID(),charge=crypto.randomUUID(),supplier=crypto.randomUUID(),title=crypto.randomUUID();
function fixture(){return {tenant_id:tenant,actor_id:actor,charge_id:charge,receivable_id:title,revision:'a'.repeat(32),origin_verified:true,original:{supplier_id:supplier,supplier_name:'Fornecedor preservado',amount_cents:'15000',delivery_stop_id:crypto.randomUUID()},current:{client_id:actor,amount_cents:'10000',receivable_id:title,status:'pending'},target:{client_id:supplier,amount_cents:'15000'},eligible:true,can_repair:true,can_execute:false,blockers:[],dependencies:[{source_table:'finance_expense_items',source_id:crypto.randomUUID(),blocking:false,reason:'unchanged_canonical_cost'}],history:[],effects:{cash_changed:false,charge_changed:false,cost_changed:false}};}
function show(cache=new QueryClient()){render(<QueryClientProvider client={cache}><UnloadingProjectionRepairWorkspace tenant={tenant} actor={actor} chargeId={charge}/></QueryClientProvider>);return cache;}
afterEach(()=>{cleanup();read.mockReset();send.mockReset();localStorage.clear();});
it('compares the preserved origin/current/target and leaves execution unavailable',async()=>{read.mockResolvedValue(fixture());show();await screen.findByText('Origem preservada');expect(screen.getAllByText('R$ 150,00')).toHaveLength(2);expect(screen.getByText('R$ 100,00')).toBeInTheDocument();expect(screen.getByText(/Preservada, sem impedir esta reparação/)).toBeInTheDocument();expect(screen.getByText(/A confirmação de reparação está indisponível/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Confirmar|Executar/})).not.toBeInTheDocument();expect(read).toHaveBeenCalledWith({tenantId:tenant,actorId:actor,chargeId:charge});});
it('shows blocking evidence and permanent manual repair history separately',async()=>{const data=fixture();Object.assign(data,{eligible:false,blockers:[{code:'unloading_financial_history_requires_resolution',source_table:'receivables_payments',source_ids:[title]}],history:[{id:crypto.randomUUID(),request_id:crypto.randomUUID(),actor_id:actor,actor_name:'Ana',reason:'Restaurar título conforme origem',created_at:'2026-09-10',before:{client_id:actor,amount_cents:null},after:{client_id:supplier,amount_cents:'15000'}}]});data.dependencies.push({source_table:'receivables_payments',source_id:title,blocking:true,reason:'unloading_financial_history_requires_resolution'});read.mockResolvedValue(data);show();await screen.findAllByText(/Há histórico financeiro relacionado/);expect(screen.getByText(/Impede a reparação/)).toBeInTheDocument();expect(screen.getByText('Ajuste manual').parentElement?.parentElement).toHaveClass('border-amber-600');expect(screen.getByText(/Restaurar título conforme origem/)).toBeInTheDocument();expect(screen.getByText(/Antes:.*Indeterminado/)).toBeInTheDocument();});
it('hides prior eligibility and amounts during refetch and errors',async()=>{read.mockResolvedValue(fixture());const cache=show();await screen.findByText('Origem preservada');let reject!:(error:Error)=>void;read.mockImplementation(()=>new Promise((_resolve,fail)=>{reject=fail;}));await act(async()=>{void cache.invalidateQueries({queryKey:['finance-unloading-projection-repair',tenant,actor,charge]});});await screen.findByText('Consultando origem, título e dependências…');expect(screen.queryByText('Origem preservada')).not.toBeInTheDocument();await act(async()=>reject(Error('offline')));expect(await screen.findByRole('alert')).toHaveTextContent('Nenhuma elegibilidade anterior');expect(screen.queryByText('R$ 150,00')).not.toBeInTheDocument();});


it('preserves confirmed success when the actual query refetch fails',async()=>{
 Object.defineProperty(navigator,'locks',{configurable:true,value:{request:(_key:string,work:()=>Promise<unknown>)=>work()}});
 read.mockResolvedValueOnce({...fixture(),can_execute:true}).mockRejectedValue(Error('offline after confirmation'));
 send.mockImplementation(async command=>({error:null,data:{version:1,tenant_id:tenant,actor_id:actor,request_id:command.request_id,charge_id:charge,receivable_id:title,repair_id:crypto.randomUUID(),confirmed:true,cash_changed:false,charge_changed:false,cost_changed:false}}));
 show();await screen.findByLabelText('Motivo da reparação');
 fireEvent.change(screen.getByLabelText('Motivo da reparação'),{target:{value:'Restaurar conforme origem preservada'}});fireEvent.click(screen.getByText('Revisar reparação'));fireEvent.click(screen.getByRole('checkbox'));
 await act(async()=>fireEvent.click(screen.getByText('Confirmar reparação do título')));
 expect(await screen.findByText(/A reparação foi confirmada, mas a consulta não foi atualizada/)).toBeInTheDocument();expect(screen.getByText(/Reparação confirmada para a descarga/)).toBeInTheDocument();expect(screen.queryByText('Revisar reparação')).not.toBeInTheDocument();expect(screen.queryByText('Origem preservada')).not.toBeInTheDocument();expect(send).toHaveBeenCalledTimes(1);expect(read).toHaveBeenCalledTimes(2);expect(localStorage.length).toBe(0);
});
