import {afterEach,expect,it,vi} from 'vitest';
import {unloadingOriginCorrectionContextSchema,unloadingOriginProposalSchema,unloadingEffectiveOriginSchema} from '@/lib/financial/unloadingOriginCorrectionContract';
import {readUnloadingOriginCorrectionContext} from '@/lib/financial/unloadingOriginCorrectionClient';
import {originCorrectionFixture,originCorrectionIds as ids} from './helpers/unloadingOriginCorrectionFixture';
const rpc=vi.hoisted(()=>vi.fn());vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc}}));afterEach(()=>rpc.mockReset());
it('accepts cancellation only with no free supplier/amount and no monetary side effect',()=>{const v=originCorrectionFixture();const proposal={operation:'cancel_origin',effective_on:'2026-09-11',collection_right_only:true};expect(unloadingOriginProposalSchema.safeParse({...proposal,amount_cents:'0'}).success).toBe(false);expect(unloadingOriginCorrectionContextSchema.safeParse({...v,proposal,target:{...v.effective,status:'cancelled',amount_cents:'0'}}).success).toBe(true);expect(unloadingOriginCorrectionContextSchema.safeParse({...v,effects:{...v.effects,cost_changed:true}}).success).toBe(false);});
it('rejects mismatched target, negative amount and unsupported eligibility',()=>{const v=originCorrectionFixture();expect(unloadingOriginCorrectionContextSchema.safeParse({...v,target:{...v.target,amount_cents:'13000'}}).success).toBe(false);expect(unloadingOriginProposalSchema.safeParse({...v.proposal,amount_cents:'-100'}).success).toBe(false);expect(unloadingOriginCorrectionContextSchema.safeParse({...v,eligible:false,can_execute:true}).success).toBe(false);});
it('keeps an unverified current origin indeterminate instead of restoring the original',()=>{const v=originCorrectionFixture();const resolved={version:1,tenant_id:ids.tenant,charge_id:ids.charge,receivable_id:ids.receivable,verified:false,issue:'unloading_amendment_chain_invalid',original:v.original,effective:null,revision:v.origin_revision,history:[],last_effective_on:'2026-09-11'};expect(unloadingEffectiveOriginSchema.parse(resolved).effective).toBeNull();expect(unloadingEffectiveOriginSchema.safeParse({...resolved,effective:v.original}).success).toBe(false);});
it('checks tenant, actor, charge and exact proposal returned by preview',async()=>{const v=originCorrectionFixture();const input={tenantId:ids.tenant,actorId:ids.actor,chargeId:ids.charge,proposal:v.proposal};rpc.mockResolvedValue({data:v,error:null});await expect(readUnloadingOriginCorrectionContext(input)).resolves.toEqual(v);expect(rpc).toHaveBeenCalledWith('get_finance_unloading_origin_correction_context',{_tenant_id:ids.tenant,_charge_id:ids.charge,_proposal:v.proposal});for(const key of ['tenant_id','actor_id','charge_id']){rpc.mockResolvedValue({data:{...v,[key]:crypto.randomUUID()},error:null});await expect(readUnloadingOriginCorrectionContext(input)).rejects.toThrow();}rpc.mockResolvedValue({data:{...v,proposal:{...v.proposal,effective_on:'2026-09-10'}},error:null});await expect(readUnloadingOriginCorrectionContext(input)).rejects.toThrow();});

it('reports a missing public wrapper without returning a usable preview',async()=>{const v=originCorrectionFixture();rpc.mockResolvedValue({data:null,error:{code:'PGRST202',message:'function not found'}});await expect(readUnloadingOriginCorrectionContext({tenantId:ids.tenant,actorId:ids.actor,chargeId:ids.charge,proposal:v.proposal})).rejects.toThrow('ainda não está disponível');});
