// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {afterAll,afterEach,beforeAll,beforeEach,expect,it} from 'vitest';
import {createUploadQuarantineDatabase,quarantineMigration} from './helpers/uploadQuarantineDatabase';
import {financeAs,financeIds as i} from './helpers/financeLedgerDatabase';
let db:Awaited<ReturnType<typeof createUploadQuarantineDatabase>>;
beforeAll(async()=>{db=await createUploadQuarantineDatabase();},30000);
beforeEach(async()=>{await db.exec('begin');await db.query("select set_config('request.jwt.claim.sub',$1,true),set_config('request.jwt.claims',$2,true),set_config('request.headers',$3,true)",[i.operator,JSON.stringify({active_tenant_id:i.tenant,role:'authenticated'}),JSON.stringify({'x-agvlog-tenant-id':i.tenant})]);});
afterEach(async()=>db.exec('rollback'));afterAll(async()=>db.close());
async function service(sql:string,args:unknown[]=[]){await db.exec('savepoint service_call;set role service_role');try{const r=await db.query<{v:Record<string,unknown>}>(sql,args);await db.exec('reset role;release savepoint service_call');return r.rows[0].v;}catch(e){await db.exec('rollback to savepoint service_call');throw e;}}
async function reserve(format='ofx'){const p={version:2,tenant_id:i.tenant,request_id:randomUUID(),source_type:'bank_account',source_id:i.account,original_sha256:'a'.repeat(64),size_bytes:50,declared_mime:'application/octet-stream',format};const r=(await financeAs<{v:{artifact_id:string,usable:boolean}}>(db,i.operator,'select reserve_finance_upload_artifact($1) v',[p])).rows[0].v;const prep=await service('select prepare_finance_upload_artifact($1,$2,$3,$4,$5) v',[r.artifact_id,i.tenant,i.operator,p.original_sha256,p.size_bytes]);return {p,r,prep};}
async function upload(s:Awaited<ReturnType<typeof reserve>>){await db.query("insert into storage.objects(bucket_id,name,metadata,user_metadata) values('upload-quarantine',$1,$2,$3)",[s.prep.original_path,{size:50,mimetype:'application/octet-stream'},{version:2,artifact_id:s.r.artifact_id,sha256:s.p.original_sha256,size_bytes:50,kind:'quarantine_original'}]);const path=String(s.prep.derived_prefix)+'.json';await db.query("insert into storage.objects(bucket_id,name,metadata,user_metadata) values('upload-validated',$1,$2,$3)",[path,{size:80,mimetype:'application/json'},{version:2,artifact_id:s.r.artifact_id,sha256:'b'.repeat(64),original_sha256:s.p.original_sha256,size_bytes:80,kind:'validated_derivative'}]);return {version:2,artifact_id:s.r.artifact_id,ticket:s.prep.ticket,state:'validated_data',method:'native-ofx-v1',derivative:{bucket:'upload-validated',path,sha256:'b'.repeat(64),size_bytes:80,mime:'application/json',method:'native-ofx-v1',financial_mapping_required:false},issues:[]};}
it('installs without changing captured movement correction implementations or runtime readiness',async()=>{const before=(await db.query('select finance_private.movement_correction_runtime_state() v')).rows;await db.exec(quarantineMigration);await db.exec((await import('node:fs')).readFileSync('supabase/migrations/20260911041340_finance_quarantine_statement_artifact_bridge.sql','utf8'));expect((await db.query('select finance_private.movement_correction_runtime_state() v')).rows).toEqual(before);expect((await db.query('select snapshot=finance_private.movement_void_command_runtime_state() valid from finance_private.movement_void_command_baseline')).rows).toEqual([{valid:true}]);});
it('preserves original privately, releases only confirmed data derivative and replays exactly',async()=>{await db.exec(quarantineMigration);const s=await reserve();expect(s.r.usable).toBe(false);const payload=await upload(s);const result=await service('select finalize_finance_upload_artifact($1) v',[payload]);expect(result).toMatchObject({usable:true,state:'validated_data'});expect(JSON.stringify(result)).not.toContain('/original');expect(await service('select finalize_finance_upload_artifact($1) v',[payload])).toEqual(result);expect((await financeAs(db,i.operator,"select name from storage.objects where bucket_id='upload-quarantine'")).rows).toEqual([]);expect((await financeAs(db,i.operator,"select name from storage.objects where bucket_id='upload-validated'")).rows).toHaveLength(1);await db.exec('savepoint immutable');await expect(db.query("delete from storage.objects where bucket_id='upload-quarantine'")).rejects.toMatchObject({code:'55000'});await db.exec('rollback to savepoint immutable');await expect(service('select finalize_finance_upload_artifact($1) v',[{...payload,issues:['different']}])).rejects.toMatchObject({code:'23505'});});
it('rejects browser finalize, cross-company read, altered gate authorization and revoked actor',async()=>{await db.exec(quarantineMigration);const s=await reserve();await expect(financeAs(db,i.operator,'select finalize_finance_upload_artifact($1)',[{version:2}])).rejects.toMatchObject({code:'42501'});await expect(financeAs(db,i.operator,'select get_finance_upload_artifact($1,$2)',[i.otherTenant,s.r.artifact_id])).rejects.toMatchObject({code:'42501'});await db.query("update tenant_memberships set active=false where tenant_id=$1 and user_id=$2",[i.tenant,i.operator]);await expect(service('select prepare_finance_upload_artifact($1,$2,$3,$4,$5) v',[s.r.artifact_id,i.tenant,i.operator,s.p.original_sha256,50])).rejects.toMatchObject({code:'42501'});});
it('keeps PDF quarantined and refuses nonexistent or falsely declared derivatives',async()=>{await db.exec(quarantineMigration);const s=await reserve('pdf');await upload(s);const p={version:2,artifact_id:s.r.artifact_id,ticket:s.prep.ticket,state:'quarantined',method:null,derivative:null,issues:['format_requires_sanitization']};expect(await service('select finalize_finance_upload_artifact($1) v',[p])).toMatchObject({usable:false,state:'quarantined'});});
it('invalidates tickets on gate drift and expiry, and requires authenticated renewal',async()=>{await db.exec(quarantineMigration);const s=await reserve();const prepare=()=>service('select prepare_finance_upload_artifact($1,$2,$3,$4,$5) v',[s.r.artifact_id,i.tenant,i.operator,s.p.original_sha256,50]);
 await db.exec('savepoint gate');await db.exec("comment on function finance_private.can_access(uuid) is 'comment does not change authority'");await expect(prepare()).resolves.toBeDefined();
 await db.exec('revoke execute on function finance_private.can_access(uuid) from authenticated');await expect(prepare()).rejects.toMatchObject({code:'42501'});await db.exec('rollback to savepoint gate');
 await db.query("update secure_upload_private.artifacts set authorization_expires_at=clock_timestamp()-interval '1 second' where id=$1",[s.r.artifact_id]);await expect(prepare()).rejects.toMatchObject({code:'42501'});
 await financeAs(db,i.operator,'select reserve_finance_upload_artifact($1)',[s.p]);await expect(prepare()).resolves.toBeDefined();
 await expect(financeAs(db,i.operator,'select reserve_finance_upload_artifact($1)',[{...s.p,original_sha256:'c'.repeat(64)}])).rejects.toMatchObject({code:'23505'});
});
it('denies a mixed actor, unknown source and extra alleged scanner claims',async()=>{await db.exec(quarantineMigration);const s=await reserve();await db.query("insert into tenant_memberships values($1,$2,'driver',true)",[i.tenant,i.operator]);await expect(service('select prepare_finance_upload_artifact($1,$2,$3,$4,$5) v',[s.r.artifact_id,i.tenant,i.operator,s.p.original_sha256,50])).rejects.toMatchObject({code:'42501'});await db.query("delete from tenant_memberships where tenant_id=$1 and user_id=$2 and role='driver'",[i.tenant,i.operator]);
 await expect(financeAs(db,i.operator,'select reserve_finance_upload_artifact($1)',[{...s.p,request_id:randomUUID(),source_id:randomUUID()}])).rejects.toMatchObject({code:'42501'});
 const p=await upload(s);await expect(service('select finalize_finance_upload_artifact($1) v',[{...p,scanned:true}])).rejects.toMatchObject({code:'22023'});await expect(service('select finalize_finance_upload_artifact($1) v',[{...p,derivative:{...p.derivative,path:String(s.prep.original_path)}}])).rejects.toMatchObject({code:'23514'});
 expect((await financeAs(db,i.operator,'select get_finance_upload_artifact($1,$2) v',[i.tenant,s.r.artifact_id])).rows[0]).toMatchObject({v:{usable:false,state:'quarantined'}});
});
it('retains failed validation evidence and permits a renewed authenticated retry',async()=>{await db.exec(quarantineMigration);const s=await reserve();const p=await upload(s);await service('select finalize_finance_upload_artifact($1) v',[{version:2,artifact_id:s.r.artifact_id,ticket:s.prep.ticket,state:'validation_failed',method:null,derivative:null,issues:['cpu_budget']}]);
 await financeAs(db,i.operator,'select reserve_finance_upload_artifact($1)',[s.p]);const next=await service('select prepare_finance_upload_artifact($1,$2,$3,$4,$5) v',[s.r.artifact_id,i.tenant,i.operator,s.p.original_sha256,50]);expect(next.ticket).not.toBe(s.prep.ticket);await expect(service('select finalize_finance_upload_artifact($1) v',[p])).rejects.toMatchObject({code:'42501'});
 expect(await service('select finalize_finance_upload_artifact($1) v',[{...p,ticket:next.ticket}])).toMatchObject({usable:true});expect((await db.query("select count(*)::int n from secure_upload_private.events where artifact_id=$1 and action='validation_recorded'",[s.r.artifact_id])).rows).toEqual([{n:2}]);
});
it('blocks original access even with an unrelated permissive policy and rejects overwrite',async()=>{await db.exec(quarantineMigration);const s=await reserve();await upload(s);await db.exec('create policy qa_unrelated_broad_read on storage.objects for select to authenticated using(true)');expect((await financeAs(db,i.operator,"select name from storage.objects where bucket_id='upload-quarantine'")).rows).toEqual([]);
 await db.exec('savepoint overwrite');await expect(db.query("update storage.objects set metadata='{}' where bucket_id='upload-quarantine'")).rejects.toMatchObject({code:'55000'});await db.exec('rollback to savepoint overwrite');
 expect((await db.query("select has_table_privilege('service_role','secure_upload_private.artifacts','INSERT') direct,has_function_privilege('anon','public.reserve_finance_upload_artifact(jsonb)','EXECUTE') anon")).rows).toEqual([{direct:false,anon:false}]);
});
it('imports a validated artifact without creating an original download and verifies through a renewed operator authorization',async()=>{
 await db.exec(quarantineMigration);
 await db.exec((await import('node:fs')).readFileSync('supabase/migrations/20260911041340_finance_quarantine_statement_artifact_bridge.sql','utf8'));
 const before=(await db.query('select finance_private.movement_correction_runtime_state() v')).rows;
 const s=await reserve();const finalized=await upload(s);await service('select finalize_finance_upload_artifact($1) v',[finalized]);
 const payload={version:2,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,artifact_id:s.r.artifact_id,file_hash:s.p.original_sha256,source_path:finalized.derivative.path,currency:'BRL',parser_version:'native-ofx-v1',mapping:{},rows:[{amount_cents:1000,posted_on:'2026-08-15',description:'Entrada conferida',bank_id:'TEST-ARTIFACT-1',raw:{}}],period_start:'2026-08-15',period_end:'2026-08-15',opening_cents:0,closing_cents:1000,reason:'Importação de derivado com identidade preservada',file_name:'original.ofx'};
 const receipt=(await financeAs<{v:{import_id:string}}>(db,i.operator,'select intake_finance_statement_artifact($1) v',[payload])).rows[0].v;
 const snapshot=(await financeAs<{v:{revision:string,import_data:{source_snapshot:{artifact:{artifact_id:string}}}}}>(db,i.operator,'select inspect_finance_statement_source($1,$2) v',[i.tenant,receipt.import_id])).rows[0].v;
 expect(snapshot.import_data.source_snapshot.artifact.artifact_id).toBe(s.r.artifact_id);expect(JSON.stringify(snapshot)).not.toContain('/original');
 const auth=(await financeAs<{v:{authorization_id:string}}>(db,i.operator,'select authorize_finance_statement_artifact_verification($1,$2) v',[i.tenant,receipt.import_id])).rows[0].v;
 const report={tenant_id:i.tenant,actor_id:i.operator,request_id:randomUUID(),import_id:receipt.import_id,reader_version:'statement-artifact-v2',source_revision:snapshot.revision,file_hash:s.p.original_sha256,outcome:'rows_match',report:{matched_rows:1,hash_verified:true,artifact_id:s.r.artifact_id,original_sha256:s.p.original_sha256,derivative_sha256:finalized.derivative.sha256,derivative_hash_verified:true,original_reopened:false,validation_method:'native-ofx-v1'}};
 expect(await service('select record_finance_statement_artifact_verification($1,$2) v',[report,auth.authorization_id])).toMatchObject({confirmed:true,source_verification:'rows_match'});
 const afterVerification=(await financeAs<{v:{revision:string}}>(db,i.operator,'select inspect_finance_statement_source($1,$2) v',[i.tenant,receipt.import_id])).rows[0].v;expect(afterVerification.revision).toBe(snapshot.revision);
 expect(await service('select record_finance_statement_artifact_verification($1,$2) v',[report,auth.authorization_id])).toMatchObject({confirmed:true});
 expect((await db.query('select count(*)::int n from finance_bank_entries')).rows).toEqual([{n:1}]);expect((await db.query('select count(*)::int n from finance_movements')).rows).toEqual([{n:0}]);
 expect((await db.query('select finance_private.movement_correction_runtime_state() v')).rows).toEqual(before);
 await expect(service('select record_finance_statement_artifact_verification($1,$2) v',[{...report,report:{...report.report,original_reopened:true}},auth.authorization_id])).rejects.toMatchObject({code:'23514'});
 await expect(financeAs(db,i.operator,'select intake_finance_statement_artifact($1)',[{...payload,request_id:randomUUID(),bank_account_id:i.otherAccount}])).rejects.toMatchObject({code:'22023'});
 const colleague=randomUUID();await db.query('insert into auth.users(id,email) values($1,$2)',[colleague,'colleague@example.test']);await db.query("insert into tenant_memberships values($1,$2,'operator',true)",[i.tenant,colleague]);
 const second=(await financeAs<{v:{authorization_id:string}}>(db,colleague,'select authorize_finance_statement_artifact_verification($1,$2) v',[i.tenant,receipt.import_id])).rows[0].v;
 expect(await service('select record_finance_statement_artifact_verification($1,$2) v',[{...report,request_id:randomUUID(),actor_id:colleague},second.authorization_id])).toMatchObject({confirmed:true});
 expect((await db.query('select actor_id from secure_upload_private.artifacts where id=$1',[s.r.artifact_id])).rows).toEqual([{actor_id:i.operator}]);

});
it('imports mapped CSV data with mapping still explicit and blocks a parser/source mismatch',async()=>{
 await db.exec(quarantineMigration);await db.exec((await import('node:fs')).readFileSync('supabase/migrations/20260911041340_finance_quarantine_statement_artifact_bridge.sql','utf8'));
 const s=await reserve('csv');const p=await upload(s);p.method='strict-csv-matrix-v1';p.derivative.method='strict-csv-matrix-v1';p.derivative.financial_mapping_required=true;
 await service('select finalize_finance_upload_artifact($1) v',[p]);
 const input={version:2,tenant_id:i.tenant,request_id:randomUUID(),bank_account_id:i.account,artifact_id:s.r.artifact_id,file_hash:s.p.original_sha256,source_path:p.derivative.path,currency:'BRL',parser_version:'mapped-csv-v1',mapping:{delimiter:';',date_column:0,amount_column:1},rows:[{amount_cents:-500,posted_on:'2026-08-15',description:'Despesa CSV',raw:{cells:['15/08/2026','-5,00']}}],period_start:'2026-08-15',period_end:'2026-08-15',reason:'Mapeamento CSV declarado para conferência',file_name:'original.csv'};
 await expect(financeAs(db,i.operator,'select intake_finance_statement_artifact($1)',[{...input,parser_version:'native-ofx-v1'}])).rejects.toMatchObject({code:'23514'});
 const out=(await financeAs<{v:{import_id:string}}>(db,i.operator,'select intake_finance_statement_artifact($1) v',[input])).rows[0].v;
 expect((await db.query('select parser_version,mapping from finance_statement_imports where id=$1',[out.import_id])).rows).toEqual([{parser_version:'mapped-csv-v1',mapping:input.mapping}]);
 expect((await db.query('select count(*)::int n from finance_statement_verifications')).rows).toEqual([{n:0}]);
});
