import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {readPeriodEvidence} from '@/lib/financial/periodEvidenceClient';
import {accountOpeningPendingSchema,type AccountOpeningPending} from '@/lib/financial/accountOpeningContract';
import {readAccountOpening,recordAccountOpening,reverseAccountOpening,AccountOpeningRejectedError} from '@/lib/financial/accountOpeningClient';
import {readOpeningAccount,recordCashOpening} from '@/lib/financial/cashOpeningClient';
import {totalCashCounts} from '@/lib/financial/cashOpeningContract';
import {CashOpeningForm,CashCountDetails} from './CashOpeningForm';
import {AccountOpeningEvidence} from './AccountOpeningEvidence';
type Props={tenant:string;actor:string;account:string;from:string;to:string};
const messages:Record<string,string>={finance_opening_anchor_required:'É necessário saldo OFX do fim do dia anterior, no fuso de Brasília.',finance_opening_evidence_changed:'As evidências mudaram. Atualize a consulta e revise a abertura novamente.',finance_account_opening_exists:'Já existe uma abertura para esta conta. Confira o histórico antes de continuar.',finance_account_opening_not_found:'A abertura não foi encontrada nesta conta.',finance_opening_already_reversed:'Esta abertura já foi desfeita. Confira o histórico.',finance_cash_opening_requires_count:'Caixa físico exige contagem própria. Este painel aceita somente abertura bancária por OFX.',finance_access_denied:'Acesso financeiro não confirmado.',finance_cash_account_required:'Selecione um caixa físico ativo. A contagem não pode abrir uma conta bancária.',finance_invalid_cash_counts:'Confira as denominações e informe quantidades inteiras, sem repetir linhas.',finance_cash_count_limit:'A contagem ultrapassa o limite permitido. Revise as quantidades.',finance_invalid_cash_opening_evidence:'A evidência da contagem precisa de revisão.',finance_invalid_period:'A data do saldo deve ser válida e não pode estar no futuro.',finance_request_conflict:'Este pedido já possui outro conteúdo. Confira o histórico e retome o pedido original.'};
const explain=(e:unknown)=>e instanceof Error?(messages[e.message]||'Não foi possível confirmar a operação. Confira o histórico e atualize a consulta.'):'Não foi possível confirmar a operação.';
export function AccountOpeningReview(props:Props){const [open,setOpen]=useState(false);return <section className="rounded border p-3 space-y-2" aria-label="Abertura auditada da conta"><h3 className="font-medium">Abertura auditada da conta</h3>{!open?<Button variant="outline" onClick={()=>setOpen(true)}>Consultar abertura da conta</Button>:<AccountOpeningWorkspace key={`${props.tenant}:${props.actor}:${props.account}:${props.from}:${props.to}`} {...props}/>}</section>;}
export function AccountOpeningWorkspace({tenant,actor,account,from,to}:Props){
 const key=`finance-account-opening:${tenant}:${actor}:${account}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=accountOpeningPendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.account!==account||pending.command.tenant_id!==tenant||(pending.kind!=='reverse'&&pending.command.account_id!==account))throw new Error();return {pending};}catch{return {error:'Não foi possível recuperar o pedido de abertura. Novos envios estão bloqueados; verifique o histórico.'};}});
 const [pending,setPending]=useState<AccountOpeningPending|undefined>(restored.pending),[reason,setReason]=useState(''),[reverseId,setReverseId]=useState(''),[review,setReview]=useState(false);
 const [reviewRevision,setReviewRevision]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState('');
 const live=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const context=useQuery({queryKey:['finance-account-opening',tenant,actor,account,from,to],queryFn:()=>readAccountOpening(tenant,account,from,to),retry:false});
 const accountQuery=useQuery({queryKey:['finance-opening-account',tenant,actor,account],queryFn:()=>readOpeningAccount(tenant,account),retry:false});
 const selectedAccount=accountQuery.error||accountQuery.isFetching?undefined:accountQuery.data,isCash=selectedAccount?.account_type==='cash',isBank=!!selectedAccount&&!isCash;
 const evidence=useQuery({queryKey:['finance-period-evidence',tenant,actor,account,from,to],queryFn:()=>readPeriodEvidence(tenant,account,from,to),enabled:isBank,retry:false});
 const data=context.error||context.isFetching?undefined:context.data,source=evidence.error||evidence.isFetching?undefined:evidence.data;
 const previousDay=new Date(`${from}T12:00:00Z`);previousDay.setUTCDate(previousDay.getUTCDate()-1);const day=Number.isNaN(previousDay.getTime())?'':previousDay.toISOString().slice(0,10);
 const anchors=source?.anchors.filter(a=>a.day===day)||[];
 const eligible=isBank&&!!data&&!data.opening&&source?.opening_balance_cents!==null&&source?.opening_balance_cents!==undefined&&anchors.length>0&&anchors.every(anchor=>anchor.offset_minutes===-180);
 const cashEligible=isCash&&!!selectedAccount?.active&&!!data&&!data.opening;
 const reversing=!!data?.history.some(item=>item.id===reverseId&&!item.reversal);
 function refresh(){setReview(false);void context.refetch();void accountQuery.refetch();if(isBank)void evidence.refetch();}
 async function submit(candidate?:AccountOpeningPending){
  if(sending.current||restored.error)return;let original=pending;
  if(!original){if(candidate?.kind==='cash'){if(!cashEligible)return;original=accountOpeningPendingSchema.parse(candidate);}else{if(!review||(!reverseId&&reviewRevision!==source?.revision)||reason.trim().length<10||(!reverseId&&!eligible)||(reverseId&&!reversing))return;
   const parsed=accountOpeningPendingSchema.safeParse(reverseId?{kind:'reverse',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),opening_id:reverseId,reason}}:{kind:'record',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),account_id:account,from,to,revision:source!.revision,reason}});if(!parsed.success)return;original=parsed.data;
   }
   try{sessionStorage.setItem(key,JSON.stringify({actor,account,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma abertura ou correção foi enviada.');return;}setPending(original);
  }
  sending.current=true;setBusy(true);setError('');
  try{if(original.kind==='record')await recordAccountOpening(original.command);else if(original.kind==='cash'){const result=await recordCashOpening(original.command);if(live.current)setNotice(`Contagem confirmada pelo servidor: ${formatFinanceCents(result.balance_cents)}. Nenhum movimento de dinheiro foi criado.`);}else await reverseAccountOpening(original.command);sessionStorage.removeItem(key);
   for(const prefix of ['finance-account-opening','finance-account-period','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});
   if(live.current){setPending(undefined);setReview(false);setReason('');setReverseId('');if(original.kind!=='cash')setNotice(original.kind==='record'?'Abertura registrada com autoria e evidências. Nenhum movimento de dinheiro foi criado.':'Abertura desfeita com histórico preservado. Nenhum dinheiro foi movimentado.');}
  }catch(e){if(e instanceof AccountOpeningRejectedError&&!pending){try{sessionStorage.removeItem(key);if(live.current){setPending(undefined);setReview(false);setError(explain(e));}void context.refetch();if(isBank)void evidence.refetch();}catch{if(live.current)setError('Pedido recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}
   else if(live.current)setError(`${explain(e)} O pedido original foi preservado para retomada.`);
  }finally{sending.current=false;if(live.current)setBusy(false);}
 }
 return <div className="space-y-3 text-sm"><p>O saldo é baseado na abertura e nos movimentos registrados desde o corte. Não confirma saldo real nem fecha o período; registros antigos e conciliação continuam necessários.</p>
 <Button variant="outline" disabled={busy||context.isFetching||evidence.isFetching||accountQuery.isFetching} onClick={refresh}>Atualizar abertura e evidências</Button>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{(context.isFetching||evidence.isFetching||accountQuery.isFetching)&&<p role="status">Consultando abertura e suas evidências…</p>}{(context.isError||(isBank&&evidence.isError)||accountQuery.isError)&&<p role="alert">Não foi possível consultar a abertura ou suas evidências. Atualize antes de iniciar outro registro.</p>}
 {data?.opening&&<div className="rounded border p-2"><p>Abertura vigente desde {data.opening.effective_from}: {formatFinanceCents(data.opening.balance_cents)}</p><p>Por {data.opening.actor_name} ({data.opening.actor_id}) · {data.opening.created_at}</p>{data.opening.evidence_status==='requires_review'&&<p role="alert">A evidência da abertura mudou ou não pode mais ser confirmada. Abertura preservada para revisão.</p>}</div>}
 {data?.book&&<dl className="grid grid-cols-2 gap-2">{[['Saldo inicial dos registros',data.book.opening_cents],['Entradas registradas',data.book.in_cents],['Saídas registradas',data.book.out_cents],['Saldo final dos registros',data.book.closing_cents]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{formatFinanceCents(value)}</dd></div>)}</dl>}
 {data?.opening&&!data.book&&<p>O período começa antes do corte da abertura. Não há saldo calculado para este intervalo.</p>}
 {isCash&&!selectedAccount?.active&&<p role="alert">O caixa está inativo. Não é possível registrar outra abertura.</p>}
 {pending?.kind==='cash'&&<div><p>Contagem original no início de {pending.command.effective_from} · responsável {pending.command.custodian_name}</p><CashCountDetails counts={pending.command.counts}/><p>Total preservado: {formatFinanceCents(totalCashCounts(pending.command.counts))}</p></div>}
 {!pending&&cashEligible&&!reverseId&&<CashOpeningForm tenant={tenant} account={account} from={from} disabled={busy||!!restored.error} onConfirm={command=>void submit({kind:'cash',command})}/>}
 {data&&<section aria-label="Histórico de aberturas"><h4>Histórico permanente de intervenções manuais</h4>{data.history.length===0?<p>Nenhuma abertura registrada.</p>:data.history.map(item=><article className="rounded border border-amber-600 p-2 my-2" key={item.id}><p>Abertura manual · {item.reversal?'Desfeita':'Ativa'} · {item.effective_from} · {formatFinanceCents(item.balance_cents)}</p><p>Por {item.actor_name} ({item.actor_id}) · {item.created_at}</p><p>Motivo: {item.reason}</p><AccountOpeningEvidence type={item.evidence_type} evidence={item.evidence}/>{item.reversal?<><p>Desfeita por {item.reversal.actor_name} ({item.reversal.actor_id}) · {item.reversal.created_at}</p><p>Motivo da correção: {item.reversal.reason}</p></>:<Button variant="outline" disabled={busy||!!pending||!!restored.error} onClick={()=>{setReverseId(item.id);setReview(false);setReason('');}}>Corrigir esta abertura</Button>}</article>)}</section>}
 {pending?<><p>Pedido original de {pending.kind==='reverse'?'correção':'abertura'}: {pending.command.request_id}</p>{pending.kind==='record'&&<p>Período original: {pending.command.from} a {pending.command.to}</p>}<p>Motivo preservado: {pending.command.reason}</p><Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar pedido de abertura</Button></>:<>
 {!reverseId&&isBank&&source&&<><p>Âncora anterior a {from}: {source.opening_balance_cents===null?'Não disponível':formatFinanceCents(source.opening_balance_cents)}</p>{anchors.map(anchor=><p key={anchor.verification_id}>Saldo de {anchor.day} · {anchor.file_name} · {anchor.offset_minutes===-180?'fuso Brasília (UTC−03:00)':`fuso incompatível (${anchor.offset_minutes} minutos)`} · {formatFinanceCents(anchor.cents)}</p>)}{!eligible&&!data?.opening&&<p>Sem âncora elegível de abertura no fim do dia anterior. Importe e confira o OFX antes de registrar.</p>}</>}
 {(eligible||reversing)&&<><p>{reverseId?'Corrigir abertura '+reverseId:`Abertura efetiva em ${from}, derivada do saldo OFX acima. O valor não é digitado.`}</p><label>Motivo da abertura ou correção<Textarea maxLength={2000} disabled={review} value={reason} onChange={e=>setReason(e.target.value)}/></label>{review?<><p>Confirme a {reverseId?'correção da abertura selecionada':'abertura por esta âncora'}. O dinheiro não será movimentado.</p><Button disabled={busy||!!restored.error||(!reverseId&&reviewRevision!==source?.revision)} onClick={()=>void submit()}>Confirmar abertura ou correção</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(false)}>Voltar à revisão</Button></>:<Button disabled={reason.trim().length<10||!!restored.error} onClick={()=>{setReviewRevision(source?.revision||'');setReview(true);}}>Revisar abertura ou correção</Button>}{reverseId&&<Button variant="outline" disabled={busy} onClick={()=>{setReverseId('');setReview(false);}}>Cancelar correção</Button>}</>}
 </>}
 </div>;
}
