import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {accountPeriodBlockerLabels,type AccountPeriodClosePreview} from '@/lib/financial/accountPeriodCloseContract';
export function AccountPeriodClosePreview({data}:{data:AccountPeriodClosePreview}){
 const value=(cents:string|null)=>cents===null?'Não determinado':formatFinanceCents(cents);
 return <section className="space-y-3" aria-label="Resultado da conferência para fechamento"><h3 className="font-semibold">Conta {data.account_id} · {data.from} a {data.to}</h3><p>Dias civis de São Paulo · BRL. Extrato e movimento interno representam o mesmo dinheiro e não são somados entre si.</p><table className="w-full text-left"><thead><tr><th>Representação</th><th>Entradas</th><th>Saídas</th></tr></thead><tbody><tr><th>Banco</th><td>{value(data.balances.bank_in_cents)}</td><td>{value(data.balances.bank_out_cents)}</td></tr><tr><th>Movimentos registrados</th><td>{value(data.balances.recorded_in_cents)}</td><td>{value(data.balances.recorded_out_cents)}</td></tr></tbody></table><p>Saldo inicial verificado: {value(data.balances.opening_cents)} · saldo final verificado: {value(data.balances.closing_cents)}</p><p>Abertura: {data.opening_id||'Sem abertura identificada'} · fechamento predecessor: {data.predecessor_id||'Primeiro período'}</p>
 {data.blockers.length?<><h4 className="font-medium">Bloqueios para o fechamento bancário</h4><ul className="list-disc pl-5" role="alert">{data.blockers.map((blocker,index)=><li key={`${blocker.code}:${index}`}>{accountPeriodBlockerLabels[blocker.code]||'A conferência identificou uma pendência que exige revisão.'}{!accountPeriodBlockerLabels[blocker.code]&&<span> Referência: {blocker.code}.</span>}{(blocker.source_table||blocker.source_ids.length>0)&&<details><summary>Origens do bloqueio</summary><p>Fonte: {blocker.source_table||'Não especificada'} · abrangência: conta</p>{blocker.source_ids.map(id=><p key={id}>{id}</p>)}</details>}</li>)}</ul></>:<p>A conferência atual não identificou bloqueios bancários. O fechamento ainda exige revisão e confirmação autorizada.</p>}
 <p>Comprovantes pendentes, gastos ainda sem detalhamento e títulos em aberto não são automaticamente diferenças bancárias. Fechar o banco não declara todos os gastos integralmente conferidos.</p><p>A aprovação humana da cobertura não atesta autenticidade bancária.</p>{!data.can_execute&&<p role="alert">Consulta disponível. Fechar e reabrir exigem administrador autorizado da empresa.</p>}
 </section>;
}
