import {CashPeriodEvidenceSummary} from './CashPeriodEvidenceSummary';
import {AccountPeriodEvidenceIndexPanel} from './AccountPeriodEvidenceIndexPanel';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {z} from 'zod';
import {Button} from '@/components/ui/button';
import {readAccountPeriodEvidence} from '@/lib/financial/accountPeriodEvidenceClient';
import {exportAccountPeriodEvidence} from '@/lib/financial/accountPeriodEvidenceContract';
import {formatFinanceCents,movementNatures} from '@/lib/financial/ledgerContract';
type Props={tenant:string;actor:string;account:string;closure:string};
const money=z.union([z.string().regex(/^-?\d+$/),z.number().int().safe()]).transform(String);
const presentation=z.object({balances:z.object({opening_cents:money.nullable(),closing_cents:money.nullable(),bank_in_cents:money,bank_out_cents:money,recorded_in_cents:money,recorded_out_cents:money}),facts:z.object({movements:z.array(z.object({id:z.string(),nature:z.string(),direction:z.string(),description:z.string(),occurred_on:z.string(),amount_cents:money}))})});
export function AccountPeriodEvidencePanel(props:Props){const [open,setOpen]=useState(false);return <section className="border-t pt-2 space-y-3"><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Ocultar evidências do fechamento':'Evidências do fechamento'}</Button>{open&&<AccountPeriodEvidenceWorkspace key={`${props.tenant}:${props.actor}:${props.account}:${props.closure}`} {...props}/>}</section>;}
export function AccountPeriodEvidenceWorkspace({tenant,actor,account,closure}:Props){const [page,setPage]=useState(1),[dependencyPage,setDependencyPage]=useState(1),[error,setError]=useState('');const query=useQuery({queryKey:['finance-account-period-evidence',tenant,actor,account,closure],queryFn:()=>readAccountPeriodEvidence(tenant,account,closure),retry:false}),data=query.isFetching||query.isError?undefined:query.data;const parsed=data?presentation.safeParse(data.snapshot):null,summary=parsed?.success?parsed.data:null;const value=(cents:string|null)=>cents===null?'Não determinado':formatFinanceCents(cents);
 function download(){if(!data)return;let url:string|undefined;try{const json=exportAccountPeriodEvidence(data);url=URL.createObjectURL(new Blob([json],{type:'application/json;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`fechamento-${closure}.json`;anchor.click();setError('');}catch{setError('Não foi possível preparar a exportação. Tente novamente.');}finally{if(url)URL.revokeObjectURL(url);}}
 return <div className="space-y-3 text-sm"><h4 className="font-semibold">Evidências do fechamento</h4><p>Registros preservados na decisão, com autoria e verificações de integridade. Não atestam autenticidade bancária. A exportação contém esses registros; não baixa os arquivos originais.</p><Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>Atualizar evidências preservadas</Button>{query.isFetching&&<p role="status">Consultando evidências do fechamento…</p>}{query.isError&&<p role="alert">Não foi possível consultar as evidências. Nenhuma integridade foi presumida.</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{data.closure.from} a {data.closure.to} · fechamento {data.closure_id}</p><p>Decisão manual por {data.closure.actor_name} ({data.closure.actor_id}) · {data.closure.created_at}</p><p>Motivo: {data.closure.reason}</p><p>Integridade do registro preservado: {data.integrity.snapshot_matches_revision?'corresponde à revisão':'divergência identificada'} · vínculos das evidências: {data.integrity.dependencies_match?'correspondem ao fechamento':'divergência identificada'}</p>{(!data.integrity.snapshot_matches_revision||!data.integrity.dependencies_match)&&<p role="alert">Há divergência na integridade das evidências preservadas. Encaminhe esta conferência para revisão antes de confiar no registro.</p>}{data.reopening&&<p>Reaberto por {data.reopening.actor_name} ({data.reopening.actor_id}) · {data.reopening.created_at} · motivo: {data.reopening.reason}. Evidências originais preservadas.</p>}
 {data.snapshot.evidence_type==='cash_count_v1'?<CashPeriodEvidenceSummary snapshot={data.snapshot}/>:summary?<><table className="w-full text-left"><thead><tr><th>Valores preservados</th><th>Entradas</th><th>Saídas</th></tr></thead><tbody><tr><th>Banco</th><td>{value(summary.balances.bank_in_cents)}</td><td>{value(summary.balances.bank_out_cents)}</td></tr><tr><th>Movimentos registrados</th><td>{value(summary.balances.recorded_in_cents)}</td><td>{value(summary.balances.recorded_out_cents)}</td></tr></tbody></table><p>Saldo inicial: {value(summary.balances.opening_cents)} · final: {value(summary.balances.closing_cents)}</p><h5 className="font-medium">Natureza dos movimentos preservados</h5>{summary.facts.movements.slice((page-1)*30,page*30).map(movement=><article className="border rounded p-2" key={movement.id}><p>{movement.description} · {movement.occurred_on} · {movement.direction==='in'?'Entrada':movement.direction==='out'?'Saída':'Sentido a revisar'} · {value(movement.amount_cents)}</p><p>{movementNatures[movement.nature as keyof typeof movementNatures]||movement.nature} · movimento {movement.id}</p></article>)}{!summary.facts.movements.length&&<p>Nenhum movimento no registro preservado.</p>}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Movimentos preservados anteriores</Button><span>Página {page}</span><Button variant="outline" disabled={page*30>=summary.facts.movements.length} onClick={()=>setPage(page+1)}>Próximos movimentos preservados</Button></div></>:<p>O detalhamento resumido desta versão não está disponível. Os registros integrais permanecem na exportação.</p>}
 <AccountPeriodEvidenceIndexPanel data={data}/><details><summary>Identificação das evidências vinculadas ({data.dependencies.length})</summary>{data.dependencies.slice((dependencyPage-1)*30,dependencyPage*30).map((dependency,index)=><DependencySummary key={index} dependency={dependency}/>)}<div className="flex gap-2"><Button variant="outline" disabled={dependencyPage===1} onClick={()=>setDependencyPage(dependencyPage-1)}>Evidências vinculadas anteriores</Button><span>Página {dependencyPage}</span><Button variant="outline" disabled={dependencyPage*30>=data.dependencies.length} onClick={()=>setDependencyPage(dependencyPage+1)}>Próximas evidências vinculadas</Button></div></details><p>Revisão preservada: {data.closure.revision}</p><Button onClick={download}>Exportar evidências do fechamento em JSON</Button></>}</div>;
}


const dependencyLabels:Record<string,string>={finance_movement_voids:'Invalidação auditada de movimento',finance_cash_period_counts:'Contagem de caixa',finance_cash_period_count_reversals:'Reversão de contagem de caixa',finance_statement_imports:'Extrato importado',finance_statement_rows:'Linha do extrato',finance_bank_entries:'Transação bancária',finance_movements:'Movimento registrado',finance_account_openings:'Abertura da conta',finance_account_period_closures:'Fechamento anterior',finance_statement_verifications:'Verificação do extrato',finance_statement_identity_reviews:'Revisão de identidade da transação',finance_statement_review_reversals:'Reversão da revisão de identidade',finance_reconciliation_groups:'Conciliação bancária',finance_reconciliation_reversals:'Reversão de conciliação',finance_statement_coverage_approvals:'Aprovação da cobertura',finance_legacy_cut_reviews:'Revisão do corte histórico',finance_internal_transfers:'Transferência entre contas',finance_transfer_departures:'Saída de transferência em trânsito'};
function DependencySummary({dependency}:{dependency:Record<string,unknown>}){const kind=typeof dependency.source_kind==='string'?dependency.source_kind:'',id=typeof dependency.source_id==='string'?dependency.source_id:'Não identificada',from=typeof dependency.affected_from==='string'?dependency.affected_from:null,to=typeof dependency.affected_to==='string'?dependency.affected_to:null,revision=typeof dependency.source_revision==='string'?dependency.source_revision:null;return <article className="border rounded p-2 my-2"><p className="font-medium">{dependencyLabels[kind]||'Origem registrada'}</p><p>Identificação: {id}</p><p>Período afetado: {from||'Não informado'} a {to||'Não informado'}</p><details><summary>Detalhes de rastreio</summary>{!dependencyLabels[kind]&&<p>Tipo registrado: {kind||'Não informado'}</p>}<p>Revisão preservada: {revision||'Não informada'}</p></details></article>;}
