import {AccountPeriodCloseHistory} from './AccountPeriodCloseHistory';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {AccountPeriodClosePreview} from './AccountPeriodClosePreview';
import {LegacyCutReview} from './LegacyCutReview';
import {accountPeriodPendingSchema,accountPeriodCloseErrorLabels,type AccountPeriodPending} from '@/lib/financial/accountPeriodCloseContract';
import {readAccountPeriodHistory,readAccountPeriodClosePreview,submitAccountPeriodDecision,AccountPeriodCloseRejectedError} from '@/lib/financial/accountPeriodCloseClient';
type Props={tenant:string;actor:string;account:string;from:string;to:string};
export function AccountPeriodClosePanel(props:Props){const [open,setOpen]=useState(false);return <section aria-label="Fechamento bancário auditado" className="border rounded p-3 space-y-3"><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Ocultar fechamento bancário':'Conferir fechamento e histórico bancário'}</Button>{open&&<FinanceAccessBoundary><AccountPeriodCloseWorkspace key={`${props.tenant}:${props.actor}:${props.account}:${props.from}:${props.to}`} {...props}/></FinanceAccessBoundary>}</section>;}
export function AccountPeriodCloseWorkspace({tenant,actor,account,from,to}:Props){
 const key=`finance-account-period-decision:${tenant}:${actor}:${account}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=accountPeriodPendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.account!==account||pending.command.tenant_id!==tenant||(pending.kind==='close'&&pending.command.account_id!==account))throw new Error();return {pending};}catch{return {error:'O pedido de fechamento não pôde ser recuperado. Novas decisões estão bloqueadas; confira o histórico.'};}});
 const [pending,setPending]=useState<AccountPeriodPending|undefined>(restored.pending),[review,setReview]=useState<AccountPeriodPending>(),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState(''),[offset,setOffset]=useState(0),[reopenId,setReopenId]=useState<string|null>(null);const live=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const query=useQuery({queryKey:['finance-account-period-close-preview',tenant,actor,account,from,to],queryFn:()=>readAccountPeriodClosePreview(tenant,account,from,to),retry:false}),data=query.isError||query.isFetching?undefined:query.data;
 const historyQuery=useQuery({queryKey:['finance-account-period-close-history',tenant,actor,account,offset],queryFn:()=>readAccountPeriodHistory(tenant,account,offset),retry:false}),history=historyQuery.isFetching||historyQuery.isError?undefined:historyQuery.data,selected=history?.items.find(item=>item.id===reopenId),mayReopen=!!selected?.can_reopen&&!!history?.can_execute;
 const mayClose=!!data?.eligible&&data.can_execute,reviewCurrent=!!review&&checked&&(review.kind==='close'?mayClose&&review.command.revision===data?.revision:mayReopen&&review.command.closure_id===selected?.id&&review.command.revision===selected.revision);
 function prepare(){if((reopenId?!mayReopen:!mayClose)||!checked||restored.error)return;const parsed=accountPeriodPendingSchema.safeParse(reopenId?{kind:'reopen',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),closure_id:selected!.id,revision:selected!.revision,reason}}:{kind:'close',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),account_id:account,from,to,revision:data!.revision,reason}});if(parsed.success)setReview(parsed.data);}
 async function submit(){const original=pending||review;if(!original||sending.current||restored.error||(!pending&&!reviewCurrent))return;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,account,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhum fechamento ou reabertura foi enviado.');return;}setPending(original);}sending.current=true;setBusy(true);setError('');try{const result=await submitAccountPeriodDecision(original);if(result.account_id!==account)throw new Error('Resposta fora da conta.');sessionStorage.removeItem(key);for(const prefix of ['finance-account-period-close-preview','finance-account-period-close-history','finance-account-period-evidence','finance-account-period','finance-audit','finance-account-opening','finance-statement-coverage-review','finance-legacy-cut-review'])void cache.invalidateQueries({queryKey:[prefix]});if(live.current){setPending(undefined);setReview(undefined);setChecked(false);setReason('');setReopenId(null);setNotice(original.kind==='close'?`Fechamento confirmado: ${result.closure_id}. Registro do fechamento preservado; nenhum dinheiro foi alterado.`:`Reabertura confirmada para ${result.closure_id}. O fechamento original permanece no histórico e nenhum dinheiro foi alterado.`);}}catch(cause){if(cause instanceof AccountPeriodCloseRejectedError&&!pending){try{sessionStorage.removeItem(key);if(live.current){setPending(undefined);setReview(undefined);setError(accountPeriodCloseErrorLabels[cause.message]||'A decisão foi recusada. Atualize os bloqueios, a permissão e as dependências do período.');}void query.refetch();void historyQuery.refetch();}catch{if(live.current)setError('Pedido recusado, mas sua recuperação local precisa ser conferida.');}}else if(live.current)setError('Resposta não confirmada. O pedido original foi preservado para retomada.');}finally{sending.current=false;if(live.current)setBusy(false);}}
 return <div className="space-y-4 text-sm"><h2 className="font-semibold">Fechamento e histórico bancário</h2><p>Confira conta, período e saldos antes de fechar. O registro preserva os responsáveis e os motivos. Para corrigir dinheiro ou evidências de um período fechado, revise sua reabertura. Este controle não executa transferências, pagamentos ou baixas de títulos.</p><Button variant="outline" disabled={busy||query.isFetching||historyQuery.isFetching} onClick={()=>{setReview(undefined);void query.refetch();void historyQuery.refetch();}}>Atualizar conferência do fechamento</Button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Conferindo elegibilidade do período…</p>}{query.isError&&<p role="alert">Não foi possível consultar a elegibilidade. Nenhum saldo ou fechamento foi presumido.</p>}{data&&<AccountPeriodClosePreview data={data}/>}
 {pending?<><p>Pedido original: {pending.command.request_id} · {pending.kind==='close'?`fechamento de ${pending.command.from} a ${pending.command.to}`:`reabertura do fechamento ${pending.command.closure_id}`} · motivo: {pending.command.reason}.</p><Button disabled={busy||!!restored.error||(pending.kind==='close'?data?.can_execute===false:history?.can_execute===false)} onClick={()=>void submit()}>Retomar decisão bancária original</Button></>:(reopenId?mayReopen:mayClose)&&<><label className="flex gap-2"><input type="checkbox" checked={checked} disabled={!!review} onChange={event=>setChecked(event.target.checked)}/>{reopenId?"Conferi o fechamento selecionado e quero reabri-lo, preservando o histórico e sem alterar dinheiro.":"Conferi o período, os saldos e as origens e quero fechar esta conta no intervalo indicado."}</label><label>Motivo da decisão bancária<Textarea maxLength={2000} disabled={!!review} value={reason} onChange={event=>setReason(event.target.value)}/></label>{review?<><p>Revisão final: {review.kind==="close"?`fechar conta ${account}, de ${review.command.from} a ${review.command.to}`:`reabrir fechamento ${review.command.closure_id}, de ${selected?.from} a ${selected?.to}`}. Não há movimentação de dinheiro.</p>{!reviewCurrent&&<p role="alert">A conferência mudou. Volte e revise novamente.</p>}<Button disabled={busy||!reviewCurrent||!!restored.error} onClick={()=>void submit()}>{review.kind==="close"?"Confirmar fechamento bancário":"Confirmar reabertura bancária"}</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão bancária</Button></>:<Button disabled={!checked||reason.trim().length<10||!!restored.error} onClick={prepare}>{reopenId?"Revisar decisão de reabertura":"Revisar fechamento bancário"}</Button>}{reopenId&&<Button variant="outline" disabled={busy} onClick={()=>{setReopenId(null);setReview(undefined);setChecked(false);setReason("");}}>Cancelar reabertura</Button>}</>}
 {historyQuery.isFetching&&<p role="status">Consultando histórico de fechamentos…</p>}{historyQuery.isError&&<p role="alert">Não foi possível consultar o histórico. Isso não significa que a conta não possui fechamentos.</p>}{history&&<AccountPeriodCloseHistory actor={actor} data={history} disabled={busy||!!pending||!!review} onReopen={id=>{setReopenId(id);setReview(undefined);setChecked(false);setReason("");}} onPage={next=>{setOffset(next);setReopenId(null);setReview(undefined);setChecked(false);}}/>} <LegacyCutReview tenant={tenant} actor={actor} account={account} from={from} to={to}/>
 </div>;
}
