import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {buildAccountPeriodEvidenceIndex} from '@/lib/financial/accountPeriodEvidenceIndex';
import type {AccountPeriodEvidence} from '@/lib/financial/accountPeriodEvidenceContract';
function Pager({name,page,total,onPage}:{name:string;page:number;total:number;onPage:(page:number)=>void}){return <div className="flex gap-2 items-center"><Button variant="outline" disabled={page===1} onClick={()=>onPage(page-1)}>{name}: anteriores</Button><span>Página {page} · até 30 registros</span><Button variant="outline" disabled={page*30>=total} onClick={()=>onPage(page+1)}>{name}: próximos</Button></div>;}
export function AccountPeriodEvidenceIndexPanel({data}:{data:AccountPeriodEvidence}){const index=useMemo(()=>buildAccountPeriodEvidenceIndex(data),[data]),[documentPage,setDocumentPage]=useState(1),[decisionPage,setDecisionPage]=useState(1),[missingPage,setMissingPage]=useState(1),[issuePage,setIssuePage]=useState(1);return <section className="space-y-4 border-t pt-3" aria-label="Documentos e intervenções preservados"><h4 className="font-semibold">Documentos e intervenções preservados</h4><p>Comprovantes de movimentos, extratos e decisões preservados neste fechamento. Documentos de despesas e folha estão fora deste índice.</p>
 <section aria-label="Referências de documentos preservados" className="space-y-2"><h5 className="font-medium">Documentos identificados: {index.documents.length}</h5>{!index.documents.length&&<p>Nenhum documento identificado neste registro.</p>}{index.documents.slice((documentPage-1)*30,documentPage*30).map(document=><article key={`${document.kind}:${document.source_id}`} className="border rounded p-2"><p className="font-medium">{document.kind==='bank_statement'?'Extrato bancário':document.kind==='voided_movement_receipt'?'Comprovante do original invalidado — fora dos valores ativos':'Comprovante de movimento'}</p><p>Origem: {document.source_id}</p><p className="break-all">Localização preservada: {document.path}</p><DocumentMetadata evidence={document.evidence}/></article>)}<Pager name="Documentos preservados" page={documentPage} total={index.documents.length} onPage={setDocumentPage}/></section>
 <section aria-label="Intervenções manuais preservadas" className="space-y-2"><h5 className="font-medium">Intervenções manuais: {index.manual_decisions.length}</h5>{!index.manual_decisions.length&&<p>Nenhuma intervenção manual neste registro.</p>}{index.manual_decisions.slice((decisionPage-1)*30,decisionPage*30).map(decision=><article key={`${decision.kind}:${decision.id}`} className="border border-amber-600 rounded p-2"><p className="font-medium">{decision.kind==='movement_void'?'Invalidação manual de movimento':decision.kind==='cash_count'?'Contagem manual de caixa':decision.kind==='reconciliation'?'Conciliação manual':'Reversão manual de conciliação'} · {decision.kind==='movement_void'?'Original excluído dos valores ativos':decision.kind==='reversal'?'Reversão preservada':decision.active===true?'Ativa no fechamento':decision.active===false?'Desfeita no fechamento':'Situação exige revisão'}</p><p>Por {decision.actor_name} ({decision.actor_id}) · {decision.created_at}</p><p>Motivo: {decision.reason}</p><p>Identificação: {decision.id}</p>{decision.movement_id&&<p>Movimento original: {decision.movement_id}</p>}{decision.duplicate_of_movement_id&&<p>Duplicidade do movimento: {decision.duplicate_of_movement_id}</p>}{decision.replacement_movement_id&&<p>Registro substituto: {decision.replacement_movement_id}</p>}</article>)}<Pager name="Intervenções preservadas" page={decisionPage} total={index.manual_decisions.length} onPage={setDecisionPage}/></section>
 <section aria-label="Comprovantes não identificados" className="space-y-2"><h5 className="font-medium">Movimentos sem comprovante vinculado no fechamento: {index.missing_movement_receipt_ids.length}</h5>{index.missing_movement_receipt_ids.slice((missingPage-1)*30,missingPage*30).map(id=><p key={id}>Movimento: {id}</p>)}<Pager name="Comprovantes pendentes" page={missingPage} total={index.missing_movement_receipt_ids.length} onPage={setMissingPage}/></section>
 {index.coverage_issues.length>0&&<section aria-label="Limites do índice preservado" className="space-y-2"><h5 className="font-medium">Pendências de informação preservada: {index.coverage_issues.length}</h5><ul className="list-disc pl-5">{index.coverage_issues.slice((issuePage-1)*30,issuePage*30).map(issue=><li key={issue}>{issue}</li>)}</ul><Pager name="Pendências do índice" page={issuePage} total={index.coverage_issues.length} onPage={setIssuePage}/></section>}
 </section>;}
function DocumentMetadata({evidence}:{evidence:unknown}){const metadata=typeof evidence==='object'&&evidence!==null&&!Array.isArray(evidence)?evidence as Record<string,unknown>:null;return <details><summary>Metadados preservados</summary>{metadata?<>{typeof metadata.file_name==='string'&&<p>Arquivo: {metadata.file_name}</p>}{typeof metadata.file_hash==='string'&&<p className="break-all">Identificador de integridade: {metadata.file_hash}</p>}{typeof metadata.parser_version==='string'&&<p>Versão da leitura: {metadata.parser_version}</p>}<p>Metadados integrais estão no registro exportado do fechamento.</p></>:<p>Sem metadados identificados neste registro.</p>}</details>;}
