import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {cashDenominations,totalCashCounts} from '@/lib/financial/cashOpeningContract';
import {cashPeriodCountCommandSchema,type CashPeriodCountCommand} from '@/lib/financial/cashPeriodContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {CashCountDetails} from './CashOpeningForm';
export function CashPeriodCountForm({tenant,account,end,disabled,onConfirm,initial}:{tenant:string;account:string;end:string;disabled:boolean;onConfirm:(command:CashPeriodCountCommand)=>void;initial?:CashPeriodCountCommand}){const [custodian,setCustodian]=useState(initial?.custodian_name||''),[reason,setReason]=useState(initial?.reason||''),[quantities,setQuantities]=useState<Record<number,string>>(()=>Object.fromEntries((initial?.counts||[]).map(row=>[row.denomination_cents,String(row.quantity)]))),[review,setReview]=useState<CashPeriodCountCommand>();const rows=cashDenominations.map(denomination_cents=>({denomination_cents,quantity:/^\d{1,9}$/.test(quantities[denomination_cents]||'0')?Number(quantities[denomination_cents]||0):-1})),total=rows.every(row=>row.quantity>=0)?totalCashCounts(rows):null,parsed=cashPeriodCountCommandSchema.safeParse({version:1,tenant_id:tenant,request_id:'00000000-0000-4000-8000-000000000001',account_id:account,period_end:end,counted_at_boundary:'end_of_day',counts:rows,custodian_name:custodian,reason});return <section className="border rounded p-3 space-y-3" aria-label="Contagem do caixa no fim do período"><h3 className="font-semibold">Contagem física ao fim de {end}</h3><p>Declare o dinheiro contado ao encerramento desse dia, depois dos movimentos. O sistema registra também quando e por quem esta declaração foi inserida. Campos de quantidade vazios representam zero.</p>{review?<><p>Revisão da contagem: fim de {review.period_end} · responsável pela guarda: {review.custodian_name}</p><CashCountDetails counts={review.counts}/><p className="font-semibold">Total declarado: {formatFinanceCents(totalCashCounts(review.counts))}</p><p>Motivo: {review.reason}</p><Button disabled={disabled} onClick={()=>onConfirm(review)}>Confirmar registro da contagem final</Button><Button variant="outline" disabled={disabled} onClick={()=>setReview(undefined)}>Voltar à contagem final</Button></>:<><label>Responsável pela guarda do caixa<Input disabled={disabled} maxLength={200} value={custodian} onChange={event=>setCustodian(event.target.value)}/></label><fieldset disabled={disabled} className="grid grid-cols-2 gap-2"><legend>Cédulas e moedas contadas</legend>{cashDenominations.map(value=><label key={value}>{formatFinanceCents(value)}<Input aria-label={`Quantidade final de ${formatFinanceCents(value)}`} inputMode="numeric" value={quantities[value]||''} placeholder="0" onChange={event=>setQuantities({...quantities,[value]:event.target.value})}/></label>)}</fieldset><p>Total da contagem: {total===null?'Quantidade inválida':formatFinanceCents(total)}</p><label>Motivo da contagem final<Textarea disabled={disabled} maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></label><Button disabled={disabled||!parsed.success} onClick={()=>{if(parsed.success)setReview({...parsed.data,request_id:crypto.randomUUID()});}}>Revisar contagem final</Button></>}</section>;}
