import {totalCashCounts} from '@/lib/financial/cashOpeningContract';
import {CashCountDetails} from './CashOpeningForm';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {CashPeriodCountForm} from './CashPeriodCountForm';
import {CashPeriodCountsHistory} from './CashPeriodCountsHistory';
import {CashPeriodPreviewDetails} from './CashPeriodPreviewDetails';
import {AccountPeriodCloseHistory} from './AccountPeriodCloseHistory';
import {LegacyCutReview} from './LegacyCutReview';
import {cashPeriodPendingSchema,cashPeriodIssueLabels,type CashPeriodPending,type CashPeriodCountCommand} from '@/lib/financial/cashPeriodContract';
import {readCashPeriodCounts,readCashPeriodPreview,submitCashPeriodDecision,CashPeriodRejectedError} from '@/lib/financial/cashPeriodClient';
import {readAccountPeriodHistory,AccountPeriodCloseRejectedError} from '@/lib/financial/accountPeriodCloseClient';
import {accountPeriodCloseErrorLabels} from '@/lib/financial/accountPeriodCloseContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
type Props={tenant:string;actor:string;account:string;from:string;to:string};
export function CashPeriodClosePanel(props:Props){const [open,setOpen]=useState(false);return <section className="border rounded p-3"><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Ocultar conferência do caixa':'Contagem e fechamento do caixa físico'}</Button>{open&&<FinanceAccessBoundary><CashPeriodCloseWorkspace key={`${props.tenant}:${props.actor}:${props.account}:${props.from}:${props.to}`} {...props}/></FinanceAccessBoundary>}</section>;}
export function CashPeriodCloseWorkspace({tenant,actor,account,from,to}:Props){
 const key=`finance-cash-period-decision:${tenant}:${actor}:${account}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=cashPeriodPendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.account!==account||pending.command.tenant_id!==tenant||(('account_id' in pending.command)&&pending.command.account_id!==account))throw new Error();return {pending};}catch{return {error:'Não foi possível recuperar a decisão do caixa. Novos envios estão bloqueados; confira o histórico.'};}});
 const [retryCount,setRetryCount]=useState<CashPeriodCountCommand>();
 const [pending,setPending]=useState<CashPeriodPending|undefined>(restored.pending),[review,setReview]=useState<CashPeriodPending>(),[selected,setSelected]=useState(''),[countPage,setCountPage]=useState(1),[offset,setOffset]=useState(0),[mode,setMode]=useState<{kind:'reverse_count'|'reopen';id:string}>(),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState('');
 const alive=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const countsQuery=useQuery({queryKey:['finance-cash-period-counts',tenant,actor,account,to,countPage],queryFn:()=>readCashPeriodCounts(tenant,account,to,countPage),retry:false}),historyQuery=useQuery({queryKey:['finance-account-period-close-history',tenant,actor,account,offset],queryFn:()=>readAccountPeriodHistory(tenant,account,offset),retry:false}),previewQuery=useQuery({queryKey:['finance-cash-period-close-preview',tenant,actor,account,from,to,selected],queryFn:()=>readCashPeriodPreview(tenant,account,from,to,selected),enabled:!!selected&&!pending,retry:false});
 const counts=countsQuery.isError||countsQuery.isFetching?undefined:countsQuery.data,history=historyQuery.isError||historyQuery.isFetching?undefined:historyQuery.data,preview=selected&&!previewQuery.isError&&!previewQuery.isFetching?previewQuery.data:undefined;
 const reversing=counts?.rows.find(row=>row.id===mode?.id),reopening=history?.items.find(row=>row.id===mode?.id),mayClose=!!preview?.eligible&&preview.can_execute,mayReverse=!!counts?.can_reverse&&!!reversing?.can_reverse,mayReopen=!!history?.can_execute&&!!reopening?.can_reopen,mayDecide=mode?.kind==='reverse_count'?mayReverse:mode?.kind==='reopen'?mayReopen:mayClose;
 const reviewCurrent=!!review&&checked&&(review.kind==='close'?mayClose&&review.command.count_id===selected&&review.command.revision===preview?.revision:review.kind==='reverse_count'?mayReverse&&review.command.count_id===reversing?.id&&review.command.revision===reversing?.revision:review.kind==='reopen'?mayReopen&&review.command.closure_id===reopening?.id&&review.command.revision===reopening?.revision:false);
 const locked=busy||!!pending||!!restored.error;
 function refresh(){for(const prefix of ['finance-cash-period-counts','finance-cash-period-close-preview','finance-account-period-close-preview','finance-account-period-close-history','finance-account-period-evidence','finance-account-opening','finance-legacy-cut-review','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});}
 function prepare(){if(locked||!mayDecide||!checked)return;const base={version:1,tenant_id:tenant,request_id:crypto.randomUUID(),reason};const parsed=cashPeriodPendingSchema.safeParse(mode?.kind==='reverse_count'?{kind:'reverse_count',command:{...base,count_id:reversing!.id,revision:reversing!.revision}}:mode?.kind==='reopen'?{kind:'reopen',command:{...base,closure_id:reopening!.id,revision:reopening!.revision}}:{kind:'close',command:{...base,account_id:account,from,to,count_id:selected,revision:preview!.revision}});if(parsed.success)setReview(parsed.data);}
 async function submit(incoming?:CashPeriodPending){if(sending.current||restored.error)return;const original=pending||incoming||review;if(!original)return;if(!pending){if(original.kind==='record_count'){if(!counts?.can_record||original.command.account_id!==account||original.command.period_end!==to)return;}else if(!reviewCurrent)return;try{sessionStorage.setItem(key,JSON.stringify({actor,account,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma decisão foi enviada.');return;}setPending(original);}sending.current=true;setBusy(true);setError('');try{const result=await submitCashPeriodDecision(original);if(result.account_id!==account)throw new Error('Resposta fora do caixa.');sessionStorage.removeItem(key);refresh();if(alive.current){setRetryCount(undefined);setPending(undefined);setReview(undefined);setMode(undefined);setReason('');setChecked(false);setSelected('');setNotice(original.kind==='record_count'&&'counted_cents' in result?`Contagem registrada pelo servidor: ${formatFinanceCents(result.counted_cents)}. O dinheiro não foi alterado.`:original.kind==='close'?'Caixa fechado. O registro da conferência foi preservado.':original.kind==='reopen'?'Período reaberto; o fechamento original permanece no histórico.':'Contagem desfeita; sua declaração original permanece no histórico.');}}catch(e){if((e instanceof CashPeriodRejectedError||e instanceof AccountPeriodCloseRejectedError)&&!pending){try{sessionStorage.removeItem(key);if(alive.current){if(original.kind===`record_count`)setRetryCount(original.command);setPending(undefined);setReview(undefined);setChecked(false);setError(cashPeriodIssueLabels[e.message]||accountPeriodCloseErrorLabels[e.message]||'A decisão foi recusada. Atualize a conta, a contagem e o período antes de revisar novamente.');}refresh();}catch{if(alive.current)setError('O pedido foi recusado, mas o registro local precisa ser conferido no histórico.');}}else if(alive.current)setError('Não foi possível confirmar a resposta. A decisão original foi preservada para retomada.');}finally{sending.current=false;if(alive.current)setBusy(false);}}
 return <div className="space-y-4 pt-3"><h2 className="font-semibold">Contagem, fechamento e histórico do caixa</h2><p>Conta {account} · {from} a {to}. A contagem divergente pode ser registrada, mas não permite fechar o período. Diferenças não geram ajustes automáticos.</p><Button variant="outline" disabled={busy} onClick={()=>{setReview(undefined);setChecked(false);refresh();}}>Atualizar conferência do caixa</Button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{countsQuery.isFetching&&<p role="status">Consultando contagens…</p>}{countsQuery.isError&&<p role="alert">Não foi possível consultar as contagens. Atualize antes de registrar ou corrigir.</p>}{counts&&<><CashPeriodCountsHistory data={counts} selected={selected} disabled={locked||!!review} onSelect={id=>{setSelected(id);setReview(undefined);setMode(undefined);setChecked(false);}} onReverse={id=>{setMode({kind:'reverse_count',id});setReview(undefined);setChecked(false);setReason('');}} onPage={setCountPage}/>{!counts.can_record&&!counts.active_count_id&&<p>Nova contagem indisponível para este período. Confira se a conta está ativa, o dia terminou e o período permite registro.</p>}{counts.can_record&&!pending&&!mode&&<CashPeriodCountForm tenant={tenant} account={account} end={to} initial={retryCount} disabled={locked||!!review} onConfirm={command=>void submit({kind:'record_count',command})}/>}</>}
 {!selected&&<p>Escolha explicitamente uma contagem ativa para conferir o encerramento.</p>}{selected&&previewQuery.isFetching&&<p role="status">Conferindo saldo esperado e contagem…</p>}{selected&&previewQuery.isError&&<p role="alert">Não foi possível conferir o saldo. Não há autorização de fechamento nesta resposta.</p>}{preview&&<CashPeriodPreviewDetails data={preview}/>}
 {pending?<><p>Pedido original: {pending.command.request_id} · motivo: {pending.command.reason}</p>{pending.kind==='record_count'&&<><p>Contagem original para o fim de {pending.command.period_end} · responsável: {pending.command.custodian_name}</p><CashCountDetails counts={pending.command.counts}/><p>Total original: {formatFinanceCents(totalCashCounts(pending.command.counts))}</p></>}{pending.kind==='close'&&<p>Período original: {pending.command.from} a {pending.command.to} · contagem {pending.command.count_id}</p>}{pending.kind==='reverse_count'&&<p>Contagem original a corrigir: {pending.command.count_id}</p>}{pending.kind==='reopen'&&<p>Fechamento original a reabrir: {pending.command.closure_id}</p>}<Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar decisão original do caixa</Button></>:(mayDecide||!!review)&&<section className="space-y-2 border rounded p-3"><label className="flex gap-2"><input type="checkbox" disabled={!!review||locked} checked={checked} onChange={event=>setChecked(event.target.checked)}/>{mode?.kind==='reverse_count'?'Conferi a contagem que será desfeita; o dinheiro e a declaração original serão preservados.':mode?.kind==='reopen'?'Conferi o período que será reaberto para correção, preservando o fechamento original.':'Conferi a conta, o período, a contagem escolhida e os saldos para fechamento.'}</label><label>Motivo da decisão sobre o caixa<Textarea maxLength={2000} disabled={!!review||locked} value={reason} onChange={event=>setReason(event.target.value)}/></label>{review?<><p>Revisão final: {review.kind==='close'?`fechar ${from} a ${to} com a contagem ${selected}`:review.kind==='reverse_count'?`desfazer a contagem ${review.command.count_id}`:`reabrir o fechamento ${review.kind==='reopen'?review.command.closure_id:''}`}.</p>{!reviewCurrent&&<p role="alert">A conferência mudou. Volte e revise novamente.</p>}<Button disabled={locked||!reviewCurrent} onClick={()=>void submit()}>Confirmar decisão sobre o caixa</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão do caixa</Button></>:<Button disabled={locked||!checked||reason.trim().length<10||!mayDecide} onClick={prepare}>Revisar decisão sobre o caixa</Button>}{mode&&<Button variant="outline" disabled={busy} onClick={()=>{setMode(undefined);setReview(undefined);setChecked(false);}}>Cancelar correção do caixa</Button>}</section>}
 <LegacyCutReview tenant={tenant} actor={actor} account={account} from={from} to={to}/>{historyQuery.isFetching&&<p role="status">Consultando histórico de fechamentos…</p>}{historyQuery.isError&&<p role="alert">Não foi possível consultar o histórico de fechamentos.</p>}{history&&<AccountPeriodCloseHistory data={history} actor={actor} disabled={locked||!!review} onReopen={id=>{setMode({kind:'reopen',id});setReview(undefined);setChecked(false);setReason('');}} onPage={setOffset}/>}</div>;
}
