import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {CashForecastAgendaHistory} from './CashForecastAgendaHistory';
import {CashForecastAgendaConfirmation} from './CashForecastAgendaConfirmation';
import {readCashForecastAgenda} from '@/lib/financial/cashForecastAgendaClient';
import {forecastMoney} from '@/lib/financial/cashForecastViewLabels';
type Props={tenant:string;actor:string;economicKey:string;cutoff:string;end:string;label?:string};
export function CashForecastAgendaDialog(props:Props&{open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Revisar data esperada</DialogTitle><DialogDescription>A agenda registra uma expectativa financeira, sem alterar o vencimento da origem.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><CashForecastAgendaWorkspace key={`${props.tenant}:${props.actor}:${props.economicKey}:${props.cutoff}:${props.end}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
export function CashForecastAgendaWorkspace({tenant,actor,economicKey,cutoff,end,label}:Props){const cache=useQueryClient();const query=useQuery({queryKey:['finance-cash-forecast-agenda',tenant,actor,economicKey,cutoff,end],queryFn:()=>readCashForecastAgenda(tenant,actor,cutoff,end,economicKey),retry:false,staleTime:0,refetchOnMount:'always'});const data=!query.isFetching&&!query.isError&&query.isFetchedAfterMount?query.data:undefined;const refresh=()=>Promise.all([...['finance-cash-forecast-agenda','finance-cash-forecast-preview'].map(k=>cache.invalidateQueries({queryKey:[k,tenant]},{throwOnError:true})),cache.invalidateQueries({queryKey:['finance-cash-forecast-sources',tenant],predicate:q=>q.queryKey[3]===null},{throwOnError:true})]);return <section aria-label="Conferência da agenda" className="space-y-3"><p>{label||'Origem financeira'} · referência {economicKey}</p><Button disabled={query.isFetching} onClick={()=>void query.refetch()}>Atualizar agenda</Button>{query.isFetching&&<p role="status">Conferindo origem e agenda…</p>}{query.isError&&<p role="alert">A agenda está indisponível. Nenhuma revisão anterior permite confirmar.</p>}{data&&<><p>Nominal {forecastMoney(data.origin.nominal_cents)} · realizado {forecastMoney(data.origin.fulfilled_cents)} · crédito vinculado {forecastMoney(data.origin.reserved_credit_cents)}</p><p>Vencimento na origem: {(data.origin.original_expected_on===undefined?data.origin.expected_date_source==='due_date'?data.origin.expected_on:null:data.origin.original_expected_on)||'Não informado'} · expectativa atual: {data.origin.expected_on||'Indeterminada'}.</p><CashForecastAgendaHistory origin={data.origin}/>{!data.eligible&&<p role="alert">A origem não é elegível: confira sua validade e o saldo ainda não realizado.</p>}</>}<CashForecastAgendaConfirmation tenant={tenant} actor={actor} economicKey={economicKey} preview={data} refresh={refresh}/></section>;}
