import {CashForecastAgendaDialog} from './CashForecastAgendaDialog';
import {defaultForecastDates} from '@/lib/financial/cashForecastViewLabels';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {CashForecastSummary} from './CashForecastSummary';
import {CashForecastSources} from './CashForecastSources';
import {CashForecastPreserve} from './CashForecastPreserve';
import {CashForecastHistory} from './CashForecastHistory';
import {readCashForecastPreview,readCashForecastSnapshot} from '@/lib/financial/cashForecastViewClient';
type Props={tenant:string;actor:string;onSelectSnapshot?:(snapshotId:string|null)=>void};
export function CashForecastPanel(props:Props){return <FinanceAccessBoundary><CashForecastWorkspace key={`${props.tenant}:${props.actor}`} {...props}/></FinanceAccessBoundary>;}
export function CashForecastWorkspace({tenant,actor,onSelectSnapshot}:Props){const [agenda,setAgenda]=useState<{key:string;label:string;cutoff:string;end:string}|null>(null);const initial=defaultForecastDates();const [cutoff,setCutoff]=useState(initial.cutoff),[end,setEnd]=useState(initial.end),[request,setRequest]=useState<{cutoff:string;end:string;epoch:number}|null>(null),[snapshot,setSnapshot]=useState<string|null>(null),[notice,setNotice]=useState('');const callback=useRef(onSelectSnapshot);callback.current=onSelectSnapshot;const cache=useQueryClient();useEffect(()=>{callback.current?.(null);return()=>callback.current?.(null);},[tenant,actor]);const query=useQuery({queryKey:['finance-cash-forecast-preview',tenant,actor,request],queryFn:()=>readCashForecastPreview(tenant,actor,request!.cutoff,request!.end),enabled:!!request&&!snapshot,retry:false,staleTime:0});const stored=useQuery({queryKey:['finance-cash-forecast-snapshot',tenant,actor,snapshot],queryFn:()=>readCashForecastSnapshot(tenant,actor,snapshot!),enabled:!!snapshot,retry:false,staleTime:0,refetchOnMount:'always'});const original=snapshot&&!stored.isFetching&&!stored.isError?stored.data:undefined;const current=!snapshot&&request&&!query.isFetching&&!query.isError?query.data:undefined;const shown=original?.summary??current;useEffect(()=>{callback.current?.(original?.snapshot_id??null);},[original?.snapshot_id]);const clear=()=>{setAgenda(null);setSnapshot(null);callback.current?.(null);setRequest(null);setNotice('');};const select=(id:string)=>{callback.current?.(null);setSnapshot(id);setNotice('');};const changed=useCallback(()=>{setRequest(null);setNotice('As fontes mudaram. Confira novamente a previsão antes de usar seus valores.');callback.current?.(null);},[]);async function confirmed(id:string){select(id);await cache.invalidateQueries({queryKey:['finance-cash-forecast-history',tenant,actor]},{throwOnError:true});}
return <section aria-label="Previsão de caixa" className="space-y-4"><h2>Previsão de caixa</h2><p>Compare expectativas de entrada e saída com o saldo-base de todas as contas da empresa. Esta consulta não é DRE nem confirmação bancária.</p><div className="flex flex-wrap gap-3"><label>Data do saldo-base<input type="date" value={cutoff} onChange={e=>{clear();setCutoff(e.target.value);}}/></label><label>Prever até<input type="date" value={end} onChange={e=>{clear();setEnd(e.target.value);}}/></label><Button disabled={!cutoff||!end||cutoff>=end||query.isFetching} onClick={()=>{setSnapshot(null);callback.current?.(null);setNotice('');setRequest(r=>({cutoff,end,epoch:(r?.epoch??0)+1}));}}>Conferir previsão atual</Button></div>{notice&&<p role="alert">{notice}</p>}{(query.isFetching&&!snapshot||stored.isFetching&&snapshot)&&<p role="status">Conferindo fontes e valores…</p>}{(snapshot?stored.isError:query.isError)&&<p role="alert">A previsão está indisponível. Nenhum valor anterior será apresentado como atual.</p>}{original&&<section aria-label="Previsão original"><h3>{original.title}</h3><p>Preservada por {original.actor_name} · {original.actor_id} · {original.created_at}</p><p>Motivo: {original.reason}</p><p>Captura {original.snapshot_id} · pedido {original.request_id}. Os valores abaixo pertencem à evidência original.</p><Button onClick={clear}>Fechar previsão original</Button></section>}{shown&&<><CashForecastSummary data={shown}/><CashForecastSources key={`${tenant}:${actor}:${snapshot??'current'}:${shown.revision}`} tenant={tenant} actor={actor} summary={shown} snapshotId={snapshot} onChanged={changed} onAgenda={(key,label)=>setAgenda({key,label,cutoff:shown.cutoff,end:shown.period_end})}/></>}<CashForecastPreserve key={`${tenant}:${actor}`} tenant={tenant} actor={actor} preview={current||undefined} onConfirmed={confirmed}/>{agenda&&<CashForecastAgendaDialog tenant={tenant} actor={actor} economicKey={agenda.key} label={agenda.label} cutoff={agenda.cutoff} end={agenda.end} open onOpenChange={open=>{if(!open)setAgenda(null);}}/>}<CashForecastHistory tenant={tenant} actor={actor} onSelect={select}/></section>;}
