import {CashForecastAgendaHistory} from './CashForecastAgendaHistory';
import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {CashForecastChangedError,readCashForecastSources} from '@/lib/financial/cashForecastViewClient';
import type {CashForecastSources as Page,CashForecastSummary} from '@/lib/financial/cashForecastViewContract';
import {forecastMoney,forecastIssue} from '@/lib/financial/cashForecastViewLabels';
const labels={origins:'Títulos e fretes',movements:'Movimentos registrados',credits:'Créditos de clientes',issues:'Pendências'};
export function CashForecastSources({tenant,actor,summary,snapshotId,onChanged,onAgenda}:{tenant:string;actor:string;summary:CashForecastSummary;snapshotId:string|null;onChanged:()=>void;onAgenda?:(key:string,label:string)=>void}){const [kind,setKind]=useState<Page['kind']>('origins'),[page,setPage]=useState(1);const query=useQuery({queryKey:['finance-cash-forecast-sources',tenant,actor,snapshotId,summary.revision,kind,page],queryFn:()=>readCashForecastSources(tenant,actor,summary.cutoff,summary.period_end,snapshotId,kind,page,summary.revision),retry:false});useEffect(()=>{if(query.error instanceof CashForecastChangedError)onChanged();},[query.error,onChanged]);const data=!query.isFetching&&!query.isError?query.data:undefined;return <section aria-label="Fontes da previsão" className="space-y-2"><h3>Fontes {snapshotId?'originais preservadas':'da consulta atual'}</h3><label>Tipo de fonte<select value={kind} onChange={e=>{setKind(e.target.value as Page['kind']);setPage(1);}}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{query.isFetching&&<p role="status">Carregando fontes…</p>}{query.isError&&<p role="alert">As fontes estão indisponíveis ou mudaram. Atualize a consulta; a página anterior não será reutilizada.</p>}{data&&<><p>{data.total} fontes · página {page} de {Math.max(1,Math.ceil(data.total/30))}</p><CashForecastSourceRows data={data} onAgenda={snapshotId?undefined:onAgenda}/>{snapshotId&&<p>Nomes e descrições identificam as fontes conforme o cadastro atual. Valores, datas econômicas e revisões acima pertencem à captura original.</p>}<Button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Página anterior de fontes</Button><Button disabled={page*30>=data.total} onClick={()=>setPage(p=>p+1)}>Próxima página de fontes</Button></>}</section>;}
function Identity({row}:{row:{display?:{label:string|null;party_name:string|null;description:string|null;document_number:string|null}}}){return row.display?<p>Identificação atual: {[row.display.label,row.display.party_name,row.display.description,row.display.document_number].filter(Boolean).join(' · ')||'Cadastro sem identificação descritiva'}</p>:null;}
export function CashForecastSourceRows({data,onAgenda}:{data:Page;onAgenda?:(key:string,label:string)=>void}){if(data.kind==='origins')return <ul>{data.rows.map(r=><li className="rounded border p-2" key={r.economic_key}><Identity row={r}/><p>{r.source_table==='payables'?'Conta a pagar':r.scenario==='unbilled'?'Frete a faturar':'Título a receber'} · {r.source_id} · {r.direction==='in'?'Entrada':'Saída'}</p><p>Nominal {forecastMoney(r.nominal_cents)} · realizado {forecastMoney(r.fulfilled_cents)} · crédito vinculado {forecastMoney(r.reserved_credit_cents)}</p><p>Data prevista: {r.expected_on||'Indeterminada'} · {r.valid?'Origem conferida':'Origem requer conferência; valores indeterminados'}</p><CashForecastAgendaHistory origin={r}/>{onAgenda&&r.valid&&<Button onClick={()=>onAgenda(r.economic_key,[r.display?.party_name,r.display?.label,r.display?.description].filter(Boolean).join(' · ')||r.source_id)}>Revisar data esperada desta origem</Button>}</li>)}</ul>;if(data.kind==='movements')return <ul>{data.rows.map(r=><li key={r.movement_id}><Identity row={r}/>{r.direction==='in'?'Entrada':'Saída'} {forecastMoney(r.amount_cents)} · {r.occurred_on} · conta {r.account_id} · movimento {r.movement_id}</li>)}</ul>;if(data.kind==='credits')return <ul>{data.rows.map(r=><li key={r.credit_id}><Identity row={r}/>Crédito {r.credit_id} · pagador {r.payer_id} · saldo disponível {forecastMoney(r.amount_cents)} · {r.valid?'Conferido':'Precisa de conferência'} · recebimento {r.source_payment_id}</li>)}</ul>;return <ul>{data.rows.map((r,n)=><li key={n}>{forecastIssue(r.code)} · {r.source_ids.join(', ')||'Sem ID individual'} · {r.code}</li>)}</ul>;}
