import {costDispositionReturnErrorLabel} from '@/lib/financial/costDispositionReturnLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {type CostDispositionReturnPreview} from '@/lib/financial/costDispositionReturnContract';
import {sendCostDispositionReturn} from '@/lib/financial/costDispositionReturnClient';
import {createCostDispositionReturnOutbox,lockCostDispositionReturn,pendingCostDispositionReturn,costDispositionReturnKey,type PendingCostDispositionReturn} from '@/lib/financial/costDispositionReturnOutbox';
export function CostDispositionReturnConfirmation({tenant,actor,dispositionId,preview,refresh}:{tenant:string;actor:string;dispositionId:string;preview:CostDispositionReturnPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingCostDispositionReturn|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingCostDispositionReturn(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createCostDispositionReturnOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockCostDispositionReturn,send:sendCostDispositionReturn}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===costDispositionReturnKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.disposition_id===dispositionId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{dispositionId,movementId:preview!.incoming.movement_id,amountCents:preview!.effects.amount_cents,expected:{expense_id:preview!.expense_id,charge_id:preview!.charge_id,payable_id:preview!.payable_id,regularization_id:preview!.regularization_id,effects:preview!.effects},revision:preview!.revision,reason});setConfirmed(`Devolução registrada: ${formatFinanceCents(result.effects.amount_cents)}. Entrada ${result.incoming_movement_id}; pedido ${result.request_id}. Nenhum novo movimento de dinheiro foi criado. A conferência bancária permanece separada.`);setReview(null);try{await refresh();}catch{setError('A devolução foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(costDispositionReturnErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da devolução">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novas correções estão bloqueadas.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · responsabilidade {pending.payload.disposition_id} · entrada {pending.payload.incoming_movement_id} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p><p>Valor: {formatFinanceCents(pending.payload.amount_cents)} · gasto {pending.expected.expense_id}</p>{pending.payload.disposition_id!==dispositionId&&<p role="alert">Este pedido pertence a outra responsabilidade. A recuperação consulta exclusivamente aquele pedido.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido de devolução</Button></>:fresh?<><label className="block">Motivo da devolução<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar devolução</Button>{review===preview?.revision&&<><p>Vincular a entrada já registrada ao retorno desta responsabilidade. Nenhum novo dinheiro será movimentado. Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi a entrada e o responsável. Confirmo o vínculo desta devolução ao dinheiro já registrado, sem nova transferência bancária.</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar devolução</Button></>}</>:<p>A confirmação de devolução está indisponível nesta consulta.</p>}</section>;
}
