import {CustomerCreditRefundDialog} from './CustomerCreditRefundPanel';
import {refreshCustomerCredit} from '@/lib/financial/customerCreditCache';
import {useCallback,useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {CustomerCreditReview} from './CustomerCreditReview';
import {CustomerCreditConfirmation} from './CustomerCreditConfirmation';
import {CustomerCreditChangedError,customerCreditError,readCustomerCreditOptions} from '@/lib/financial/customerCreditClient';
import type {CustomerCreditOptions,CustomerCreditQuery} from '@/lib/financial/customerCreditContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
const money=(v:string|null)=>v===null?'Indeterminado':formatFinanceCents(v);
type Selection={receivableId:string;applicationId:string|null;label:string};
export function CustomerCreditDialog({tenant,actor,onClose}:{tenant:string;actor:string;onClose:()=>void}){return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="sm:max-w-4xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Créditos de clientes</DialogTitle><DialogDescription>Crédito existente do mesmo pagador pode liquidar títulos. Aplicar ou liberar um vínculo não movimenta dinheiro.</DialogDescription></DialogHeader><FinanceAccessBoundary><CustomerCreditPanel key={`${tenant}:${actor}`} tenant={tenant} actor={actor}/></FinanceAccessBoundary><Button variant="outline" onClick={onClose}>Fechar créditos</Button></DialogContent></Dialog>;}
export function CustomerCreditPanel({tenant,actor}:{tenant:string;actor:string}){
 const cache=useQueryClient();const refresh=()=>refreshCustomerCredit(cache,tenant);
 const clearSelection=useCallback(()=>setSelection(null),[]);
 const [refundOpen,setRefundOpen]=useState(false);
 const [credit,setCredit]=useState<{id:string;name:string}|null>(null),[kind,setKind]=useState<'targets'|'history'>('targets'),[selection,setSelection]=useState<Selection|null>(null);
 return <section className="space-y-3">{!credit?<><CustomerCreditCatalogue tenant={tenant} actor={actor} kind="credits" creditId={null} onCredit={(id,name)=>{setCredit({id,name});setSelection(null);}}/><CustomerCreditConfirmation tenant={tenant} actor={actor} preview={undefined} refresh={refresh}/></>:<><Button variant="outline" onClick={()=>{setCredit(null);setSelection(null);setRefundOpen(false);}}>Voltar aos créditos</Button><h3>Crédito de {credit.name}</h3><Button variant="outline" onClick={()=>setRefundOpen(true)}>Conferir devolução de dinheiro</Button>{refundOpen&&<CustomerCreditRefundDialog tenant={tenant} actor={actor} creditId={credit.id} onClose={()=>setRefundOpen(false)}/>}<p className="text-xs">Referência {credit.id}</p><div className="flex gap-2"><Button variant={kind==='targets'?'default':'outline'} onClick={()=>{setKind('targets');setSelection(null);}}>Títulos do pagador</Button><Button variant={kind==='history'?'default':'outline'} onClick={()=>{setKind('history');setSelection(null);}}>Histórico de aplicações</Button></div><CustomerCreditCatalogue key={`${credit.id}:${kind}`} tenant={tenant} actor={actor} kind={kind} creditId={credit.id} onSelection={setSelection} onUnavailable={clearSelection}/>{selection?<CustomerCreditReview key={`${credit.id}:${selection.receivableId}:${selection.applicationId}`} tenant={tenant} actor={actor} creditId={credit.id} {...selection}/>:<CustomerCreditConfirmation tenant={tenant} actor={actor} preview={undefined} refresh={refresh}/>}</>}</section>;
}
export function CustomerCreditCatalogue({tenant,actor,kind,creditId,onCredit,onSelection,onUnavailable}:{tenant:string;actor:string;kind:CustomerCreditQuery['kind'];creditId:string|null;onCredit?:(id:string,name:string)=>void;onSelection?:(value:Selection)=>void;onUnavailable?:()=>void}){
 const [draft,setDraft]=useState(''),[search,setSearch]=useState(''),[available,setAvailable]=useState(false),[offset,setOffset]=useState(0),[revision,setRevision]=useState<string|null>(null),[epoch,setEpoch]=useState(0),[notice,setNotice]=useState('');
 const query=useQuery({queryKey:['finance-customer-credit-options',tenant,actor,kind,creditId,search,available,offset,revision,epoch],queryFn:()=>readCustomerCreditOptions(tenant,actor,{kind,credit_id:creditId,payer_id:null,search,available_only:available,offset,limit:30,expected_revision:revision}),retry:false});
 useEffect(()=>{if(query.error instanceof CustomerCreditChangedError){setNotice('A consulta mudou. Reiniciamos na primeira página para mostrar os dados atuais.');setOffset(0);setRevision(null);setEpoch(x=>x+1);}},[query.error]);
 const data=query.isFetching||query.isError?undefined:query.data;
 function navigate(next:number){if(data){setRevision(data.revision);setOffset(next);onUnavailable?.();}}
 return <section aria-label={kind==='credits'?'Catálogo de créditos':kind==='targets'?'Títulos elegíveis':'Histórico do crédito'} className="space-y-2"><form onSubmit={e=>{e.preventDefault();setSearch(draft.trim());setOffset(0);setRevision(null);setEpoch(x=>x+1);onUnavailable?.();}}><label>Buscar {kind==='credits'?'pagador':'título'}<Input value={draft} onChange={e=>setDraft(e.target.value)}/></label>{kind==='credits'&&<label><input type="checkbox" checked={available} onChange={e=>{setAvailable(e.target.checked);setOffset(0);setRevision(null);}}/> Somente com crédito disponível</label>}<Button>Pesquisar</Button></form>{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Carregando consulta…</p>}{query.error&&!(query.error instanceof CustomerCreditChangedError)&&<p role="alert">{customerCreditError(query.error)} <Button onClick={()=>void query.refetch()}>Tentar novamente</Button></p>}{data&&<><p>{data.total} {kind==='history'?'eventos':'registros'} no filtro. Valores não devem ser somados ao caixa.</p><CustomerCreditRows data={data} onCredit={onCredit} onSelection={onSelection}/><div className="flex gap-2"><Button disabled={data.offset===0} onClick={()=>navigate(Math.max(0,data.offset-data.limit))}>Página anterior</Button><span>Página {Math.floor(data.offset/data.limit)+1}</span><Button disabled={data.next_offset===null} onClick={()=>navigate(data.next_offset!)}>Próxima página</Button></div></>}</section>;
}
function CustomerCreditRows({data,onCredit,onSelection}:{data:CustomerCreditOptions;onCredit?:(id:string,name:string)=>void;onSelection?:(v:Selection)=>void}){
 if(data.kind==='credits')return <>{data.rows.map(r=><article key={r.credit_id} className="rounded border p-3"><h4>{r.payer_name||'Pagador sem nome informado'}</h4><p>Crédito original {money(r.original_cents)} · aplicado {money(r.applied_cents)} · disponível {money(r.available_cents)}</p><p>Liberações de aplicações acumuladas {money(r.released_cents)} (não são devoluções de dinheiro).</p>{r.returned_cents===undefined?<p>Devoluções de dinheiro não detalhadas nesta versão.</p>:<p>Dinheiro devolvido: {money(r.returned_cents)}</p>}<p className="text-xs">Crédito {r.credit_id} · pagador {r.payer_id} · pagamento de origem {r.source_payment_id}</p>{!r.valid&&<p role="alert">Origem do crédito precisa de conferência; disponibilidade indeterminada.</p>}<Button onClick={()=>onCredit?.(r.credit_id,r.payer_name||r.payer_id)}>Conferir crédito de {r.payer_name||r.payer_id}</Button></article>)}</>;
 if(data.kind==='targets')return <>{data.rows.map(r=><article key={r.receivable_id} className="rounded border p-3"><h4>{r.reference}</h4><p>Dinheiro recebido {money(r.cash_received_cents)} · crédito aplicado {money(r.credit_applied_cents)} · liquidado {money(r.settled_cents)} · em aberto {money(r.open_cents)}</p><p className="text-xs">Título {r.receivable_id}</p><Button onClick={()=>onSelection?.({receivableId:r.receivable_id,applicationId:null,label:r.reference})}>Selecionar {r.reference}</Button></article>)}</>;
 return <>{data.rows.map(r=><article key={r.id} className="rounded border border-amber-600 bg-amber-50 dark:bg-amber-950 p-3"><strong>{r.action==='apply'?'Aplicação':'Liberação'} · {r.reference}</strong><p>{money(r.amount_cents)}{r.action==='apply'&&` · ainda vinculado ${money(r.remaining_cents)}`}</p><p>Autor: {r.actor_name} {r.actor_id?`(${r.actor_id})`:'(sistema)'} · {r.created_at}</p><p>Motivo: {r.reason}</p>{r.observation_id&&<p>Observação fiscal vinculada {r.observation_id}</p>}<p className="text-xs">Evento {r.id} · título {r.receivable_id}</p>{r.can_release&&<Button onClick={()=>onSelection?.({receivableId:r.receivable_id,applicationId:r.application_id,label:r.reference})}>Conferir liberação de {r.reference}</Button>}</article>)}</>;
}
