import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {CustomerCreditRefundReview} from './CustomerCreditRefundReview';
import {CustomerCreditRefundConfirmation} from './CustomerCreditRefundConfirmation';
import {CustomerCreditRefundChangedError,customerCreditRefundError,readCustomerCreditRefundOptions} from '@/lib/financial/customerCreditRefundClient';
import {refreshCustomerCredit} from '@/lib/financial/customerCreditCache';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
export function CustomerCreditRefundDialog({tenant,actor,creditId,onClose}:{tenant:string;actor:string;creditId:string;onClose:()=>void}){return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="sm:max-w-4xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Devolução de crédito</DialogTitle><DialogDescription>Vincule uma saída já registrada ao pagador do crédito. Esta ação não faz transferências nem cria movimentos bancários.</DialogDescription></DialogHeader><CustomerCreditRefundPanel key={`${tenant}:${actor}:${creditId}`} tenant={tenant} actor={actor} creditId={creditId}/><Button variant="outline" onClick={onClose}>Fechar devolução</Button></DialogContent></Dialog>;}
export function CustomerCreditRefundPanel({tenant,actor,creditId}:{tenant:string;actor:string;creditId:string}){
 const [kind,setKind]=useState<'movements'|'history'>('movements'),[draft,setDraft]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[revision,setRevision]=useState<string|null>(null),[epoch,setEpoch]=useState(0),[notice,setNotice]=useState(''),[movement,setMovement]=useState<string|null>(null);const cache=useQueryClient();
 const query=useQuery({queryKey:['finance-customer-credit-refund-options',tenant,actor,creditId,kind,search,offset,revision,epoch],queryFn:()=>readCustomerCreditRefundOptions(tenant,actor,creditId,{kind,search,offset,limit:30,expected_revision:revision}),retry:false});const data=query.isFetching||query.isError?undefined:query.data;
 useEffect(()=>{if(query.error instanceof CustomerCreditRefundChangedError){setNotice('A consulta mudou. Reiniciamos na primeira página.');setOffset(0);setRevision(null);setEpoch(v=>v+1);setMovement(null);}},[query.error]);
 function reset(){setOffset(0);setRevision(null);setMovement(null);}
 return <section className="space-y-3"><div className="flex gap-2"><Button onClick={()=>{setKind('movements');reset();}}>Saídas registradas</Button><Button onClick={()=>{setKind('history');reset();}}>Histórico de devoluções</Button></div><form onSubmit={e=>{e.preventDefault();setSearch(draft.trim());reset();setEpoch(v=>v+1);}}><label>Buscar saída ou devolução<Input value={draft} onChange={e=>setDraft(e.target.value)}/></label><Button>Pesquisar</Button></form>{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando saídas e devoluções…</p>}{query.error&&!(query.error instanceof CustomerCreditRefundChangedError)&&<p role="alert">{customerCreditRefundError(query.error)} <Button onClick={()=>void query.refetch()}>Tentar novamente</Button></p>}{data&&<><p>{data.total} {data.kind==='history'?'devoluções vinculadas':'saídas compatíveis'} no filtro.</p>{data.rows.length===0&&<p>Nenhum registro encontrado. Para vincular devolução, a saída precisa estar registrada e comprovar o documento do pagador.</p>}{data.kind==='movements'?data.rows.map(r=><article className="rounded border p-3" key={r.movement_id}><h4>{r.beneficiary_name||'Destinatário sem nome'} · {r.beneficiary_document||'Documento não informado'}</h4><p>{r.bank_account_name||'Conta sem nome'} · {r.occurred_on} · saída {formatFinanceCents(r.amount_cents)}</p><p>Utilizado {formatFinanceCents(r.used_cents)} · disponível {formatFinanceCents(r.available_cents)}</p><p className="text-xs">Movimento {r.movement_id}</p><Button onClick={()=>setMovement(r.movement_id)}>Conferir saída de {r.occurred_on}</Button></article>):data.rows.map(r=><article className="rounded border border-amber-600 bg-amber-50 dark:bg-amber-950 p-3" key={r.refund_id}><strong>Devolução vinculada: {formatFinanceCents(r.amount_cents)}</strong><p>Saída de {r.occurred_on} · movimento {r.outgoing_movement_id}</p><p>Autor: {r.actor_name||'Nome não informado'} ({r.actor_id||'sistema'}) · registro {r.created_at}</p><p>Motivo: {r.reason}</p><p className="text-xs">Vínculo {r.refund_id}</p></article>)}<div className="flex gap-2"><Button disabled={!data.offset} onClick={()=>{setOffset(Math.max(0,data.offset-data.limit));setRevision(data.revision);setMovement(null);}}>Página anterior</Button><span>Página {Math.floor(data.offset/data.limit)+1}</span><Button disabled={data.next_offset===null} onClick={()=>{setOffset(data.next_offset!);setRevision(data.revision);setMovement(null);}}>Próxima página</Button></div></>}{movement?<CustomerCreditRefundReview key={movement} tenant={tenant} actor={actor} creditId={creditId} movementId={movement}/>:<CustomerCreditRefundConfirmation tenant={tenant} actor={actor} preview={undefined} refresh={()=>refreshCustomerCredit(cache,tenant)}/>}</section>;
}
