import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import type {CustomerCreditRefundPreview} from '@/lib/financial/customerCreditRefundContract';
import {customerCreditRefundError,sendCustomerCreditRefund} from '@/lib/financial/customerCreditRefundClient';
import {createCustomerCreditRefundOutbox,customerCreditRefundKey,lockCustomerCreditRefund,pendingCustomerCreditRefund,type PendingCustomerCreditRefund} from '@/lib/financial/customerCreditRefundOutbox';
export function CustomerCreditRefundConfirmation({tenant,actor,preview,refresh}:{tenant:string;actor:string;preview:CustomerCreditRefundPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingCustomerCreditRefund|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[checked,setChecked]=useState<string|null>(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState('');
 const sync=()=>{try{setPending(pendingCustomerCreditRefund(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createCustomerCreditRefundOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||t!==live.current.tenant||a!==live.current.actor)throw Error('Recupere o pedido na sessão original.');},lock:lockCustomerCreditRefund,send:sendCustomerCreditRefund}));
 useEffect(()=>{live.current.active=true;syncRef.current();const listener=(e:StorageEvent)=>{if(e.key===null||e.key===customerCreditRefundKey(tenant,actor))syncRef.current();};window.addEventListener('storage',listener);return()=>{live.current.active=false;window.removeEventListener('storage',listener);};},[tenant,actor]);
 const fresh=preview?.can_execute&&preview.eligible&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(busy||corrupt||confirmed||!recover&&(!fresh||checked!==preview?.revision||reason.trim().length<5))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{credit_id:preview!.credit_id,outgoing_movement_id:preview!.outgoing_movement_id,expected:{payer_id:preview!.payer_id,effects:preview!.effects},amount_cents:preview!.amount_cents,expected_revision:preview!.revision,reason});setConfirmed(`Devolução vinculada à saída ${result.outgoing_movement_id}: ${formatFinanceCents(result.amount_cents)}. Pedido ${result.request_id}. Nenhum novo dinheiro foi movimentado.`);setChecked(null);try{await refresh();}catch{setError('A operação foi registrada, mas a consulta não foi atualizada. Atualize antes de continuar.');}}catch(failure){setChecked(null);setError(customerCreditRefundError(failure));try{await refresh();}catch{/* Preserve the original rejection and durable request. */}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da devolução">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; nova operação bloqueada.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · crédito {pending.payload.credit_id} · saída {pending.payload.outgoing_movement_id} · pagador {pending.expected.payer_id}</p><p>Vincular devolução de {formatFinanceCents(pending.payload.amount_cents)}. Motivo: {pending.payload.reason}</p>{preview&&(preview.credit_id!==pending.payload.credit_id||preview.outgoing_movement_id!==pending.payload.outgoing_movement_id)&&<p>Este pedido pertence a outra seleção; recuperar repete somente o pedido original.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido de devolução</Button></>:fresh?<><label className="block">Motivo<textarea value={reason} maxLength={2000} disabled={busy} onChange={e=>{setReason(e.target.value);setChecked(null);}}/></label><label className="block"><input type="checkbox" checked={checked===preview.revision} disabled={busy} onChange={e=>setChecked(e.target.checked?preview.revision:null)}/> Conferi crédito, destinatário, saída e valor. Esta operação vincula uma saída já registrada ao crédito. Não executa transferência nem cria saída bancária.</label><Button disabled={busy||checked!==preview.revision||reason.trim().length<5} onClick={()=>void execute(false)}>Confirmar vínculo de devolução</Button></>:<p>Confirmação indisponível. Consulte uma prévia atual.</p>}</section>;
}
