import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {readDriverAdvancePositions,readDriverAdvanceReturnOptions,readDriverAdvanceReturnPreview,sendDriverAdvanceReturn} from '@/lib/financial/driverAdvanceReturnClient';
import {reaisToCents,type DriverAdvancePosition} from '@/lib/financial/driverAdvanceReturnContract';
import {createDriverAdvanceReturnOutbox,driverAdvanceReturnKey,lockDriverAdvanceReturn,pendingDriverAdvanceReturn,type DriverAdvanceReturnInput,type PendingDriverAdvanceReturn} from '@/lib/financial/driverAdvanceReturnOutbox';

const money=(value:string|null)=>value===null?'A revisar':formatFinanceCents(value);
export function DriverAdvanceReturns({tenant,actor}:{tenant:string;actor:string}){
 const cache=useQueryClient(),[page,setPage]=useState(1),[selected,setSelected]=useState<DriverAdvancePosition|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<PendingDriverAdvanceReturn|null>(null),[corrupt,setCorrupt]=useState(false),live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const sync=()=>{try{setPending(pendingDriverAdvanceReturn(localStorage,tenant,actor));setCorrupt(false);}catch{setPending(null);setCorrupt(true);}};const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createDriverAdvanceReturnOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome a devolução na empresa e sessão originais.');},lock:lockDriverAdvanceReturn,send:sendDriverAdvanceReturn}));
 useEffect(()=>{live.current.active=true;syncRef.current();const listener=(event:StorageEvent)=>{if(event.key===null||event.key===driverAdvanceReturnKey(tenant,actor))syncRef.current();};window.addEventListener('storage',listener);return()=>{live.current.active=false;window.removeEventListener('storage',listener);};},[tenant,actor]);
 const query=useQuery({queryKey:['finance-driver-advance-positions',tenant,actor,page],queryFn:()=>readDriverAdvancePositions(tenant,actor,page),retry:false,staleTime:0}),data=query.isFetching||query.isError?undefined:query.data;
 async function refresh(){for(const key of ['finance-driver-advance-positions','finance-movements','finance-expenses','finance-options','finance-audit','finance-reconciliation-options'])await cache.invalidateQueries({queryKey:[key]});}
 function discardCorrupt(){try{localStorage.removeItem(driverAdvanceReturnKey(tenant,actor));setPending(null);setCorrupt(false);setSelected(null);setError('');setNotice('Recuperação incompatível descartada. Você pode iniciar uma nova devolução.');}catch{setError('Não foi possível descartar a recuperação incompatível. Recarregue a página e tente novamente.');}}
 async function recorded(result:{request_id:string;open_cents:string}){setSelected(null);setNotice(`Devolução vinculada. Saldo aberto: ${formatFinanceCents(result.open_cents)}. Pedido ${result.request_id}. Nenhum dinheiro novo foi criado.`);try{await refresh();}catch{setError('A devolução foi confirmada, mas as consultas não foram atualizadas. Atualize a tela antes de continuar.');}}
 async function recover(){if(busy||corrupt||!pending)return;setBusy(true);setError('');try{await recorded(await outbox.recover(tenant,actor));}catch(value){setError(value instanceof Error?value.message:'Não foi possível recuperar a devolução preservada.');}finally{setBusy(false);}}
 return <section className="space-y-3 rounded-lg border p-4" aria-label="Saldos de adiantamentos de viagem"><div><h2 className="font-semibold">Devoluções de adiantamentos de viagem</h2><p className="text-sm text-muted-foreground">Vincule uma entrada bancária já registrada ao saldo não utilizado. O envio original e suas categorias não são alterados.</p></div>
  {notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{corrupt&&<div><p role="alert">O pedido de devolução salvo está inconsistente. Preserve os dados antes de iniciar outra operação.</p><Button variant="outline" disabled={busy} onClick={discardCorrupt}>Descartar recuperação incompatível</Button></div>}{pending&&!corrupt&&<div className="rounded border border-amber-400 p-3 text-sm"><p>Há uma devolução sem confirmação: pedido {pending.payload.request_id}, valor {formatFinanceCents(pending.payload.amount_cents)}.</p><Button className="mt-2" variant="outline" disabled={busy} onClick={()=>void recover()}>{busy?'Recuperando…':'Recuperar pedido original'}</Button></div>}
  {query.isFetching&&<p role="status">Conferindo saldos de adiantamentos…</p>}{query.isError&&<div role="alert"><p>Não foi possível conferir os saldos de adiantamentos.</p><Button variant="outline" onClick={()=>void query.refetch()}>Tentar novamente</Button></div>}
  {data&&<><div className="space-y-2">{data.rows.map(position=><article key={position.movement_id} className="flex flex-col gap-2 rounded border p-3 md:flex-row md:items-center md:justify-between"><div><p className="font-medium">{position.driver_name??'Motorista não identificado'} · {position.occurred_on.split('-').reverse().join('/')}</p><p className="text-sm">Enviado {money(position.amount_cents)} · comprovado {money(position.allocated_cents)} · devolvido {money(position.returned_cents)} · <strong>aberto {money(position.open_cents)}</strong></p><p className="text-xs text-muted-foreground">Conta de origem: {position.account_name} · {position.history_count} devolução(ões) vinculada(s)</p>{position.history.length>0&&<details><summary>Auditar devoluções</summary>{position.history.map(row=><p key={row.return_id}>{row.occurred_on.split('-').reverse().join('/')} · {formatFinanceCents(row.amount_cents)} · {row.actor_name} · {row.reason} · entrada {row.incoming_movement_id}</p>)}</details>}{!position.verified&&<p role="alert" className="text-sm">Saldo não verificável: {position.issue??'origem inconsistente'}.</p>}</div><Button disabled={corrupt||!!pending||!position.verified||position.open_cents==='0'||position.open_cents===null} onClick={()=>{setError('');setSelected(position);}}>Vincular devolução registrada</Button></article>)}{data.total===0&&<p>Nenhum adiantamento de viagem registrado.</p>}</div><div className="flex items-center justify-between"><Button variant="outline" disabled={page===1||query.isFetching} onClick={()=>setPage(value=>value-1)}>Anterior</Button><span className="text-sm">Página {page} de {Math.max(1,Math.ceil(data.total/data.page_size))}</span><Button variant="outline" disabled={page*data.page_size>=data.total||query.isFetching} onClick={()=>setPage(value=>value+1)}>Próxima</Button></div></>}
  {selected&&<DriverAdvanceReturnDialog tenant={tenant} actor={actor} position={selected} busy={busy} onClose={()=>!busy&&setSelected(null)} onSubmit={async input=>{setBusy(true);setError('');try{await recorded(await outbox.submit(tenant,actor,input));}catch(value){setError(value instanceof Error?value.message:'Não foi possível confirmar a devolução. O pedido foi preservado quando o resultado ficou incerto.');throw value;}finally{setBusy(false);}}}/>}</section>;
}

function DriverAdvanceReturnDialog({tenant,actor,position,busy,onClose,onSubmit}:{tenant:string;actor:string;position:DriverAdvancePosition;busy:boolean;onClose:()=>void;onSubmit:(input:DriverAdvanceReturnInput)=>Promise<void>}){
 const [draftSearch,setDraftSearch]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[optionsRevision,setOptionsRevision]=useState<string|null>(null),[incoming,setIncoming]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[ack,setAck]=useState<string|null>(null),[rejected,setRejected]=useState<string|null>(null),[localError,setLocalError]=useState('');const amountCents=reaisToCents(amount);
 const options=useQuery({queryKey:['finance-driver-advance-return-options',tenant,actor,position.movement_id,search,page,page===1?null:optionsRevision],queryFn:()=>readDriverAdvanceReturnOptions(tenant,actor,position.movement_id,search,page,page===1?null:optionsRevision),enabled:page===1||optionsRevision!==null,retry:false,staleTime:0});
 const optionsData=options.isFetching||options.isError?undefined:options.data;useEffect(()=>{if(optionsData?.page===1)setOptionsRevision(optionsData.revision);},[optionsData]);
 const preview=useQuery({queryKey:['finance-driver-advance-return-preview',tenant,actor,position.movement_id,incoming,amountCents],queryFn:()=>readDriverAdvanceReturnPreview(tenant,actor,position.movement_id,incoming,amountCents!),enabled:false,retry:false,staleTime:0}),data=preview.isFetching||preview.isError?undefined:preview.data,fresh=!!data?.can_execute&&data.revision!==rejected;
 async function submit(){if(busy||!data||!fresh||ack!==data.revision||reason.trim().length<10)return;setLocalError('');try{await onSubmit({advance_movement_id:position.movement_id,incoming_movement_id:incoming,amount_cents:data.amount_cents,expected_revision:data.revision,reason,expected_open_cents:data.effects.open_after_cents!});}catch(value){setRejected(data.revision);setAck(null);setLocalError(value instanceof Error?value.message:'Não foi possível confirmar a devolução.');}}
 return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Vincular devolução registrada</DialogTitle><DialogDescription>Selecione uma entrada bancária já existente. Nenhum dinheiro novo será criado e os movimentos originais permanecerão inalterados.</DialogDescription></DialogHeader><div className="space-y-3"><p>{position.driver_name??'Motorista'} · saldo aberto {money(position.open_cents)}</p>
  <form className="flex gap-2" onSubmit={event=>{event.preventDefault();setSearch(draftSearch.trim());setPage(1);setOptionsRevision(null);setIncoming('');setAck(null);}}><div className="flex-1"><Label htmlFor="driver-return-search">Buscar entrada</Label><Input id="driver-return-search" value={draftSearch} onChange={event=>setDraftSearch(event.target.value)} placeholder="Descrição, favorecido ou conta"/></div><Button className="self-end" type="submit" variant="outline">Buscar</Button></form>
  {options.isFetching&&<p role="status">Buscando entradas disponíveis…</p>}{options.isError&&<p role="alert">Não foi possível carregar as entradas disponíveis.</p>}{optionsData&&<><Label htmlFor="driver-return-movement">Entrada bancária devolvida</Label><select id="driver-return-movement" className="h-10 w-full rounded-md border bg-background px-3" value={incoming} onChange={event=>{setIncoming(event.target.value);setAck(null);setRejected(null);}}><option value="">Selecione uma entrada</option>{optionsData.rows.map(row=><option key={row.id} value={row.id}>{row.occurred_on.split('-').reverse().join('/')} · {row.bank_account_name} · {formatFinanceCents(row.available_cents)} · {row.description}</option>)}</select>{optionsData.total===0&&<p>Nenhuma entrada compatível foi encontrada para este motorista.</p>}<div className="flex items-center justify-between"><Button variant="outline" disabled={page===1||options.isFetching} onClick={()=>{setPage(value=>value-1);setIncoming('');setAck(null);}}>Anterior</Button><span className="text-sm">Página {page} de {Math.max(1,Math.ceil(optionsData.total/optionsData.page_size))}</span><Button variant="outline" disabled={page*optionsData.page_size>=optionsData.total||options.isFetching||!optionsRevision} onClick={()=>{setPage(value=>value+1);setIncoming('');setAck(null);}}>Próxima</Button></div></>}
  <div><Label htmlFor="driver-return-amount">Valor devolvido</Label><Input id="driver-return-amount" inputMode="decimal" value={amount} onChange={event=>{setAmount(event.target.value);setAck(null);setRejected(null);}} placeholder="0,00"/></div>{amount&&!amountCents&&<p role="alert">Informe um valor maior que zero com até duas casas decimais.</p>}<Button variant="outline" title={busy?'Aguarde a operação atual.':!incoming?'Selecione uma entrada bancária.':!amountCents?'Informe um valor válido.':'Conferir a entrada e o saldo.'} disabled={busy||!incoming||!amountCents} onClick={()=>{setAck(null);setRejected(null);void preview.refetch();}}>{preview.isFetching?'Conferindo…':'Conferir devolução'}</Button>
  {preview.isFetching&&<p role="status">Conferindo a devolução…</p>}{preview.isError&&<p role="alert">Não foi possível conferir esta devolução. Atualize as opções e tente novamente.</p>}{data&&!fresh&&<p role="alert">A devolução não está disponível nesta conferência. Revise o saldo e a entrada selecionada.</p>}{data&&fresh&&<><div className="rounded border p-3 text-sm"><p>Saldo antes: {formatFinanceCents(data.effects.open_before_cents)} · saldo depois: {formatFinanceCents(data.effects.open_after_cents!)}</p><p>Entrada disponível: {formatFinanceCents(data.incoming.available_cents)}.</p><p>Nenhum caixa ou despesa será criado; ambos os movimentos originais permanecerão inalterados.</p></div><div><Label htmlFor="driver-return-reason">Motivo da vinculação</Label><textarea id="driver-return-reason" className="min-h-20 w-full rounded-md border bg-background p-2" maxLength={2000} value={reason} onChange={event=>{setReason(event.target.value);setAck(null);}}/></div><label className="flex gap-2"><input type="checkbox" checked={ack===data.revision} onChange={event=>setAck(event.target.checked?data.revision:null)}/> Conferi o motorista, a entrada bancária, o valor e o saldo final.</label></>}
  {localError&&<p role="alert">{localError}</p>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={onClose}>Cancelar</Button><Button disabled={busy||!fresh||!data||ack!==data.revision||reason.trim().length<10} onClick={()=>void submit()}>{busy?'Confirmando…':'Confirmar vinculação'}</Button></div></div></DialogContent></Dialog>;
}
