import {useCallback,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {EmployeeAdvancePaymentPages} from './EmployeeAdvancePaymentPages';
import {EmployeeAdvancePaymentConfirmation} from './EmployeeAdvancePaymentConfirmation';
import {readEmployeeAdvancePayment} from '@/lib/financial/employeeAdvancePaymentClient';
import {formatFinanceCents,parseFinanceAmount} from '@/lib/financial/ledgerContract';
const labels:Record<string,string>={finance_advance_manager_required:'Somente a gestão pode confirmar este pagamento.',finance_advance_source_invalid:'A origem do adiantamento precisa de conferência.',finance_advance_not_payable:'Este adiantamento não permite novos pagamentos.',finance_advance_payment_amount_invalid:'Informe um valor positivo com até duas casas decimais.',finance_advance_movement_required:'Selecione uma saída registrada.',finance_advance_beneficiary_mismatch:'A saída não comprova o mesmo funcionário.',finance_advance_movement_invalid:'A saída não é válida para este vínculo.',finance_advance_movement_capacity:'A saída não possui saldo disponível suficiente.',finance_advance_exceeds_open:'O valor supera o restante do adiantamento.'};
export function EmployeeAdvancePaymentDialog(props:{tenant:string;actor:string;advance:string;open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>Conferir pagamento do adiantamento</DialogTitle><DialogDescription>Vincule uma saída já registrada ao funcionário. É possível registrar parte do valor; nenhum novo dinheiro ou gasto será criado. A conciliação bancária permanece separada.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><EmployeeAdvancePaymentWorkspace key={`${props.tenant}:${props.actor}:${props.advance}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
export function EmployeeAdvancePaymentWorkspace({tenant,actor,advance}:{tenant:string;actor:string;advance:string}){
 const cache=useQueryClient(),[selected,setSelected]=useState<{id:string;label:string}|null>(null),[amount,setAmount]=useState(''),[request,setRequest]=useState<{movement:string;amount:string;epoch:number}|null>(null),[error,setError]=useState('');
 const invalidate=useCallback(()=>{setSelected(null);setRequest(null);},[]);
 const preview=useQuery({queryKey:['finance-advance-payment-preview',tenant,actor,advance,request],queryFn:()=>readEmployeeAdvancePayment(tenant,actor,advance,request?.movement||null,request?.amount||null),retry:false,staleTime:0,refetchOnMount:'always'});
 const data=preview.isFetchedAfterMount&&!preview.isFetching&&!preview.isError?preview.data:undefined;
 async function refresh(){invalidate();await Promise.all(['finance-advance-payment-preview','finance-advance-payment-options','finance-advance-payment-history','employee_advances','finance-payable-portfolio','finance-payable-approval','finance-account-period','finance-period-money-package','finance-audit','finance-cash-forecast-preview'].map(key=>cache.invalidateQueries({queryKey:[key,tenant]},{throwOnError:true})));}
 const money=(v:string|null)=>v===null?'Indeterminado':formatFinanceCents(v);
 return <section className="space-y-3" aria-label="Pagamento canônico de adiantamento">{preview.isFetching&&<p role="status">Conferindo adiantamento…</p>}{preview.isError&&<><p role="alert">A conferência está indisponível. Nenhuma consulta anterior autoriza pagar.</p><Button onClick={()=>void preview.refetch()}>Conferir novamente</Button></>}{data&&<><p>{data.advance.employee_name} · {data.advance.employee_document||'Documento não informado'}</p><p>Nominal: {money(data.advance.amount_cents)} · pago comprovado: {money(data.advance.paid_cents)} · restante: {money(data.advance.open_cents)}</p><p>{data.advance.payment_count} pagamentos canônicos anteriores. Consulte os comprovantes no histórico paginado abaixo.</p>{!data.advance.verified&&<p role="alert">A posição requer conferência de origem. Valores desconhecidos não são tratados como zero.</p>}</>}
 <EmployeeAdvancePaymentPages tenant={tenant} actor={actor} advance={advance} kind="options" onInvalidate={invalidate} onSelect={(id,label)=>{setSelected({id,label});setRequest(null);}}/>{selected&&<p>Saída selecionada: {selected.label}</p>}<label>Valor a vincular (R$)<Input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setRequest(null);}}/></label><Button disabled={!selected||preview.isFetching} onClick={()=>{const cents=parseFinanceAmount(amount);if(cents===null){setError('Informe um valor positivo com até duas casas decimais.');return;}setError('');setRequest(old=>({movement:selected!.id,amount:String(cents),epoch:(old?.epoch||0)+1}));}}>Conferir vínculo</Button>{error&&<p role="alert">{error}</p>}{data&&request&&<section aria-label="Prévia do pagamento"><p>Proposto: {money(data.amount_cents)} · pago após o vínculo: {money(data.effects.paid_after_cents)} · restante: {money(data.effects.open_after_cents)}</p><p>{data.effects.create_payable?'Será criada a obrigação vinculada ao adiantamento.':'A obrigação existente será preservada.'} {data.effects.approve_payable?'A confirmação também aprova a obrigação conferida.':''}</p>{data.blockers.map(code=><p role="alert" key={code}>{labels[code]||'Este vínculo exige regularização antes da confirmação.'}</p>)}</section>}
 <EmployeeAdvancePaymentConfirmation tenant={tenant} actor={actor} advance={advance} preview={request?data:undefined} refresh={refresh}/><EmployeeAdvancePaymentPages tenant={tenant} actor={actor} advance={advance} kind="history"/>
 </section>;
}
