import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {readEmployeeAdvanceAction,sendEmployeeAdvanceAction} from '@/lib/financial/employeeAdvanceActionClient';
import {createEmployeeAdvanceActionOutbox,lockEmployeeAdvanceAction,pendingEmployeeAdvanceAction,employeeAdvanceActionKey,type PendingEmployeeAdvanceAction} from '@/lib/financial/employeeAdvanceActionOutbox';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
type Props={tenant:string;actor:string;advance:string;action:'approve'|'cancel'};
export function EmployeeAdvanceActionDialog(props:Props&{open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent><DialogHeader><DialogTitle>{props.action==='approve'?'Aprovar adiantamento':'Cancelar adiantamento'}</DialogTitle><DialogDescription>Confira a situação e registre o motivo. Esta ação não realiza pagamentos.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><EmployeeAdvanceActionWorkspace key={`${props.tenant}:${props.actor}:${props.advance}:${props.action}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
export function EmployeeAdvanceActionWorkspace({tenant,actor,advance,action}:Props){
 const cache=useQueryClient(),live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingEmployeeAdvanceAction|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[ack,setAck]=useState<string|null>(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[rejected,setRejected]=useState<string|null>(null);
 const sync=()=>{try{setPending(pendingEmployeeAdvanceAction(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createEmployeeAdvanceActionOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na empresa e sessão originais.');},lock:lockEmployeeAdvanceAction,send:sendEmployeeAdvanceAction}));
 useEffect(()=>{live.current.active=true;syncRef.current();const listen=(e:StorageEvent)=>{if(e.key===null||e.key===employeeAdvanceActionKey(tenant,actor))syncRef.current();};window.addEventListener('storage',listen);return()=>{live.current.active=false;window.removeEventListener('storage',listen);};},[tenant,actor]);
 const query=useQuery({queryKey:['finance-advance-action-preview',tenant,actor,advance,action],queryFn:()=>readEmployeeAdvanceAction(tenant,actor,advance,action),retry:false,staleTime:0,refetchOnMount:'always'});
 const data=query.isFetchedAfterMount&&!query.isFetching&&!query.isError?query.data:undefined,fresh=!!data?.can_execute&&data.revision!==rejected;
 if(corrupt)return <section className="space-y-3" aria-label="Conferência da situação do adiantamento"><div role="alert"><p>O pedido salvo está inconsistente. Preserve os dados antes de continuar.</p><Button variant="outline" onClick={()=>{try{localStorage.removeItem(employeeAdvanceActionKey(tenant,actor));setPending(null);setCorrupt(false);setError('');}catch{setError('Não foi possível descartar o pedido incompatível.');}}}>Descartar pedido incompatível</Button></div>{error&&<p role="alert">{error}</p>}</section>;
 async function refresh(){await Promise.all(['employee_advances','finance-advance-action-preview','finance-advance-payment-preview','finance-advance-payment-history','payables','finance-payable-portfolio','finance-audit'].map(k=>cache.invalidateQueries({queryKey:[k,tenant]},{throwOnError:true})));}
 async function execute(recover:boolean){if(busy||corrupt||confirmed||!recover&&(!fresh||!data||ack!==data.revision||reason.trim().length<10))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{advance_id:advance,action,expected_revision:data!.revision,reason,expected:data!.effects});setConfirmed(`${result.action==='approve'?'Adiantamento aprovado':'Adiantamento cancelado'}. Referência ${result.advance_id}; pedido ${result.request_id}. Nenhum dinheiro movimentado.`);setAck(null);try{await refresh();}catch{setError('A ação foi registrada, mas as consultas não foram atualizadas. Atualize antes de continuar.');}}catch(e){setRejected(data?.revision??null);setAck(null);setError(e instanceof Error?e.message:'Não foi possível confirmar. Preserve e recupere o pedido pendente.');}finally{setBusy(false);}}
 return <section className="space-y-3" aria-label="Conferência da situação do adiantamento">{query.isFetching&&<p role="status">Conferindo situação atual…</p>}{query.isError&&<p role="alert">Não foi possível conferir este adiantamento.</p>}<Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setAck(null);setRejected(null);void query.refetch();}}>Atualizar conferência</Button>{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados antes de continuar.</p>:pending?<><p>Pedido pendente {pending.payload.request_id} · adiantamento {pending.payload.advance_id} · {pending.payload.action==='approve'?'aprovar':'cancelar'}.</p><p>Motivo: {pending.payload.reason}</p><Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido original</Button></>:data?<><p>{data.advance.employee_name} · situação {data.advance.status}</p><p>Valor {data.advance.amount_cents===null?'A revisar':formatFinanceCents(data.advance.amount_cents)} · entregue {data.advance.paid_cents===null?'A revisar':formatFinanceCents(data.advance.paid_cents)}</p>{!fresh?<p role="alert">A ação não está disponível nesta conferência. Revise a origem, os pagamentos e os vínculos com a folha antes de continuar.</p>:<><label className="block">Motivo<textarea maxLength={2000} disabled={busy} value={reason} onChange={e=>{setReason(e.target.value);setAck(null);}}/></label><label className="block"><input type="checkbox" disabled={busy} checked={ack===data.revision} onChange={e=>setAck(e.target.checked?data.revision:null)}/> Conferi o funcionário, o valor e a ação proposta.</label><Button disabled={busy||ack!==data.revision||reason.trim().length<10} onClick={()=>void execute(false)}>Confirmar {action==='approve'?'aprovação':'cancelamento'}</Button></>}</>:null}</section>;
}
