import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {type EmployeeAdvancePaymentCommand,type EmployeeAdvancePaymentPreview} from '@/lib/financial/employeeAdvancePaymentContract';
import {sendEmployeeAdvancePayment} from '@/lib/financial/employeeAdvancePaymentClient';
import {createEmployeeAdvancePaymentOutbox,lockEmployeeAdvancePayment,pendingEmployeeAdvancePayment,employeeAdvancePaymentKey,type PendingEmployeeAdvancePayment} from '@/lib/financial/employeeAdvancePaymentOutbox';
export function EmployeeAdvancePaymentConfirmation({tenant,actor,advance,preview,refresh}:{tenant:string;actor:string;advance:string;preview:EmployeeAdvancePaymentPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingEmployeeAdvancePayment|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[method,setMethod]=useState<EmployeeAdvancePaymentCommand['method']>('pix'),[ack,setAck]=useState<string|null>(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[rejected,setRejected]=useState<string|null>(null);
 const sync=()=>{try{setPending(pendingEmployeeAdvancePayment(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createEmployeeAdvancePaymentOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||t!==live.current.tenant||a!==live.current.actor)throw Error('Retome o pedido na empresa e sessão originais.');},lock:lockEmployeeAdvancePayment,send:sendEmployeeAdvancePayment}));
 useEffect(()=>{live.current.active=true;syncRef.current();const listen=(event:StorageEvent)=>{if(event.key===null||event.key===employeeAdvancePaymentKey(tenant,actor))syncRef.current();};window.addEventListener('storage',listen);return()=>{live.current.active=false;window.removeEventListener('storage',listen);};},[tenant,actor]);
 const fresh=!!preview?.can_execute&&preview.eligible&&preview.can_pay&&preview.tenant_id===tenant&&preview.actor_id===actor&&preview.advance_id===advance&&preview.revision!==rejected;
 if(corrupt)return <section aria-label="Confirmar pagamento do adiantamento" className="rounded border p-3 space-y-2"><div role="alert"><p>O pedido salvo está inconsistente. Preserve os dados; novos pagamentos estão bloqueados.</p><Button variant="outline" onClick={()=>{try{localStorage.removeItem(employeeAdvancePaymentKey(tenant,actor));setPending(null);setCorrupt(false);setError('');}catch{setError('Não foi possível descartar o pedido incompatível.');}}}>Descartar pedido incompatível</Button></div>{error&&<p role="alert">{error}</p>}</section>;
 async function execute(recover:boolean){if(busy||confirmed||corrupt||(!recover&&(!fresh||!preview||ack!==preview.revision||reason.trim().length<10)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{advance_id:advance,movement_id:preview!.movement_id!,amount_cents:preview!.amount_cents!,expected_revision:preview!.revision,method,reason,expected:{paid_cents:preview!.effects.paid_after_cents!,open_cents:preview!.effects.open_after_cents!}});setConfirmed(`Pagamento vinculado: ${formatFinanceCents(result.amount_cents)}. Adiantamento ${result.advance_id}; pedido ${result.request_id}. Nenhum novo dinheiro ou gasto foi criado.`);setAck(null);try{await refresh();}catch{setError('O vínculo foi confirmado, mas a consulta não foi atualizada. Atualize a tela; não envie outro pedido.');}}catch{setRejected(preview?.revision||null);setAck(null);setError('O pagamento não foi confirmado. Recupere o pedido preservado, se houver; caso contrário, confira uma nova prévia antes de tentar novamente.');}finally{setBusy(false);}}
 return <section aria-label="Confirmar pagamento do adiantamento" className="rounded border p-3 space-y-2">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novos pagamentos estão bloqueados.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · autor {pending.actorId}</p><p>Adiantamento {pending.payload.advance_id} · saída {pending.payload.movement_id} · valor {formatFinanceCents(pending.payload.amount_cents)}</p><p>Motivo: {pending.payload.reason}</p>{pending.payload.advance_id!==advance&&<p role="alert">Este pedido pertence a outro adiantamento. A recuperação verifica somente o pedido original.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pagamento preservado</Button></>:fresh?<><label>Método da saída<select value={method} disabled={busy} onChange={e=>{setMethod(e.target.value as EmployeeAdvancePaymentCommand['method']);setAck(null);}}>{[['pix','Pix'],['boleto','Boleto'],['ted','TED'],['doc','DOC'],['dinheiro','Dinheiro'],['cartao','Cartão'],['debito_automatico','Débito automático'],['other','Outro']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Motivo do vínculo<textarea value={reason} maxLength={2000} disabled={busy} onChange={e=>{setReason(e.target.value);setAck(null);}}/></label><label><input type="checkbox" checked={ack===preview?.revision} disabled={busy||reason.trim().length<10} onChange={e=>setAck(e.target.checked?preview!.revision:null)}/> Conferi funcionário, conta, saída e valor. Confirmo somente o vínculo ao dinheiro já registrado.</label><Button disabled={busy||ack!==preview?.revision||reason.trim().length<10} onClick={()=>void execute(false)}>Confirmar vínculo do pagamento</Button></>:<p>A confirmação está indisponível. Confira uma prévia atual e elegível.</p>}</section>;
}
