import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {readEmployeeAdvancePaymentPage,EmployeeAdvancePaymentChangedError} from '@/lib/financial/employeeAdvancePaymentClient';
export function EmployeeAdvancePaymentPages({tenant,actor,advance,kind,onSelect,onInvalidate}:{tenant:string;actor:string;advance:string;kind:'options'|'history';onSelect?:(id:string,label:string)=>void;onInvalidate?:()=>void}){
 const [text,setText]=useState(''),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[paging,setPaging]=useState({offset:0,revision:null as string|null,epoch:0});
 const query=useQuery({queryKey:[`finance-advance-payment-${kind}`,tenant,actor,advance,search,paging],queryFn:()=>readEmployeeAdvancePaymentPage(tenant,actor,advance,kind,paging.offset,paging.revision,search),retry:false,staleTime:0,refetchOnMount:'always'});
 useEffect(()=>{if(query.isFetching||query.isError)onInvalidate?.();},[query.isFetching,query.isError,onInvalidate]);
 useEffect(()=>{if(query.error instanceof EmployeeAdvancePaymentChangedError){setNotice(query.error.message);setPaging(p=>({offset:0,revision:null,epoch:p.epoch+1}));}},[query.error]);
 const data=query.isFetchedAfterMount&&!query.isFetching&&!query.isError?query.data:undefined;
 return <section aria-label={kind==='options'?'Saídas para o adiantamento':'Histórico de pagamentos do adiantamento'} className="space-y-2">{kind==='options'&&<><label>Buscar saída registrada<Input value={text} onChange={e=>setText(e.target.value)}/></label><Button onClick={()=>{onInvalidate?.();setSearch(text);setPaging(p=>({offset:0,revision:null,epoch:p.epoch+1}));}}>Buscar saídas</Button></>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando {kind==='options'?'saídas disponíveis':'histórico'}…</p>}{query.isError&&<><p role="alert">A consulta está indisponível. Nenhuma linha anterior pode ser selecionada.</p><Button onClick={()=>void query.refetch()}>Tentar consulta novamente</Button></>}{data&&<><p>{data.total} {kind==='options'?'saídas disponíveis':'pagamentos deste fluxo'} em todas as páginas.</p>{data.rows.map(row=>'id' in row?<article key={row.id} className="rounded border p-2"><p>{row.beneficiary_name} · {row.beneficiary_document||'Documento não informado'} · {row.account_name||'Conta sem nome'} · {row.occurred_on}</p><p>{row.description} · registrado {formatFinanceCents(row.amount_cents)} · disponível {formatFinanceCents(row.available_cents)}</p><details><summary>Identificação da saída</summary>{row.id} · conta {row.bank_account_id}</details><Button onClick={()=>onSelect?.(row.id,`${row.beneficiary_name} · ${row.account_name||'Conta sem nome'} · ${row.occurred_on} · disponível ${formatFinanceCents(row.available_cents)}`)}>Selecionar saída</Button></article>:<article key={row.request_id} className="rounded border p-2"><p>Pagamento vinculado: {formatFinanceCents(row.result.amount_cents)} · {row.created_at}</p><p>Autor: {row.actor_name||row.actor_id} · pedido: {row.request_id}</p><p>Motivo: {row.reason}</p><p>Saída: {row.result.movement_id} · pago acumulado {formatFinanceCents(row.result.paid_cents)} · restante após este pedido {formatFinanceCents(row.result.open_cents)}</p></article>)}<Button disabled={paging.offset===0} onClick={()=>{onInvalidate?.();setPaging({...paging,offset:Math.max(0,paging.offset-30),revision:data.revision});}}>Página anterior</Button><Button disabled={data.next_offset===null} onClick={()=>{onInvalidate?.();setPaging({...paging,offset:data.next_offset!,revision:data.revision});}}>Próxima página</Button></>}</section>;
}
