import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {expenseCategories,type ExpenseBatchDraft} from '@/lib/financial/expenseBatchContract';
import {previewExpensePaste,type PastedExpense} from '@/lib/financial/expenseBatchPaste';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
export function ExpenseBatchPaste({context,existingCount,disabled,onAppend}:{context:ExpenseBatchDraft['context'];existingCount:number;disabled:boolean;onAppend:(rows:PastedExpense[],context:ExpenseBatchDraft['context'])=>void}){
 const [open,setOpen]=useState(false),[text,setText]=useState(''),[review,setReview]=useState<{text:string;context:ExpenseBatchDraft['context'];count:number;result:ReturnType<typeof previewExpensePaste>}|null>(null),[notice,setNotice]=useState('');const consumed=useRef(false);
 const shown=review&&review.text===text&&review.context===context&&review.count===existingCount?review.result:null;
 function check(){consumed.current=false;setNotice('');setReview({text,context,count:existingCount,result:previewExpensePaste(text,context,existingCount)});}
 function append(){if(disabled||consumed.current||!shown||shown.errors.length||shown.rows.some(r=>r.errors.length))return;try{consumed.current=true;onAppend(shown.rows.map(r=>r.value!),context);setNotice(`${shown.count} gastos adicionados ao rascunho. Nenhum lote foi enviado.`);setReview(null);setText('');}catch(error){consumed.current=false;setNotice(error instanceof Error?error.message:'Não foi possível incluir as linhas.');}}
 return <section className="space-y-2 rounded border p-3" aria-label="Colagem de planilha"><Button type="button" variant="outline" disabled={disabled} onClick={()=>setOpen(v=>!v)}>{open?'Fechar colagem':'Colar linhas de planilha'}</Button>{notice&&<p role="status">{notice}</p>}{open&&<><p>Copie as células da planilha nesta ordem: Categoria, Descrição, Valor, Data; opcionalmente Fornecedor, Documento e Vencimento. Cabeçalho opcional. Exemplo de valor: 1.234,56; data: 11/09/2026.</p><p>As linhas existentes serão preservadas. Comprovantes, entrega, cadastro do favorecido e vínculos de pagamento continuam sujeitos à conferência; a colagem não os cria.</p><details><summary>Categorias aceitas</summary><p>{Object.values(expenseCategories).join(' · ')}</p></details><label className="block">Células copiadas<textarea className="block min-h-32 w-full rounded border bg-background p-2" value={text} disabled={disabled} onChange={e=>{setText(e.target.value);setReview(null);setNotice('');}}/></label><Button type="button" disabled={disabled||!text.trim()} onClick={check}>Conferir colagem</Button>{shown&&<><p>{shown.count} linhas coladas · {existingCount} gastos existentes · total das linhas válidas: {formatFinanceCents(shown.totalCents)}</p>{shown.errors.map(e=><p role="alert" key={e}>{e}</p>)}<div className="max-h-80 overflow-auto"><table className="w-full text-sm"><caption>Prévia da colagem</caption><thead><tr><th>Linha</th><th>Categoria / descrição</th><th>Valor / data</th><th>Fornecedor / documento / vencimento</th><th>Conferência</th></tr></thead><tbody>{shown.rows.map(r=><tr key={r.line}><td>{r.line}</td><td>{r.value?`${expenseCategories[r.value.category]} · ${r.value.description}`:'Linha inválida'}</td><td>{r.value&&`${r.value.amount} · ${r.value.date}`}</td><td>{r.value&&[r.value.supplierName||'Fornecedor a conferir',r.value.document,r.value.dueDate].filter(Boolean).join(' · ')}</td><td>{r.errors.length?r.errors.join(' '):'Pronta para o rascunho; comprovante a conferir'}</td></tr>)}</tbody></table></div><Button type="button" disabled={disabled||!!shown.errors.length||shown.rows.some(r=>r.errors.length>0)} onClick={append}>Adicionar linhas ao rascunho</Button></>}</>}</section>;
}
