import {useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {expenseCancellationCommandSchema,expenseCancellationLabels,type ExpenseCancellationCommand} from '@/lib/financial/expenseCancellationContract';
import {readExpenseCancellation,submitExpenseCancellation,ExpenseCancellationRejectedError} from '@/lib/financial/expenseCancellationClient';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
type Props={tenant:string;actor:string;expenseId:string};
export function ExpenseCancellationReview(props:Props){const [open,setOpen]=useState(false);return <><Button variant="outline" size="sm" onClick={()=>setOpen(!open)}>{open?'Recolher revisão do gasto':'Revisar cancelamento / histórico do gasto'}</Button>{open&&<FinanceAccessBoundary><ExpenseCancellationWorkspace key={`${props.tenant}:${props.actor}:${props.expenseId}`} {...props}/></FinanceAccessBoundary>}</>;}
export function ExpenseCancellationWorkspace({tenant,actor,expenseId}:Props){
 const key=`finance-expense-cancellation:${tenant}:${actor}:${expenseId}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),command=expenseCancellationCommandSchema.parse(saved.command);if(saved.actor!==actor||command.tenant_id!==tenant||command.expense_id!==expenseId)throw new Error();return {command};}catch{return {error:'Não foi possível recuperar o pedido preservado. Novos cancelamentos estão bloqueados; confira o histórico.'};}});
 const [pending,setPending]=useState<ExpenseCancellationCommand|undefined>(restored.command),[review,setReview]=useState<ExpenseCancellationCommand>(),[reason,setReason]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState('');
 const sending=useRef(false),cache=useQueryClient();
 const query=useQuery({queryKey:['finance-expense-cancellation',tenant,actor,expenseId],queryFn:()=>readExpenseCancellation(tenant,expenseId),retry:false}),data=query.isFetching||query.isError?undefined:query.data;
 const eligible=!!data?.eligible&&data.can_execute&&!restored.error;
 const current=eligible&&accepted&&review?.revision===data?.revision&&review?.reason===reason.trim();
 function prepare(){if(!eligible||!accepted)return;const parsed=expenseCancellationCommandSchema.safeParse({version:1,tenant_id:tenant,request_id:crypto.randomUUID(),expense_id:expenseId,revision:data!.revision,reason});if(parsed.success)setReview(parsed.data);}
 async function submit(){if(sending.current||restored.error)return;const command=pending||review;if(!command||(!pending&&!current))return;const uncertain=!!pending;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,command}));}catch{setError('Não foi possível preservar o pedido. Nenhum cancelamento foi enviado.');return;}setPending(command);}sending.current=true;setBusy(true);setError('');try{await submitExpenseCancellation(command);sessionStorage.removeItem(key);setPending(undefined);setReview(undefined);setReason('');setAccepted(false);setNotice('Cancelamento confirmado. O gasto original e sua autoria permanecem no histórico. Nenhum dinheiro foi alterado.');for(const prefix of ['finance-expense-cancellation','finance-expenses','finance-recorded-costs','finance-recorded-cost-summary','payables','driver_settlements','driver_settlement','finance-settlement-expense-context','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});void invalidateAccountReview(cache,tenant);}catch(e){if(e instanceof ExpenseCancellationRejectedError&&!uncertain){try{sessionStorage.removeItem(key);setPending(undefined);setReview(undefined);setError(expenseCancellationLabels[e.message]||'O cancelamento foi recusado. Atualize os dados e confira os impedimentos antes de revisar novamente.');void query.refetch();}catch{setError('O pedido foi recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}else setError('Não foi possível confirmar a resposta. O pedido original foi preservado; retome para verificar seu resultado sem criar outro pedido.');}finally{sending.current=false;setBusy(false);}}
 return <section className="space-y-3 rounded border p-3 text-sm" aria-label="Cancelamento auditado do gasto"><h3 className="font-semibold">Cancelamento auditado do gasto em lote</h3><p>O cancelamento é definitivo. Preserva o registro original e retira o gasto dos indicadores ativos. Não executa transferência, estorno ou novo pagamento.</p>
 <Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar conferência do gasto</Button>
 {query.isFetching&&<p role="status">Consultando gasto e dependências…</p>}{query.isError&&<p role="alert">Não foi possível consultar o gasto. Atualize antes de uma nova decisão.</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {data&&<><p>{data.snapshot.expense.description} · gasto {expenseId} · lote {data.snapshot.expense.batch_id}</p><p>Data: {data.snapshot.expense.occurred_on} · título: {data.snapshot.payable?.id||'Não identificado'}</p>
 {data.cancellation?<article className="rounded border border-amber-600 p-3"><h4>Cancelado — excluído dos indicadores ativos</h4><p>Cancelamento manual por {data.cancellation.actor_name} ({data.cancellation.actor_id}) · {data.cancellation.created_at}</p><p>Motivo: {data.cancellation.reason}</p><p>Registro: {data.cancellation.id}</p></article>:<><p>Custo a retirar dos indicadores: {data.effects.cost_removed_cents===null?'Não determinado':formatFinanceCents(data.effects.cost_removed_cents)}</p><p>Obrigação a cancelar: {data.effects.obligation_cancelled_cents===null?'Não determinada':formatFinanceCents(data.effects.obligation_cancelled_cents)}</p><p>Dinheiro: sem alteração.</p>{data.issue&&<p role="alert">{expenseCancellationLabels[data.issue]||'Há uma dependência que exige revisão específica. Este gasto não pode ser cancelado neste fluxo.'}</p>}{!data.can_execute&&<p>Seu acesso permite consultar, mas não executar este cancelamento.</p>}</>}
 </>}
 {data?.issue&&<details><summary>Referências para conferência dos impedimentos</summary>{Object.entries({payments:'Pagamentos do título',allocations:'Utilizações de envios',payable_links:'Vínculos do título',legacy_links:'Associações antigas',maintenance_claims:'Associações de manutenção',labor_history:'Histórico de mão de obra',part_history:'Histórico de peças',stock_history:'Histórico de estoque',settlements:'Acertos relacionados',payroll_items:'Itens de folha',obligations:'Obrigações relacionadas',closure_dependencies:'Dependências de fechamento'}).map(([field,label])=>{const rows=data.snapshot[field];if(!Array.isArray(rows)||!rows.length)return null;return <div key={field}><h4>{label}</h4><ul>{rows.map((row,index)=><li key={index}>{row&&typeof row==='object'&&typeof row.id==='string'?row.id:'Referência preservada na conferência'}</li>)}</ul></div>;})}</details>}
 {pending?<><p>Pedido original {pending.request_id} · gasto {pending.expense_id}</p><p>Motivo preservado: {pending.reason}</p><Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar cancelamento do gasto</Button></>:eligible&&<><label>Motivo do cancelamento<Textarea maxLength={2000} disabled={busy||!!review} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex gap-2"><input type="checkbox" checked={accepted} disabled={busy||!!review} onChange={e=>setAccepted(e.target.checked)}/>Conferi o gasto e o título. Entendo que o cancelamento é definitivo e preserva o original no histórico.</label>{review?<><p>Revisão final: cancelar somente o gasto {expenseId} e a obrigação indicada acima. Motivo: {review.reason}</p>{!current&&<p role="alert">A conferência mudou. Atualize e revise novamente.</p>}<Button disabled={busy||!current} onClick={()=>void submit()}>Confirmar cancelamento do gasto</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão</Button></>:<Button disabled={busy||!accepted||reason.trim().length<10} onClick={prepare}>Revisar cancelamento do gasto</Button>}</>}
 </section>;
}
