import {movementUseError} from '@/lib/financial/movementUseErrors';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {legacyPayableIssueLabels,legacyPayablePendingSchema,type LegacyPayablePending} from '@/lib/financial/legacyPayableAssociationContract';
import {readLegacyPayableAssociation,submitLegacyPayableAssociation,LegacyPayableRejectedError} from '@/lib/financial/legacyPayableAssociationClient';
type Props={tenant:string;actor:string;payment:string;onRecorded?:()=>void};
export function LegacyPayableAssociation(props:Props){const [open,setOpen]=useState(false);return <><Button size="sm" variant="outline" onClick={()=>setOpen(true)}>Associar saída existente</Button>{open&&<FinanceAccessBoundary><Dialog open onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Associação do pagamento antigo</DialogTitle><DialogDescription>Vincule o pagamento existente a uma saída já registrada. Nenhum dinheiro ou pagamento adicional será criado.</DialogDescription></DialogHeader><LegacyPayableAssociationWorkspace key={`${props.tenant}:${props.actor}:${props.payment}`} {...props}/></DialogContent></Dialog></FinanceAccessBoundary>}</>;}
export function LegacyPayableAssociationWorkspace({tenant,actor,payment,onRecorded}:Props){
 const key=`finance-legacy-payable-association:${tenant}:${actor}:${payment}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=legacyPayablePendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.payment!==payment||pending.command.tenant_id!==tenant||(pending.kind==='associate'&&pending.command.payment_id!==payment))throw new Error();return {pending};}catch{return {error:'Não foi possível recuperar o pedido. Novas associações e correções estão bloqueadas; confira o histórico.'};}});
 const [pending,setPending]=useState<LegacyPayablePending|undefined>(restored.pending),[review,setReview]=useState<LegacyPayablePending>(),[choice,setChoice]=useState(''),[reverse,setReverse]=useState(false),[reason,setReason]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState('');
 const alive=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const [reviewedContext,setReviewedContext]=useState('');
 const query=useQuery({queryKey:['finance-legacy-payable-association',tenant,actor,payment,page],queryFn:()=>readLegacyPayableAssociation(tenant,payment,page),retry:false});
 const data=query.isError||query.isFetching?undefined:query.data,selected=data?.rows.find(row=>row.id===choice);
 const canAssociate=!!data?.eligible&&!data.active_link&&!!selected,canReverse=!!data?.active_link;
 const contextFingerprint=JSON.stringify({payment:data?.payment,row:selected,active:data?.active_link});
 const reviewCurrent=!!review&&reviewedContext===contextFingerprint&&(review.kind==='associate'?canAssociate&&review.command.movement_id===choice&&review.command.revision===data?.revision:canReverse&&review.command.link_id===data?.active_link);
 function prepare(){if(restored.error||(reverse?!canReverse:!canAssociate))return;const parsed=legacyPayablePendingSchema.safeParse(reverse?{kind:'reverse',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),link_id:data!.active_link,reason}}:{kind:'associate',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),payment_id:payment,movement_id:choice,revision:data!.revision,reason}});if(parsed.success){setReview(parsed.data);setReviewedContext(contextFingerprint);}}
 async function submit(){if(sending.current||restored.error)return;const original=pending||review;if(!original||(!pending&&!reviewCurrent))return;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,payment,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma associação foi enviada.');return;}setPending(original);}sending.current=true;setBusy(true);setError('');
  try{const result=await submitLegacyPayableAssociation(original);if(result.payment_id!==payment)throw new Error('Resposta fora do pagamento.');sessionStorage.removeItem(key);void invalidateAccountReview(cache,tenant);for(const prefix of ['finance-legacy-payable-association','finance-legacy-inventory','finance-legacy-integrity-inventory','payables_payments','payables','finance-movements','finance-payable-options','finance-options','finance-manual-expense-options','finance-audit','finance-account-period'])void cache.invalidateQueries({queryKey:[prefix]});onRecorded?.();if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setReverse(false);setReason('');setNotice(original.kind==='associate'?'Associação confirmada. O pagamento e o dinheiro permanecem os mesmos.':'Associação desfeita. O pagamento foi preservado e o título não foi reaberto.');}}
  catch(e){if(e instanceof LegacyPayableRejectedError&&!pending){try{sessionStorage.removeItem(key);if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setError(`O vínculo foi recusado. ${movementUseError(e)||legacyPayableIssueLabels[e.message]||'Atualize e confira conta, favorecido, data e capacidade da saída.'} O pagamento antigo permanece preservado.`);}void query.refetch();}catch{if(alive.current)setError('Pedido recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}else if(alive.current)setError('Não foi possível confirmar a resposta. O pedido original foi preservado para retomada.');}
  finally{sending.current=false;if(alive.current)setBusy(false);}
 }
 return <div className="space-y-3 text-sm"><p>A associação identifica a saída do pagamento antigo. Desfazer este vínculo não apaga o pagamento, não reabre o título e não altera o dinheiro. A conciliação bancária continua separada.</p><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar associações</Button>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando pagamento e saídas…</p>}{query.isError&&<p role="alert">Não foi possível consultar o pagamento. Atualize antes de fazer uma nova associação.</p>}
 {data&&<><p>Pagamento {data.payment.id} · título {data.payment.payable_id}</p><p>{data.payment.supplier_name||'Favorecido não identificado'} · {data.payment.account_name||'Conta não identificada'} · {data.payment.paid_on||'Data não identificada'} · {data.payment.amount_cents===null?'Valor a revisar':formatFinanceCents(data.payment.amount_cents)}</p>
 {!data.eligible&&!data.active_link&&<p role="alert">{movementUseError({message:data.issue})||legacyPayableIssueLabels[data.issue||'']||'Este pagamento precisa de revisão antes de ser associado. Confira os dados originais, os vínculos anteriores e a identificação da conta e do favorecido.'}</p>}
 <section aria-label="Histórico permanente das associações"><h3>Histórico de associações manuais</h3>{data.history.length===0?<p>Nenhuma associação nesta página.</p>:data.history.map(item=><article key={item.id} className="rounded border border-amber-600 p-2"><p>Associação manual · {item.reversal?'Desfeita':'Ativa'} · {formatFinanceCents(item.amount_cents)}</p><p>Saída: {item.movement_id}</p><p>Por {item.actor_name} ({item.actor_id}) · {item.created_at}</p><p>Motivo: {item.reason}</p>{item.reversal&&<><p>Desfeita por {item.reversal.actor_name} ({item.reversal.actor_id}) · {item.reversal.created_at}</p><p>Motivo da correção: {item.reversal.reason}</p><p>Pagamento preservado; esta correção não reabre o título.</p></>}</article>)}</section>
 {!pending&&data.active_link&&<Button variant="outline" disabled={busy||!!restored.error} onClick={()=>{setReverse(true);setReview(undefined);setReason('');}}>Desfazer associação ativa</Button>}
 {!pending&&!reverse&&!data.active_link&&data.eligible&&<><fieldset disabled={busy||!!review||!!restored.error}><legend>Saídas elegíveis para o pagamento integral</legend>{data.rows.map(row=><label className="flex gap-2 border rounded p-2" key={row.id}><input type="radio" name="legacy-payable-movement" checked={choice===row.id} onChange={()=>setChoice(row.id)}/><span>{row.description} · {row.account_name} · {row.occurred_on}<br/>{row.beneficiary_name} · saída {row.id}<br/>Total {formatFinanceCents(row.amount_cents)} · disponível {formatFinanceCents(row.remaining_cents)}{row.bank_reference&&<> · referência {row.bank_reference}</>}</span></label>)}</fieldset>{data.total===0&&<p>Nenhuma saída elegível. Revise os registros existentes e a origem do pagamento. A ausência de candidata não significa que é necessário pagar novamente.</p>}</>}
 <div className="flex gap-2"><Button variant="outline" disabled={page===1||busy||!!review} onClick={()=>{setPage(page-1);setChoice('');}}>Anterior</Button><span>Página {page}</span><Button variant="outline" disabled={page*20>=Math.max(data.total,data.history_total)||busy||!!review} onClick={()=>{setPage(page+1);setChoice('');}}>Próxima</Button></div>
 </>}
 {pending?<><p>Pedido original: {pending.command.request_id}</p><p>{pending.kind==='associate'?`Saída preservada: ${pending.command.movement_id}`:`Associação a corrigir: ${pending.command.link_id}`}</p><p>Motivo preservado: {pending.command.reason}</p><Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar associação original</Button></>:((reverse&&canReverse)||(!reverse&&canAssociate))&&<><label>Motivo da associação ou correção<Textarea maxLength={2000} value={reason} disabled={!!review} onChange={e=>setReason(e.target.value)}/></label>{review?<><p>Revisão final: {review.kind==='associate'?`associar este pagamento à saída ${review.command.movement_id}`:`desfazer apenas a associação ${review.command.link_id}`}. Nenhum novo pagamento será criado.</p>{!reviewCurrent&&<p role="alert">O contexto mudou. Volte à revisão antes de confirmar.</p>}<Button disabled={busy||!reviewCurrent||!!restored.error} onClick={()=>void submit()}>Confirmar associação ou correção</Button><Button variant="outline" onClick={()=>setReview(undefined)}>Voltar à revisão</Button></>:<Button disabled={reason.trim().length<10||!!restored.error} onClick={prepare}>Revisar associação ou correção</Button>}{reverse&&<Button variant="outline" disabled={busy} onClick={()=>{setReverse(false);setReview(undefined);}}>Cancelar correção</Button>}</>}
 </div>;
}
