import {PaidMovementVoidEvidence} from './PaidMovementVoidEvidence';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {legacyCutCommandSchema,legacyCutIssueLabels,type LegacyCutCommand} from '@/lib/financial/legacyCutReviewContract';
import {readLegacyCutReview,submitLegacyCutReview,LegacyCutRejectedError} from '@/lib/financial/legacyCutReviewClient';
type Props={tenant:string;actor:string;account:string;from:string;to:string};
export function LegacyCutReview(props:Props){const [open,setOpen]=useState(false);return <section className="border rounded p-3 space-y-3" aria-label="Revisão do corte histórico"><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Ocultar revisão do corte':'Revisar corte histórico de dinheiro'}</Button>{open&&<LegacyCutReviewWorkspace key={`${props.tenant}:${props.actor}:${props.account}:${props.from}:${props.to}`} {...props}/>}</section>;}
export function LegacyCutReviewWorkspace({tenant,actor,account,from,to}:Props){
 const key=`finance-legacy-cut-review:${tenant}:${actor}:${account}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),command=legacyCutCommandSchema.parse(saved.command);if(saved.actor!==actor||command.tenant_id!==tenant||command.account_id!==account)throw new Error();return {command};}catch{return {error:'Não foi possível recuperar o pedido de corte. Novas revisões estão bloqueadas; consulte o histórico.'};}});
 const [pending,setPending]=useState<LegacyCutCommand|undefined>(restored.command),[review,setReview]=useState<LegacyCutCommand>(),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState('');const sending=useRef(false),live=useRef(true),cache=useQueryClient();useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const query=useQuery({queryKey:['finance-legacy-cut-review',tenant,actor,account,from,to],queryFn:()=>readLegacyCutReview(tenant,account,from,to),retry:false}),data=query.isFetching||query.isError?undefined:query.data;
 const mayReview=!!data?.can_review&&!data.approved&&!data.blockers.length,reviewCurrent=!!review&&mayReview&&data?.revision===review.revision&&checked;
 function prepare(){if(!mayReview||!checked||restored.error)return;const parsed=legacyCutCommandSchema.safeParse({version:1,tenant_id:tenant,request_id:crypto.randomUUID(),account_id:account,from,to,revision:data!.revision,reason,sources_reviewed:true});if(parsed.success)setReview(parsed.data);}
 async function submit(){const original=pending||review;if(!original||sending.current||restored.error||(!pending&&!reviewCurrent))return;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,command:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma revisão foi enviada.');return;}setPending(original);}sending.current=true;setBusy(true);setError('');try{await submitLegacyCutReview(original);sessionStorage.removeItem(key);for(const prefix of ['finance-cash-period-close-preview','finance-legacy-cut-review','finance-account-period-close-preview','finance-account-period-close-history','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});if(live.current){setPending(undefined);setReview(undefined);setChecked(false);setReason('');setNotice('Revisão do corte registrada com autoria. Isso não fecha o período e não cria dinheiro.');}}catch(cause){if(cause instanceof LegacyCutRejectedError&&!pending){try{sessionStorage.removeItem(key);if(live.current){setPending(undefined);setReview(undefined);setError(legacyCutIssueLabels[cause.message]||'A revisão foi recusada. Atualize as fontes e confira seu acesso administrativo.');}void query.refetch();}catch{if(live.current)setError('Pedido recusado, mas sua recuperação local precisa ser verificada.');}}else if(live.current)setError('Resposta não confirmada. O pedido original foi preservado para retomada.');}finally{sending.current=false;if(live.current)setBusy(false);}}
 return <div className="space-y-3 text-sm"><p>Revisão das fontes monetárias históricas examinadas para esta conta e corte. Fontes sem conta ou data identificadas podem bloquear várias contas; seus valores não são distribuídos nem somados entre elas. Custos e obrigações não são somados ao dinheiro.</p><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar manifesto do corte</Button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Conferindo fontes históricas completas…</p>}{query.isError&&<p role="alert">Não foi possível consultar o corte. Nenhuma ausência de pendências foi presumida.</p>}{data&&<><p>{data.from} a {data.to} · {data.manifest.source_count} origem(ns) monetária(s) · classificador {data.manifest.classifier_version}</p><p>{data.approved?'Revisão atual aprovada':data.status==='needs_review'?'As fontes mudaram; nova revisão necessária':'Corte ainda não aprovado'}</p><section aria-label="Histórico permanente do corte"><h4>Revisões manuais preservadas</h4>{data.history.map(item=><article key={item.id} className="border border-amber-600 p-2"><p>Revisão manual {item.id} · por {item.actor_name} ({item.actor_id}) · {item.created_at}</p><p>Motivo: {item.reason}</p><p>{data.current&&data.review_id===item.id?"Corresponde às fontes atuais.":"Revisão anterior preservada, sem aprovação das fontes atuais."}</p></article>)}</section><details><summary>Tabelas examinadas, inclusive vazias</summary>{Object.entries(data.manifest.evidence).map(([table,rows])=><p key={table}>{table}: {rows.length} registro(s) examinados.</p>)}</details>
 {data.blockers.length>0&&<><p role="alert">{data.blockers.length} bloqueio(s) no corte.</p><ul className="list-disc pl-5">{data.blockers.slice((page-1)*30,page*30).map((blocker,index)=><li key={`${blocker.source_id}:${index}`}>{legacyCutIssueLabels[blocker.code]||'A origem exige resolução antes de aprovar.'} · {blocker.source_table} · {blocker.source_id}</li>)}</ul></>}
 <PaidMovementVoidEvidence events={data.manifest.evidence.finance_movement_voids} tenant={tenant}/><section aria-label="Origens do manifesto"><h4>Origens e vínculos por identificação</h4>{data.manifest.sources.slice((page-1)*30,page*30).map(source=><article className="border rounded p-2" key={`${source.source_table}:${source.source_id}`}><p>{source.source_table} · {source.source_id}</p><p>{source.classification==='exact_canonical_mapping'?'Vínculo exato com registros canônicos':source.classification==='exact_projection_alias'?'Pagamento já representado nos movimentos, sem nova saída':source.classification==='reversed_canonical_payment_projection'?'Projeção de pagamento revertida':source.classification==='integrity_failure'?'Inconsistência de integridade':'Origem precisa de resolução'} · {source.occurred_on||'Sem data válida'} · conta {source.account_id||'Não identificada'}</p><p>Valor da origem, sem soma entre fontes: {source.amount_cents===null?'Indeterminado':formatFinanceCents(source.amount_cents)}</p>{source.footprints&&source.footprints.length>0&&<><p>{source.classification==='exact_projection_alias'?'Parcelas comprovadas nesta conta e período':'Parcelas preservadas com comprovação inconsistente — não representam nova saída'}</p><ul aria-label={source.classification==='exact_projection_alias'?'Parcelas comprovadas nesta conta e período':'Parcelas preservadas com comprovação inconsistente'}>{source.footprints.map(part=><li key={`${part.payment_id}:${part.link_id}`}>{part.occurred_on||'Data não identificada'} · {part.amount_cents===null?'Indeterminado':formatFinanceCents(part.amount_cents)} · conta {part.account_id||'Não identificada'} · pagamento {part.payment_id} · movimento {part.movement_id} · vínculo {part.link_id||'Não identificado — comprovação incompleta'}</li>)}</ul></>}<details><summary>Movimentos relacionados</summary>{!source.movement_ids.length&&<p>IDs dos movimentos não identificados nesta consulta; comprovação incompleta.</p>}{source.movement_ids.map(id=><p key={id}>{id}</p>)}</details></article>)}{!data.manifest.sources.length&&<p>Nenhuma origem monetária foi identificada no manifesto examinado. Ainda é necessária revisão explícita do corte.</p>}</section>
 <div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Origens anteriores do corte</Button><span>Página {page} · até 30 origens e bloqueios</span><Button variant="outline" disabled={page*30>=Math.max(data.manifest.source_count,data.blockers.length)} onClick={()=>setPage(page+1)}>Próximas origens do corte</Button></div>{!data.can_review&&<p>A revisão do corte exige administrador autorizado. Esta consulta não concede permissão para fechar.</p>}</>}
 {pending?<><p>Pedido original {pending.request_id} · corte de {pending.from} a {pending.to} · motivo: {pending.reason}. Declaração de fontes revisadas preservada.</p><Button disabled={busy||!!restored.error||data?.can_review===false} onClick={()=>void submit()}>Retomar revisão do corte</Button></>:mayReview&&<><label className="flex gap-2"><input type="checkbox" checked={checked} disabled={!!review} onChange={event=>setChecked(event.target.checked)}/>Conferi as fontes examinadas e seus vínculos por ID para este corte histórico.</label><label>Motivo da revisão do corte<Textarea maxLength={2000} disabled={!!review} value={reason} onChange={event=>setReason(event.target.value)}/></label>{review?<><p>Confirmar revisão do corte de {review.from} a {review.to}, sem fechar o banco.</p>{!reviewCurrent&&<p role="alert">O contexto mudou. Revise novamente.</p>}<Button disabled={busy||!reviewCurrent||!!restored.error} onClick={()=>void submit()}>Confirmar revisão do corte</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão do corte</Button></>:<Button disabled={!checked||reason.trim().length<10||!!restored.error} onClick={prepare}>Revisar decisão do corte</Button>}</>}
 </div>;
}
