import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {expenseCategoryLabels,expensePaymentLabels} from '@/lib/financial/expenseReviewCommands';
import {legacyCostIssueLabels,legacyCostPendingSchema,type LegacyCostPending} from '@/lib/financial/legacyCostAssociationContract';
import {readLegacyCostAssociation,submitLegacyCostAssociation,LegacyCostRejectedError} from '@/lib/financial/legacyCostAssociationClient';
type Props={tenant:string;actor:string;expense:string;onRecorded?:()=>void};
export function LegacyCostAssociation(props:Props){const [open,setOpen]=useState(false);return <><Button size="sm" variant="outline" onClick={()=>setOpen(true)}>Associar custo existente</Button>{open&&<FinanceAccessBoundary><Dialog open onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Associação da despesa antiga</DialogTitle><DialogDescription>Identifique duas representações do mesmo gasto. Não é conciliação bancária nem registro de outro custo.</DialogDescription></DialogHeader><LegacyCostAssociationWorkspace key={`${props.tenant}:${props.actor}:${props.expense}`} {...props}/></DialogContent></Dialog></FinanceAccessBoundary>}</>;}
export function LegacyCostAssociationWorkspace({tenant,actor,expense,onRecorded}:Props){
 const key=`finance-legacy-cost-association:${tenant}:${actor}:${expense}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=legacyCostPendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.expense!==expense||pending.command.tenant_id!==tenant||(pending.kind==='associate'&&pending.command.expense_id!==expense))throw new Error();return {pending};}catch{return {error:'Não foi possível recuperar o pedido. Novas associações e correções estão bloqueadas; confira o histórico.'};}});
 const [pending,setPending]=useState<LegacyCostPending|undefined>(restored.pending),[review,setReview]=useState<LegacyCostPending>(),[choice,setChoice]=useState(''),[reverse,setReverse]=useState(false),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState(''),[fingerprint,setFingerprint]=useState('');
 const alive=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const query=useQuery({queryKey:['finance-legacy-cost-context',tenant,actor,expense,page],queryFn:()=>readLegacyCostAssociation(tenant,expense,page),retry:false});
 const data=query.isError||query.isFetching?undefined:query.data,selected=data?.candidates.find(row=>row.cost_id===choice);
 const canAssociate=!!data&&!data.source.issue&&!data.active_link&&!!selected&&!selected.issue&&confirmed,canReverse=!!data?.active_link;
 const current=JSON.stringify({source:data?.source,selected,active:data?.active_link});
 const reviewCurrent=!!review&&current===fingerprint&&(review.kind==='associate'?canAssociate&&review.command.cost_id===choice&&review.command.revision===selected?.revision:canReverse&&review.command.link_id===data?.active_link?.id);
 function prepare(){if(restored.error||(reverse?!canReverse:!canAssociate))return;const parsed=legacyCostPendingSchema.safeParse(reverse?{kind:'reverse',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),link_id:data!.active_link!.id,reason}}:{kind:'associate',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),expense_id:expense,cost_id:choice,revision:selected!.revision,reason,same_expense_confirmed:true}});if(parsed.success){setReview(parsed.data);setFingerprint(current);}}
 async function submit(){if(sending.current||restored.error)return;const original=pending||review;if(!original||(!pending&&!reviewCurrent))return;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,expense,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma decisão foi enviada.');return;}setPending(original);}sending.current=true;setBusy(true);setError('');
  try{const result=await submitLegacyCostAssociation(original);if(result.expense_id!==expense)throw new Error('Resposta fora da despesa.');sessionStorage.removeItem(key);for(const prefix of ['finance-legacy-cost-context','finance-legacy-cost-inventory','finance-expenses','finance-recorded-cost-summary','driver_settlements','driver_settlement','finance-settlement-expense-context','expense_approval','expense-review-context','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});onRecorded?.();if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setReverse(false);setConfirmed(false);setReason('');setNotice(original.kind==='associate'?'Associação confirmada pelo servidor. Nenhum dinheiro ou obrigação foi criado.':'Associação desfeita. Custos originais, dinheiro e obrigações foram preservados.');}}
  catch(e){if(e instanceof LegacyCostRejectedError&&!pending){try{sessionStorage.removeItem(key);if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setError(legacyCostIssueLabels[e.message]||'A decisão foi recusada. Atualize e revise as duas origens, a aprovação e os vínculos de acerto e folha.');}void query.refetch();}catch{if(alive.current)setError('Pedido recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}else if(alive.current)setError('Não foi possível confirmar a resposta. O pedido original foi preservado para retomada.');}
  finally{sending.current=false;if(alive.current)setBusy(false);}
 }
 const issue=(value:string)=>legacyCostIssueLabels[value]||'Esta origem exige revisão de compatibilidade e de vínculos antes de ser associada.';
 return <div className="space-y-3 text-sm"><p>A associação integral declara que a despesa antiga e o custo escolhido representam o mesmo gasto. Valor e data semelhantes não comprovam essa identidade. Não cria pagamento, obrigação ou dinheiro. A reversão desfaz somente a associação. Depois de associada, a despesa antiga permanece protegida contra edição e exclusão, inclusive após desfazer o vínculo. A correção auditada da própria despesa ainda não está disponível.</p><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar custos e vínculos</Button>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando despesa e custos…</p>}{query.isError&&<p role="alert">Não foi possível consultar a despesa. Atualize antes de uma nova decisão.</p>}
 {data&&<><h3 className="font-medium">{data.source.description||"Despesa antiga sem descrição"}</h3><p>Despesa antiga: {data.source.id} · {expenseCategoryLabels[data.source.category]||data.source.category} · {data.source.occurred_on||'Sem data válida'} · {data.source.amount_cents===null?'Valor a revisar':formatFinanceCents(data.source.amount_cents)}</p><p>{expensePaymentLabels[data.source.payment_source]||'Origem do custeio a revisar'} · {data.source.reimbursable?'Reembolsável':'Não reembolsável'} · {data.source.approval_status==='approved'?'Aprovada':'Aprovação pendente de revisão'}</p>{data.source.issue&&<p role="alert">{issue(data.source.issue)}</p>}
 {data.active_link&&<p className="border border-amber-600 p-2">Associação manual ativa: custo {data.active_link.cost_id} · {formatFinanceCents(data.active_link.amount_cents)} · por {data.active_link.actor_name} ({data.active_link.actor_id}) · {data.active_link.created_at}. Motivo: {data.active_link.reason}</p>}
 <section aria-label="Histórico permanente dos custos"><h3>Histórico de associações manuais</h3>{data.history.rows.length===0?<p>Nenhuma associação nesta página.</p>:data.history.rows.map(item=><article key={item.id} className="rounded border border-amber-600 p-2"><p>Associação manual · {item.reversal?'Desfeita':'Sem reversão'} · {formatFinanceCents(item.amount_cents)} · custo {item.cost_id}</p><p>Por {item.actor_name} ({item.actor_id}) · {item.created_at}</p><p>Motivo: {item.reason}</p>{item.reversal&&<><p>Desfeita por {item.reversal.actor_name} ({item.reversal.actor_id}) · {item.reversal.created_at}</p><p>Motivo: {item.reversal.reason}</p></>}</article>)}</section>
 {!pending&&data.active_link&&<Button variant="outline" disabled={busy||!!restored.error} onClick={()=>{setReverse(true);setReview(undefined);setReason('');}}>Desfazer associação ativa</Button>}
 {!pending&&!reverse&&!data.active_link&&!data.source.issue&&<><fieldset disabled={busy||!!review||!!restored.error}><legend>Custos existentes compatíveis para revisão integral</legend>{data.candidates.map(row=><label className="flex gap-2 border rounded p-2" key={row.cost_id}><input type="radio" name="legacy-cost" disabled={!!row.issue} checked={choice===row.cost_id} onChange={()=>setChoice(row.cost_id)}/><span>{row.description} · {row.occurred_on||'Sem data válida'} · {formatFinanceCents(row.amount_cents)}<br/>Custo: {row.cost_id} · lote: {row.batch_id}{row.issue&&<p>{issue(row.issue)}</p>}</span></label>)}</fieldset>{!data.total&&<p>Nenhum custo elegível. Revise as origens existentes; isso não indica que é necessário registrar o gasto novamente.</p>}</>}
 <div className="flex gap-2 items-center"><Button variant="outline" disabled={page===1||busy||!!review} onClick={()=>{setChoice('');setPage(page-1);}}>Vínculos anteriores</Button><span>Página {page} · {data.total} custo(s), {data.history.total} associação(ões)</span><Button variant="outline" disabled={page*30>=Math.max(data.total,data.history.total)||busy||!!review} onClick={()=>{setChoice('');setPage(page+1);}}>Próximos vínculos</Button></div></>}
 {pending?<><p>Pedido original: {pending.command.request_id} · motivo: {pending.command.reason}</p>{pending.kind==='associate'&&<p>Custo original: {pending.command.cost_id} · declaração de mesmo gasto preservada.</p>}<Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar associação ou correção de custo</Button></>:(reverse?canReverse:!!selected)&&<>{!reverse&&<label className="flex gap-2"><input type="checkbox" disabled={!!review} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Conferi que as duas origens representam integralmente o mesmo gasto.</label>}<label>Motivo da associação ou correção de custo<Textarea maxLength={2000} disabled={!!review} value={reason} onChange={event=>setReason(event.target.value)}/></label>{review?<><p>Revisão final: {review.kind==='associate'?`associar a despesa ${expense} ao custo ${review.command.cost_id}`:'desfazer somente a associação ativa'}.</p>{!reviewCurrent&&<p role="alert">O contexto mudou. Volte e revise novamente.</p>}<Button disabled={busy||!reviewCurrent||!!restored.error} onClick={()=>void submit()}>Confirmar associação ou correção de custo</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão</Button></>:<Button disabled={reason.trim().length<10||(!reverse&&!canAssociate)||!!restored.error} onClick={prepare}>Revisar associação ou correção de custo</Button>}{reverse&&<Button variant="outline" disabled={busy} onClick={()=>{setReverse(false);setReview(undefined);}}>Cancelar correção</Button>}</>}
 </div>;
}
