import {PaidMovementVoidEvidence} from './PaidMovementVoidEvidence';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {readLegacyIntegrity} from '@/lib/financial/legacyIntegrityClient';
import {legacyIntegritySourceLabels,legacyIntegrityIssueLabels,type LegacyIntegrityRow} from '@/lib/financial/legacyIntegrityContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
export function LegacyUnresolvedInventory({tenant,actor}:{tenant:string;actor:string}){return <Workspace key={`${tenant}:${actor}`} tenant={tenant} actor={actor}/>;}
function Workspace({tenant,actor}:{tenant:string;actor:string}){
 const [open,setOpen]=useState(false),[page,setPage]=useState(1);
 const query=useQuery({queryKey:['finance-legacy-integrity-inventory',tenant,actor,page],queryFn:()=>readLegacyIntegrity(tenant,page),enabled:open,retry:false}),data=query.isError||query.isFetching?undefined:query.data;
 return <section aria-label="Integridade dos registros antigos da empresa" className="rounded border p-3 space-y-3"><h3 className="font-medium">Registros antigos sem data válida ou com origem pendente</h3><p>Consulta da empresa inteira, sem filtro de conta ou período. As mesmas fontes podem aparecer no inventário por período; não some valores nem registros novamente entre consultas de contas.</p>{!open?<Button variant="outline" onClick={()=>setOpen(true)}>Consultar integridade dos registros antigos</Button>:<><Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>Atualizar integridade dos registros antigos</Button>{query.isFetching&&<p role="status">Consultando integridade histórica…</p>}{query.isError&&<p role="alert">Não foi possível consultar estas pendências. Atualize a consulta; a falha não representa ausência de registros.</p>}{data&&<><p>{data.total} registro(s) da empresa com pendências de integridade.</p><p>As contagens de motivos podem se sobrepor: um mesmo registro pode ter várias pendências. Nenhum total monetário é calculado aqui.</p><h4 className="font-medium">Com conta identificada: {data.identified_account.total}</h4><Rows tenant={tenant} rows={data.identified_account.rows}/><h4 className="font-medium">Conta ausente ou incompatível com a empresa: {data.unknown_account.total}</h4><Rows tenant={tenant} rows={data.unknown_account.rows}/><details><summary>Contagem por motivo na empresa</summary><ul>{Object.entries(data.counts_by_issue).map(([issue,count])=><li key={issue}>{legacyIntegrityIssueLabels[issue]||'Pendência de origem a revisar'}: {count}{!legacyIntegrityIssueLabels[issue]&&<span> · referência {issue}</span>}</li>)}</ul></details><p>Uma lista vazia não aprova a incorporação dos registros antigos e não libera o fechamento. Esta consulta não cria valores, corrige origens ou altera pagamentos.</p><div className="flex gap-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Integridade anterior</Button><span>Página {page} · até 30 registros por grupo</span><Button variant="outline" disabled={page*30>=Math.max(data.identified_account.total,data.unknown_account.total)} onClick={()=>setPage(page+1)}>Próxima integridade</Button></div></>}</>}</section>;
}
function Rows({rows,tenant}:{rows:LegacyIntegrityRow[];tenant:string}){return rows.length?<ul className="space-y-2">{rows.map(row=><li key={`${row.source_table}:${row.source_id}`} className="rounded border border-amber-600 p-2"><p className="font-medium">{legacyIntegritySourceLabels[row.source_table]||'Registro histórico'} · {row.direction==='in'?'Entrada declarada':row.direction==='out'?'Saída declarada':'Direção a esclarecer'}</p><p>{row.date_status==='valid'?`Data declarada: ${row.occurred_on}`:row.date_status==='missing'?'Data ausente — fora dos filtros por período':'Data inválida — fora dos filtros por período'}</p><p>{row.amount_cents===null?'Valor não validado — sem conversão ou soma':`Valor declarado: ${formatFinanceCents(row.amount_cents)}`}</p><ul className="list-disc pl-4">{row.issues.map(issue=><li key={issue}>{legacyIntegrityIssueLabels[issue]||'Origem ou vínculo precisa de revisão.'}{!legacyIntegrityIssueLabels[issue]&&<span> Referência: {issue}</span>}</li>)}</ul><PaidMovementVoidEvidence events={row.context.movement_voids} tenant={tenant}/><details><summary>Identificação e dados originais para rastreio</summary><p>Fonte: {row.source_table} · registro: {row.source_id}</p><p>Conta: {row.account_status==='identified'?'identificada':row.account_status==='not_in_tenant'?'referência não encontrada nesta empresa':'não identificada'}{row.account_id&&` · referência ${row.account_id}`}</p><p>Data original: {row.raw_date??'ausente'}</p><p>Valor original: {row.raw_amount??'ausente'}</p><pre className="whitespace-pre-wrap break-all">{JSON.stringify(row.context,null,2)}</pre></details></li>)}</ul>:<p>Nenhuma pendência neste grupo e página.</p>;}
