import {StockAcquisitionInventory} from './StockAcquisitionInventory';
import {MaintenanceCostContextPanel} from './MaintenanceCostContextPanel';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {readLegacyCostInventory} from '@/lib/financial/legacyCostAssociationClient';
import {legacyCostIssueLabels} from '@/lib/financial/legacyCostAssociationContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {LegacyCostAssociation} from './LegacyCostAssociation';
const statuses:Record<string,string>={approved:'Aprovada',pending:'Pendente',rejected:'Rejeitada',open:'Aberta',in_progress:'Em andamento',completed:'Concluída',cancelled:'Cancelada'};
export function LegacyCostInventory({tenant,actor}:{tenant:string;actor:string}){const [open,setOpen]=useState(false);return <section className="border rounded p-3 space-y-3" aria-label="Inventário de custos antigos"><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Ocultar custos antigos':'Conferir custos antigos e associações'}</Button>{open&&<><StockAcquisitionInventory tenant={tenant} actor={actor}/><Inventory key={`${tenant}:${actor}`} tenant={tenant} actor={actor}/></>}</section>;}
function Inventory({tenant,actor}:{tenant:string;actor:string}){
 const [filter,setFilter]=useState({source:'all',page:1});const query=useQuery({queryKey:['finance-legacy-cost-inventory',tenant,actor,filter],queryFn:()=>readLegacyCostInventory(tenant,filter.page,filter.source),retry:false}),data=query.isError||query.isFetching?undefined:query.data;
 return <div className="space-y-3 text-sm"><h2 className="font-semibold">Custos antigos: identificação de representações existentes</h2><p>Inventário da empresa, inclusive registros sem data válida. Não é total de custos nem de dinheiro: despesas antigas, ordens, peças e consumo podem representar o mesmo gasto. Manutenção continua exigindo revisão por componentes; sua cobertura permanece incompleta.</p><label>Fonte do custo antigo<select className="ml-2 rounded border p-2" value={filter.source} onChange={event=>setFilter({source:event.target.value,page:1})}><option value="all">Todas as fontes deste inventário</option><option value="driver_expenses">Despesas antigas de motoristas</option><option value="maintenance_orders">Ordens de manutenção</option></select></label><Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>Atualizar inventário de custos</Button>{query.isFetching&&<p role="status">Consultando custos antigos…</p>}{query.isError&&<p role="alert">Não foi possível consultar o inventário. Isso não representa ausência de pendências.</p>}{data&&<><p>{data.total} registro(s) nesta fonte · página {data.page} · até 30 registros.</p>{!data.rows.length&&<p>Nenhum registro nesta página. A lista vazia não confirma cobertura completa.</p>}<ul className="space-y-2">{data.rows.map(row=><li key={`${row.source_table}:${row.source_id}`} className="border rounded p-3 space-y-2"><h3 className="font-medium">{row.description||'Sem descrição'} · {row.source_table==='driver_expenses'?'Despesa de motorista':'Ordem de manutenção'}</h3><p>{row.occurred_on||'Sem data válida'} · {statuses[row.status]||'Estado a revisar'} · {row.amount_cents===null?'Valor a revisar':`Valor declarado na origem: ${formatFinanceCents(row.amount_cents)}`}</p><p>Identificação: {row.source_id}</p>{row.active_link_id&&<p className="text-amber-700">Associação manual ativa. Consulte autoria e motivo no histórico.</p>}{row.issue&&<p>{legacyCostIssueLabels[row.issue]||'A origem precisa de revisão antes de ser associada.'}</p>}{row.source_table==='driver_expenses'?<LegacyCostAssociation tenant={tenant} actor={actor} expense={row.source_id}/>:<MaintenanceCostContextPanel tenant={tenant} actor={actor} order={row.source_id}/>}</li>)}</ul><div className="flex gap-2"><Button variant="outline" disabled={filter.page===1} onClick={()=>setFilter({...filter,page:filter.page-1})}>Custos anteriores</Button><Button variant="outline" disabled={filter.page*30>=data.total} onClick={()=>setFilter({...filter,page:filter.page+1})}>Próximos custos</Button></div></>}</div>;
}
