import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {Input} from '@/components/ui/input';
import {maintenanceLaborIssueLabels,maintenanceLaborPendingSchema,type MaintenanceLaborPending} from '@/lib/financial/maintenanceLaborAssociationContract';
import {readMaintenanceLaborAssociation,submitMaintenanceLaborAssociation,MaintenanceLaborRejectedError} from '@/lib/financial/maintenanceLaborAssociationClient';
type Props={tenant:string;actor:string;order:string;onRecorded?:()=>void};
export function MaintenanceLaborAssociation(props:Props){const [open,setOpen]=useState(false);return <><Button size="sm" variant="outline" onClick={()=>setOpen(true)}>Associar mão de obra a custo existente</Button>{open&&<FinanceAccessBoundary><Dialog open onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Associação da mão de obra da OS</DialogTitle><DialogDescription>Identifique a mesma mão de obra em um custo existente, com fornecedor cadastrado. Sem novo custo ou baixa.</DialogDescription></DialogHeader><MaintenanceLaborAssociationWorkspace key={`${props.tenant}:${props.actor}:${props.order}`} {...props}/></DialogContent></Dialog></FinanceAccessBoundary>}</>;}
export function MaintenanceLaborAssociationWorkspace({tenant,actor,order,onRecorded}:Props){
 const key=`finance-maintenance-labor-association:${tenant}:${actor}:${order}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=maintenanceLaborPendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.order!==order||pending.command.tenant_id!==tenant||(pending.kind==='associate'&&pending.command.order_id!==order))throw new Error();return {pending};}catch{return {error:'Não foi possível recuperar o pedido. Novas associações e correções estão bloqueadas; confira o histórico.'};}});
 const [pending,setPending]=useState<MaintenanceLaborPending|undefined>(restored.pending),[review,setReview]=useState<MaintenanceLaborPending>(),[choice,setChoice]=useState(''),[reverse,setReverse]=useState(false),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState(''),[fingerprint,setFingerprint]=useState(''),[search,setSearch]=useState(''),[draftSearch,setDraftSearch]=useState('');
 const alive=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const query=useQuery({queryKey:['finance-maintenance-labor-context',tenant,actor,order,page,search],queryFn:()=>readMaintenanceLaborAssociation(tenant,order,page,search),retry:false});
 const data=query.isError||query.isFetching?undefined:query.data,selected=data?.candidates.find(row=>row.cost_id===choice);
 const canAssociate=!!data&&!data.active_link&&!!selected&&!selected.issue&&!!selected.supplier_id&&confirmed,canReverse=!!data?.active_link;
 const current=JSON.stringify({source:data?.source,selected,active:data?.active_link});
 const reviewCurrent=!!review&&current===fingerprint&&(review.kind==='associate'?canAssociate&&review.command.cost_id===choice&&review.command.revision===selected?.revision:canReverse&&review.command.link_id===data?.active_link?.id);
 function prepare(){if(restored.error||(reverse?!canReverse:!canAssociate))return;const parsed=maintenanceLaborPendingSchema.safeParse(reverse?{kind:'reverse',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),link_id:data!.active_link!.id,reason}}:{kind:'associate',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),order_id:order,cost_id:choice,revision:selected!.revision,reason,same_labor_confirmed:true}});if(parsed.success){setReview(parsed.data);setFingerprint(current);}}
 async function submit(){if(sending.current||restored.error)return;const original=pending||review;if(!original||(!pending&&!reviewCurrent))return;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,order,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma decisão foi enviada.');return;}setPending(original);}sending.current=true;setBusy(true);setError('');
  try{const result=await submitMaintenanceLaborAssociation(original);if(result.order_id!==order)throw new Error('Resposta fora da OS.');sessionStorage.removeItem(key);for(const prefix of ['finance-maintenance-labor-context','finance-legacy-cost-inventory','finance-maintenance-cost-context','finance-expenses','finance-recorded-cost-summary','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});onRecorded?.();if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setReverse(false);setConfirmed(false);setReason('');setNotice(original.kind==='associate'?'Associação confirmada pelo servidor. Nenhum dinheiro ou obrigação foi criado.':'Associação desfeita. Custos originais, dinheiro e obrigações foram preservados.');}}
  catch(e){if(e instanceof MaintenanceLaborRejectedError&&!pending){try{sessionStorage.removeItem(key);if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setError(maintenanceLaborIssueLabels[e.message]||'A decisão foi recusada. Atualize e revise a OS, o custo escolhido e o cadastro do fornecedor.');}void query.refetch();}catch{if(alive.current)setError('Pedido recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}else if(alive.current)setError('Não foi possível confirmar a resposta. O pedido original foi preservado para retomada.');}
  finally{sending.current=false;if(alive.current)setBusy(false);}
 }
 const issue=(value:string)=>maintenanceLaborIssueLabels[value]||'Esta origem exige revisão de compatibilidade e de vínculos antes de ser associada.';
 return <div className="space-y-3 text-sm"><p>Associe somente a mão de obra declarada na OS. Peças e total do cabeçalho não entram nesta associação. O texto do fornecedor da OS não identifica automaticamente um cadastro. Confira o fornecedor por ID no custo escolhido. Não cria custo, pagamento, obrigação ou dinheiro; a reversão desfaz somente o vínculo. Desfaça a associação ativa antes de corrigir valores financeiros da OS; o histórico original permanece preservado.</p><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar custos e vínculos</Button>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando mão de obra e custos…</p>}{query.isError&&<p role="alert">Não foi possível consultar a mão de obra. Atualize antes de uma nova decisão.</p>}
 <form className="flex gap-2 items-end" onSubmit={event=>{event.preventDefault();setPage(1);setChoice("");setReview(undefined);setSearch(draftSearch);if(search===draftSearch&&page===1)void query.refetch();}}><label>Buscar custo de mão de obra<Input maxLength={200} disabled={busy||!!pending} value={draftSearch} onChange={event=>setDraftSearch(event.target.value)}/></label><Button disabled={busy||!!pending||query.isFetching}>Buscar custos</Button></form>{data&&<><h3 className="font-medium">Mão de obra da OS {data.source.order_number}</h3><p>OS: {data.source.id} · abertura: {data.source.opened_on||"Sem data válida"} · mão de obra declarada: {data.source.labor_cents===null?"Valor a revisar":formatFinanceCents(data.source.labor_cents)}</p><p>Fornecedor escrito na OS: {data.source.supplier_name||"Não informado"}. Texto declarado, sem vínculo automático com cadastro.</p>{data.active_link&&<p className="border border-amber-600 p-2">Associação manual ativa: custo {data.active_link.cost_id} · fornecedor {data.active_link.supplier_id} · {formatFinanceCents(data.active_link.amount_cents)} · por {data.active_link.actor_name} ({data.active_link.actor_id}) · {data.active_link.created_at}. Motivo: {data.active_link.reason}</p>}
 <section aria-label="Histórico permanente da mão de obra"><h3>Histórico de associações manuais</h3>{data.history.rows.length===0?<p>Nenhuma associação nesta página.</p>:data.history.rows.map(item=><article key={item.id} className="rounded border border-amber-600 p-2"><p>Associação manual · {item.reversal?'Desfeita':'Sem reversão'} · {formatFinanceCents(item.amount_cents)} · custo {item.cost_id} · fornecedor {item.supplier_id}</p><p>Por {item.actor_name} ({item.actor_id}) · {item.created_at}</p><p>Motivo: {item.reason}</p>{item.reversal&&<><p>Desfeita por {item.reversal.actor_name} ({item.reversal.actor_id}) · {item.reversal.created_at}</p><p>Motivo: {item.reversal.reason}</p></>}</article>)}</section>
 {!pending&&data.active_link&&<Button variant="outline" disabled={busy||!!restored.error} onClick={()=>{setReverse(true);setReview(undefined);setReason('');}}>Desfazer associação ativa</Button>}
 {!pending&&!reverse&&!data.active_link&&<><fieldset disabled={busy||!!review||!!restored.error}><legend>Custos existentes de manutenção para revisão da mão de obra</legend>{data.candidates.map(row=><label className="flex gap-2 border rounded p-2" key={row.cost_id}><input type="radio" name="legacy-cost" disabled={!!row.issue||!row.supplier_id} checked={choice===row.cost_id} onChange={()=>setChoice(row.cost_id)}/><span>{row.description} · {row.occurred_on||'Sem data válida'} · {formatFinanceCents(row.amount_cents)}<br/>Fornecedor cadastrado: {row.supplier_name||"Não identificado"} · ID: {row.supplier_id||"Ausente"}<br/>Custo: {row.cost_id} · lote: {row.batch_id}{row.issue&&<p>{issue(row.issue)}</p>}</span></label>)}</fieldset>{!data.total&&<p>Nenhum custo elegível. Revise as origens existentes; isso não indica que é necessário registrar o gasto novamente.</p>}</>}
 <div className="flex gap-2 items-center"><Button variant="outline" disabled={page===1||busy||!!review} onClick={()=>{setChoice('');setPage(page-1);}}>Vínculos anteriores</Button><span>Página {page} · {data.total} custo(s), {data.history.total} associação(ões)</span><Button variant="outline" disabled={page*30>=Math.max(data.total,data.history.total)||busy||!!review} onClick={()=>{setChoice('');setPage(page+1);}}>Próximos vínculos</Button></div></>}
 {pending?<><p>Pedido original: {pending.command.request_id} · motivo: {pending.command.reason}</p>{pending.kind==='associate'&&<p>Custo original: {pending.command.cost_id} · declaração de mesma mão de obra preservada.</p>}<Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar associação ou correção de mão de obra</Button></>:(reverse?canReverse:!!selected)&&<>{!reverse&&<label className="flex gap-2"><input type="checkbox" disabled={!!review} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Conferi que a mão de obra da OS corresponde integralmente ao custo e ao fornecedor cadastrado escolhidos.</label>}<label>Motivo da associação ou correção de mão de obra<Textarea maxLength={2000} disabled={!!review} value={reason} onChange={event=>setReason(event.target.value)}/></label>{review?<><p>Revisão final: {review.kind==='associate'?`associar a mão de obra da OS ${order} ao custo ${review.command.cost_id}, fornecedor ${selected?.supplier_name||"não identificado"} (${selected?.supplier_id||"sem cadastro"})`:'desfazer somente a associação ativa'}.</p>{!reviewCurrent&&<p role="alert">O contexto mudou. Volte e revise novamente.</p>}<Button disabled={busy||!reviewCurrent||!!restored.error} onClick={()=>void submit()}>Confirmar associação ou correção de mão de obra</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão</Button></>:<Button disabled={reason.trim().length<10||(!reverse&&!canAssociate)||!!restored.error} onClick={prepare}>Revisar associação ou correção de mão de obra</Button>}{reverse&&<Button variant="outline" disabled={busy} onClick={()=>{setReverse(false);setReview(undefined);}}>Cancelar correção</Button>}</>}
 </div>;
}
