import {StockConsumptionAttribution} from './StockConsumptionAttribution';
import {MaintenanceDirectPartAssociation} from './MaintenanceDirectPartAssociation';
import {MaintenanceLaborAssociation} from './MaintenanceLaborAssociation';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {readMaintenanceCostContext} from '@/lib/financial/maintenanceCostContextClient';
import {maintenanceCostIssueLabels} from '@/lib/financial/maintenanceCostContextContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {MAINT_STATUS_LABELS} from '@/hooks/useMaintenanceOrders';
type Props={tenant:string;actor:string;order:string};
const money=(value:string|null)=>value===null?'Valor não determinado':formatFinanceCents(value);
const movementLabels:Record<string,string>={entry:'Entrada física',exit:'Saída física',adjustment:'Ajuste de estoque',transfer:'Transferência física',in:'Entrada física',out:'Saída física'};
function Issues({items}:{items:string[]}){return items.length?<ul className="list-disc pl-5 text-amber-800">{items.map(issue=><li key={issue}>{maintenanceCostIssueLabels[issue]||'Componente precisa de revisão.'}{!maintenanceCostIssueLabels[issue]&&<span> Referência: {issue}</span>}</li>)}</ul>:<p>Nenhuma inconsistência sinalizada nesta representação. Isso não confirma custo novo ou cobertura completa.</p>;}
export function MaintenanceCostContextPanel(props:Props){const [open,setOpen]=useState(false);return <><Button size="sm" variant="outline" onClick={()=>setOpen(true)}>Conferir componentes da OS</Button>{open&&<FinanceAccessBoundary><Dialog open onOpenChange={setOpen}><DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Conferência dos componentes da manutenção</DialogTitle><DialogDescription>Confira registros existentes e revise separadamente a associação de mão de obra. Sem novo custo ou baixa.</DialogDescription></DialogHeader><MaintenanceCostContextWorkspace key={`${props.tenant}:${props.actor}:${props.order}`} {...props}/></DialogContent></Dialog></FinanceAccessBoundary>}</>;}
export function MaintenanceCostContextWorkspace({tenant,actor,order}:Props){
 const [page,setPage]=useState(1);const query=useQuery({queryKey:['finance-maintenance-cost-context',tenant,actor,order,page],queryFn:()=>readMaintenanceCostContext(tenant,order,page),retry:false}),data=query.isError||query.isFetching?undefined:query.data;
 return <div className="space-y-4 text-sm"><p>O cabeçalho da OS, suas peças e os movimentos de estoque podem descrever o mesmo gasto. Não some essas três representações como custos distintos. Compra e consumo de uma peça não significam dois pagamentos.</p><p>Custo reconhecido por esta conferência: não determinado. Cobertura de manutenção incompleta; a associação de mão de obra possui revisão própria e não reconhece peças ou o total da OS.</p><Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>Atualizar componentes da OS</Button>{query.isFetching&&<p role="status">Consultando componentes da manutenção…</p>}{query.isError&&<p role="alert">Não foi possível consultar os componentes. A falha não representa ausência de registros ou de inconsistências.</p>}{data&&<>
 <section aria-label="Cabeçalho declarado da OS" className="border rounded p-3 space-y-2"><h3 className="font-semibold">Cabeçalho declarado: {data.header.order_number}</h3><p>{MAINT_STATUS_LABELS[data.header.status]||'Estado a revisar'} · {data.header.opened_on||'Sem data válida'}</p><p>{data.header.description||'Sem descrição'} · fornecedor informado: {data.header.supplier_name||'Não identificado'}</p><dl className="grid sm:grid-cols-3 gap-2"><div><dt>Peças declaradas no cabeçalho</dt><dd>{money(data.header.parts_cents)}</dd></div><div><dt>Mão de obra declarada</dt><dd>{money(data.header.labor_cents)}</dd></div><div><dt>Total declarado na OS</dt><dd>{money(data.header.total_cents)}</dd></div></dl><p>OS: {data.header.id}. Esses valores não são somados aos detalhes abaixo.</p><Issues items={data.header.issues}/><section aria-label="Associação isolada de mão de obra" className="border-t pt-2"><p>Vincule apenas a mão de obra a um custo existente, com fornecedor cadastrado e revisão explícita.</p><MaintenanceLaborAssociation tenant={tenant} actor={actor} order={order}/></section></section>
 <section aria-label="Peças registradas na OS" className="space-y-2"><h3 className="font-semibold">Peças registradas: {data.parts.total}</h3>{!data.parts.rows.length&&<p>Nenhuma peça nesta página.</p>}{data.parts.rows.map(part=><article key={part.id} className="rounded border p-3 space-y-1"><p className="font-medium">{part.description}</p><p>Quantidade declarada: {part.quantity??'Não determinada'} · valor unitário: {money(part.unit_cost_cents)} · valor do registro: {money(part.total_cost_cents)}</p><Issues items={part.issues}/><MaintenanceDirectPartAssociation tenant={tenant} actor={actor} part={part.id}/>{part.stock_movement_id&&<StockConsumptionAttribution tenant={tenant} actor={actor} part={part.id} movement={part.stock_movement_id}/>}<details><summary>Rastreio da peça</summary><p>Registro: {part.id}</p><p>Item de estoque: {part.stock_item_id||'Não vinculado'}</p><p>Movimento de estoque: {part.stock_movement_id||'Não vinculado'}</p></details></article>)}</section>
 <section aria-label="Movimentos de estoque relacionados" className="space-y-2"><h3 className="font-semibold">Movimentos de estoque relacionados: {data.stock.total}</h3><p>Movimentação física não comprova pagamento nem autoriza reconhecer outra compra.</p>{!data.stock.rows.length&&<p>Nenhum movimento de estoque nesta página.</p>}{data.stock.rows.map(stock=><article key={stock.id} className="rounded border p-3 space-y-1"><p className="font-medium">{movementLabels[stock.movement_type]||'Movimentação física a revisar'} · {stock.occurred_on||'Sem data válida'}</p><p>Quantidade declarada: {stock.quantity??'Não determinada'} · valor unitário: {money(stock.unit_cost_cents)} · valor do registro: {money(stock.total_cost_cents)}</p><Issues items={stock.issues}/><details><summary>Rastreio do estoque</summary><p>Movimento: {stock.id}</p><p>Item: {stock.stock_item_id}</p><p>OS referenciada: {stock.maintenance_order_id||'Não vinculada'}</p></details></article>)}</section>
 <div className="flex gap-3 items-center"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Componentes anteriores</Button><span>Página {page} · até 30 peças e 30 movimentos</span><Button variant="outline" disabled={page*30>=Math.max(data.parts.total,data.stock.total)} onClick={()=>setPage(page+1)}>Próximos componentes</Button></div></>}</div>;
}
