import {ExpenseReceiptDialog} from './ExpenseReceiptDialog';
import {useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {manualExpenseCancellationCommandSchema,manualExpenseCancellationLabels,type ManualExpenseCancellationCommand} from '@/lib/financial/manualExpenseCancellationContract';
import {readManualExpenseCancellation,submitManualExpenseCancellation,ManualExpenseCancellationRejectedError} from '@/lib/financial/manualExpenseCancellationClient';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
type Props={tenant:string;actor:string;payableId:string};
export function ManualExpenseCancellationReview(props:Props){const [open,setOpen]=useState(false);return <><Button variant="outline" size="sm" onClick={()=>setOpen(!open)}>{open?'Recolher revisão da despesa avulsa':'Revisar cancelamento / histórico da despesa avulsa'}</Button>{open&&<FinanceAccessBoundary><ManualExpenseCancellationWorkspace key={`${props.tenant}:${props.actor}:${props.payableId}`} {...props}/></FinanceAccessBoundary>}</>;}
export function ManualExpenseCancellationWorkspace({tenant,actor,payableId}:Props){
 const key=`finance-manual-expense-cancellation:${tenant}:${actor}:${payableId}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),command=manualExpenseCancellationCommandSchema.parse(saved.command);if(saved.actor!==actor||command.tenant_id!==tenant||command.payable_id!==payableId)throw new Error();return {command};}catch{return {error:'Não foi possível recuperar o pedido preservado. Novos cancelamentos estão bloqueados; confira o histórico.'};}});
 const [pending,setPending]=useState<ManualExpenseCancellationCommand|undefined>(restored.command),[review,setReview]=useState<ManualExpenseCancellationCommand>(),[reason,setReason]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState('');
 const [receipt,setReceipt]=useState<string>();
 const sending=useRef(false),cache=useQueryClient();
 const query=useQuery({queryKey:['finance-manual-expense-cancellation',tenant,actor,payableId],queryFn:()=>readManualExpenseCancellation(tenant,payableId),retry:false}),data=query.isFetching||query.isError?undefined:query.data;
 const eligible=!!data?.eligible&&data.can_execute&&!restored.error;
 const current=eligible&&accepted&&review?.revision===data?.revision&&review?.reason===reason.trim();
 function prepare(){if(!eligible||!accepted)return;const parsed=manualExpenseCancellationCommandSchema.safeParse({version:1,tenant_id:tenant,request_id:crypto.randomUUID(),payable_id:payableId,revision:data!.revision,reason});if(parsed.success)setReview(parsed.data);}
 async function submit(){if(sending.current||restored.error)return;const command=pending||review;if(!command||(!pending&&!current))return;const uncertain=!!pending;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,command}));}catch{setError('Não foi possível preservar o pedido. Nenhum cancelamento foi enviado.');return;}setPending(command);}sending.current=true;setBusy(true);setError('');try{await submitManualExpenseCancellation(command);sessionStorage.removeItem(key);setPending(undefined);setReview(undefined);setReason('');setAccepted(false);setNotice('Cancelamento confirmado. A despesa avulsa original e sua autoria permanecem no histórico. Nenhum dinheiro foi alterado.');for(const prefix of ['finance-manual-expense-cancellation','finance-expenses','finance-recorded-costs','finance-recorded-cost-summary','payables','driver_settlements','driver_settlement','finance-settlement-expense-context','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});void invalidateAccountReview(cache,tenant);}catch(e){if(e instanceof ManualExpenseCancellationRejectedError&&!uncertain){try{sessionStorage.removeItem(key);setPending(undefined);setReview(undefined);setError(manualExpenseCancellationLabels[e.message]||'O cancelamento foi recusado. Atualize os dados e confira os impedimentos antes de revisar novamente.');void query.refetch();}catch{setError('O pedido foi recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}else setError('Não foi possível confirmar a resposta. O pedido original foi preservado; retome para verificar seu resultado sem criar outro pedido.');}finally{sending.current=false;setBusy(false);}}
 return <section className="space-y-3 rounded border p-3 text-sm" aria-label="Cancelamento auditado da despesa avulsa"><h3 className="font-semibold">Cancelamento auditado da despesa avulsa</h3><p>O cancelamento é definitivo. Preserva o registro original e retira a despesa avulsa dos indicadores ativos. Não executa transferência, estorno ou novo pagamento.</p>
 <Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar conferência da despesa avulsa</Button>
 {query.isFetching&&<p role="status">Consultando despesa avulsa e dependências…</p>}{query.isError&&<p role="alert">Não foi possível consultar a despesa avulsa. Atualize antes de uma nova decisão.</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {data&&<><p>{data.snapshot.payable?.description||'Despesa avulsa sem descrição'} · título {payableId}</p><p>Valor original: {data.effects.cost_removed_cents===null?'Não determinado':formatFinanceCents(data.effects.cost_removed_cents)}</p><p>Registro original: {data.original_request_id||'Não identificado'} · favorecido: {data.snapshot.payable?.supplier_name||'Não identificado'}</p>
 {data.snapshot.command&&<details><summary>Registro original preservado</summary><p>Pedido: {data.snapshot.command.request_id}</p><p>Autor do registro: {typeof data.snapshot.command.actor_id==='string'?data.snapshot.command.actor_id:'Não informado'} · {typeof data.snapshot.command.created_at==='string'?data.snapshot.command.created_at:'Data não informada'}</p><p>Descrição original: {typeof data.snapshot.command.payload.description==='string'?data.snapshot.command.payload.description:'Não informada'}</p><p>Motivo original: {typeof data.snapshot.command.payload.reason==='string'?data.snapshot.command.payload.reason:'Não informado'}</p><p>Documento: {typeof data.snapshot.command.payload.document_number==='string'?data.snapshot.command.payload.document_number:'Não informado'}</p></details>}
 {data.snapshot.evidence.map((item,index)=>typeof item.receipt_path==='string'?<Button key={index} variant="outline" onClick={()=>setReceipt(item.receipt_path as string)}>Ver comprovante preservado {index+1}</Button>:null)}
 {data.cancellation?<article className="rounded border border-amber-600 p-3"><h4>Cancelado — excluído dos indicadores ativos</h4><p>Cancelamento manual por {data.cancellation.actor_name} ({data.cancellation.actor_id}) · {data.cancellation.created_at}</p><p>Motivo: {data.cancellation.reason}</p><p>Registro: {data.cancellation.id}</p></article>:<><p>Custo a retirar dos indicadores: {data.effects.cost_removed_cents===null?'Não determinado':formatFinanceCents(data.effects.cost_removed_cents)}</p><p>Obrigação a cancelar: {data.effects.obligation_cancelled_cents===null?'Não determinada':formatFinanceCents(data.effects.obligation_cancelled_cents)}</p><p>Dinheiro: sem alteração.</p>{data.issue&&<p role="alert">{manualExpenseCancellationLabels[data.issue]||'Há uma dependência que exige revisão específica. Esta despesa avulsa não pode ser cancelada neste fluxo.'}</p>}{!data.can_execute&&<p>Seu acesso permite consultar, mas não executar este cancelamento.</p>}</>}
 </>}
 {data?.issue&&<details><summary>Referências para conferência dos impedimentos</summary>{Object.entries({commands:'Registros originais',payments:'Pagamentos do título',links:'Vínculos do título',expense_items:'Gastos de lote relacionados',advances:'Adiantamentos',settlement_items:'Itens de acerto',payroll_items:'Itens de folha',obligations:'Obrigações relacionadas',closure_dependencies:'Dependências de fechamento'}).map(([field,label])=>{const rows=data.snapshot[field];if(!Array.isArray(rows)||!rows.length)return null;return <div key={field}><h4>{label}</h4><ul>{rows.map((row,index)=><li key={index}>{row&&typeof row==='object'&&typeof row.id==='string'?row.id:'Referência preservada na conferência'}</li>)}</ul></div>;})}</details>}
 {pending?<><p>Pedido original {pending.request_id} · despesa avulsa {pending.payable_id}</p><p>Motivo preservado: {pending.reason}</p><Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar cancelamento da despesa avulsa</Button></>:eligible&&<><label>Motivo do cancelamento<Textarea maxLength={2000} disabled={busy||!!review} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex gap-2"><input type="checkbox" checked={accepted} disabled={busy||!!review} onChange={e=>setAccepted(e.target.checked)}/>Conferi a despesa avulsa e o título. Entendo que o cancelamento é definitivo e preserva o original no histórico.</label>{review?<><p>Revisão final: cancelar somente a despesa avulsa {payableId} e a obrigação indicada acima. Motivo: {review.reason}</p>{!current&&<p role="alert">A conferência mudou. Atualize e revise novamente.</p>}<Button disabled={busy||!current} onClick={()=>void submit()}>Confirmar cancelamento da despesa avulsa</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão</Button></>:<Button disabled={busy||!accepted||reason.trim().length<10} onClick={prepare}>Revisar cancelamento da despesa avulsa</Button>}</>}
 {receipt&&<ExpenseReceiptDialog tenantId={tenant} path={receipt} onClose={()=>setReceipt(undefined)}/>}
 </section>;
}
