import {useRef,useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {z} from 'zod';
import {Button} from '@/components/ui/button';
import {movementVoidCommandSchema,movementVoidErrorLabel,type MovementVoidCommand} from '@/lib/financial/movementVoidCommandContract';
import {MovementVoidRejectedError,submitMovementVoid} from '@/lib/financial/movementVoidCommandClient';
import type {MovementCorrectionPreview} from '@/lib/financial/movementCorrectionPreviewContract';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
const effectsSchema=z.object({account_id:z.string().uuid(),occurred_on:z.string(),inflow_delta_cents:z.string().regex(/^-?\d+$/),outflow_delta_cents:z.string().regex(/^-?\d+$/),balance_delta_cents:z.string().regex(/^-?\d+$/)});
const savedSchema=z.object({actor:z.string().uuid(),original_request_id:z.string().uuid(),command:movementVoidCommandSchema,effects:effectsSchema}).strict();
type Saved=z.infer<typeof savedSchema>;
export function MovementVoidConfirmation({tenant,actor,movementId,preview}:{tenant:string;actor:string;movementId:string;preview:MovementCorrectionPreview|undefined}){
 const key=`finance-movement-void:${tenant}:${actor}:${movementId}`,cache=useQueryClient(),busyRef=useRef(false);
 const [restored]=useState(()=>{try{const raw=localStorage.getItem(key);if(!raw)return {saved:null,corrupt:false};const saved=savedSchema.parse(JSON.parse(raw));if(saved.actor!==actor||saved.command.tenant_id!==tenant||saved.command.movement_id!==movementId)throw Error();return {saved,corrupt:false};}catch{return {saved:null,corrupt:true};}});
 const [pending,setPending]=useState<Saved|null>(restored.saved),[review,setReview]=useState<Saved|null>(null),[reason,setReason]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const eligible=!notice&&!!preview?.can_execute&&preview.eligible&&!!preview.effects;
 const refresh=()=>Promise.all([invalidateAccountReview(cache,tenant),...['finance-movements','finance-movement-correction-preview','finance-audit','finance-options','finance-payable-options','finance-manual-expense-options','finance-receipt-movement-options','finance-settlement-movements','finance-settlement-payment-candidates','finance-movement-receipts','finance-reconciliation-options','finance-reconciliation-history','finance-automatic-reconciliation','finance-statement-lines'].map(prefix=>cache.invalidateQueries({queryKey:[prefix,tenant]}))]);
 function prepare(){if(!eligible||!preview?.effects||pending||restored.corrupt)return;const command:MovementVoidCommand={version:1,tenant_id:tenant,request_id:crypto.randomUUID(),movement_id:movementId,revision:preview.revision,reason:reason.trim()};if(!movementVoidCommandSchema.safeParse(command).success){setError('Informe um motivo entre 10 e 2.000 caracteres.');return;}if(!preview.origin.original_request_id){setError("A origem do registro precisa ser comprovada antes de confirmar.");return;}setReview({actor,original_request_id:preview.origin.original_request_id,command,effects:effectsSchema.parse(preview.effects)});setError('');}
 function removeOwned(original:Saved){const raw=localStorage.getItem(key);if(raw&&JSON.stringify(savedSchema.parse(JSON.parse(raw)))!==JSON.stringify(original))throw Error("Outro pedido está preservado neste dispositivo.");localStorage.removeItem(key);}
 async function submit(){const original=pending||review,uncertain=!!pending;if(!original||busyRef.current||restored.corrupt)return;if(!uncertain&&(!eligible||preview?.revision!==original.command.revision||!ack))return;
 busyRef.current=true;setBusy(true);setError('');
 try{const raw=localStorage.getItem(key);if(raw&&JSON.stringify(savedSchema.parse(JSON.parse(raw)))!==JSON.stringify(original))throw Error();localStorage.setItem(key,JSON.stringify(original));}catch{setError('Não foi possível preservar este pedido, ou outro pedido já está salvo. Nenhuma confirmação foi enviada. Preserve os dados e reabra a conferência.');busyRef.current=false;setBusy(false);return;}
 setPending(original);
 try{const result=await submitMovementVoid(original.command);if(result.original_request_id!==original.original_request_id||result.actor_id!==actor||Object.entries(original.effects).some(([field,value])=>result.effects[field as keyof typeof result.effects]!==value))throw Error('Resultado incompatível com a conferência preservada.');try{removeOwned(original);}catch{setError('A invalidação foi confirmada. Outro pedido salvo foi preservado; reabra a conferência para consultá-lo.');}setPending(null);setReview(null);setAck(false);setNotice(`Registro invalidado por ${result.actor_name} (${result.actor_id}), em ${result.created_at}. Motivo: ${result.reason}. O original permanece no histórico; o saldo registrado foi atualizado sem executar transação bancária.`);try{await refresh();}catch{setError('A invalidação foi confirmada, mas as listas não foram atualizadas. Atualize a consulta.');}}
 catch(failure){setError(movementVoidErrorLabel(failure));if(failure instanceof MovementVoidRejectedError&&!uncertain){try{removeOwned(original);setPending(null);setReview(null);setAck(false);}catch{setError('O pedido permanece preservado neste dispositivo. Retome a consulta antes de outra decisão.');}void refresh().catch(()=>setError("A rejeição foi confirmada, mas a consulta não foi atualizada. Atualize a conferência antes de revisar outro pedido."));}}
 finally{busyRef.current=false;setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da invalidação">{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{restored.corrupt?<p role="alert">O pedido salvo está inconsistente. Novas confirmações estão bloqueadas; preserve os dados para revisão.</p>:pending?<><p>Há um pedido preservado para este movimento. Retomar consulta o resultado do mesmo pedido, sem criar outra correção.</p><p>Pedido {pending.command.request_id} · motivo: {pending.command.reason}</p><Button disabled={busy} onClick={()=>void submit()}>Retomar pedido de invalidação</Button></>:eligible?<><label className="block">Motivo da invalidação<textarea className="block w-full rounded border p-2" value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy} onClick={prepare}>Revisar invalidação</Button>{review&&review.command.revision===preview?.revision&&<><p>Invalidar o movimento {movementId} retira seu efeito do saldo registrado. O original, a autoria e o motivo permanecem no histórico.</p><p>Motivo: {review.command.reason}</p><label className="block"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi o movimento e o efeito previsto sobre o saldo registrado.</label><Button disabled={!ack||busy} onClick={()=>void submit()}>Confirmar invalidação</Button></>}</>:<p>A confirmação está indisponível nesta consulta. Atualize a conferência e verifique os impedimentos.</p>}</section>;
}
