import {useState} from 'react';
import {MovementVoidConfirmation} from './MovementVoidConfirmation';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {formatFinanceCents,movementNatures} from '@/lib/financial/ledgerContract';
import {movementCorrectionIssueLabels,movementCorrectionReadinessLabel} from '@/lib/financial/movementCorrectionPreviewContract';
import {readMovementCorrectionPreview} from '@/lib/financial/movementCorrectionPreviewClient';
type Props={tenant:string;actor:string;movementId:string};
export function MovementCorrectionReview(props:Props){return <FinanceAccessBoundary><MovementCorrectionReviewWorkspace key={`${props.tenant}:${props.actor}:${props.movementId}`} {...props}/></FinanceAccessBoundary>;}
const labels:Record<string,string>={bank_accounts:'Contas',finance_movement_voids:'Invalidações de movimentos',finance_account_period_closures:'Fechamentos',finance_account_period_reopenings:'Reaberturas',employee_advances:'Adiantamentos',payroll_entry_items:'Itens de folha',driver_settlement_items:'Composição de acerto',finance_fiscal_receivable_origins:'Origens fiscais',finance_unloading_charges:'Descargas e reembolsos',finance_events:'Histórico financeiro',correction_backlinks:'Referências de outras correções',finance_reconciliation_groups:'Conciliações',finance_reconciliation_reversals:'Reversões de conciliação',finance_expense_allocations:'Utilizações em gastos',finance_payable_movement_links:'Vínculos de pagamentos',finance_settlement_movement_links:'Vínculos de acertos',finance_receivable_movement_links:'Vínculos de recebíveis',finance_legacy_receipt_movement_links:'Associações de recebimentos antigos',finance_account_period_dependencies:'Dependências de fechamento',finance_internal_transfers:'Transferências',finance_transfer_departures:'Saídas em trânsito',payables_payments:'Pagamentos de títulos',driver_settlement_payments:'Pagamentos de acertos',finance_commands:'Registros financeiros'};
const text=(value:unknown,fallback='Não informado')=>typeof value==='string'&&value?value:fallback;
const amount=(value:unknown)=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?formatFinanceCents(value):typeof value==='string'&&/^\d+$/.test(value)?formatFinanceCents(value):'Valor não determinado';
export function MovementCorrectionReviewWorkspace({tenant,actor,movementId}:Props){const [page,setPage]=useState(1),query=useQuery({queryKey:['finance-movement-correction-preview',tenant,actor,movementId],queryFn:()=>readMovementCorrectionPreview(tenant,movementId),retry:false}),data=query.isFetching||query.isError?undefined:query.data;return <section className="space-y-3 rounded border p-3 text-sm" aria-label="Conferência para correção do movimento"><h3 className="font-semibold">Conferência para correção do registro</h3><p>Esta consulta mostra a origem, os vínculos e o efeito previsto da correção.</p><Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>Atualizar conferência do movimento</Button>{query.isFetching&&<p role="status">Consultando origem, dependências e efeitos…</p>}{query.isError&&<p role="alert">Não foi possível consultar o movimento. Nenhuma elegibilidade ou efeito foi presumido.</p>}{data&&<><h4>Registro original</h4><p>{data.origin.snapshot.movement.description} · {data.origin.snapshot.movement.beneficiary_name}</p><p>{data.origin.snapshot.movement.occurred_on} · {data.origin.snapshot.movement.direction==='in'?'Entrada':data.origin.snapshot.movement.direction==='out'?'Saída':'Direção a revisar'} · {amount(data.origin.snapshot.movement.amount_cents)}</p><p>{movementNatures[data.origin.snapshot.movement.nature as keyof typeof movementNatures]||'Natureza a revisar'} · conta {data.origin.snapshot.movement.bank_account_id}</p><p>Movimento: {movementId} · registrado por {data.origin.snapshot.movement.created_by} · {data.origin.snapshot.movement.created_at}</p><p>Pedido original: {data.origin.original_request_id||'Não comprovado'}</p><p>Origem: {data.origin.verified?'registro manual comprovado':'comprovação pendente'}</p>{data.origin.issue&&<p role="alert">{movementCorrectionIssueLabels[data.origin.issue]||'A origem apresenta inconsistência e precisa de revisão.'}</p>}{data.origin.snapshot.recording_events.map((event,index)=><p key={index}>Evento original: {text(event.id)} · {text(event.actor_name)} ({text(event.actor_id)}) · {text(event.created_at)} · motivo: {text(event.reason)}</p>)}
 {data.void&&<article className="border border-amber-600 p-2"><h4>Original já invalidado</h4><p>Por {data.void.actor_name} ({data.void.actor_id}) · {data.void.created_at}</p><p>Motivo: {data.void.reason} · evento {data.void.id}</p></article>}
 <p>{data.eligible?'A consulta não encontrou impedimentos para o efeito previsto.':'Há impedimentos para invalidar este registro.'}</p>{!data.readiness.ready&&<p role="alert">Há verificações pendentes. A confirmação permanece indisponível.</p>}
 {data.blockers.length>0&&<section><h4>Impedimentos identificados ({data.blockers.length})</h4><ul>{data.blockers.slice((page-1)*30,page*30).map((blocker,index)=><li key={index} className="border-l-2 pl-2">{movementCorrectionIssueLabels[blocker.code]||'Esta dependência impede a correção e exige revisão específica.'}<p>{blocker.source_table?(labels[blocker.source_table]||'Origem relacionada'):'Condição do movimento'} · {blocker.source_ids.join(', ')||'Sem referência individual'}</p><details><summary>Referência técnica do impedimento</summary>{blocker.code}</details></li>)}</ul><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Impedimentos anteriores</Button><Button variant="outline" disabled={page*30>=data.blockers.length} onClick={()=>setPage(page+1)}>Próximos impedimentos</Button></section>}
 <section><h4>Efeito prospectivo, condicionado à resolução dos impedimentos</h4>{data.effects?<><p>Conta {data.effects.account_id} · dia {data.effects.occurred_on}</p><p>Variação das entradas registradas: {formatFinanceCents(data.effects.inflow_delta_cents)}</p><p>Variação das saídas registradas: {formatFinanceCents(data.effects.outflow_delta_cents)}</p><p>Variação do saldo representado: {formatFinanceCents(data.effects.balance_delta_cents)}</p><p>Nenhuma transação bancária seria executada. Estes valores são uma simulação da alteração do registro, não uma correção realizada.</p></>:<p>Efeito não determinado para este contexto. Nenhum valor zero foi presumido.</p>}</section>
 <details><summary>Dependências preservadas por origem</summary>{Object.entries(data.dependencies).map(([table,rows])=><DependencyRows key={table} table={table} rows={rows}/>)}</details><details><summary>Proteções ainda necessárias</summary>{data.readiness.missing.length?data.readiness.missing.map(item=><div key={item}><p>{movementCorrectionReadinessLabel(item)}</p><details><summary>Referência da proteção</summary>{item}</details></div>):<p>Nenhuma proteção ausente nesta consulta.</p>}</details></>}<MovementVoidConfirmation key={[tenant,actor,movementId].join(":")} tenant={tenant} actor={actor} movementId={movementId} preview={data}/></section>;}
function DependencyRows({table,rows}:{table:string;rows:Record<string,unknown>[]}){const [page,setPage]=useState(1);if(!rows.length)return null;return <section><h4>{labels[table]||'Origem relacionada'} · {rows.length} registro(s)</h4>{rows.slice((page-1)*30,page*30).map((row,index)=><p key={index}>ID: {text(row.id,text(row.source_id,text(row.movement_id,text(row.request_id,text(row.command_id)))))}{Boolean(row.period_start||row.period_end||row.affected_from||row.affected_to)&&<> · período: {text(row.period_start??row.affected_from)} a {text(row.period_end??row.affected_to)}</>}{Boolean(row.closure_id)&&<> · fechamento: {text(row.closure_id)}</>}</p>)}{rows.length>30&&<><Button disabled={page===1} onClick={()=>setPage(page-1)}>Dependências anteriores</Button><Button disabled={page*30>=rows.length} onClick={()=>setPage(page+1)}>Próximas dependências</Button></>}</section>;}
