import {openComplementExtinctionErrorLabel} from '@/lib/financial/openComplementExtinctionLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {openComplementExtinctionExpectedSchema,type OpenComplementExtinctionPreview} from '@/lib/financial/openComplementExtinctionContract';
import {sendOpenComplementExtinction} from '@/lib/financial/openComplementExtinctionClient';
import {createOpenComplementExtinctionOutbox,lockOpenComplementExtinction,pendingOpenComplementExtinction,openComplementExtinctionKey,type PendingOpenComplementExtinction} from '@/lib/financial/openComplementExtinctionOutbox';
export function OpenComplementExtinctionConfirmation({tenant,actor,chargeId,preview,refresh,canConfirm}:{tenant:string;actor:string;chargeId:string;canConfirm:boolean;preview:OpenComplementExtinctionPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingOpenComplementExtinction|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingOpenComplementExtinction(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createOpenComplementExtinctionOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockOpenComplementExtinction,send:sendOpenComplementExtinction}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===openComplementExtinctionKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=canConfirm&&!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.charge_id===chargeId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(!canConfirm||busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{chargeId,expenseId:preview!.expense_id,payableId:preview!.payable_id,proposal:preview!.proposal,expected:openComplementExtinctionExpectedSchema.parse(preview!.effects),revision:preview!.revision,reason});setConfirmed(`Complemento cancelado para a descarga ${result.charge_id}. Custo corrigido ${formatFinanceCents(result.effects.cost_after_cents)}; nominal histórico ${formatFinanceCents(result.effects.historical_payable_nominal_cents)} preservado com status cancelado e devido R$ 0,00. Saldo sob responsabilidade do motorista ${formatFinanceCents(result.effects.residual_cents)}. Nenhum dinheiro foi movimentado. Pedido ${result.request_id}.`);setReview(null);try{await refresh();}catch{setError('A correção do complemento foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(openComplementExtinctionErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section aria-label="Confirmar extinção do complemento" className="rounded border p-3 space-y-2">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">Pedido salvo incompatível. Preserve os dados; novo envio bloqueado.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · descarga {pending.payload.charge_id} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p><p>Custo proposto: {formatFinanceCents(pending.payload.proposal.amount_cents)} · nominal a cancelar: {formatFinanceCents(pending.expected.historical_payable_nominal_cents)} · saldo histórico do motorista: {formatFinanceCents(pending.expected.residual_cents)}</p>{pending.payload.proposal.dispositions.map(d=><p key={d.source_id}>Alocação {d.source_id} · responsável {d.responsible_id} · aplicado {formatFinanceCents(d.applied_cents)}</p>)}{pending.payload.charge_id!==chargeId&&<p role="alert">Este pedido pertence a outra descarga. A recuperação usa exclusivamente aquela origem.</p>}<Button disabled={busy||!canConfirm} onClick={()=>void execute(true)}>Recuperar extinção do complemento</Button></>:fresh?<><label>Motivo da extinção<textarea value={reason} maxLength={2000} disabled={busy} onChange={e=>{setReason(e.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar extinção do complemento</Button>{review===preview?.revision&&<><p>O título preservará o nominal histórico com status cancelado, devido zero. O custo ficará coberto pelas alocações existentes. A cobrança da descarga e o dinheiro não serão alterados.</p><p>{preview!.effects.residual_cents==='0'?'Aplicação igual ao valor reservado: sem excedente e sem nova dívida.':`O saldo de ${formatFinanceCents(preview!.effects.residual_cents)} continuará reservado sob responsabilidade dos motoristas apresentados; ainda não foi devolvido.`}</p><label><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/> Conferi o custo, o complemento cancelado, cada aplicação e o responsável pelo eventual saldo.</label><Button disabled={busy||!ack} onClick={()=>void execute(false)}>Confirmar extinção do complemento</Button></>}</>:<p>A extinção está indisponível nesta consulta.</p>}</section>;
}
