import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {useTenant} from '@/hooks/useTenant';
import {ExpenseComplementExtinctionHistory} from './ExpenseComplementExtinctionHistory';
import {UnloadingCostDispositionEditor} from './UnloadingCostDispositionEditor';
import {OpenComplementExtinctionConfirmation} from './OpenComplementExtinctionConfirmation';
import {proposedAppliedCents} from '@/lib/financial/unloadingCostRegularizationContract';
import {openComplementExtinctionProposalSchema,type OpenComplementExtinctionProposal,type OpenComplementExtinctionPreview} from '@/lib/financial/openComplementExtinctionContract';
import {readOpenComplementExtinction} from '@/lib/financial/openComplementExtinctionClient';
import {openComplementExtinctionLabels} from '@/lib/financial/openComplementExtinctionLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
type Scope={tenant:string;actor:string;chargeId:string};
export function OpenComplementExtinctionDialog(props:Scope&{open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent className="max-h-[90vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>Corrigir custo e cancelar complemento aberto</DialogTitle><DialogDescription>Confira a aplicação de cada fonte e quem responde pelo saldo. Esta operação não devolve dinheiro.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><OpenComplementExtinctionWorkspace key={`${props.tenant}:${props.actor}:${props.chargeId}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
export function OpenComplementExtinctionWorkspace({tenant,actor,chargeId}:Scope){const {currentRole}=useTenant();const cache=useQueryClient();const [value,setValue]=useState(''),[amount,setAmount]=useState(''),[applied,setApplied]=useState<Record<string,string>>({}),[selected,setSelected]=useState<OpenComplementExtinctionProposal|null>(null),[error,setError]=useState('');
 const discovery=useQuery({queryKey:['finance-open-complement-extinction-sources',tenant,actor,chargeId,amount],queryFn:()=>readOpenComplementExtinction(tenant,actor,chargeId,{amount_cents:amount,dispositions:[]}),enabled:!!amount,retry:false,staleTime:0});
 const sources=amount&&!discovery.isFetching&&!discovery.isError?discovery.data:undefined;
 const preview=useQuery({queryKey:['finance-open-complement-extinction-preview',tenant,actor,chargeId,discovery.data?.revision,selected],queryFn:()=>readOpenComplementExtinction(tenant,actor,chargeId,selected!),enabled:!!selected&&!!sources,retry:false,staleTime:0});
 const data=sources&&selected&&!preview.isFetching&&!preview.isError?preview.data:undefined;
 const refresh=()=>Promise.all([invalidateAccountReview(cache,tenant),...['finance-open-complement-extinction-sources','finance-open-complement-extinction-preview','finance-cost-dispositions','finance-expenses','finance-recorded-costs','finance-recorded-cost-summary','finance-payable-portfolio','finance-settlement-expense-context'].map(prefix=>cache.invalidateQueries({queryKey:[prefix,tenant]},{throwOnError:true}))]);
 function discover(){const cents=proposedAppliedCents(value);if(cents===null||cents==='0'){setError('Informe um custo positivo com até duas casas decimais.');return;}setError('');setApplied({});setSelected(null);if(amount===cents)void discovery.refetch();else setAmount(cents);}
 function review(){if(!sources)return;try{const proposal=openComplementExtinctionProposalSchema.parse({amount_cents:amount,dispositions:sources.dispositions.map(source=>({source_kind:source.source_kind,source_id:source.source_id,applied_cents:proposedAppliedCents(applied[`${source.source_kind}:${source.source_id}`]||''),disposition_type:source.disposition_type,responsible_id:source.responsible_id}))});setError('');setSelected(proposal);}catch{setError('Confira o valor aplicado e o responsável comprovado de cada fonte.');}}
 return <section aria-label="Extinção de complemento aberto" className="space-y-3"><p>Descarga {chargeId}</p><label>Custo corrigido (R$)<Input value={value} inputMode="decimal" onChange={e=>{setValue(e.target.value);setAmount('');setApplied({});setSelected(null);}}/></label><Button onClick={discover}>Consultar fontes do custo</Button>{error&&<p role="alert">{error}</p>}{(discovery.isFetching||preview.isFetching)&&<p role="status">Conferindo fontes e responsabilidades…</p>}{(discovery.isError||preview.isError)&&<p role="alert">A extinção está indisponível nesta consulta. Nenhuma prévia anterior permite confirmar.</p>}{sources&&<><UnloadingCostDispositionEditor rows={sources.dispositions.map(s=>({source:{kind:s.source_kind,id:s.source_id,movementId:s.movement_id,grossReservedCents:s.gross_reserved_cents,responsibleId:s.responsible_id,responsibleName:s.responsible_name,dispositionType:s.disposition_type,issue:s.responsible_id?null:'Responsável não comprovado'},applied:applied[`${s.source_kind}:${s.source_id}`]||''}))} onChange={(index,next)=>{const s=sources.dispositions[index];setApplied(old=>({...old,[`${s.source_kind}:${s.source_id}`]:next}));setSelected(null);}}/><Button disabled={preview.isFetching} onClick={review}>Conferir aplicação e saldos pendentes</Button></>}{data&&<OpenComplementExtinctionDetails data={data}/>}<OpenComplementExtinctionConfirmation key={`${tenant}:${actor}:${chargeId}`} tenant={tenant} actor={actor} chargeId={chargeId} preview={data} canConfirm={['owner','admin'].includes(currentRole||'')} refresh={refresh}/></section>;
}
const money=(v:string|null)=>v===null?'Indeterminado':formatFinanceCents(v);
export function OpenComplementExtinctionDetails({data}:{data:OpenComplementExtinctionPreview}){return <section aria-label="Valores da extinção" className="space-y-2"><p>Custo original {money(data.cost_origin.original_amount_cents)} · vigente {money(data.cost_origin.effective_amount_cents)} · proposto {money(data.target.cost_cents)}</p><p>Reserva preservada {money(data.allocated_reserved_cents)}. Complemento nominal histórico {money(data.payable.amount_cents)} · situação atual {data.payable.status} · situação proposta cancelado · devido proposto R$ 0,00.</p><p>Favorecido do título: {data.payable.beneficiary_name||'Nome não informado'} · {data.payable.beneficiary_id||'ID não informado'}</p><p>{!data.eligible?'A responsabilidade ainda não está confirmada; resolva os impedimentos desta prévia.':data.effects.residual_cents==='0'?'Aplicação integral da reserva: não há excedente nem nova dívida.':`Saldo sob responsabilidade do motorista: ${money(data.effects.residual_cents)}. Esse dinheiro ainda não foi devolvido.`}</p><p>A cobrança da descarga permanece inalterada. Nenhum dinheiro será movimentado ou liberado.</p>{data.dispositions.map(d=><p key={d.source_id}>{d.responsible_name||'Nome não informado'} · responsável {d.responsible_id||'Não comprovado'} · aplicado {money(d.applied_cents)} · saldo {money(d.residual_cents)}</p>)}{data.blockers.map((b,n)=><p role="alert" key={n}>{openComplementExtinctionLabels[b.code as keyof typeof openComplementExtinctionLabels]||'Esta dependência impede a extinção. Confira a origem.'} · {b.source_ids.join(', ')} · {b.code}</p>)}{data.cost_origin.complement_extinction&&<ExpenseComplementExtinctionHistory value={data.cost_origin.complement_extinction}/>}</section>;}
