import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useTenant} from '@/hooks/useTenant';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {PayableApprovalConfirmation} from './PayableApprovalConfirmation';
import {readPayableApproval,payableApprovalLabels} from '@/lib/financial/payableApprovalClient';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
type Scope={tenant:string;actor:string;payableId:string};
export function PayableApprovalDialog(props:Scope&{open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Conferir aprovação da conta</DialogTitle><DialogDescription>A aprovação preserva o valor conferido e não realiza pagamento.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><PayableApprovalWorkspace key={`${props.tenant}:${props.actor}:${props.payableId}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
const money=(v:string|null)=>v===null?'Indeterminado':formatFinanceCents(v);
export function PayableApprovalWorkspace({tenant,actor,payableId}:Scope){const {currentRole}=useTenant();const cache=useQueryClient();const query=useQuery({queryKey:['finance-payable-approval',tenant,actor,payableId],queryFn:()=>readPayableApproval(tenant,actor,payableId),retry:false,staleTime:0,refetchOnMount:'always'});const data=!query.isFetching&&!query.isError&&query.isFetchedAfterMount?query.data:undefined;const refresh=async()=>{await invalidateAccountReview(cache,tenant);await Promise.all(['finance-payable-approval','payables','finance-payable-portfolio','finance-expenses'].map(prefix=>cache.invalidateQueries({queryKey:[prefix,tenant]},{throwOnError:true})));};return <section aria-label="Conferência da aprovação" className="space-y-3"><p>Conta {payableId}</p><Button disabled={query.isFetching} onClick={()=>void query.refetch()}>Atualizar conferência</Button>{query.isFetching&&<p role="status">Conferindo obrigação e custo…</p>}{query.isError&&<p role="alert">A consulta de aprovação está indisponível. Nenhuma prévia anterior permite confirmar.</p>}{data&&<><p>Favorecido: {data.obligation.beneficiary_name||'Nome não informado'} · {data.obligation.beneficiary_id||'Identidade não informada'}</p><p>Valor da obrigação: {money(data.obligation.amount_cents)} · pago: {money(data.obligation.paid_cents)} · situação: {data.obligation.status}</p>{data.cost_origin&&<p>Custo original: {money(data.cost_origin.original_amount_cents)} · custo vigente: {money(data.cost_origin.effective_amount_cents)} · gasto {data.cost_origin.expense_id}</p>}<p>A obrigação pode ser somente o complemento do custo. Nenhum valor será alterado por esta aprovação.</p>{data.blockers.map((b,i)=><p role="alert" key={i}>{payableApprovalLabels[b.code]||'Esta dependência impede a aprovação.'} · {b.source_ids.join(', ')} <span className="text-xs">{b.code}</span></p>)}</>}<PayableApprovalConfirmation key={`${tenant}:${actor}:${payableId}`} tenant={tenant} actor={actor} payableId={payableId} canConfirm={['owner','admin'].includes(currentRole||'')} preview={data} refresh={refresh}/></section>;}
