import {payableApprovalErrorLabel} from '@/lib/financial/payableApprovalClient';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {payableApprovalExpectedSchema,type PayableApprovalPreview} from '@/lib/financial/payableApprovalContract';
import {sendPayableApproval} from '@/lib/financial/payableApprovalClient';
import {createPayableApprovalOutbox,lockPayableApproval,pendingPayableApproval,payableApprovalKey,type PendingPayableApproval} from '@/lib/financial/payableApprovalOutbox';
export function PayableApprovalConfirmation({tenant,actor,payableId,preview,refresh,canConfirm}:{tenant:string;actor:string;payableId:string;canConfirm:boolean;preview:PayableApprovalPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingPayableApproval|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingPayableApproval(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createPayableApprovalOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockPayableApproval,send:sendPayableApproval}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===payableApprovalKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=canConfirm&&!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.payable_id===payableId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(!canConfirm||busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{payableId,amountCents:preview!.obligation.amount_cents!,expected:payableApprovalExpectedSchema.parse({amount_cents:preview!.obligation.amount_cents,cost_revision:preview!.cost_origin?.revision??null}),revision:preview!.revision,reason});setConfirmed(`Aprovação confirmada para a conta ${result.payable_id}, no valor ${formatFinanceCents(result.amount_cents)}. Autor ${result.actor_id}, em ${result.approved_at}. Pedido ${result.request_id}. Nenhum pagamento foi realizado.`);setReview(null);try{await refresh();}catch{setError('A aprovação foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(payableApprovalErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da aprovação">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novas aprovações estão bloqueadas.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · conta a pagar {pending.payload.payable_id} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p><p>Valor preservado: {formatFinanceCents(pending.payload.amount_cents)}. Revisão {pending.payload.revision}</p>{pending.payload.payable_id!==payableId&&<p role="alert">Este pedido pertence a outra conta. Recuperar consulta exclusivamente aquele pedido.</p>}<Button disabled={busy||!canConfirm} onClick={()=>void execute(true)}>Recuperar pedido de aprovação</Button></>:fresh?<><label className="block">Motivo da aprovação<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar aprovação</Button>{review===preview?.revision&&<><p>Aprovar a obrigação de {formatFinanceCents(preview!.obligation.amount_cents!)} para {preview!.obligation.beneficiary_name||'favorecido sem nome informado'}. O custo de origem é apresentado separadamente e não será alterado. Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi o valor e o favorecido desta obrigação. A aprovação não realiza pagamento.</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar aprovação</Button></>}</>:<p>A confirmação de aprovação está indisponível nesta consulta.</p>}</section>;
}
