import {ExpenseCostCoverage} from './ExpenseCostCoverage';
import {PAYABLE_CATEGORIES,PAYABLE_CATEGORY_LABELS} from '@/hooks/usePayables';
import {FinanceOptionPicker} from './FinanceOptionPicker';
import type {FinanceOption} from '@/lib/financial/expenseBatchContract';
import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {readPayablePortfolio} from '@/lib/financial/payablePortfolioClient';
import type {PayablePortfolioFilters} from '@/lib/financial/payablePortfolioContract';
import {payablePortfolioStatusLabels as statuses,payablePortfolioIssueLabels as issues} from '@/lib/financial/payablePortfolioLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
const initial:PayablePortfolioFilters={date_basis:'due_date',from:null,to:null,category:null,supplier_id:null,search:null,status:null,source:null};
const money=(value:string|null)=>value===null?'Indeterminado':formatFinanceCents(value);
type Props={tenant:string;actor:string;onManage?:()=>void;onOpen?:(id:string,action:"edit"|"payments")=>void};
export function PayablePortfolioPanel(props:Props){return <FinanceAccessBoundary><PayablePortfolioWorkspace key={`${props.tenant}:${props.actor}`} {...props}/></FinanceAccessBoundary>;}
export function PayablePortfolioWorkspace({tenant,actor,onManage,onOpen}:Props){
 const [draft,setDraft]=useState(initial),[filters,setFilters]=useState(initial),[list,setList]=useState({page:1,revision:null as string|null}),[notice,setNotice]=useState('');
 const [supplier,setSupplier]=useState<FinanceOption|null>(null);
 const cache=useQueryClient(),query=useQuery({queryKey:['finance-payable-portfolio',tenant,actor,filters,list.page,list.revision],queryFn:()=>readPayablePortfolio(tenant,filters,list.page,list.revision),retry:false});
 const changed=!!query.error&&typeof query.error==='object'&&'message' in query.error&&query.error.message==='finance_payable_portfolio_changed';
 useEffect(()=>{if(!changed)return;setNotice('A carteira mudou durante a navegação. A consulta foi reiniciada na primeira página; confira os totais atualizados.');void cache.invalidateQueries({queryKey:['finance-payable-portfolio',tenant,actor,filters,1,null]});setList({page:1,revision:null});},[changed,cache,tenant,actor,filters]);
 const data=query.isFetching||query.isError?undefined:query.data;
 function apply(){setNotice('');setList({page:1,revision:null});setFilters({...draft});if(JSON.stringify(draft)===JSON.stringify(filters))void cache.invalidateQueries({queryKey:['finance-payable-portfolio',tenant,actor]});}
 return <section className="rounded border p-4 space-y-4" aria-label="Carteira de contas a pagar"><header className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-semibold">Carteira de contas a pagar</h2>{onManage&&<Button variant="outline" onClick={onManage}>Gerenciar contas a pagar</Button>}</header><p className="text-sm">Filtros e totais abrangem todos os títulos encontrados no servidor, antes da paginação. Posição operacional atual dos títulos, com pagamentos registrados. Não representa o saldo bancário nem reconstrói a carteira como ela era em uma data passada. Os filtros abaixo são próprios desta carteira e não usam o cliente, categoria ou período dos painéis acima.</p>
 <form className="flex flex-wrap gap-3 items-end" onSubmit={e=>{e.preventDefault();apply();}}><label>Buscar conta<Input placeholder="Fornecedor, descrição ou documento" maxLength={200} value={draft.search||''} onChange={e=>setDraft({...draft,search:e.target.value||null})}/></label><label>Situação da conta<select className="block rounded border p-2" value={draft.status||''} onChange={e=>setDraft({...draft,status:(e.target.value||null) as PayablePortfolioFilters['status']})}><option value="">Todas</option><option value="pending">Pendente</option><option value="approved">Aprovada</option><option value="partial">Pagamento parcial</option><option value="paid">Paga</option><option value="overdue">Vencimento ultrapassado e não quitada</option><option value="cancelled">Cancelada</option><option value="unknown">Status desconhecido</option></select></label><label>Origem da conta<select className="block rounded border p-2" value={draft.source||''} onChange={e=>setDraft({...draft,source:(e.target.value||null) as PayablePortfolioFilters['source']})}><option value="">Todas</option><option value="manual">Avulsa</option><option value="system">Operacional</option><option value="unknown">Outra origem</option></select></label><label>Categoria da conta<select className="block rounded border p-2" value={draft.category||''} onChange={e=>setDraft({...draft,category:e.target.value||null})}><option value="">Todas</option>{PAYABLE_CATEGORIES.map(category=><option key={category} value={category}>{PAYABLE_CATEGORY_LABELS[category]}</option>)}</select></label><FinanceOptionPicker tenant={tenant} actor={actor} kind="suppliers" label="Fornecedor da conta" value={supplier} onChange={value=>{setSupplier(value);setDraft({...draft,supplier_id:value?.id||null});}}/><label>Data usada na carteira<select className="block rounded border p-2" value={draft.date_basis} onChange={e=>setDraft({...draft,date_basis:e.target.value as PayablePortfolioFilters['date_basis']})}><option value="due_date">Vencimento</option><option value="created_at">Criação do título</option></select></label><label>Contas a pagar — início<Input type="date" value={draft.from||''} onChange={e=>setDraft({...draft,from:e.target.value||null})}/></label><label>Contas a pagar — fim<Input type="date" min={draft.from||undefined} value={draft.to||''} onChange={e=>setDraft({...draft,to:e.target.value||null})}/></label><Button type="submit" disabled={query.isFetching}>Consultar contas a pagar</Button></form>
 {notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando carteira completa e página de títulos…</p>}{query.isError&&!changed&&<p role="alert">Não foi possível consultar a carteira. Os valores anteriores foram ocultados.<Button variant="outline" onClick={()=>void query.refetch()}>Tentar consultar carteira novamente</Button></p>}
 {data&&<><p className="text-sm">Posição atual em {data.as_of.split('-').reverse().join('/')} · filtro por {data.date_basis==='due_date'?'vencimento':'criação'}: {data.from||'sem início'} a {data.to||'sem fim'}.</p><div className="grid sm:grid-cols-4 gap-3">{[['Valor dos títulos ativos',data.nominal_cents],['Pagamentos alocados',data.paid_cents],['Em aberto',data.open_cents],['Em aberto e vencido',data.overdue_cents]].map(([label,value])=><div className="rounded border p-3" key={label}><h3>{label}</h3><p className="text-xl font-semibold">{money(value)}</p></div>)}</div>
 <p>{data.total_titles} título(s) no filtro, incluindo {data.cancelled_titles} cancelado(s), preservado(s) na lista e excluído(s) dos valores ativos. Totais calculados sobre toda a carteira filtrada, não apenas esta página.</p>{!data.totals_valid&&<p role="alert">Totais indeterminados: {data.invalid_titles} título(s) precisam de revisão. Nenhum total zero foi presumido.</p>}{data.undated_titles>0&&<p role="alert">{data.undated_titles} título(s) sem data válida para este filtro foram mantidos como pendência, sem atribuição ao período selecionado.</p>}
 <div className="flex flex-wrap gap-3">{data.status_counts.map(row=><span key={row.status}>{statuses[row.status]||'Situação a revisar'}: {row.count}</span>)}</div>{data.issue_counts.length>0&&<details><summary>Pendências de toda a carteira filtrada</summary><ul>{data.issue_counts.map(row=><li key={row.issue}>{issues[row.issue]||'Informação financeira precisa de revisão'}: {row.count}</li>)}</ul></details>}
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>Título / favorecido</th><th>Datas</th><th>Situação</th><th>Valor ativo</th><th>Pago alocado</th><th>Em aberto</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.source_id} className="border-t align-top"><td className="p-2"><p>{row.description||'Descrição não informada'}</p><p>{row.supplier_name||'Favorecido não identificado'}</p><details><summary>Origem e rastreabilidade</summary><p>Título: {row.source_id}</p><p>Favorecido: {row.supplier_id||'Não identificado'}</p><p>Origem: {row.origin.source_table||'Não informada'} · {row.origin.source_id||'Sem referência'}</p><p>Valor declarado nesta consulta (R$): {row.declared_amount??'Não informado'}</p><p>Pago declarado em reais: {row.declared_paid??'Não informado'}</p><p>{row.expense_cost_version&&<>Custo relacionado: {row.expense_cost_version.expense_id} · {money(row.expense_cost_version.amount_cents)} · {row.expense_cost_version.verified?'Versão comprovada':'Versão a conferir'} · revisão {row.expense_cost_version.revision}</>}</p>{row.payment_cost_versions?.map(link=><p key={`${link.payment_id}:${link.event_id}`}>Versão do custo preservada no pagamento {link.payment_id}: {money(link.cost_version.amount_cents)} · gasto {link.cost_version.expense_id} · alteração {link.cost_version.amendment_id||'Original'} · evento {link.event_id}. Este valor não é somado novamente ao pagamento.</p>)}{row.coverage&&<ExpenseCostCoverage coverage={row.coverage} costCents={row.expense_cost_version?.amount_cents??null}/>}<ul>{row.payment_ids.map(id=><li key={id}>Pagamento: {id}</li>)}</ul></details>{row.issues.length>0&&<ul className="text-amber-700">{row.issues.map(issue=><li key={issue}>{issues[issue]||'Informação financeira precisa de revisão'}</li>)}</ul>}</td><td className="p-2">Vencimento: {row.due_on||'Sem data válida'}<p>Criação: {row.created_on||'Sem data válida'}</p>{!row.date_in_range&&<p className="text-amber-700">Sem atribuição ao período</p>}</td><td className="p-2">{statuses[row.status]||'Situação a revisar'}{row.status==='cancelled'&&<p>Original preservado; excluído dos valores ativos</p>}</td><td className="p-2">{money(row.nominal_cents)}</td><td className="p-2">{money(row.paid_cents)}</td><td className="p-2">{money(row.open_cents)}{onOpen&&<div className="flex gap-2 mt-2"><Button variant="outline" onClick={()=>onOpen(row.source_id,"edit")}>Abrir conta</Button><Button variant="outline" onClick={()=>onOpen(row.source_id,"payments")}>Baixas</Button></div>}</td></tr>)}</tbody></table>{!data.rows.length&&<p>Nenhum título nesta página e filtro.</p>}</div>
 <div className="flex gap-3 items-center"><Button variant="outline" disabled={list.page===1} onClick={()=>setList({page:list.page-1,revision:data.revision})}>Títulos a pagar anteriores</Button><span>Página {data.page} de {Math.max(1,Math.ceil(data.total_titles/30))} · até 30 títulos</span><Button variant="outline" disabled={data.page*30>=data.total_titles} onClick={()=>setList({page:list.page+1,revision:data.revision})}>Próximos títulos a pagar</Button></div></>}
 </section>;
}
