import {useState} from 'react';
import {unloadingFlowIssueLabels} from '@/lib/financial/periodUnloadingFlowLabels';
import {Button} from '@/components/ui/button';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import type {PeriodUnloadingFlow} from '@/lib/financial/periodUnloadingFlowContract';
const value=(cents:string|null)=>cents===null?'Indeterminado':formatFinanceCents(cents);
const kinds={adjustment:'Ajuste do direito de cobrança',charge:'Descarga originalmente registrada',receipt:'Recebimento alocado à descarga',refund:'Devolução registrada'};
const sidecars={allocation_correction:'Correção de alocação',customer_credit:'Crédito do pagador',legacy_association:'Associação manual de recebimento antigo',association_reversal:'Reversão de associação'};
export function UnloadingFlowTotals({origin,receipt,refund,adjustment,net}:{adjustment?:PeriodUnloadingFlow['adjustment_totals'];net?:PeriodUnloadingFlow['net_origin_totals'];origin:PeriodUnloadingFlow['origin_totals'];receipt:PeriodUnloadingFlow['receipt_totals'];refund:PeriodUnloadingFlow['refund_totals']}){return <dl className="grid gap-3 sm:grid-cols-3">{([['Descargas originadas',origin],['Recebimentos alocados',receipt],['Devoluções',refund],...(adjustment?[['Ajustes da cobrança',adjustment] as const]:[]),...(net?[['Líquido das cobranças originadas e ajustadas (não é saldo devedor)',net] as const]:[])] as const).map(([label,total])=><div key={label}><dt>{label}</dt><dd>{value(total.amount_cents)} · {total.count} evento(s)</dd>{!total.valid&&<p className="text-amber-700 dark:text-amber-400">Valor indeterminado: há pendências neste conjunto.</p>}</div>)}</dl>;}
export function UnloadingFlowEvent({row}:{row:PeriodUnloadingFlow['rows'][number]}){return <article className="space-y-2 rounded border p-3"><h4 className="font-semibold">{kinds[row.kind]} · {value(row.amount_cents)}</h4><p>{row.supplier_name||'Nome preservado não informado'} · fornecedor {row.supplier_id}</p><p>Data econômica: {row.economic_on||'Não determinada'} · registro: {row.recorded_at}</p><p>Descarga {row.charge_id} · entrega {row.delivery_stop_id} · título {row.receivable_id}</p><p>Vencimento originalmente declarado: {row.original_due_date||'Não informado'}</p>{(row.kind==='receipt'||row.kind==='refund')&&<p>{row.money_covered?'Movimento coberto pelos fechamentos selecionados':'Cobertura do movimento não comprovada neste pacote'} · movimento {row.movement_id||'Não identificado'} · conta {row.bank_account_id||'Não identificada'}</p>}{!row.valid&&<p role="alert">Este evento tem pendências. Seu valor não comprova recuperação líquida nem saldo devedor.</p>}{row.kind==='adjustment'&&<p className="rounded border border-amber-600 bg-amber-50 p-2 dark:bg-amber-950/30">Ajuste manual · {row.adjustment_leg==='release'?'Retirada da cobrança anterior':'Reconhecimento da cobrança'} · {row.amendment_actor_name||'Nome não informado'} ({row.amendment_actor_id}) · motivo: {row.amendment_reason} · evento {row.amendment_id}. Sem movimentação de dinheiro.</p>}{row.sidecars.map(sidecar=><p key={`${sidecar.kind}:${sidecar.id}`} className="rounded border border-amber-600 bg-amber-50 p-2 dark:bg-amber-950/30">{sidecars[sidecar.kind]} · registro conhecido nesta consulta, sem data econômica presumida · autor {sidecar.actor_id||'Não informado'} · {sidecar.recorded_at} · ID {sidecar.id}</p>)}<details><summary>Referências da origem e dos vínculos</summary><p>Evento {row.event_id} · pedido original {row.original_command_id||'Não informado'} · pedido financeiro {row.command_id||'Não informado'}</p><p>Pagamento {row.payment_id||'Não informado'} · devolução {row.reversal_id||'Não informada'} · fechamentos {row.closure_ids.join(', ')||'Não indicados'}</p><p>Documentos {row.document_ids.join(', ')||'Não indicados'}</p><p>Comprovante registrado: {row.receipt_path||'Não indicado'}</p></details><UnloadingFlowIssues issues={row.issues}/></article>;}
export function UnloadingFlowGroups({groups}:{groups:PeriodUnloadingFlow['supplier_groups']}){const [page,setPage]=useState(1);return <section><h4 className="font-semibold">Por fornecedor</h4>{groups.slice((page-1)*20,page*20).map(group=><article key={group.supplier_id} className="my-2 rounded border p-2"><p>{group.supplier_name||'Nome não informado'} · {group.supplier_id}</p><UnloadingFlowTotals origin={group.origin_totals} receipt={group.receipt_totals} refund={group.refund_totals} adjustment={group.adjustment_totals} net={group.net_origin_totals}/></article>)}{groups.length>20&&<><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Fornecedores anteriores</Button><Button variant="outline" disabled={page*20>=groups.length} onClick={()=>setPage(page+1)}>Próximos fornecedores</Button></>}</section>;}
export function UnloadingFlowMoneyLinks({links}:{links:PeriodUnloadingFlow['money_links']}){const [page,setPage]=useState(1);return <details><summary>Movimentos relacionados, sem duplicação ({links.length})</summary><p>O valor alocado à descarga já faz parte do movimento. Não some os dois valores nem repita este dinheiro no pacote.</p>{links.slice((page-1)*20,page*20).map(link=><article key={link.movement_id} className="my-2 border-l-2 pl-2"><p>Movimento {link.movement_id} · conta {link.bank_account_id}</p><p>Valor do movimento: {value(link.amount_cents)} · alocado aos eventos deste demonstrativo: {value(link.allocated_event_cents)}</p><p>{link.money_covered?'Coberto por fechamento':'Cobertura não comprovada'} · {link.closure_ids.join(', ')||'Sem fechamento identificado'}</p><p>Eventos {link.event_ids.join(', ')}</p><UnloadingFlowIssues issues={link.issues}/></article>)}{links.length>20&&<><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Movimentos anteriores</Button><Button variant="outline" disabled={page*20>=links.length} onClick={()=>setPage(page+1)}>Próximos movimentos</Button></>}</details>;}
export function UnloadingFlowIssues({issues}:{issues:string[]}){if(!issues.length)return null;return <details><summary>Pendências ou limites ({issues.length})</summary>{issues.map((issue,index)=><div key={`${issue}:${index}`}><p>{unloadingFlowIssueLabels[issue]||"Esta condição limita a classificação ou a cobertura deste demonstrativo."}</p><details><summary>Referência da condição</summary>{issue}</details></div>)}</details>;}
