import {useState} from 'react';
import {periodMoneyIssueLabels} from '@/lib/financial/periodMoneyIssueLabels';
import {Button} from '@/components/ui/button';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import type {PeriodMoneyPackage} from '@/lib/financial/periodMoneyPackageContract';
export function MoneyPackageClosures({rows}:{rows:PeriodMoneyPackage['accounts'][number]['closures']}){const [page,setPage]=useState(1);return <details><summary>Fechamentos e reaberturas ({rows.length})</summary>{rows.slice((page-1)*20,page*20).map(row=><article key={row.id} className="my-2 border-l-2 pl-2"><p>{row.from} a {row.to} · {row.active?'Fechamento ativo':'Fechamento reaberto ou inativo'} · {row.evidence_kind==='cash_count'?'Contagem física':row.evidence_kind==='bank_statement'?'Extrato bancário':'Evidência a revisar'}</p><p>Por {row.actor_name} ({row.actor_id}) · {row.created_at}</p><p>Motivo: {row.reason}</p><p>Fechamento {row.id}</p>{(!row.integrity.snapshot_matches_revision||!row.integrity.dependencies_match)&&<p role="alert">Os dados preservados ou suas dependências apresentam inconsistência.</p>}{row.reopening&&<p>Reaberto por {row.reopening.actor_name} ({row.reopening.actor_id}) · {row.reopening.created_at} · motivo: {row.reopening.reason} · reabertura {row.reopening.id}</p>}<details><summary>Referências preservadas</summary><p>Abertura: {row.opening_id||'Não indicada'} · fechamento anterior: {row.predecessor_id||'Não indicado'} · aprovação de cobertura: {row.coverage_approval_id||'Não indicada'} · contagem: {row.count_id||'Não indicada'}</p><p>Revisão: {row.revision}</p></details></article>)}{rows.length>20&&<><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Fechamentos anteriores</Button><Button variant="outline" disabled={page*20>=rows.length} onClick={()=>setPage(page+1)}>Próximos fechamentos</Button></>}</details>;}
const transferLabels={internal_pair:'Transferência interna comprovada',scope_boundary_out:'Saída para conta fora da seleção',scope_boundary_in:'Entrada de conta fora da seleção',cross_period:'Transferência entre períodos',in_transit:'Transferência em trânsito',needs_review:'Transferência a revisar'};
export function MoneyPackageTransfers({rows}:{rows:PeriodMoneyPackage['transfers']}){const [page,setPage]=useState(1);return <details><summary>Rastreio das transferências ({rows.length})</summary>{rows.slice((page-1)*20,page*20).map(row=><article key={row.id} className="my-2 border-l-2 pl-2"><p>{transferLabels[row.classification]} · {row.amount_cents===null?'Valor indeterminado':formatFinanceCents(row.amount_cents)}</p><p>Origem {row.source_account_id||'Não identificada'} · saída {row.outgoing_id} · {row.outgoing_on||'Data não determinada'}</p><p>Destino {row.destination_account_id||'Não identificado'} · entrada {row.incoming_id||'Não identificada'} · {row.incoming_on||'Data não determinada'}</p><p>Transferência {row.id} · fechamentos {row.source_closure_ids.join(', ')||'Não identificados'}</p>{row.issues.length>0&&<p role="alert">Esta transferência exige conferência antes de ajustar os fluxos.</p>}<MoneyPackageIssues issues={row.issues}/></article>)}{rows.length>20&&<><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Transferências anteriores</Button><Button variant="outline" disabled={page*20>=rows.length} onClick={()=>setPage(page+1)}>Próximas transferências</Button></>}</details>;}
export function MoneyPackageIssues({issues}:{issues:string[]}){if(!issues.length)return null;return <details><summary>Pendências e limites da conferência ({issues.length})</summary>{issues.map((issue,index)=><div key={`${issue}:${index}`}><p>{periodMoneyIssueLabels[issue]||"Esta condição limita a cobertura da conferência e precisa de revisão."}</p><details><summary>Referência da condição</summary>{issue}</details></div>)}</details>;}
