import {portfolioValue,type PortfolioState} from '@/hooks/useReceivablePortfolio';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';

import {portfolioStatusLabels} from '@/lib/financial/receivablePortfolioContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
function OpenBar({nominal,open}:{nominal:string|null;open:string|null}){if(nominal===null||open===null)return null;const total=BigInt(nominal),share=total===0n?0:Number(BigInt(open)*10000n/total)/100;return <div role="img" aria-label={`${share}% do valor nominal em aberto`} className="h-2 w-32 bg-muted rounded my-1"><div className="h-full bg-primary rounded" style={{width:`${share}%`}}/></div>;}
export function ReceivablePortfolioCard({state}:{state:PortfolioState}){return <Card><CardContent className="p-5 space-y-2"><p className="text-xs text-muted-foreground">Saldo a receber dos títulos ativos</p><p className="text-2xl font-bold">{portfolioValue(state,'open_cents')}</p><p className="text-xs">Vencido em {state.data?.as_of||'data a confirmar'}: {portfolioValue(state,'overdue_cents')}</p><p className="text-xs text-muted-foreground">Valores após baixas parciais; não representam saldo bancário.</p></CardContent></Card>;}
export function ReceivablePortfolioStatus({state,onManage}:{state:PortfolioState;onManage:()=>void}){const {query,data}=state;return <Card><CardHeader><CardTitle className="text-sm">Carteira de títulos ativos por status</CardTitle><Button variant="outline" onClick={onManage}>Gerenciar contas a receber</Button></CardHeader><CardContent className="space-y-3"><p>Resumo integral do servidor, por criação do título em São Paulo e cliente. Tipo de documento, categoria de despesa e centro de custo não filtram esta carteira. Baixas alocadas incluem recebimentos parciais e não representam entradas bancárias no período.</p>{query.isFetching&&<p role="status">Consultando carteira completa…</p>}{query.isError&&<p role="alert">Não foi possível consultar a carteira. <Button variant="link" onClick={()=>void query.refetch()}>Tentar carteira novamente</Button></p>}{data&&<><p>{data.total_titles} título(s) ativo(s) · {data.canceled_titles} cancelado(s) excluído(s) dos valores.</p>{!data.totals_valid&&<p role="alert">{data.invalid_titles} título(s) precisam de revisão. Os valores da carteira estão indisponíveis. Registros sem data válida aparecem como pendência mesmo com filtro de período, pois não é possível determinar a qual período pertencem.</p>}<div className="grid sm:grid-cols-3 gap-3"><p>Valor nominal ativo: <strong>{portfolioValue(state,'nominal_cents')}</strong></p><p>Baixas alocadas aos títulos ativos: <strong>{portfolioValue(state,'received_allocated_cents')}</strong></p><p>Saldo em aberto: <strong>{portfolioValue(state,'open_cents')}</strong></p></div>{data.status_rows.length?<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th>Status · parcela em aberto</th><th>Títulos</th><th>Nominal</th><th>Baixado</th><th>Em aberto</th></tr></thead><tbody>{data.status_rows.map(row=><tr key={row.status}><td>{portfolioStatusLabels[row.status]||'Status a revisar'}<OpenBar nominal={row.nominal_cents} open={row.open_cents}/></td><td>{row.count}</td><td>{row.nominal_cents===null?'A revisar':formatFinanceCents(row.nominal_cents)}</td><td>{row.received_allocated_cents===null?'A revisar':formatFinanceCents(row.received_allocated_cents)}</td><td>{row.open_cents===null?'A revisar':formatFinanceCents(row.open_cents)}</td></tr>)}</tbody></table></div>:<p>Nenhum título ativo no filtro.</p>}</>}</CardContent></Card>;}
