import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {z} from 'zod';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {readReceivableHistory,ReceivableHistoryChangedError} from '@/lib/financial/receivableHistoryClient';
import type {ReceivableHistory} from '@/lib/financial/receivableHistoryContract';
import {ReceivableHistoryEvent} from './ReceivableHistoryEvent';
const limitationLabels:Record<string,string>={capture_time_is_not_commit_time:'A data de captura não comprova quando a transação foi confirmada.',sequence_order_is_not_commit_order:'A sequência dos eventos não comprova a ordem das confirmações.',pre_baseline_history_not_certified:'O histórico anterior ao estado inicial observado não é certificado.',not_a_historical_balance:'As versões não representam saldo histórico.',payer_name_at_capture_only:'O nome do devedor corresponde à identificação preservada na captura.'};
type Props={tenant:string;actor:string};
export function ReceivableHistoryDialog({tenant,actor,onClose}:Props&{onClose:()=>void}){return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Histórico de alterações dos títulos</DialogTitle><DialogDescription>Versões capturadas dos recebíveis, incluindo títulos excluídos. Esta consulta não calcula a posição financeira de uma data passada.</DialogDescription></DialogHeader><FinanceAccessBoundary><ReceivableHistoryWorkspace key={`${tenant}:${actor}`} tenant={tenant} actor={actor}/></FinanceAccessBoundary><Button variant="outline" onClick={onClose}>Fechar histórico</Button></DialogContent></Dialog>;}
export function ReceivableHistoryWorkspace({tenant,actor}:Props){
 const [generation,setGeneration]=useState(0),[draft,setDraft]=useState(''),[filter,setFilter]=useState<string|null>(null),[paging,setPaging]=useState<{page:number;revision:string|null}>({page:1,revision:null}),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const query=useQuery({queryKey:['finance-receivable-history',tenant,actor,filter,paging.page,paging.revision,generation],queryFn:()=>readReceivableHistory({tenantId:tenant,receivableId:filter,page:paging.page,expectedRevision:paging.revision}),retry:false});
 useEffect(()=>{if(query.error instanceof ReceivableHistoryChangedError){setNotice('O histórico mudou durante a navegação. A consulta foi reiniciada na primeira página.');setGeneration(value=>value+1);setPaging({page:1,revision:null});}},[query.error]);
 const data=query.isFetching||query.isError?undefined:query.data;
 function apply(){const id=draft.trim();if(id&&!z.string().uuid().safeParse(id).success){setError('Informe um ID de título válido ou deixe o campo vazio para consultar todos.');return;}setError('');setNotice('');setFilter(id||null);setPaging({page:1,revision:null});if((id||null)===filter&&paging.page===1&&paging.revision===null)void query.refetch();}
 return <section className="space-y-3" aria-label="Consulta de alterações de recebíveis"><form className="flex flex-wrap items-end gap-2" onSubmit={event=>{event.preventDefault();apply();}}><label>ID do título (opcional)<Input value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Todos os títulos, inclusive excluídos"/></label><Button disabled={query.isFetching}>Consultar alterações</Button></form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{query.isFetching&&<p role="status">Consultando versões capturadas…</p>}{query.isError&&!(query.error instanceof ReceivableHistoryChangedError)&&<p role="alert">Não foi possível consultar o histórico. Nenhum dado anterior foi mantido como atual. <Button variant="link" onClick={()=>void query.refetch()}>Tentar histórico novamente</Button></p>}{data&&<HistoryContent data={data} onPage={page=>setPaging({page,revision:data.revision})}/>}</section>;
}
function HistoryContent({data,onPage}:{data:ReceivableHistory;onPage:(page:number)=>void}){return <div className="space-y-3">{data.coverage?<p>Captura iniciada em {data.coverage.starts_at} · {data.coverage.baseline_kind==='existing_tenant'?'Estado inicial observado de uma empresa existente':'Captura iniciada com a criação da empresa'}. O estado anterior à captura é desconhecido; a versão inicial não comprova o passado.</p>:<p role="alert">A cobertura da captura não foi estabelecida. Ausência de eventos não comprova ausência de títulos ou alterações.</p>}<p>{data.total} evento(s) capturado(s). Versões não são títulos distintos e não devem ser somadas como receita.</p><p>Datas de captura e sequência identificam o registro técnico; não comprovam quando uma transação ficou visível para outros usuários.</p>{!data.rows.length&&<p>Nenhum evento encontrado neste filtro e na cobertura informada.</p>}{data.rows.map(row=><ReceivableHistoryEvent key={row.event_order} row={row}/>)}<div className="flex gap-3 items-center"><Button variant="outline" disabled={data.page===1} onClick={()=>onPage(data.page-1)}>Página anterior</Button><span>Página {data.page} de {Math.max(1,Math.ceil(data.total/data.page_size))}</span><Button variant="outline" disabled={data.page*data.page_size>=data.total} onClick={()=>onPage(data.page+1)}>Próxima página</Button></div><p className="text-xs">Consulta gerada em {data.captured_at}. {data.receivable_id?`Título filtrado: ${data.receivable_id}`:'Todos os títulos da empresa, inclusive excluídos.'}</p>{data.limitations.length>0&&<details><summary>Limites da consulta</summary>{data.limitations.map(item=><p key={item}>{limitationLabels[item]||"Há uma limitação adicional de cobertura que exige revisão."}</p>)}</details>}</div>;}
