import type {ReceivableHistory} from '@/lib/financial/receivableHistoryContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
const operations={BASELINE:'Estado inicial observado',INSERT:'Título criado',UPDATE:'Título alterado',DELETE:'Título excluído — histórico preservado'};
const fields:Record<string,string>={amount_cents:'Valor nominal',received_cents:'Baixas projetadas',payer:'Identificação preservada do devedor',source:'Origem do título',issues:'Pendências da versão',description:'Descrição',invoice_number:'Referência',status:'Status',due_date:'Vencimento',client_id:'Devedor',updated_at:'Data de atualização',received_at:'Data de recebimento',created_at:'Data de criação'};
const issueLabels:Record<string,string>={amount_invalid:'Valor nominal inválido',received_amount_unknown:'Valor das baixas não informado',received_amount_invalid:'Valor das baixas inválido',due_date_invalid:'Vencimento inválido',client_id_invalid:'Identidade do devedor inválida',source_identity_invalid:'Identidade da origem inválida',payer_snapshot_invalid:'Identificação preservada do devedor inconsistente'};
const statuses:Record<string,string>={pending:'Pendente',invoiced:'Faturado',partial:'Parcialmente baixado',received:'Baixado integralmente',cancelled:'Cancelado'};
type Row=ReceivableHistory['rows'][number];
export function ReceivableHistoryEvent({row}:{row:Row}){return <article className="space-y-2 rounded border p-3"><h3 className="font-semibold">{operations[row.operation]}</h3><p>Título {row.receivable_id} · captura {row.captured_at}</p><p>{row.actor_kind==='system'?'Origem: sistema':`Usuário autenticado: ${row.actor_name||'Nome não informado'} (${row.actor_id||'ID não informado'})`}</p>{row.changed_fields.length>0&&<p>Campos alterados: {row.changed_fields.map(field=>fields[field]||'Outro campo do título').join(', ')}</p>}<div className="grid gap-3 sm:grid-cols-2"><Snapshot label="Antes" snapshot={row.before}/><Snapshot label="Depois" snapshot={row.after}/></div><details><summary>Referências da captura</summary><p>Evento {row.event_order} · transação {row.transaction_id}</p><p>Campos: {row.changed_fields.join(', ')||'Sem comparação de campos'}</p></details></article>;}
function Snapshot({label,snapshot}:{label:string;snapshot:Row['before']}){const value=(amount:string|null)=>amount===null?'Indeterminado':formatFinanceCents(amount);return <section><h4 className="font-medium">{label}</h4>{snapshot?<><p>{snapshot.description||'Descrição não informada'} · referência {snapshot.invoice_number||'Não informada'}</p><p>Valor nominal: {value(snapshot.amount_cents)}</p><p>Baixas projetadas: {value(snapshot.received_cents)}</p><p>Vencimento: {snapshot.due_date||'Não informado'} · status: {snapshot.status?(statuses[snapshot.status]||'Status a revisar'):'Não informado'}</p><p>Devedor: {snapshot.payer?.company_name||'Nome não comprovado'} · {snapshot.client_id||'ID não informado'}</p>{snapshot.issues.length>0&&<p role="alert">Esta versão contém campos ou vínculos indeterminados e precisa de revisão.</p>}<details><summary>Origens preservadas</summary>{Object.entries(snapshot.source).map(([key,id])=><p key={key}>{({order_id:'Pedido',fiscal_document_id:'Documento fiscal',load_id:'Carga',client_invoice_id:'Fatura',closing_report_id:'Fechamento de cobrança'} as Record<string,string>)[key]||'Origem'}: {id||'Não informada'}</p>)}{snapshot.issues.map(issue=><p key={issue}>{issueLabels[issue]||"Condição da versão precisa de revisão"}</p>)}</details></>:<p>Sem versão neste lado do evento.</p>}</section>;}
