import {recordedCostCategoryLabels as labels} from '@/lib/financial/recordedCostCategories';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import type {RecordedCostState} from '@/hooks/useRecordedCostSummary';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
function Total({state}:{state:RecordedCostState}){return <>{state.query.isFetching||state.query.isPending?'Consultando…':state.query.isError?'Indisponível':!state.data?.totals_valid||state.data.total_cents===null?'A revisar':formatFinanceCents(state.data.total_cents)}</>;}
export function RecordedCostCard({state}:{state:RecordedCostState}){return <Card><CardContent className="p-5 space-y-2"><p className="text-xs text-muted-foreground">Custos registrados na cobertura atual</p><p className="text-2xl font-bold"><Total state={state}/></p><p className="text-xs">Despesas registradas e remuneração da folha. Custo não é saída bancária.</p></CardContent></Card>;}
function Breakdown({title,rows,total}:{title:string;rows:{key:string;label:string;count:number;amount:string|null}[];total:string|null}){return <section className="space-y-2"><h4 className="font-medium">{title}</h4>{!rows.length?<p>Nenhum registro neste grupo.</p>:rows.map(row=><div key={row.key} className="rounded border p-2"><p>{row.label} · {row.count} registro(s) · {row.amount===null?'A revisar':formatFinanceCents(row.amount)}</p>{total!==null&&row.amount!==null&&BigInt(total)>0n&&<div role="img" aria-label={`Participação de ${row.label} nos custos registrados`} className="h-2 bg-muted rounded"><div className="bg-primary h-full rounded" style={{width:`${Number(BigInt(row.amount)*10000n/BigInt(total))/100}%`}}/></div>}</div>)}</section>;}
export function RecordedCostSummary({state,onManage}:{state:RecordedCostState;onManage:()=>void}){const {query,data}=state;return <Card><CardHeader><CardTitle className="text-sm">Composição dos custos registrados</CardTitle><Button variant="outline" onClick={onManage}>Consultar despesas registradas</Button></CardHeader><CardContent className="space-y-3"><p>Cobertura: lotes de despesas, gastos avulsos e remuneração da folha. Não representa o custo global da empresa nem o caixa. Despesas antigas de motoristas, ordens de manutenção, composição de acertos e reembolsos/adiantamentos da folha ficam fora desta soma para evitar duplicação.</p><p>Filtros: data, categoria e centro de custo. Cliente e tipo de documento fiscal não filtram estes custos.</p>{query.isFetching&&<p role="status">Consultando todos os custos da cobertura…</p>}{query.isError&&<p role="alert">Não foi possível consultar os custos. <Button variant="link" onClick={()=>void query.refetch()}>Tentar custos novamente</Button></p>}{data&&<><p>{data.total_count} registro(s) · {data.cancelled_count} cancelado(s) sem contribuição ao custo.</p>{!data.totals_valid&&<p role="alert">{data.invalid_count} registro(s) precisam de revisão, incluindo {data.payroll_unclassified_count} item(ns) de folha sem classificação. Totais indisponíveis; registros sem data válida permanecem como pendência mesmo com filtro temporal.</p>}<p>Total desta cobertura: <strong><Total state={state}/></strong></p><p>{data.recorded_date_count} registro(s) usam data de registro. A distribuição mensal segue a data disponível na fonte, sem presumir data bancária.</p><div className="grid lg:grid-cols-3 gap-3"><Breakdown title="Por categoria" total={data.total_cents} rows={data.categories.map(row=>({key:row.category||'unknown',label:row.category?(labels[row.category]||row.category):'Categoria a revisar',count:row.item_count,amount:row.amount_cents}))}/><Breakdown title="Por centro de custo" total={data.total_cents} rows={data.cost_centers.map(row=>({key:row.cost_center_id||'unassigned',label:row.cost_center_name||'Sem centro identificado',count:row.item_count,amount:row.amount_cents}))}/><Breakdown title="Por mês" total={data.total_cents} rows={data.months.map(row=>({key:row.month||'undated',label:row.month||'Sem data válida',count:row.item_count,amount:row.amount_cents}))}/></div>{data.total_count===0&&<p>Não há registros nesta cobertura e filtro. Isso não comprova ausência de custos fora das fontes incorporadas.</p>}</>}</CardContent></Card>;}
