import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {coveragePendingSchema,coverageBlockingLabels,type CoveragePending} from '@/lib/financial/statementCoverageContract';
import {readStatementCoverage,submitStatementCoverage,CoverageRejectedError} from '@/lib/financial/statementCoverageClient';
type Props={tenant:string;actor:string;account:string;from:string;to:string};
const statuses={not_approved:'Cobertura ainda não aprovada',approved:'Cobertura aprovada pelo usuário',needs_review:'Aprovação com evidências alteradas',reversed:'Aprovação desfeita'};
const errors:Record<string,string>={finance_coverage_evidence_changed:'As evidências mudaram. Atualize e faça uma nova revisão.',finance_coverage_not_eligible:'Existem impedimentos para aprovar esta cobertura. Atualize e confira as pendências.',finance_coverage_approval_exists:'Já existe uma aprovação ativa. Confira o histórico.',finance_invalid_coverage_declaration:'Confirme separadamente a origem dos arquivos e a cobertura integral do período.',finance_coverage_already_reversed:'Esta aprovação já foi desfeita. Confira o histórico.',finance_coverage_approval_not_found:'A aprovação não foi encontrada nesta empresa.',finance_access_denied:'Seu acesso financeiro não foi confirmado.'};
const explain=(e:unknown)=>e instanceof Error?(errors[e.message]||'Não foi possível confirmar a revisão da cobertura.'):'Não foi possível confirmar a revisão da cobertura.';
export function StatementCoverageReview(props:Props){const [open,setOpen]=useState(false);return <section aria-label="Aprovação de cobertura dos extratos" className="rounded border p-3 space-y-2"><h3 className="font-medium">Aprovação de cobertura dos extratos</h3>{!open?<Button variant="outline" onClick={()=>setOpen(true)}>Revisar cobertura dos extratos</Button>:<StatementCoverageWorkspace key={`${props.tenant}:${props.actor}:${props.account}:${props.from}:${props.to}`} {...props}/>}</section>;}
export function StatementCoverageWorkspace({tenant,actor,account,from,to}:Props){
 const key=`finance-statement-coverage:${tenant}:${actor}:${account}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=coveragePendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.account!==account||pending.command.tenant_id!==tenant||(pending.kind==='approve'&&pending.command.account_id!==account))throw new Error();return {pending};}catch{return {error:'Não foi possível recuperar o pedido. Novas aprovações e correções estão bloqueadas; confira o histórico.'};}});
 const [pending,setPending]=useState<CoveragePending|undefined>(restored.pending),[review,setReview]=useState<CoveragePending>(),[reverseId,setReverseId]=useState('');
 const [originals,setOriginals]=useState(false),[complete,setComplete]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const live=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const query=useQuery({queryKey:['finance-statement-coverage-review',tenant,actor,account,from,to],queryFn:()=>readStatementCoverage(tenant,account,from,to),retry:false});
 const data=query.error||query.isFetching?undefined:query.data,mayApprove=!!data?.can_approve&&data.blocking_reasons.length===0&&!data.approval,mayReverse=!!data?.approval&&data.approval.id===reverseId;
 const reviewCurrent=!!review&&!!data&&(review.kind==='approve'?mayApprove&&review.command.revision===data.revision:mayReverse&&review.command.approval_id===data.approval?.id);
 function prepare(){if(restored.error||(!reverseId&&!mayApprove)||(reverseId&&!mayReverse))return;const parsed=coveragePendingSchema.safeParse(reverseId?{kind:'reverse',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),approval_id:reverseId,reason}}:{kind:'approve',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),account_id:account,from,to,revision:data!.revision,reason,originals_obtained_from_bank:originals,complete_period_confirmed:complete}});if(parsed.success)setReview(parsed.data);}
 async function submit(){
  if(sending.current||restored.error)return;const original=pending||review;if(!original||(!pending&&!reviewCurrent))return;
  if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,account,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma aprovação ou correção foi enviada.');return;}setPending(original);}
  sending.current=true;setBusy(true);setError('');
  try{await submitStatementCoverage(original);sessionStorage.removeItem(key);for(const prefix of ['finance-statement-coverage-review','finance-account-period','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});if(live.current){setPending(undefined);setReview(undefined);setReverseId('');setReason('');setOriginals(false);setComplete(false);setNotice(original.kind==='approve'?'Cobertura aprovada pelo usuário, com declarações e autoria preservadas. A autenticidade bancária não foi atestada e o período continua aberto.':'Aprovação desfeita. Declarações e autoria permanecem no histórico; o período continua aberto.');}}
  catch(e){if(e instanceof CoverageRejectedError&&!pending){try{sessionStorage.removeItem(key);if(live.current){setPending(undefined);setReview(undefined);setError(explain(e));}void query.refetch();}catch{if(live.current)setError('Pedido recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}else if(live.current)setError(`${explain(e)} O pedido original foi preservado para retomada.`);}
  finally{sending.current=false;if(live.current)setBusy(false);}
 }
 return <div className="space-y-3 text-sm"><p>Esta é uma revisão humana da cobertura dos arquivos. As declarações do responsável não atestam autenticidade bancária e não fecham o período.</p><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar cobertura</Button>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando evidências e aprovações…</p>}{query.isError&&<p role="alert">Não foi possível consultar a cobertura. Atualize antes de enviar outra decisão.</p>}
 {data&&<><h4 className="font-medium">{statuses[data.status]}</h4><p>Período: {data.from} a {data.to} · {data.evidence.qualified_source_count} arquivo(s) com conta e linhas conferidas.</p><p>Dias sem cobertura integral declarada: {data.evidence.missing_declared_days} · diferença entre saldos e movimentação: {data.evidence.difference_cents===null?'não comparável':formatFinanceCents(data.evidence.difference_cents)}</p>
 {data.blocking_reasons.length>0&&<ul role="alert" className="list-disc pl-5">{data.blocking_reasons.map(reason=><li key={reason}>{coverageBlockingLabels[reason]}</li>)}</ul>}
 {data.status==='needs_review'&&<p role="alert">As evidências mudaram depois da aprovação. Revise os arquivos e desfaça a aprovação anterior antes de aprovar novamente.</p>}
 <details><summary>Fontes dos saldos neste período</summary>{data.evidence.anchors.map(anchor=><p key={`${anchor.verification_id}:${anchor.day}`}>{anchor.day} · {anchor.file_name} · {formatFinanceCents(anchor.cents)}</p>)}</details>
 <section aria-label="Histórico permanente de cobertura"><h4>Histórico de aprovações manuais</h4>{data.history.length===0?<p>Nenhuma aprovação anterior.</p>:data.history.map(item=><article key={item.id} className="rounded border border-amber-600 p-2 my-2"><p>Aprovação manual · {item.reversal?'Desfeita':'Sem reversão'} · {item.period_start} a {item.period_end}</p><p>Por {item.actor_name} ({item.actor_id}) · {item.created_at}</p><p>Motivo: {item.reason}</p><p>Declarou que obteve os originais do banco e conferiu o período completo. Autenticidade bancária não atestada.</p><details><summary>Evidências preservadas na aprovação</summary><p>{item.snapshot.evidence.qualified_source_count} arquivo(s) conferido(s); {item.snapshot.evidence.missing_declared_days} dia(s) sem cobertura declarada.</p>{item.snapshot.evidence.anchors.map(anchor=><p key={`${anchor.verification_id}:${anchor.day}`}>{anchor.day} · {anchor.file_name} · {formatFinanceCents(anchor.cents)}</p>)}</details>{item.reversal&&<><p>Desfeita por {item.reversal.actor_name} ({item.reversal.actor_id}) · {item.reversal.created_at}</p><p>Motivo da correção: {item.reversal.reason}</p></>}</article>)}</section>
 {!pending&&data.approval&&<Button variant="outline" disabled={busy||!!restored.error} onClick={()=>{setReverseId(data.approval!.id);setReview(undefined);setReason('');}}>Desfazer aprovação ativa</Button>}
 </>}
 {pending?<><p>Pedido original de {pending.kind==='approve'?'aprovação':'correção'}: {pending.command.request_id}</p>{pending.kind==='approve'&&<p>Período original: {pending.command.from} a {pending.command.to}. As duas declarações originais serão preservadas.</p>}<p>Motivo preservado: {pending.command.reason}</p><Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar decisão de cobertura</Button></>:(mayApprove||mayReverse)&&<>
 {!reverseId&&<><label className="flex gap-2"><input type="checkbox" checked={originals} disabled={!!review} onChange={e=>setOriginals(e.target.checked)}/>Declaro que obtive os arquivos originais diretamente do banco.</label><label className="flex gap-2"><input type="checkbox" checked={complete} disabled={!!review} onChange={e=>setComplete(e.target.checked)}/>Conferi que os arquivos abrangem integralmente o período selecionado, sem omissões conhecidas.</label></>}
 <label>Motivo da decisão<Textarea maxLength={2000} disabled={!!review} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 {review?<><p>Revisão final: {review.kind==='approve'?`aprovar a cobertura de ${review.command.from} a ${review.command.to} pelas duas declarações acima`:'desfazer a aprovação selecionada'}. Esta decisão não fecha o período.</p>{!reviewCurrent&&<p role="alert">O contexto mudou. Volte e revise novamente.</p>}<Button disabled={busy||!reviewCurrent||!!restored.error} onClick={()=>void submit()}>Confirmar decisão de cobertura</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão</Button></>:<Button disabled={reason.trim().length<10||(!reverseId&&(!originals||!complete))||!!restored.error} onClick={prepare}>Revisar decisão de cobertura</Button>}
 {reverseId&&<Button variant="outline" disabled={busy} onClick={()=>{setReverseId('');setReview(undefined);}}>Cancelar correção</Button>}
 </>}
 </div>;
}
