import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {StockAcquisitionAssociation} from './StockAcquisitionAssociation';
import {readStockAcquisitionInventory} from '@/lib/financial/stockAcquisitionClient';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
export function StockAcquisitionInventory({tenant,actor}:{tenant:string;actor:string}){const [open,setOpen]=useState(false);return <section className="border rounded p-3"><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Ocultar aquisições de estoque':'Conferir aquisições de estoque'}</Button>{open&&<FinanceAccessBoundary><StockAcquisitionInventoryWorkspace key={`${tenant}:${actor}`} tenant={tenant} actor={actor}/></FinanceAccessBoundary>}</section>;}
export function StockAcquisitionInventoryWorkspace({tenant,actor}:{tenant:string;actor:string}){const [filter,setFilter]=useState({page:1,search:''}),[draft,setDraft]=useState('');const query=useQuery({queryKey:['finance-stock-cost-inventory',tenant,actor,filter],queryFn:()=>readStockAcquisitionInventory(tenant,filter.page,filter.search),retry:false}),data=query.isError||query.isFetching?undefined:query.data;return <div className="space-y-3 text-sm"><h3 className="font-semibold">Entradas de estoque e custos de aquisição</h3><p>Entradas da empresa, inclusive sem data ou valor válido. Associe compras comprovadas a custos existentes. Esta lista não certifica saldo físico nem representa custos adicionais.</p><form onSubmit={event=>{event.preventDefault();setFilter({page:1,search:draft});if(filter.page===1&&filter.search===draft)void query.refetch();}}><label>Buscar entrada de estoque<Input maxLength={200} value={draft} onChange={event=>setDraft(event.target.value)}/></label><Button disabled={query.isFetching}>Buscar entradas</Button></form>{query.isFetching&&<p role="status">Consultando entradas…</p>}{query.isError&&<p role="alert">Não foi possível consultar as entradas. Tente buscar novamente.</p>}{data&&<><p>{data.total} entrada(s) · {data.associated_count} associada(s) · {data.unassociated_count} sem associação.</p>{!data.rows.length&&<p>Nenhuma entrada nesta página.</p>}{data.rows.map(row=><article key={row.id} className="border rounded p-2"><h4>{row.item_name||'Item não identificado'}</h4><p>Entrada: {row.id} · item: {row.stock_item_id}</p><p>{row.movement_date||'Sem data válida'} · quantidade: {row.quantity||'Não determinada'} · valor declarado: {row.total_cost_cents===null?'A revisar':formatFinanceCents(row.total_cost_cents)}</p><p>{row.reason==='purchase'?'Compra declarada':'Origem exige revisão: não declarada como compra'}</p>{row.active_link_id&&<p className="text-amber-700">Associação manual registrada. Autoria e motivo disponíveis no histórico.</p>}<StockAcquisitionAssociation tenant={tenant} actor={actor} inbound={row.id}/></article>)}<div className="flex gap-2"><Button variant="outline" disabled={filter.page===1} onClick={()=>setFilter({...filter,page:filter.page-1})}>Entradas anteriores</Button><span>Página {data.page} · até 30 registros</span><Button variant="outline" disabled={filter.page*30>=data.total} onClick={()=>setFilter({...filter,page:filter.page+1})}>Próximas entradas</Button></div></>}</div>;}
