function decimal(value:string){const clean=value.trim();if(!/^[0-9]+(\.[0-9]+)?$/.test(clean))return null;const [whole,fraction='']=clean.split('.');return (whole.replace(/^0+(?=\d)/,'')||'0')+'.'+fraction.replace(/0+$/,'');}
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {Input} from '@/components/ui/input';
import {stockAcquisitionIssueLabels,stockAcquisitionPendingSchema,type StockAcquisitionPending} from '@/lib/financial/stockAcquisitionContract';
import {readStockAcquisitionAssociation,submitStockAcquisitionAssociation,StockAcquisitionRejectedError} from '@/lib/financial/stockAcquisitionClient';
type Props={tenant:string;actor:string;inbound:string;onRecorded?:()=>void};
export function StockAcquisitionAssociation(props:Props){const [open,setOpen]=useState(false);return <><Button size="sm" variant="outline" onClick={()=>setOpen(true)}>Associar aquisição de estoque a custo existente</Button>{open&&<FinanceAccessBoundary><Dialog open onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Associação da aquisição de estoque</DialogTitle><DialogDescription>Identifique a mesma aquisição de estoque em um custo existente, com fornecedor cadastrado. Sem novo custo ou baixa.</DialogDescription></DialogHeader><StockAcquisitionAssociationWorkspace key={`${props.tenant}:${props.actor}:${props.inbound}`} {...props}/></DialogContent></Dialog></FinanceAccessBoundary>}</>;}
export function StockAcquisitionAssociationWorkspace({tenant,actor,inbound,onRecorded}:Props){
 const key=`finance-stock-acquisition-association:${tenant}:${actor}:${inbound}`;
 const [restored]=useState(()=>{try{const raw=sessionStorage.getItem(key);if(!raw)return {};const saved=JSON.parse(raw),pending=stockAcquisitionPendingSchema.parse(saved.pending);if(saved.actor!==actor||saved.inbound!==inbound||pending.command.tenant_id!==tenant||(pending.kind==='associate'&&pending.command.inbound_movement_id!==inbound))throw new Error();return {pending};}catch{return {error:'Não foi possível recuperar o pedido. Novas associações e correções estão bloqueadas; confira o histórico.'};}});
 const [pending,setPending]=useState<StockAcquisitionPending|undefined>(restored.pending),[review,setReview]=useState<StockAcquisitionPending>(),[choice,setChoice]=useState(''),[reverse,setReverse]=useState(false),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(restored.error||''),[notice,setNotice]=useState(''),[fingerprint,setFingerprint]=useState(''),[search,setSearch]=useState(''),[draftSearch,setDraftSearch]=useState(''),[quantity,setQuantity]=useState(''),[document,setDocument]=useState('');
 const alive=useRef(true),sending=useRef(false),cache=useQueryClient();useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const query=useQuery({queryKey:['finance-stock-acquisition-context',tenant,actor,inbound,page,search],queryFn:()=>readStockAcquisitionAssociation(tenant,inbound,page,search),retry:false});
 const data=query.isError||query.isFetching?undefined:query.data,selected=data?.candidates.find(row=>row.cost_id===choice);
 const canAssociate=!!data&&!data.active_link&&!!selected&&!selected.issue&&!!selected.supplier_id&&!!selected.document_number&&!!data.source.quantity&&data.source.movement_type==="inbound"&&data.source.reason==="purchase"&&decimal(quantity)!==null&&decimal(quantity)===decimal(data.source.quantity)&&document===selected.document_number&&confirmed,canReverse=!!data?.active_link&&data.active_link.dependencies.ready&&data.active_link.dependencies.blocking_count===0;
 const current=JSON.stringify({source:data?.source,selected,active:data?.active_link});
 const reviewCurrent=!!review&&current===fingerprint&&(review.kind==='associate'?canAssociate&&review.command.cost_id===choice&&review.command.revision===selected?.revision:canReverse&&review.command.link_id===data?.active_link?.id&&review.command.revision===data?.active_link?.revision);
 function prepare(){if(restored.error||(reverse?!canReverse:!canAssociate))return;const parsed=stockAcquisitionPendingSchema.safeParse(reverse?{kind:'reverse',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),link_id:data!.active_link!.id,revision:data!.active_link!.revision,reason}}:{kind:'associate',command:{version:1,tenant_id:tenant,request_id:crypto.randomUUID(),inbound_movement_id:inbound,cost_id:choice,revision:selected!.revision,reason,same_purchase_confirmed:true,quantity:quantity.trim(),document_number:document}});if(parsed.success){setReview(parsed.data);setFingerprint(current);}}
 async function submit(){if(sending.current||restored.error)return;const original=pending||review;if(!original||(!pending&&!reviewCurrent))return;if(!pending){try{sessionStorage.setItem(key,JSON.stringify({actor,inbound,pending:original}));}catch{setError('Não foi possível preservar o pedido. Nenhuma decisão foi enviada.');return;}setPending(original);}sending.current=true;setBusy(true);setError('');
  try{const result=await submitStockAcquisitionAssociation(original);if(result.inbound_movement_id!==inbound)throw new Error('Resposta fora da entrada de estoque.');sessionStorage.removeItem(key);for(const prefix of ['finance-stock-acquisition-context','finance-stock-consumption-context','finance-stock-consumption-preview','finance-stock-cost-inventory','finance-maintenance-direct-inbound-context','finance-maintenance-labor-context','finance-legacy-cost-context','finance-legacy-cost-inventory','finance-maintenance-cost-context','finance-expenses','finance-recorded-cost-summary','finance-audit'])void cache.invalidateQueries({queryKey:[prefix]});onRecorded?.();if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setReverse(false);setConfirmed(false);setReason('');setNotice(original.kind==='associate'?'Associação confirmada pelo servidor. Nenhum dinheiro ou obrigação foi criado.':'Associação desfeita. Custos originais, dinheiro e obrigações foram preservados.');}}
  catch(e){if(e instanceof StockAcquisitionRejectedError&&!pending){try{sessionStorage.removeItem(key);if(alive.current){setPending(undefined);setReview(undefined);setChoice('');setError(stockAcquisitionIssueLabels[e.message]||'A decisão foi recusada. Atualize e revise a entrada, o custo escolhido e o cadastro do fornecedor.');}void query.refetch();}catch{if(alive.current)setError('Pedido recusado, mas a recuperação local não pôde ser atualizada. Confira o histórico.');}}else if(alive.current)setError('Não foi possível confirmar a resposta. O pedido original foi preservado para retomada.');}
  finally{sending.current=false;if(alive.current)setBusy(false);}
 }
 const issue=(value:string)=>stockAcquisitionIssueLabels[value]||'Esta origem exige revisão de compatibilidade e de vínculos antes de ser associada.';
 return <div className="space-y-3 text-sm"><p>Associe esta entrada de compra ao custo já registrado da mesma aquisição. Confira quantidade, documento e fornecedor por ID. Não cria custo, pagamento ou obrigação e não altera o estoque físico. Desfazer o vínculo preserva a compra e exige resolver atribuições dependentes primeiro.</p><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{setReview(undefined);void query.refetch();}}>Atualizar custos e vínculos</Button>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{query.isFetching&&<p role="status">Consultando aquisição de estoque e custos…</p>}{query.isError&&<p role="alert">Não foi possível consultar a aquisição de estoque. Atualize antes de uma nova decisão.</p>}
 <form className="flex gap-2 items-end" onSubmit={event=>{event.preventDefault();setPage(1);setChoice("");setReview(undefined);setSearch(draftSearch);if(search===draftSearch&&page===1)void query.refetch();}}><label>Buscar custo da aquisição de estoque<Input maxLength={200} disabled={busy||!!pending} value={draftSearch} onChange={event=>setDraftSearch(event.target.value)}/></label><Button disabled={busy||!!pending||query.isFetching}>Buscar custos</Button></form>{data&&<><h3 className="font-medium">Entrada de estoque: {data.source.item_name||"Item não identificado"}</h3><p>Entrada: {data.source.id} · item: {data.source.stock_item_id}</p><p>O total considera quantidade × preço unitário declarado, arredondado em centavos.</p><p>Data registrada: {data.source.movement_date||"Sem data válida"}</p><p>Quantidade na origem: {data.source.quantity||"Não determinada"} · unitário: {data.source.unit_cost_decimal!==null?`R$ ${data.source.unit_cost_decimal.replace(".",",")}`:data.source.unit_cost_cents===null?"Não determinado":formatFinanceCents(data.source.unit_cost_cents)} · total da entrada: {data.source.total_cost_cents===null?"Não determinado":formatFinanceCents(data.source.total_cost_cents)}</p>{(data.source.movement_type!=="inbound"||data.source.reason!=="purchase")&&<p role="alert">Esta origem não é uma entrada explicitamente registrada como compra. Revise o registro operacional.</p>}{data.active_link&&<p className="border border-amber-600 p-2">Associação manual ativa: custo {data.active_link.cost_id} · fornecedor {data.active_link.supplier_id} · {formatFinanceCents(data.active_link.amount_cents)} · por {data.active_link.actor_name} ({data.active_link.actor_id}) · {data.active_link.created_at}. Motivo: {data.active_link.reason}</p>}
 {data.active_link&&!canReverse&&<p role="alert">A reversão depende de conferir e resolver as atribuições desta aquisição. Pendências: {data.active_link.dependencies.blocking_count}. Atualize o contexto antes de corrigir.</p>}<section aria-label="Histórico permanente da aquisição de estoque"><h3>Histórico de associações manuais</h3>{data.history.rows.length===0?<p>Nenhuma associação nesta página.</p>:data.history.rows.map(item=><article key={item.id} className="rounded border border-amber-600 p-2"><p>Associação manual · {item.reversal?'Desfeita':'Sem reversão'} · {formatFinanceCents(item.amount_cents)} · custo {item.cost_id} · fornecedor {item.supplier_id}</p><p>Por {item.actor_name} ({item.actor_id}) · {item.created_at}</p><p>Motivo: {item.reason}</p>{item.reversal&&<><p>Desfeita por {item.reversal.actor_name} ({item.reversal.actor_id}) · {item.reversal.created_at}</p><p>Motivo: {item.reversal.reason}</p></>}</article>)}</section>
 {!pending&&data.active_link&&<Button variant="outline" disabled={busy||!!restored.error||!canReverse} onClick={()=>{setReverse(true);setReview(undefined);setReason('');}}>Desfazer associação ativa</Button>}
 {!pending&&!reverse&&!data.active_link&&<><fieldset disabled={busy||!!review||!!restored.error}><legend>Custos existentes para revisão da aquisição de estoque</legend>{data.candidates.map(row=><label className="flex gap-2 border rounded p-2" key={row.cost_id}><input type="radio" name="legacy-cost" disabled={!!row.issue||!row.supplier_id||!row.document_number||data.source.movement_type!=="inbound"||data.source.reason!=="purchase"} checked={choice===row.cost_id} onChange={()=>setChoice(row.cost_id)}/><span>{row.description} · {row.occurred_on||'Sem data válida'} · {formatFinanceCents(row.amount_cents)}<br/>Fornecedor cadastrado: {row.supplier_name||"Não identificado"} · ID: {row.supplier_id||"Ausente"}<br/>Documento do custo: {row.document_number||"Ausente"}<br/>Custo: {row.cost_id} · lote: {row.batch_id}{row.issue&&<p>{issue(row.issue)}</p>}</span></label>)}</fieldset>{!data.total&&<p>Nenhum custo elegível. Revise as origens existentes; isso não indica que é necessário registrar o gasto novamente.</p>}</>}
 <div className="flex gap-2 items-center"><Button variant="outline" disabled={page===1||busy||!!review} onClick={()=>{setChoice('');setPage(page-1);}}>Vínculos anteriores</Button><span>Página {page} · {data.total} custo(s), {data.history.total} associação(ões)</span><Button variant="outline" disabled={page*30>=Math.max(data.total,data.history.total)||busy||!!review} onClick={()=>{setChoice('');setPage(page+1);}}>Próximos vínculos</Button></div></>}
 {pending?<><p>Pedido original: {pending.command.request_id} · motivo: {pending.command.reason}</p>{pending.kind==='associate'&&<p>Custo original: {pending.command.cost_id} · quantidade: {pending.command.quantity} · documento: {pending.command.document_number} · classificação: aquisição de estoque.</p>}<Button disabled={busy||!!restored.error} onClick={()=>void submit()}>Retomar associação ou correção de aquisição de estoque</Button></>:(reverse?canReverse:!!selected)&&<>{!reverse&&<><label>Quantidade da aquisição de estoque<Input inputMode="decimal" disabled={!!review} value={quantity} onChange={event=>setQuantity(event.target.value.replace(",","."))}/></label><label>Documento da aquisição de estoque<Input maxLength={200} disabled={!!review} value={document} onChange={event=>setDocument(event.target.value)}/></label><label className="flex gap-2"><input type="checkbox" disabled={!!review} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Conferi que esta entrada e o custo escolhido representam a mesma compra, com a quantidade, o documento e o fornecedor indicados.</label></>}<label>Motivo da associação ou correção de aquisição de estoque<Textarea maxLength={2000} disabled={!!review} value={reason} onChange={event=>setReason(event.target.value)}/></label>{review?<><p>Revisão final: {review.kind==='associate'?`associar a entrada ${inbound}, quantidade ${review.command.quantity}, documento ${review.command.document_number}, ao custo ${review.command.cost_id}, fornecedor ${selected?.supplier_name||"não identificado"} (${selected?.supplier_id||"sem cadastro"})`:'desfazer somente a associação ativa'}.</p>{!reviewCurrent&&<p role="alert">O contexto mudou. Volte e revise novamente.</p>}<Button disabled={busy||!reviewCurrent||!!restored.error} onClick={()=>void submit()}>Confirmar associação ou correção de aquisição de estoque</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(undefined)}>Voltar à revisão</Button></>:<Button disabled={reason.trim().length<10||(!reverse&&!canAssociate)||!!restored.error} onClick={prepare}>Revisar associação ou correção de aquisição de estoque</Button>}{reverse&&<Button variant="outline" disabled={busy} onClick={()=>{setReverse(false);setReview(undefined);}}>Cancelar correção</Button>}</>}
 </div>;
}
