import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {freightStateLabels,freightIssueLabels,freightStates,type FreightState} from '@/lib/financial/unbilledFreightContract';
import {readUnbilledFreightOrigins,readUnbilledFreightSummary} from '@/lib/financial/unbilledFreightClient';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {UnbilledFreightSummary} from './UnbilledFreightSummary';
type Props={tenant:string;actor:string;clients:{id:string;label:string}[]};
export function UnbilledFreightPanel(props:Props){return <Workspace key={`${props.tenant}:${props.actor}`} {...props}/>;}
function Workspace({tenant,actor,clients}:Props){
 const [draft,setDraft]=useState({from:'',to:'',client:'all'}),[filters,setFilters]=useState({from:null as string|null,to:null as string|null,client:null as string|null}),[list,setList]=useState({state:'review' as FreightState|null,page:1});
 const summary=useQuery({queryKey:['finance-unbilled-freight-summary',tenant,actor,filters.from,filters.to,filters.client],queryFn:()=>readUnbilledFreightSummary(tenant,filters),retry:false});
 const origins=useQuery({queryKey:['finance-unbilled-freight-origins',tenant,actor,filters.from,filters.to,filters.client,list.state,list.page],queryFn:()=>readUnbilledFreightOrigins(tenant,filters,list.state,list.page),retry:false});
 const data=summary.isFetching||summary.isError?undefined:summary.data,rows=origins.isFetching||origins.isError?undefined:origins.data;
 function apply(){const next={from:draft.from||null,to:draft.to||null,client:draft.client==='all'?null:draft.client};setFilters(next);setList({...list,page:1});if(JSON.stringify(next)===JSON.stringify(filters)){void summary.refetch();void origins.refetch();}}
 return <Card><CardHeader><CardTitle className="text-sm">Previsão de fretes ainda não faturados</CardTitle></CardHeader><CardContent className="space-y-3"><p>Filtros próprios desta previsão: data de emissão da NF original ou data de registro da tentativa de reentrega em São Paulo. Não usam os filtros dos painéis acima. A cobertura é parcial e não representa dinheiro recebido, título a receber confirmado ou saldo bancário.</p><form className="grid sm:grid-cols-4 gap-2 items-end" onSubmit={event=>{event.preventDefault();apply();}}><label>Origem do frete — início<Input type="date" value={draft.from} onChange={event=>setDraft({...draft,from:event.target.value})}/></label><label>Origem do frete — fim<Input type="date" min={draft.from||undefined} value={draft.to} onChange={event=>setDraft({...draft,to:event.target.value})}/></label><label>Cliente da previsão<select className="block border rounded p-2 w-full" value={draft.client} onChange={event=>setDraft({...draft,client:event.target.value})}><option value="all">Todos</option>{clients.map(client=><option key={client.id} value={client.id}>{client.label}</option>)}</select></label><Button type="submit" disabled={summary.isFetching||origins.isFetching}>Consultar previsão de frete</Button></form>{summary.isFetching&&<p role="status">Consultando previsão de fretes…</p>}{summary.isError&&<p role="alert">Não foi possível consultar a previsão. Nenhum valor zero foi presumido.</p>}{data&&<UnbilledFreightSummary data={data}/>}
 <section aria-label="Origens e pendências de frete" className="space-y-3 border-t pt-3"><h3 className="font-medium">Origens e pendências da previsão</h3><label>Estado das origens<select className="ml-2 border rounded p-2" value={list.state||'all'} onChange={event=>setList({state:event.target.value==='all'?null:event.target.value as FreightState,page:1})}><option value="all">Todos os estados</option>{freightStates.map(state=><option value={state} key={state}>{freightStateLabels[state]}</option>)}</select></label><p>O estado filtra apenas esta lista. Os totais acima consideram todos os estados nas datas e no cliente escolhidos.</p>{origins.isFetching&&<p role="status">Consultando origens da página…</p>}{origins.isError&&<p role="alert">Não foi possível consultar as origens. A falha não representa ausência de pendências.</p>}{rows&&<><p>{rows.total} origem(ns) nesta seleção de estado.</p>{rows.rows.length?<ul className="space-y-2">{rows.rows.map(row=><li className="rounded border border-amber-600 p-3" key={`${row.document_id}:${row.attempt_id||'original'}`}><p className="font-medium">{row.attempt_id?'Tentativa de reentrega':'Frete da NF original'} · {freightStateLabels[row.state]}</p><p>{row.date_basis==='invoice_issue_date'?'Emissão da NF':'Registro da tentativa'}: {row.origin_date||'Sem data válida'}</p><p>{row.freight_cents===null?'Frete não determinado':`Frete informado na NF: ${formatFinanceCents(row.freight_cents)}`}. Este campo é a declaração da origem, não o total previsto.</p><ul className="list-disc pl-4">{row.issues.map(issue=><li key={issue}>{freightIssueLabels[issue]||'Origem precisa de revisão.'}{!freightIssueLabels[issue]&&<span> Referência: {issue}</span>}</li>)}</ul><details><summary>Identificação para rastreio</summary><p>NF: {row.document_id}</p>{row.attempt_id&&<p>Tentativa: {row.attempt_id}</p>}<p>Cliente: {row.client_id||'Não identificado'}</p></details></li>)}</ul>:<p>Nenhuma origem nesta página e seleção. Outros estados ou fontes fora da cobertura podem continuar pendentes.</p>}<div className="flex gap-2 items-center"><Button variant="outline" disabled={list.page===1} onClick={()=>setList({...list,page:list.page-1})}>Origens anteriores</Button><span>Página {list.page} · até 30 origens</span><Button variant="outline" disabled={list.page*30>=rows.total} onClick={()=>setList({...list,page:list.page+1})}>Próximas origens</Button></div></>}</section>
 </CardContent></Card>;
}
