import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import type {UnloadingProjectionRepairContext} from '@/lib/financial/unloadingProjectionRepairContract';
import {sendUnloadingProjectionRepair} from '@/lib/financial/unloadingProjectionRepairCommandClient';
import {createUnloadingProjectionRepairOutbox,lockUnloadingProjectionRepair,pendingUnloadingProjectionRepair,unloadingProjectionRepairKey,type PendingUnloadingProjectionRepair} from '@/lib/financial/unloadingProjectionRepairOutbox';
export function UnloadingProjectionRepairConfirmation({tenant,actor,chargeId,preview,refresh}:{tenant:string;actor:string;chargeId:string;preview:UnloadingProjectionRepairContext|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingUnloadingProjectionRepair|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingUnloadingProjectionRepair(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createUnloadingProjectionRepairOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockUnloadingProjectionRepair,send:sendUnloadingProjectionRepair}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===unloadingProjectionRepairKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.charge_id===chargeId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{chargeId,receivableId:preview!.receivable_id,revision:preview!.revision,reason});setConfirmed(`Reparação confirmada para a descarga ${result.charge_id}, título ${result.receivable_id}. Pedido ${result.request_id}. O dinheiro, o custo e a descarga foram preservados.`);setReview(null);try{await refresh();}catch{setError('A reparação foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(failure instanceof Error?failure.message:'O pedido não foi confirmado. Se estiver preservado abaixo, recupere o mesmo pedido; caso contrário, atualize a conferência antes de revisar novamente.');try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da reparação">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novas reparações estão bloqueadas.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · descarga {pending.payload.charge_id} · título {pending.receivableId} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p>{pending.payload.charge_id!==chargeId&&<p role="alert">Este pedido pertence a outra descarga. Recuperar consulta exclusivamente aquele pedido; não repara o título aberto agora.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido de reparação</Button></>:fresh?<><label className="block">Motivo da reparação<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar reparação</Button>{review===preview?.revision&&<><p>Restaurar o fornecedor e o valor do título conforme a origem exibida. Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi o título atual, a origem e o resultado previsto.</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar reparação do título</Button></>}</>:<p>A confirmação de reparação está indisponível nesta consulta.</p>}</section>;
}
