import {proposedAppliedCents} from '@/lib/financial/unloadingCostRegularizationContract';
import {Input} from '@/components/ui/input';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import type {UnloadingCostRegularizationProposal} from '@/lib/financial/unloadingCostRegularizationContract';
type Disposition=UnloadingCostRegularizationProposal['dispositions'][number];
export interface FundingSourceChoice {kind:Disposition['source_kind'];id:string;movementId:string|null;grossReservedCents:string|null;responsibleId:string|null;responsibleName:string|null;dispositionType:Disposition['disposition_type'];issue:string|null}
export interface FundingSourceInput {source:FundingSourceChoice;applied:string}

export function UnloadingCostDispositionEditor({rows,onChange,disabled=false}:{rows:FundingSourceInput[];onChange:(index:number,value:string)=>void;disabled?:boolean}){return <fieldset disabled={disabled} className="space-y-3"><legend>Aplicação e saldo pendente de cada fonte</legend><p>Confirme quanto de cada fonte cobre o custo corrigido. O restante permanece reservado, sob responsabilidade de quem recebeu; não é uma devolução.</p>{rows.map(({source,applied},index)=>{const cents=proposedAppliedCents(applied),valid=cents!==null&&source.grossReservedCents!==null&&BigInt(cents)<=BigInt(source.grossReservedCents);return <section key={`${source.kind}:${source.id}`} aria-label={`Fonte ${index+1}`} className="rounded border p-3"><h4>{source.kind==='expense_allocation'?'Envio vinculado ao gasto':'Pagamento do título'}</h4><p>Fonte {source.id} · movimento {source.movementId||'Não comprovado'}</p><p>Responsável: {source.responsibleName||'Nome não informado'} · {source.responsibleId||'Identidade não comprovada'}</p><p>Valor reservado original: {source.grossReservedCents===null?'Indeterminado':formatFinanceCents(source.grossReservedCents)}</p><label>Valor desta fonte aplicado ao custo (R$)<Input aria-label={`Valor aplicado da fonte ${index+1}`} inputMode="decimal" value={applied} disabled={!!source.issue||!source.responsibleId} onChange={event=>onChange(index,event.target.value)}/></label><p>{source.dispositionType==='driver_custody'?'Saldo sob responsabilidade do motorista':'Valor a recuperar de quem recebeu'}: {valid?formatFinanceCents((BigInt(source.grossReservedCents!)-BigInt(cents)).toString()):'Indeterminado'}</p>{applied&&!valid&&<p role="alert">Informe um valor válido que não exceda a fonte reservada.</p>}{source.issue&&<p role="alert">Esta fonte precisa de conferência antes da proposta. Diagnóstico: {source.issue}</p>}</section>;})}</fieldset>;}
