import {unloadingCostRegularizationErrorLabel} from '@/lib/financial/unloadingCostRegularizationLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {unloadingCostRegularizationEffectsSchema,type UnloadingCostRegularizationProposal,type UnloadingCostRegularizationPreview} from '@/lib/financial/unloadingCostRegularizationContract';
import {sendUnloadingCostRegularization} from '@/lib/financial/unloadingCostRegularizationClient';
import {createUnloadingCostRegularizationOutbox,lockUnloadingCostRegularization,pendingUnloadingCostRegularization,unloadingCostRegularizationKey,type PendingUnloadingCostRegularization} from '@/lib/financial/unloadingCostRegularizationOutbox';
export function UnloadingCostRegularizationConfirmation({tenant,actor,chargeId,preview,proposal,refresh}:{tenant:string;actor:string;chargeId:string;preview:UnloadingCostRegularizationPreview|undefined;proposal:UnloadingCostRegularizationProposal|null;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingUnloadingCostRegularization|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingUnloadingCostRegularization(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createUnloadingCostRegularizationOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockUnloadingCostRegularization,send:sendUnloadingCostRegularization}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===unloadingCostRegularizationKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.charge_id===chargeId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(busy||confirmed||corrupt||(!recover&&(!fresh||!preview||!proposal||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{chargeId,expenseId:preview!.expense_id,payableId:preview!.payable_id,proposal:proposal!,expected:unloadingCostRegularizationEffectsSchema.parse(preview!.effects),revision:preview!.revision,reason});setConfirmed(`Regularização confirmada para a descarga ${result.charge_id}, gasto ${result.expense_id}. Pedido ${result.request_id}. Custo ${formatFinanceCents(result.effects.cost_after_cents)}; saldo do motorista ${formatFinanceCents(result.effects.driver_custody_cents)}; valor a recuperar ${formatFinanceCents(result.effects.payment_recovery_cents)}. Dinheiro, título histórico e conciliação preservados.`);setReview(null);try{await refresh();}catch{setError('A regularização de custo foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(unloadingCostRegularizationErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da regularização de custo">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novas correções estão bloqueadas.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · descarga {pending.payload.charge_id} · gasto {pending.payload.expense_id} · conta a pagar {pending.payload.payable_id||'Sem título'} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p><p>Valor proposto preservado: {formatFinanceCents(pending.payload.proposal.amount_cents)}. Os saldos permanecem pendentes; não representam devolução.</p><p>Saldo motorista: {formatFinanceCents(pending.expected.driver_custody_cents)} · recuperação: {formatFinanceCents(pending.expected.payment_recovery_cents)}</p>{pending.payload.proposal.dispositions.map(d=><p key={`${d.source_kind}:${d.source_id}`}>Fonte {d.source_id} · responsável {d.responsible_id} · aplicado {formatFinanceCents(d.applied_cents)} · {d.disposition_type==='driver_custody'?'Responsabilidade do motorista':'Recuperação de quem recebeu'}</p>)}{pending.payload.charge_id!==chargeId&&<p role="alert">Este pedido pertence a outra descarga. Recuperar consulta exclusivamente aquele pedido; não corrige a descarga aberta agora.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido de regularização de custo</Button></>:fresh?<><label className="block">Motivo da regularização de custo<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar regularização de custo</Button>{review===preview?.revision&&<><p>Regularizar o custo e registrar a responsabilidade pelo saldo pendente. O título histórico, a cobrança e o dinheiro permanecem inalterados. Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi cada fonte e responsável. Confirmo que os saldos pendentes não foram devolvidos e continuam reservados; título histórico, cobrança e dinheiro permanecem inalterados.</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar regularização de custo</Button></>}</>:<p>A confirmação de regularização de custo está indisponível nesta consulta.</p>}</section>;
}
