import {unloadingOpenComplementErrorLabel} from '@/lib/financial/unloadingOpenComplementLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {unloadingOpenComplementExpectedSchema,type UnloadingOpenComplementPreview} from '@/lib/financial/unloadingOpenComplementContract';
import {sendUnloadingOpenComplement} from '@/lib/financial/unloadingOpenComplementClient';
import {createUnloadingOpenComplementOutbox,lockUnloadingOpenComplement,pendingUnloadingOpenComplement,unloadingOpenComplementKey,type PendingUnloadingOpenComplement} from '@/lib/financial/unloadingOpenComplementOutbox';
export function UnloadingOpenComplementConfirmation({tenant,actor,chargeId,preview,refresh,canConfirm}:{tenant:string;actor:string;chargeId:string;canConfirm:boolean;preview:UnloadingOpenComplementPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingUnloadingOpenComplement|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingUnloadingOpenComplement(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createUnloadingOpenComplementOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockUnloadingOpenComplement,send:sendUnloadingOpenComplement}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===unloadingOpenComplementKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=canConfirm&&!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.charge_id===chargeId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(!canConfirm||busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{chargeId,expenseId:preview!.expense_id,payableId:preview!.payable_id,amountCents:preview!.target.cost_cents,expected:unloadingOpenComplementExpectedSchema.parse(preview!.effects),revision:preview!.revision,reason});setConfirmed(`Correção do complemento confirmada para a descarga ${result.charge_id}, gasto ${result.expense_id} e conta a pagar ${result.payable_id}. Pedido ${result.request_id}. O custo e o complemento aberto foram corrigidos. Os envios vinculados permaneceram reservados. A cobrança e o dinheiro permaneceram inalterados.${result.effects.approval_reset?' A conta voltou a pendente e precisa de nova aprovação.':''}`);setReview(null);try{await refresh();}catch{setError('A correção do complemento foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(unloadingOpenComplementErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da correção do complemento">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novas correções estão bloqueadas.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · descarga {pending.payload.charge_id} · gasto {pending.payload.expense_id} · conta a pagar {pending.payload.payable_id} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p><p>Custo proposto preservado: {formatFinanceCents(pending.payload.amount_cents)}. Complemento preservado: {formatFinanceCents(pending.expected.complement_after_cents)}. {pending.expected.approval_reset&&'A aprovação anterior será retirada; nova aprovação será necessária.'}</p>{pending.payload.charge_id!==chargeId&&<p role="alert">Este pedido pertence a outra descarga. Recuperar consulta exclusivamente aquele pedido; não corrige a descarga aberta agora.</p>}<Button disabled={busy||!canConfirm} onClick={()=>void execute(true)}>Recuperar pedido de correção do complemento</Button></>:fresh?<><label className="block">Motivo da correção do complemento<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar correção do complemento</Button>{review===preview?.revision&&<>{preview?.approval_reset&&<p role="alert">A conta aprovada voltará a pendente. O novo valor exige outra aprovação.</p>}<p>Corrigir o custo e somente seu complemento aberto na mesma descarga. Os vínculos existentes continuam reservados. A cobrança, o beneficiário e o dinheiro permanecem inalterados. Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi custo, valor vinculado e complemento atuais e propostos. Confirmo que a cobrança permanece inalterada e que uma aprovação anterior deve ser refeita quando indicado.</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar correção do complemento</Button></>}</>:<p>A confirmação de correção do complemento está indisponível nesta consulta.</p>}</section>;
}
