import {useState} from 'react';
import {FinanceOptionPicker} from './FinanceOptionPicker';
import type {FinanceOption} from '@/lib/financial/expenseBatchContract';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {UnloadingOriginCorrectionConfirmation} from './UnloadingOriginCorrectionConfirmation';
import {readUnloadingOriginCorrectionContext,UnloadingOriginCorrectionUnavailableError} from '@/lib/financial/unloadingOriginCorrectionClient';
import {unloadingOriginProposalSchema,type UnloadingOriginProposal,type UnloadingOriginCorrectionContext} from '@/lib/financial/unloadingOriginCorrectionContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
type Scope={tenant:string;actor:string;chargeId:string};
// Publish this entry only with its public SQL wrappers; unavailable RPCs fail closed.
export function UnloadingOriginCorrectionDialog(props:Scope&{open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>Corrigir cobrança da descarga</DialogTitle><DialogDescription>Confira o direito de cobrança. O custo, a conta a pagar e o dinheiro registrado permanecem separados.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><UnloadingOriginCorrectionWorkspace key={`${props.tenant}:${props.actor}:${props.chargeId}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
export function UnloadingOriginCorrectionWorkspace({tenant,actor,chargeId}:Scope){
 const [operation,setOperation]=useState<'amend_origin'|'cancel_origin'>('amend_origin'),[supplier,setSupplier]=useState<FinanceOption|null>(null),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[proposal,setProposal]=useState<UnloadingOriginProposal|null>(null),[error,setError]=useState('');
 const cache=useQueryClient();
 const query=useQuery({queryKey:['finance-unloading-origin-correction',tenant,actor,chargeId,proposal],queryFn:()=>readUnloadingOriginCorrectionContext({tenantId:tenant,actorId:actor,chargeId,proposal:proposal!}),enabled:!!proposal,retry:false,staleTime:0});
 const data=proposal&&!query.isFetching&&!query.isError?query.data:undefined;
 const change=()=>{setProposal(null);setError('');};
 function preview(){const match=amount.trim().match(/^(\d+)(?:[,.](\d{1,2}))?$/);const cents=match?(BigInt(match[1])*100n+BigInt((match[2]||'').padEnd(2,'0'))).toString():'';const parsed=unloadingOriginProposalSchema.safeParse(operation==='cancel_origin'?{operation,effective_on:date,collection_right_only:true}:{operation,supplier_id:supplier?.id,amount_cents:cents,effective_on:date,collection_right_only:true});if(!parsed.success){setError('Informe data válida e, para alteração, fornecedor do catálogo e valor positivo com até duas casas decimais.');return;}setProposal(parsed.data);if(JSON.stringify(parsed.data)===JSON.stringify(proposal))void query.refetch();}
 const refresh=()=>Promise.all([invalidateAccountReview(cache,tenant),...['finance-unloading-origin-correction','finance-expenses','receivables','receivable-financial-context','finance-period-unloading-flow','finance-unloading-projection-repair','finance-receivable-unloading-origin'].map(prefix=>cache.invalidateQueries({queryKey:[prefix,tenant]},{throwOnError:true}))]);
 return <section className="space-y-3" aria-label="Conferência da cobrança da descarga"><p>Descarga {chargeId}</p><label className="block">Tipo de correção<select value={operation} onChange={e=>{change();setOperation(e.target.value as typeof operation);}}><option value="amend_origin">Alterar fornecedor ou valor da cobrança</option><option value="cancel_origin">Cancelar direito de cobrança</option></select></label>{operation==='amend_origin'&&<><FinanceOptionPicker tenant={tenant} actor={actor} kind="suppliers" label="Fornecedor devedor" value={supplier} onChange={value=>{change();setSupplier(value);}}/><label className="block">Valor proposto (R$)<input inputMode="decimal" value={amount} onChange={e=>{change();setAmount(e.target.value);}}/></label></>}<label className="block">Data econômica da correção<input type="date" value={date} onChange={e=>{change();setDate(e.target.value);}}/></label><p>Use a data econômica da alteração. Este registro não reconstrói o que era conhecido no passado.</p><Button disabled={query.isFetching} onClick={preview}>Conferir proposta de cobrança</Button>{error&&<p role="alert">{error}</p>}{query.isFetching&&<p role="status">Conferindo proposta e vínculos…</p>}{query.isError&&<p role="alert">{query.error instanceof UnloadingOriginCorrectionUnavailableError?query.error.message:'A consulta falhou. A elegibilidade anterior está indisponível; confira novamente.'}</p>}{data&&<UnloadingOriginCorrectionDetails key={data.revision} data={data}/>}<UnloadingOriginCorrectionConfirmation key={`${tenant}:${actor}:${chargeId}`} tenant={tenant} actor={actor} chargeId={chargeId} preview={data} refresh={refresh}/></section>;
}
const labels:Record<string,string>={unloading_origin_unverified:'A origem da descarga não foi comprovada.',unloading_origin_not_active:'O direito de cobrança não está ativo.',unloading_projection_requires_repair:'O título diverge da cobrança vigente e precisa de reparação antes desta alteração.',unloading_correction_date_invalid:'A data econômica deve respeitar a ocorrência, a última versão e o dia atual.',unloading_supplier_unavailable:'O fornecedor proposto não está disponível nesta empresa.',unloading_correction_no_change:'A proposta já corresponde à cobrança vigente.',unloading_closed_dependency:'Há vínculo com período fechado que precisa ser regularizado.',unloading_financial_history_requires_resolution:'O histórico financeiro exige regularização específica antes desta alteração.',unloading_projection_state_requires_resolution:'A situação do título exige regularização específica.',unloading_dependency_reader_missing:'Uma dependência não pôde ser conferida.',unloading_cost_origin_mismatch:'O custo diverge da origem e precisa de conferência.',unchanged_canonical_cost:'Custo preservado; não será alterado.',reopened_period_history:'Histórico de período já reaberto, preservado para consulta.'};
export function UnloadingOriginCorrectionDetails({data}:{data:UnloadingOriginCorrectionContext}){
 const [page,setPage]=useState(1);
 return <div className="space-y-3"><p>Título {data.receivable_id}</p><div className="grid gap-3 sm:grid-cols-3">{[['Original',data.original],['Vigente',data.effective],['Proposta',data.target]].map(([title,value])=>{const state=value as typeof data.effective;return <section key={String(title)} aria-label={`Cobrança ${title}`} className="rounded border p-2"><h3>{String(title)}</h3>{state?<><p>{state.supplier_name||'Nome não informado'} · {state.supplier_id}</p><p>{formatFinanceCents(state.amount_cents)}</p><p>{state.status==='cancelled'?'Direito de cobrança cancelado':'Direito de cobrança ativo'}</p></>:<p>Indeterminado</p>}</section>;})}</div><p>Data econômica proposta: {data.proposal.effective_on}</p><section aria-label="Efeitos separados"><h3>Efeitos separados</h3><p>Cobrança: somente o direito de cobrar será alterado conforme a proposta.</p><p>Custo: preservado, sem correção por esta operação.</p><p>Conta a pagar: preservada, sem cancelamento ou mudança de valor.</p><p>Dinheiro: nenhum pagamento, recebimento ou devolução será criado.</p></section>{data.blockers.map((b,i)=><p role="alert" key={i}>{labels[b.code]||'Condição que exige revisão antes de corrigir a cobrança.'} · {b.source_table||'Origem relacionada'} · {b.source_ids.join(', ')||'Referência individual indisponível'}</p>)}<details><summary>Vínculos conferidos ({data.dependencies.length})</summary>{data.dependencies.map((d,i)=><p key={i}>{d.blocking?'Impede esta correção':'Informativo'} · {labels[d.reason]||'Vínculo preservado para conferência.'} · {d.source_table} · {d.source_id||'Sem ID individual'}</p>)}</details><section aria-label="Histórico manual da cobrança"><h3>Histórico de alterações ({data.history.length})</h3>{data.history.slice((page-1)*20,page*20).map(e=><article key={e.id} className="rounded border border-amber-600 bg-amber-50 p-3 dark:bg-amber-950/30"><strong>Ajuste manual</strong><p>{e.actor_name||'Nome não informado'} ({e.actor_id}) · {e.created_at}</p><p>Motivo: {e.reason}</p><p>Data econômica: {e.effective_on} · evento {e.id}</p><p>Antes: {e.before.supplier_name||'Nome não informado'} ({e.before.supplier_id}) · {formatFinanceCents(e.before.amount_cents)}</p><p>Depois: {e.after.supplier_name||'Nome não informado'} ({e.after.supplier_id}) · {formatFinanceCents(e.after.amount_cents)} · {e.operation==='cancel_origin'?'Cancelamento':'Alteração'}</p></article>)}{!data.history.length&&<p>Nenhuma alteração registrada.</p>}{data.history.length>20&&<><Button disabled={page===1} onClick={()=>setPage(page-1)}>Página anterior de alterações</Button><Button disabled={page*20>=data.history.length} onClick={()=>setPage(page+1)}>Próxima página de alterações</Button></>}</section></div>;
}
