import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import type {UnloadingOriginCorrectionContext} from '@/lib/financial/unloadingOriginCorrectionContract';
import {sendUnloadingOriginCorrection,unloadingOriginCorrectionErrorLabel} from '@/lib/financial/unloadingOriginCorrectionClient';
import {createUnloadingOriginCorrectionOutbox,lockUnloadingOriginCorrection,pendingUnloadingOriginCorrection,unloadingOriginCorrectionKey,type PendingUnloadingOriginCorrection} from '@/lib/financial/unloadingOriginCorrectionOutbox';
export function UnloadingOriginCorrectionConfirmation({tenant,actor,chargeId,preview,refresh}:{tenant:string;actor:string;chargeId:string;preview:UnloadingOriginCorrectionContext|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingUnloadingOriginCorrection|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingUnloadingOriginCorrection(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createUnloadingOriginCorrectionOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockUnloadingOriginCorrection,send:sendUnloadingOriginCorrection}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===unloadingOriginCorrectionKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.charge_id===chargeId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{chargeId,receivableId:preview!.receivable_id,revision:preview!.revision,proposal:preview!.proposal,reason});setConfirmed(`Correção da cobrança confirmada para a descarga ${result.charge_id}, título ${result.receivable_id}. Pedido ${result.request_id}. O direito de cobrança foi corrigido. Dinheiro, custo e conta a pagar foram preservados.`);setReview(null);try{await refresh();}catch{setError('A correção da cobrança foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(unloadingOriginCorrectionErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da correção da cobrança">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novas correções estão bloqueadas.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · descarga {pending.payload.charge_id} · título {pending.receivableId} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p><p>Data econômica: {pending.payload.proposal.effective_on} · {pending.payload.proposal.operation==='cancel_origin'?'Cancelar direito de cobrança':`Fornecedor ${pending.payload.proposal.supplier_id} · centavos ${pending.payload.proposal.amount_cents}`}</p>{pending.payload.charge_id!==chargeId&&<p role="alert">Este pedido pertence a outra descarga. Recuperar consulta exclusivamente aquele pedido; não repara o título aberto agora.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido de correção da cobrança</Button></>:fresh?<><label className="block">Motivo da correção da cobrança<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar correção da cobrança</Button>{review===preview?.revision&&<><p>Aplicar exclusivamente a proposta exibida ao direito de cobrança desta descarga. Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi a cobrança vigente e a proposta. Confirmo somente o direito de cobrança; o custo e a conta a pagar não serão corrigidos.</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar correção da cobrança</Button></>}</>:<p>A confirmação de correção da cobrança está indisponível nesta consulta.</p>}</section>;
}
