import {unloadingCostCorrectionErrorLabel} from '@/lib/financial/unloadingCostCorrectionLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {unloadingCostCorrectionExpectedSchema,type UnloadingCostCorrectionPreview} from '@/lib/financial/unloadingCostCorrectionContract';
import {sendUnloadingCostCorrection} from '@/lib/financial/unloadingCostCorrectionClient';
import {createUnloadingCostCorrectionOutbox,lockUnloadingCostCorrection,pendingUnloadingCostCorrection,unloadingCostCorrectionKey,type PendingUnloadingCostCorrection} from '@/lib/financial/unloadingCostCorrectionOutbox';
export function UnloadingCostCorrectionConfirmation({tenant,actor,chargeId,preview,refresh}:{tenant:string;actor:string;chargeId:string;preview:UnloadingCostCorrectionPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingUnloadingCostCorrection|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingUnloadingCostCorrection(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createUnloadingCostCorrectionOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockUnloadingCostCorrection,send:sendUnloadingCostCorrection}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===unloadingCostCorrectionKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const fresh=!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.charge_id===chargeId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{chargeId,expenseId:preview!.expense_id,payableId:preview!.payable_id,amountCents:preview!.target.amount_cents,expected:unloadingCostCorrectionExpectedSchema.parse({cost_before_cents:preview!.effects.cost_before_cents,cost_after_cents:preview!.effects.cost_after_cents,obligation_before_cents:preview!.effects.obligation_before_cents,obligation_after_cents:preview!.effects.obligation_after_cents,approval_reset:preview!.approval_reset,payable_status:'pending'}),revision:preview!.revision,reason});setConfirmed(`Correção de custo confirmada para a descarga ${result.charge_id}, gasto ${result.expense_id} e conta a pagar ${result.payable_id}. Pedido ${result.request_id}. O custo e a obrigação foram corrigidos. A cobrança e o dinheiro permaneceram inalterados.${result.approval_reset?' A conta voltou a pendente e precisa de nova aprovação.':''}`);setReview(null);try{await refresh();}catch{setError('A correção de custo foi confirmada, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(unloadingCostCorrectionErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação da correção de custo">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novas correções estão bloqueadas.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · descarga {pending.payload.charge_id} · gasto {pending.payload.expense_id} · conta a pagar {pending.payload.payable_id} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p><p>Valor proposto preservado: {formatFinanceCents(pending.payload.amount_cents)}. {pending.expected.approval_reset&&'A aprovação anterior será retirada; nova aprovação será necessária.'}</p>{pending.payload.charge_id!==chargeId&&<p role="alert">Este pedido pertence a outra descarga. Recuperar consulta exclusivamente aquele pedido; não corrige a descarga aberta agora.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido de correção de custo</Button></>:fresh?<><label className="block">Motivo da correção de custo<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar correção de custo</Button>{review===preview?.revision&&<>{preview?.approval_reset&&<p role="alert">A conta aprovada voltará a pendente. O novo valor exige outra aprovação.</p>}<p>Corrigir somente o valor do custo e da obrigação na mesma descarga. A cobrança, o beneficiário e o dinheiro permanecem inalterados. Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> Conferi custo e obrigação atuais e propostos. Confirmo que a cobrança permanece inalterada e que uma aprovação anterior deve ser refeita quando indicado.</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar correção de custo</Button></>}</>:<p>A confirmação de correção de custo está indisponível nesta consulta.</p>}</section>;
}
