import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {ExpenseFundingSummary} from './ExpenseFundingSummary';
import {UnloadingCostDispositionEditor} from './UnloadingCostDispositionEditor';
import {UnloadingCostRegularizationConfirmation} from './UnloadingCostRegularizationConfirmation';
import {proposedAppliedCents,unloadingCostRegularizationProposalSchema,type UnloadingCostRegularizationProposal,type UnloadingCostRegularizationPreview} from '@/lib/financial/unloadingCostRegularizationContract';
import {readUnloadingCostRegularization} from '@/lib/financial/unloadingCostRegularizationClient';
import {unloadingCostRegularizationLabels} from '@/lib/financial/unloadingCostRegularizationLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
type Scope={tenant:string;actor:string;chargeId:string};
export function UnloadingCostRegularizationDialog(props:Scope&{open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent className="max-h-[90vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>Regularizar custo coberto e saldo pendente</DialogTitle><DialogDescription>Confira a aplicação de cada fonte e quem responde pelo saldo. Esta operação não devolve dinheiro.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><UnloadingCostRegularizationWorkspace key={`${props.tenant}:${props.actor}:${props.chargeId}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
export function UnloadingCostRegularizationWorkspace({tenant,actor,chargeId}:Scope){const cache=useQueryClient();const [value,setValue]=useState(''),[amount,setAmount]=useState(''),[applied,setApplied]=useState<Record<string,string>>({}),[selected,setSelected]=useState<UnloadingCostRegularizationProposal|null>(null),[error,setError]=useState('');
 const discovery=useQuery({queryKey:['finance-cost-regularization-sources',tenant,actor,chargeId,amount],queryFn:()=>readUnloadingCostRegularization(tenant,actor,chargeId,{amount_cents:amount,dispositions:[]}),enabled:!!amount,retry:false,staleTime:0});
 const sources=amount&&!discovery.isFetching&&!discovery.isError?discovery.data:undefined;
 const preview=useQuery({queryKey:['finance-cost-regularization-preview',tenant,actor,chargeId,discovery.data?.revision,selected],queryFn:()=>readUnloadingCostRegularization(tenant,actor,chargeId,selected!),enabled:!!selected&&!!sources,retry:false,staleTime:0});
 const data=sources&&selected&&!preview.isFetching&&!preview.isError?preview.data:undefined;
 const refresh=()=>Promise.all([invalidateAccountReview(cache,tenant),...['finance-cost-regularization-sources','finance-cost-regularization-preview','finance-cost-dispositions','finance-expenses','finance-recorded-costs','finance-recorded-cost-summary','finance-payable-portfolio','finance-settlement-expense-context'].map(prefix=>cache.invalidateQueries({queryKey:[prefix,tenant]},{throwOnError:true}))]);
 function discover(){const cents=proposedAppliedCents(value);if(cents===null||cents==='0'){setError('Informe um custo positivo com até duas casas decimais.');return;}setError('');setApplied({});setSelected(null);if(amount===cents)void discovery.refetch();else setAmount(cents);}
 function review(){if(!sources)return;try{const proposal=unloadingCostRegularizationProposalSchema.parse({amount_cents:amount,dispositions:sources.source_rows.map(source=>({source_kind:source.source_kind,source_id:source.source_id,applied_cents:proposedAppliedCents(applied[`${source.source_kind}:${source.source_id}`]||''),disposition_type:source.disposition_type,responsible_id:source.responsible_id}))});setError('');setSelected(proposal);}catch{setError('Confira o valor aplicado e o responsável comprovado de cada fonte.');}}
 return <section aria-label="Regularização de custo financiado" className="space-y-3"><p>Descarga {chargeId}</p><label>Custo corrigido (R$)<Input value={value} inputMode="decimal" onChange={e=>{setValue(e.target.value);setAmount('');setApplied({});setSelected(null);}}/></label><Button onClick={discover}>Consultar fontes do custo</Button>{error&&<p role="alert">{error}</p>}{(discovery.isFetching||preview.isFetching)&&<p role="status">Conferindo fontes e responsabilidades…</p>}{(discovery.isError||preview.isError)&&<p role="alert">A regularização está indisponível nesta consulta. Nenhuma prévia anterior permite confirmar.</p>}{sources&&<><UnloadingCostDispositionEditor rows={sources.source_rows.map(s=>({source:{kind:s.source_kind,id:s.source_id,movementId:s.movement_id,grossReservedCents:s.gross_reserved_cents,responsibleId:s.responsible_id,responsibleName:s.responsible_name,dispositionType:s.disposition_type,issue:s.responsible_id?null:'Responsável não comprovado'},applied:applied[`${s.source_kind}:${s.source_id}`]||''}))} onChange={(index,next)=>{const s=sources.source_rows[index];setApplied(old=>({...old,[`${s.source_kind}:${s.source_id}`]:next}));setSelected(null);}}/><Button disabled={preview.isFetching} onClick={review}>Conferir aplicação e saldos pendentes</Button></>}{data&&<UnloadingCostRegularizationDetails data={data}/>}<UnloadingCostRegularizationConfirmation key={`${tenant}:${actor}:${chargeId}`} tenant={tenant} actor={actor} chargeId={chargeId} preview={data} proposal={selected} refresh={refresh}/></section>;
}
const money=(v:string|null)=>v===null?'Indeterminado':formatFinanceCents(v);
export function UnloadingCostRegularizationDetails({data}:{data:UnloadingCostRegularizationPreview}){const e=data.effects;return <section aria-label="Prévia da regularização" className="space-y-3"><p>Custo original: {money(data.cost_origin.original_amount_cents)} · vigente: {money(e.cost_before_cents)} · proposto: {money(e.cost_after_cents)} · variação: {money(e.cost_delta_cents)}</p><ExpenseFundingSummary costCents={e.cost_after_cents} grossReservedCents={e.gross_reserved_cents} driverCustodyCents={e.driver_custody_cents} paymentRecoveryCents={e.payment_recovery_cents} prospective/><p>Título histórico {data.payable_id||'Não há título nesta origem'} · nominal preservado: {money(data.obligation.nominal_cents)} · pago preservado: {money(data.obligation.paid_cents)} · em aberto: {money(data.obligation.open_cents)}</p><p>Capacidade liberada para outros pagamentos: R$ 0,00. Cobrança da descarga inalterada.</p>{data.materialization_plan.action==='review_required'&&<p role="alert">Há composição de acerto ou folha que exige revisão: {data.materialization_plan.source_ids.join(', ')}.</p>}{data.blockers.map((b,index)=><p role="alert" key={index}>{unloadingCostRegularizationLabels[b.code]||'Uma dependência precisa de revisão antes desta regularização.'} · {b.source_ids.join(', ')}<span className="block text-xs">{b.code}</span></p>)}{data.cost_origin.regularization?.history.map(h=><article key={h.id} className="rounded border border-amber-600 p-2"><strong>Regularização manual preservada</strong><p>{h.actor_name||'Responsável identificado'} · {h.actor_id} · {h.created_at}</p><p>{h.reason}</p><p>De {money(h.cost_before_cents)} para {money(h.cost_after_cents)} · pedido {h.request_id}</p></article>)}</section>;}
