import {unloadingCancellationErrorLabel} from '@/lib/financial/unloadingCancellationLabels';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {priorUnloadingCancellationId,unloadingCancellationExpectedSchema,type UnloadingCancellationPreview} from '@/lib/financial/unloadingCancellationContract';
import {sendUnloadingCancellation} from '@/lib/financial/unloadingCancellationClient';
import {createUnloadingCancellationOutbox,lockUnloadingCancellation,pendingUnloadingCancellation,unloadingCancellationKey,type PendingUnloadingCancellation} from '@/lib/financial/unloadingCancellationOutbox';
export function UnloadingCancellationConfirmation({tenant,actor,chargeId,preview,refresh}:{tenant:string;actor:string;chargeId:string;preview:UnloadingCancellationPreview|undefined;refresh:()=>Promise<unknown>}){
 const live=useRef({tenant,actor,active:true});live.current={tenant,actor,active:true};
 const [pending,setPending]=useState<PendingUnloadingCancellation|null>(null),[corrupt,setCorrupt]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState<string|null>(null),[ack,setAck]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(''),[requiresRefresh,setRequiresRefresh]=useState(false);
 const sync=()=>{try{setPending(pendingUnloadingCancellation(localStorage,tenant,actor));setCorrupt(false);}catch{setCorrupt(true);}};
 const syncRef=useRef(sync);syncRef.current=sync;
 const [outbox]=useState(()=>createUnloadingCancellationOutbox({storage:localStorage,uuid:()=>crypto.randomUUID(),changed:()=>{if(live.current.active)syncRef.current();},assertContext:(t,a)=>{if(!live.current.active||live.current.tenant!==t||live.current.actor!==a)throw Error('Retome o pedido na sessão original.');},lock:lockUnloadingCancellation,send:sendUnloadingCancellation}));
 useEffect(()=>{live.current.active=true;syncRef.current();const storage=(event:StorageEvent)=>{if(event.key===null||event.key===unloadingCancellationKey(tenant,actor))syncRef.current();};window.addEventListener('storage',storage);return()=>{live.current.active=false;window.removeEventListener('storage',storage);};},[tenant,actor]);
 useEffect(()=>{if(preview)setRequiresRefresh(false);},[preview]);
 const priorId=preview?priorUnloadingCancellationId(preview.origin):null;
 const fresh=!requiresRefresh&&!!preview?.can_execute&&preview.eligible&&preview.charge_id===chargeId&&preview.tenant_id===tenant&&preview.actor_id===actor;
 async function execute(recover:boolean){if(busy||confirmed||corrupt||(!recover&&(!fresh||!preview||review!==preview.revision||!ack)))return;setBusy(true);setError('');try{const result=recover?await outbox.recover(tenant,actor):await outbox.submit(tenant,actor,{chargeId,effectiveOn:preview!.effective_on,...(priorId?{priorOriginAmendmentId:priorId}:{}),expected:unloadingCancellationExpectedSchema.parse({receivable_id:preview!.origin.receivable_id,expense_id:preview!.expense_id,payable_id:preview!.payable_id,cost_removed_cents:preview!.effects.cost_removed_cents,obligation_cancelled_cents:preview!.effects.obligation_cancelled_cents,collection_cancelled_cents:preview!.effects.collection_cancelled_cents}),revision:preview!.revision,reason});setConfirmed(`Cancelamento coordenado confirmado para a descarga ${result.charge_id}, título ${result.receivable_id}. Pedido ${result.request_id}. ${result.collection_cancelled_cents==='0'?'A cobrança permaneceu cancelada; custo e conta a pagar foram cancelados, sem nova retirada da cobrança.':'Cobrança, custo e conta a pagar foram cancelados conforme a conferência.'} Nenhum dinheiro foi movimentado.`);setReview(null);try{await refresh();}catch{setError('O cancelamento coordenado foi confirmado, mas a consulta não foi atualizada. Atualize a conferência.');}}catch(failure){setRequiresRefresh(true);setReview(null);setAck(false);setError(unloadingCancellationErrorLabel(failure));try{await refresh();setRequiresRefresh(false);}catch{setError('A resposta não foi confirmada e a conferência não foi atualizada. Preserve qualquer pedido exibido abaixo e atualize a consulta.');}}finally{setBusy(false);}}
 return <section className="space-y-2 rounded border p-3" aria-label="Confirmação do cancelamento coordenado">{error&&<p role="alert">{error}</p>}{confirmed?<p role="status">{confirmed}</p>:corrupt?<p role="alert">O pedido salvo está inconsistente. Preserve os dados; novos cancelamentos estão bloqueados.</p>:pending?<><p>Pedido preservado {pending.payload.request_id} · descarga {pending.payload.charge_id} · título {pending.expected.receivable_id} · autor {pending.actorId}</p><p>Motivo: {pending.payload.reason}</p>{pending.payload.prior_origin_amendment_id&&<p>Cobrança já cancelada no evento {pending.payload.prior_origin_amendment_id}. Este pedido cancela somente custo e obrigação, sem nova retirada da cobrança.</p>}<p>Valores do pedido preservado: cobrança {formatFinanceCents(pending.expected.collection_cancelled_cents)} · custo {formatFinanceCents(pending.expected.cost_removed_cents)} · obrigação {formatFinanceCents(pending.expected.obligation_cancelled_cents)}</p><p>Gasto {pending.expected.expense_id} · conta a pagar {pending.expected.payable_id} · data econômica {pending.payload.effective_on}</p>{pending.payload.charge_id!==chargeId&&<p role="alert">Este pedido pertence a outra descarga. Recuperar consulta exclusivamente aquele pedido; não cancela a descarga aberta agora.</p>}<Button disabled={busy} onClick={()=>void execute(true)}>Recuperar pedido de cancelamento coordenado</Button></>:fresh?<><label className="block">Motivo do cancelamento coordenado<textarea value={reason} maxLength={2000} disabled={busy} onChange={event=>{setReason(event.target.value);setReview(null);setAck(false);}}/></label><Button disabled={busy||reason.trim().length<10||reason.trim().length>2000} onClick={()=>{setReview(preview!.revision);setAck(false);}}>Revisar cancelamento coordenado</Button>{review===preview?.revision&&<><p>{priorId?'Cobrança já cancelada; cancelar somente custo e obrigação, preservando o evento anterior e sem nova retirada da cobrança.':'Cancelar conjuntamente o direito de cobrança, o custo e a conta a pagar exibidos, preservando os registros originais e o histórico.'} {priorId&&`Evento anterior: ${priorId}.`} Motivo: {reason}</p><label><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> {priorId?'Conferi o cancelamento anterior da cobrança. Confirmo somente o cancelamento do custo e da obrigação, sem dupla retirada ou movimentação de dinheiro.':'Conferi separadamente cobrança, custo e conta a pagar. Confirmo o cancelamento coordenado, sem pagamento, recebimento ou devolução.'}</label><Button disabled={!ack||busy} onClick={()=>void execute(false)}>Confirmar cancelamento coordenado</Button></>}</>:<p>A confirmação de cancelamento coordenado está indisponível nesta consulta.</p>}</section>;
}
