import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useTenant} from '@/hooks/useTenant';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {FinanceAccessBoundary} from './FinanceAccessBoundary';
import {ExpenseOpenComplementHistory} from './ExpenseOpenComplementHistory';
import {UnloadingOpenComplementConfirmation} from './UnloadingOpenComplementConfirmation';
import {readUnloadingOpenComplement} from '@/lib/financial/unloadingOpenComplementClient';
import type {UnloadingOpenComplementPreview} from '@/lib/financial/unloadingOpenComplementContract';
import {proposedAppliedCents} from '@/lib/financial/unloadingCostRegularizationContract';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
import {unloadingOpenComplementLabels} from '@/lib/financial/unloadingOpenComplementLabels';
import {invalidateAccountReview} from '@/lib/financial/invalidateAccountReview';
type Scope={tenant:string;actor:string;chargeId:string};
export function UnloadingOpenComplementDialog(props:Scope&{open:boolean;onOpenChange:(open:boolean)=>void}){return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>Conferir custo e complemento aberto</DialogTitle><DialogDescription>Os envios vinculados permanecem reservados. A correção pode alterar o custo e o restante ainda não pago, sem novo dinheiro.</DialogDescription></DialogHeader>{props.open&&<FinanceAccessBoundary><UnloadingOpenComplementWorkspace key={`${props.tenant}:${props.actor}:${props.chargeId}`} {...props}/></FinanceAccessBoundary>}</DialogContent></Dialog>;}
export function UnloadingOpenComplementWorkspace({tenant,actor,chargeId}:Scope){const {currentRole}=useTenant();const [value,setValue]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState('');const cache=useQueryClient();const query=useQuery({queryKey:['finance-unloading-open-complement',tenant,actor,chargeId,selected],queryFn:()=>readUnloadingOpenComplement(tenant,actor,chargeId,selected),enabled:!!selected,retry:false,staleTime:0});const data=selected&&!query.isFetching&&!query.isError?query.data:undefined;const refresh=()=>Promise.all([invalidateAccountReview(cache,tenant),...['finance-unloading-open-complement','finance-unloading-cost-correction','finance-expenses','finance-recorded-costs','finance-recorded-cost-summary','finance-settlement-expense-context','finance-payable-portfolio','payables','finance-cost-dispositions'].map(prefix=>cache.invalidateQueries({queryKey:[prefix,tenant]},{throwOnError:true}))]);return <section aria-label="Conferência de complemento aberto" className="space-y-3"><p>Descarga {chargeId}</p><label>Novo custo total (R$)<input inputMode="decimal" value={value} onChange={e=>{setValue(e.target.value);setSelected('');setError('');}}/></label><Button disabled={query.isFetching} onClick={()=>{const amount=proposedAppliedCents(value);if(!amount||amount==='0'){setError('Informe custo positivo com até duas casas decimais.');return;}setError('');if(selected===amount)void query.refetch();else setSelected(amount);}}>Conferir complemento aberto</Button>{error&&<p role="alert">{error}</p>}{query.isFetching&&<p role="status">Conferindo custo, vínculos e complemento…</p>}{query.isError&&<p role="alert">A consulta do complemento está indisponível. Nenhuma prévia anterior permite confirmar.</p>}{data&&<UnloadingOpenComplementDetails data={data}/>}<UnloadingOpenComplementConfirmation key={`${tenant}:${actor}:${chargeId}`} tenant={tenant} actor={actor} chargeId={chargeId} canConfirm={['owner','admin'].includes(currentRole||'')} preview={data} refresh={refresh}/></section>;}
const money=(v:string|null)=>v===null?'Indeterminado':formatFinanceCents(v);
export function UnloadingOpenComplementDetails({data}:{data:UnloadingOpenComplementPreview}){return <section aria-label="Valores do complemento" className="space-y-3"><p>Favorecido preservado: {data.payable.beneficiary_name||'Nome não informado'} · {data.payable.beneficiary_id||'Identidade não informada'}</p><p>Gasto {data.expense_id} · conta a pagar {data.payable_id}</p><p>Custo original: {money(data.cost_origin.original_amount_cents)} · custo vigente: {money(data.cost_origin.effective_amount_cents)} · proposto: {money(data.target.cost_cents)}</p><p>Vínculo mantido reservado: {money(data.allocated_reserved_cents)}</p><p>Complemento vigente: {money(data.payable.amount_cents)} · complemento proposto: {money(data.target.complement_cents)}</p><p>Nenhum novo dinheiro, devolução ou capacidade de pagamento será criado. A cobrança da descarga permanece inalterada.</p>{data.approval_reset&&<p role="alert">A conta aprovada voltará a pendente. O complemento corrigido exige nova aprovação.</p>}{data.blockers.map((b,i)=><p key={i} role="alert">{unloadingOpenComplementLabels[b.code]||'Esta dependência exige conferência antes da correção.'} · {b.source_ids.join(', ')||'Sem referência individual'}<span className="block text-xs">{b.code}</span></p>)}{data.cost_origin.open_complement&&<ExpenseOpenComplementHistory value={data.cost_origin.open_complement}/>}</section>;}
