import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {formatFinanceCents} from '@/lib/financial/ledgerContract';
// Presentation model only. A future reader must supply the resolved current version;
// this component never derives it by adding a page of historical adjustments.
type Supplier={id:string;name:string|null};
export type UnloadingOriginVersionsModel={
 chargeId:string;deliveryId:string;receivableId:string;
 original:{supplier:Supplier;amountCents:string|null;effectiveOn:string|null};
 current:{status:'active'|'cancelled'|'unknown';supplier:Supplier|null;amountCents:string|null;versionId:string|null};
 adjustments:Array<{id:string;operation:'amend'|'cancel';effectiveOn:string|null;capturedAt:string;actorId:string;actorName:string|null;reason:string;legs:Array<{supplier:Supplier;deltaCents:string|null}>}>;
 preservedCost:{expenseId:string;amountCents:string|null;payableId:string|null;payeeName:string|null}|null;
 historyComplete:boolean;
};
const money=(cents:string|null)=>cents!==null&&/^-?\d+$/.test(cents)?formatFinanceCents(cents):'Indeterminado';
const supplier=(value:Supplier|null)=>value?`${value.name||'Nome preservado não informado'} · ${value.id}`:'Fornecedor indeterminado';
export function UnloadingOriginVersions({data}:{data:UnloadingOriginVersionsModel}){
 const [page,setPage]=useState(1);const safePage=Math.min(page,Math.max(1,Math.ceil(data.adjustments.length/20)));
 return <section aria-label="Cobrança de descarga e custo preservado" className="space-y-3 rounded border p-3"><h3>Cobrança de descarga e custo preservado</h3><p>Descarga {data.chargeId} · entrega {data.deliveryId} · título {data.receivableId}</p><div className="grid gap-3 sm:grid-cols-2"><section aria-label="Cobrança original"><h4>Cobrança original</h4><p>{supplier(data.original.supplier)}</p><p>{money(data.original.amountCents)}</p><p>Data econômica: {data.original.effectiveOn||'Indeterminada'}</p></section><section aria-label="Cobrança vigente"><h4>Cobrança vigente</h4><p>{data.current.status==='cancelled'?'Cobrança cancelada':data.current.status==='active'?'Direito de cobrança vigente':'Situação a conferir'}</p><p>{supplier(data.current.supplier)}</p><p>{money(data.current.amountCents)}</p><p>Versão {data.current.versionId||'Original ou versão não informada'}</p></section></div><section aria-label="Custo preservado"><h4>Custo preservado</h4>{data.preservedCost?<><p>Gasto {data.preservedCost.expenseId} · {money(data.preservedCost.amountCents)}</p><p>Favorecido do pagamento: {data.preservedCost.payeeName||'Não informado'}</p><p>Conta a pagar: {data.preservedCost.payableId||'Não informada'}</p></>:<p>Informação do custo indisponível nesta consulta.</p>}<p>Alterar ou cancelar o direito de cobrar não desfaz o gasto, a obrigação de pagar ou o dinheiro registrado.</p></section><section aria-label="Histórico manual da cobrança"><h4>Ajustes da cobrança</h4>{!data.historyComplete&&<p role="alert">O histórico exibido é parcial. A cobrança vigente depende da versão resolvida pelo servidor, sem somar esta lista.</p>}{data.adjustments.slice((safePage-1)*20,safePage*20).map(event=><article key={event.id} className="my-2 rounded border border-amber-600 bg-amber-50 p-3 dark:bg-amber-950/30"><h5>Ajuste manual — {event.operation==='cancel'?'cancelamento':'alteração'}</h5><p>{event.actorName||'Nome não informado'} ({event.actorId})</p><p>Motivo: {event.reason}</p><p>Data econômica: {event.effectiveOn||'Indeterminada'} · registrado em {event.capturedAt}</p><p>Evento {event.id}</p>{event.legs.map((leg,index)=><p key={`${leg.supplier.id}:${index}`}>{supplier(leg.supplier)} · ajuste {money(leg.deltaCents)}</p>)}</article>)}{!data.adjustments.length&&<p>{data.historyComplete?'Nenhum ajuste registrado.':'Nenhum ajuste disponível nesta parte do histórico.'}</p>}{data.adjustments.length>20&&<><Button variant="outline" disabled={safePage===1} onClick={()=>setPage(safePage-1)}>Página anterior de ajustes</Button><Button variant="outline" disabled={safePage*20>=data.adjustments.length} onClick={()=>setPage(safePage+1)}>Próxima página de ajustes</Button></>}</section><p>Os ajustes descrevem o direito de cobrança. Não são recebimentos, saídas de caixa nem saldo devedor do período. Pagamentos passados conservam seu fornecedor de origem.</p></section>;
}
