import { useMemo, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, BookOpen, CircleHelp, LifeBuoy, Search, Wrench, AlertTriangle } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { findNavigationPage } from '@/components/layout/navigation';
import { useTenant } from '@/hooks/useTenant';
import { useTenantCapabilities, type IntegrationCapability } from '@/hooks/useTenantCapabilities';
import { useFinanceAccess } from '@/hooks/useFinanceLedger';
import { isFinancialPath } from '@/lib/financial/financeRoutes';

type Guide = {
  id: string; title: string; category: string; summary: string; keywords: string;
  paths: string[]; steps: string[]; tips: string[];
};

type TroubleshootingItem = { problem: string; cause: string; action: string; keywords: string };

const guides: Guide[] = [
  { id: 'importar', title: 'Importar documentos e criar cargas', category: 'Planejamento e cargas', summary: 'Use a importação para transformar arquivos fiscais em cargas organizadas.', keywords: 'xml nota fiscal arquivo importar carga erro cliente duplicado', paths: ['/ingestion', '/loads'], steps: ['Abra Importação de documentos e envie os XMLs ou arquivos aceitos pela tela.', 'Revise as validações. Corrija documentos sem cliente, endereço ou dados obrigatórios antes de avançar.', 'Confira o agrupamento e os dados da carga; ajuste os itens quando necessário.', 'Confirme a criação e acompanhe o resultado em Cargas ou no histórico de importações.'], tips: ['Documento rejeitado costuma indicar campo ausente ou arquivo inválido; abra o detalhe da validação para ver qual campo corrigir.', 'Antes de reenviar um arquivo, consulte o histórico para evitar duplicidade.'] },
  { id: 'planejar-viagem', title: 'Planejar cargas e viagens', category: 'Planejamento e cargas', summary: 'Entenda a sequência entre cargas disponíveis, roteirização e acompanhamento.', keywords: 'viagem rota roteirizar carga motorista veículo manifesto planejar', paths: ['/loads', '/route-planning', '/operations-control'], steps: ['Em Cargas, confira se os documentos e os endereços estão corretos.', 'Abra Roteirização para organizar as cargas por rota e planejar a sequência.', 'Revise distância, paradas e compatibilidade operacional antes de confirmar.', 'Acompanhe a execução na Torre de controle e trate alertas ou eventos pendentes.'], tips: ['Uma carga pode não aparecer para roteirização se ainda estiver incompleta ou vinculada a outra operação.', 'Dados de endereço imprecisos podem afetar a sequência; use Validação de endereços para revisar coordenadas.'] },
  { id: 'acompanhar-entrega', title: 'Acompanhar entrega e comprovantes', category: 'Rastreamento e entrega', summary: 'Localize o andamento de uma nota, confira eventos e consulte o comprovante.', keywords: 'entrega rastrear acompanhar canhoto comprovante POD nota fiscal ocorrência', paths: ['/traceability', '/delivery-receipts', '/events'], steps: ['Abra Rastreabilidade de notas e pesquise pela chave, número da nota ou outro identificador disponível.', 'Abra o registro para conferir os eventos e a situação mais recente.', 'Para localizar comprovantes, use Canhotos e filtre pelos dados da entrega.', 'Se houver divergência, consulte Eventos operacionais e a ocorrência associada.'], tips: ['A ausência de comprovante pode significar que a entrega ainda não foi sincronizada ou que o documento não está vinculado à nota pesquisada.', 'Confira o período e remova filtros restritivos quando um resultado não aparecer.'] },
  { id: 'ocorrencias', title: 'Registrar e tratar uma ocorrência', category: 'Rastreamento e entrega', summary: 'Registre problemas da operação e acompanhe o tratamento até a resolução.', keywords: 'problema atraso avaria falta devolução ocorrência evento incidente', paths: ['/events', '/alerts', '/occurrence-reports'], steps: ['Abra Eventos operacionais para localizar o evento ou registrar o ocorrido no fluxo disponível.', 'Associe a ocorrência à carga, nota ou viagem correta e descreva o que aconteceu.', 'Inclua os dados necessários para a equipe responsável agir e salve o registro.', 'Acompanhe pendências em Alertas e consulte Relatórios de ocorrências para análise.'], tips: ['Use a ocorrência formal quando o processo exigir apuração de RH; ocorrências operacionais ficam no fluxo de eventos.', 'Informe referências do documento e uma descrição objetiva para facilitar a busca posterior.'] },
  { id: 'faturar', title: 'Preparar faturamento e documentos fiscais', category: 'Fiscal e financeiro', summary: 'Confira documentos pendentes antes de emitir ou acompanhar CT-e, MDF-e e NFS-e.', keywords: 'faturar emitir cte mdfe nfse nota rejeição fiscal imposto', paths: ['/cte-hub', '/fiscal-documents', '/mdfe'], steps: ['Confira se os documentos fiscais e os dados do cliente estão corretos.', 'Abra Central CT-e para revisar pendências e selecionar os documentos elegíveis.', 'Revise os dados e a prévia antes de confirmar uma emissão.', 'Acompanhe o resultado na Central CT-e; consulte a mensagem da SEFAZ quando houver rejeição.'], tips: ['Emissão fiscal depende de configuração e acesso habilitados para a empresa.', 'Não repita uma emissão sem conferir o status anterior e o retorno da integração.'] },
  { id: 'financeiro', title: 'Lançar e acompanhar contas a pagar e receber', category: 'Fiscal e financeiro', summary: 'Consulte títulos, vencimentos e movimentações pelos módulos financeiros.', keywords: 'financeiro pagar receber contas boleto título baixa vencimento caixa', paths: ['/financial', '/payables', '/receivables'], steps: ['Comece pelo Painel financeiro para localizar indicadores e atalhos da rotina.', 'Use Contas a pagar ou Contas a receber para filtrar títulos por situação e vencimento.', 'Abra o título para revisar valores e registrar a ação disponível no fluxo.', 'Confira as movimentações e a previsão de caixa para validar o reflexo financeiro.'], tips: ['Verifique empresa ativa e período selecionado se os valores não corresponderem ao esperado.', 'Títulos originados de documentos podem exigir correção no documento de origem antes do lançamento.'] },
  { id: 'cadastros', title: 'Cadastrar clientes, veículos e motoristas', category: 'Cadastros e equipe', summary: 'Mantenha os dados básicos completos para evitar bloqueios em operações.', keywords: 'cadastro cliente fornecedor veículo motorista funcionário dados', paths: ['/clients', '/vehicles', '/drivers'], steps: ['Abra o cadastro correspondente: Clientes e fornecedores, Veículos ou Motoristas.', 'Use Novo cadastro e preencha os campos obrigatórios indicados na tela.', 'Revise identificadores, contatos e informações operacionais antes de salvar.', 'Retorne ao processo que originou a necessidade e confirme que o cadastro pode ser selecionado.'], tips: ['Se o registro não aparecer em uma lista, verifique se está ativo e se a empresa selecionada é a correta.', 'Evite criar duplicatas; pesquise por documento, placa ou nome antes de incluir.'] },
  { id: 'acessos', title: 'Convidar usuários e ajustar acessos', category: 'Cadastros e equipe', summary: 'Gerencie convites, empresas disponíveis e permissões da equipe.', keywords: 'usuário convidar login senha permissão perfil acesso empresa equipe', paths: ['/team', '/settings'], steps: ['Abra Equipe e acessos e confira a empresa ativa.', 'Convide a pessoa usando o endereço de e-mail correto.', 'Defina o perfil e as permissões necessárias para a função.', 'Peça que a pessoa conclua o acesso pelo convite e valide que as telas esperadas estão disponíveis.'], tips: ['Acesso a módulos opcionais pode depender de habilitação da empresa, além do perfil do usuário.', 'Nunca compartilhe senhas; cada pessoa deve usar seu próprio acesso.'] },
  { id: 'buscar-telas', title: 'Encontrar uma tela ou uma informação', category: 'Navegação', summary: 'Use a busca da navegação e os filtros para localizar rapidamente o que precisa.', keywords: 'buscar pesquisar menu tela página filtro localizar informação', paths: ['/'], steps: ['Na barra lateral, digite o nome da tela ou um termo relacionado; Ctrl+K abre a busca no computador.', 'Para localizar registros dentro de uma tela, use os filtros e a busca daquela lista.', 'Confira o período, a empresa ativa e outros filtros aplicados.', 'Se a tela não aparecer, o recurso pode depender do perfil ou da configuração da empresa.'], tips: ['Pesquise também por termos comuns da rotina, como “canhoto”, “XML” ou “acerto”.', 'Este Centro de ajuda reúne os principais fluxos e pode ser buscado por problema ou tarefa.'] },
  { id: 'manutencao-frota', title: 'Controlar manutenção e abastecimento da frota', category: 'Frota e manutenção', summary: 'Consulte veículos, ordens de manutenção, abastecimentos e odômetros.', keywords: 'frota manutenção oficina ordem serviço abastecimento combustível odômetro veículo pneu', paths: ['/vehicles', '/maintenance-orders', '/fleet-map'], steps: ['Confira o cadastro do veículo e os dados de identificação em Veículos.', 'Registre serviços e acompanhe pendências em Ordens de manutenção.', 'Registre abastecimentos e leituras do odômetro no histórico do veículo.', 'Use os relatórios da frota para comparar os registros no período desejado.'], tips: ['Cadastre placa e veículo antes de lançar uma operação para evitar associação incorreta.', 'Registros de odômetro fora de sequência podem exigir conferência com a leitura anterior.'] },
  { id: 'estoque', title: 'Movimentar estoque e fazer inventário', category: 'Estoque e patrimônio', summary: 'Registre entradas, saídas e contagens para manter o saldo rastreável.', keywords: 'estoque almoxarifado inventário entrada saída produto material saldo contagem patrimônio', paths: ['/stock', '/inventory', '/assets'], steps: ['Confira se o item e sua unidade de medida estão cadastrados corretamente.', 'Use Estoque e almoxarifado para consultar saldo e registrar movimentações.', 'Para conferir o saldo físico, abra Inventário logístico e selecione os itens a contar.', 'Registre as contagens e revise divergências antes de concluir a conferência.'], tips: ['Verifique depósito, unidade de medida e período ao investigar uma divergência.', 'Use Ativos e patrimônio para bens controlados como ativos, em vez de materiais de consumo.'] },
  { id: 'conciliacao', title: 'Importar extrato e conciliar movimentações', category: 'Fiscal e financeiro', summary: 'Compare extratos bancários com os lançamentos e revise diferenças.', keywords: 'banco extrato conciliação conciliar importar OFX CSV movimento divergência', paths: ['/financial/statements', '/bank-reconciliation', '/financial/movements'], steps: ['Abra Extratos importados e envie um arquivo no formato aceito pela tela.', 'Revise as linhas importadas e confirme conta bancária, datas e valores.', 'Abra Conciliação bancária e associe cada linha ao lançamento correspondente.', 'Revise itens sem correspondência e diferenças antes de finalizar o período.'], tips: ['O mesmo extrato pode gerar duplicidade se importado mais de uma vez; confira o período antes do envio.', 'Diferenças de data, valor ou conta podem impedir uma sugestão automática de conciliação.'] },
  { id: 'despesas', title: 'Registrar e aprovar despesas operacionais', category: 'Fiscal e financeiro', summary: 'Acompanhe despesas informadas pela equipe e conclua a revisão financeira.', keywords: 'despesa gasto reembolso motorista comprovante aprovação aprovar centro custo', paths: ['/expense-approval', '/financial/recorded-expenses', '/cost-centers'], steps: ['Acesse Aprovação de despesas para localizar lançamentos que aguardam revisão.', 'Confira valor, categoria, responsável, data e comprovante anexado.', 'Aprove ou devolva para ajuste seguindo as opções da própria tela.', 'Consulte Gastos conferidos para acompanhar despesas aprovadas e seus vínculos.'], tips: ['Uma imagem ou comprovante ilegível pode atrasar a conferência; solicite um arquivo nítido.', 'Confira centro de custo e viagem associados antes de aprovar.'] },
  { id: 'relatorios', title: 'Gerar relatórios e exportar resultados', category: 'Relatórios e análise', summary: 'Escolha o relatório, ajuste o período e revise os filtros antes de exportar.', keywords: 'relatório exportar baixar planilha excel pdf produtividade frota auditoria', paths: ['/reports', '/productivity', '/data-audit'], steps: ['Abra a área de relatórios adequada à pergunta que deseja responder.', 'Defina o intervalo de datas e os filtros disponíveis, como cliente, veículo ou situação.', 'Confira se a tela apresenta os dados esperados antes de exportar.', 'Use a opção de exportação da própria página e guarde o arquivo no local apropriado.'], tips: ['Resultados vazios geralmente estão ligados ao período, empresa ativa ou filtros selecionados.', 'Relatórios operacionais e auditorias podem apresentar critérios e permissões diferentes.'] },
  { id: 'app-motorista', title: 'Usar o aplicativo do motorista', category: 'Operação do motorista', summary: 'Consulte cargas e paradas, registre eventos e acompanhe sincronizações pendentes.', keywords: 'motorista aplicativo celular viagem parada entrega offline sincronizar evento checklist', paths: ['/driver', '/driver/loads', '/driver/stops'], steps: ['Entre na área do motorista com seu próprio acesso e confirme a viagem atribuída.', 'Abra cargas e paradas para consultar as instruções e os documentos da operação.', 'Registre entregas, eventos, despesas ou checklist na seção correspondente.', 'Confira sincronizações pendentes quando voltar a ter conexão e aguarde a confirmação de envio.'], tips: ['Se uma ação não aparecer, confirme se a viagem está atribuída ao usuário e se os dados foram sincronizados.', 'Evite fechar a página enquanto uma operação estiver sendo enviada.'] },
  { id: 'coletas', title: 'Criar e acompanhar uma solicitação de coleta', category: 'Planejamento e cargas', summary: 'Registre a solicitação, revise os dados do cliente e acompanhe sua conversão operacional.', keywords: 'coleta pickup solicitar agendamento cliente endereço mercadoria ordem', paths: ['/pickup-orders', '/orders', '/loads'], steps: ['Abra Coletas e inicie uma solicitação para o cliente correto.', 'Informe endereço, contatos, volumes e janela de coleta solicitada.', 'Revise e salve; acompanhe a situação na lista de coletas.', 'Quando processada, localize a carga ou pedido vinculado e continue o planejamento.'], tips: ['Endereço e telefone de contato ajudam a evitar falhas na coleta.', 'Se o cliente não aparecer, confira o cadastro e a empresa ativa.'] },
  { id: 'rastreamento-alertas', title: 'Configurar monitoramento e alertas de rota', category: 'Rastreamento e entrega', summary: 'Use mapa, cercas virtuais e alertas para acompanhar deslocamentos e desvios.', keywords: 'gps localização cerca geofence mapa alerta corredor rota atraso posição', paths: ['/fleet-map', '/geofences', '/alerts'], steps: ['Confira no Mapa da frota se os veículos e as posições estão disponíveis.', 'Cadastre ou revise as Cercas virtuais e os Corredores monitorados conforme a operação.', 'Acompanhe os avisos em Alertas e abra o detalhe para verificar o evento gerador.', 'Revise a configuração do veículo e a integração de rastreamento quando não houver posições.'], tips: ['A disponibilidade de localização depende da integração e do envio de posições pelo rastreador.', 'Confirme o fuso, a data e o veículo filtrado antes de concluir que uma posição está ausente.'] },
  { id: 'frete', title: 'Consultar ou simular o valor do frete', category: 'Cadastros e operação', summary: 'Revise tabelas e regiões para simular o cálculo aplicado à operação.', keywords: 'frete tarifa preço tabela região simulador cálculo valor', paths: ['/freight', '/regions', '/clients'], steps: ['Confira se as regiões de origem e destino estão cadastradas corretamente.', 'Revise a tabela de frete e suas vigências na área de Frete automático.', 'Abra o simulador, informe os dados da operação e calcule o valor.', 'Compare a composição apresentada com as regras contratadas antes de aplicar ao documento.'], tips: ['Tabelas vencidas ou faixas incompletas podem impedir um cálculo esperado.', 'Verifique peso, valor declarado, distância e adicionais utilizados na simulação.'] },
];

const troubleshooting: TroubleshootingItem[] = [
  { problem: 'Não encontro uma carga, nota ou título', cause: 'Filtros ativos, intervalo de datas ou empresa selecionada podem ocultar o registro.', action: 'Limpe a busca, amplie o período e confira a empresa ativa. Pesquise também por outro identificador, como número, chave ou placa.', keywords: 'sumiu registro não aparece localizar filtro data empresa título nota carga' },
  { problem: 'Não consigo acessar uma tela', cause: 'O perfil do usuário ou a habilitação do recurso para a empresa pode limitar o acesso.', action: 'Confirme a empresa ativa e peça ao administrador para revisar Equipe e acessos e as configurações do módulo.', keywords: 'permissão acesso bloqueado tela perfil usuário módulo' },
  { problem: 'Uma ação ficou carregando ou não concluiu', cause: 'A conexão pode ter oscilado ou a solicitação pode ainda estar sendo processada.', action: 'Atualize a tela uma vez e confira o histórico ou o status antes de repetir. Em caso de erro, anote a mensagem e o horário.', keywords: 'erro falha carregando travou salvar processando duplicado' },
  { problem: 'O documento fiscal foi rejeitado', cause: 'A mensagem de retorno costuma apontar um dado cadastral ou fiscal que precisa de correção.', action: 'Abra o detalhe da rejeição, corrija a informação na origem e confira a situação atual antes de enviar novamente.', keywords: 'rejeição sefaz cte nfse mdfe fiscal erro emissão' },
  { problem: 'A posição do veículo não atualiza', cause: 'O rastreador pode não ter enviado uma posição recente ou a integração pode estar indisponível.', action: 'Confira o horário da última posição, o veículo e a conexão do rastreador. Consulte Integrações se a falha atingir vários veículos.', keywords: 'gps mapa rastreador localização posição frota desatualizada' },
  { problem: 'O total do relatório está diferente', cause: 'O relatório pode usar outro período, situação, empresa ou critério de inclusão.', action: 'Compare os filtros e o período com a tela de origem e verifique se os registros estão em rascunho, pendentes ou concluídos.', keywords: 'divergência valor total relatório quantidade diferente financeiro' },
  { problem: 'O comprovante de entrega não aparece', cause: 'A entrega pode não ter sido sincronizada ou o comprovante pode estar associado a outro documento.', action: 'Confira Canhotos e Rastreabilidade de notas, revise o período e pesquise pela chave ou número da nota.', keywords: 'canhoto comprovante pod entrega imagem ausente foto' },
  { problem: 'Não consigo selecionar um cliente, veículo ou motorista', cause: 'O cadastro pode estar inativo, incompleto ou indisponível para a empresa selecionada.', action: 'Pesquise o cadastro na área correspondente, confira o status e complete os campos obrigatórios antes de voltar ao processo.', keywords: 'lista seleção cadastro não aparece inativo cliente motorista veículo' },
];

const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

type HelpPathAccess = {
  financeAvailable?: boolean;
  capabilityAvailable?: (capability: IntegrationCapability) => boolean;
};

const driverHelpPaths = new Set(['/driver', '/driver/loads', '/driver/stops']);

export function canOpenHelpPath(role: string | null, path: string, access: HelpPathAccess = {}) {
  if (role === 'driver') return driverHelpPaths.has(path);
  if (path === '/driver' || path.startsWith('/driver/')) return false;
  if (!role || !['owner', 'admin', 'operator'].includes(role)) return false;
  const page = findNavigationPage(path);
  if (!page) return false;
  if (page.item.roles && !page.item.roles.includes(role)) return false;
  if (isFinancialPath(path) && access.financeAvailable !== true) return false;
  if (page.item.capability && !access.capabilityAvailable?.(page.item.capability)) return false;
  return true;
}

export default function HelpCenter() {
  const location = useLocation();
  const { currentRole } = useTenant();
  const financeAccess = useFinanceAccess();
  const financeAvailable = financeAccess.data === true && financeAccess.isFetchedAfterMount && !financeAccess.error;
  const { isEnabled, isLoading: capabilitiesLoading, error: capabilitiesError } = useTenantCapabilities();
  const access: HelpPathAccess = {
    financeAvailable,
    capabilityAvailable: capability => !capabilitiesLoading && !capabilitiesError && isEnabled(capability),
  };
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('Todas');
  const currentPath = new URLSearchParams(location.search).get('from') ?? '';
  const currentGuide = guides.find(guide => guide.paths.some(path => currentPath === path || currentPath.startsWith(`${path}/`)));
  const visibleCurrentGuide = currentGuide && (category === 'Todas' || currentGuide.category === category)
    ? currentGuide
    : undefined;
  const results = useMemo(() => {
    const term = normalize(query.trim());
    return guides.filter(guide => (category === 'Todas' || guide.category === category) && (!term || term.split(/\s+/).every(word => normalize(`${guide.title} ${guide.category} ${guide.summary} ${guide.keywords} ${guide.steps.join(' ')} ${guide.tips.join(' ')}`).includes(word))));
  }, [query, category]);
  const issueResults = useMemo(() => {
    const term = normalize(query.trim());
    if (!term) return troubleshooting;
    return troubleshooting.filter(item => term.split(/\s+/).every(word => normalize(`${item.problem} ${item.cause} ${item.action} ${item.keywords}`).includes(word)));
  }, [query]);
  const categories = ['Todas', ...new Set(guides.map(guide => guide.category))];
  const quickPaths = (currentRole === 'driver'
    ? ['/driver', '/driver/loads', '/driver/stops']
    : ['/ingestion', '/loads', '/operations-control', '/traceability', '/cte-hub', '/financial', '/team'])
    .filter(path => canOpenHelpPath(currentRole, path, access));

  return <div className="mx-auto max-w-6xl space-y-6">
    <div className="rounded-2xl bg-primary px-6 py-7 text-primary-foreground md:px-9 md:py-10">
      <div className="flex items-start gap-4"><div className="rounded-xl bg-primary-foreground/15 p-3"><LifeBuoy className="h-6 w-6" /></div><div><p className="text-sm font-medium text-primary-foreground/80">AGVLog · Central de ajuda</p><h1 className="mt-1 text-2xl font-bold md:text-3xl">Como podemos ajudar?</h1><p className="mt-2 max-w-2xl text-sm text-primary-foreground/85">Encontre orientações práticas para localizar telas, concluir processos e resolver dúvidas comuns.</p></div></div>
      <div className="relative mt-6 max-w-2xl"><Search aria-hidden="true" className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input aria-label="Buscar na central de ajuda" placeholder="Ex.: como importar XML, localizar canhoto, dar acesso..." className="h-11 bg-background pl-10 text-foreground" value={query} onChange={event => setQuery(event.target.value)} /></div>
    </div>

    {visibleCurrentGuide && !query && <Card className="border-primary/30"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Ajuda para esta área</p><p className="mt-1 font-medium">{visibleCurrentGuide.title}</p><p className="text-sm text-muted-foreground">{visibleCurrentGuide.summary}</p></div><Button asChild variant="outline"><a href={`#${visibleCurrentGuide.id}`}>Ver orientação <ArrowRight className="ml-2 h-4 w-4" /></a></Button></CardContent></Card>}

    <section aria-labelledby="shortcuts-heading" className="space-y-3"><div><h2 id="shortcuts-heading" className="text-lg font-semibold">Acesso rápido</h2><p className="text-sm text-muted-foreground">Abra diretamente as áreas mais procuradas.</p></div><div className="flex flex-wrap gap-2">{quickPaths.map(path => <Button key={path} asChild size="sm" variant="secondary"><Link to={path}>{findNavigationPage(path)?.item.label ?? path}</Link></Button>)}</div></section>

    <section aria-labelledby="guides-heading" className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="guides-heading" className="text-xl font-semibold">Guias por tarefa</h2><p className="text-sm text-muted-foreground">Passos, atalhos e dicas para os fluxos mais usados.</p></div><span className="text-sm text-muted-foreground">{results.length} {results.length === 1 ? 'guia' : 'guias'}</span></div><div className="flex flex-wrap gap-2" aria-label="Filtrar guias por área">{categories.map(item => <Button key={item} type="button" size="sm" variant={category === item ? 'default' : 'outline'} aria-pressed={category === item} onClick={() => setCategory(item)}>{item}</Button>)}</div>
      {results.length ? <div className="grid gap-4 lg:grid-cols-2">{results.map(guide => <Card key={guide.id} id={guide.id} className="scroll-mt-20"><CardHeader className="pb-3"><p className="text-xs font-medium uppercase tracking-wide text-primary">{guide.category}</p><CardTitle className="flex items-start gap-2 text-lg"><BookOpen className="mt-0.5 h-5 w-5 shrink-0 text-primary" />{guide.title}</CardTitle><p className="text-sm text-muted-foreground">{guide.summary}</p></CardHeader><CardContent className="space-y-4"><ol className="space-y-2 pl-5 text-sm marker:font-semibold marker:text-primary">{guide.steps.map(step => <li key={step} className="list-decimal pl-1">{step}</li>)}</ol><div className="rounded-lg bg-muted/60 p-3"><p className="mb-1 text-xs font-semibold uppercase tracking-wide">Dicas rápidas</p><ul className="space-y-1 text-sm text-muted-foreground">{guide.tips.map(tip => <li key={tip}>• {tip}</li>)}</ul></div><div className="flex flex-wrap gap-2">{guide.paths.map(path => {
        const label = findNavigationPage(path)?.item.label ?? path.slice(1);
        return canOpenHelpPath(currentRole, path, access)
          ? <Button key={path} asChild size="sm" variant="outline"><Link to={path}>{label}<ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></Button>
          : <span key={path} aria-disabled="true" title="Atalho indisponível para este acesso ou configuração" className="inline-flex h-9 items-center rounded-md border border-input bg-muted px-3 text-sm text-muted-foreground">{label}</span>;
      })}</div></CardContent></Card>)}</div> : <Card><CardContent className="flex flex-col items-center gap-2 py-12 text-center"><CircleHelp className="h-8 w-8 text-muted-foreground" /><p className="font-medium">Não encontramos um guia com esses termos.</p><p className="text-sm text-muted-foreground">Tente buscar por uma tarefa, tela ou palavra mais simples.</p><Button variant="outline" onClick={() => { setQuery(''); setCategory('Todas'); }}>Ver todos os guias</Button></CardContent></Card>}
    </section>

    <section aria-labelledby="troubleshooting-heading" className="space-y-4"><div><div className="flex items-center gap-2"><AlertTriangle aria-hidden="true" className="h-5 w-5 text-primary" /><h2 id="troubleshooting-heading" className="text-xl font-semibold">Solução de problemas</h2></div><p className="mt-1 text-sm text-muted-foreground">Respostas rápidas para situações que costumam gerar dúvidas.</p></div>{issueResults.length ? <div className="grid gap-3 md:grid-cols-2">{issueResults.map(item => <Card key={item.problem}><CardHeader className="pb-2"><CardTitle className="flex items-start gap-2 text-base"><Wrench aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />{item.problem}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p><span className="font-medium">Possível causa:</span> {item.cause}</p><p className="text-muted-foreground"><span className="font-medium text-foreground">O que fazer:</span> {item.action}</p></CardContent></Card>)}</div> : <p className="text-sm text-muted-foreground">Nenhum problema encontrado com esses termos.</p>}</section>
    <p className="border-t pt-4 text-sm text-muted-foreground">Ainda precisa de ajuda? Anote a tela, a empresa ativa e a mensagem exibida para encaminhar à equipe de assistência.</p>
  </div>;
}
