
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS trade_name text,
  ADD COLUMN IF NOT EXISTS person_type text,
  ADD COLUMN IF NOT EXISTS state_registration text,
  ADD COLUMN IF NOT EXISTS municipal_registration text,
  ADD COLUMN IF NOT EXISTS ie_indicator text,
  ADD COLUMN IF NOT EXISTS internal_code text,
  ADD COLUMN IF NOT EXISTS sigla text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS cfop_client_type text,
  ADD COLUMN IF NOT EXISTS tax_regime text,
  ADD COLUMN IF NOT EXISTS payer_group text,
  ADD COLUMN IF NOT EXISTS payer text,
  ADD COLUMN IF NOT EXISTS freight_calc_type text,
  ADD COLUMN IF NOT EXISTS cubage_factor numeric,
  ADD COLUMN IF NOT EXISTS accounting_code_client text,
  ADD COLUMN IF NOT EXISTS accounting_code_supplier text,
  ADD COLUMN IF NOT EXISTS budget_group_client text,
  ADD COLUMN IF NOT EXISTS budget_group_supplier text,
  ADD COLUMN IF NOT EXISTS client_type text,
  ADD COLUMN IF NOT EXISTS country_code text DEFAULT '1058',
  ADD COLUMN IF NOT EXISTS country_name text DEFAULT 'BRASIL',
  ADD COLUMN IF NOT EXISTS address_street text,
  ADD COLUMN IF NOT EXISTS address_number text,
  ADD COLUMN IF NOT EXISTS address_complement text,
  ADD COLUMN IF NOT EXISTS address_neighborhood text,
  ADD COLUMN IF NOT EXISTS address_city text,
  ADD COLUMN IF NOT EXISTS address_state text,
  ADD COLUMN IF NOT EXISTS address_zip text,
  ADD COLUMN IF NOT EXISTS contact_name text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS mobile text,
  ADD COLUMN IF NOT EXISTS fax text,
  ADD COLUMN IF NOT EXISTS blocked boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS billed boolean,
  ADD COLUMN IF NOT EXISTS taxes_enabled boolean,
  ADD COLUMN IF NOT EXISTS tax_code text,
  ADD COLUMN IF NOT EXISTS tax_description text,
  ADD COLUMN IF NOT EXISTS notes text;

CREATE INDEX IF NOT EXISTS idx_clients_tenant_tax_id ON public.clients(tenant_id, tax_id);
CREATE INDEX IF NOT EXISTS idx_clients_tenant_company_name_trgm ON public.clients USING gin (company_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_clients_tenant_trade_name_trgm ON public.clients USING gin (trade_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_clients_payer_group ON public.clients(tenant_id, payer_group);
