import {z} from 'zod';
import {supabase} from '@/integrations/supabase/client';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),count=z.number().int().nonnegative();
export const tripMaterializedCorrectionCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,trip_id:uuid,expected_revision:revision,reason:z.string().trim().min(10).max(2000),preserve_history_confirmed:z.literal(true),fiscal_financial_unchanged_confirmed:z.literal(true)}).strict();
export type TripMaterializedCorrectionCommand=z.infer<typeof tripMaterializedCorrectionCommandSchema>;
export const tripMaterializedCorrectionResultSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,trip_id:uuid,request_id:uuid,prior_status:z.string(),status:z.literal('cancelled'),confirmed:z.literal(true),pending_stops_cancelled:count,load_links_preserved:z.literal(true),operational_history_preserved:z.literal(true),fiscal_changed:z.literal(false),financial_changed:z.literal(false)}).strict();
export const tripMaterializedCorrectionPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,trip_id:uuid,status:z.string(),mode:z.literal('materialized_correction'),revision,can_execute:z.boolean(),clean_planned_trip:z.boolean(),completed_correction:z.boolean(),result:tripMaterializedCorrectionResultSchema.nullable(),load_ids:z.array(uuid),stop_ids:z.array(uuid),dependency_counts:z.array(z.object({code:z.string(),count})),pending_stop_count:count}).strict();
type Rpc=(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:{code?:string}|null}>;
export class TripMaterializedCorrectionRejected extends Error{}
async function call(name:string,args:Record<string,unknown>){const {data,error}=await(supabase.rpc as unknown as Rpc)(name,args);if(error){if(/^(22|23|40|42|55)/.test(error.code||''))throw new TripMaterializedCorrectionRejected('O servidor recusou a correção. Consulte novamente a viagem e o histórico preservado.');throw Error('Não foi possível confirmar a resposta. O pedido foi preservado para retomar.');}return data;}
export async function previewTripMaterializedCorrection(tenant:string,actor:string,trip:string){const data=tripMaterializedCorrectionPreviewSchema.parse(await call('preview_dispatch_trip_correction',{_tenant_id:tenant,_trip_id:trip}));if(data.tenant_id!==tenant||data.actor_id!==actor||data.trip_id!==trip)throw Error('Conferência corretiva fora do contexto.');return data;}
export async function correctMaterializedTrip(command:TripMaterializedCorrectionCommand,actor:string){const parsed=tripMaterializedCorrectionCommandSchema.parse(command),data=tripMaterializedCorrectionResultSchema.parse(await call('correct_dispatch_trip',{_payload:parsed}));if(data.tenant_id!==parsed.tenant_id||data.actor_id!==actor||data.trip_id!==parsed.trip_id||data.request_id!==parsed.request_id)throw Error('Confirmação corretiva fora do pedido original.');return data;}
