-- Dados extraídos da migration 20260416190208_6ece5360-5ff6-44ee-8ade-1346aa2b5290.sql
-- Motivo: DML com tenant_id fixo não pertence ao histórico reutilizável de schema.
-- Execução manual, opcional, apenas em ambientes que já possuem o tenant referenciado.

INSERT INTO public.operational_routes (tenant_id, name, classification, destinations, periodicity_default, active)
SELECT v.tenant_id, v.name, v.classification, v.destinations, v.periodicity_default, v.active
FROM (VALUES

  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 01 - UBERLANDIA', 'municipality', '[{"name": "UBERLANDIA 05", "periodicity": "daily", "weekdays": []}]'::jsonb, 'daily', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 02 - ARAGUARI', 'municipality', '[{"name": "ARAGUARI", "periodicity": "weekly", "weekdays": [2, 3, 4, 5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 03 - MONTE CARMELO', 'municipality', '[{"name": "MONTE CARMELO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "COROMANDEL", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "ABADIA DOS DOURADOS", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "CASCALHO RICO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ESTRELA DO SUL", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ROMARIA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "INDIANOPOLIS", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 04 - PATROCINIO', 'municipality', '[{"name": "PATROCINIO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "GUIMARÂNIA", "periodicity": "biweekly", "weekdays": [3]}, {"name": "IRAI DE MINAS", "periodicity": "biweekly", "weekdays": [3]}, {"name": "SERRA DO SALITRE", "periodicity": "weekly", "weekdays": [5]}, {"name": "BREJO BONITO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "S.JOÃO DA SERRA NEGRA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CRUZEIRO DA FORTALEZA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 05 - PATOS DE MINAS', 'municipality', '[{"name": "PATOS DE MINAS", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "PRESIDENTE OLEGARIO", "periodicity": "biweekly", "weekdays": [3]}, {"name": "SANTANA DE PATOS", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 06 - SAO GOTARDO', 'municipality', '[{"name": "CARMO DO PARANAIBA", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "SÃO GOTARDO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "LAGOA FORMOSA", "periodicity": "biweekly", "weekdays": [3]}, {"name": "TIROS", "periodicity": "biweekly", "weekdays": [3]}, {"name": "MATUTINA", "periodicity": "biweekly", "weekdays": [3]}, {"name": "ARAPUÃ", "periodicity": "biweekly", "weekdays": [5]}, {"name": "RIO PARANAIBA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 07 - ITUIUTABA', 'municipality', '[{"name": "ITUIUTABA", "periodicity": "weekly", "weekdays": [3, 5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 08 - NOVA PONTE', 'municipality', '[{"name": "NOVA PONTE", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "SANTA JULIANA", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "PERDIZES", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "PEDRINOPOLIS", "periodicity": "weekly", "weekdays": [5]}, {"name": "TAPUIRAMA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 09 - ARAXA', 'municipality', '[{"name": "ARAXA", "periodicity": "weekly", "weekdays": [3, 5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 10 - UBERABA', 'municipality', '[{"name": "UBERABA", "periodicity": "weekly", "weekdays": [3, 5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 11 - CONCEICAO DAS ALAGOAS', 'municipality', '[{"name": "CONCEICAO DAS ALAGOAS", "periodicity": "weekly", "weekdays": [3]}, {"name": "AGUA COMPRIDA", "periodicity": "weekly", "weekdays": [3]}, {"name": "CAMPO FLORIDO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "VERISSIMO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PIRAJUBA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 12 - SACRAMENTO', 'municipality', '[{"name": "SACRAMENTO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "DELTA", "periodicity": "weekly", "weekdays": [5]}, {"name": "CONQUISTA", "periodicity": "weekly", "weekdays": [5]}, {"name": "PEIROPOLIS", "periodicity": "weekly", "weekdays": [5]}, {"name": "PONTE ALTA", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 13 - TUPACIGUARA', 'municipality', '[{"name": "TUPACIGUARA", "periodicity": "weekly", "weekdays": [5]}, {"name": "MONTE ALEGRE", "periodicity": "weekly", "weekdays": [5]}, {"name": "ARAPORÃ", "periodicity": "weekly", "weekdays": [5]}, {"name": "CENTRALINA", "periodicity": "weekly", "weekdays": [5]}, {"name": "CANAPOLIS", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 14 - FRUTAL', 'municipality', '[{"name": "FRUTAL", "periodicity": "weekly", "weekdays": [5]}, {"name": "APARECIDA DE MINAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "COMENDADOR GOMES", "periodicity": "biweekly", "weekdays": [5]}, {"name": "FRONTEIRA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ITAPAGIPE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PLANURA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PRADOLANDIA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "S.FRANCISCO DE SALES", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 15 - ITURAMA', 'municipality', '[{"name": "ITURAMA", "periodicity": "weekly", "weekdays": [5]}, {"name": "ALEXANDRITA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CARNEIRINHO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "S.SEBASTIÃO DO PONTAL", "periodicity": "biweekly", "weekdays": [5]}, {"name": "HONOROPOLIS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "LIMEIRA DO OESTE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "UNIÃO DE MINAS", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 16 - PRATA', 'municipality', '[{"name": "PRATA", "periodicity": "weekly", "weekdays": [5]}, {"name": "CAMPINA VERDE", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 17 - IBIA', 'municipality', '[{"name": "IBIA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "TAPIRA", "periodicity": "monthly", "weekdays": [5]}, {"name": "CAMPOS ALTOS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "SANTA ROSA DA SERRA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PRATINHA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 18 - SANTA VITORIA', 'municipality', '[{"name": "SANTA VITORIA", "periodicity": "weekly", "weekdays": [5]}, {"name": "GURINHATÃ", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 19 - CAPINOPOLIS', 'municipality', '[{"name": "CAPINOPOLIS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CACHOEIRA DOURADA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "IPIACU", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 20 - UNAI / PARACATU', 'municipality', '[{"name": "PARACATU", "periodicity": "weekly", "weekdays": [5]}, {"name": "UNAI", "periodicity": "weekly", "weekdays": [5]}, {"name": "JOÃO PINHEIRO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "BRASILANDIA DE MINAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ARINOS", "periodicity": "monthly", "weekdays": [5]}, {"name": "BURITIS", "periodicity": "monthly", "weekdays": [5]}, {"name": "URUCUIA", "periodicity": "monthly", "weekdays": [5]}, {"name": "RIACHINHO", "periodicity": "monthly", "weekdays": [5]}]'::jsonb, 'monthly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 21 - VAZANTE', 'municipality', '[{"name": "GUARDA MOR", "periodicity": "biweekly", "weekdays": [5]}, {"name": "LAGAMAR", "periodicity": "biweekly", "weekdays": [5]}, {"name": "LAGOA GRANDE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "VAZANTE", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 22 - MONTES CLAROS / CURVELO', 'municipality', '[{"name": "MONTES CLAROS", "periodicity": "weekly", "weekdays": [1, 2, 4]}, {"name": "BOCAIUVA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "CURVELO", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "AUGUSTO DE LIMA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "BUENOPOLIS", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "ENGENHEIRO NAVARRO", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "FELIXLANDIA", "periodicity": "biweekly", "weekdays": [2, 5]}, {"name": "JOAQUIM FELICIO", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "SÃO GONÇALO DO ABAETE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "TRES MARIAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "VARJÃO DE MINAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CORINTO", "periodicity": "weekly", "weekdays": [4]}, {"name": "FRANCISCO DUMONT", "periodicity": "monthly", "weekdays": [4]}, {"name": "GUARACIAMA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MORRO DA GARÇA", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 23 - JANAUBA / ESPINOSA', 'municipality', '[{"name": "ESPINOSA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "JANAUBA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "MONTE AZUL", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "JAIBA", "periodicity": "biweekly", "weekdays": [2, 4]}, {"name": "PORTEIRINHA", "periodicity": "biweekly", "weekdays": [2]}, {"name": "VERDELANDIA", "periodicity": "biweekly", "weekdays": [2]}, {"name": "CAPITÃO ENEAS", "periodicity": "weekly", "weekdays": [4]}, {"name": "MATO VERDE", "periodicity": "weekly", "weekdays": [4]}, {"name": "NOVA PORTEIRINHA", "periodicity": "weekly", "weekdays": [4]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 24 - JANUARIA', 'municipality', '[{"name": "JANUARIA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "ITACARAMBI", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MANGA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MONTALVANIA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SÃO JOÃO DAS MISSÕES", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'weekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 25 - SALINAS', 'municipality', '[{"name": "SALINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "TAIOBEIRAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "RIO PARDO DE MINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "ARACUAI", "periodicity": "biweekly", "weekdays": [4]}, {"name": "ITAOBIM", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MEDINA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "PADRE PARAISO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "ITINGA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "JEQUITINHONHA", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 26 - PIRAPORA', 'municipality', '[{"name": "PIRAPORA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "BURITIZEIRO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "VARZEA DA PALMA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "LASSANCE", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SANTA FE DE MINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "PONTO CHIQUE", "periodicity": "biweekly", "weekdays": [4]}, {"name": "JEQUITAI", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 27 - SAO FRANCISCO', 'municipality', '[{"name": "BRASILIA DE MINAS", "periodicity": "biweekly", "weekdays": [2]}, {"name": "LUISLANDIA", "periodicity": "biweekly", "weekdays": [2]}, {"name": "SÃO FRANCISCO", "periodicity": "biweekly", "weekdays": [2]}, {"name": "SÃO ROMÃO", "periodicity": "biweekly", "weekdays": [2]}, {"name": "UBAÍ", "periodicity": "biweekly", "weekdays": [2]}, {"name": "PINTOPOLIS", "periodicity": "biweekly", "weekdays": [2]}]'::jsonb, 'biweekly', true),
  ('db36dc9b-2bfb-4e3f-985b-ec4880b7ee97'::uuid, 'ROTA 29 - DIAMANTINA', 'municipality', '[{"name": "DIAMANTINA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "GOUVEIA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SERRO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "DATAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "FELICIO DOS SANTOS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "COUTO DE M. DE MINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "PRESIDENTE KUBITCHEK", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SENADOR M. GONÇALVES", "periodicity": "biweekly", "weekdays": [4]}, {"name": "CONCEIÇÃO M. DENTRO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "CONGONHAS DO NORTE", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SÃO G. DO RIO PRETO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "OLHOS-D ÁGUA", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'biweekly', true),

  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 01 - UBERLANDIA', 'municipality', '[{"name": "UBERLANDIA 05", "periodicity": "daily", "weekdays": []}]'::jsonb, 'daily', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 02 - ARAGUARI', 'municipality', '[{"name": "ARAGUARI", "periodicity": "weekly", "weekdays": [2, 3, 4, 5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 03 - MONTE CARMELO', 'municipality', '[{"name": "MONTE CARMELO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "COROMANDEL", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "ABADIA DOS DOURADOS", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "CASCALHO RICO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ESTRELA DO SUL", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ROMARIA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "INDIANOPOLIS", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 04 - PATROCINIO', 'municipality', '[{"name": "PATROCINIO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "GUIMARÂNIA", "periodicity": "biweekly", "weekdays": [3]}, {"name": "IRAI DE MINAS", "periodicity": "biweekly", "weekdays": [3]}, {"name": "SERRA DO SALITRE", "periodicity": "weekly", "weekdays": [5]}, {"name": "BREJO BONITO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "S.JOÃO DA SERRA NEGRA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CRUZEIRO DA FORTALEZA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 05 - PATOS DE MINAS', 'municipality', '[{"name": "PATOS DE MINAS", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "PRESIDENTE OLEGARIO", "periodicity": "biweekly", "weekdays": [3]}, {"name": "SANTANA DE PATOS", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 06 - SAO GOTARDO', 'municipality', '[{"name": "CARMO DO PARANAIBA", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "SÃO GOTARDO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "LAGOA FORMOSA", "periodicity": "biweekly", "weekdays": [3]}, {"name": "TIROS", "periodicity": "biweekly", "weekdays": [3]}, {"name": "MATUTINA", "periodicity": "biweekly", "weekdays": [3]}, {"name": "ARAPUÃ", "periodicity": "biweekly", "weekdays": [5]}, {"name": "RIO PARANAIBA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 07 - ITUIUTABA', 'municipality', '[{"name": "ITUIUTABA", "periodicity": "weekly", "weekdays": [3, 5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 08 - NOVA PONTE', 'municipality', '[{"name": "NOVA PONTE", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "SANTA JULIANA", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "PERDIZES", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "PEDRINOPOLIS", "periodicity": "weekly", "weekdays": [5]}, {"name": "TAPUIRAMA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 09 - ARAXA', 'municipality', '[{"name": "ARAXA", "periodicity": "weekly", "weekdays": [3, 5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 10 - UBERABA', 'municipality', '[{"name": "UBERABA", "periodicity": "weekly", "weekdays": [3, 5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 11 - CONCEICAO DAS ALAGOAS', 'municipality', '[{"name": "CONCEICAO DAS ALAGOAS", "periodicity": "weekly", "weekdays": [3]}, {"name": "AGUA COMPRIDA", "periodicity": "weekly", "weekdays": [3]}, {"name": "CAMPO FLORIDO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "VERISSIMO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PIRAJUBA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 12 - SACRAMENTO', 'municipality', '[{"name": "SACRAMENTO", "periodicity": "weekly", "weekdays": [3, 5]}, {"name": "DELTA", "periodicity": "weekly", "weekdays": [5]}, {"name": "CONQUISTA", "periodicity": "weekly", "weekdays": [5]}, {"name": "PEIROPOLIS", "periodicity": "weekly", "weekdays": [5]}, {"name": "PONTE ALTA", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 13 - TUPACIGUARA', 'municipality', '[{"name": "TUPACIGUARA", "periodicity": "weekly", "weekdays": [5]}, {"name": "MONTE ALEGRE", "periodicity": "weekly", "weekdays": [5]}, {"name": "ARAPORÃ", "periodicity": "weekly", "weekdays": [5]}, {"name": "CENTRALINA", "periodicity": "weekly", "weekdays": [5]}, {"name": "CANAPOLIS", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 14 - FRUTAL', 'municipality', '[{"name": "FRUTAL", "periodicity": "weekly", "weekdays": [5]}, {"name": "APARECIDA DE MINAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "COMENDADOR GOMES", "periodicity": "biweekly", "weekdays": [5]}, {"name": "FRONTEIRA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ITAPAGIPE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PLANURA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PRADOLANDIA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "S.FRANCISCO DE SALES", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 15 - ITURAMA', 'municipality', '[{"name": "ITURAMA", "periodicity": "weekly", "weekdays": [5]}, {"name": "ALEXANDRITA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CARNEIRINHO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "S.SEBASTIÃO DO PONTAL", "periodicity": "biweekly", "weekdays": [5]}, {"name": "HONOROPOLIS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "LIMEIRA DO OESTE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "UNIÃO DE MINAS", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 16 - PRATA', 'municipality', '[{"name": "PRATA", "periodicity": "weekly", "weekdays": [5]}, {"name": "CAMPINA VERDE", "periodicity": "weekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 17 - IBIA', 'municipality', '[{"name": "IBIA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "TAPIRA", "periodicity": "monthly", "weekdays": [5]}, {"name": "CAMPOS ALTOS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "SANTA ROSA DA SERRA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "PRATINHA", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 18 - SANTA VITORIA', 'municipality', '[{"name": "SANTA VITORIA", "periodicity": "weekly", "weekdays": [5]}, {"name": "GURINHATÃ", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 19 - CAPINOPOLIS', 'municipality', '[{"name": "CAPINOPOLIS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CACHOEIRA DOURADA", "periodicity": "biweekly", "weekdays": [5]}, {"name": "IPIACU", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 20 - UNAI / PARACATU', 'municipality', '[{"name": "PARACATU", "periodicity": "weekly", "weekdays": [5]}, {"name": "UNAI", "periodicity": "weekly", "weekdays": [5]}, {"name": "JOÃO PINHEIRO", "periodicity": "biweekly", "weekdays": [5]}, {"name": "BRASILANDIA DE MINAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "ARINOS", "periodicity": "monthly", "weekdays": [5]}, {"name": "BURITIS", "periodicity": "monthly", "weekdays": [5]}, {"name": "URUCUIA", "periodicity": "monthly", "weekdays": [5]}, {"name": "RIACHINHO", "periodicity": "monthly", "weekdays": [5]}]'::jsonb, 'monthly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 21 - VAZANTE', 'municipality', '[{"name": "GUARDA MOR", "periodicity": "biweekly", "weekdays": [5]}, {"name": "LAGAMAR", "periodicity": "biweekly", "weekdays": [5]}, {"name": "LAGOA GRANDE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "VAZANTE", "periodicity": "biweekly", "weekdays": [5]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 22 - MONTES CLAROS / CURVELO', 'municipality', '[{"name": "MONTES CLAROS", "periodicity": "weekly", "weekdays": [1, 2, 4]}, {"name": "BOCAIUVA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "CURVELO", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "AUGUSTO DE LIMA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "BUENOPOLIS", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "ENGENHEIRO NAVARRO", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "FELIXLANDIA", "periodicity": "biweekly", "weekdays": [2, 5]}, {"name": "JOAQUIM FELICIO", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "SÃO GONÇALO DO ABAETE", "periodicity": "biweekly", "weekdays": [5]}, {"name": "TRES MARIAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "VARJÃO DE MINAS", "periodicity": "biweekly", "weekdays": [5]}, {"name": "CORINTO", "periodicity": "weekly", "weekdays": [4]}, {"name": "FRANCISCO DUMONT", "periodicity": "monthly", "weekdays": [4]}, {"name": "GUARACIAMA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MORRO DA GARÇA", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 23 - JANAUBA / ESPINOSA', 'municipality', '[{"name": "ESPINOSA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "JANAUBA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "MONTE AZUL", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "JAIBA", "periodicity": "biweekly", "weekdays": [2, 4]}, {"name": "PORTEIRINHA", "periodicity": "biweekly", "weekdays": [2]}, {"name": "VERDELANDIA", "periodicity": "biweekly", "weekdays": [2]}, {"name": "CAPITÃO ENEAS", "periodicity": "weekly", "weekdays": [4]}, {"name": "MATO VERDE", "periodicity": "weekly", "weekdays": [4]}, {"name": "NOVA PORTEIRINHA", "periodicity": "weekly", "weekdays": [4]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 24 - JANUARIA', 'municipality', '[{"name": "JANUARIA", "periodicity": "weekly", "weekdays": [2, 4]}, {"name": "ITACARAMBI", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MANGA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MONTALVANIA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SÃO JOÃO DAS MISSÕES", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'weekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 25 - SALINAS', 'municipality', '[{"name": "SALINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "TAIOBEIRAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "RIO PARDO DE MINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "ARACUAI", "periodicity": "biweekly", "weekdays": [4]}, {"name": "ITAOBIM", "periodicity": "biweekly", "weekdays": [4]}, {"name": "MEDINA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "PADRE PARAISO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "ITINGA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "JEQUITINHONHA", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 26 - PIRAPORA', 'municipality', '[{"name": "PIRAPORA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "BURITIZEIRO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "VARZEA DA PALMA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "LASSANCE", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SANTA FE DE MINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "PONTO CHIQUE", "periodicity": "biweekly", "weekdays": [4]}, {"name": "JEQUITAI", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 27 - SAO FRANCISCO', 'municipality', '[{"name": "BRASILIA DE MINAS", "periodicity": "biweekly", "weekdays": [2]}, {"name": "LUISLANDIA", "periodicity": "biweekly", "weekdays": [2]}, {"name": "SÃO FRANCISCO", "periodicity": "biweekly", "weekdays": [2]}, {"name": "SÃO ROMÃO", "periodicity": "biweekly", "weekdays": [2]}, {"name": "UBAÍ", "periodicity": "biweekly", "weekdays": [2]}, {"name": "PINTOPOLIS", "periodicity": "biweekly", "weekdays": [2]}]'::jsonb, 'biweekly', true),
  ('6e874e6e-5bca-486d-9928-bef0646989c4'::uuid, 'ROTA 29 - DIAMANTINA', 'municipality', '[{"name": "DIAMANTINA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "GOUVEIA", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SERRO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "DATAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "FELICIO DOS SANTOS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "COUTO DE M. DE MINAS", "periodicity": "biweekly", "weekdays": [4]}, {"name": "PRESIDENTE KUBITCHEK", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SENADOR M. GONÇALVES", "periodicity": "biweekly", "weekdays": [4]}, {"name": "CONCEIÇÃO M. DENTRO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "CONGONHAS DO NORTE", "periodicity": "biweekly", "weekdays": [4]}, {"name": "SÃO G. DO RIO PRETO", "periodicity": "biweekly", "weekdays": [4]}, {"name": "OLHOS-D ÁGUA", "periodicity": "biweekly", "weekdays": [4]}]'::jsonb, 'biweekly', true)

) AS v(tenant_id, name, classification, destinations, periodicity_default, active)
WHERE NOT EXISTS (
  SELECT 1 FROM public.operational_routes r
  WHERE r.tenant_id = v.tenant_id AND r.name = v.name
);