import {supabase} from '@/integrations/supabase/client';
import {accountPeriodHistorySchema,accountPeriodClosePreviewSchema,accountPeriodPendingSchema,accountPeriodCloseResultSchema,accountPeriodReopenResultSchema,type AccountPeriodPending} from './accountPeriodCloseContract';
type Rpc=(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:{message:string;code?:string}|null}>;
export class AccountPeriodCloseRejectedError extends Error {}
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await(supabase.rpc as unknown as Rpc)(name,args);if(error){if(['22023','23514','23505','40001','42501','55000'].includes(error.code||''))throw new AccountPeriodCloseRejectedError(error.message);throw new Error(error.message);}return data;}
export async function submitAccountPeriodDecision(pending:AccountPeriodPending){accountPeriodPendingSchema.parse(pending);const raw=await rpc(pending.kind==='close'?'close_finance_account_period':'reopen_finance_account_period',{_payload:pending.command});const result=pending.kind==='close'?accountPeriodCloseResultSchema.parse(raw):accountPeriodReopenResultSchema.parse(raw);if(result.tenant_id!==pending.command.tenant_id||result.request_id!==pending.command.request_id)throw new Error('Confirmação fora do pedido de fechamento.');if(pending.kind==='close'){const closed=accountPeriodCloseResultSchema.parse(result);if(closed.account_id!==pending.command.account_id||closed.from!==pending.command.from||closed.to!==pending.command.to||closed.revision!==pending.command.revision)throw new Error('Confirmação fora do período revisado.');}else if(result.closure_id!==pending.command.closure_id)throw new Error('Reabertura fora do fechamento escolhido.');return result;}

export async function readAccountPeriodClosePreview(tenant:string,account:string,from:string,to:string){const result=accountPeriodClosePreviewSchema.parse(await rpc('preview_finance_account_period_close',{_tenant_id:tenant,_account_id:account,_from:from,_to:to}));if(result.tenant_id!==tenant||result.account_id!==account||result.from!==from||result.to!==to)throw new Error('Conferência fora da conta ou período.');return result;}


export async function readAccountPeriodHistory(tenant:string,account:string,offset=0,limit=30){const result=accountPeriodHistorySchema.parse(await rpc('get_finance_account_period_history',{_tenant_id:tenant,_account_id:account,_offset:offset,_limit:limit}));if(result.tenant_id!==tenant||result.account_id!==account||result.offset!==offset||result.limit!==limit)throw new Error('Histórico fora da conta ou página.');return result;}
