import {z} from 'zod';
import {cashCountsSchema} from './cashOpeningContract';
import {accountPeriodReopenCommandSchema} from './accountPeriodCloseContract';
const uuid=z.string().uuid(),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),revision=z.string().regex(/^[a-f0-9]{32}$/),reason=z.string().trim().min(10).max(2000),cents=z.string().regex(/^\d+$/),signed=z.string().regex(/^-?\d+$/),base={version:z.literal(1),tenant_id:uuid,request_id:uuid};
export const cashPeriodCountCommandSchema=z.object({...base,account_id:uuid,period_end:date,counts:cashCountsSchema,custodian_name:z.string().trim().min(2).max(200),reason,counted_at_boundary:z.literal('end_of_day')}).strict();
export const cashPeriodCountReverseCommandSchema=z.object({...base,count_id:uuid,revision,reason}).strict();
export const cashPeriodCloseCommandSchema=z.object({...base,account_id:uuid,from:date,to:date,count_id:uuid,revision,reason}).strict().refine(value=>value.from<=value.to);
export const cashPeriodPendingSchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('record_count'),command:cashPeriodCountCommandSchema}),z.object({kind:z.literal('reverse_count'),command:cashPeriodCountReverseCommandSchema}),z.object({kind:z.literal('close'),command:cashPeriodCloseCommandSchema}),z.object({kind:z.literal('reopen'),command:accountPeriodReopenCommandSchema})]);
export type CashPeriodPending=z.infer<typeof cashPeriodPendingSchema>;
export type CashPeriodCountCommand=z.infer<typeof cashPeriodCountCommandSchema>;
const countResult={...base,count_id:uuid,account_id:uuid,period_end:date,counted_cents:cents,revision,confirmed:z.literal(true),cash_created:z.literal(false)};
export const cashPeriodCountResultSchema=z.object(countResult);
export const cashPeriodCountReverseResultSchema=z.object({...countResult,reversal_id:uuid});
export const cashPeriodCloseResultSchema=z.object({...base,account_id:uuid,closure_id:uuid,from:date,to:date,revision,confirmed:z.literal(true),cash_changed:z.literal(false)});
export const cashPeriodCountSchema=z.object({id:uuid,tenant_id:uuid,account_id:uuid,period_end:date,evidence_type:z.literal('cash_count_v1'),currency:z.literal('BRL'),timezone:z.literal('America/Sao_Paulo'),boundary:z.literal('end_of_day'),counts:cashCountsSchema,total_cents:cents,custodian_name:z.string(),actor_id:uuid,actor_name:z.string(),reason:z.string(),request_id:uuid,revision,created_at:z.string()}).passthrough();
export const cashPeriodPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,account_id:uuid,from:date,to:date,currency:z.literal('BRL'),timezone:z.literal('America/Sao_Paulo'),evidence_type:z.literal('cash_count_v1'),revision,eligible:z.boolean(),can_execute:z.boolean(),blockers:z.array(z.object({code:z.string(),source_table:z.string().nullable(),source_ids:z.array(uuid),scope:z.literal('account')})),opening_id:uuid.nullable(),predecessor_id:uuid.nullable(),count:cashPeriodCountSchema.nullable(),balances:z.object({opening_cents:signed.nullable(),in_cents:cents.nullable(),out_cents:cents.nullable(),expected_closing_cents:signed.nullable(),counted_closing_cents:cents.nullable(),difference_cents:signed.nullable(),closing_cents:signed.nullable()})}).passthrough().superRefine((data,ctx)=>{if(data.from>data.to||data.eligible!==(data.blockers.length===0)||(data.count&&(data.count.tenant_id!==data.tenant_id||data.count.account_id!==data.account_id||data.count.period_end!==data.to))||(data.eligible&&(!data.count||data.balances.difference_cents!=='0'||Object.values(data.balances).some(value=>value===null))))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Conferência do caixa inconsistente.'});});
export type CashPeriodPreview=z.infer<typeof cashPeriodPreviewSchema>;
export const cashPeriodIssueLabels:Record<string,string>={};
const countReversalSchema=z.object({id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).passthrough();
export const cashPeriodCountsSchema=z.object({version:z.literal(1),tenant_id:uuid,account_id:uuid,period_end:date,page:z.number().int().positive(),page_size:z.literal(30),total:z.number().int().nonnegative(),active_count_id:uuid.nullable(),can_record:z.boolean(),can_reverse:z.boolean(),rows:z.array(cashPeriodCountSchema.extend({reversal:countReversalSchema.nullable(),can_reverse:z.boolean()})).max(30)}).superRefine((data,ctx)=>{if(data.rows.length>data.total||new Set(data.rows.map(row=>row.id)).size!==data.rows.length||data.rows.some(row=>row.tenant_id!==data.tenant_id||row.account_id!==data.account_id||row.period_end!==data.period_end||(row.can_reverse&&(!data.can_reverse||row.reversal!==null))||row.total_cents!==row.counts.reduce((sum,line)=>sum+BigInt(line.denomination_cents)*BigInt(line.quantity),0n).toString()))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Contagens fora do período ou inconsistentes.'});});
export type CashPeriodCounts=z.infer<typeof cashPeriodCountsSchema>;
export const cashPeriodCountHistorySchema=cashPeriodCountsSchema;
Object.assign(cashPeriodIssueLabels,{
 cash_account_required:'Selecione uma conta ativa de caixa físico em reais.',cash_opening_requires_review:'A abertura física precisa estar válida e revisada.',cash_count_requires_review:'A contagem escolhida precisa estar ativa e corresponder ao encerramento deste dia.',cash_count_integrity_failure:'A discriminação da contagem não corresponde ao total preservado.',cash_count_difference:'A contagem difere do saldo esperado. Investigue a falta ou sobra antes de fechar.',cash_has_bank_evidence_anomaly:'Existem evidências bancárias vinculadas indevidamente a este caixa. Revise essas origens.',cash_negative_position:'Os registros resultam em saldo negativo de caixa. Revise os movimentos.',closed_period_guards_incomplete:'As proteções do fechamento ainda precisam de revisão.',period_not_ended:'O dia final ainda não terminou em São Paulo.',finance_cash_account_required:'Esta operação exige conta ativa de caixa físico em reais.',finance_cash_count_already_active:'Já existe uma contagem ativa para esse encerramento. Confira o histórico.',finance_cash_count_busy:'Outra operação está alterando o caixa. Atualize a consulta.',finance_cash_count_changed:'A contagem mudou desde a revisão. Atualize e revise novamente.',finance_cash_count_not_found:'A contagem não foi encontrada nesta empresa.',finance_cash_count_total_mismatch:'O total não corresponde às cédulas e moedas declaradas.',finance_cash_period_not_ended:'Registre a contagem de um dia já encerrado em São Paulo.',finance_account_period_closed:'O período está fechado. Reabra-o antes de corrigir a contagem.',finance_account_not_found:'A conta não foi encontrada nesta empresa.'
});
