import {z} from 'zod';
import {cashForecastCollectorSchema} from './cashForecastCollectorContract';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),signed=z.string().regex(/^-?(0|[1-9]\d*)$/),cents=z.string().regex(/^(0|[1-9]\d*)$/),day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),stamp=z.string().datetime({offset:true});
const collected=cashForecastCollectorSchema.innerType().shape;
const scenario=z.object({complete:z.boolean(),closing_cents:signed.nullable()}).refine(v=>v.complete||v.closing_cents===null,'Cenário incompleto não tem saldo final determinado.');
export const cashForecastSummarySchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,revision,captured_at:stamp,cutoff:day,period_end:day,account_scope:collected.account_scope,base:collected.base,projection_available:z.boolean(),confirmed:scenario.nullable(),expanded:scenario.nullable(),recorded_totals:z.object({in_cents:cents,out_cents:cents}).nullable(),scheduled:z.object({confirmed_in_cents:cents,confirmed_out_cents:cents,unbilled_in_cents:cents}).nullable(),unscheduled:z.object({confirmed_cents:cents,unbilled_cents:cents}).nullable(),unassigned_credit_cents:cents.nullable(),counts:collected.counts,issue_groups:z.array(z.object({scope:z.enum(['confirmed','expanded','all']),code:z.string(),count:z.number().int().nonnegative()}))}).superRefine((v,c)=>{const fail=()=>c.addIssue({code:'custom',message:'Resumo de previsão incompatível.'});if(v.cutoff>=v.period_end||v.base.as_of!==v.cutoff||v.counts.accounts!==v.account_scope.account_ids.length)fail();if(v.base.components.length!==v.counts.accounts||new Set(v.account_scope.account_ids).size!==v.counts.accounts||new Set(v.base.components.map(x=>x.account_id)).size!==v.counts.accounts||v.base.components.some(x=>!v.account_scope.account_ids.includes(x.account_id)))fail();if(v.projection_available!==Boolean(v.counts.accounts))fail();const validNumbers=[v.base.amount_cents,...v.base.components.map(x=>x.amount_cents),v.confirmed?.closing_cents,v.expanded?.closing_cents,...Object.values(v.recorded_totals??{}),...Object.values(v.scheduled??{})].every(x=>x==null||signed.safeParse(x).success);if(validNumbers){const unknown=v.base.components.length===0||v.base.components.some(x=>x.amount_cents===null);if(unknown?(v.base.amount_cents!==null||v.base.confirmation!=='unverified'):(v.base.amount_cents===null||v.base.components.reduce((n,x)=>n+BigInt(x.amount_cents!),0n)!==BigInt(v.base.amount_cents)))fail();if(v.base.amount_cents!==null&&v.recorded_totals&&v.scheduled){const expected=BigInt(v.base.amount_cents)+BigInt(v.recorded_totals.in_cents)-BigInt(v.recorded_totals.out_cents)+BigInt(v.scheduled.confirmed_in_cents)-BigInt(v.scheduled.confirmed_out_cents);if(v.confirmed?.closing_cents!==null&&v.confirmed&&BigInt(v.confirmed.closing_cents)!==expected)fail();if(v.expanded?.closing_cents!==null&&v.expanded&&BigInt(v.expanded.closing_cents)!==expected+BigInt(v.scheduled.unbilled_in_cents))fail();}}if([v.confirmed,v.expanded,v.recorded_totals,v.scheduled,v.unscheduled].some(x=>(x!==null)!==v.projection_available))fail();if(v.base.amount_cents===null&&(v.confirmed?.closing_cents!==null&&v.confirmed!==null||v.expanded?.closing_cents!==null&&v.expanded!==null))fail();});
export const cashForecastPreviewSchema=cashForecastSummarySchema.innerType().extend({can_record:z.boolean()}).superRefine((v,c)=>{const result=cashForecastSummarySchema.safeParse(v);if(!result.success)c.addIssue({code:'custom',message:'Resumo de previsão inválido.'});});
const identity=z.object({version:z.literal(1),tenant_id:uuid,snapshot_id:uuid,request_id:uuid,actor_id:uuid,actor_name:z.string(),title:z.string(),reason:z.string(),created_at:stamp,source_revision:revision,content_hash:revision});
export const cashForecastSnapshotSchema=identity.extend({viewer_actor_id:uuid,summary:cashForecastSummarySchema}).superRefine((v,c)=>{if(v.summary.tenant_id!==v.tenant_id||v.summary.actor_id!==v.actor_id||v.summary.revision!==v.source_revision)c.addIssue({code:'custom',message:'Origem preservada incompatível.'});});
export const cashForecastHistorySchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,page:z.number().int().positive(),page_size:z.literal(30),total:z.number().int().nonnegative(),revision,rows:z.array(identity.omit({version:true,tenant_id:true}).extend({cutoff:day,period_end:day,confirmed_complete:z.boolean(),expanded_complete:z.boolean()})).max(30)});
const page={version:z.literal(1),tenant_id:uuid,actor_id:uuid,snapshot_id:uuid.nullable(),page:z.number().int().positive(),page_size:z.literal(30),total:z.number().int().nonnegative(),revision};
const display=z.object({basis:z.literal('current_identification'),label:z.string().nullable(),party_name:z.string().nullable(),description:z.string().nullable(),document_number:z.string().nullable()}).optional();
const displayedOrigin=collected.origins.element.innerType().extend({display}).superRefine((v,c)=>{try{if(!collected.origins.element.safeParse(v).success)c.addIssue({code:'custom',message:'Origem inválida.'});}catch{c.addIssue({code:'custom',message:'Valor de origem inválido.'});}});
export const cashForecastSourcesSchema=z.discriminatedUnion('kind',[
 z.object({...page,kind:z.literal('origins'),rows:z.array(displayedOrigin).max(30)}),z.object({...page,kind:z.literal('movements'),rows:z.array(collected.recorded_after_cutoff.element.extend({display})).max(30)}),z.object({...page,kind:z.literal('credits'),rows:z.array(collected.credits.element.extend({display})).max(30)}),z.object({...page,kind:z.literal('issues'),rows:z.array(z.object({scope:z.enum(['confirmed','expanded','all']).optional(),code:z.string(),source_ids:z.array(uuid),display})).max(30)})]);
export const cashForecastCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,cutoff:day,period_end:day,source_revision:revision,title:z.string().refine(v=>v.trim().length>=2&&v.trim().length<=120),reason:z.string().refine(v=>v.trim().length>=5&&v.trim().length<=2000)}).strict().refine(v=>v.cutoff<v.period_end);
export const cashForecastResultSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,request_id:uuid,snapshot_id:uuid,source_revision:revision,content_hash:revision,confirmed:z.literal(true),cash_changed:z.literal(false)});
export type CashForecastSummary=z.infer<typeof cashForecastSummarySchema>;
export type CashForecastPreview=z.infer<typeof cashForecastPreviewSchema>;
export type CashForecastCommand=z.infer<typeof cashForecastCommandSchema>;
export type CashForecastSources=z.infer<typeof cashForecastSourcesSchema>;
export function parseCashForecastResult(value:unknown,command:CashForecastCommand,actor:string){const v=cashForecastResultSchema.parse(value);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.source_revision!==command.source_revision)throw new Error('Resposta fora da previsão preservada.');return v;}
