import {z} from 'zod';
import {cashForecastCollectorSchema} from './cashForecastCollectorContract';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const cashForecastAgendaOriginSchema=cashForecastCollectorSchema.innerType().shape.origins.element;
export const cashForecastAgendaPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,cutoff:day,period_end:day,revision,origin:cashForecastAgendaOriginSchema,eligible:z.boolean(),can_execute:z.boolean()}).superRefine((v,c)=>{const fail=()=>c.addIssue({code:'custom',message:'Agenda sem comprovação suficiente.'});if(v.cutoff>=v.period_end||v.can_execute&&!v.eligible)fail();if(v.eligible){const o=v.origin;if(!o.valid||o.nominal_cents===null||o.fulfilled_cents===null||o.reserved_credit_cents===null)fail();else if([o.nominal_cents,o.fulfilled_cents,o.reserved_credit_cents].every(n=>/^\d+$/.test(n))&&BigInt(o.nominal_cents)<=BigInt(o.fulfilled_cents)+BigInt(o.reserved_credit_cents))fail();}});
export const cashForecastAgendaCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,economic_key:z.string().min(1),action:z.enum(['set','clear']),expected_on:day.nullable(),reason:z.string().refine(v=>v.trim().length>=5&&v.trim().length<=2000),expected_revision:revision,cutoff:day,period_end:day}).strict().refine(v=>(v.action==='set')===(v.expected_on!==null)&&v.cutoff<v.period_end);
export const cashForecastAgendaResultSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,event_id:uuid,request_id:uuid,economic_key:z.string().min(1),action:z.enum(['set','clear']),expected_on:day.nullable()}).strict().refine(v=>(v.action==='set')===(v.expected_on!==null));
export type CashForecastAgendaCommand=z.infer<typeof cashForecastAgendaCommandSchema>;
export type CashForecastAgendaPreview=z.infer<typeof cashForecastAgendaPreviewSchema>;
export type CashForecastAgendaOrigin=z.infer<typeof cashForecastAgendaOriginSchema>;
export function parseCashForecastAgendaResult(value:unknown,command:CashForecastAgendaCommand,actor:string){const v=cashForecastAgendaResultSchema.parse(value);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.economic_key!==command.economic_key||v.action!==command.action||v.expected_on!==command.expected_on)throw new Error('Resposta fora da revisão de data preservada.');return v;}
