import {z} from 'zod';
const id=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^-?[0-9]+$/),nonnegative=z.string().regex(/^[0-9]+$/),day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const component=z.object({account_id:id,account_kind:z.enum(['bank','cash','unsupported']),source_table:z.enum(['finance_account_period_closures','finance_account_openings']).nullable(),source_id:id.nullable(),source_revision:revision,amount_cents:cents.nullable(),confirmation:z.enum(['bank_confirmed','cash_count','provisional','unverified'])});
const agenda=z.object({event_id:id,revision,stale:z.boolean(),history:z.array(z.object({id,ordinal:z.number().int().positive(),previous_id:id.nullable(),action:z.enum(['set','clear']),expected_on:day.nullable(),source_revision:revision,original_expected_on:day.nullable(),original_expected_date_source:z.enum(['due_date','unknown']),actor_id:id,actor_name:z.string(),reason:z.string(),created_at:z.string().datetime({offset:true})})).min(1)});
const origin=z.object({economic_key:z.string().min(1),source_table:z.enum(['receivables','payables','fiscal_documents','delivery_attempts']),source_id:id,source_revision:revision,direction:z.enum(['in','out']),scenario:z.enum(['confirmed','unbilled']),nominal_cents:nonnegative.nullable(),fulfilled_cents:nonnegative.nullable(),reserved_credit_cents:nonnegative.nullable(),expected_on:day.nullable(),expected_date_source:z.enum(['due_date','reviewed_date','unknown']),original_expected_on:day.nullable().optional(),original_expected_date_source:z.enum(['due_date','unknown']).optional(),agenda:agenda.optional(),valid:z.boolean()}).superRefine((v,c)=>{if(v.valid?(v.nominal_cents===null||v.fulfilled_cents===null||v.reserved_credit_cents===null):(v.nominal_cents!==null||v.fulfilled_cents!==null||v.reserved_credit_cents!==null))c.addIssue({code:'custom',message:'Origin validity and values disagree'});if(v.valid&&BigInt(v.fulfilled_cents!)+BigInt(v.reserved_credit_cents!)>BigInt(v.nominal_cents!))c.addIssue({code:'custom',message:'Origin exceeds nominal'});if(v.agenda){const h=v.agenda.history,last=h[h.length-1];if(new Set(h.map(e=>e.id)).size!==h.length||(v.original_expected_on===null)!==(v.original_expected_date_source==='unknown')||(last.action==='clear'?(v.agenda.stale||v.expected_on!==v.original_expected_on||v.expected_date_source!==v.original_expected_date_source):v.agenda.stale?(v.expected_on!==null||v.expected_date_source!=='unknown'):(v.expected_on!==last.expected_on||v.expected_date_source!=='reviewed_date')))c.addIssue({code:'custom',message:'Agenda metadata mismatch'});if(v.original_expected_on===undefined||v.original_expected_date_source===undefined||last.id!==v.agenda.event_id||h.some((e,n)=>e.ordinal!==n+1||e.previous_id!==(n?h[n-1].id:null)||(e.action==='set')!==(e.expected_on!==null)))c.addIssue({code:'custom',message:'Invalid agenda history'});}else if(v.expected_date_source==='reviewed_date'||v.original_expected_on!==undefined||v.original_expected_date_source!==undefined)c.addIssue({code:'custom',message:'Missing agenda evidence'});if((v.expected_on===null)!==(v.expected_date_source==='unknown'))c.addIssue({code:'custom',message:'Expected date evidence missing'});});
/** Current company-wide evidence collection. It is not a persisted forecast or historical as-of reconstruction. */
export const cashForecastCollectorSchema=z.object({version:z.literal(1),tenant_id:id,actor_id:id,captured_at:z.string().datetime({offset:true}),revision,basis:z.literal('current_company_cash_forecast'),cutoff:day,period_end:day,account_scope:z.object({mode:z.literal('whole_company'),account_ids:z.array(id)}),base:z.object({as_of:day,amount_cents:cents.nullable(),confirmation:z.enum(['bank_confirmed','cash_count','mixed_confirmed','provisional','unverified']),components:z.array(component)}),origins:z.array(origin),recorded_after_cutoff:z.array(z.object({movement_id:id,account_id:id,source_revision:revision,occurred_on:day,direction:z.enum(['in','out']),amount_cents:nonnegative,confirmation:z.literal('recorded')})),unassigned_credit_cents:nonnegative.nullable(),credits:z.array(z.object({credit_id:id,payer_id:id,source_payment_id:id,source_revision:revision,amount_cents:nonnegative.nullable(),valid:z.boolean()})),source_issues:z.array(z.object({scope:z.enum(['confirmed','expanded','all']),code:z.string().min(1),source_ids:z.array(id)})),counts:z.object({accounts:z.number().int().nonnegative(),origins:z.number().int().nonnegative(),movements:z.number().int().nonnegative(),credits:z.number().int().nonnegative()})}).superRefine((v,c)=>{
 const fail=(message:string)=>c.addIssue({code:'custom',message});
 if(v.counts.accounts!==v.account_scope.account_ids.length||v.counts.origins!==v.origins.length||v.counts.movements!==v.recorded_after_cutoff.length||v.counts.credits!==v.credits.length)fail('Counts must cover complete collection');
 for(const ids of [v.account_scope.account_ids,v.base.components.map(x=>x.account_id),v.origins.map(x=>x.economic_key),v.recorded_after_cutoff.map(x=>x.movement_id),v.credits.map(x=>x.credit_id)])if(new Set(ids).size!==ids.length)fail('Duplicate source identity');
 if(v.base.as_of!==v.cutoff||v.base.components.length!==v.account_scope.account_ids.length||v.base.components.some(x=>!v.account_scope.account_ids.includes(x.account_id)))fail('Base account scope mismatch');
 for(const b of v.base.components){if(b.confirmation==='unverified'?(b.amount_cents!==null):(b.amount_cents===null||b.source_id===null||b.source_table===null||b.account_kind==='unsupported'))fail('Base component lacks proof');}
 const invalid=v.base.components.length===0||v.base.components.some(x=>x.amount_cents===null);
 if(invalid?(v.base.amount_cents!==null||v.base.confirmation!=='unverified'):(v.base.amount_cents===null||v.base.components.reduce((n,x)=>n+BigInt(x.amount_cents!),0n)!==BigInt(v.base.amount_cents)))fail('Base sum or validity mismatch');
 for(const credit of v.credits)if(credit.valid===(credit.amount_cents===null))fail('Credit validity mismatch');
 if(v.credits.some(x=>!x.valid)?v.unassigned_credit_cents!==null:(v.unassigned_credit_cents===null||BigInt(v.unassigned_credit_cents)!==v.credits.reduce((n,x)=>n+BigInt(x.amount_cents!),0n)))fail('Credit sum mismatch');
});
export type CashForecastCollector=z.infer<typeof cashForecastCollectorSchema>;
