import {supabase} from '@/integrations/supabase/client';
import {cashPeriodCountsSchema,cashPeriodPreviewSchema,cashPeriodPendingSchema,cashPeriodCountResultSchema,cashPeriodCountReverseResultSchema,cashPeriodCloseResultSchema,type CashPeriodPending} from './cashPeriodContract';
import {submitAccountPeriodDecision} from './accountPeriodCloseClient';
import {totalCashCounts} from './cashOpeningContract';
type Rpc=(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:{message:string;code?:string}|null}>;
export class CashPeriodRejectedError extends Error {}
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await(supabase.rpc as unknown as Rpc)(name,args);if(error){if(['22023','23514','23505','40001','42501','55000'].includes(error.code||''))throw new CashPeriodRejectedError(error.message);throw new Error(error.message);}return data;}
export async function readCashPeriodCounts(tenant:string,account:string,end:string,page=1){const data=cashPeriodCountsSchema.parse(await rpc('get_finance_cash_period_counts',{_tenant_id:tenant,_account_id:account,_period_end:end,_page:page}));if(data.tenant_id!==tenant||data.account_id!==account||data.period_end!==end||data.page!==page)throw new Error('Contagens fora da conta ou período selecionado.');return data;}
export async function readCashPeriodPreview(tenant:string,account:string,from:string,to:string,count:string){const data=cashPeriodPreviewSchema.parse(await rpc('preview_finance_cash_period_close',{_tenant_id:tenant,_account_id:account,_from:from,_to:to,_count_id:count}));if(data.tenant_id!==tenant||data.account_id!==account||data.from!==from||data.to!==to||(data.count&&data.count.id!==count))throw new Error('Conferência fora da conta, período ou contagem.');return data;}
export async function submitCashPeriodDecision(pending:CashPeriodPending){cashPeriodPendingSchema.parse(pending);if(pending.kind==='reopen')return submitAccountPeriodDecision(pending);const name=pending.kind==='record_count'?'record_finance_cash_period_count':pending.kind==='reverse_count'?'reverse_finance_cash_period_count':'close_finance_cash_period',raw=await rpc(name,{_payload:pending.command});
 if(pending.kind==='close'){const result=cashPeriodCloseResultSchema.parse(raw);if(result.tenant_id!==pending.command.tenant_id||result.request_id!==pending.command.request_id||result.account_id!==pending.command.account_id||result.from!==pending.command.from||result.to!==pending.command.to||result.revision!==pending.command.revision)throw new Error('Resposta fora do fechamento conferido.');return result;}
 const result=pending.kind==='record_count'?cashPeriodCountResultSchema.parse(raw):cashPeriodCountReverseResultSchema.parse(raw);if(result.tenant_id!==pending.command.tenant_id||result.request_id!==pending.command.request_id||(pending.kind==='record_count'&&(result.account_id!==pending.command.account_id||result.period_end!==pending.command.period_end||result.counted_cents!==totalCashCounts(pending.command.counts)))||(pending.kind==='reverse_count'&&result.count_id!==pending.command.count_id))throw new Error('Resposta fora da contagem conferida.');return result;
}
