import {supabase} from '@/integrations/supabase/client';
import {cashForecastPreviewSchema,cashForecastSnapshotSchema,cashForecastHistorySchema,cashForecastSourcesSchema,cashForecastCommandSchema,type CashForecastCommand,type CashForecastSources} from './cashForecastViewContract';
type Rpc=(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:unknown}>;const rpc=supabase.rpc as unknown as Rpc;
export class CashForecastChangedError extends Error{constructor(){super('As fontes mudaram. Atualize a conferência e comece pela primeira página.');}}
async function read(name:string,args:Record<string,unknown>){const {data,error}=await rpc(name,args);if(error){if(typeof error==='object'&&'code' in error&&error.code==='40001')throw new CashForecastChangedError();throw error;}return data;}
function scope(v:{tenant_id:string;actor_id:string},tenant:string,actor:string){if(v.tenant_id!==tenant||v.actor_id!==actor)throw new Error('Consulta fora da empresa ou sessão solicitada.');}
export async function readCashForecastPreview(tenant:string,actor:string,cutoff:string,end:string){const v=cashForecastPreviewSchema.parse(await read('preview_finance_cash_forecast',{_tenant_id:tenant,_cutoff:cutoff,_period_end:end,_expected_revision:null}));scope(v,tenant,actor);if(v.cutoff!==cutoff||v.period_end!==end)throw new Error('Período de previsão incompatível.');return v;}
export async function readCashForecastSnapshot(tenant:string,actor:string,id:string){const v=cashForecastSnapshotSchema.parse(await read('get_finance_cash_forecast_snapshot',{_tenant_id:tenant,_snapshot_id:id}));if(v.tenant_id!==tenant||v.viewer_actor_id!==actor||v.snapshot_id!==id)throw new Error('Captura fora da consulta solicitada.');return v;}
export async function readCashForecastHistory(tenant:string,actor:string,page:number,revision:string|null){const v=cashForecastHistorySchema.parse(await read('get_finance_cash_forecast_history',{_tenant_id:tenant,_page:page,_expected_revision:revision}));scope(v,tenant,actor);if(v.page!==page||revision!==null&&v.revision!==revision)throw new Error('Página de histórico incompatível.');return v;}
export async function readCashForecastSources(tenant:string,actor:string,cutoff:string,end:string,snapshot:string|null,kind:CashForecastSources['kind'],page:number,revision:string){const v=cashForecastSourcesSchema.parse(await read('get_finance_cash_forecast_sources',{_tenant_id:tenant,_cutoff:cutoff,_period_end:end,_snapshot_id:snapshot,_kind:kind,_page:page,_expected_revision:revision}));scope(v,tenant,actor);if(v.page!==page||v.snapshot_id!==snapshot||v.kind!==kind||v.revision!==revision)throw new Error('Página de fontes incompatível.');return v;}
export const sendCashForecast=(command:CashForecastCommand)=>rpc('record_finance_cash_forecast',{_payload:cashForecastCommandSchema.parse(command)});
