import {z} from 'zod';
import {expenseCostDispositionSchema} from './expenseCostFundingContract';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^(0|[1-9]\d*)$/),positive=z.string().regex(/^[1-9]\d{0,13}$/),signed=z.string().regex(/^-?\d+$/);
export const costDispositionReturnEffectsSchema=z.object({amount_cents:positive,open_before_cents:cents.nullable(),open_after_cents:signed.nullable(),cash_changed:z.literal(false),original_reservation_changed:z.literal(false),incoming_capacity_consumed_cents:positive}).strict();
export const costDispositionReturnCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,disposition_id:uuid,incoming_movement_id:uuid,amount_cents:positive,revision,reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000)}).strict();
const identity={version:z.literal(1),tenant_id:uuid,actor_id:uuid,expense_id:uuid,charge_id:uuid,payable_id:uuid.nullable(),regularization_id:uuid,disposition_id:uuid};
export const costDispositionReturnPreviewSchema=z.object({...identity,revision,disposition:expenseCostDispositionSchema.nullable(),incoming:z.object({movement_id:uuid,bank_account_id:uuid,occurred_on:z.string(),amount_cents:positive,used_cents:signed,available_cents:signed,recorded_counterparty:z.string().nullable()}).strict(),blockers:z.array(z.object({code:z.string(),source_table:z.string().nullable(),source_ids:z.array(uuid)}).strict()),eligible:z.boolean(),can_record:z.boolean(),can_execute:z.boolean(),effects:costDispositionReturnEffectsSchema}).strict().superRefine((v,ctx)=>{
 if([v.effects.amount_cents,v.effects.incoming_capacity_consumed_cents,v.effects.open_before_cents,v.effects.open_after_cents,v.incoming.amount_cents,v.incoming.used_cents,v.incoming.available_cents].some(n=>n!==null&&!/^-?\d+$/.test(n)))return;
 const invalid=(message:string)=>ctx.addIssue({code:z.ZodIssueCode.custom,message});
 if(v.effects.amount_cents!==v.effects.incoming_capacity_consumed_cents)invalid('Capacidade diferente do retorno.');
 if(v.effects.open_before_cents!==null&&v.effects.open_after_cents!==null&&BigInt(v.effects.open_before_cents)-BigInt(v.effects.amount_cents)!==BigInt(v.effects.open_after_cents))invalid('Saldo posterior incompatível.');
 if(BigInt(v.incoming.amount_cents)-BigInt(v.incoming.used_cents)!==BigInt(v.incoming.available_cents))invalid('Capacidade da entrada incompatível.');
 if(v.disposition&&v.disposition.id!==v.disposition_id)invalid('Disposição diferente da consulta.');
 if(v.can_execute&&(!v.eligible||!v.can_record))invalid('Execução sem elegibilidade.');
 if(v.eligible&&(!v.disposition||v.blockers.length||v.effects.open_before_cents===null||v.effects.open_after_cents===null||BigInt(v.effects.open_after_cents)<0n||BigInt(v.incoming.available_cents)<BigInt(v.effects.amount_cents)||v.disposition.open_cents!==v.effects.open_before_cents))invalid('Prévia elegível sem cobertura comprovada.');
});
export const costDispositionReturnResultSchema=z.object({...identity,request_id:uuid,return_id:uuid,incoming_movement_id:uuid,confirmed:z.literal(true),effects:costDispositionReturnEffectsSchema}).strict();
export type CostDispositionReturnCommand=z.infer<typeof costDispositionReturnCommandSchema>;
export type CostDispositionReturnPreview=z.infer<typeof costDispositionReturnPreviewSchema>;
export type CostDispositionReturnResult=z.infer<typeof costDispositionReturnResultSchema>;
export type CostDispositionReturnExpected=Pick<CostDispositionReturnPreview,'expense_id'|'charge_id'|'payable_id'|'regularization_id'|'effects'>;
export function parseCostDispositionReturnResult(value:unknown,command:CostDispositionReturnCommand,actor:string,expected:CostDispositionReturnExpected){const v=costDispositionReturnResultSchema.parse(value);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.disposition_id!==command.disposition_id||v.incoming_movement_id!==command.incoming_movement_id||v.effects.amount_cents!==command.amount_cents||v.expense_id!==expected.expense_id||v.charge_id!==expected.charge_id||v.payable_id!==expected.payable_id||v.regularization_id!==expected.regularization_id||Object.keys(expected.effects).some(k=>v.effects[k as keyof typeof v.effects]!==expected.effects[k as keyof typeof expected.effects]))throw new Error('Resposta diferente do pedido de devolução preservado.');return v;}
export const costReturnMovementOptionsSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,disposition_id:uuid,query:z.string(),page:z.number().int().positive(),page_size:z.literal(30),total:z.number().int().nonnegative(),revision,rows:z.array(z.object({id:uuid,bank_account_id:uuid,bank_account_name:z.string().nullable(),occurred_on:z.string(),label:z.string(),amount_cents:positive,used_cents:signed,available_cents:signed}).strict()).max(30)}).strict();
