import {supabase} from '@/integrations/supabase/client';
import {customerCreditCommandSchema,customerCreditOptionsSchema,customerCreditPreviewSchema,customerCreditQuerySchema,type CustomerCreditCommand,type CustomerCreditQuery} from './customerCreditContract';
type Rpc=(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:unknown}>;const rpc=supabase.rpc.bind(supabase) as unknown as Rpc;
export class CustomerCreditChangedError extends Error{}
export async function readCustomerCreditOptions(tenant:string,actor:string,query:CustomerCreditQuery){const q=customerCreditQuerySchema.parse(query),{data,error}=await rpc('get_finance_customer_credit_options',{_tenant_id:tenant,_query:q});if(error){if(typeof error==='object'&&'code' in error&&error.code==='40001')throw new CustomerCreditChangedError('A consulta mudou. Recomece na primeira página.');throw error;}const v=customerCreditOptionsSchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.kind!==q.kind||v.credit_id!==q.credit_id||v.search!==q.search||v.offset!==q.offset||v.limit!==q.limit||v.available_only!==q.available_only||(q.kind==='credits'&&v.payer_id!==q.payer_id)||q.expected_revision&&q.expected_revision!==v.revision)throw Error('Consulta de crédito incompatível com o filtro e sessão.');return v;}
export async function readCustomerCreditPreview(tenant:string,actor:string,credit:string,receivable:string,amount:string,application:string|null){const {data,error}=await rpc('preview_finance_customer_credit_application',{_tenant_id:tenant,_credit_id:credit,_receivable_id:receivable,_amount_cents:amount,_application_id:application});if(error)throw error;const v=customerCreditPreviewSchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.credit_id!==credit||v.receivable_id!==receivable||v.amount_cents!==amount||v.application_id!==application)throw Error('Prévia de crédito fora da sessão ou proposta.');return v;}
export const sendCustomerCredit=(command:CustomerCreditCommand)=>rpc('record_finance_customer_credit_application',{_payload:customerCreditCommandSchema.parse(command)});
const labels:Record<string,string>={credit_source_unverified:'A origem do crédito precisa de conferência.',credit_payer_mismatch:'O título e o crédito pertencem a pagadores diferentes.',credit_target_unverified:'A liquidação do título precisa de conferência.',credit_target_not_collectible:'Este título não pode receber uma aplicação de crédito.',credit_capacity_exceeded:'O valor supera o crédito disponível.',credit_target_capacity_exceeded:'O valor supera o saldo em aberto do título.',credit_release_capacity_exceeded:'O valor supera a aplicação ainda vinculada.',credit_target_cancelled:'O título foi cancelado; confira a liberação automática no histórico.',finance_credit_application_changed:'O crédito ou o título mudou. Confira uma nova prévia antes de confirmar.',finance_credit_application_busy:'Outra operação utiliza esta origem. Atualize a consulta.',finance_credit_application_unavailable:'A aplicação ou liberação não está disponível nesta situação.'};
export const customerCreditIssue=(code:string)=>labels[code]??`A origem exige conferência (${code}).`;
export function customerCreditError(error:unknown){const message=error instanceof Error?error.message:typeof error==='object'&&error!==null&&'message' in error?String(error.message):'';const code=Object.keys(labels).find(k=>message.includes(k));return code?labels[code]:message.includes('PGRST202')||message.includes('Could not find')?'A operação de crédito ainda está indisponível neste ambiente.':error instanceof Error?error.message:'Não foi possível confirmar a resposta. Preserve e recupere o pedido, se exibido.';}
