import {z} from 'zod';
import {customerCreditPositionSchema} from './customerCreditContract';
const id=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^(0|[1-9]\d*)$/),positive=z.string().regex(/^[1-9]\d{0,13}$/),signed=z.string().regex(/^-?\d+$/),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),doc=z.string().regex(/^(\d{11}|\d{14})$/).nullable();
const integer=(v:unknown):v is string=>typeof v==='string'&&/^-?\d+$/.test(v);
const invalid=(ctx:z.RefinementCtx)=>ctx.addIssue({code:'custom',message:'Identidade ou saldo da devolução inconsistente.'});
export const customerCreditRefundEffectsSchema=z.object({amount_cents:positive,credit_before_cents:cents.nullable(),credit_after_cents:cents.nullable(),movement_available_before_cents:signed,movement_available_after_cents:cents.nullable()}).strict();
export const customerCreditRefundPreviewSchema=z.object({version:z.literal(1),tenant_id:id,actor_id:id,credit_id:id,payer_id:id,payer:z.object({id,name:z.string().nullable(),document:doc}).strict(),identity:z.object({verified:z.boolean()}).strict(),outgoing_movement_id:id,amount_cents:positive,credit:customerCreditPositionSchema,outgoing:z.object({movement_id:id,bank_account_id:id,occurred_on:date.nullable(),amount_cents:positive,used_cents:signed,available_cents:signed,beneficiary_name:z.string().nullable(),beneficiary_document:doc}).strict(),effects:customerCreditRefundEffectsSchema,eligible:z.boolean(),can_execute:z.boolean(),blockers:z.array(z.string()),revision}).strict().superRefine((v,ctx)=>{
 const e=v.effects,o=v.outgoing,c=v.credit;
 if(c.tenant_id!==v.tenant_id||c.credit_id!==v.credit_id||c.payer_id!==v.payer_id||v.payer.id!==v.payer_id||o.movement_id!==v.outgoing_movement_id||e.amount_cents!==v.amount_cents||e.credit_before_cents!==c.available_cents||e.movement_available_before_cents!==o.available_cents||v.can_execute&&!v.eligible)invalid(ctx);
 if([o.amount_cents,o.used_cents,o.available_cents].every(integer)&&BigInt(o.amount_cents)-BigInt(o.used_cents)!==BigInt(o.available_cents))invalid(ctx);
 if(v.identity.verified&&(!v.payer.document||v.payer.document!==o.beneficiary_document))invalid(ctx);
 if(v.eligible){if(!c.valid||o.occurred_on===null||!v.identity.verified||v.blockers.length||![e.amount_cents,e.credit_before_cents,e.credit_after_cents,e.movement_available_before_cents,e.movement_available_after_cents,c.applied_cents,c.returned_cents,c.original_cents].every(integer))return invalid(ctx);
 if(BigInt(e.credit_before_cents!)-BigInt(e.amount_cents)!==BigInt(e.credit_after_cents!)||BigInt(e.movement_available_before_cents)-BigInt(e.amount_cents)!==BigInt(e.movement_available_after_cents!)||BigInt(c.original_cents)!==BigInt(c.applied_cents!)+BigInt(c.returned_cents!)+BigInt(c.available_cents!))invalid(ctx);
 }else if(e.credit_after_cents!==null||e.movement_available_after_cents!==null)invalid(ctx);
});
export type CustomerCreditRefundPreview=z.infer<typeof customerCreditRefundPreviewSchema>;
export const customerCreditRefundCommandSchema=z.object({version:z.literal(1),tenant_id:id,request_id:id,credit_id:id,outgoing_movement_id:id,amount_cents:positive,expected_revision:revision,reason:z.string().refine(v=>v.trim().length>=5&&v.trim().length<=2000)}).strict();
export type CustomerCreditRefundCommand=z.infer<typeof customerCreditRefundCommandSchema>;
export const customerCreditRefundResultSchema=z.object({version:z.literal(1),tenant_id:id,actor_id:id,request_id:id,refund_id:id,credit_id:id,payer_id:id,outgoing_movement_id:id,amount_cents:positive,cash_movement_created:z.literal(false),effects:customerCreditRefundEffectsSchema}).strict();
export const customerCreditRefundExpectedSchema=z.object({payer_id:id,effects:customerCreditRefundEffectsSchema}).strict().refine(v=>v.effects.credit_before_cents!==null&&v.effects.credit_after_cents!==null&&v.effects.movement_available_after_cents!==null);
export type CustomerCreditRefundExpected=z.infer<typeof customerCreditRefundExpectedSchema>;
export function parseCustomerCreditRefundResult(raw:unknown,c:CustomerCreditRefundCommand,actor:string,expected:CustomerCreditRefundExpected){const v=customerCreditRefundResultSchema.parse(raw);if(v.tenant_id!==c.tenant_id||v.actor_id!==actor||v.request_id!==c.request_id||v.credit_id!==c.credit_id||v.outgoing_movement_id!==c.outgoing_movement_id||v.amount_cents!==c.amount_cents||v.payer_id!==expected.payer_id||Object.keys(expected.effects).some(k=>v.effects[k as keyof typeof v.effects]!==expected.effects[k as keyof typeof expected.effects]))throw Error('Resposta diferente da devolução preservada.');return v;}
const envelope={version:z.literal(1),tenant_id:id,actor_id:id,credit_id:id,payer_id:id,search:z.string(),offset:z.number().int().nonnegative(),limit:z.number().int().positive().max(100),total:z.number().int().nonnegative(),next_offset:z.number().int().nonnegative().nullable(),revision,can_execute:z.literal(false)};
export const customerCreditRefundQuerySchema=z.object({kind:z.enum(['movements','history']),search:z.string().max(200),offset:z.number().int().nonnegative(),limit:z.number().int().min(1).max(100),expected_revision:revision.nullable()}).strict();
export type CustomerCreditRefundQuery=z.infer<typeof customerCreditRefundQuerySchema>;
export const customerCreditRefundOptionsSchema=z.discriminatedUnion('kind',[z.object({...envelope,kind:z.literal('movements'),rows:z.array(z.object({movement_id:id,bank_account_id:id,bank_account_name:z.string().nullable(),occurred_on:date,amount_cents:positive,used_cents:cents,available_cents:positive,beneficiary_name:z.string().nullable(),beneficiary_document:doc,revision}).strict())}).strict(),z.object({...envelope,kind:z.literal('history'),rows:z.array(z.object({refund_id:id,credit_id:id,payer_id:id,outgoing_movement_id:id,amount_cents:positive,actor_id:id.nullable(),actor_name:z.string().nullable(),reason:z.string(),created_at:z.string(),occurred_on:date,bank_account_id:id}).strict())}).strict()]).superRefine((v,ctx)=>{if(v.rows.length>v.limit||v.offset+v.rows.length>v.total||v.next_offset!==(v.offset+v.rows.length<v.total?v.offset+v.rows.length:null))invalid(ctx);if(v.kind==='history'&&v.rows.some(r=>r.credit_id!==v.credit_id||r.payer_id!==v.payer_id))invalid(ctx);});
export type CustomerCreditRefundOptions=z.infer<typeof customerCreditRefundOptionsSchema>;
