import {z} from 'zod';
const id=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^(0|[1-9]\d{0,13})$/),positive=z.string().regex(/^[1-9]\d{0,13}$/);
const safe=(v:unknown):v is string=>typeof v==='string'&&/^(0|[1-9]\d{0,13})$/.test(v);
const issue=(ctx:z.RefinementCtx)=>ctx.addIssue({code:'custom',message:'Valores ou identidades do crédito inconsistentes.'});
export const customerCreditPositionSchema=z.object({version:z.literal(1),tenant_id:id,credit_id:id,payer_id:id,valid:z.boolean(),original_cents:cents,applied_cents:cents.nullable(),released_cents:cents,returned_cents:cents.nullable().optional(),available_cents:cents.nullable(),binding_revision:revision,source_revision:revision,revision}).strict();
const target=z.object({receivable_id:id,payer_id:id.nullable(),reference:z.string(),status:z.string(),nominal_cents:cents.nullable(),cash_received_cents:cents.nullable(),credit_applied_cents:cents.nullable(),settled_cents:cents.nullable(),open_cents:cents.nullable(),revision}).strict();
export const customerCreditPreviewSchema=z.object({version:z.literal(1),tenant_id:id,actor_id:id,action:z.enum(['apply','release']),application_id:id.nullable(),credit_id:id,receivable_id:id,amount_cents:positive,credit:customerCreditPositionSchema,target,release_available_cents:cents.nullable(),eligible:z.boolean(),can_execute:z.boolean(),blockers:z.array(z.string()),revision}).strict().superRefine((v,ctx)=>{
 if(v.credit.tenant_id!==v.tenant_id||v.credit.credit_id!==v.credit_id||v.target.receivable_id!==v.receivable_id||(v.action==='apply')!==(v.application_id===null)||v.can_execute&&!v.eligible)issue(ctx);
 const c=v.credit,t=v.target;
 if(c.valid&&(!safe(c.applied_cents)||!safe(c.available_cents)||!safe(c.original_cents)||(c.returned_cents!==undefined&&!safe(c.returned_cents))||BigInt(c.applied_cents)+BigInt(c.available_cents)+(c.returned_cents===undefined?0n:safe(c.returned_cents)?BigInt(c.returned_cents):0n)!==BigInt(c.original_cents)))issue(ctx);
 if([t.cash_received_cents,t.credit_applied_cents,t.settled_cents].every(safe)&&BigInt(t.cash_received_cents!)+BigInt(t.credit_applied_cents!)!==BigInt(t.settled_cents!))issue(ctx);
 if(v.eligible){if(!c.valid||v.blockers.length||c.payer_id!==t.payer_id||!safe(v.amount_cents)||![t.nominal_cents,t.cash_received_cents,t.credit_applied_cents,t.settled_cents,t.open_cents].every(safe))return issue(ctx);
 const capacity=v.action==='apply'?c.available_cents:v.release_available_cents;
 if(!safe(capacity)||BigInt(v.amount_cents)>BigInt(capacity)||v.action==='apply'&&BigInt(v.amount_cents)>BigInt(t.open_cents!))issue(ctx);}
});
export type CustomerCreditPreview=z.infer<typeof customerCreditPreviewSchema>;
export const customerCreditCommandSchema=z.object({version:z.literal(1),tenant_id:id,request_id:id,credit_id:id,receivable_id:id,application_id:id.nullable(),action:z.enum(['apply','release']),amount_cents:positive,expected_revision:revision,reason:z.string().refine(v=>v.trim().length>=5&&v.trim().length<=2000)}).strict().refine(v=>(v.action==='apply')===(v.application_id===null));
export type CustomerCreditCommand=z.infer<typeof customerCreditCommandSchema>;
export const customerCreditResultSchema=z.object({version:z.literal(1),tenant_id:id,actor_id:id,request_id:id,event_id:id,application_id:id,action:z.enum(['apply','release']),credit_id:id,receivable_id:id,amount_cents:positive,cash_movement_created:z.literal(false)}).strict();
export type CustomerCreditResult=z.infer<typeof customerCreditResultSchema>;
export function parseCustomerCreditResult(data:unknown,command:CustomerCreditCommand,actor:string){const v=customerCreditResultSchema.parse(data);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.credit_id!==command.credit_id||v.receivable_id!==command.receivable_id||v.action!==command.action||v.amount_cents!==command.amount_cents||(command.action==='release'?v.application_id!==command.application_id:v.application_id!==v.event_id))throw Error('Resposta fora do pedido de crédito preservado.');return v;}
export const customerCreditRowSchema=z.object({credit_id:id,payer_id:id,payer_name:z.string().nullable(),original_cents:cents,applied_cents:cents.nullable(),released_cents:cents,returned_cents:cents.nullable().optional(),available_cents:cents.nullable(),valid:z.boolean(),revision,source_payment_id:id,created_at:z.string()}).strict();
export const customerCreditTargetSchema=target.extend({payer_id:id,nominal_cents:cents,cash_received_cents:cents,credit_applied_cents:cents,settled_cents:cents,open_cents:cents});
export const customerCreditHistorySchema=z.object({id,application_id:id,credit_id:id,receivable_id:id,reference:z.string(),action:z.enum(['apply','release']),amount_cents:cents,remaining_cents:cents.nullable(),actor_id:id.nullable(),actor_name:z.string(),reason:z.string(),observation_id:id.nullable(),created_at:z.string(),can_release:z.boolean()}).strict();
export const customerCreditQuerySchema=z.object({kind:z.enum(['credits','targets','history']),credit_id:id.nullable(),payer_id:id.nullable(),search:z.string().max(200),available_only:z.boolean(),offset:z.number().int().nonnegative(),limit:z.number().int().min(1).max(100),expected_revision:revision.nullable()}).strict();
export type CustomerCreditQuery=z.infer<typeof customerCreditQuerySchema>;
const envelope={version:z.literal(1),tenant_id:id,actor_id:id,credit_id:id.nullable(),payer_id:id.nullable(),search:z.string(),available_only:z.boolean(),offset:z.number().int().nonnegative(),limit:z.number().int().positive().max(100),total:z.number().int().nonnegative(),next_offset:z.number().int().nonnegative().nullable(),revision,can_execute:z.literal(false)};
export const customerCreditOptionsSchema=z.discriminatedUnion('kind',[z.object({...envelope,kind:z.literal('credits'),rows:z.array(customerCreditRowSchema)}).strict(),z.object({...envelope,kind:z.literal('targets'),rows:z.array(customerCreditTargetSchema)}).strict(),z.object({...envelope,kind:z.literal('history'),rows:z.array(customerCreditHistorySchema)}).strict()]).superRefine((v,ctx)=>{if(v.rows.length>v.limit||v.offset+v.rows.length>v.total||v.next_offset!==((v.offset+v.rows.length<v.total)?v.offset+v.rows.length:null)||(v.kind!=='credits'&&(!v.credit_id||!v.payer_id)))issue(ctx);if(v.kind==='targets'&&v.rows.some(r=>r.payer_id!==v.payer_id))issue(ctx);if(v.kind==='history'&&v.rows.some(r=>r.credit_id!==v.credit_id))issue(ctx);});
export type CustomerCreditOptions=z.infer<typeof customerCreditOptionsSchema>;
