import {supabase} from '@/integrations/supabase/client';
import {customerCreditRefundCommandSchema,customerCreditRefundPreviewSchema,customerCreditRefundOptionsSchema,customerCreditRefundQuerySchema,type CustomerCreditRefundCommand,type CustomerCreditRefundQuery} from './customerCreditRefundContract';
type Rpc=(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:unknown}>;const rpc=supabase.rpc.bind(supabase) as unknown as Rpc;
export class CustomerCreditRefundChangedError extends Error{}
export async function readCustomerCreditRefundOptions(tenant:string,actor:string,credit:string,query:CustomerCreditRefundQuery){const q=customerCreditRefundQuerySchema.parse(query),{data,error}=await rpc('get_finance_customer_credit_refund_options',{_tenant_id:tenant,_credit_id:credit,_query:q});if(error){if(typeof error==='object'&&'code' in error&&error.code==='40001')throw new CustomerCreditRefundChangedError('A consulta mudou. Reinicie a primeira página.');throw error;}const v=customerCreditRefundOptionsSchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.credit_id!==credit||v.kind!==q.kind||v.search!==q.search||v.offset!==q.offset||v.limit!==q.limit||q.expected_revision&&v.revision!==q.expected_revision)throw Error('Consulta fora do crédito e sessão solicitados.');return v;}
export async function readCustomerCreditRefundPreview(tenant:string,actor:string,credit:string,movement:string,amount:string){const {data,error}=await rpc('preview_finance_customer_credit_refund',{_tenant_id:tenant,_credit_id:credit,_outgoing_movement_id:movement,_amount_cents:amount});if(error)throw error;const v=customerCreditRefundPreviewSchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.credit_id!==credit||v.outgoing_movement_id!==movement||v.amount_cents!==amount)throw Error('Prévia fora da proposta de devolução.');return v;}
export const sendCustomerCreditRefund=(command:CustomerCreditRefundCommand)=>rpc('record_finance_customer_credit_refund',{_payload:customerCreditRefundCommandSchema.parse(command)});
const labels:Record<string,string>={credit_refund_payer_unproven:'O documento do destinatário não comprova o pagador do crédito.',credit_source_unverified:'A origem do crédito precisa de conferência.',credit_refund_movement_unproven:'A saída não tem prova válida para esta devolução.',credit_refund_movement_capacity_exceeded:'A saída não possui capacidade disponível para este valor.',credit_refund_capacity_exceeded:'O valor supera o crédito disponível.',credit_refund_period_closed:'A saída pertence a um período fechado.',credit_refund_period_unverified:'O período da saída precisa de conferência.',finance_credit_refund_changed:'O crédito ou a saída mudou. Consulte uma nova prévia.',finance_credit_refund_busy:'Outra operação utiliza esta origem. Atualize a consulta.'};
export const customerCreditRefundIssue=(code:string)=>labels[code]??`A devolução exige conferência (${code}).`;
export function customerCreditRefundError(error:unknown){const message=error instanceof Error?error.message:typeof error==='object'&&error!==null&&'message' in error?String(error.message):'';const key=Object.keys(labels).find(k=>message.includes(k));return key?labels[key]:error instanceof Error?error.message:'Não foi possível confirmar a resposta. Preserve e recupere o pedido exibido.';}
