import {z} from 'zod';
import {driverAdvanceReturnCommandSchema,driverAdvanceReturnResultSchema,parseDriverAdvanceReturnResult} from './driverAdvanceReturnContract';
const uuid=z.string().uuid(),cents=z.string().regex(/^\d+$/);
const inputSchema=driverAdvanceReturnCommandSchema.omit({version:true,tenant_id:true,request_id:true}).extend({expected_open_cents:cents});
export type DriverAdvanceReturnInput=z.infer<typeof inputSchema>;
const pendingSchema=z.object({version:z.literal(1),tenantId:uuid,actorId:uuid,expectedOpenCents:cents,payload:driverAdvanceReturnCommandSchema}).strict();
export type PendingDriverAdvanceReturn=z.infer<typeof pendingSchema>;
type Store=Pick<Storage,'getItem'|'setItem'|'removeItem'>;type Command=z.infer<typeof driverAdvanceReturnCommandSchema>;type Result=z.infer<typeof driverAdvanceReturnResultSchema>;
export const driverAdvanceReturnKey=(tenant:string,actor:string)=>`agvlog:driver-advance-return:v1:${tenant}:${actor}`;
const unavailable=()=>Error('O pedido de devolução salvo está indisponível ou incompatível. Preserve os dados antes de iniciar outro.');
export function pendingDriverAdvanceReturn(storage:Store,tenant:string,actor:string):PendingDriverAdvanceReturn|null{try{uuid.parse(tenant);uuid.parse(actor);const raw=storage.getItem(driverAdvanceReturnKey(tenant,actor));if(raw===null)return null;if(raw.length>30000)throw unavailable();const original=JSON.parse(raw),row=pendingSchema.parse(original);if(row.tenantId!==tenant||row.actorId!==actor||row.payload.tenant_id!==tenant)throw unavailable();return original;}catch{throw unavailable();}}
const fallbackLocks=new Map<string,Promise<void>>();
export async function lockDriverAdvanceReturn<T>(key:string,work:()=>Promise<T>):Promise<T>{if(typeof navigator!=='undefined'&&navigator.locks)return navigator.locks.request(key,work);const prior=fallbackLocks.get(key)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});const tail=prior.catch(()=>{}).then(()=>gate);fallbackLocks.set(key,tail);await prior.catch(()=>{});try{return await work();}finally{release();if(fallbackLocks.get(key)===tail)fallbackLocks.delete(key);}}
interface Dependencies{storage:Store;uuid:()=>string;assertContext:(tenant:string,actor:string)=>void;changed:()=>void;lock:<T>(key:string,work:()=>Promise<T>)=>Promise<T>;send:(payload:Command)=>Promise<{data:unknown;error:unknown}>}
const definitive=(error:unknown)=>{const code=typeof error==='object'&&error!==null&&'code' in error?String(error.code):'';return /^(22|23)/.test(code)||['40001','40P01','55P03','42501','55000'].includes(code);};
export function createDriverAdvanceReturnOutbox(deps:Dependencies){let flight:{identity:string;promise:Promise<Result>}|null=null;const notify=()=>{try{deps.changed();}catch{/* Notification failure cannot change the persisted command. */}};
 function run(tenant:string,actor:string,input?:DriverAdvanceReturnInput){let parsed:DriverAdvanceReturnInput|undefined;try{uuid.parse(tenant);uuid.parse(actor);parsed=input===undefined?undefined:inputSchema.parse(input);}catch(error){return Promise.reject(error);}const identity=JSON.stringify([tenant,actor,parsed??null]);if(flight)return flight.identity===identity?flight.promise:Promise.reject(Error('Outra devolução está em andamento. Aguarde ou recupere o pedido original.'));
  const key=driverAdvanceReturnKey(tenant,actor),promise=Promise.resolve().then(()=>deps.lock(key,async()=>{deps.assertContext(tenant,actor);const observed=deps.storage.getItem(key),found=pendingDriverAdvanceReturn(deps.storage,tenant,actor);if(deps.storage.getItem(key)!==observed)throw unavailable();let row=found;const uncertain=!!found;if(row&&parsed)throw Error('Há uma devolução sem confirmação. Recupere o pedido existente.');if(!row){if(!parsed)throw Error('Não há devolução pendente nesta sessão.');const {expected_open_cents,...command}=parsed;row={version:1,tenantId:tenant,actorId:actor,expectedOpenCents:expected_open_cents,payload:driverAdvanceReturnCommandSchema.parse({version:1,tenant_id:tenant,request_id:deps.uuid(),...command})};}const raw=found?observed:JSON.stringify(row);if(raw===null)throw unavailable();if(!found){if(deps.storage.getItem(key)!==null)throw unavailable();deps.storage.setItem(key,raw);notify();}if(deps.storage.getItem(key)!==raw)throw unavailable();const forget=()=>{try{if(deps.storage.getItem(key)===raw)deps.storage.removeItem(key);}finally{notify();}};
   try{deps.assertContext(tenant,actor);const {data,error}=await deps.send(row.payload);deps.assertContext(tenant,actor);if(error)throw error;const result=parseDriverAdvanceReturnResult(data,row.payload,actor,row.expectedOpenCents);try{forget();}catch{/* A confirmed result remains confirmed; the stored replay is harmless. */}return result;}catch(error){if(!uncertain&&definitive(error))try{forget();}catch{/* Preserve the command if cleanup itself fails. */}throw error;}}));flight={identity,promise};void promise.finally(()=>{if(flight?.promise===promise)flight=null;notify();}).catch(()=>{/* The caller receives the original promise rejection. */});return promise;}
 return{submit:(tenant:string,actor:string,input:DriverAdvanceReturnInput)=>run(tenant,actor,input),recover:(tenant:string,actor:string)=>run(tenant,actor)};
}
