import {z} from 'zod';
import {employeeAdvancePaymentPreviewSchema} from './employeeAdvancePaymentContract';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),action=z.enum(['approve','cancel']),status=z.enum(['approved','cancelled']);
export const employeeAdvanceActionCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,advance_id:uuid,action,expected_revision:revision,reason:z.string().trim().min(10).max(2000)}).strict();
export type EmployeeAdvanceActionCommand=z.infer<typeof employeeAdvanceActionCommandSchema>;
export const employeeAdvanceActionExpectedSchema=z.object({cash_changed:z.literal(false),status_after:status}).strict();
export const employeeAdvanceActionPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,advance_id:uuid,action,revision,eligible:z.boolean(),can_manage:z.boolean(),can_execute:z.boolean(),blockers:z.array(z.string()),advance:employeeAdvancePaymentPreviewSchema.innerType().shape.advance,effects:employeeAdvanceActionExpectedSchema}).superRefine((v,ctx)=>{if(v.advance.tenant_id!==v.tenant_id||v.advance.advance_id!==v.advance_id||v.effects.status_after!==(v.action==='approve'?'approved':'cancelled')||v.can_execute&&(!v.eligible||!v.can_manage||!v.advance.verified||v.blockers.length||v.advance.paid_cents!=='0'))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Conferência de situação do adiantamento inconsistente.'});});
export type EmployeeAdvanceActionPreview=z.infer<typeof employeeAdvanceActionPreviewSchema>;
export const employeeAdvanceActionResultSchema=z.object({version:z.literal(1),confirmed:z.literal(true),tenant_id:uuid,actor_id:uuid,request_id:uuid,advance_id:uuid,action,status,cash_changed:z.literal(false)}).refine(v=>v.status===(v.action==='approve'?'approved':'cancelled'));
export function parseEmployeeAdvanceActionResult(data:unknown,command:EmployeeAdvanceActionCommand,actor:string,expected:z.infer<typeof employeeAdvanceActionExpectedSchema>){const v=employeeAdvanceActionResultSchema.parse(data);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.advance_id!==command.advance_id||v.action!==command.action||v.status!==expected.status_after)throw Error('Resposta incompatível com o pedido de adiantamento preservado.');return v;}
