import {z} from 'zod';
const uuid=z.string().uuid(),cents=z.string().regex(/^(0|[1-9][0-9]{0,13})$/),positive=z.string().regex(/^[1-9][0-9]{0,13}$/),revision=z.string().regex(/^[a-f0-9]{32}$/),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const employeeAdvancePaymentCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,advance_id:uuid,movement_id:uuid,amount_cents:positive,expected_revision:revision,method:z.enum(['pix','boleto','ted','doc','dinheiro','cartao','debito_automatico','other']),reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000,'Informe um motivo entre 10 e 2.000 caracteres.')}).strict();
export type EmployeeAdvancePaymentCommand=z.infer<typeof employeeAdvancePaymentCommandSchema>;
export const employeeAdvancePositionSchema=z.object({version:z.literal(1),tenant_id:uuid,advance_id:uuid,employee_id:uuid,employee_name:z.string(),employee_document:z.string().nullable(),driver_id:uuid.nullable(),status:z.string(),payable_id:uuid.nullable(),payable_status:z.string().nullable(),verified:z.boolean(),issues:z.array(z.string()),revision,amount_cents:cents.nullable(),paid_cents:cents.nullable(),open_cents:cents.nullable(),payment_count:z.number().int().nonnegative()}).superRefine((v,ctx)=>{const values=[v.amount_cents,v.paid_cents,v.open_cents];if(values.some(x=>x!==null&&!/^(0|[1-9][0-9]{0,13})$/.test(x)))return;if(values.some(x=>v.verified?x===null:x!==null)||(v.verified&&BigInt(v.amount_cents!)!==BigInt(v.paid_cents!)+BigInt(v.open_cents!)))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Composição do adiantamento incompatível.'});});
export const employeeAdvancePaymentPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,advance_id:uuid,movement_id:uuid.nullable(),amount_cents:positive.nullable(),revision,eligible:z.boolean(),can_pay:z.boolean(),can_execute:z.boolean(),blockers:z.array(z.string()),advance:employeeAdvancePositionSchema,movement:z.object({id:uuid,bank_account_id:uuid,occurred_on:date,beneficiary_name:z.string(),beneficiary_document:z.string().nullable(),amount_cents:positive,available_cents:cents.nullable(),identity_verified:z.boolean()}).nullable(),effects:z.object({cash_created:z.literal(false),expense_created:z.literal(false),create_payable:z.boolean(),approve_payable:z.boolean(),paid_before_cents:cents.nullable(),paid_after_cents:cents.nullable(),open_after_cents:cents.nullable()})}).superRefine((v,ctx)=>{const issue=()=>ctx.addIssue({code:z.ZodIssueCode.custom,message:'Prévia de adiantamento incompatível.'});if(v.advance.tenant_id!==v.tenant_id||v.advance.advance_id!==v.advance_id||v.movement&&v.movement.id!==v.movement_id)issue();if(v.can_execute&&(!v.eligible||!v.can_pay||!v.advance.verified||!v.movement?.identity_verified||v.movement.available_cents===null||v.blockers.length||!v.amount_cents||v.advance.open_cents===null)){issue();return;}if(v.can_execute){const e=v.effects,a=v.advance;if([v.amount_cents,a.open_cents,e.paid_before_cents,e.paid_after_cents,e.open_after_cents,v.movement?.available_cents].some(x=>x!=null&&!/^(0|[1-9][0-9]{0,13})$/.test(x)))return;if([e.paid_before_cents,e.paid_after_cents,e.open_after_cents].some(x=>x===null))issue();else if(e.paid_before_cents!==a.paid_cents||BigInt(e.paid_after_cents!)!==BigInt(e.paid_before_cents!)+BigInt(v.amount_cents!)||BigInt(e.open_after_cents!)+BigInt(v.amount_cents!)!==BigInt(a.open_cents!)||BigInt(v.amount_cents!)>BigInt(v.movement!.available_cents!))issue();}});
export type EmployeeAdvancePaymentPreview=z.infer<typeof employeeAdvancePaymentPreviewSchema>;
export const employeeAdvancePaymentResultSchema=z.object({version:z.literal(1),confirmed:z.literal(true),tenant_id:uuid,actor_id:uuid,request_id:uuid,advance_id:uuid,payable_id:uuid,payment_id:uuid,link_id:uuid,movement_id:uuid,amount_cents:positive,status:z.enum(['approved','paid']),paid_cents:positive,open_cents:cents,cash_created:z.literal(false),expense_created:z.literal(false)}).superRefine((v,ctx)=>{if(!/^[1-9][0-9]{0,13}$/.test(v.paid_cents)||!/^[1-9][0-9]{0,13}$/.test(v.amount_cents))return;if((v.status==='paid')!==(v.open_cents==='0')||BigInt(v.paid_cents)<BigInt(v.amount_cents))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Resultado do adiantamento incompatível.'});});

export const employeeAdvancePaymentExpectedSchema=z.object({paid_cents:positive,open_cents:cents}).strict();
export function parseEmployeeAdvancePaymentResult(data:unknown,command:EmployeeAdvancePaymentCommand,actor:string,expected:z.infer<typeof employeeAdvancePaymentExpectedSchema>){const v=employeeAdvancePaymentResultSchema.parse(data);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.advance_id!==command.advance_id||v.movement_id!==command.movement_id||v.amount_cents!==command.amount_cents||v.paid_cents!==expected.paid_cents||v.open_cents!==expected.open_cents)throw Error('Resposta incompatível com o pagamento de adiantamento preservado.');return v;}

const page={version:z.literal(1),tenant_id:uuid,actor_id:uuid,advance_id:uuid,offset:z.number().int().nonnegative(),limit:z.number().int().min(1).max(100),total:z.number().int().nonnegative(),next_offset:z.number().int().nonnegative().nullable(),revision};
export const employeeAdvancePaymentOptionsSchema=z.object({...page,rows:z.array(z.object({id:uuid,bank_account_id:uuid,account_name:z.string().nullable(),occurred_on:date,beneficiary_name:z.string(),beneficiary_document:z.string().nullable(),description:z.string(),amount_cents:positive,available_cents:positive,identity_verified:z.literal(true)}))});
export const employeeAdvancePaymentHistorySchema=z.object({...page,rows:z.array(z.object({request_id:uuid,actor_id:uuid,created_at:z.string().datetime({offset:true}),reason:z.string(),actor_name:z.string().nullable(),result:employeeAdvancePaymentResultSchema}))}).superRefine((v,ctx)=>{for(const row of v.rows)if(row.result.tenant_id!==v.tenant_id||row.result.advance_id!==v.advance_id||row.result.actor_id!==row.actor_id||row.result.request_id!==row.request_id)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Histórico de outro adiantamento ou autor.'});});
