import {z} from 'zod';
const uuid=z.string().uuid(), cents=z.string().regex(/^\d+$/), revision=z.string().regex(/^[a-f0-9]{32}$/);
export const expenseCancellationEventSchema=z.object({id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).passthrough();
export const expenseCancellationPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,expense_id:uuid,revision,eligible:z.boolean(),issue:z.string().nullable(),can_execute:z.boolean(),snapshot:z.object({expense:z.object({id:uuid,tenant_id:uuid,batch_id:uuid,description:z.string(),category:z.string(),occurred_on:z.string()}).passthrough(),payable:z.object({id:uuid}).passthrough().nullable()}).passthrough(),cancellation:expenseCancellationEventSchema.nullable(),effects:z.object({cost_removed_cents:cents.nullable(),obligation_cancelled_cents:cents.nullable(),cash_changed:z.literal(false)})}).superRefine((v,c)=>{if(v.snapshot.expense.id!==v.expense_id||v.snapshot.expense.tenant_id!==v.tenant_id)c.addIssue({code:'custom',message:'Gasto fora do contexto.'});if(v.eligible&&(v.issue!==null||v.cancellation||!v.snapshot.payable||v.effects.cost_removed_cents===null||v.effects.obligation_cancelled_cents===null))c.addIssue({code:'custom',message:'Efeitos incompletos para cancelamento.'});});
export const expenseCancellationCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,expense_id:uuid,revision,reason:z.string().trim().min(10).max(2000)}).strict();
export type ExpenseCancellationCommand=z.infer<typeof expenseCancellationCommandSchema>;
export const expenseCancellationResultSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,expense_id:uuid,cancellation_id:uuid,payable_id:uuid.nullable(),amount_cents:cents,confirmed:z.literal(true),cash_changed:z.literal(false)});
export const expenseCancellationLabels:Record<string,string>={finance_expense_not_found:'O gasto não está disponível nesta empresa.',finance_expense_already_cancelled:'Este gasto já foi cancelado. O original permanece no histórico.',finance_expense_unloading_requires_resolution:'A descarga possui reembolso relacionado e precisa de resolução específica.',finance_expense_money_dependency:'Há pagamentos ou vínculos com dinheiro neste gasto. O cancelamento simples está impedido, inclusive para vínculos históricos.',finance_expense_payable_inconsistent:'O título precisa estar aberto e corresponder integralmente ao gasto e ao favorecido. Revise o título.',finance_expense_source_association_dependency:'Há associações históricas com outras origens ou estoque. Este cancelamento não desfaz essas relações.',finance_expense_protected_composition:'O gasto participa de folha ou acerto protegido. Revise essas dependências.',finance_expense_obligation_dependency:'Há obrigação financeira relacionada que impede este cancelamento.',finance_expense_closed_period_dependency:'O gasto participa de um período fechado. Revise o fechamento relacionado.',finance_expense_cancellation_changed:'As informações mudaram. Atualize e faça uma nova revisão.'};
expenseCancellationLabels.finance_dependency_busy='Outra operação está alterando uma dependência deste gasto. Atualize e revise novamente.';
