import {z} from 'zod';
const uuid=z.string().uuid(),reason=z.string().trim().min(10).max(2000),cents=z.string().regex(/^\d+$/);
const base={version:z.literal(1),tenant_id:uuid,request_id:uuid};
export const legacyCostAssociateCommandSchema=z.object({...base,expense_id:uuid,cost_id:uuid,revision:z.string().regex(/^[a-f0-9]{32}$/),reason,same_expense_confirmed:z.literal(true)}).strict();
export const legacyCostReverseCommandSchema=z.object({...base,link_id:uuid,reason}).strict();
export const legacyCostPendingSchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('associate'),command:legacyCostAssociateCommandSchema}),z.object({kind:z.literal('reverse'),command:legacyCostReverseCommandSchema})]);
export type LegacyCostPending=z.infer<typeof legacyCostPendingSchema>;
const result={...base,link_id:uuid,expense_id:uuid,cost_id:uuid,amount_cents:cents,confirmed:z.literal(true)};
export const legacyCostAssociateResultSchema=z.object({...result,cash_created:z.literal(false),obligation_created:z.literal(false)});
export const legacyCostReverseResultSchema=z.object({...result,reversal_id:uuid,cash_changed:z.literal(false),obligation_changed:z.literal(false)});
export const legacyCostIssueLabels:Record<string,string>={finance_access_denied:'Seu acesso financeiro não foi confirmado.',finance_request_conflict:'Este pedido já identifica outra decisão. Confira o histórico antes de continuar.'};
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),count=z.number().int().nonnegative();
const link=z.object({id:uuid,cost_id:uuid,amount_cents:cents,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()});
export const legacyCostContextSchema=z.object({version:z.literal(1),tenant_id:uuid,expense_id:uuid,page:z.number().int().positive(),page_size:z.literal(30),total:count,source:z.object({id:uuid,trip_id:uuid.nullable(),driver_id:uuid.nullable(),description:z.string().nullable(),category:z.string(),amount_cents:cents.nullable(),occurred_on:date.nullable(),approval_status:z.string(),payment_source:z.string(),reimbursable:z.boolean(),issue:z.string().nullable()}),active_link:link.nullable(),history:z.object({total:count,rows:z.array(link.extend({reversal:z.object({id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).nullable()})).max(30)}),candidates:z.array(z.object({cost_id:uuid,batch_id:uuid,description:z.string(),category:z.string(),amount_cents:cents,occurred_on:date.nullable(),issue:z.string().nullable(),revision:z.string().regex(/^[a-f0-9]{32}$/)})).max(30)}).superRefine((data,ctx)=>{if(data.source.id!==data.expense_id||new Set(data.candidates.map(row=>row.cost_id)).size!==data.candidates.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Contexto de custo incompatível.'});});
export const legacyCostInventorySchema=z.object({version:z.literal(1),tenant_id:uuid,page:z.number().int().positive(),page_size:z.literal(30),total:count,source_filter:z.enum(["all","driver_expenses","maintenance_orders"]),rows:z.array(z.object({source_table:z.enum(['driver_expenses','maintenance_orders']),source_id:uuid,description:z.string().nullable(),occurred_on:date.nullable(),amount_cents:cents.nullable(),status:z.string(),issue:z.string().nullable(),active_link_id:uuid.nullable()})).max(30),coverage_complete:z.literal(false)});

Object.assign(legacyCostIssueLabels,{
 finance_legacy_expense_not_found:'A despesa antiga não foi encontrada nesta empresa.',finance_legacy_expense_not_approved:'A despesa ainda não está aprovada.',finance_legacy_expense_invalid_value:'O valor ou a data da despesa precisam de revisão.',finance_legacy_expense_reimbursement_requires_review:'A despesa pode representar reembolso ao motorista. Esse vínculo exige revisão específica e não pode ser associado neste fluxo.',finance_legacy_expense_trip_mismatch:'A viagem e o motorista da despesa precisam de identificação compatível.',finance_legacy_cost_already_associated:'Uma das origens já possui associação ativa. Confira o histórico.',finance_legacy_cost_already_reversed:'A associação já foi desfeita. Atualize o histórico.',finance_legacy_cost_changed:'Os dados de uma das origens mudaram. Atualize e faça uma nova revisão.',finance_legacy_cost_link_not_found:'A associação não foi encontrada nesta empresa.',finance_legacy_cost_not_found:'O custo escolhido não foi encontrado.',finance_legacy_cost_obligation_conflict:'Há obrigação ou custeio conflitante. Revise os vínculos existentes sem registrar outro gasto.',finance_legacy_cost_payroll_protected:'A origem participa de folha protegida. Revise o histórico antes de alterar a associação.',finance_legacy_cost_settlement_protected:'A origem participa de acerto protegido. A associação não pode alterar esse histórico.',finance_legacy_cost_source_mismatch:'As duas origens possuem valor, categoria ou data incompatíveis.',finance_legacy_cost_trip_mismatch:'O custo e a despesa não pertencem à mesma viagem e motorista.',maintenance_components_require_review:'A ordem de manutenção exige revisão por componentes. Total da ordem, peças e consumo de estoque não podem ser somados automaticamente.'});
legacyCostIssueLabels.finance_expense_not_found='A despesa não foi encontrada nesta empresa.';
legacyCostIssueLabels.finance_legacy_cost_source_immutable='A despesa já associada permanece protegida contra edição e exclusão, mesmo após reversão. Corrigir o vínculo não autoriza alterar a origem.';
