import {z} from 'zod';
const uuid=z.string().uuid(),cents=z.string().regex(/^\d+$/),reason=z.string().trim().min(10).max(2000);
const base={version:z.literal(1),tenant_id:uuid,request_id:uuid};
export const legacyPayableIssueLabels:Record<string,string>={finance_payment_not_found:'O pagamento não foi encontrado nesta empresa.',finance_legacy_payment_not_found:'O pagamento antigo não foi encontrado nesta empresa.',finance_legacy_payable_not_found:'O título do pagamento não foi encontrado.',finance_legacy_payment_amount_invalid:'O valor do pagamento antigo precisa ser revisado.',finance_legacy_payment_date_invalid:'A data do pagamento antigo precisa ser revisada.',finance_legacy_payment_account_invalid:'A conta do pagamento antigo precisa ser identificada.',finance_legacy_payment_not_eligible:'Este pagamento usa o fluxo de baixa atual; consulte seu histórico de baixa.',finance_legacy_payment_already_associated:'Este pagamento já tem uma associação ativa. Confira o histórico.',finance_legacy_bank_source_mismatch:'O registro bancário antigo diverge do pagamento. Revise sua origem.',finance_legacy_bank_source_ambiguous:'O mesmo registro bancário antigo aparece em mais de um pagamento. A origem precisa ser esclarecida.',finance_legacy_movement_mismatch:'A saída não corresponde à conta, data ou motorista do pagamento.',finance_movement_overallocated:'A saída não tem mais capacidade para o pagamento integral.',finance_payment_already_linked:'O pagamento já possui vínculo ativo.',finance_payment_link_mismatch:'O pagamento e a saída possuem informações incompatíveis.',finance_invalid_payment_movement:'A saída selecionada não é elegível para este pagamento.',finance_legacy_association_not_found:'A associação antiga não foi encontrada.',finance_legacy_association_already_reversed:'A associação já foi desfeita. Confira o histórico.',finance_access_denied:'Seu acesso financeiro não foi confirmado.',finance_request_conflict:'O identificador do pedido já pertence a outra decisão. Confira o histórico antes de continuar.'};
export const legacyPayableAssociateCommandSchema=z.object({...base,payment_id:uuid,movement_id:uuid,revision:z.string().min(1),reason}).strict();
export const legacyPayableReverseCommandSchema=z.object({...base,link_id:uuid,reason}).strict();
export const legacyPayablePendingSchema=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('associate'),command:legacyPayableAssociateCommandSchema}),
 z.object({kind:z.literal('reverse'),command:legacyPayableReverseCommandSchema}),
]);
export type LegacyPayablePending=z.infer<typeof legacyPayablePendingSchema>;
legacyPayableIssueLabels.finance_legacy_payment_changed='Os dados do pagamento ou de sua origem mudaram. Atualize e faça uma nova revisão antes de associar.';
const result={...base,payment_id:uuid,payable_id:uuid,movement_id:uuid,link_id:uuid,origin:z.literal('legacy_adoption'),confirmed:z.literal(true)};
export const legacyPayableAssociateResultSchema=z.object({...result,amount_cents:cents,bank_transaction_id:uuid.nullable(),cash_created:z.literal(false),payment_created:z.literal(false)});
export const legacyPayableReverseResultSchema=z.object({...result,reversal_id:uuid,released_cents:cents,cash_changed:z.literal(false),payment_changed:z.literal(false)});
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const legacyPayableContextSchema=z.object({version:z.literal(1),tenant_id:uuid,payment_id:uuid,revision:z.string().min(1),page:z.number().int().positive(),page_size:z.literal(20),total:z.number().int().nonnegative(),
 rows:z.array(z.object({id:uuid,bank_account_id:uuid,account_name:z.string(),beneficiary_name:z.string(),description:z.string(),occurred_on:date,bank_reference:z.string().nullable(),amount_cents:cents,remaining_cents:cents})),
 payment:z.object({id:uuid,payable_id:uuid,bank_account_id:uuid.nullable(),account_name:z.string().nullable(),supplier_name:z.string().nullable(),paid_on:date.nullable(),amount_cents:cents.nullable(),bank_transaction_id:uuid.nullable(),driver_id:uuid.nullable()}),eligible:z.boolean(),issue:z.string().nullable(),active_link:uuid.nullable(),history_total:z.number().int().nonnegative(),
 history:z.array(z.object({id:uuid,movement_id:uuid,amount_cents:cents,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string(),origin:z.literal('legacy_adoption'),reversal:z.object({id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).nullable()}))
}).superRefine((data,ctx)=>{if(data.payment_id!==data.payment.id)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Pagamento fora do contexto.'});});
