import {z} from 'zod';
const uuid=z.string().uuid(),reason=z.string().trim().min(10).max(2000),cents=z.string().regex(/^\d+$/),revision=z.string().regex(/^[a-f0-9]{32}$/),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(),count=z.number().int().nonnegative();
const base={version:z.literal(1),tenant_id:uuid,request_id:uuid};
export const maintenanceLaborAssociateCommandSchema=z.object({...base,order_id:uuid,cost_id:uuid,revision,reason,same_labor_confirmed:z.literal(true)}).strict();
export const maintenanceLaborReverseCommandSchema=z.object({...base,link_id:uuid,reason}).strict();
export const maintenanceLaborPendingSchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('associate'),command:maintenanceLaborAssociateCommandSchema}),z.object({kind:z.literal('reverse'),command:maintenanceLaborReverseCommandSchema})]);
export type MaintenanceLaborPending=z.infer<typeof maintenanceLaborPendingSchema>;
const result={...base,link_id:uuid,order_id:uuid,cost_id:uuid,amount_cents:cents,confirmed:z.literal(true)};
export const maintenanceLaborAssociateResultSchema=z.object({...result,cash_created:z.literal(false),obligation_created:z.literal(false)});
export const maintenanceLaborReverseResultSchema=z.object({...result,reversal_id:uuid,cash_changed:z.literal(false),obligation_changed:z.literal(false)});
const link=z.object({id:uuid,cost_id:uuid,amount_cents:cents,supplier_id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()});
export const maintenanceLaborContextSchema=z.object({version:z.literal(1),tenant_id:uuid,order_id:uuid,page:z.number().int().positive(),page_size:z.literal(30),search:z.string().max(200),total:count,source:z.object({id:uuid,order_number:z.string(),status:z.string(),labor_cents:cents.nullable(),supplier_name:z.string().nullable(),opened_on:date}),active_link:link.nullable(),history:z.object({total:count,rows:z.array(link.extend({reversal:z.object({id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).nullable()})).max(30)}),candidates:z.array(z.object({cost_id:uuid,batch_id:uuid,description:z.string(),category:z.string(),amount_cents:cents,occurred_on:date,supplier_id:uuid.nullable(),supplier_name:z.string().nullable(),issue:z.string().nullable(),revision})).max(30)}).superRefine((data,ctx)=>{if(data.source.id!==data.order_id||new Set(data.candidates.map(row=>row.cost_id)).size!==data.candidates.length||data.candidates.length>data.total||data.history.rows.length>data.history.total)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Contexto de mão de obra incompatível.'});});
export const maintenanceLaborIssueLabels:Record<string,string>={finance_access_denied:'Seu acesso financeiro não foi confirmado.',finance_request_conflict:'O pedido identifica outra decisão. Confira o histórico.',finance_legacy_cost_changed:'Os dados da OS ou do custo mudaram. Atualize e faça uma nova revisão.'};
Object.assign(maintenanceLaborIssueLabels,{finance_maintenance_order_not_found:'A OS não foi encontrada nesta empresa.',finance_maintenance_labor_order_not_completed:'A OS precisa estar concluída antes de associar sua mão de obra.',finance_maintenance_labor_invalid_value:'O valor ou a data da mão de obra precisam de revisão.',finance_maintenance_labor_supplier_required:'Escolha um custo com fornecedor cadastrado válido. O nome escrito na OS não basta.',finance_maintenance_labor_source_mismatch:'O valor do custo não corresponde à mão de obra declarada.',finance_maintenance_labor_target_context:'O custo não pertence ao contexto elegível de manutenção ou serviço.',finance_maintenance_labor_obligation_conflict:'Há obrigação ou vínculo conflitante. Revise o custo existente sem criar outra cobrança.',finance_maintenance_labor_cost_not_found:'O custo não foi encontrado nesta empresa.',finance_maintenance_labor_already_associated:'A OS ou o custo já possui associação ativa. Confira o histórico.',finance_maintenance_labor_already_reversed:'A associação já foi desfeita. Atualize o histórico.',finance_maintenance_labor_changed:'Os dados da OS, custo ou fornecedor mudaram. Atualize e revise novamente.',finance_maintenance_labor_concurrent_change:'Outra operação alterou a origem. Atualize antes de confirmar.',finance_maintenance_labor_link_not_found:'A associação não foi encontrada nesta empresa.',finance_maintenance_labor_source_protected:'Desfaça a associação ativa antes de corrigir os valores financeiros da OS. A associação original e sua reversão permanecem no histórico.'});

maintenanceLaborIssueLabels.finance_maintenance_labor_target_obligation_invalid='O título vinculado ao custo está cancelado ou diverge do fornecedor ou valor. Revise essa obrigação antes de associar.';
