import {z} from 'zod';
const uuid=z.string().uuid(),reason=z.string().trim().min(10).max(2000),cents=z.string().regex(/^\d+$/),revision=z.string().regex(/^[a-f0-9]{32}$/),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(),count=z.number().int().nonnegative();
const base={version:z.literal(1),tenant_id:uuid,request_id:uuid};
export const maintenanceDirectPartAssociateCommandSchema=z.object({...base,part_id:uuid,cost_id:uuid,revision,reason,classification:z.literal("direct_purchase"),quantity:z.string().regex(/^[0-9]+(\.[0-9]+)?$/).refine(value=>/[1-9]/.test(value)),document_number:z.string().min(1).max(200),same_part_confirmed:z.literal(true)}).strict();
export const maintenanceDirectPartReverseCommandSchema=z.object({...base,link_id:uuid,reason}).strict();
export const maintenanceDirectPartPendingSchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('associate'),command:maintenanceDirectPartAssociateCommandSchema}),z.object({kind:z.literal('reverse'),command:maintenanceDirectPartReverseCommandSchema})]);
export type MaintenanceDirectPartPending=z.infer<typeof maintenanceDirectPartPendingSchema>;
const result={...base,link_id:uuid,order_id:uuid,part_id:uuid,cost_id:uuid,amount_cents:cents,confirmed:z.literal(true)};
export const maintenanceDirectPartAssociateResultSchema=z.object({...result,cash_created:z.literal(false),obligation_created:z.literal(false)});
export const maintenanceDirectPartReverseResultSchema=z.object({...result,reversal_id:uuid,cash_changed:z.literal(false),obligation_changed:z.literal(false)});
const link=z.object({id:uuid,cost_id:uuid,amount_cents:cents,supplier_id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()});
export const maintenanceDirectPartContextSchema=z.object({version:z.literal(1),tenant_id:uuid,part_id:uuid,order_id:uuid,page:z.number().int().positive(),page_size:z.literal(30),search:z.string().max(200),total:count,source:z.object({id:uuid,order_id:uuid,order_number:z.string().nullable(),order_status:z.string().nullable(),description:z.string(),quantity:z.string().regex(/^\d+(\.\d+)?$/).nullable(),unit_cost_cents:cents.nullable(),total_cost_cents:cents.nullable(),stock_item_id:uuid.nullable(),stock_movement_id:uuid.nullable()}),active_link:link.nullable(),history:z.object({total:count,rows:z.array(link.extend({reversal:z.object({id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).nullable()})).max(30)}),candidates:z.array(z.object({cost_id:uuid,batch_id:uuid,description:z.string(),category:z.string(),amount_cents:cents,occurred_on:date,supplier_id:uuid.nullable(),supplier_name:z.string().nullable(),document_number:z.string().nullable(),issue:z.string().nullable(),revision})).max(30)}).superRefine((data,ctx)=>{if(data.source.id!==data.part_id||data.source.order_id!==data.order_id||new Set(data.candidates.map(row=>row.cost_id)).size!==data.candidates.length||data.candidates.length>data.total||data.history.rows.length>data.history.total)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Contexto da peça incompatível.'});});

export const maintenanceDirectPartIssueLabels:Record<string,string>={finance_access_denied:'Seu acesso financeiro não foi confirmado.',finance_request_conflict:'O pedido identifica outra decisão. Confira o histórico.'};


Object.assign(maintenanceDirectPartIssueLabels,{finance_maintenance_part_not_found:'A peça não foi encontrada nesta empresa.',finance_maintenance_direct_part_order_not_completed:'A OS da peça precisa estar concluída.',finance_maintenance_part_stock_consumption:'A peça possui movimento de estoque. Consumo não pode ser classificado como compra direta.',finance_maintenance_part_catalog_invalid:'O item de catálogo não foi localizado nesta empresa.',finance_maintenance_part_stock_requires_review:'Há movimentos de estoque relacionados à mesma peça e OS. Esclareça a origem antes de associar.',finance_maintenance_direct_part_invalid_value:'Quantidade, valor unitário e total da peça precisam ser válidos e coerentes.',finance_maintenance_direct_part_cost_not_found:'O custo escolhido não foi encontrado.',finance_maintenance_direct_part_target_context:'Escolha um custo do contexto de manutenção elegível.',finance_maintenance_direct_part_supplier_required:'O custo precisa de fornecedor cadastrado válido.',finance_maintenance_direct_part_document_required:'O custo precisa do documento que identifica a compra.',finance_maintenance_direct_part_source_mismatch:'O valor do custo não corresponde ao total da peça ou sua data precisa de revisão.',finance_maintenance_cost_already_associated:'A peça ou o custo já possui associação ativa. Confira o histórico.',finance_maintenance_direct_part_target_obligation_invalid:'O título do custo está cancelado ou diverge do fornecedor ou valor.',finance_maintenance_direct_part_obligation_conflict:'Há obrigação conflitante. Revise os vínculos sem registrar outra compra.',finance_maintenance_direct_part_link_not_found:'A associação não foi encontrada nesta empresa.',finance_maintenance_direct_part_already_reversed:'A associação já foi desfeita.',finance_maintenance_direct_part_changed:'A peça, o custo ou seu fornecedor mudaram. Atualize e revise novamente.',finance_maintenance_direct_part_declaration_mismatch:'A quantidade ou o documento informado diverge da origem. Confira ambos antes de confirmar.',finance_maintenance_direct_part_source_protected:'Desfaça a associação ativa antes de corrigir os dados financeiros da peça. O histórico permanece preservado.',finance_maintenance_cost_concurrent_change:'Outra operação alterou o contexto. Atualize a consulta.'});
