import {z} from 'zod';
const uuid=z.string().uuid(),cents=z.string().regex(/^\d+$/),revision=z.string().regex(/^[a-f0-9]{32}$/);
export const manualExpenseCancellationEventSchema=z.object({id:uuid,tenant_id:uuid,payable_id:uuid,original_request_id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).passthrough();
export const manualExpenseCancellationPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,payable_id:uuid,original_request_id:uuid.nullable(),revision,eligible:z.boolean(),issue:z.string().nullable(),can_execute:z.boolean(),snapshot:z.object({payable:z.object({id:uuid,tenant_id:uuid,description:z.string().nullable(),supplier_name:z.string().nullable(),category:z.string().nullable()}).passthrough().nullable(),command:z.object({tenant_id:uuid,request_id:uuid,action:z.literal('record_manual_expense'),payload:z.record(z.unknown()),result:z.record(z.unknown())}).passthrough().nullable(),evidence:z.array(z.record(z.unknown()))}).passthrough(),cancellation:manualExpenseCancellationEventSchema.nullable(),effects:z.object({cost_removed_cents:cents.nullable(),obligation_cancelled_cents:cents.nullable(),cash_changed:z.literal(false)})}).superRefine((v,c)=>{const fail=()=>c.addIssue({code:'custom',message:'Identidade ou efeitos da despesa avulsa inconsistentes.'});if(v.snapshot.payable&&(v.snapshot.payable.id!==v.payable_id||v.snapshot.payable.tenant_id!==v.tenant_id))fail();if(v.snapshot.command&&(v.snapshot.command.tenant_id!==v.tenant_id||v.snapshot.command.request_id!==v.original_request_id||v.snapshot.command.result.payable_id!==v.payable_id))fail();if(v.cancellation&&(v.cancellation.tenant_id!==v.tenant_id||v.cancellation.payable_id!==v.payable_id||v.cancellation.original_request_id!==v.original_request_id))fail();if(v.eligible&&(v.issue!==null||v.cancellation||!v.snapshot.payable||!v.snapshot.command||!v.original_request_id||v.effects.cost_removed_cents===null||v.effects.obligation_cancelled_cents===null))fail();});
export const manualExpenseCancellationCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,payable_id:uuid,revision,reason:z.string().trim().min(10).max(2000)}).strict();
export type ManualExpenseCancellationCommand=z.infer<typeof manualExpenseCancellationCommandSchema>;
export const manualExpenseCancellationResultSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,payable_id:uuid,original_request_id:uuid,cancellation_id:uuid,amount_cents:cents,confirmed:z.literal(true),cash_changed:z.literal(false)});
export const manualExpenseCancellationLabels:Record<string,string>={finance_manual_expense_not_found:'Não foi localizado um registro original de despesa avulsa para este título.',finance_manual_expense_already_cancelled:'Esta despesa avulsa já foi cancelada. O original permanece no histórico.',finance_manual_expense_source_inconsistent:'O título não corresponde integralmente ao registro original aberto da despesa. Confira valor, favorecido, datas, situação e origem.',finance_manual_expense_unloading_requires_resolution:'A descarga exige resolução específica do reembolso.',finance_manual_expense_money_dependency:'Há pagamento ou vínculo com dinheiro nesta despesa. O cancelamento simples é impedido, inclusive para relações históricas.',finance_manual_expense_materialization_dependency:'Esta despesa possui relação com adiantamento, folha, acerto ou outra obrigação. O cancelamento não desfaz essas relações.',finance_manual_expense_closed_period_dependency:'A despesa participa de um período fechado. Revise o fechamento relacionado.',finance_manual_expense_cancellation_changed:'A despesa mudou. Atualize os dados e faça uma nova revisão.'};
manualExpenseCancellationLabels.finance_dependency_busy='Outra operação está alterando uma dependência desta despesa. Atualize e revise novamente.';
