import {z} from 'zod';
const uuid=z.string().uuid(),signed=z.string().regex(/^-?\d{1,14}$/);
export const movementVoidCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,movement_id:uuid,revision:z.string().regex(/^[0-9a-f]{32}$/),reason:z.string().trim().min(10).max(2000)}).strict();
export type MovementVoidCommand=z.infer<typeof movementVoidCommandSchema>;
export const movementVoidResultSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,movement_id:uuid,original_request_id:uuid,correction_id:uuid,kind:z.literal('void'),confirmed:z.literal(true),bank_money_transacted:z.literal(false),recorded_balance_changed:z.literal(true),actor_id:uuid,actor_name:z.string().min(1),reason:z.string().min(10),created_at:z.string().datetime({offset:true}),effects:z.object({computation:z.literal('prospective_invalidation'),bank_money_transacted:z.literal(false),recorded_balance_changed:z.literal(true),account_id:uuid,occurred_on:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),inflow_delta_cents:signed,outflow_delta_cents:signed,balance_delta_cents:signed})}).superRefine((v,c)=>{
 const e=v.effects;if(![e.inflow_delta_cents,e.outflow_delta_cents,e.balance_delta_cents].every(x=>signed.safeParse(x).success))return;
 const incoming=BigInt(e.inflow_delta_cents),outgoing=BigInt(e.outflow_delta_cents);
 if(incoming-outgoing!==BigInt(e.balance_delta_cents)||!((incoming<0n&&outgoing===0n)||(outgoing<0n&&incoming===0n)))c.addIssue({code:'custom',message:'Efeitos da invalidação inconsistentes.'});
});
export type MovementVoidResult=z.infer<typeof movementVoidResultSchema>;
const labels:Record<string,string>={finance_movement_correction_changed:'O movimento ou seus vínculos mudaram. Atualize a conferência antes de confirmar.',finance_movement_correction_blocked:'O movimento possui impedimentos. Confira os vínculos e períodos relacionados.',finance_movement_correction_busy:'Outra operação está alterando estes registros. Atualize a conferência.',finance_movement_correction_runtime_not_ready:'As proteções da correção precisam ser verificadas antes de confirmar.',finance_movement_not_found:'O movimento não foi encontrado nesta empresa.',finance_access_denied:'Seu acesso financeiro não permite esta operação.',finance_request_conflict:'Este pedido já foi utilizado com outros dados. Confira o histórico antes de prosseguir.',finance_invalid_payload:'Os dados da confirmação são inválidos. Revise o motivo e a conferência.'};
export function movementVoidErrorLabel(error:unknown){const message=error instanceof Error?error.message:typeof error==='string'?error:'';return labels[message]||'Não foi possível confirmar o resultado. Preserve o pedido e consulte novamente antes de iniciar outra correção.';}
