import {z} from 'zod';
import {unloadingOpenComplementPreviewSchema} from './unloadingOpenComplementContract';
import {costFundingSourceSchema} from './expenseCostFundingContract';
const uuid=z.string().uuid(),positive=z.string().regex(/^[1-9]\d{0,13}$/),cents=z.string().regex(/^(0|[1-9]\d*)$/),signed=z.string().regex(/^-?\d+$/),revision=z.string().regex(/^[a-f0-9]{32}$/);
export const openComplementExtinctionProposalSchema=z.object({amount_cents:positive,dispositions:z.array(z.object({source_kind:z.literal('expense_allocation'),source_id:uuid,applied_cents:cents,responsible_id:uuid,disposition_type:z.literal('driver_custody')}).strict()).max(500)}).strict().refine(v=>new Set(v.dispositions.map(d=>d.source_id)).size===v.dispositions.length,'Fonte repetida.');
export const openComplementExtinctionEffectsSchema=z.object({cost_before_cents:positive.nullable(),cost_after_cents:positive,complement_before_cents:positive.nullable(),complement_after_cents:z.literal('0'),historical_payable_nominal_cents:positive.nullable(),residual_cents:signed,capacity_released_cents:z.literal('0'),cash_changed:z.literal(false),approval_reset:z.boolean()}).strict();
export const openComplementExtinctionExpectedSchema=openComplementExtinctionEffectsSchema.extend({cost_before_cents:positive,complement_before_cents:positive,historical_payable_nominal_cents:positive,residual_cents:cents});
export const openComplementExtinctionPreviewSchema=unloadingOpenComplementPreviewSchema.innerType().extend({proposal:openComplementExtinctionProposalSchema,dispositions:z.array(costFundingSourceSchema.extend({applied_cents:cents,residual_cents:signed})),target:z.object({cost_cents:positive,complement_cents:z.literal('0'),status:z.literal('cancelled')}),effects:openComplementExtinctionEffectsSchema}).superRefine((v,c)=>{const fail=()=>c.addIssue({code:'custom',message:'Conferência da extinção incompatível.'});if(v.cost_origin.tenant_id!==v.tenant_id||v.cost_origin.expense_id!==v.expense_id||v.cost_origin.charge_id!==v.charge_id||v.cost_origin.payable_id!==v.payable_id)fail();if(v.proposal.amount_cents!==v.target.cost_cents||v.effects.cost_after_cents!==v.target.cost_cents||v.effects.cost_before_cents!==v.cost_origin.effective_amount_cents||v.effects.complement_before_cents!==v.payable.amount_cents||v.effects.historical_payable_nominal_cents!==v.payable.amount_cents||v.effects.approval_reset!==v.approval_reset)fail();if(v.can_execute&&(!v.eligible||!v.can_correct))fail();if(v.eligible){if(v.blockers.length||!v.cost_origin.verified||v.payable.amount_cents===null||!['pending','approved'].includes(v.payable.status)||v.approval_reset!==(v.payable.status==='approved')||v.dispositions.length===0||v.dispositions.length!==v.proposal.dispositions.length||!openComplementExtinctionExpectedSchema.safeParse(v.effects).success)fail();const numeric=[v.allocated_reserved_cents,v.proposal.amount_cents,v.effects.residual_cents,...v.dispositions.flatMap(d=>[d.gross_reserved_cents,d.applied_cents,d.residual_cents])].every(n=>/^[0-9]+$/.test(n));if(numeric){let gross=0n,applied=0n,residual=0n;for(const d of v.dispositions){const proposed=v.proposal.dispositions.find(x=>x.source_id===d.source_id);if(d.source_kind!=='expense_allocation'||d.disposition_type!=='driver_custody'||d.responsible_type!=='driver'||!d.responsible_id||!proposed||proposed.applied_cents!==d.applied_cents||proposed.responsible_id!==d.responsible_id||BigInt(d.applied_cents)+BigInt(d.residual_cents)!==BigInt(d.gross_reserved_cents))fail();gross+=BigInt(d.gross_reserved_cents);applied+=BigInt(d.applied_cents);residual+=BigInt(d.residual_cents);}if(new Set(v.dispositions.map(d=>d.source_id)).size!==v.dispositions.length||gross!==BigInt(v.allocated_reserved_cents)||applied!==BigInt(v.proposal.amount_cents)||residual!==BigInt(v.effects.residual_cents))fail();}}});
export const openComplementExtinctionCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid,proposal:openComplementExtinctionProposalSchema,revision,reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000)}).strict().refine(v=>v.proposal.dispositions.length>0);
export const openComplementExtinctionResultSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,request_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid,extinction_id:uuid,regularization_id:uuid,confirmed:z.literal(true),effects:openComplementExtinctionExpectedSchema,payable_status:z.literal('cancelled')}).strict();
export type OpenComplementExtinctionProposal=z.infer<typeof openComplementExtinctionProposalSchema>;
export type OpenComplementExtinctionPreview=z.infer<typeof openComplementExtinctionPreviewSchema>;
export type OpenComplementExtinctionCommand=z.infer<typeof openComplementExtinctionCommandSchema>;
export type OpenComplementExtinctionExpected=z.infer<typeof openComplementExtinctionExpectedSchema>;
export function parseOpenComplementExtinctionResult(value:unknown,command:OpenComplementExtinctionCommand,actor:string,expected:OpenComplementExtinctionExpected){const v=openComplementExtinctionResultSchema.parse(value);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.charge_id!==command.charge_id||v.expense_id!==command.expense_id||v.payable_id!==command.payable_id||v.effects.cost_after_cents!==command.proposal.amount_cents||Object.entries(expected).some(([key,value])=>v.effects[key as keyof typeof expected]!==value))throw new Error('Resposta fora da extinção preservada.');return v;}
