import {supabase} from '@/integrations/supabase/client';
import {readBlobBytes} from '@/lib/uploadPolicy';
import {payableXmlArtifactSchema,payableXmlCommandSchema,payableXmlContextSchema,type PayableXmlCommand} from './payableXmlContract';
type Rpc=(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:unknown}>;
const rpc:Rpc=(name,args)=>(supabase.rpc as unknown as Rpc)(name,args);
export const sendPayableXml=(command:PayableXmlCommand)=>rpc('record_finance_payable_xml',{_payload:payableXmlCommandSchema.parse(command)});
export async function readPayableXmlContext(tenant:string,actor:string,id:string,offset=0,revision:string|null=null){const {data,error}=await rpc('get_finance_payable_xml_context',{_tenant_id:tenant,_payable_id:id,_offset:offset,_expected_revision:revision});if(error)throw error;const v=payableXmlContextSchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.payable_id!==id||v.offset!==offset||(revision!==null&&v.history_revision!==revision))throw Error('Consulta XML fora da conta ou sessão atual.');return v;}
export async function getPayableXmlLocator(tenant:string,link:string){const {data,error}=await rpc('get_finance_payable_xml_locator_v1',{_tenant_id:tenant,_link_id:link});if(error)throw error;if(!data||typeof data!=='object'||!('bucket' in data)||!('path' in data))throw Error('Localização do XML inválida.');return data as {bucket:string;path:string};}
export const payableXmlUploadKey=(tenant:string,actor:string)=>`agvlog:payable-xml-file:v1:${tenant}:${actor}`;
export async function preservePayableXmlFile(tenant:string,actor:string,file:File,storage:Pick<Storage,'getItem'|'setItem'>=localStorage){if(file.size>2_000_000||file.size===0)throw Error('O XML deve ter até 2 MB.');const bytes=await readBlobBytes(file),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',Uint8Array.from(bytes).buffer)),b=>b.toString(16).padStart(2,'0')).join('');const key=payableXmlUploadKey(tenant,actor),raw=storage.getItem(key);let request:string=crypto.randomUUID();if(raw){const old=JSON.parse(raw);if(old.tenant===tenant&&old.actor===actor&&old.hash===hash&&old.size===file.size&&typeof old.request==='string')request=old.request;}
 storage.setItem(key,JSON.stringify({tenant,actor,request,hash,size:file.size}));const body=new FormData();body.set('tenant_id',tenant);body.set('request_id',request);body.set('file',file);const {data,error}=await supabase.functions.invoke('finance-payable-xml',{body});if(error){let code='';try{if('context' in error&&error.context instanceof Response)code=String((await error.context.clone().json()).error??'');}catch{/* Preserve original transport failure. */}throw Error(code==='payable_xml_layout_unsupported'||code==='payable_xml_namespace_unsupported'?'Este anexo aceita XML de NF-e. O leiaute selecionado ainda não é suportado.':code==='payable_xml_entities_forbidden'||code==='payable_xml_processing_instruction_forbidden'?'O XML contém declarações não permitidas. Selecione o arquivo original exportado pelo emissor.':'Não foi possível preservar o XML. A conta não foi salva; mantenha os campos e tente novamente.');}
 const v=payableXmlArtifactSchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.request_id!==request||v.sha256!==hash||v.size_bytes!==file.size||v.state!=='original_quarantined')throw Error('Confirmação do XML incompatível com o arquivo selecionado.');storage.setItem(key,JSON.stringify({tenant,actor,request,hash,size:file.size,artifact_id:v.artifact_id}));return v;}
export async function discardPayableXmlUpload(tenant:string,actor:string,storage:Pick<Storage,'getItem'|'removeItem'>=localStorage){const key=payableXmlUploadKey(tenant,actor),raw=storage.getItem(key);if(!raw)return false;const row=JSON.parse(raw) as {tenant?:string;actor?:string;artifact_id?:string};if(row.tenant!==tenant||row.actor!==actor||!row.artifact_id)throw Error('Não foi possível identificar o upload abandonado.');const {data,error}=await rpc('discard_finance_payable_xml_upload_v1',{_tenant_id:tenant,_artifact_id:row.artifact_id});if(error)throw error;if(data===true)storage.removeItem(key);return data===true;}
export function payableXmlError(error:unknown){const message=error instanceof Error?error.message:typeof error==='object'&&error!==null&&'message' in error?String(error.message):'';if(message.includes('payable_xml_already_registered'))return 'Este XML já está registrado em uma conta ativa desta empresa. Consulte a conta existente; nenhuma nova conta foi criada.';if(message.includes('payable_xml_changed'))return 'A conta mudou desde a abertura. Reabra a conta para conferir os valores atuais antes de salvar.';if(message.includes('payable_xml_history_changed'))return 'O histórico mudou. Atualize a primeira página.';return message||'Não foi possível confirmar o salvamento. Recupere o pedido preservado antes de tentar outro.';}
