import {z} from 'zod';
const uuid=z.string().uuid(),hash=z.string().regex(/^[a-f0-9]{64}$/),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^[1-9][0-9]{0,13}$/);
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
export const payableXmlSummarySchema=z.object({kind:z.literal('nfe'),emitter_name:z.string().min(1).max(1000),emitter_document:z.string().regex(/^(\d{11}|\d{14})$/),document_number:z.string().regex(/^\d{1,9}$/),series:z.string().regex(/^\d{1,3}$/),access_key:z.string().regex(/^\d{44}$/),issue_date:date,amount_cents:cents,signature_verified:z.literal(false),antivirus_verified:z.literal(false)}).strict();
export const payableXmlArtifactSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,request_id:uuid,artifact_id:uuid,sha256:hash,size_bytes:z.number().int().min(1).max(2_000_000),state:z.enum(['reserved','original_quarantined']),summary:payableXmlSummarySchema.nullable(),signature_verified:z.literal(false),antivirus_verified:z.literal(false)}).strict().refine(v=>(v.state==='original_quarantined')===(v.summary!==null));
export const payableXmlFieldsSchema=z.object({supplier_name:z.string().refine(v=>v.trim().length>0),category:z.string().min(1),description:z.string().nullable(),amount_cents:cents,due_date:date.nullable(),competence_date:date.nullable(),document_number:z.string().nullable(),status:z.enum(['pending','overdue','cancelled','approved','paid']),notes:z.string().nullable()}).strict();
export const payableXmlCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,artifact_id:uuid,payable_id:uuid.nullable(),expected_revision:revision.nullable(),fields:payableXmlFieldsSchema}).strict().refine(v=>(v.payable_id===null)===(v.expected_revision===null));
export const payableXmlResultSchema=z.object({version:z.literal(1),confirmed:z.literal(true),tenant_id:uuid,actor_id:uuid,request_id:uuid,payable_id:uuid,artifact_id:uuid,link_id:uuid,amount_cents:cents,original_preserved:z.literal(true),cash_changed:z.literal(false),fiscal_document_created:z.literal(false)}).strict();
export type PayableXmlCommand=z.infer<typeof payableXmlCommandSchema>;
export function parsePayableXmlResult(value:unknown,command:PayableXmlCommand,actor:string){const v=payableXmlResultSchema.parse(value);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.request_id!==command.request_id||v.artifact_id!==command.artifact_id||v.amount_cents!==command.fields.amount_cents||(command.payable_id!==null&&command.payable_id!==v.payable_id))throw Error('A resposta não corresponde à conta e ao XML preservados.');return v;}
export const payableXmlContextSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,payable_id:uuid,revision,history_revision:revision,payable:z.object({id:uuid,tenant_id:uuid}).passthrough(),offset:z.number().int().nonnegative(),total:z.number().int().nonnegative(),next_offset:z.number().int().nonnegative().nullable(),rows:z.array(z.object({link_id:uuid,created_at:z.string(),actor_id:uuid,artifact:payableXmlArtifactSchema}).strict()).max(50)}).strict().superRefine((v,c)=>{if(v.payable.id!==v.payable_id||v.payable.tenant_id!==v.tenant_id||v.rows.some(r=>r.artifact.tenant_id!==v.tenant_id||r.artifact.actor_id!==r.actor_id))c.addIssue({code:'custom',message:'Identidade do histórico XML divergente.'});});
export function payableXmlMoney(value:string){if(!/^\d{1,12}(?:\.\d{1,2})?$/.test(value))throw Error('Informe um valor positivo com no máximo duas casas decimais.');const parts=value.split('.');return cents.parse((BigInt(parts[0])*100n+BigInt((parts[1]??'').padEnd(2,'0'))).toString());}
