import {z} from 'zod';
import {expenseCostOriginSchema} from './unloadingCostCorrectionContract';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^(0|[1-9]\d{0,13})$/),positive=z.string().regex(/^[1-9]\d{0,13}$/);
export const payableApprovalCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,payable_id:uuid,revision,amount_cents:positive,reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000)}).strict();
export const payableApprovalExpectedSchema=z.object({amount_cents:positive,cost_revision:revision.nullable()}).strict();
export const payableApprovalPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,payable_id:uuid,revision,obligation:z.object({amount_cents:cents.nullable(),paid_cents:cents.nullable(),status:z.string(),beneficiary_id:uuid.nullable(),beneficiary_name:z.string().nullable(),source_table:z.string().nullable(),source_id:uuid.nullable()}),cost_origin:expenseCostOriginSchema.nullable(),blockers:z.array(z.object({code:z.string(),source_table:z.string().nullable(),source_ids:z.array(uuid)})),eligible:z.boolean(),can_approve:z.boolean(),can_execute:z.boolean()}).superRefine((v,c)=>{const fail=()=>c.addIssue({code:'custom',message:'Prévia de aprovação incompatível.'});if(v.cost_origin&&(v.cost_origin.tenant_id!==v.tenant_id||v.cost_origin.payable_id!==v.payable_id))fail();if(v.can_execute&&(!v.eligible||!v.can_approve))fail();if(v.eligible&&(v.blockers.length||!['pending','overdue'].includes(v.obligation.status)||!v.obligation.amount_cents||!positive.safeParse(v.obligation.amount_cents).success||v.obligation.paid_cents!=='0'||(v.cost_origin&&!v.cost_origin.verified)))fail();});
export const payableApprovalResultSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,request_id:uuid,payable_id:uuid,approval_event_id:uuid,confirmed:z.literal(true),amount_cents:positive,status:z.literal('approved'),approved_at:z.string().datetime({offset:true}),cost_revision:revision.nullable(),cash_changed:z.literal(false)});
export type PayableApprovalCommand=z.infer<typeof payableApprovalCommandSchema>;
export type PayableApprovalPreview=z.infer<typeof payableApprovalPreviewSchema>;
export function parsePayableApprovalResult(value:unknown,command:PayableApprovalCommand,actor:string,expected:z.infer<typeof payableApprovalExpectedSchema>){const v=payableApprovalResultSchema.parse(value);if(v.tenant_id!==command.tenant_id||v.actor_id!==actor||v.payable_id!==command.payable_id||v.request_id!==command.request_id||v.amount_cents!==command.amount_cents||v.amount_cents!==expected.amount_cents||v.cost_revision!==expected.cost_revision)throw new Error('Resposta incompatível com a aprovação preservada.');return v;}
