import {receivableAdjustmentLabel} from './receivableAdjustmentLabels';
import {supabase} from '@/integrations/supabase/client';
import {receivableAdjustmentCommandSchema,type ReceivableAdjustmentCommand} from './receivableAdjustmentCommandContract';
import {receivableAdjustmentPreviewSchema,receivableAdjustmentHistorySchema,receivableAdjustmentHistoryQuerySchema,type ReceivableAdjustmentHistoryQuery} from './receivableAdjustmentContract';
type Rpc=(name:string,args:Record<string,unknown>)=>Promise<{data:unknown;error:unknown}>;const rpc=supabase.rpc.bind(supabase) as unknown as Rpc;
export class ReceivableAdjustmentChangedError extends Error{}
export async function readReceivableAdjustment(tenant:string,actor:string,receivable:string,kind:'discount'|'loss',amount:string,date:string,adjustment:string|null){const {data,error}=await rpc('preview_finance_receivable_adjustment',{_tenant_id:tenant,_receivable_id:receivable,_kind:kind,_amount_cents:amount,_effective_on:date,_adjustment_id:adjustment});if(error)throw error;const v=receivableAdjustmentPreviewSchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.receivable_id!==receivable||v.kind!==kind||v.amount_cents!==amount||v.effective_on!==date||v.adjustment_id!==adjustment)throw Error('Prévia fora do título e da proposta solicitados.');return v;}
export async function readReceivableAdjustmentHistory(tenant:string,actor:string,receivable:string,query:ReceivableAdjustmentHistoryQuery){const q=receivableAdjustmentHistoryQuerySchema.parse(query),{data,error}=await rpc('get_finance_receivable_adjustments',{_tenant_id:tenant,_receivable_id:receivable,_query:q});if(error){if(typeof error==='object'&&'code' in error&&error.code==='40001')throw new ReceivableAdjustmentChangedError('O histórico mudou. Atualize a primeira página.');throw error;}const v=receivableAdjustmentHistorySchema.parse(data);if(v.tenant_id!==tenant||v.actor_id!==actor||v.receivable_id!==receivable||v.offset!==q.offset||v.limit!==q.limit||q.expected_revision&&q.expected_revision!==v.revision)throw Error('Histórico fora da sessão ou revisão.');return v;}
export const sendReceivableAdjustment=(command:ReceivableAdjustmentCommand)=>rpc('record_finance_receivable_adjustment',{_payload:receivableAdjustmentCommandSchema.parse(command)});
export function receivableAdjustmentError(error:unknown){if(typeof error==='object'&&error!==null&&'code' in error&&['PGRST202','42883'].includes(String(error.code)))return 'Descontos e perdas ainda não estão disponíveis neste ambiente. Nenhum ajuste foi confirmado.';const message=error instanceof Error?error.message:typeof error==='object'&&error!==null&&'message' in error?String(error.message):'';const code=message.match(/finance_adjustment_[a-z_]+/)?.[0];return code?receivableAdjustmentLabel(code):message||'Não foi possível confirmar o ajuste. Preserve e recupere qualquer pedido exibido.';}
