export {receivableAdjustmentCommandSchema} from './receivableAdjustmentCommandContract';
import {z} from 'zod';
import {receivableAdjustmentKindSchema,type ReceivableAdjustmentCommand} from './receivableAdjustmentCommandContract';
const id=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^(0|[1-9]\d{0,13})$/),positive=z.string().regex(/^[1-9]\d{0,13}$/),signed=z.string().regex(/^-?\d+$/),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),kind=receivableAdjustmentKindSchema,action=z.enum(['apply','reverse']);
export const receivableAdjustmentCompositionSchema=z.object({amount_cents:cents.nullable(),cash_received_cents:cents.nullable(),credit_applied_cents:cents.nullable(),discount_cents:cents.nullable(),loss_cents:cents.nullable(),adjustment_cents:cents.nullable(),settled_cents:cents.nullable(),open_cents:cents.nullable()}).strict();
export type ReceivableAdjustmentComposition=z.infer<typeof receivableAdjustmentCompositionSchema>;
const numeric=(v:unknown):v is string=>typeof v==='string'&&/^-?\d+$/.test(v);
export function adjustmentCompositionValid(c:ReceivableAdjustmentComposition){if(!Object.values(c).every(numeric))return false;return BigInt(c.discount_cents!)+BigInt(c.loss_cents!)===BigInt(c.adjustment_cents!)&&BigInt(c.cash_received_cents!)+BigInt(c.credit_applied_cents!)+BigInt(c.adjustment_cents!)===BigInt(c.settled_cents!)&&BigInt(c.settled_cents!)+BigInt(c.open_cents!)===BigInt(c.amount_cents!);}
export const receivableAdjustmentEffectsSchema=z.object({cash_changed:z.literal(false),nominal_changed:z.literal(false),adjustment_delta_cents:signed,before:receivableAdjustmentCompositionSchema,after:receivableAdjustmentCompositionSchema}).strict();
const effectsValid=(e:z.infer<typeof receivableAdjustmentEffectsSchema>)=>{if(!numeric(e.adjustment_delta_cents)||!adjustmentCompositionValid(e.before)||!adjustmentCompositionValid(e.after))return false;return e.before.amount_cents===e.after.amount_cents&&e.before.cash_received_cents===e.after.cash_received_cents&&e.before.credit_applied_cents===e.after.credit_applied_cents&&BigInt(e.after.adjustment_cents!)-BigInt(e.before.adjustment_cents!)===BigInt(e.adjustment_delta_cents);};
const base={version:z.literal(1),tenant_id:id,actor_id:id,receivable_id:id,action,kind,amount_cents:positive,effective_on:date};
export const receivableAdjustmentPreviewSchema=z.object({...base,adjustment_id:id.nullable(),revision,eligible:z.boolean(),can_adjust:z.boolean(),can_execute:z.boolean(),blockers:z.array(z.object({code:z.string(),source_ids:z.array(id)}).strict()),target:receivableAdjustmentCompositionSchema.extend({receivable_id:id,payer_id:id.nullable(),reference:z.string(),status:z.string(),revision,source_issue:z.string().nullable(),fiscal_block_reason:z.string().nullable()}),adjustment:z.object({id,kind,original_cents:positive,reversed_cents:cents,available_to_reverse_cents:cents.nullable(),effective_on:date,created_at:z.string(),actor_id:id.nullable(),actor_name:z.string(),reason:z.string()}).strict().nullable(),effects:receivableAdjustmentEffectsSchema}).strict().superRefine((v,ctx)=>{
 const fail=()=>ctx.addIssue({code:'custom',message:'Prévia de ajuste incompatível com valores e identidades.'});
 if(v.target.receivable_id!==v.receivable_id||(v.action==='apply')!==(v.adjustment_id===null)||v.can_execute&&(!v.eligible||!v.can_adjust)||Object.keys(v.effects.before).some(k=>v.effects.before[k as keyof typeof v.effects.before]!==v.target[k as keyof typeof v.effects.before]))fail();
 if(!numeric(v.amount_cents)||!numeric(v.effects.adjustment_delta_cents))return;
 if(BigInt(v.effects.adjustment_delta_cents)!==(v.action==='apply'?1n:-1n)*BigInt(v.amount_cents))fail();
 if(v.eligible){if(v.blockers.length||!effectsValid(v.effects))return fail();const field=v.kind==='discount'?'discount_cents':'loss_cents',other=v.kind==='discount'?'loss_cents':'discount_cents';if(v.effects.before[other]!==v.effects.after[other]||BigInt(v.effects.after[field]!)-BigInt(v.effects.before[field]!)!==BigInt(v.effects.adjustment_delta_cents))fail();if(v.action==='reverse'&&(!v.adjustment||v.adjustment.id!==v.adjustment_id||v.adjustment.kind!==v.kind||!numeric(v.adjustment.available_to_reverse_cents)||BigInt(v.amount_cents)>BigInt(v.adjustment.available_to_reverse_cents)))fail();}
});
export type ReceivableAdjustmentPreview=z.infer<typeof receivableAdjustmentPreviewSchema>;
export const receivableAdjustmentResultSchema=z.object({...base,confirmed:z.literal(true),request_id:id,event_id:id,adjustment_id:id,cash_movement_created:z.literal(false),effects:receivableAdjustmentEffectsSchema}).strict().refine(v=>effectsValid(v.effects));
export const receivableAdjustmentExpectedSchema=receivableAdjustmentEffectsSchema.refine(effectsValid);
export function parseReceivableAdjustmentResult(raw:unknown,c:ReceivableAdjustmentCommand,actor:string,expected:z.infer<typeof receivableAdjustmentExpectedSchema>){const v=receivableAdjustmentResultSchema.parse(raw);if(v.tenant_id!==c.tenant_id||v.actor_id!==actor||v.request_id!==c.request_id||v.receivable_id!==c.receivable_id||v.action!==c.action||v.kind!==c.kind||v.amount_cents!==c.amount_cents||v.effective_on!==c.effective_on||(c.action==='reverse'?v.adjustment_id!==c.adjustment_id:v.adjustment_id!==v.event_id)||JSON.stringify(v.effects)!==JSON.stringify(receivableAdjustmentEffectsSchema.parse(expected)))throw Error('Resposta diferente do ajuste preservado.');return v;}
export const receivableAdjustmentHistoryQuerySchema=z.object({offset:z.number().int().nonnegative(),limit:z.number().int().min(1).max(100),expected_revision:revision.nullable()}).strict();
export type ReceivableAdjustmentHistoryQuery=z.infer<typeof receivableAdjustmentHistoryQuerySchema>;
export const receivableAdjustmentHistorySchema=z.object({version:z.literal(1),tenant_id:id,actor_id:id,receivable_id:id,offset:z.number().int().nonnegative(),limit:z.number().int().min(1).max(100),total:z.number().int().nonnegative(),next_offset:z.number().int().nonnegative().nullable(),revision,rows:z.array(z.object({id,adjustment_id:id,action,kind,amount_cents:positive,effective_on:date,created_at:z.string(),actor_id:id.nullable(),actor_name:z.string(),reason:z.string(),observation_id:id.nullable(),available_to_reverse_cents:cents.nullable()}).strict()),can_execute:z.literal(false)}).strict().superRefine((v,ctx)=>{if(v.rows.length!==Math.min(v.limit,Math.max(0,v.total-v.offset))||new Set(v.rows.map(r=>r.id)).size!==v.rows.length||v.offset+v.rows.length>v.total||v.next_offset!==(v.offset+v.rows.length<v.total?v.offset+v.rows.length:null)||v.rows.some(r=>r.action==='reverse'&&r.available_to_reverse_cents!==null))ctx.addIssue({code:'custom',message:'Histórico de ajustes inconsistente.'});});
