import {z} from 'zod';
import {receivableAgreementCommandSchema,receivableAgreementResultSchema,receivableAgreementStorageKey,type ReceivableAgreementCommand,type ReceivableAgreementResult} from './receivableAgreementContract';
const id=z.string().uuid();
const inputSchema=receivableAgreementCommandSchema.innerType().omit({version:true,tenant_id:true,request_id:true});
export type ReceivableAgreementInput=z.infer<typeof inputSchema>;
const pendingSchema=z.object({version:z.literal(1),tenantId:id,actorId:id,payload:receivableAgreementCommandSchema}).strict();
export type PendingReceivableAgreement=z.infer<typeof pendingSchema>;
type Store=Pick<Storage,'getItem'|'setItem'|'removeItem'>;const unavailable=()=>new Error('O pedido de renegociação salvo está indisponível ou incompatível. Preserve os dados antes de iniciar outro.');
export function pendingReceivableAgreement(storage:Store,tenant:string,actor:string):PendingReceivableAgreement|null{try{id.parse(tenant);id.parse(actor);const raw=storage.getItem(receivableAgreementStorageKey(tenant,actor));if(raw===null)return null;if(raw.length>100000)throw unavailable();const original=JSON.parse(raw),row=pendingSchema.parse(original);if(row.tenantId!==tenant||row.actorId!==actor||row.payload.tenant_id!==tenant)throw unavailable();return original;}catch{throw unavailable();}}
export function discardPendingReceivableAgreement(storage:Store,tenant:string,actor:string){id.parse(tenant);id.parse(actor);storage.removeItem(receivableAgreementStorageKey(tenant,actor));}
const fallbackLocks=new Map<string,Promise<void>>();
export async function lockReceivableAgreement<T>(key:string,work:()=>Promise<T>):Promise<T>{if(typeof navigator!=='undefined'&&navigator.locks)return navigator.locks.request(key,work);const prior=fallbackLocks.get(key)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});const tail=prior.catch(()=>{}).then(()=>gate);fallbackLocks.set(key,tail);await prior.catch(()=>{});try{return await work();}finally{release();if(fallbackLocks.get(key)===tail)fallbackLocks.delete(key);}}
interface Dependencies{storage:Store;uuid:()=>string;assertContext:(tenant:string,actor:string)=>void;changed:()=>void;lock:<T>(key:string,work:()=>Promise<T>)=>Promise<T>;send:(command:ReceivableAgreementCommand)=>Promise<ReceivableAgreementResult>;isDefinitive:(error:unknown)=>boolean}
export function createReceivableAgreementOutbox(deps:Dependencies){let flight:{identity:string;promise:Promise<ReceivableAgreementResult>}|null=null;const notify=()=>{try{deps.changed();}catch{/* UI notification is best effort. */}};
 function run(tenant:string,actor:string,input?:ReceivableAgreementInput){let parsed:ReceivableAgreementInput|undefined;try{id.parse(tenant);id.parse(actor);parsed=input===undefined?undefined:inputSchema.parse(input);}catch(error){return Promise.reject(error);}const identity=JSON.stringify([tenant,actor,parsed??null]);if(flight)return flight.identity===identity?flight.promise:Promise.reject(Error('Outra renegociação está em andamento.'));
 const key=receivableAgreementStorageKey(tenant,actor),promise=Promise.resolve().then(()=>deps.lock(key,async()=>{deps.assertContext(tenant,actor);const observed=deps.storage.getItem(key),found=pendingReceivableAgreement(deps.storage,tenant,actor);if(deps.storage.getItem(key)!==observed)throw unavailable();let row=found;const uncertain=!!found;if(row&&parsed)throw Error('Há uma renegociação sem confirmação. Recupere o pedido existente.');if(!row){if(!parsed)throw Error('Não há renegociação pendente nesta sessão.');row={version:1,tenantId:tenant,actorId:actor,payload:receivableAgreementCommandSchema.parse({version:1,tenant_id:tenant,request_id:deps.uuid(),...parsed})};}const raw=found?observed:JSON.stringify(row);if(raw===null)throw unavailable();if(!found){if(deps.storage.getItem(key)!==null)throw unavailable();deps.storage.setItem(key,raw);notify();}if(deps.storage.getItem(key)!==raw)throw unavailable();const forget=()=>{try{if(deps.storage.getItem(key)===raw)deps.storage.removeItem(key);}finally{notify();}};
 try{deps.assertContext(tenant,actor);const result=receivableAgreementResultSchema.parse(await deps.send(row.payload));deps.assertContext(tenant,actor);if(result.tenant_id!==tenant||result.actor_id!==actor||result.request_id!==row.payload.request_id||result.receivable_id!==row.payload.receivable_id||result.action!==row.payload.action)throw Error('Resposta incompatível com o pedido de renegociação preservado.');try{forget();}catch{/* The confirmed result remains authoritative if local cleanup fails. */}return result;}catch(error){if(!uncertain&&deps.isDefinitive(error))try{forget();}catch{/* Preserve the definitive server error when local cleanup fails. */}throw error;}}));flight={identity,promise};void promise.finally(()=>{if(flight?.promise===promise)flight=null;notify();}).catch(()=>undefined);return promise;}
 return {submit:(tenant:string,actor:string,input:ReceivableAgreementInput)=>run(tenant,actor,input),recover:(tenant:string,actor:string)=>run(tenant,actor)};
}
