import {z} from 'zod';
const uuid=z.string().uuid(),count=z.number().int().nonnegative(),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),amount=z.string().regex(/^\d+$/).nullable();
export type RecordedCostFilters={from:string|null;to:string|null;category:string|null;costCenter:string|null};
export const recordedCostSummarySchema=z.object({version:z.literal(1),tenant_id:uuid,from:date.nullable(),to:date.nullable(),category:z.string().nullable(),cost_center:z.string().nullable(),coverage:z.literal('recorded_batches_manual_and_payroll_remuneration'),coverage_complete:z.literal(false),excludes_bank_cash:z.literal(true),total_count:count,cancelled_count:count,invalid_count:count,payroll_unclassified_count:count,recorded_date_count:count,totals_valid:z.boolean(),total_cents:amount,categories:z.array(z.object({category:z.string().nullable(),item_count:count,amount_cents:amount})),cost_centers:z.array(z.object({cost_center_id:uuid.nullable(),cost_center_name:z.string().nullable(),item_count:count,amount_cents:amount})),months:z.array(z.object({month:z.string().regex(/^\d{4}-\d{2}$/).nullable(),item_count:count,amount_cents:amount})),excluded_sources:z.array(z.enum(['legacy_driver_expenses','maintenance_orders','settlement_composition','payroll_reimbursements_and_advances']))}).superRefine((data,ctx)=>{
 const amounts=[data.total_cents,...data.categories.map(row=>row.amount_cents),...data.cost_centers.map(row=>row.amount_cents),...data.months.map(row=>row.amount_cents)];
 if(amounts.some(value=>data.totals_valid?value===null:value!==null)||data.invalid_count>data.total_count||data.payroll_unclassified_count>data.invalid_count||(data.totals_valid&&data.invalid_count>0))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Totais de custos incompatíveis.'});
 if(new Set(data.excluded_sources).size!==4)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Cobertura de custos incompleta na resposta.'});
 for(const rows of [data.categories,data.cost_centers,data.months]){if(rows.reduce((sum,row)=>sum+row.item_count,0)!==data.total_count)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Contagem de custos inconsistente.'});if(data.totals_valid&&data.total_cents!==null&&rows.every(row=>row.amount_cents!==null)&&rows.reduce((sum,row)=>sum+BigInt(row.amount_cents!),0n)!==BigInt(data.total_cents))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Grupos e total de custos divergem.'});}
});
