import {movementUseError} from './movementUseErrors';
import {supabase} from '@/integrations/supabase/client';
import {settlementPaymentCommandSchema,settlementPaymentResultSchema,settlementPaymentCandidatesSchema,type SettlementPaymentCommand} from './settlementPaymentContract';
type Rpc=(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:{message:string;code?:string}|null}>;
export class SettlementPaymentRejectedError extends Error {}
export function settlementPaymentError(error:unknown){const movementError=movementUseError(error);if(movementError)return movementError;const message=error instanceof Error?error.message:'Não foi possível confirmar a operação.';
 const labels:Record<string,string>={finance_settlement_requires_review:'Revise a aprovação, o recálculo e o motorista do acerto antes de registrar o pagamento.',finance_settlement_invalid_balance:'O saldo do acerto está inconsistente. Confira os pagamentos e revise o acerto.',finance_invalid_payment_query:'Informe um valor positivo válido para consultar as saídas.',finance_settlement_not_found:'O acerto não foi encontrado nesta empresa.',finance_movement_overallocated:'A saída já não tem capacidade suficiente. Atualize a seleção.',finance_access_denied:'Seu acesso financeiro não foi confirmado.',finance_settlement_driver_required:'Identifique o motorista do acerto antes de registrar o pagamento.',finance_settlement_movement_mismatch:'A saída não corresponde ao motorista ou ao tipo de pagamento deste acerto.',finance_invalid_account:'A conta da saída está inválida. Confira o registro bancário.',finance_settlement_locked_in_payroll:'O acerto pertence a uma folha protegida. Revise a folha antes de registrar outro pagamento.',finance_payroll_period_protected:'A folha está protegida contra alterações. Revise sua situação antes de continuar.',finance_settlement_overlapping_payroll:'Há folhas sobrepostas para este motorista. Resolva a duplicidade antes de registrar o pagamento.',finance_settlement_amount_review:'Os valores do acerto precisam de revisão antes de receber outro pagamento.',finance_settlement_overpaid:'O valor supera o saldo efetivo do acerto. Atualize os pagamentos e ajuste o valor.',finance_request_conflict:'Este pedido já possui outro conteúdo registrado. Confira o histórico antes de continuar.',finance_invalid_payload:'Confira o valor, a saída, o método e o motivo do pagamento.'};return labels[message]||message;
}
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await (supabase.rpc as unknown as Rpc)(name,args);if(error){if(['22023','23514','23505','40001','42501','55000'].includes(error.code||''))throw new SettlementPaymentRejectedError(error.message);throw new Error(error.message);}return data;}
export async function recordSettlementPayment(command:SettlementPaymentCommand){
 settlementPaymentCommandSchema.parse(command);const result=settlementPaymentResultSchema.parse(await rpc('record_finance_settlement_payment',{_payload:command}));
 if(result.tenant_id!==command.tenant_id||result.request_id!==command.request_id||result.settlement_id!==command.settlement_id||result.movement_id!==command.movement_id||result.amount_cents!==command.amount_cents)throw new Error('Pagamento fora do contexto.');return result;
}
export async function readSettlementPaymentCandidates(tenant:string,settlement:string,amount:number,page:number){
 const result=settlementPaymentCandidatesSchema.parse(await rpc('get_finance_settlement_payment_candidates',{_tenant_id:tenant,_settlement_id:settlement,_amount_cents:amount,_page:page}));
 if(result.tenant_id!==tenant||result.settlement_id!==settlement||result.amount_cents!==amount||result.page!==page)throw new Error('Saídas fora do contexto.');return result;
}
