import {z} from 'zod';
import {periodEvidenceSchema} from './periodEvidenceClient';
const uuid=z.string().uuid(),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const declarations=z.object({originals_obtained_from_bank:z.literal(true),complete_period_confirmed:z.literal(true)});
export const coverageBlockingLabels={period_not_finished:'O período ainda não terminou.',bank_account_required:'Este controle exige conta bancária, não caixa físico.',coverage_gaps:'Há dias sem cobertura integral declarada nos arquivos.',timezone_conflict:'Os fusos dos arquivos são incompatíveis.',missing_anchors:'Faltam saldos nos limites do período.',conflicting_anchors:'Os arquivos apresentam saldos conflitantes.',balance_mismatch:'Os saldos não fecham com a movimentação identificada.',timezone_not_sao_paulo:'As evidências não usam o fuso de São Paulo.',source_account_unverified:'A identificação de conta de algum arquivo precisa de revisão.',source_integrity_issue:'A integridade de algum original precisa de revisão.',unsupported_source_format:'Há arquivo em formato não elegível para esta aprovação.',unverified_source:'Há original cujas linhas ainda não foram conferidas.',unresolved_identity:'Há linhas com identidade de transação pendente.'} as const;
const snapshot=z.object({version:z.literal(1),tenant_id:uuid,account_id:uuid,from:date,to:date,evidence:periodEvidenceSchema,dependencies:z.record(z.unknown()),blocking_reasons:z.array(z.enum(Object.keys(coverageBlockingLabels) as [keyof typeof coverageBlockingLabels,...(keyof typeof coverageBlockingLabels)[]])),can_approve:z.boolean(),revision:z.string().min(1),authenticity_status:z.literal('not_attested'),review_method:z.literal('reviewed_by_user'),can_close:z.literal(false)});
const approval=z.object({id:uuid,tenant_id:uuid,bank_account_id:uuid,period_start:date,period_end:date,actor_id:uuid,actor_name:z.string(),reason:z.string(),revision:z.string(),snapshot,declarations,created_at:z.string()});
export const statementCoverageSchema=snapshot.extend({status:z.enum(['not_approved','approved','needs_review','reversed']),current:z.boolean(),approval:approval.nullable(),history:z.array(approval.extend({reversal:z.object({id:uuid,tenant_id:uuid,approval_id:uuid,actor_id:uuid,actor_name:z.string(),reason:z.string(),created_at:z.string()}).nullable()}))}).superRefine((data,ctx)=>{
 const same=(s:{tenant_id:string;account_id:string;from:string;to:string})=>s.tenant_id===data.tenant_id&&s.account_id===data.account_id&&s.from===data.from&&s.to===data.to;
 if(!same(data.evidence))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Evidência fora da cobertura.'});
 for(const item of [...(data.approval?[data.approval]:[]),...data.history])if(item.tenant_id!==data.tenant_id||item.bank_account_id!==data.account_id||item.period_start!==data.from||item.period_end!==data.to||!same(item.snapshot)||!same(item.snapshot.evidence)||item.snapshot.revision!==item.revision)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Histórico fora da cobertura.'});
 for(const item of data.history)if(item.reversal&&(item.reversal.approval_id!==item.id||item.reversal.tenant_id!==data.tenant_id))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Reversão fora da aprovação.'});
});
export const coverageApprovalCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,account_id:uuid,from:date,to:date,revision:z.string().min(1),reason:z.string().trim().min(10).max(2000),originals_obtained_from_bank:z.literal(true),complete_period_confirmed:z.literal(true)}).strict();
export const coverageReversalCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,approval_id:uuid,reason:z.string().trim().min(10).max(2000)}).strict();
export const coveragePendingSchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('approve'),command:coverageApprovalCommandSchema}),z.object({kind:z.literal('reverse'),command:coverageReversalCommandSchema})]);
export type CoveragePending=z.infer<typeof coveragePendingSchema>;
export const coverageApprovalResultSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,approval_id:uuid,revision:z.string(),review_method:z.literal('reviewed_by_user'),authenticity_status:z.literal('not_attested'),confirmed:z.literal(true),can_close:z.literal(false)});
export const coverageReversalResultSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,approval_id:uuid,reversal_id:uuid,confirmed:z.literal(true),can_close:z.literal(false)});
