import {supabase} from '@/integrations/supabase/client';
import {stockAcquisitionInventorySchema,stockAcquisitionContextSchema,stockAcquisitionPendingSchema,stockAcquisitionAssociateResultSchema,stockAcquisitionReverseResultSchema,type StockAcquisitionPending} from './stockAcquisitionContract';
type Rpc=(name:string,args:Record<string,unknown>)=>PromiseLike<{data:unknown;error:{message:string;code?:string}|null}>;
export class StockAcquisitionRejectedError extends Error {}
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await(supabase.rpc as unknown as Rpc)(name,args);if(error){if(['22023','23514','23505','40001','42501','55000'].includes(error.code||''))throw new StockAcquisitionRejectedError(error.message);throw new Error(error.message);}return data;}
export async function readStockAcquisitionAssociation(tenant:string,part:string,page=1,search=''){const data=stockAcquisitionContextSchema.parse(await rpc('get_finance_stock_acquisition_context',{_tenant_id:tenant,_inbound_movement_id:part,_page:page,_search:search}));if(data.tenant_id!==tenant||data.inbound_movement_id!==part||data.page!==page||data.search!==search)throw new Error('Consulta fora da entrada de estoque selecionada.');return data;}
export async function submitStockAcquisitionAssociation(pending:StockAcquisitionPending){stockAcquisitionPendingSchema.parse(pending);const raw=await rpc(pending.kind==='associate'?'associate_finance_stock_acquisition':'reverse_finance_stock_acquisition_association',{_payload:pending.command});const result=pending.kind==='associate'?stockAcquisitionAssociateResultSchema.parse(raw):stockAcquisitionReverseResultSchema.parse(raw);if(result.tenant_id!==pending.command.tenant_id||result.request_id!==pending.command.request_id||(pending.kind==='associate'&&(result.inbound_movement_id!==pending.command.inbound_movement_id||result.cost_id!==pending.command.cost_id))||(pending.kind==='reverse'&&result.link_id!==pending.command.link_id))throw new Error('Confirmação fora da associação de aquisição.');return result;}


export async function readStockAcquisitionInventory(tenant:string,page=1,search=''){const data=stockAcquisitionInventorySchema.parse(await rpc('get_finance_stock_acquisition_inventory',{_tenant_id:tenant,_page:page,_search:search}));if(data.tenant_id!==tenant||data.page!==page||data.search!==search)throw new Error('Inventário fora da empresa ou busca solicitada.');return data;}
