import {z} from 'zod';
const uuid=z.string().uuid(),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),count=z.number().int().nonnegative(),cents=z.string().regex(/^\d+$/).nullable();
export const freightStates=['available','reserved','uncertain','authorized','review','cancelled'] as const;
const state=z.enum(freightStates);
export type FreightState=z.infer<typeof state>;
export type FreightFilters={from:string|null;to:string|null;client:string|null};
const envelope={version:z.literal(1),tenant_id:uuid,from:date.nullable(),to:date.nullable(),client_id:uuid.nullable()};
export const unbilledFreightSummarySchema=z.object({...envelope,basis:z.literal('per_nf_freight'),date_basis:z.literal('invoice_issue_or_attempt_recorded_date'),expected_receipt_date:z.null(),coverage_complete:z.literal(false),total_origins:count,available_count:count,reserved_count:count,uncertain_count:count,authorized_count:count,review_count:count,cancelled_count:count,undated_count:count,totals_valid:z.boolean(),forecast_cents:cents,groups:z.array(z.object({state,origin_count:count,forecast_cents:cents})),months:z.array(z.object({month:z.string().regex(/^\d{4}-\d{2}$/).nullable(),origin_count:count,forecast_cents:cents})),diagnostics:z.record(count)}).superRefine((data,ctx)=>{
 const amounts=[data.forecast_cents,...data.groups.map(row=>row.forecast_cents),...data.months.map(row=>row.forecast_cents)];
 if(amounts.some(value=>data.totals_valid?value===null:value!==null)||data.totals_valid!==(data.review_count===0)||data.undated_count>data.total_origins||new Set(data.groups.map(row=>row.state)).size!==data.groups.length||new Set(data.months.map(row=>row.month)).size!==data.months.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Resumo da previsão inconsistente.'});
 if(freightStates.reduce((sum,state)=>sum+data[`${state}_count`],0)!==data.total_origins||data.groups.some(row=>row.origin_count!==data[`${row.state}_count`]))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Estados da previsão incompatíveis.'});
 for(const rows of [data.groups,data.months]){if(rows.reduce((sum,row)=>sum+row.origin_count,0)!==data.total_origins)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Contagens da previsão divergentes.'});if(data.totals_valid&&data.forecast_cents!==null&&rows.every(row=>row.forecast_cents!==null)&&rows.reduce((sum,row)=>sum+BigInt(row.forecast_cents!),0n)!==BigInt(data.forecast_cents))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Valores da previsão divergentes.'});}
 if(data.totals_valid&&data.groups.some(row=>row.state!=='available'&&row.forecast_cents!==null&&BigInt(row.forecast_cents)!==0n))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Estado não disponível incluído na previsão.'});
});
export const unbilledFreightOriginsSchema=z.object({...envelope,state:state.nullable(),page:z.number().int().positive(),page_size:z.literal(30),total:count,rows:z.array(z.object({document_id:uuid,attempt_id:uuid.nullable(),client_id:uuid.nullable(),origin_date:date.nullable(),date_basis:z.enum(['invoice_issue_date','attempt_recorded_date']),state,freight_cents:cents,issues:z.array(z.string())})).max(30)}).superRefine((data,ctx)=>{
 if(data.rows.some(row=>(data.state&&row.state!==data.state)||(row.attempt_id===null?row.date_basis!=='invoice_issue_date':row.date_basis!=='attempt_recorded_date'||row.freight_cents!==null))||new Set(data.rows.map(row=>`${row.document_id}:${row.attempt_id||'original'}`)).size!==data.rows.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Origens da previsão incompatíveis.'});
});
export const freightStateLabels:Record<FreightState,string>={available:'Disponível para previsão',reserved:'Reservado para emissão',uncertain:'Resultado fiscal incerto',authorized:'Já autorizado',review:'Precisa de revisão',cancelled:'Cancelado'};
export type UnbilledFreightSummary=z.infer<typeof unbilledFreightSummarySchema>;

export const freightIssueLabels:Record<string,string>={fiscal_state_unknown:'O estado fiscal não foi reconhecido e precisa de revisão.',authorization_evidence_invalid:'A evidência de autorização fiscal precisa de revisão.',service_outcome_requires_pricing_review:'O resultado do serviço exige revisão do preço do frete.',multiple_authorizations:'Há mais de uma autorização relacionada à mesma NF.',cancelled_service_requires_review:'O serviço fiscal cancelado precisa de revisão.',legacy_fiscal_coverage_unconfirmed:'A cobertura fiscal antiga ainda não foi confirmada.',fiscal_marker_without_source:'Há indicação de emissão sem origem fiscal identificada.',commercial_claim_requires_allocation_review:'A cobrança comercial precisa de revisão do vínculo.',original_service_has_redelivery:'O serviço original possui tentativa de reentrega.',duplicate_invoice_identity:'A identidade da NF aparece duplicada.',payer_unknown:'O pagador do frete precisa ser identificado.',origin_date_unknown:'A data da origem precisa ser identificada.',freight_unknown:'O valor de frete não está determinado.',unpriced_redelivery:'A tentativa de reentrega ainda não tem preço de frete determinado.'};
