import {z} from 'zod';
import {unloadingEffectiveOriginSchema} from './unloadingOriginCorrectionContract';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^\d+$/);
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
export const unloadingCancellationPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,charge_id:uuid,expense_id:uuid.nullable(),payable_id:uuid.nullable(),effective_on:day,origin:unloadingEffectiveOriginSchema,cost:z.object({amount_cents:cents,payable_cents:cents.nullable(),beneficiary_id:uuid.nullable(),beneficiary_name:z.string().nullable(),payee_type:z.enum(['supplier','driver']).nullable()}).strict().nullable(),blockers:z.array(z.object({code:z.string(),source_table:z.string().nullable(),source_ids:z.array(uuid)}).strict()),eligible:z.boolean(),can_cancel:z.boolean(),can_execute:z.boolean(),revision,effects:z.object({computation:z.literal('prospective_coordinated_cancellation'),cash_changed:z.literal(false),cost_removed_cents:cents.nullable(),obligation_cancelled_cents:cents.nullable(),collection_cancelled_cents:cents.nullable()}).strict(),history:z.array(z.object({request_id:uuid,actor_id:uuid,actor_name:z.string().nullable(),reason:z.string(),created_at:z.string(),expense_cancellation_id:uuid,origin_amendment_id:uuid}).strict())}).strict().superRefine((v,c)=>{
 const fail=(message:string)=>c.addIssue({code:'custom',message});
 if(v.origin.tenant_id!==v.tenant_id||v.origin.charge_id!==v.charge_id)fail('Origem fora da descarga solicitada.');
 if(v.eligible&&(v.blockers.length||!v.origin.verified||v.origin.effective?.status!=='active'||!v.expense_id||!v.payable_id||!v.cost||Object.values(v.effects).some(value=>value===null)))fail('Cancelamento elegível sem evidências completas.');
 if(v.can_execute&&(!v.eligible||!v.can_cancel))fail('Execução sem permissão e elegibilidade.');
 if(v.eligible&&(v.effects.cost_removed_cents!==v.cost?.amount_cents||v.effects.obligation_cancelled_cents!==v.cost?.payable_cents||v.effects.collection_cancelled_cents!==v.origin.effective?.amount_cents))fail('Efeitos diferentes dos valores conferidos.');
});
export type UnloadingCancellationPreview=z.infer<typeof unloadingCancellationPreviewSchema>;
export const unloadingCancellationCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,charge_id:uuid,effective_on:day,revision,reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000)}).strict();
export type UnloadingCancellationCommand=z.infer<typeof unloadingCancellationCommandSchema>;
export const unloadingCancellationExpectedSchema=z.object({receivable_id:uuid,expense_id:uuid,payable_id:uuid,cost_removed_cents:cents,obligation_cancelled_cents:cents,collection_cancelled_cents:cents}).strict();
export type UnloadingCancellationExpected=z.infer<typeof unloadingCancellationExpectedSchema>;
export const unloadingCancellationResultSchema=unloadingCancellationExpectedSchema.extend({version:z.literal(1),tenant_id:uuid,actor_id:uuid,request_id:uuid,charge_id:uuid,expense_cancellation_id:uuid,origin_amendment_id:uuid,confirmed:z.literal(true),cash_changed:z.literal(false)}).strict();
export function parseUnloadingCancellationResult(value:unknown,command:UnloadingCancellationCommand,actorId:string,expected:UnloadingCancellationExpected){const result=unloadingCancellationResultSchema.parse(value);if(result.tenant_id!==command.tenant_id||result.actor_id!==actorId||result.request_id!==command.request_id||result.charge_id!==command.charge_id||Object.entries(expected).some(([key,value])=>result[key as keyof typeof result]!==value))throw new Error('Resposta incompatível com o cancelamento preservado.');return result;}
