import {z} from 'zod';
import {expenseCostOriginSchema} from './unloadingCostCorrectionContract';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),positive=z.string().regex(/^[1-9]\d{0,13}$/),cents=z.string().regex(/^(0|[1-9]\d*)$/);
export const unloadingOpenComplementEffectsSchema=z.object({cost_before_cents:positive.nullable(),cost_after_cents:positive,complement_before_cents:positive.nullable(),complement_after_cents:positive.nullable(),cash_changed:z.literal(false),capacity_released_cents:z.literal('0'),approval_reset:z.boolean()}).strict();
export const unloadingOpenComplementExpectedSchema=unloadingOpenComplementEffectsSchema.extend({cost_before_cents:positive,complement_before_cents:positive,complement_after_cents:positive});
const identity={version:z.literal(1),tenant_id:uuid,actor_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid};
export const unloadingOpenComplementCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid,amount_cents:positive,revision,reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000)}).strict();
export const unloadingOpenComplementPreviewSchema=z.object({...identity,revision,cost_origin:expenseCostOriginSchema,allocated_reserved_cents:cents,payable:z.object({amount_cents:positive.nullable(),status:z.string(),beneficiary_id:uuid.nullable(),beneficiary_name:z.string().nullable()}).strict(),target:z.object({cost_cents:positive,complement_cents:positive.nullable(),status:z.literal('pending')}).strict(),approval_reset:z.boolean(),blockers:z.array(z.object({code:z.string(),source_table:z.string().nullable(),source_ids:z.array(uuid)}).strict()),eligible:z.boolean(),can_correct:z.boolean(),can_execute:z.boolean(),effects:unloadingOpenComplementEffectsSchema}).strict().superRefine((v,ctx)=>{
 const fail=(message:string)=>ctx.addIssue({code:'custom',message});
 if(v.cost_origin.tenant_id!==v.tenant_id||v.cost_origin.expense_id!==v.expense_id||v.cost_origin.charge_id!==v.charge_id||v.cost_origin.payable_id!==v.payable_id)fail('Origem diferente da consulta.');
 if(v.effects.cost_before_cents!==v.cost_origin.effective_amount_cents||v.effects.complement_before_cents!==v.payable.amount_cents||v.effects.cost_after_cents!==v.target.cost_cents||v.effects.complement_after_cents!==v.target.complement_cents||v.effects.approval_reset!==v.approval_reset)fail('Efeitos diferentes dos valores conferidos.');
 if(/^\d+$/.test(v.target.cost_cents)&&/^\d+$/.test(v.allocated_reserved_cents)){const after=BigInt(v.target.cost_cents)-BigInt(v.allocated_reserved_cents);if(v.target.complement_cents!==(after>0n?after.toString():null))fail('Complemento não corresponde ao custo menos o vínculo preservado.');}
 if(v.can_execute&&(!v.eligible||!v.can_correct))fail('Execução sem permissão ou elegibilidade.');
 if(v.eligible&&(!v.cost_origin.verified||v.blockers.length||!['pending','approved'].includes(v.payable.status)||v.approval_reset!==(v.payable.status==='approved')||v.effects.cost_before_cents===null||v.effects.complement_before_cents===null||v.effects.complement_after_cents===null||v.effects.cost_before_cents===v.effects.cost_after_cents))fail('Correção sem evidência completa.');
});
export const unloadingOpenComplementResultSchema=z.object({...identity,request_id:uuid,amendment_id:uuid,confirmed:z.literal(true),effects:unloadingOpenComplementExpectedSchema,payable_status:z.literal('pending')}).strict();
export type UnloadingOpenComplementCommand=z.infer<typeof unloadingOpenComplementCommandSchema>;
export type UnloadingOpenComplementPreview=z.infer<typeof unloadingOpenComplementPreviewSchema>;
export type UnloadingOpenComplementExpected=z.infer<typeof unloadingOpenComplementExpectedSchema>;
export function parseUnloadingOpenComplementResult(value:unknown,command:UnloadingOpenComplementCommand,actor:string,expected:UnloadingOpenComplementExpected){const r=unloadingOpenComplementResultSchema.parse(value);if(r.tenant_id!==command.tenant_id||r.actor_id!==actor||r.request_id!==command.request_id||r.charge_id!==command.charge_id||r.expense_id!==command.expense_id||r.payable_id!==command.payable_id||r.effects.cost_after_cents!==command.amount_cents||Object.keys(expected).some(k=>r.effects[k as keyof typeof expected]!==expected[k as keyof typeof expected]))throw new Error('Resposta incompatível com o pedido de correção do complemento.');return r;}
