import {z} from 'zod';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/);
const positiveCents=z.string().regex(/^[1-9]\d{0,13}$/),nonnegativeCents=z.string().regex(/^(0|[1-9]\d{0,13})$/);
export const unloadingCostDispositionProposalSchema=z.object({source_kind:z.enum(['expense_allocation','payable_link']),source_id:uuid,applied_cents:nonnegativeCents,disposition_type:z.enum(['driver_custody','payment_recovery']),responsible_id:uuid}).strict();
export const unloadingCostRegularizationProposalSchema=z.object({amount_cents:positiveCents,dispositions:z.array(unloadingCostDispositionProposalSchema).max(500)}).strict().superRefine((v,c)=>{const keys=v.dispositions.map(s=>`${s.source_kind}:${s.source_id}`);if(new Set(keys).size!==keys.length)c.addIssue({code:'custom',message:'A mesma fonte não pode aparecer duas vezes na proposta.'});});
export type UnloadingCostRegularizationProposal=z.infer<typeof unloadingCostRegularizationProposalSchema>;
export const unloadingCostRegularizationCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid.nullable(),revision,proposal:unloadingCostRegularizationProposalSchema,reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000)}).strict().refine(v=>v.proposal.dispositions.length>0,'Confirme as fontes da proposta.');
export type UnloadingCostRegularizationCommand=z.infer<typeof unloadingCostRegularizationCommandSchema>;

export function proposedAppliedCents(value:string):string|null{const m=value.trim().match(/^(\d{1,12})(?:[,.](\d{1,2}))?$/);return m?(BigInt(m[1])*100n+BigInt((m[2]||'').padEnd(2,'0'))).toString():null;}

import {expenseCostOriginSchema} from './unloadingCostCorrectionContract';
import {costFundingSourceSchema,costDispositionPreviewSchema} from './expenseCostFundingContract';
const total=z.string().regex(/^(0|[1-9]\d*)$/),signed=z.string().regex(/^-?\d+$/);
export const unloadingCostRegularizationEffectsSchema=z.object({computation:z.literal('prospective_cost_regularization'),cost_before_cents:positiveCents.nullable(),cost_after_cents:positiveCents,cost_delta_cents:signed.nullable(),gross_reserved_cents:total,applied_cents:total,residual_cents:signed,driver_custody_cents:signed,payment_recovery_cents:signed,cash_changed:z.literal(false),payable_changed:z.literal(false),reconciliation_changed:z.literal(false),movement_capacity_released_cents:z.literal('0')}).strict();
export const unloadingCostRegularizationPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid.nullable(),revision,cost_origin:expenseCostOriginSchema,source_rows:z.array(costFundingSourceSchema),dispositions:z.array(costDispositionPreviewSchema),obligation:z.object({action:z.literal('preserve_historical'),nominal_cents:total.nullable(),paid_cents:total.nullable(),open_cents:signed.nullable()}).strict(),materialization_plan:z.object({action:z.enum(['none','review_required']),source_ids:z.array(uuid)}).strict(),blockers:z.array(z.object({code:z.string(),source_table:z.string().nullable(),source_ids:z.array(uuid)}).strict()),eligible:z.boolean(),can_regularize:z.boolean(),can_execute:z.boolean(),effects:unloadingCostRegularizationEffectsSchema}).strict().superRefine((v,c)=>{
 const fail=(message:string)=>c.addIssue({code:'custom',message});
 if(v.cost_origin.tenant_id!==v.tenant_id||v.cost_origin.expense_id!==v.expense_id||v.cost_origin.charge_id!==v.charge_id||v.cost_origin.payable_id!==v.payable_id)fail('Origem fora da regularização.');
 if(v.effects.cost_before_cents!==v.cost_origin.effective_amount_cents)fail('Custo anterior diferente da origem.');
 if(v.eligible&&(v.blockers.length||!v.cost_origin.verified||v.dispositions.length===0||v.dispositions.some(d=>!d.responsible_id||d.residual_cents.startsWith('-'))||v.effects.applied_cents!==v.effects.cost_after_cents||v.materialization_plan.action!=='none'))fail('Elegibilidade sem comprovação completa.');
 const e=v.effects;const amounts=[e.gross_reserved_cents,e.applied_cents,e.residual_cents,e.driver_custody_cents,e.payment_recovery_cents,e.cost_after_cents,...(e.cost_before_cents===null?[]:[e.cost_before_cents]),...(e.cost_delta_cents===null?[]:[e.cost_delta_cents])];
 if(amounts.every(n=>/^-?\d+$/.test(n))){if(BigInt(e.gross_reserved_cents)!==BigInt(e.applied_cents)+BigInt(e.residual_cents)||BigInt(e.residual_cents)!==BigInt(e.driver_custody_cents)+BigInt(e.payment_recovery_cents))fail('Decomposição financeira inconsistente.');if(e.cost_before_cents!==null&&(e.cost_delta_cents===null||BigInt(e.cost_after_cents)-BigInt(e.cost_before_cents)!==BigInt(e.cost_delta_cents)))fail('Variação de custo inconsistente.');}
 if(v.eligible&&v.dispositions.every(d=>[d.gross_reserved_cents,d.applied_cents,d.residual_cents].every(n=>/^\d+$/.test(n)))){
  const ds=v.dispositions;if(ds.length!==v.source_rows.length||new Set(ds.map(d=>`${d.source_kind}:${d.source_id}`)).size!==ds.length||ds.some(d=>!v.source_rows.some(s=>s.source_kind===d.source_kind&&s.source_id===d.source_id&&s.movement_id===d.movement_id&&s.payment_id===d.payment_id&&s.gross_reserved_cents===d.gross_reserved_cents&&s.responsible_id===d.responsible_id&&s.disposition_type===d.disposition_type)||BigInt(d.gross_reserved_cents)!==BigInt(d.applied_cents)+BigInt(d.residual_cents)))fail('Fontes e disposições inconsistentes.');
  const sum=(key:'gross_reserved_cents'|'applied_cents'|'residual_cents',kind?:string)=>ds.filter(d=>!kind||d.disposition_type===kind).reduce((n,d)=>n+BigInt(d[key]),0n).toString();
  if(e.gross_reserved_cents!==sum('gross_reserved_cents')||e.applied_cents!==sum('applied_cents')||e.residual_cents!==sum('residual_cents')||e.driver_custody_cents!==sum('residual_cents','driver_custody')||e.payment_recovery_cents!==sum('residual_cents','payment_recovery'))fail('Totais não correspondem às responsabilidades.');
 }
 if(v.can_execute&&(!v.eligible||!v.can_regularize))fail('Execução sem autorização.');
});
export type UnloadingCostRegularizationPreview=z.infer<typeof unloadingCostRegularizationPreviewSchema>;
export const unloadingCostRegularizationResultSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,request_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid.nullable(),regularization_id:uuid,disposition_ids:z.array(uuid),confirmed:z.literal(true),effects:unloadingCostRegularizationEffectsSchema}).strict();
export type UnloadingCostRegularizationExpected=z.infer<typeof unloadingCostRegularizationEffectsSchema>;
export function parseUnloadingCostRegularizationResult(value:unknown,command:UnloadingCostRegularizationCommand,actor:string,expected:UnloadingCostRegularizationExpected){const result=unloadingCostRegularizationResultSchema.parse(value);if(result.tenant_id!==command.tenant_id||result.actor_id!==actor||result.request_id!==command.request_id||result.charge_id!==command.charge_id||result.expense_id!==command.expense_id||result.payable_id!==command.payable_id||result.effects.cost_after_cents!==command.proposal.amount_cents||Object.entries(expected).some(([k,v])=>result.effects[k as keyof typeof expected]!==v)||result.disposition_ids.length!==command.proposal.dispositions.length||new Set(result.disposition_ids).size!==result.disposition_ids.length)throw new Error('Resposta incompatível com a regularização preservada.');return result;}
