import {expenseCostRegularizationSchema} from './expenseCostFundingContract';
import {z} from 'zod';
const uuid=z.string().uuid(),revision=z.string().regex(/^[a-f0-9]{32}$/),cents=z.string().regex(/^[1-9]\d{0,13}$/);
export const expenseCostOriginSchema=z.object({version:z.literal(1),tenant_id:uuid,expense_id:uuid,charge_id:uuid.nullable(),payable_id:uuid.nullable(),verified:z.boolean(),issue:z.string().nullable(),original_amount_cents:cents,effective_amount_cents:cents.nullable(),regularization:expenseCostRegularizationSchema.nullable().optional(),revision,history:z.array(z.object({id:uuid,ordinal:z.number().int().positive(),previous_id:uuid.nullable(),request_id:uuid,before_amount_cents:cents,after_amount_cents:cents,approval_reset:z.boolean(),actor_id:uuid,actor_name:z.string().nullable(),reason:z.string(),created_at:z.string(),revision_after:revision}).strict())}).strict().superRefine((v,c)=>{if(v.verified&&(v.issue!==null||v.effective_amount_cents===null)||!v.verified&&v.effective_amount_cents!==null)c.addIssue({code:'custom',message:'Custo vigente incompatível com a comprovação da origem.'});});
export type ExpenseCostOrigin=z.infer<typeof expenseCostOriginSchema>;
export const unloadingCostCorrectionCommandSchema=z.object({version:z.literal(1),tenant_id:uuid,request_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid,amount_cents:cents,revision,reason:z.string().refine(v=>v.trim().length>=10&&v.trim().length<=2000)}).strict();
export type UnloadingCostCorrectionCommand=z.infer<typeof unloadingCostCorrectionCommandSchema>;
export const unloadingCostCorrectionExpectedSchema=z.object({cost_before_cents:cents,cost_after_cents:cents,obligation_before_cents:cents,obligation_after_cents:cents,approval_reset:z.boolean(),payable_status:z.literal('pending')}).strict();
export type UnloadingCostCorrectionExpected=z.infer<typeof unloadingCostCorrectionExpectedSchema>;
export const unloadingCostCorrectionResultSchema=unloadingCostCorrectionExpectedSchema.extend({version:z.literal(1),tenant_id:uuid,actor_id:uuid,request_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid,amendment_id:uuid,confirmed:z.literal(true),cash_changed:z.literal(false),collection_changed:z.literal(false)}).strict();
export function parseUnloadingCostCorrectionResult(value:unknown,command:UnloadingCostCorrectionCommand,actor:string,expected:UnloadingCostCorrectionExpected){const result=unloadingCostCorrectionResultSchema.parse(value);if(result.tenant_id!==command.tenant_id||result.actor_id!==actor||result.request_id!==command.request_id||result.charge_id!==command.charge_id||result.expense_id!==command.expense_id||result.payable_id!==command.payable_id||result.cost_after_cents!==command.amount_cents||result.obligation_after_cents!==command.amount_cents||Object.entries(expected).some(([key,value])=>result[key as keyof typeof result]!==value))throw Error('Resposta incompatível com a correção de custo preservada.');return result;}
import {unloadingEffectiveOriginSchema} from './unloadingOriginCorrectionContract';
export const unloadingCostCorrectionPreviewSchema=z.object({version:z.literal(1),tenant_id:uuid,actor_id:uuid,charge_id:uuid,expense_id:uuid,payable_id:uuid,cost:expenseCostOriginSchema,collection:unloadingEffectiveOriginSchema,payable:z.object({original_amount_cents:cents.nullable(),amount_cents:cents.nullable(),status:z.string(),beneficiary_id:uuid.nullable(),beneficiary_name:z.string().nullable()}).strict(),target:z.object({amount_cents:cents,payable_amount_cents:cents,payable_status:z.literal('pending')}).strict(),approval_reset:z.boolean(),blockers:z.array(z.object({code:z.string(),source_table:z.string().nullable(),source_ids:z.array(uuid)}).strict()),eligible:z.boolean(),can_correct:z.boolean(),can_execute:z.boolean(),revision,effects:z.object({computation:z.literal('prospective_cost_correction'),cost_before_cents:cents.nullable(),cost_after_cents:cents,cost_delta_cents:z.string().regex(/^-?\d+$/).nullable(),obligation_before_cents:cents.nullable(),obligation_after_cents:cents,cash_changed:z.literal(false),collection_changed:z.literal(false),approval_reset:z.boolean()}).strict()}).strict().superRefine((v,c)=>{
 const fail=(message:string)=>c.addIssue({code:'custom',message});
 if(v.cost.tenant_id!==v.tenant_id||v.cost.expense_id!==v.expense_id||v.cost.charge_id!==v.charge_id||v.cost.payable_id!==v.payable_id||v.collection.tenant_id!==v.tenant_id||v.collection.charge_id!==v.charge_id)fail('Fontes fora da correção solicitada.');
 if(v.target.amount_cents!==v.target.payable_amount_cents||v.effects.cost_after_cents!==v.target.amount_cents||v.effects.obligation_after_cents!==v.target.payable_amount_cents||v.effects.approval_reset!==v.approval_reset)fail('Efeitos diferentes da proposta.');
 if(v.effects.cost_before_cents!==v.cost.effective_amount_cents||v.effects.obligation_before_cents!==v.payable.amount_cents)fail('Valores anteriores diferentes da conferência.');
 const calculable=v.effects.cost_before_cents!==null&&/^[1-9]\d{0,13}$/.test(v.effects.cost_before_cents)&&/^[1-9]\d{0,13}$/.test(v.effects.cost_after_cents)&&(v.effects.cost_delta_cents===null||/^-?\d+$/.test(v.effects.cost_delta_cents));
 if(calculable&&v.effects.cost_before_cents!==null&&(v.effects.cost_delta_cents===null||BigInt(v.effects.cost_after_cents)-BigInt(v.effects.cost_before_cents)!==BigInt(v.effects.cost_delta_cents)))fail('Diferença de custo incompatível.');
 if(v.effects.cost_before_cents===null&&v.effects.cost_delta_cents!==null)fail('Diferença determinada sem custo anterior.');
 if(v.eligible&&(v.blockers.length||!v.cost.verified||!v.collection.verified||v.cost.effective_amount_cents===null||v.payable.amount_cents===null||v.cost.effective_amount_cents===v.target.amount_cents||!['pending','approved'].includes(v.payable.status)||v.approval_reset!==(v.payable.status==='approved')))fail('Correção elegível sem evidências completas.');
 if(v.can_execute&&(!v.can_correct||!v.eligible))fail('Execução sem permissão e elegibilidade.');
});
export type UnloadingCostCorrectionPreview=z.infer<typeof unloadingCostCorrectionPreviewSchema>;
