
ALTER TABLE public.drivers
  ADD COLUMN IF NOT EXISTS driver_type text NOT NULL DEFAULT 'proprio',
  ADD COLUMN IF NOT EXISTS sigla text,
  ADD COLUMN IF NOT EXISTS registration_date date,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS supplier text,
  ADD COLUMN IF NOT EXISTS contact text,
  ADD COLUMN IF NOT EXISTS cpf text,
  ADD COLUMN IF NOT EXISTS cnh_number text,
  ADD COLUMN IF NOT EXISTS cnh_category text,
  ADD COLUMN IF NOT EXISTS cnh_expiry date,
  ADD COLUMN IF NOT EXISTS birth_date date,
  ADD COLUMN IF NOT EXISTS naturalidade text,
  ADD COLUMN IF NOT EXISTS naturalidade_uf text,
  ADD COLUMN IF NOT EXISTS nacionalidade text DEFAULT 'BRASILEIRO',
  ADD COLUMN IF NOT EXISTS sex text,
  ADD COLUMN IF NOT EXISTS skin_color text,
  ADD COLUMN IF NOT EXISTS eye_color text,
  ADD COLUMN IF NOT EXISTS hair_color text,
  ADD COLUMN IF NOT EXISTS distinguishing_marks text,
  ADD COLUMN IF NOT EXISTS weight_kg numeric,
  ADD COLUMN IF NOT EXISTS height_m numeric,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS spouse_name text,
  ADD COLUMN IF NOT EXISTS education text,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS mother_name text,
  ADD COLUMN IF NOT EXISTS phone_secondary text,
  ADD COLUMN IF NOT EXISTS mobile text,
  ADD COLUMN IF NOT EXISTS fleet_type text,
  ADD COLUMN IF NOT EXISTS driver_kind_code text,
  ADD COLUMN IF NOT EXISTS address_street text,
  ADD COLUMN IF NOT EXISTS address_number text,
  ADD COLUMN IF NOT EXISTS address_complement text,
  ADD COLUMN IF NOT EXISTS address_neighborhood text,
  ADD COLUMN IF NOT EXISTS address_city text,
  ADD COLUMN IF NOT EXISTS address_state text,
  ADD COLUMN IF NOT EXISTS address_zip text,
  ADD COLUMN IF NOT EXISTS residence_type text,
  ADD COLUMN IF NOT EXISTS residence_since date,
  ADD COLUMN IF NOT EXISTS prev_address_street text,
  ADD COLUMN IF NOT EXISTS prev_address_number text,
  ADD COLUMN IF NOT EXISTS prev_address_complement text,
  ADD COLUMN IF NOT EXISTS prev_address_neighborhood text,
  ADD COLUMN IF NOT EXISTS prev_address_city text,
  ADD COLUMN IF NOT EXISTS prev_address_state text,
  ADD COLUMN IF NOT EXISTS prev_address_zip text,
  ADD COLUMN IF NOT EXISTS prev_residence_type text,
  ADD COLUMN IF NOT EXISTS prev_residence_duration text,
  ADD COLUMN IF NOT EXISTS emit_contract boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS blocked boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS commissioned boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS mechanic boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS romaneio_monitor_responsible boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS notes text;
