-- Migration originalmente composta apenas de DML (dados de um tenant específico).
-- O conteúdo foi movido para scripts/ops/seeds/20260310162234_dafe78a2-1c07-4fb3-af78-e2dc729b38ea.sql
-- para manter o histórico de migrations reprodutível desde schema vazio.
-- Nenhuma mudança de schema: intencionalmente sem instruções.
