-- Migration originalmente composta apenas de DML (dados de um tenant específico).
-- O conteúdo foi movido para scripts/ops/seeds/20260603191710_63219c6f-483c-4fd2-9bef-6dfb428fcccf.sql
-- para manter o histórico de migrations reprodutível desde schema vazio.
-- Nenhuma mudança de schema: intencionalmente sem instruções.
