-- Links an existing real incoming movement to the unused balance of one driver
-- advance. The original outgoing movement and expense categories remain intact.
set lock_timeout='3s';set statement_timeout='30s';
do $pins$declare spec record;p record;body text;begin
 for spec in select * from(values
  ('finance_private.movement_used_cents(uuid,uuid)',array['cc216802448c49d665d2b5d2e2335415','a64a5e2f0ea0fdec562c4baa81b58fd4']::text[],'movement_used_before_driver_returns'),
  ('finance_private.receipt_movement_used_cents(uuid,uuid)',array['09ac7f454ff10e20328534f3c2dd236e']::text[],'receipt_movement_used_before_driver_returns')
)v(signature,hashes,alias) loop
  select * into p from pg_proc where oid=to_regprocedure(spec.signature);
  if p.oid is null or not(md5(replace(p.prosrc,E'\r\n',E'\n'))=any(spec.hashes)) or not p.prosecdef or p.provolatile<>'s' or p.proconfig is distinct from array['search_path=""']::text[] or exists(select 1 from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where a.grantee<>p.proowner) then raise exception 'finance_driver_advance_return_predecessor_changed:%',spec.signature using errcode='55000';end if;
  body:=pg_get_functiondef(p.oid);body:=replace(body,'FUNCTION finance_private.'||p.proname||'(','FUNCTION finance_private.'||spec.alias||'(');execute body;
 end loop;
end$pins$;
revoke all on function finance_private.movement_used_before_driver_returns(uuid,uuid),finance_private.receipt_movement_used_before_driver_returns(uuid,uuid) from public,anon,authenticated,service_role;

create table finance_private.driver_advance_returns(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),advance_movement_id uuid not null,incoming_movement_id uuid not null,
 amount_cents bigint not null check(amount_cents between 1 and 99999999999999),request_id uuid not null,actor_id uuid not null,actor_name text not null,
 reason text not null check(length(btrim(reason)) between 10 and 2000),source_snapshot jsonb not null,result jsonb not null,created_at timestamptz not null default clock_timestamp(),
 unique(tenant_id,request_id),foreign key(tenant_id,advance_movement_id) references public.finance_movements(tenant_id,id),foreign key(tenant_id,incoming_movement_id) references public.finance_movements(tenant_id,id)
);
create index driver_advance_returns_advance on finance_private.driver_advance_returns(tenant_id,advance_movement_id,created_at,id);
create index driver_advance_returns_incoming on finance_private.driver_advance_returns(tenant_id,incoming_movement_id,id);
alter table finance_private.driver_advance_returns enable row level security;revoke all on finance_private.driver_advance_returns from public,anon,authenticated,service_role;
create trigger preserve_driver_advance_return before update or delete on finance_private.driver_advance_returns for each row execute function finance_private.preserve_event();

create or replace function finance_private.movement_used_cents(_tenant uuid,_movement uuid) returns numeric language sql stable security definer set search_path='' as $$
 select finance_private.movement_used_before_driver_returns(_tenant,_movement)+coalesce((select sum(amount_cents) from finance_private.driver_advance_returns where tenant_id=_tenant and advance_movement_id=_movement),0)
$$;
create or replace function finance_private.receipt_movement_used_cents(_tenant uuid,_movement uuid) returns numeric language sql stable security definer set search_path='' as $$
 select finance_private.receipt_movement_used_before_driver_returns(_tenant,_movement)+coalesce((select sum(amount_cents) from finance_private.driver_advance_returns where tenant_id=_tenant and incoming_movement_id=_movement),0)
$$;
revoke all on function finance_private.movement_used_cents(uuid,uuid),finance_private.receipt_movement_used_cents(uuid,uuid) from public,anon,authenticated,service_role;

create function finance_private.driver_advance_position(_tenant uuid,_advance uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare a public.finance_movements%rowtype;r finance_private.driver_advance_returns%rowtype;i public.finance_movements%rowtype;allocated numeric;returned numeric:=0;valid boolean:=true;issue text;history jsonb:='[]';result jsonb;begin
 perform finance_private.require_access(_tenant);select * into a from public.finance_movements where tenant_id=_tenant and id=_advance;
 if a.id is null or a.direction<>'out' or a.nature<>'driver_advance' or a.driver_id is null then raise exception 'finance_driver_advance_not_found' using errcode='22023';end if;
 allocated:=finance_private.movement_used_before_driver_returns(_tenant,_advance);
 if allocated<0 or allocated<>trunc(allocated) or allocated>a.amount_cents or not exists(select 1 from finance_private.active_movements where tenant_id=_tenant and id=a.id) then valid:=false;issue:='finance_driver_advance_source_unverified';end if;
 for r in select * from finance_private.driver_advance_returns where tenant_id=_tenant and advance_movement_id=_advance order by created_at,id loop
  select * into i from public.finance_movements where tenant_id=_tenant and id=r.incoming_movement_id;
  if i.id is null or i.direction<>'in' or i.nature not in('refund','receipt','other') or i.driver_id is distinct from a.driver_id or i.occurred_on<a.occurred_on or to_jsonb(a) is distinct from r.source_snapshot->'advance' or to_jsonb(i) is distinct from r.source_snapshot->'incoming' or not exists(select 1 from finance_private.active_movements where tenant_id=_tenant and id=i.id) or not exists(select 1 from public.finance_events e where e.tenant_id=_tenant and e.entity_type='driver_advance' and e.entity_id=_advance and e.action='driver_advance_return_recorded' and e.actor_id=r.actor_id and e.after_data=r.result) then valid:=false;issue:='finance_driver_advance_return_chain_unverified';end if;
  returned:=returned+r.amount_cents;history:=history||jsonb_build_array(jsonb_build_object('return_id',r.id,'incoming_movement_id',r.incoming_movement_id,'amount_cents',r.amount_cents::text,'actor_id',r.actor_id,'actor_name',r.actor_name,'reason',r.reason,'created_at',r.created_at,'occurred_on',i.occurred_on,'bank_account_id',i.bank_account_id));
 end loop;
 if allocated+returned>a.amount_cents then valid:=false;issue:='finance_driver_advance_return_capacity_invalid';end if;
 result:=jsonb_build_object('version',1,'tenant_id',_tenant,'actor_id',auth.uid(),'movement_id',a.id,'driver_id',a.driver_id,'bank_account_id',a.bank_account_id,'occurred_on',a.occurred_on,'amount_cents',a.amount_cents::text,'allocated_cents',case when valid then trunc(allocated)::text end,'returned_cents',case when valid then trunc(returned)::text end,'open_cents',case when valid then trunc(a.amount_cents-allocated-returned)::text end,'verified',valid,'issue',issue,'history',history);
 return result||jsonb_build_object('revision',md5(result::text));
end$$;
revoke all on function finance_private.driver_advance_position(uuid,uuid) from public,anon,authenticated,service_role;

create function finance_private.driver_advance_return_context(_tenant uuid,_advance uuid,_incoming uuid,_amount text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare p jsonb;i public.finance_movements%rowtype;used numeric;amount bigint;blockers jsonb:='[]';result jsonb;begin
 perform finance_private.require_access(_tenant);if coalesce(_amount,'')!~'^[1-9][0-9]{0,13}$' then raise exception 'finance_driver_advance_return_amount_invalid' using errcode='22023';end if;amount:=_amount::bigint;p:=finance_private.driver_advance_position(_tenant,_advance);
 select * into i from public.finance_movements where tenant_id=_tenant and id=_incoming;if not found then raise exception 'finance_driver_advance_return_movement_missing' using errcode='22023';end if;used:=finance_private.receipt_movement_used_cents(_tenant,_incoming);
 if p->'verified' is distinct from 'true'::jsonb then blockers:=blockers||jsonb_build_array('finance_driver_advance_source_unverified');end if;
 if amount>coalesce((p->>'open_cents')::numeric,-1) then blockers:=blockers||jsonb_build_array('finance_driver_advance_return_exceeds_open');end if;
 if i.direction<>'in' or i.nature not in('refund','receipt','other') or i.driver_id::text is distinct from p->>'driver_id' or i.occurred_on<(p->>'occurred_on')::date or not exists(select 1 from finance_private.active_movements where tenant_id=_tenant and id=i.id) then blockers:=blockers||jsonb_build_array('finance_driver_advance_return_movement_incompatible');end if;
 if used<0 or used<>trunc(used) or used+amount>i.amount_cents then blockers:=blockers||jsonb_build_array('finance_driver_advance_return_incoming_capacity_exceeded');end if;
 if not exists(select 1 from public.finance_commands c where c.tenant_id=_tenant and c.action='record_movement' and c.actor_id=i.created_by and c.result->>'movement_id'=i.id::text) then blockers:=blockers||jsonb_build_array('finance_driver_advance_return_recording_unverified');end if;
 begin perform finance_private.assert_closed_source_mutable(_tenant,'finance_movements',(select to_jsonb(m) from public.finance_movements m where m.id=_advance));perform finance_private.assert_closed_source_mutable(_tenant,'finance_movements',to_jsonb(i));exception when sqlstate '55000' then blockers:=blockers||jsonb_build_array('finance_driver_advance_return_period_closed');end;
 result:=jsonb_build_object('version',1,'tenant_id',_tenant,'actor_id',auth.uid(),'advance_movement_id',_advance,'incoming_movement_id',_incoming,'amount_cents',_amount,'position',p,'incoming',jsonb_build_object('movement_id',i.id,'bank_account_id',i.bank_account_id,'occurred_on',i.occurred_on,'amount_cents',i.amount_cents::text,'used_cents',trunc(used)::text,'available_cents',trunc(i.amount_cents-used)::text,'counterparty_name',i.beneficiary_name),'effects',jsonb_build_object('open_before_cents',p->>'open_cents','open_after_cents',case when blockers='[]'::jsonb then ((p->>'open_cents')::numeric-amount)::text end,'cash_created',false,'expense_created',false,'original_movement_changed',false),'eligible',blockers='[]'::jsonb,'can_execute',false,'blockers',blockers);
 return result||jsonb_build_object('revision',md5(result::text));
end$$;
revoke all on function finance_private.driver_advance_return_context(uuid,uuid,uuid,text) from public,anon,authenticated,service_role;

create function finance_private.record_driver_advance_return(_payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare t uuid;actor uuid:=auth.uid();request uuid;advance uuid;incoming uuid;ctx jsonb;existing public.finance_commands%rowtype;old finance_private.driver_advance_returns%rowtype;new_id uuid:=gen_random_uuid();name text;result_value jsonb;begin
 if jsonb_typeof(_payload) is distinct from 'object' then raise exception 'finance_driver_advance_return_invalid' using errcode='22023';end if;
 t:=(_payload->>'tenant_id')::uuid;request:=(_payload->>'request_id')::uuid;advance:=(_payload->>'advance_movement_id')::uuid;incoming:=(_payload->>'incoming_movement_id')::uuid;perform finance_private.require_access(t);
 if request is null or advance is null or incoming is null or _payload->>'version' is distinct from '1' or coalesce(_payload->>'amount_cents','')!~'^[1-9][0-9]{0,13}$' or coalesce(_payload->>'expected_revision','')!~'^[a-f0-9]{32}$' or length(btrim(coalesce(_payload->>'reason',''))) not between 10 and 2000 or exists(select 1 from jsonb_object_keys(_payload)k where k<>all(array['version','tenant_id','request_id','advance_movement_id','incoming_movement_id','amount_cents','expected_revision','reason'])) then raise exception 'finance_driver_advance_return_invalid' using errcode='22023';end if;
 perform pg_advisory_xact_lock(hashtextextended(t::text||':finance',0));perform 1 from public.tenant_memberships where tenant_id=t and user_id=actor order by role::text for share nowait;perform 1 from public.drivers where tenant_id=t and user_id=actor order by id for share nowait;perform finance_private.require_access(t);
 select * into existing from public.finance_commands where tenant_id=t and request_id=request;if found then if existing.actor_id<>actor or existing.action<>'record_driver_advance_return' or existing.payload<>_payload then raise exception 'finance_request_conflict' using errcode='23505';end if;return existing.result;end if;
 select * into old from finance_private.driver_advance_returns where tenant_id=t and request_id=request;if found then raise exception 'finance_driver_advance_return_command_missing' using errcode='55000';end if;
 perform 1 from public.finance_movements where tenant_id=t and id=advance for update nowait;perform 1 from public.finance_movements where tenant_id=t and id=incoming for update nowait;
 ctx:=finance_private.driver_advance_return_context(t,advance,incoming,_payload->>'amount_cents');if ctx->>'revision' is distinct from _payload->>'expected_revision' then raise exception 'finance_driver_advance_return_changed' using errcode='40001';end if;if ctx->>'eligible' is distinct from 'true' then raise exception 'finance_driver_advance_return_blocked' using errcode='55000';end if;
 select coalesce(nullif(raw_user_meta_data->>'full_name',''),email,actor::text) into name from auth.users where id=actor;
 result_value:=jsonb_build_object('version',1,'confirmed',true,'tenant_id',t,'actor_id',actor,'request_id',request,'return_id',new_id,'advance_movement_id',advance,'incoming_movement_id',incoming,'amount_cents',_payload->>'amount_cents','cash_created',false,'expense_created',false,'open_cents',ctx#>>'{effects,open_after_cents}');
 insert into finance_private.driver_advance_returns(id,tenant_id,advance_movement_id,incoming_movement_id,amount_cents,request_id,actor_id,actor_name,reason,source_snapshot,result) values(new_id,t,advance,incoming,(_payload->>'amount_cents')::bigint,request,actor,coalesce(name,actor::text),btrim(_payload->>'reason'),jsonb_build_object('advance',(select to_jsonb(m) from public.finance_movements m where m.tenant_id=t and m.id=advance),'incoming',(select to_jsonb(m) from public.finance_movements m where m.tenant_id=t and m.id=incoming)),result_value);
 insert into public.finance_events(tenant_id,entity_type,entity_id,action,actor_id,actor_name,reason,before_data,after_data) values(t,'driver_advance',advance,'driver_advance_return_recorded',actor,coalesce(name,actor::text),btrim(_payload->>'reason'),ctx,result_value);
 insert into public.finance_commands(tenant_id,request_id,actor_id,action,payload,result) values(t,request,actor,'record_driver_advance_return',_payload,result_value);
 if finance_private.driver_advance_position(t,advance)->'verified' is distinct from 'true'::jsonb then raise exception 'finance_driver_advance_return_chain_invalid' using errcode='23514';end if;return result_value;
exception when lock_not_available then raise exception 'finance_driver_advance_return_busy' using errcode='40001';end$$;
revoke all on function finance_private.record_driver_advance_return(jsonb) from public,anon,authenticated,service_role;

create function finance_private.guard_driver_advance_return() returns trigger language plpgsql security definer set search_path='' as $$
declare a public.finance_movements%rowtype;i public.finance_movements%rowtype;begin
 if tg_table_name='finance_movement_voids' then if exists(select 1 from finance_private.driver_advance_returns where tenant_id=new.tenant_id and(new.movement_id=advance_movement_id or new.movement_id=incoming_movement_id)) then raise exception 'finance_driver_advance_return_movement_protected' using errcode='55000';end if;return new;end if;
 select * into a from public.finance_movements where tenant_id=new.tenant_id and id=new.advance_movement_id for update nowait;select * into i from public.finance_movements where tenant_id=new.tenant_id and id=new.incoming_movement_id for update nowait;
 if a.id is null or a.direction<>'out' or a.nature<>'driver_advance' or a.driver_id is null or i.id is null or i.direction<>'in' or i.nature not in('refund','receipt','other') or i.driver_id is distinct from a.driver_id or i.occurred_on<a.occurred_on or not exists(select 1 from finance_private.active_movements where tenant_id=new.tenant_id and id=a.id) or not exists(select 1 from finance_private.active_movements where tenant_id=new.tenant_id and id=i.id) then raise exception 'finance_driver_advance_return_source_invalid' using errcode='23514';end if;
 if finance_private.movement_used_cents(new.tenant_id,a.id)+new.amount_cents>a.amount_cents or finance_private.receipt_movement_used_cents(new.tenant_id,i.id)+new.amount_cents>i.amount_cents then raise exception 'finance_driver_advance_return_capacity_exceeded' using errcode='23514';end if;
 perform finance_private.assert_closed_source_mutable(new.tenant_id,'finance_movements',to_jsonb(a));perform finance_private.assert_closed_source_mutable(new.tenant_id,'finance_movements',to_jsonb(i));return new;
exception when lock_not_available then raise exception 'finance_driver_advance_return_busy' using errcode='40001';end$$;
revoke all on function finance_private.guard_driver_advance_return() from public,anon,authenticated,service_role;
create trigger driver_advance_return_capacity before insert on finance_private.driver_advance_returns for each row execute function finance_private.guard_driver_advance_return();
create trigger a_driver_advance_return_void before insert on public.finance_movement_voids for each row execute function finance_private.guard_driver_advance_return();

create function finance_private.driver_advance_positions(_tenant uuid,_page integer default 1) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare rows jsonb:='[]';r record;p jsonb;total integer;revision text;begin perform finance_private.require_access(_tenant);if _page is null or _page not between 1 and 1000000 then raise exception 'finance_invalid_page' using errcode='22023';end if;
 for r in select m.id,b.name account_name,coalesce(d.name,m.beneficiary_name) driver_name from finance_private.active_movements m join public.bank_accounts b on b.tenant_id=m.tenant_id and b.id=m.bank_account_id left join public.drivers d on d.tenant_id=m.tenant_id and d.id=m.driver_id where m.tenant_id=_tenant and m.direction='out' and m.nature='driver_advance' order by m.occurred_on desc,m.id loop p:=finance_private.driver_advance_position(_tenant,r.id);rows:=rows||jsonb_build_array(p||jsonb_build_object('account_name',r.account_name,'driver_name',r.driver_name,'history_count',jsonb_array_length(p->'history')));end loop;
 total:=jsonb_array_length(rows);revision:=md5(rows::text);return jsonb_build_object('version',1,'tenant_id',_tenant,'actor_id',auth.uid(),'page',_page,'page_size',30,'total',total,'revision',revision,'rows',(select coalesce(jsonb_agg(value order by ordinal),'[]') from jsonb_array_elements(rows) with ordinality x(value,ordinal) where ordinal>(_page-1)*30 and ordinal<=_page*30));end$$;

create function finance_private.driver_advance_return_options(_tenant uuid,_advance uuid,_search text,_page integer,_expected_revision text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare p jsonb;rows jsonb;total integer;revision text;begin perform finance_private.require_access(_tenant);if _page is null or _page not between 1 and 1000000 or length(coalesce(_search,''))>200 or(_page>1 and _expected_revision is null) or(_expected_revision is not null and _expected_revision!~'^[a-f0-9]{32}$') then raise exception 'finance_invalid_page' using errcode='22023';end if;p:=finance_private.driver_advance_position(_tenant,_advance);
 with candidates as materialized(select m.id,m.bank_account_id,b.name bank_account_name,m.occurred_on,m.beneficiary_name,m.description,m.amount_cents,finance_private.receipt_movement_used_cents(_tenant,m.id) used from finance_private.active_movements m join public.bank_accounts b on b.tenant_id=m.tenant_id and b.id=m.bank_account_id where m.tenant_id=_tenant and m.direction='in' and m.nature in('refund','receipt','other') and m.driver_id=(p->>'driver_id')::uuid and m.occurred_on>=(p->>'occurred_on')::date and(coalesce(btrim(_search),'')='' or strpos(lower(concat_ws(' ',m.description,m.beneficiary_name,b.name)),lower(btrim(_search)))>0)),available as materialized(select id,bank_account_id,bank_account_name,occurred_on,beneficiary_name,description,amount_cents::text amount_cents,trunc(used)::text used_cents,trunc(amount_cents-used)::text available_cents from candidates where used>=0 and used=trunc(used) and used<amount_cents),meta as(select count(*) total,md5((p->>'revision')||coalesce(_search,'')||coalesce(string_agg(md5(to_jsonb(a)::text),'' order by occurred_on desc,id),'')) revision from available a),paged as(select * from available order by occurred_on desc,id limit 30 offset (_page-1)*30) select coalesce((select jsonb_agg(to_jsonb(x) order by occurred_on desc,id) from paged x),'[]'),meta.total,meta.revision into rows,total,revision from meta;
 if _expected_revision is not null and _expected_revision is distinct from revision then raise exception 'finance_driver_advance_return_options_changed' using errcode='40001';end if;return jsonb_build_object('version',1,'tenant_id',_tenant,'actor_id',auth.uid(),'advance_movement_id',_advance,'search',coalesce(_search,''),'page',_page,'page_size',30,'total',total,'revision',revision,'rows',rows);end$$;

create function finance_private.dispatch_driver_advance_return(_payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$begin perform finance_private.require_access((_payload->>'tenant_id')::uuid);return finance_private.record_driver_advance_return(_payload);end$$;
create function public.get_finance_driver_advance_positions(_tenant_id uuid,_page integer default 1) returns jsonb language sql stable security invoker set search_path='' as $$select finance_private.driver_advance_positions(_tenant_id,_page)$$;
create function public.get_finance_driver_advance_return_options(_tenant_id uuid,_advance_movement_id uuid,_search text default '',_page integer default 1,_expected_revision text default null) returns jsonb language sql stable security invoker set search_path='' as $$select finance_private.driver_advance_return_options(_tenant_id,_advance_movement_id,_search,_page,_expected_revision)$$;
create function public.preview_finance_driver_advance_return(_tenant_id uuid,_advance_movement_id uuid,_incoming_movement_id uuid,_amount_cents text) returns jsonb language plpgsql stable security invoker set search_path='' as $$declare v jsonb;begin v:=finance_private.driver_advance_return_context(_tenant_id,_advance_movement_id,_incoming_movement_id,_amount_cents);return v||jsonb_build_object('can_execute',v->'eligible'='true'::jsonb and has_function_privilege('authenticated','public.record_finance_driver_advance_return(jsonb)','execute'));end$$;
create function public.record_finance_driver_advance_return(_payload jsonb) returns jsonb language sql security invoker set search_path='' as $$select finance_private.dispatch_driver_advance_return(_payload)$$;
revoke all on function finance_private.driver_advance_positions(uuid,integer),finance_private.driver_advance_return_options(uuid,uuid,text,integer,text),finance_private.dispatch_driver_advance_return(jsonb),public.get_finance_driver_advance_positions(uuid,integer),public.get_finance_driver_advance_return_options(uuid,uuid,text,integer,text),public.preview_finance_driver_advance_return(uuid,uuid,uuid,text),public.record_finance_driver_advance_return(jsonb) from public,anon,authenticated,service_role;
grant execute on function finance_private.driver_advance_return_context(uuid,uuid,uuid,text),finance_private.driver_advance_positions(uuid,integer),finance_private.driver_advance_return_options(uuid,uuid,text,integer,text),finance_private.dispatch_driver_advance_return(jsonb),public.get_finance_driver_advance_positions(uuid,integer),public.get_finance_driver_advance_return_options(uuid,uuid,text,integer,text),public.preview_finance_driver_advance_return(uuid,uuid,uuid,text),public.record_finance_driver_advance_return(jsonb) to authenticated;
