create function finance_private.package_uuid(_value text) returns uuid language plpgsql immutable strict set search_path='' as $$begin return _value::uuid;exception when invalid_text_representation then return null;end$$;
create function finance_private.package_day(_value text) returns date language plpgsql immutable strict set search_path='' as $$begin return case when isfinite(_value::date) then _value::date end;exception when invalid_datetime_format or datetime_field_overflow then return null;end$$;
revoke all on function finance_private.package_uuid(text),finance_private.package_day(text) from public,anon,authenticated,service_role;
-- Frozen monetary evidence only. No current commercial portfolio or DRE.
create function finance_private.package_cents(_value text) returns numeric language sql immutable strict set search_path='' as $$select case when _value ~ '^-?[0-9]{1,40}$' then _value::numeric end$$;
revoke all on function finance_private.package_cents(text) from public,anon,authenticated,service_role;
create function finance_private.period_money_account(_tenant uuid,_account uuid,_from date,_to date) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare a public.bank_accounts%rowtype;c public.finance_account_period_closures%rowtype;ev jsonb;s jsonb;b jsonb;cl jsonb:='[]';issues text[]:='{}';transfer_issues text[]:='{}';facts jsonb:='[]';pairs jsonb:='[]';departures jsonb:='[]';day_cursor date:=_from;previous_id uuid;previous_opening uuid;initial numeric;ending numeric;ins numeric:=0;outs numeric:=0;op numeric;ci numeric;co numeric;ce numeric;fi numeric;fo numeric;part_valid boolean;active boolean;kind text;selected_count integer:=0;ids jsonb;begin
 select * into a from public.bank_accounts where tenant_id=_tenant and id=_account;
 kind:=case when a.account_type='cash' then 'cash' when a.account_type in('checking','savings') then 'bank' else 'unsupported' end;
 if kind='unsupported' then issues:=array_append(issues,'unsupported_account_type');end if;
 for c in select * from public.finance_account_period_closures where tenant_id=_tenant and account_id=_account and period_start<=_to and period_end>=_from order by period_start,period_end,id loop
 ev:=finance_private.account_period_closure_evidence(_tenant,_account,c.id);s:=ev->'snapshot';b:=s->'balances';active:=ev->'reopening'='null'::jsonb;
 cl:=cl||jsonb_build_array(jsonb_build_object('id',c.id,'from',c.period_start,'to',c.period_end,'revision',c.snapshot_revision,'active',active,'evidence_kind',case when s->>'evidence_type'='cash_count_v1' then 'cash_count' when s ? 'coverage' then 'bank_statement' else 'unknown' end,'opening_id',c.opening_id,'predecessor_id',c.predecessor_id,'coverage_approval_id',s#>'{coverage,approval,id}','count_id',s#>'{count,id}','actor_id',c.actor_id,'actor_name',c.actor_name,'reason',c.reason,'created_at',c.created_at,'integrity',ev->'integrity','reopening',ev->'reopening'));
 if not active then continue;end if;selected_count:=selected_count+1;
 part_valid:=coalesce((ev#>>'{integrity,snapshot_matches_revision}')::boolean,false) and coalesce((ev#>>'{integrity,dependencies_match}')::boolean,false);
 if not part_valid then issues:=array_append(issues,'closure_integrity_invalid');end if;
 if c.period_start< _from or c.period_end>_to then issues:=array_append(issues,'closure_crosses_requested_boundary');continue;end if;
 if c.period_start<>day_cursor then issues:=array_append(issues,'closure_gap_or_overlap');end if;day_cursor:=c.period_end+1;
 if s->>'tenant_id' is distinct from _tenant::text or s->>'account_id' is distinct from _account::text or s->>'from' is distinct from c.period_start::text or s->>'to' is distinct from c.period_end::text or s->>'currency' is distinct from 'BRL' or s->>'timezone' is distinct from 'America/Sao_Paulo' or s->'eligible' is distinct from 'true'::jsonb or s->'blockers' is distinct from '[]'::jsonb then issues:=array_append(issues,'closure_scope_or_proof_invalid');end if;
 op:=finance_private.package_cents(b->>'opening_cents');ce:=finance_private.package_cents(b->>'closing_cents');
 if kind='cash' then
 ci:=finance_private.package_cents(b->>'in_cents');co:=finance_private.package_cents(b->>'out_cents');
 if s->>'evidence_type' is distinct from 'cash_count_v1' or s#>>'{count,evidence_type}' is distinct from 'cash_count_v1' or s#>>'{count,account_id}' is distinct from _account::text or s#>>'{count,period_end}' is distinct from c.period_end::text or finance_private.package_cents(b->>'difference_cents') is distinct from 0 or finance_private.package_cents(b->>'counted_closing_cents') is distinct from ce or finance_private.package_cents(s#>>'{count,total_cents}') is distinct from ce then issues:=array_append(issues,'cash_count_proof_invalid');end if;
 else
 ci:=finance_private.package_cents(b->>'recorded_in_cents');co:=finance_private.package_cents(b->>'recorded_out_cents');
 if s#>>'{coverage,status}' is distinct from 'approved' or s#>'{coverage,current}' is distinct from 'true'::jsonb or s#>'{coverage,blocking_reasons}' is distinct from '[]'::jsonb or s#>>'{coverage,approval,id}' is null or finance_private.package_cents(b->>'bank_in_cents') is distinct from ci or finance_private.package_cents(b->>'bank_out_cents') is distinct from co then issues:=array_append(issues,'bank_coverage_proof_invalid');end if;
 end if;
 if op is null or ce is null or ci is null or co is null or ci<0 or co<0 or ce<>op+ci-co then issues:=array_append(issues,'closure_equation_invalid');end if;
 if previous_id is not null and (c.predecessor_id is distinct from previous_id or c.opening_id is distinct from previous_opening or op is distinct from ending) then issues:=array_append(issues,'closure_chain_discontinuous');end if;
 if selected_count=1 then initial:=op;end if;ending:=ce;ins:=ins+ci;outs:=outs+co;previous_id:=c.id;previous_opening:=c.opening_id;
 if jsonb_typeof(s#>'{facts,movements}') is distinct from 'array' then issues:=array_append(issues,'movement_manifest_missing');else
 select coalesce(sum(finance_private.package_cents(x->>'amount_cents')) filter(where x->>'direction'='in'),0),coalesce(sum(finance_private.package_cents(x->>'amount_cents')) filter(where x->>'direction'='out'),0) into fi,fo from jsonb_array_elements(s#>'{facts,movements}') x;
 if fi is distinct from ci or fo is distinct from co or exists(select 1 from jsonb_array_elements(s#>'{facts,movements}') x where x->>'tenant_id' is distinct from _tenant::text or x->>'bank_account_id' is distinct from _account::text or finance_private.package_uuid(x->>'id') is null or finance_private.package_day(x->>'occurred_on') is null or finance_private.package_day(x->>'occurred_on') not between c.period_start and c.period_end or x->>'direction' is null or x->>'direction' not in('in','out') or finance_private.package_cents(x->>'amount_cents') is null or finance_private.package_cents(x->>'amount_cents')<=0) then issues:=array_append(issues,'movement_manifest_invalid');end if;
 facts:=facts||(s#>'{facts,movements}');end if;
 if jsonb_typeof(s#>'{facts,transfers}')='array' then select pairs||coalesce(jsonb_agg(jsonb_build_object('closure_id',c.id,'row',x)),'[]') into pairs from jsonb_array_elements(s#>'{facts,transfers}') x;else transfer_issues:=array_append(transfer_issues,'transfer_manifest_invalid');end if;
 if jsonb_typeof(s#>'{facts,transfer_departures}')='array' then select departures||coalesce(jsonb_agg(jsonb_build_object('closure_id',c.id,'row',x)),'[]') into departures from jsonb_array_elements(s#>'{facts,transfer_departures}') x;else transfer_issues:=array_append(transfer_issues,'transfer_manifest_invalid');end if;
 end loop;
 if selected_count=0 or day_cursor<>_to+1 then issues:=array_append(issues,'closure_coverage_incomplete');end if;
 if exists(select 1 from jsonb_array_elements(facts) x group by x->>'id' having count(*)>1) then issues:=array_append(issues,'duplicate_movement_manifest');end if;
 select coalesce(jsonb_agg(distinct x->'id' order by x->'id'),'[]') into ids from jsonb_array_elements(facts) x where finance_private.package_uuid(x->>'id') is not null;
 select coalesce(array_agg(distinct x order by x),'{}') into issues from unnest(issues)x;
 return jsonb_build_object('account_id',_account,'name',coalesce(a.name,'Conta sem nome'),'account_kind',kind,'coverage_complete',cardinality(issues)=0,'issues',to_jsonb(issues),'balances',jsonb_build_object('opening_cents',case when cardinality(issues)=0 then initial::text end,'in_cents',case when cardinality(issues)=0 then ins::text end,'out_cents',case when cardinality(issues)=0 then outs::text end,'closing_cents',case when cardinality(issues)=0 then ending::text end),'closures',cl,'movement_ids',ids,'_facts',jsonb_build_object('transfer_issues',to_jsonb(transfer_issues),'movements',facts,'pairs',pairs,'departures',departures));
end$$;
revoke all on function finance_private.period_money_account(uuid,uuid,date,date) from public,anon,authenticated,service_role;

create function finance_private.period_money_package(_tenant uuid,_from date,_to date,_accounts uuid[]) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare selected uuid[];available jsonb;excluded jsonb;account uuid;row jsonb;accounts jsonb:='[]';movements jsonb:='[]';pairs jsonb:='[]';departures jsonb:='[]';transfers jsonb:='[]';issues text[]:='{}';valid boolean:=true;transfer_valid boolean:=true;op numeric:=0;ci numeric:=0;co numeric:=0;ce numeric:=0;eliminated numeric:=0;r record;tr jsonb;d jsonb;o public.finance_movements%rowtype;n public.finance_movements%rowtype;out_selected boolean;in_selected boolean;classification text;tr_issues text[];leg_ids uuid[]:='{}';seen_departures uuid[]:='{}';refs jsonb;amount numeric;result jsonb;kind text;begin
 if not finance_private.can_access(_tenant) then raise exception 'finance_access_denied' using errcode='42501';end if;
 if _from is null or _to is null or not isfinite(_from) or not isfinite(_to) or _from>_to or _accounts is null or array_ndims(_accounts)>1 or array_position(_accounts,null) is not null then raise exception 'finance_invalid_period_package_scope' using errcode='22023';end if;
 select coalesce(array_agg(distinct x order by x),'{}') into selected from unnest(_accounts)x;
 if cardinality(selected)<>cardinality(_accounts) then raise exception 'finance_duplicate_account_selection' using errcode='22023';end if;
 if exists(select 1 from unnest(selected)x where not exists(select 1 from public.bank_accounts where tenant_id=_tenant and id=x)) then raise exception 'finance_account_not_found' using errcode='22023';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'name',coalesce(a.name,'Conta sem nome'),'account_kind',case when a.account_type='cash' then 'cash' when a.account_type in('checking','savings') then 'bank' else 'unsupported' end,'account_type',a.account_type,'active',a.active) order by a.id),'[]'),coalesce(jsonb_agg(to_jsonb(a.id) order by a.id) filter(where not a.id=any(selected)),'[]') into available,excluded from public.bank_accounts a where tenant_id=_tenant;
 if cardinality(selected)=0 then valid:=false;issues:=array_append(issues,'account_selection_required');end if;
 if _to>=(statement_timestamp() at time zone 'America/Sao_Paulo')::date then valid:=false;issues:=array_append(issues,'period_not_ended');end if;
 foreach account in array selected loop
 row:=finance_private.period_money_account(_tenant,account,_from,_to);accounts:=accounts||jsonb_build_array(row-'_facts');
 if row->'coverage_complete' is distinct from 'true'::jsonb then valid:=false;issues:=array_append(issues,'account_coverage_incomplete');end if;
 op:=op+coalesce(finance_private.package_cents(row#>>'{balances,opening_cents}'),0);ci:=ci+coalesce(finance_private.package_cents(row#>>'{balances,in_cents}'),0);co:=co+coalesce(finance_private.package_cents(row#>>'{balances,out_cents}'),0);ce:=ce+coalesce(finance_private.package_cents(row#>>'{balances,closing_cents}'),0);
 if jsonb_array_length(row#>'{_facts,transfer_issues}')>0 then transfer_valid:=false;select issues||array_agg(x) into issues from jsonb_array_elements_text(row#>'{_facts,transfer_issues}')x;end if;
 movements:=movements||(row#>'{_facts,movements}');pairs:=pairs||(row#>'{_facts,pairs}');departures:=departures||(row#>'{_facts,departures}');
 end loop;
 if exists(select 1 from jsonb_array_elements(movements)x group by x->>'id' having count(*)>1) then valid:=false;issues:=array_append(issues,'duplicate_consolidated_movement');end if;
 -- Only immutable pair identities present in the selected closure snapshots are
 -- considered. A later current transfer does not rewrite a historical package.
 for r in select x#>>'{row,id}' id,jsonb_agg(x) versions from jsonb_array_elements(pairs)x group by x#>>'{row,id}' order by x#>>'{row,id}' loop
 tr:=r.versions->0->'row';if finance_private.package_uuid(tr->>'id') is null or finance_private.package_uuid(tr->>'outgoing_id') is null or finance_private.package_uuid(tr->>'incoming_id') is null then transfer_valid:=false;issues:=array_append(issues,'invalid_transfer_reference');continue;end if;out_selected:=exists(select 1 from jsonb_array_elements(movements)x where x->>'id'=tr->>'outgoing_id');in_selected:=exists(select 1 from jsonb_array_elements(movements)x where x->>'id'=tr->>'incoming_id');if not out_selected and not in_selected then continue;end if;
 tr_issues:='{}';select coalesce(jsonb_agg(distinct x->'closure_id'),'[]') into refs from jsonb_array_elements(r.versions)x;
 if (select count(distinct x->'row') from jsonb_array_elements(r.versions)x)>1 then tr_issues:=array_append(tr_issues,'transfer_snapshot_versions_conflict');end if;
 select * into o from public.finance_movements where tenant_id=_tenant and id=(tr->>'outgoing_id')::uuid;select * into n from public.finance_movements where tenant_id=_tenant and id=(tr->>'incoming_id')::uuid;
 amount:=o.amount_cents;
 if o.id is null or n.id is null or o.direction<>'out' or n.direction<>'in' or o.nature<>'transfer' or n.nature<>'transfer' or o.bank_account_id=n.bank_account_id or o.amount_cents<>n.amount_cents or n.occurred_on<o.occurred_on or tr->>'tenant_id' is distinct from _tenant::text then tr_issues:=array_append(tr_issues,'transfer_pair_identity_invalid');end if;
 if exists(select 1 from jsonb_array_elements(movements)x where x->>'id' in(o.id::text,n.id::text) and ((x->>'id'=o.id::text and (finance_private.package_cents(x->>'amount_cents') is distinct from o.amount_cents or x->>'bank_account_id' is distinct from o.bank_account_id::text or x->>'occurred_on' is distinct from o.occurred_on::text or x->>'direction' is distinct from o.direction or x->>'nature' is distinct from o.nature)) or (x->>'id'=n.id::text and (finance_private.package_cents(x->>'amount_cents') is distinct from n.amount_cents or x->>'bank_account_id' is distinct from n.bank_account_id::text or x->>'occurred_on' is distinct from n.occurred_on::text or x->>'direction' is distinct from n.direction or x->>'nature' is distinct from n.nature)))) then tr_issues:=array_append(tr_issues,'transfer_leg_snapshot_mismatch');end if;
 if o.id=any(leg_ids) or n.id=any(leg_ids) then tr_issues:=array_append(tr_issues,'transfer_leg_reused');end if;leg_ids:=array_remove(leg_ids||array[o.id,n.id],null);
 if exists(select 1 from public.finance_movement_voids where tenant_id=_tenant and movement_id in(o.id,n.id)) then tr_issues:=array_append(tr_issues,'transfer_leg_voided');end if;
 if cardinality(tr_issues)>0 then classification:='needs_review';transfer_valid:=false;
 elsif out_selected and in_selected then classification:='internal_pair';eliminated:=eliminated+amount;
 elsif not (o.occurred_on between _from and _to and n.occurred_on between _from and _to) then classification:='cross_period';
 elsif out_selected and not n.bank_account_id=any(selected) then classification:='scope_boundary_out';
 elsif in_selected and not o.bank_account_id=any(selected) then classification:='scope_boundary_in';
 else classification:='needs_review';tr_issues:=array_append(tr_issues,'selected_transfer_leg_not_covered');transfer_valid:=false;end if;
 transfers:=transfers||jsonb_build_array(jsonb_build_object('id',tr->>'id','kind','pair','outgoing_id',tr->>'outgoing_id','incoming_id',tr->>'incoming_id','source_account_id',o.bank_account_id,'destination_account_id',n.bank_account_id,'outgoing_on',o.occurred_on,'incoming_on',n.occurred_on,'amount_cents',amount::text,'classification',classification,'issues',to_jsonb(tr_issues),'source_closure_ids',refs));
 end loop;
 for r in select x#>>'{row,id}' id,jsonb_agg(x) versions from jsonb_array_elements(departures)x group by x#>>'{row,id}' order by x#>>'{row,id}' loop
 d:=r.versions->0->'row';if finance_private.package_uuid(d->>'id') is null or finance_private.package_uuid(d->>'outgoing_id') is null or finance_private.package_uuid(d->>'destination_account_id') is null then transfer_valid:=false;issues:=array_append(issues,'invalid_transfer_reference');continue;end if;if not exists(select 1 from jsonb_array_elements(movements)x where x->>'id'=d->>'outgoing_id') or exists(select 1 from jsonb_array_elements(transfers)x where x->>'outgoing_id'=d->>'outgoing_id') then continue;end if;
 select * into o from public.finance_movements where tenant_id=_tenant and id=(d->>'outgoing_id')::uuid;tr_issues:='{}';select coalesce(jsonb_agg(distinct x->'closure_id'),'[]') into refs from jsonb_array_elements(r.versions)x;
 if (select count(distinct x->'row') from jsonb_array_elements(r.versions)x)>1 or o.id is null or o.direction<>'out' or o.nature<>'transfer' or o.bank_account_id::text=d->>'destination_account_id' or d->>'tenant_id' is distinct from _tenant::text or not exists(select 1 from public.bank_accounts where tenant_id=_tenant and id=(d->>'destination_account_id')::uuid) then tr_issues:=array_append(tr_issues,'transfer_departure_identity_invalid');end if;
 if exists(select 1 from public.finance_movement_voids where tenant_id=_tenant and movement_id=o.id) then tr_issues:=array_append(tr_issues,'transfer_leg_voided');end if;
 if exists(select 1 from jsonb_array_elements(movements)x where x->>'id'=o.id::text and (finance_private.package_cents(x->>'amount_cents') is distinct from o.amount_cents or x->>'bank_account_id' is distinct from o.bank_account_id::text or x->>'occurred_on' is distinct from o.occurred_on::text or x->>'direction' is distinct from o.direction or x->>'nature' is distinct from o.nature)) then tr_issues:=array_append(tr_issues,'transfer_leg_snapshot_mismatch');end if;
 if o.id=any(leg_ids) then tr_issues:=array_append(tr_issues,'transfer_leg_reused');end if;leg_ids:=array_remove(leg_ids||array[o.id],null);
 if cardinality(tr_issues)>0 then classification:='needs_review';transfer_valid:=false;else classification:='in_transit';end if;
 transfers:=transfers||jsonb_build_array(jsonb_build_object('id',d->>'id','kind','departure','outgoing_id',d->>'outgoing_id','incoming_id',null,'source_account_id',o.bank_account_id,'destination_account_id',d->>'destination_account_id','outgoing_on',o.occurred_on,'incoming_on',null,'amount_cents',o.amount_cents::text,'classification',classification,'issues',to_jsonb(tr_issues),'source_closure_ids',refs));
 end loop;
 if exists(select 1 from jsonb_array_elements(movements)x where x->>'nature'='transfer' and not finance_private.package_uuid(x->>'id')=any(leg_ids)) then transfer_valid:=false;issues:=array_append(issues,'unclassified_transfer_movement');end if;
 if exists(select 1 from jsonb_array_elements(movements)x where x->>'nature' is null or x->>'nature' not in('driver_advance','payment','receipt','transfer','refund','customer_advance','other')) then transfer_valid:=false;issues:=array_append(issues,'invalid_movement_nature');end if;
 if not valid then transfer_valid:=false;end if;
 if not transfer_valid then issues:=array_append(issues,'transfer_classification_incomplete');end if;
 select coalesce(array_agg(distinct x order by x),'{}') into issues from unnest(issues)x;
 result:=jsonb_build_object('version',1,'tenant_id',_tenant,'currency','BRL','timezone','America/Sao_Paulo','basis','frozen_money','status_basis','current_closure_state','period',jsonb_build_object('from',_from,'to',_to),'account_scope',jsonb_build_object('selected_ids',to_jsonb(selected),'excluded_ids',excluded,'complete',cardinality(selected)>0 and jsonb_array_length(excluded)=0,'available',available),'accounts',accounts,'monetary_totals_valid',valid,'totals',jsonb_build_object('opening_cents',case when valid then op::text end,'in_cents',case when valid then ci::text end,'out_cents',case when valid then co::text end,'closing_cents',case when valid then ce::text end),'transfer_classification_valid',transfer_valid,'transfer_totals',jsonb_build_object('internal_pair_cents',case when transfer_valid then eliminated::text end,'in_excluding_internal_pairs_cents',case when transfer_valid then (ci-eliminated)::text end,'out_excluding_internal_pairs_cents',case when transfer_valid then (co-eliminated)::text end),'transfers',transfers,'issues',to_jsonb(issues),'limitations',jsonb_build_array('selected_accounts_only','frozen_money_not_commercial_as_of','not_a_profit_and_loss_statement','bank_and_book_are_not_added','transfer_classification_uses_frozen_identities'));
 return result||jsonb_build_object('revision',md5(result::text),'captured_at',statement_timestamp());
end$$;
revoke all on function finance_private.period_money_package(uuid,date,date,uuid[]) from public,anon,authenticated,service_role;
grant execute on function finance_private.period_money_package(uuid,date,date,uuid[]) to authenticated;
create function public.get_finance_period_money_package(_tenant_id uuid,_from date,_to date,_account_ids uuid[] default '{}') returns jsonb language sql stable security invoker set search_path='' as $$select finance_private.period_money_package(_tenant_id,_from,_to,_account_ids)$$;
revoke all on function public.get_finance_period_money_package(uuid,date,date,uuid[]) from public,anon,authenticated,service_role;
grant execute on function public.get_finance_period_money_package(uuid,date,date,uuid[]) to authenticated;
