-- Migration originalmente composta apenas de DML (dados de um tenant específico).
-- O conteúdo foi movido para scripts/ops/seeds/20260815021158_4dd3df95-8d92-40e5-bf3d-c65fff7d235c.sql
-- para manter o histórico de migrations reprodutível desde schema vazio.
-- Nenhuma mudança de schema: intencionalmente sem instruções.
