
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS freight_weight_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS freight_delivery_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS insurance_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS insurance_percent numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS toll_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS loading_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tracking_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gris_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_costs numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_base numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_rate numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS icms_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pis_rate numeric DEFAULT 0.65,
  ADD COLUMN IF NOT EXISTS pis_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cofins_rate numeric DEFAULT 3,
  ADD COLUMN IF NOT EXISTS cofins_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_freight numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subtotal numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS financial_value numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payer_type text DEFAULT 'CIF';
