
ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS blocked boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS in_maintenance boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS odometer_km numeric,
  ADD COLUMN IF NOT EXISTS model text,
  ADD COLUMN IF NOT EXISTS year_of_manufacture integer,
  ADD COLUMN IF NOT EXISTS brand text,
  ADD COLUMN IF NOT EXISTS capacity_ton numeric,
  ADD COLUMN IF NOT EXISTS chassis text,
  ADD COLUMN IF NOT EXISTS color text,
  ADD COLUMN IF NOT EXISTS renavam text,
  ADD COLUMN IF NOT EXISTS result_center text,
  ADD COLUMN IF NOT EXISTS result_area text,
  ADD COLUMN IF NOT EXISTS business_unit text,
  ADD COLUMN IF NOT EXISTS vehicle_type_code text,
  ADD COLUMN IF NOT EXISTS body_type_code text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS fleet_type_code text,
  ADD COLUMN IF NOT EXISTS axle_structure text,
  ADD COLUMN IF NOT EXISTS situation_code text,
  ADD COLUMN IF NOT EXISTS avg_km_per_liter numeric,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS uf text,
  ADD COLUMN IF NOT EXISTS owner_name text,
  ADD COLUMN IF NOT EXISTS owner_neighborhood text,
  ADD COLUMN IF NOT EXISTS owner_mobile text,
  ADD COLUMN IF NOT EXISTS owner_phone text,
  ADD COLUMN IF NOT EXISTS owner_notes text,
  ADD COLUMN IF NOT EXISTS tracker_name text,
  ADD COLUMN IF NOT EXISTS tracker_login text,
  ADD COLUMN IF NOT EXISTS tracker_password text;
