-- Migration originalmente composta apenas de DML (dados de um tenant específico).
-- O conteúdo foi movido para scripts/ops/seeds/20260513205409_1b15ea4d-ba4f-48e5-91a4-b5e2beca703c.sql
-- para manter o histórico de migrations reprodutível desde schema vazio.
-- Nenhuma mudança de schema: intencionalmente sem instruções.
