import {createHash} from 'node:crypto';
import type {PGlite} from '@electric-sql/pglite';
export type MovementCatalogClassification='operational_reader'|'historical_reader'|'writer'|'guard'|'needs_review';
const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
const historical=new Set(['list_movements','movement_receipt_trace','receipt_movement_trace','payable_payment_history','list_expenses','audit_events','account_period_closure_evidence','get_finance_account_period_evidence','legacy_expense_cost_snapshot','maintenance_labor_snapshot','maintenance_direct_part_snapshot','stock_acquisition_snapshot','stock_consumption_reversal_snapshot']);
const writers=new Set(['record_movement','record_expense_batch','record_manual_expense','apply_payable_movement','manage_legacy_payable_association','manage_legacy_receipt_association','project_receivable_command','process_automatic_reconciliation','record_internal_transfer','record_transfer_stage','manage_legacy_receivable_association','apply_receivable_financial_command','correct_receipt_allocation','record_settlement_payment','record_finance_settlement_payment','manage_internal_transfer','manage_transfer_departure','reconcile','reverse_reconciliation','record_statement_intake','process_reconciliation_candidates','run_automatic_reconciliation','revisit_reconciliation_candidates']);
const guards=new Set(['assert_closed_source_mutable','frozen_movement','late_payment_composition_proved','account_period_guards_ready','reconciliation_evidence_issue']);
const operational=new Set(['list_movements','movement_used_cents','receipt_movement_used_cents','account_period_review','account_period_close_snapshot','cash_period_close_snapshot','account_opening','opening_book','account_book','settlement_expense_context','canonical_trip_costs','manual_expense_movements','reconciliation_context','reconciliation_options','receipt_movement_options','payable_movement_options','expense_options','legacy_cut_manifest','legacy_cut_settlement_evidence','paid_projection_chain','payable_portfolio_evidence','legacy_payable_payment_issue','legacy_receivable_payment_issue','legacy_integrity_rows','pending_transfers','reconciliation_evidence_issue','reconciliation_snapshot_internal','frozen_movement','late_payment_composition_proved','account_period_guards_ready','assert_closed_source_mutable']);
export async function collectEffectiveMovementCatalog(db:PGlite,fixture:string){
 const functions=(await db.query<{oid:string;schema:string;name:string;identity:string;definition:string;returns:string;security_definer:boolean;volatility:string}>(`select p.oid::text,n.nspname schema,p.proname name,pg_get_function_identity_arguments(p.oid) identity,pg_get_functiondef(p.oid) definition,pg_get_function_result(p.oid) returns,p.prosecdef security_definer,p.provolatile volatility from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname not in('pg_catalog','information_schema') and p.prokind in('f','p') order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)`)).rows;
 const dependencies=(await db.query<{oid:string;dependency:string;type:string}>(`select d.objid::text oid,pg_describe_object(d.refclassid,d.refobjid,d.refobjsubid) dependency,d.deptype type from pg_depend d join pg_proc p on d.classid='pg_proc'::regclass and d.objid=p.oid join pg_namespace n on n.oid=p.pronamespace where n.nspname not in('pg_catalog','information_schema') order by d.objid,dependency,type`)).rows;
 const triggers=(await db.query<{table_name:string;name:string;function_oid:string;enabled:string;definition:string}>(`select n.nspname||'.'||c.relname table_name,t.tgname name,t.tgfoid::text function_oid,t.tgenabled enabled,pg_get_triggerdef(t.oid,true) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal order by table_name,t.tgname`)).rows;
 const refs=functions.filter(f=>/\bfinance_movements\b|\bactive_movements\b/.test(f.definition));
 const relevant=new Set(refs.map(f=>f.oid));let changed=true;while(changed){changed=false;for(const f of functions)if(!relevant.has(f.oid)&&functions.some(target=>relevant.has(target.oid)&&f.definition.includes(target.schema+'.'+target.name+'('))){relevant.add(f.oid);changed=true;}}
 const indirect=functions.filter(f=>relevant.has(f.oid)&&!refs.some(d=>d.oid===f.oid)).map(f=>({signature:f.schema+'.'+f.name+'('+f.identity+')',sha256:sha(f.definition),definition:f.definition,classification:'needs_review',basis:'transitive textual call candidate resolved against installed pg_proc; not a PostgreSQL dependency proof'}));
 const unresolvedCalls=[...new Set(functions.flatMap(f=>[...f.definition.matchAll(/finance_private\.([a-z_][a-z_0-9]*)\s*\(/g)].map(m=>m[1])).filter(name=>!functions.some(f=>f.schema==='finance_private'&&f.name===name)))].sort();
 const rows=refs.map(f=>{const associated=triggers.filter(t=>t.function_oid===f.oid);const classification:MovementCatalogClassification=writers.has(f.name)?'writer':f.returns==='trigger'||guards.has(f.name)?'guard':historical.has(f.name)?'historical_reader':operational.has(f.name)?'operational_reader':'needs_review';return{signature:`${f.schema}.${f.name}(${f.identity})`,name:f.name,classification,mixed_semantics:f.name==='list_movements'?'raw historical rows with active-only operational totals':null,classification_basis:classification==='guard'?'installed trigger return type or explicitly reviewed guard helper':'explicit reviewed name map; unknowns require review',sha256:sha(f.definition),definition:f.definition,security_definer:f.security_definer,volatility:f.volatility,pg_depend:dependencies.filter(d=>d.oid===f.oid).map(({dependency,type})=>({dependency,type})),triggers:associated.map(({function_oid:_,...t})=>({...t,sha256:sha(t.definition)})),textual_calls: functions.filter(other=>other.oid!==f.oid&&f.definition.includes(`${other.schema}.${other.name}(`)).map(other=>`${other.schema}.${other.name}(${other.identity})`)};});
 const viewDependencies=(await db.query<{name:string;dependency:string;type:string}>(`select n.nspname||'.'||c.relname name,pg_describe_object(d.refclassid,d.refobjid,d.refobjsubid) dependency,d.deptype type from pg_depend d join pg_rewrite r on d.classid='pg_rewrite'::regclass and d.objid=r.oid join pg_class c on c.oid=r.ev_class join pg_namespace n on n.oid=c.relnamespace where n.nspname not in('pg_catalog','information_schema') order by name,dependency,type`)).rows;
 const views=(await db.query<{name:string;definition:string}>(`select n.nspname||'.'||c.relname name,pg_get_viewdef(c.oid,true) definition from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind in('v','m') and n.nspname not in('pg_catalog','information_schema') order by name`)).rows.filter(v=>/\bfinance_movements\b|\bactive_movements\b/.test(v.definition)).map(v=>({...v,sha256:sha(v.definition),pg_depend:viewDependencies.filter(d=>d.name===v.name).map(({dependency,type})=>({dependency,type}))}));
 return{fixture,indirect_reference_candidates:indirect,unresolved_private_calls:unresolvedCalls,function_count:functions.length,direct_reference_count:rows.length,functions:rows,views,all_installed_signatures:functions.map(f=>`${f.schema}.${f.name}(${f.identity})`),all_triggers:triggers.map(({function_oid,...t})=>({...t,function_signature:(()=>{const f=functions.find(f=>f.oid===function_oid);return f?`${f.schema}.${f.name}(${f.identity})`:null;})(),sha256:sha(t.definition)}))};
}
