import {readFileSync} from 'node:fs';
import {createVoidAwareMonetaryProofDatabase} from './voidAwareMonetaryProofDatabase';
export async function createMovementCorrectionContextDatabase(){const db=await createVoidAwareMonetaryProofDatabase();const read=(name:string)=>readFileSync('supabase/migrations/'+name+'.sql','utf8');const baseline=read('20260824224152_baseline');
for(const table of ['driver_settlement_items'])if(!(await db.query<{v:boolean}>('select to_regclass($1) is not null v',['public.'+table])).rows[0].v)await db.exec(baseline.match(new RegExp('CREATE TABLE public\\.'+table+' \\([\\s\\S]*?\\n\\);'))![0]);
if(!(await db.query<{v:boolean}>("select to_regclass('public.finance_fiscal_receivable_origins') is not null v")).rows[0].v)await db.exec(read('20260910010034_finance_fiscal_receivable_projection').match(/create table public\.finance_fiscal_receivable_origins \([\s\S]*?\n\);/)![0].replace(/,\s*foreign key[\s\S]*?(?=\n\);)/,'').replace(/ references public\.\w+\([^)]*\)/g,''));
for(const [file,table] of [['20260909212514_finance_delivery_unloading','finance_unloading_charges'],['20260910004550_finance_fiscal_observation_queue','finance_fiscal_observations'],['20260910010034_finance_fiscal_receivable_projection','finance_fiscal_projection_events']])if(!(await db.query<{v:boolean}>('select to_regclass($1) is not null v',['public.'+table])).rows[0].v)await db.exec(read(file).match(new RegExp('create table public\\.'+table+' \\([\\s\\S]*?\\n\\);'))![0].replace(/ references public\.\w+\([^)]*\)/g,''));
await db.exec(read('20260910014238_finance_reconciliation_workspace'));
for(const [file,name] of [["20260909220020_finance_expense_workspace_queries","expense_options"],["20260910120756_finance_manual_expense_recording","manual_expense_movements"],["20260910002244_finance_payable_movement_links","payable_movement_options"],["20260910024438_finance_receivable_movement_projection","receipt_movement_options"],["20260910143920_finance_legacy_payable_association_options","legacy_payable_association"],["20260910145659_finance_legacy_receivable_association_options","legacy_receivable_association"],["20260910130921_finance_settlement_movement_options","get_settlement_payment_movements"],["20260910133355_finance_new_settlement_payment_candidates","new_settlement_payment_candidates"],["20260910002244_finance_payable_movement_links","check_movement_use"],["20260910002244_finance_payable_movement_links","check_payable_payment_insert"],["20260910130540_finance_settlement_movement_links","check_settlement_movement_link"],["20260910145616_finance_legacy_receipt_associations","check_receipt_movement_capacity"]]){const sql=read(file),start=sql.indexOf('function finance_private.'+name+'(');if(start<0)throw new Error(name);await db.exec(sql.slice(sql.lastIndexOf('create',start),sql.indexOf('$$;',start)+3).replace(/^create function/,'create or replace function'));}
// Match the real03529 predecessor: the payment guard sums active payments.
await db.exec(`do $$declare body text;needle text:='from public.payables_payments where payable_id=p.id';begin
 body:=pg_get_functiondef('finance_private.check_payable_payment_insert()'::regprocedure);
 if position(needle in body)=0 then raise exception 'fixture payable predecessor mismatch';end if;
 execute replace(body,needle,'from finance_private.active_payable_payments where payable_id=p.id');end$$;`);
for(const name of ['20260910183506_finance_active_movement_financial_guards','20260910183442_finance_reconciliation_active_movements','20260910183438_finance_active_movement_period_projections','20260910184213_finance_movement_active_reference','20260910184543_finance_active_movement_options','20260910185517_finance_movement_recording_origin','20260910190516_finance_movement_correction_context'])await db.exec(read(name));return db;}
