import {createCoordinatedUnloadingCancellationDatabase,installCoordinatedCancellation,readCancellationMigration} from './coordinatedUnloadingCancellationDatabase';
export {seedUnloadingRepairSource} from './coordinatedUnloadingCancellationDatabase';
export async function createUnloadingCostCorrectionDatabase(){return createCoordinatedUnloadingCancellationDatabase();}
export async function installUnloadingCostCorrection(db:Awaited<ReturnType<typeof createUnloadingCostCorrectionDatabase>>){await installCoordinatedCancellation(db);await db.exec(readCancellationMigration('20260911054915_finance_unloading_cancelled_claim_cost_resolution'));await db.exec(readCancellationMigration('20260911060519_finance_unloading_cost_amendments'));}
